### ISSUE TITLE
Check that we don't have unused props that we validate for no reason  (with lint rule)

### ISSUE THREAD

**Issue by lbelinsk** [wix/wix-style-react#1011]
We should have a lint rule to validate that each component prop is in Component.propTypes.

This is the relevant rule:
https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/prop-types.md

The problem is that sometimes we have this ...Input.propTypes and we need to be careful.

**Comment by shlomitc** [comment]
old issue, probably won't be fixed soon. closing
