### ISSUE TITLE
Make sure each prop is in the propTypes

### ISSUE THREAD

**Issue by lbelinsk** [wix/wix-style-react#1012]
If we were extending React.Component, then we would have been getting it by default.
The problem is that we extend WixComponent, so maybe we can add some custom lint rule.

https://flexport.engineering/writing-custom-lint-rules-for-your-picky-developers-67732afa1803

**Comment by shlomitc** [comment]
I guess this will be solved in wix-ui.
Do we want to keep this issue alive?

**Comment by shlomitc** [comment]
general infra task, closing for now
