### ISSUE TITLE
Templates for Modal

### ISSUE THREAD

**Issue by lbelinsk** [wix/wix-style-react#1017]
I talked with @wuwa and he raised a good point.
wix has a lot of complex modals, which we might be able to help by supplying some better generic template. Just like we have some messageBoxes templates, we can add some additional ones.

In order to understand more about the usages across wix, Ben suggestes to talk to dado from media-platform or with premium.

A lot of modals have scrolling inside of them, so we need to support it out of the box.
see 4.10 modal selectors in zeplin.

**Comment by shlomitc** [comment]
We'll take this into consideration when creating new templates
