### ISSUE TITLE
Need a way to use TextLink styles without the <a> tag

### ISSUE THREAD

**Issue by joncys** [wix/wix-style-react#1023]
### Summary:

I should be able to use some component styled how the `TextLink` is now styled as a button / run my custom logic on the `onClick` handler, without it automatically acting as a link. I don't really care whether that styling is a theme on the `Button` component, or you rebuild the `TextLink` to not use the `<a>` tag underneath, or provide some sort of a `<Link>` component to wrap `<Text>` (probably the best sollution), rolling own my own text links is tedious work. :(

### Priority:
- [ ] Blocker
- [ ] Urgent
- [ ] Normal
- [x] Minor

### Relevant Components:
`TextLink`

**Comment by lbelinsk** [comment]
Hey,
For this purpose we have `TextlinkLayout` and `ButtonLayout`.
See here a usage example: 
https://github.com/wix-private/account-recovery/blob/8c1570f49f1818462fba4810e068f3e7743d4c73/src/components/ForgotEmail/components/ForgotEmailFailure/ForgotEmailFailure.js#L20-L24

Is this what you had in mind?

**Comment by joncys** [comment]
@lbelinsk,

Yes, `TextlinkLayout` is exactly what I need. However, I take two issues with this:

* `TextLinkLayout` is not documented and seems to be for internal use only. If you allow using it directly, would be nice to have some documentation around it. Would also provide some sort of assurance, that the API is respected and would only change with breaking version release.
* I still have to wrap it w/ `<span onClick={} style={{userSelect: 'none'}}`. I don't really mind it (especially the `onClick`, but _maybe_ a `...Link` could have that baked in...

**Comment by lbelinsk** [comment]
1. You are 100% right. It should be documented!
2. Not sure I follow. The TexlinkLayout is simply a layout and should provide the link theme.
If you detect some generic behavior which we should have in wsr, then I will be happy to hear.

Any chance you can help with pr for the second point if we see we need it?
Will be happy to get a link for you code which uses it

**Comment by joncys** [comment]
@lbelinsk,

The more I thougth about number 2 (proxying the `onClick`), the less good of an idea it became inside my head.

**Comment by lbelinsk** [comment]
:)
So can we close this issue in favor of https://github.com/wix/wix-style-react/issues/1024 ?
