### ISSUE TITLE
GoogleAddressInput examples not working in the storybook

### ISSUE THREAD

**Issue by Roeia1** [wix/wix-style-react#1046]
### Summary:
Examples of GoogleAddressInput not working in storybook.

### Priority:
- [ ] Normal

### Steps to reproduce:
 1. Start writing in the input...

### Expected behavior:
When writing in the input it should show completion options.

**Comment by lbelinsk** [comment]
https://developers.google.com/maps/documentation/javascript/error-messages#unauthorized-url-for-client-id-map-error

![image](https://user-images.githubusercontent.com/18248989/31989952-6ac020b8-b97c-11e7-9265-a4c5639578ea.png)

**Comment by lbelinsk** [comment]
@gonengar this is the issue we talked about

**Comment by lbelinsk** [comment]
@gonengar any updates by any chance?

**Comment by shlomitc** [comment]
done, will be updated on next release
