### ISSUE TITLE
Bug with storybook tooltip max-width default value

### ISSUE THREAD

**Issue by lbelinsk** [wix/wix-style-react#1047]
Go to tooltip story:
https://wix.github.io/wix-style-react/?selectedKind=7.%20Tooltips&selectedStory=7.1.%20Tooltip&full=0&down=0&left=1&panelRight=0

You will get by deafult:
![image](https://user-images.githubusercontent.com/18248989/31966306-fb580858-b912-11e7-9dde-1328672f6f76.png)

So maxWidth isn't getting the default value it should, and the example can have a really wide tooltip which is more than the dafault max-width (204px): 

![image](https://user-images.githubusercontent.com/18248989/31966367-28486bbe-b913-11e7-8b00-101d40b0aacf.png)

**Comment by argshook** [comment]
This is old issue and the solution is to use `story.js` for tooltip documentation. 

Closing
