### ISSUE TITLE
Story dynamic components should be controlled

### ISSUE THREAD

**Issue by lbelinsk** [wix/wix-style-react#1048]
Today we want the code snippet + the props to get updated if for example a user checks the checkbox

![image](https://user-images.githubusercontent.com/18248989/31970012-4e3abf0a-b91f-11e7-8325-299d2095ab57.png)

In this example, If I check the checkbox I want it to get checked + toggle the toggleSwitch of "checked" + update the code snippet

**Comment by lbelinsk** [comment]
We can use the`makeControlled` HOC maybe: https://github.com/wix/wix-style-react/blob/master/test/utils/utils.js#L8

**Comment by argshook** [comment]
`componentProps` within `story` config is already solving this, closing
