### ISSUE TITLE
Horrible bug in dropdownLayout

### ISSUE THREAD

**Issue by lbelinsk** [wix/wix-style-react#1058]
### Summary:
Selecting an option with a mouse click is not working as expected.

### Priority:
- [x] Blocker
- [ ] Urgent
- [ ] Normal
- [ ] Minor

### Steps to reproduce:
 1. Use AutoComplete to type some text to filter some options
 2. click on some option which it's index has changed due to filtering.
 3. The wrong option got selected since selection is relative to the position instead of option id.

### Expected behavior:
Clicked option will get selected

### Additional notes:
Check Guineapig filters "Geo" of Turkey (after typing "tur")

**Comment by lbelinsk** [comment]
@alonbt

**Comment by argshook** [comment]
@alonbt i heard you also encounter this. should be fixed by now, please confirm

**Comment by alonbt** [comment]
@lbelinsk mouse issue seems to be solved
