### ISSUE TITLE
Bug in RadioButton vAlign prop

### ISSUE THREAD

**Issue by adimara** [wix/wix-style-react#1060]
### Priority:
- [ ] Blocker
- [x] Urgent
- [ ] Normal
- [ ] Minor

### Steps to reproduce:
 1. Make a radio button's label more then one line in length
 2. Use the 'top' vAlign prop

### Expected behavior:
The radio button should be aligned to the first line

**Comment by lbelinsk** [comment]
Thanks for reporting @adimara 
Any chance you have some time to help with a pr?
If not we will do our best to get to it

**Comment by adimara** [comment]
I have a few ideas but they are not the best or very exact...

**Comment by lbelinsk** [comment]
Want to share?
We can talk about it privately if you want

**Comment by lbelinsk** [comment]
We don't have guild weeks until December, so we probably won't be able to tackle this one any time soon.
If it is urgent a pr will be a great solution.
We can talk on slack about how will it be best to fix this

**Comment by Roeia1** [comment]
opened a pr about it now

**Comment by argshook** [comment]
closed by #1085
