### ISSUE TITLE
Add dock component to the library

### ISSUE THREAD

**Issue by dorg11** [wix/wix-style-react#1062]
Link to existing component in editor-ui-lib: [link](http://dev.wix.com/docs/ui-lib/ui-controls/#dock)
![image](https://user-images.githubusercontent.com/20643132/32167054-6cb51caa-bd70-11e7-84a5-fc490cabd622.png)

**Comment by lbelinsk** [comment]
@wuwa @milkyfruit We will talk about it on the next weekly

**Comment by shlomitc** [comment]
@wuwa - let's decide if we also want this component

**Comment by shlomitc** [comment]
@dorg11 - please contact me personally if you still need this component
