### ISSUE TITLE
DatePicker Uses a third party component which has some problems

### ISSUE THREAD

**Issue by lbelinsk** [wix/wix-style-react#107]
This component uses a third party library - ReactJS Datepicker  which has some issues.
https://github.com/Hacker0x01/react-datepicker

1. The year dropdown feature is pretty ugly by default. There are 2 options for the dropdown:
- **scroll**: We use this one with some additional css custom design (not final). the scroll is a bit annoying since it opens the options with the current year on top, and it is not possible to scroll up unless you click on the navigation arrow on top. scrolling down is supported.
https://github.com/Hacker0x01/react-datepicker/issues/683 - issue resolved!

- **select**: It provides a nicer scrolling flow through the options, but it opens in 100% height, and there is no class name on the select html component. Probably it will be nicer to use this option if the window will be limited in it's height.

2. I have opened an issue in the  ReactJS Datepicker repo regarding a bad keyboard navigation behaviour.
The problem we need to handle with is that we select every date on visit, without waiting for an Enter key to be clicked. it Requires some code changes in the third party component. opened an issue there:
https://github.com/Hacker0x01/react-datepicker/issues/682. -  issue resolved!

4.  Another problem with this repo is that they allow to navigate on a disabled date.
 https://github.com/Hacker0x01/react-datepicker/issues/662
We handle this problem, but this is expected to be handled by this third party component.

3. We provide a custom Input to React datepicker, and unless this Input doesn't have a focus() function (The DatePickerInput, not the Input) then an Error is triggered.
I added focus = () => {} to our customInput.
https://github.com/wix/wix-style-react/pull/106/files#diff-201c005a4e52c663980b822f93d88824R42

**Comment by emmet1982** [comment]
Hey Ibelinsk,

I am having the same issue re being able to keyboard navigate on a supposedly disabled state. You mentioned you handle this problem, can you explain your approach?

Thanks

**Comment by nirhart** [comment]
The design of this component might be ugly but at least its not broken now.
We will work further on the design after a ux review

**Comment by lbelinsk** [comment]
https://github.com/Hacker0x01/react-datepicker/issues/662#issuecomment-285477099

Problem 3 is solved in the new React DatePicker...
@nirhart

**Comment by lbelinsk** [comment]
@emmet1982 I guess I missed your question for me :(
If this issue is still relevant by any chance feel free to ask me and i will be more responsive

**Comment by lbelinsk** [comment]
Another UI issues that came up by account recovery project UX guy:
1) הכפתור של השנה נראה קצת צפוף כזה ועל הקו שמחבר את הלוח להאדר הכחול
2) אולי אפשר להצמיד את הלוח שנה יותר למעלה? שיגע בקו של השדה?

**Comment by lbelinsk** [comment]
Closing this one because we have a more updated tasks list for the next guild week track.
