### ISSUE TITLE
`<Text/>` with appearance h0 - h4 adds unnecessary margins

### ISSUE THREAD

**Issue by argshook** [wix/wix-style-react#1090]
for now, as we don't yet have themes, we decided to simply remove margins added by browser when using `<Text/>` with `apperance`s `'H0', 'H1', 'H2', 'H2.1', 'H3', 'H4'`

**Comment by lbelinsk** [comment]
Closing it as we have the new core text component with the updated typography.
@argshook if you see this issue returning in the new implementation please open an issue for it there as well in wix-ui-core

**Comment by argshook** [comment]
@lbelinsk the `<Text/>` & `<UIText/>` does not have heading styles, so no more heading tags created by `<Text/>`? if so, then there's nothing to open new issue for :)

**Comment by hepiyellow** [comment]
Related #1092
