### ISSUE TITLE
Tabs Component: List of issues

### ISSUE THREAD

**Issue by maksymc** [wix/wix-style-react#1093]
### Summary:
This ticket contains the list of issues related to Tabs component from **volodymyrk/tabs** branch. 

### Priority:
Normal

### List of issues:

**Design**
- [x] Blue bar that highlights selected tab should be displayed over the grey line & not above it. 
http://joxi.ru/Vm6leEXHxEvlWA

**Functionality**
- [x] Right / Left arrow key should switch between tabs

- [x] Focus section (from spec) of the Tabs element is not implemented
https://github.com/wix/stylable-components/blob/master/docs/tabs/tabs-spec.md#focus

- [x] If `defaultValue=none`, tabs component should still be focusable & first tab should be selected on focus

**Improvements**
- [x] Content within tabs should be focusable

**Styylable Issues**
- [ ] ::selectedTab pseudo-element is not functional (can not style tab with)
Blocked by https://core3.leankit.com/card/563451388

**Comment by lbelinsk** [comment]
@argshook is this connected to the gw task?

**Comment by argshook** [comment]
@lbelinsk doesn't look like it, @TomasRup is working on `<Tabs/>` as defined in [zeplin](https://app.zeplin.io/project/578f70936221ed4026353dd8/screen/5a0d9de770b935f7808924ef)

**Comment by shlomitc** [comment]
doesn't look relevant anymore. please re-open and explain if relevant
