### ISSUE TITLE
Colors

### ISSUE THREAD

**Issue by milkyfruit** [wix/wix-style-react#1094]
Let's update Wix Style React colors.

Reviewed colors.scss file:
- Marked which colors belong to Wix Style
- Marked deprecated / custom colors
- Linked deprecated duplicates to Wix Style colors
- Marked number of times color is used in Wix Style React Repo

The reviewed file is here:
[colors.scss.zip](https://github.com/wix/wix-style-react/files/1449187/colors.scss.zip)

**Comment by lbelinsk** [comment]
@milkyfruit this is amazing!
we will discuss it on Thursday how to deprecate + integrate it.

**Comment by wuwa** [comment]
`//==========================//
//     Wix Style Colors     //
//==========================//

/* DARK - Primary */
$D10: #162d3d;   // Primary Text
$D20: #32536A;   // Secondary Text
$D30: #577083;
$D40: #7a92a5;   // Placeholder Text
$D50: #b6c1cd;   // Disabled - Text + System Icons
$D60: #dfe5eb;   // Dividers, Disabled - Borders
$D70: #f0f4f7;   // Page Background, Disabled - Background
$D80: #ffffff;   // Content box background

/* BLUE - Brand */
$B00: #2b81cb;   // Button Focus
$B10: #3899ec;   // Main, Button
$B20: #4eb7f5;   // Hover for elements with B10, buttons, Notifications
$B30: #c1e4fe;
$B40: #daeffe;
$B50: #eaf7ff;
$B60: #f4fafe;

/* PURPLE - Premium */
$P00: #8e21b1;
$P10: #aa4dc8;
$P20: #cd68ed;
$P30: #e5c9ee;
$P40: #eedbf4;
$P50: #FAEEFF;
$P60: #FAF7FC;

/* ORANGE - Used ONLY in Labels */
$O00: #ea5f0e;
$O10: #fb7d33;
$O20: #ff9a48;

/* RED - Danger or Destructive */
$R00: #d6453d;
$R10: #ee5951;   // Main, Destructive Button
$R20: #ff6666;   // Notifications
$R30: #ffd7d7;
$R40: #ffe1e1;
$R50: #ffebeb;
$R60: #fff5f5;

/* GREEN - Success */
$G00: #44823f;
$G10: #60bc57;   // Main, Button
$G20: #80c979;   // Notifications
$G30: #c9eebc;
$G40: #DEF4D4;
$G50: #EDF9E5;
$G60: #f2fbef;

/* YELLOW - Warning */
$Y00: #c68801;
$Y10: #fdb10c;   // Notification
$Y20: #fac249;
$Y30: #fef0ba;
$Y40: #fef4cd;
$Y50: #fdf7df;
$Y60: #FFFCF0;

$TRANSPARENT: transparent;
$WHITE: #ffffff;

//==========================//
//     Semantic Colors      //
//==========================//

// main

$backgroundPrimary: $D70;
$backgroundSecondary: $WHITE;
$brandPrimary: $B10;
$brandSecondary: $D10;

$disabled:	$D50;
$focus:		$B00;

$main:		$B10;
$success:	$G10;
$warning:	$Y10;
$danger:	$R10;
$premium:	$P10;

$mainHover:		$B20;
$successHover:	$G20;
$warningHover:	$Y20;
$dangerHover:	$R20;
$premiumHover:	$P20;

$mainMuted:		$B40;
$successMuted:	$G40;
$warningMuted:	$Y40;
$dangerMuted:	$R40;
$premiumMuted:	$P40;

$mainMutedHover:	$B30;
$successMutedHover:	$G30;
$warningMutedHover:	$Y30;
$dangerMutedHover:	$R30;
$premiumMutedHover:	$P30;

// typography

$primaryText: $D10;
$secondaryText: $D20;
$placeholderText: $D40;       
$disabledText: $D50;

$linkedText: $brandPrimary;
$linkedTextHover: $brandPrimary;

$headingText: $primaryText;
$subheadingText: $secondaryText;

// layout

$cardBackground: $backgroundSecondary;
$dividerColor: $D60;

//////////////
// examples for connecting components - never directly to pallette 
//////////////

$inputBackground: $WHITE;
$inputBorderColor: $brandPrimary;
$inputColor: $primaryText;
$inputLabelColor: $secondaryText;

$primaryButton: $main;
$primaryButtonHover: $mainHover;
$primaryButtonActive: $main;
$primaryButtonFocus: $focus;

$disabledButton: $disabled;
$disabledButtonHover: $disabled;
$disabledButtonActive: $disabled;
$disabledButtonFocus: $disabled;


//======================================//
//    NOT WIX Style - Delete or Alias   //
//======================================//

// Clean up :
$D55: #cbd3dc;  // Disabled - Text - replace with $D50
$B05: #308ddd;	// unused
$R05: #d8504c;	// unused
$G05: #61ad5a;	// unused
$Y05: #eda200;	// unused

/* Product Specific Colors */
$BMCounter: #F4553F; // replace with $R10
$WR00: #e05050;      // Wix Restaurant red - replace with $R10

/*GREY - DEPRECATED Wix Style - These aren't used anymore*/
$GR10: #c8c8c8;   //used (3) $D50
$GR20: #dadada;   //used (5) $D50
$GR30: #f1f1f1;   //used (7) $D70
$GR40: $D50;      //used (1) 
$GR50: #eff1f2;	  // $D70
$GR60: #a3abb0;   //used (1) $D40;

/* Custom blue */
$B25: #A1D7FB;          // (0 results)
$B27: #b3e0fb;          // (0 results)

/* Editor Palette */

$paletteB1  : $B10;        //used (1)
$paletteB2  : $B20;
$paletteB3  : #7FCCF7;	// $B40
$paletteB4  : #D3EDFF;  //used (2) $B40
$paletteB5  : $B50;

$paletteD1  : $D10;
$paletteD2  : #2B5672;   //used (3) $D20
$paletteD3  : $D40;      //used (2)
$paletteD4  : #D9E1E8;   //used (1) $D60
$paletteD5  : #F0F3F5;   //$D70
$paletteD6  : $D80;

$paletteE1  : $B00;         //used (1)
$paletteE2  : #0D487F;
$paletteE3  : rgba(255,255,255,0.96);
$paletteE4  : #2D4150;
$paletteE5  : #B1DDf8;   //used (1) $B30
$paletteE6  : #B6C1CD;   //used (2) $D50
$paletteE7  : #5EFFFF;
$paletteE8  : #18D2DE;

$paletteP1  : $P10
$paletteP2  : #BB71D3;	//	$P20
$paletteP3  : $P30
$paletteP4  : $P40

$paletteG1  : $G10;         //used (2)
$paletteG2  : $G20;         //used (1)
$paletteG3  : #CFEBCC;
$paletteG4  : #DFF2DD;

$paletteO1  : $O10;
$paletteO2  : #FC975C;
$paletteO3  : #FED8C1;
$paletteO4  : #FEE5D6;

$paletteY1  : #FFC233;   //used (1) $Y20
$paletteY2  : #FFCE5C;
$paletteY3  : #FFEDC1;
$paletteY4  : #FFF3D6;

$paletteR1  : $R10;         //used (5)
$paletteR2  : #F1726B;
$paletteR3  : #FACDCA;
$paletteR4  : #FCE6E5;   //used (2) $R40

// Files in which these colors are used: https://github.com/wix/wix-style-react/search?utf8=%E2%9C%93&q=%24palette&type=`

**Comment by shlomitc** [comment]
Colors should be fixed now, but the semantic namings are not yet defined.
I suggest closing this issue and open it again when we have a solid understanding how this mapping should be done
