### ISSUE TITLE
Breadcrumbs

### ISSUE THREAD

**Issue by lbelinsk** [wix/wix-style-react#1110]
- [x] Remove the blue border when an item is focused.
- [x] change the current page font style to: T4 / T4.2 for dark BG

**Comment by amiryonatan** [comment]
@wuwa Hey,
I'm missing one more state, what should be the color for large and with dark background ? right now it's T4.2 but it's the same as the non-active items.

**Comment by wuwa** [comment]
it's 4.2 for dark BG

**Comment by amiryonatan** [comment]
but what about large size breadcrumbs ? with 4.2 the text is small

**Comment by amiryonatan** [comment]
![screen shot 2017-11-21 at 14 22 04](https://user-images.githubusercontent.com/8499532/33072259-68ba8fdc-cec7-11e7-989a-e5d263c09916.png)

**Comment by wuwa** [comment]
T2.2 for dark large / T2 for light large

**Comment by amiryonatan** [comment]
👍

**Comment by amiryonatan** [comment]
Fixed

**Comment by lbelinsk** [comment]
@wuwa we will release a new version tomorrow, so you can check that breadcrumbs is fixed
