### ISSUE TITLE
DatePicker moment value support

### ISSUE THREAD

**Issue by lbelinsk** [wix/wix-style-react#1111]
The auto-generated code should display the relevant format for the value prop
![image](https://user-images.githubusercontent.com/18248989/32622624-2380c29a-c58c-11e7-8706-c74b7fc4672a.png)

The value is "Mon Nov 20..."

**Comment by argshook** [comment]
closing, at the moment `wix-storybook-utils` takes care of moment value and displays it according to the `dateFormat` prop
