### ISSUE TITLE
Popover/Tooltip - allow size change without changing the arrow position

### ISSUE THREAD

**Issue by wuwa** [wix/wix-style-react#1122]
there are cases when popover content grows dynamically when open. arrow should remain in fixed location relative to button that opened it
- [ ] arrow behavior on content change

**Comment by shlomitc** [comment]
This is an old issue and the new `Popover` component solves this issue
Please verify here and re-open if there are any issues
https://wix-wix-style-react.surge.sh/?selectedKind=Components&selectedStory=Popover&full=0&addons=0&stories=1&panelRight=0
