### ISSUE TITLE
Loader

### ISSUE THREAD

**Issue by wuwa** [wix/wix-style-react#1123]
- [ ] update loaders according to [design](https://zpl.io/V1yWzz5) (ronen s. from wix OS developed some of them already)

**Comment by boriskor** [comment]
@wuwa, is the text below the Loader considered to be a part of this component, like in the [previous implementation](https://wix.github.io/wix-style-react/?selectedKind=Core&selectedStory=Loader&full=0&down=0&left=1&panelRight=0)?

**Comment by lbelinsk** [comment]
I guess it does. Must it always be Capital letters? what are the legal typographies for it?
