### ISSUE TITLE
2.2a Card Bottom Paddings

### ISSUE THREAD

**Issue by milkyfruit** [wix/wix-style-react#1125]
Something's wrong with 2.2a Card Paddings:
https://wix.github.io/wix-style-react/?selectedKind=Common&selectedStory=Grid%20with%20card%20layout&full=0&down=0&left=1&panelRight=0&downPanel=kadirahq%2Fstorybook-addon-actions%2Factions-panel

It should be 30px bottom paddings. While in demo examples it's 18px + 30px margins for text field.

Does the 30px margin is part of a card or is set manually?

### Design Guidelines
https://zpl.io/aX6zXP2

**Comment by yaronaz** [comment]
Margin is caused by last child of row element inside content - last child shouldn't have bottom margins

**Comment by shlomitc** [comment]
https://github.com/wix/wix-style-react/pull/1466

**Comment by shlomitc** [comment]
This is fixed and released already. please re-open if you see any issues
