### ISSUE TITLE
Popover jumping

### ISSUE THREAD

**Issue by alexk0ch** [wix/wix-style-react#1129]
### Priority:
- [ ] Blocker
- [ ] Urgent
- [X] Normal
- [ ] Minor

### Steps to reproduce:
For a popover:
 1. Go to https://wix.github.io/wix-style-react/?selectedKind=7.%20Tooltips&selectedStory=7.2.%20Popover&full=0&down=0&left=1&panelRight=0
 2. Click on 'Click Me' button
 3. Keep an eye on an empty space below 'Max Width' input field
 4. Appears that tooltip is rendered below input, and then it jumps to proper position (in a fraction of a second).

### Expected behavior:
Tooltip is not rendered in viewport prior being placed/animated in proper position. 

### Relevant Components:
Popover or Tooltip

### Additional notes:
https://drive.google.com/open?id=1m49Flvc-3f-AAI0j2TvstrSKrMBf0ZXJ - slow-motion video

**Comment by lbelinsk** [comment]
@shahafan this is caused due to this pr: https://github.com/wix/wix-style-react/commit/3414911db2a63f14c44c79abf0afd45ab19b0dd1

I would have to investigate, and if needed I will revert it.
Would prefer to talk with you about it to make sure I don't break you.
How can I reach you?

**Comment by shahafan** [comment]
You can revert it.
I haven't updated to 16 yet..
It won't work on 16 without it though cuz it can't find the element #865
I think you can refactor with the createPortal

**Comment by lbelinsk** [comment]
We started to work with semver so we will be able to release a breaking version when we will migrate to react 16 (in our plan). 
Just to know, are you not from Wix?

**Comment by shahafan** [comment]
No, I'm from orderaprint, the Art Store print provider

**Comment by lbelinsk** [comment]
Nice :)
Any chance I can see any component in production that you are using?

**Comment by shahafan** [comment]
Sure, just add the wix art store to your site, choose orderaprint as your provider and you'll see a lot of them.

**Comment by lbelinsk** [comment]
tried it out.. is it only in the first screenshot?

![image](https://user-images.githubusercontent.com/18248989/32915277-001954ee-cb21-11e7-8a60-c0be50f4109e.png)


![image](https://user-images.githubusercontent.com/18248989/32915218-d146c642-cb20-11e7-9b37-9c47c8a7231d.png)

![image](https://user-images.githubusercontent.com/18248989/32915246-e54d0cbe-cb20-11e7-8ac4-8397081c89dd.png)

**Comment by shahafan** [comment]
cool, the first one and the last one too, the second one isn't, you can see by the iframe url, it's progallery.orderaprint.com

**Comment by lbelinsk** [comment]
thanks :)
created a pr that reverts the change you made.
Hopefully we will upgrade to react 16 soon.
have a nice weekend!

**Comment by shahafan** [comment]
Cool, sorry for that, i was just doing a temp fix so it won't fail on 16.

**Comment by lbelinsk** [comment]
Nothing to be sorry about! pr's are always welcome :)
