### ISSUE TITLE
Button component

### ISSUE THREAD

**Issue by Shaniko** [wix/wix-style-react#113]
![screen shot 2017-01-03 at 12 12 23](https://cloud.githubusercontent.com/assets/15773988/21604825/08d64ae6-d1ae-11e6-8dba-2b860961548c.png)

Hi,
Please find screenshot attached.

It would be great if you could please add the attached styles to the  **wix-style-react** buttons library, **Disabled** state included. 

We would like to have:
1 - Additional styling for the **Secondary design**.
2 - Animation for the **Primary** button. (both *.app & *.mov => inside the attached **saveAnimation** zipped file)
[saveAnimation.zip](https://github.com/wix/wix-style-react/files/682074/saveAnimation.zip)

Thank you, 
Shani

**Comment by 3LOK** [comment]
Done.
