### ISSUE TITLE
Dropdown fine tuning for selected items and long items

### ISSUE THREAD

**Issue by wuwa** [wix/wix-style-react#1132]
- [ ] Add minWidth/maxWidth as defined [here](https://zpl.io/a87Zo6V) including defaults
- [ ] Option line should break into more lines
- [ ] Selected option should be truncated (this works I think)

**Comment by shlomitc** [comment]
a more detailed and up-to-date discussion can be found here
https://github.com/wix/wix-style-react/issues/3093
