### ISSUE TITLE
Text Area's Error Icon

### ISSUE THREAD

**Issue by milkyfruit** [wix/wix-style-react#1144]
InputArea uses wrong error icon:
https://wix.github.io/wix-style-react/?selectedKind=Core&selectedStory=InputArea&full=0&down=0&left=1&panelRight=0

[3.2a Text Area](https://wix.github.io/wix-style-react/?selectedKind=3.%20Inputs&selectedStory=3.2%20Text%20Area&full=0&down=0&left=1&panelRight=0) misses "error" property

[3.2 Specs](zpl.io/2y17RmG)

[3.1 Text Field](https://wix.github.io/wix-style-react/?selectedKind=3.%20Inputs&selectedStory=3.1%20Text%20Field&full=0&down=0&left=1&panelRight=0) misses this property as well

[3.1 Specs](zpl.io/2Edj3jv)

Error SVG Icon:
https://drive.google.com/a/wix.com/file/d/0B3MbBTg6Smtray16V2VtNjhhWUk/view?usp=sharing

**Comment by smokokoi** [comment]
@milkyfruit  - do you approve this fix UI wise?


![screen shot 2017-11-26 at 15 07 46](https://user-images.githubusercontent.com/29129957/33240236-b85066a0-d2bb-11e7-859b-6ca5c1265bda.png)
![screen shot 2017-11-26 at 15 07 31](https://user-images.githubusercontent.com/29129957/33240237-b86c9afa-d2bb-11e7-979c-0d89cd5bba06.png)

**Comment by milkyfruit** [comment]
Yes, now the icon looks good.

**Comment by shlomitc** [comment]
@milkyfruit so I see the icon is correct.

So now the `TextField` and `TextArea` composites are missing the error state?
Only in the storybook or also for users?

**Comment by milkyfruit** [comment]
@shlomitc Only the story book there's no way to test it. I haven't received any complaints from products.

**Comment by shlomitc** [comment]
Can be seen it in the TextArea component. just tick `error`
https://wix.github.io/wix-style-react/?selectedKind=3.%20Inputs&selectedStory=3.2b%20%2B%20RichTextArea&full=0&addons=0&stories=1&panelRight=0

As discussed, TextArea composite will be a more simple representation of the composition, so no need to display it in both.
