### ISSUE TITLE
Modal component not always closed on the first overlay click when opened from dropDownLayout

### ISSUE THREAD

**Issue by mennyWix** [wix/wix-style-react#1146]
### Summary:
Modal component that is being rendered as a result of selecting an item in DropDownLayout isn't always closed on first overlay click.

### Priority:
- [ ] Blocker
- [X] Urgent
- [ ] Normal
- [ ] Minor

### Steps to reproduce:
 1. Create a DropDownLayout 
 2. Open a Modal component as a result of selecting an item in the DropDownLayout. Send shouldCloseOnOverlayClick={true}  onRequestClose props to Modal component
 3. Click on the overlay - Modal component will not always closed on first click. Click again to close the component.

### Expected behavior:
Modal panel should be closed on the first overlay click

### Relevant Components:
a combination of DropDownLayout and Modal

### Additional notes:
Menu item is selected in DropDownLayout as a result of a mouse down. When a modal panel is rendered by selecting an item in dropDownLayout, overlay click isn't responding the first time.
It happens because react-modal enters a state in mouse-up that prevents from closing on overlay click...

Please note that DropDownLayout was changed to select on mouseDown in case of click event on 3.11.17 as a result of issue #1058 (https://github.com/wix/wix-style-react/issues/1058)

**Comment by shlomitc** [comment]
It's quite an old issue so I'm not sure how relevant it is.
anyway, if it still matters, please re-open and add a reproducible example
