### ISSUE TITLE
missing dropdown design

### ISSUE THREAD

**Issue by mariafeldman** [wix/wix-style-react#1149]
### Summary:
There is a design for stats widget for home page https://app.zeplin.io/project/585f883853431dfd15e71c74/screen/5a12c50c5a966aad3daf0837

which contains type of dropdown, which is missing now.

### Priority:
- [ ] Urgent

It blocks us for finishing stats widget

### Additional notes:
If you don't have permission for this project in zeplin ask **Ayelet Reuveni**. Also she knows how exactly dropdown should look

**Comment by lbelinsk** [comment]
@mariafeldman can you invite me to the zeplin?
liorbe@wix.com

**Comment by milkyfruit** [comment]
@mariafeldman please add these guys to zeplin as well: arijuss@wix.com, benb@wix.com, domasm@wix.com

**Comment by argshook** [comment]
@mariafeldman you talk about dropdown in card header? If so, `<CardHeader/>` supports `suffix` prop where you can put a dropdown in. Does it not work for you?

**Comment by milkyfruit** [comment]
If we are talking about this element:
![screen shot 2017-11-21 at 10 20 04](https://user-images.githubusercontent.com/1684587/33062225-3b46ba46-cea7-11e7-9c4a-e268673d44ae.png)

Then in the mock it looks like a ["5.2a + Suffix icon"](zpl.io/V0PJBdE) button. Buttons are intended for links and actions.

So, not to confuse, I would suggest using 4.1 Dropdown without a border. We have designed this variation, it's just not developed.

Technically, no border dropdown has the same paddings as a regular one, only has different hover styles.

**4.1 Dropdown + No Border:**
zpl.io/V1Mq4Qw
Specs:
zpl.io/aBwq8vO
