### ISSUE TITLE
Autocomplete field is refocusing on the field after select when involving redux action after selecting

### ISSUE THREAD

**Issue by alonbt** [wix/wix-style-react#1160]
### Priority:
- [ ] Blocker
- [x] Urgent
- [ ] Normal
- [ ] Minor

### Steps to reproduce:
1. set this experiment to true: specs.wos.DisplayCurrencyInBusinessSettings on wix.com
2. go to settings page in business-manager: `https://www.wix.com/business-manager/PUT_YOUR_SITE_ID_HERE/settings?debug`
3. scroll to the bottom of the page
4. select something from the currency autocomplete field and confirm the modal

5. expected: modal should close after confirm and that's it | actual: the field is auto-focusing for some weird reason after modal is closed

6. you can see that it doesn’t happen to all the other autocompletes there
7. The only difference in this field from other fields is that I trigger a redux action on the `onSelect` method https://github.com/wix-private/business-settings/blob/master/src/client/components/formComponents/dropdowns/AbstractAutocomplete/AbstractAutocomplete.tsx#L35

**Comment by argshook** [comment]
hello! this behaviour comes from `react-modal`, it tries to restore focus after modal has closed:

https://github.com/reactjs/react-modal/blob/v2.4.1/src/components/ModalPortal.js#L142-L145

this is controllable in latest `react-modal` release but, well, wix-style-react currently uses older one.

to circumvent, maybe you can try to use `ref` on `AutoComplete` and then `onSelect` also call `ref.blur()`, just before you do `this.props.beforeSelect();`. Then there should be nothing to return focus to and issue should be gone.

Please let me know if this works for you. We will anyway look into this but it will take time

**Comment by shlomitc** [comment]
WSR v3.1.3. contains the latest version `react-modal`.
https://github.com/wix/wix-style-react/blob/master/CHANGELOG.md#313---2018-04-11

Is this issue still happening?

**Comment by shlomitc** [comment]
closing for now. if still relevant, please re-open
