### ISSUE TITLE
ModalSelector Missing features

### ISSUE THREAD

**Issue by lbelinsk** [wix/wix-style-react#1163]
- [ ] Loader should not be configurable
- [ ] Change API  (no chidren prop)
- [ ] Empty state should be of node type
- [ ] Empty state for no results found
- [ ] Bottom Loader for pagination (not configurable)
- [ ] Text for loaders
- [ ] Configure Loading text (default "...Loading")
- [ ] Auto filtering (default predicate)
- [ ] Sub components: Filter, Item

**Comment by sdoomz** [comment]
@lbelinsk what is ETA for this component? We need exactly the same component for blitz

**Comment by lbelinsk** [comment]
No progress that I am aware of?
@boriskor any chance you started something there?

**Comment by boriskor** [comment]
Will be done this week, hopefully.

**Comment by shlomitc** [comment]
done
