### ISSUE TITLE
Badge

### ISSUE THREAD

**Issue by lbelinsk** [wix/wix-style-react#1165]
- [ ] Border radius should be 2px
- [ ] strict typography

@boriskor

**Comment by shlomitc** [comment]
Implement a Badge with transparent background and no borders and prefix/suffix icon.
@wuwa

**Comment by argshook** [comment]
@shlomitc why strict? Let's set default appearance to `T5` (from current `H4`). If user wants to change it, let them change it. We already have approved appearances so why do we need small, big etc variations?

**Comment by shlomitc** [comment]
@argshook - This is according a talk we had with Ben this morning and the design. Sizes should be defined.

**Comment by lbelinsk** [comment]
Done in wix-ui-backoffice
