### ISSUE TITLE
Stretchable Search

### ISSUE THREAD

**Issue by lbelinsk** [wix/wix-style-react#1168]
- [ ] See what Video team has.
- [ ] Api: if `standardWidth` or `focusedWith` are not given, width is 100%
- [ ] If `standardWidth` is given, this is the width
- [ ] sizes are oneOf(['small', 'medium', 'large'])

**Comment by lbelinsk** [comment]
http://recordit.co/0a3PiikMoS

**Comment by wuwa** [comment]
@boriskor width should be given with pixels, no "small" "medium" "large" in this case

**Comment by shlomitc** [comment]
@wuwa - is this a new component/composite or extra functionality over the `Search` component?

**Comment by shlomitc** [comment]
decision - should be a feature in the existing component

**Comment by lbelinsk** [comment]
Done by https://github.com/wix/wix-style-react/pull/1795
