### ISSUE TITLE
Composing drivers for complex components

### ISSUE THREAD

**Issue by lbelinsk** [wix/wix-style-react#1173]
For components with composite driver such as ButtonWithOptions and StatsWidget which has a complex driver object, we can't use those drivers in the unit tests. Instead we have to use the driverFactory.

For example here we can't use the testkitFactory, we must use the driverFactory:
https://github.com/wix/wix-style-react/pull/1167/files#diff-a8b046a02353d1e33444ce40252bad60R11

We had to locate it with data-hook ourselves, not to use the testkit locator infrastructure.

When we did try to import the testkitFactory, the tests just failed. only because of an import!?!
This needs to get a proper investigation and to be fixed.

Same here:
https://github.com/wix/wix-style-react/blob/master/src/ButtonWithOptions/ButtonWithOptions.driver.js#L8-L11

@mariafeldman

**Comment by boriskor** [comment]
I stumbled upon it too... I think it's related to the circular imports:

I tried to use a `textTestkitFactory` inside a `Loader.driver.js`:
```
import {textTestkitFactory} from '../../testkit';
```

But in `testkit/index.js`, there is a following code:
```
import loaderDriverFactory from '../src/Loader/Loader.driver';
export const loaderTestkitFactory = testkitFactoryCreator(loaderDriverFactory);
```

So, there is an import from `testkit/index.js` to `Loader.driver.js` & 
an import from `Loader.driver.js` to `testkit/index.js` — one of these imports is resolved as an empty object.

I've overcome this by using `testkitFactoryCreator` [again in my driver](https://github.com/wix/wix-style-react/blob/84157715b0454f5b8a0173515d93d88ee7e323cf/src/Loader/Loader.driver.js#L8).

WDYT?

**Comment by lbelinsk** [comment]
Yeah, looks like you found the issue here.
We actually need to change this `testkit/enzyme` file because tree shaking is not working and it means that if you import `textTestkitFactory` from `testkit/enzyme` you will get all the testkits of in the library.

We need to think about a better strategy.
Either we wait for webpack 4 pure modules or we can use [import-path](https://github.com/wix/import-path) for it.

@argshook @shlomitc just pointing this out, we don't want to have this problem in `wix-ui`.
Thanks @boriskor this is indeed solving what the issue is talking about.
I am not sure how we can prevent this from happening to someone else in the future, now that we know what is causing this. any ideas?

**Comment by lbelinsk** [comment]
@yardnsm FYI.
Try to see if there is a solution for this while you are refactoring

**Comment by shlomitc** [comment]
We did the tree shaking for drivers so it works as expected.
`createDriver` is actually responsible for both mounting and creating an instance of the driver, so it doesn't make sense to use it if we already have a rendered component.

I think Boris's solution is ok in general.

**Comment by shlomitc** [comment]
old issue, closing
