### ISSUE TITLE
GoogleAddressInput

### ISSUE THREAD

**Issue by lbelinsk** [wix/wix-style-react#118]
- [x] Add readOnly prop for the input

- [x] Instead of using this.refs it is recommended to use the ref callback pattern.

- [x] Instead of importing lodash, import each function separately.

- [ ] The component tries to support an Uncontrolled mode also. Is there any reason for that?

- [ ] StoryBook warnings:

<img width="1440" alt="screen shot 2017-01-03 at 7 49 37 pm" src="https://cloud.githubusercontent.com/assets/18248989/21617255/e928daac-d1ed-11e6-8dac-25cc7d738084.png">

**Comment by nirhart** [comment]
Fixed
