### ISSUE TITLE
error icon in Input sometimes looks wrong

### ISSUE THREAD

**Issue by smokokoi** [wix/wix-style-react#1195]
Open storybook and see different icons. 

cc: @lbelinsk 

![error_icons_thick_bug](https://user-images.githubusercontent.com/29129957/33273637-97461140-d396-11e7-9850-2bcf72ebb8d9.png)

**Comment by shlomitc** [comment]
Looks ok in the storybook

![image](https://user-images.githubusercontent.com/6093192/36351781-6f356220-14b7-11e8-9a96-8c66d911c113.png)

please reopen if it's not ok
