### ISSUE TITLE
"4.1 Dropdown + No Border" Variation

### ISSUE THREAD

**Issue by milkyfruit** [wix/wix-style-react#1200]
Wix Events needs a ["No Border"](https://zpl.io/aBwq8vO) variation for ["4.1 Dropdown"](https://wix.github.io/wix-style-react/?selectedKind=4.%20Selection&selectedStory=4.1%20Dropdown&full=0&down=0&left=1&panelRight=0&downPanel=kadirahq%2Fstorybook-addon-actions%2Factions-panel) component.

Additionally, the dropdown list needs to support a responsive behaviour based [on its position](https://zpl.io/aNE8eqQ) - it'll be used inside of a modal's corner.

#993

**Comment by milkyfruit** [comment]
#993

**Comment by lbelinsk** [comment]
related to #1149

**Comment by lbelinsk** [comment]
@argshook don't forget to close this when the gw finishes

**Comment by lbelinsk** [comment]
@argshook Done?

**Comment by argshook** [comment]
@lbelinsk yes done and i forgot to close as expected :)
