### ISSUE TITLE
DropDownLayout throes an exception when having a specific options combination

### ISSUE THREAD

**Issue by mennyWix** [wix/wix-style-react#1209]
### Summary:
DropDownLayout throes an exception when having a specific options combination -
1. Option with a conditional disabled option (taken from a props to make it render with different values)
2. Option with an icon...

### Priority:
- [ X] Blocker
- [ ] Urgent
- [ ] Normal
- [ ] Minor

### Steps to reproduce:
 1. Implement a component with ButtonWithOptions or IconWIthOptions as mentioned below
 2. The disabled value is injected via props. 
 3. First render - works well. Second render with different disable props - throws an exception.

import {Close} from 'wix-style-react/Icons;
const x = this.props.optionsDisabled

        <ButtonWithOptions
          closeOnSelect
          height="medium"
          itemHeight="small"
          maxHeightPixels={260}
          onChange={function () {}}
          onSelect={function () {}}
          options={[]}
          restrainDropdownSize
          selectedHighlight
          selectedId={-1}
          style={{
            padding: '0 5px'
          }}
          tabIndex={0}
          text="Click On Me"
          theme={undefined}
          >
          <ButtonWithOptions.Button
            height="medium"
            theme="fullblue"
            >
            Click On Me
          </ButtonWithOptions.Button>
          <ButtonWithOptions.Option id="1" disabled>
            Option 1
          </ButtonWithOptions.Option>
          <ButtonWithOptions.Option
            id="2"
            disabled={x}
            >
            Option 2
          </ButtonWithOptions.Option>

          <ButtonWithOptions.Option id="4">
            <Close size="12px"/>
            Option 4
          </ButtonWithOptions.Option>

        </ButtonWithOptions>

### Relevant Components:
ButtonWithOptions, conWIthOptions

**Comment by Wo1v3r** [comment]
@mennyWix 
Managed to reproduce your issue.

It seems each option should have one element e.g;
          <ButtonWithOptions.Option id="2">
             <div>
              <Close size="12px"/>
              Option 2
            </div>
          </ButtonWithOptions.Option>

This solves your issue (at least on my end) , I'll talk with Lior about it to see if that's the expected behavior.
