### ISSUE TITLE
noRightBorderRadius propType has conflicts (boolean vs string)

### ISSUE THREAD

**Issue by alonbt** [wix/wix-style-react#1212]
noRightBorderRadius is defined here as a string: https://github.com/wix/wix-style-react/blob/2b2472eaf7e71bbd96398ff43941a50b4897201d/src/Input/Input.js#L305

it is being used as a boolean here: https://github.com/wix/wix-style-react/blob/100fa6e60aa80ad128f2caf94e5cd103e9db7058/src/Composite/FieldWithSelectionComposite/FieldWithSelectionComposite.js#L66

This causes React to throw warnings.

I assume you just need to fix the type from string to boolean and it will solve the case. 

Priority: Normal

**Comment by argshook** [comment]
@alonbt yes, that's a mistake. Thanks for reporting!
