### ISSUE TITLE
Don't show empty values in the generated code

### ISSUE THREAD

**Issue by lbelinsk** [wix/wix-style-react#1216]
### Priority:
- [ ] Blocker
- [ ] Urgent
- [ ] Normal
- [x] Minor

### Steps to reproduce:
 1. go to dataPicker storybook
![image](https://user-images.githubusercontent.com/18248989/33480966-28c7bb62-d69b-11e7-81f7-8b65d93e5c54.png)

 2. insert noRightBorderRadius
![image](https://user-images.githubusercontent.com/18248989/33480961-242352ec-d69b-11e7-94be-97fb1fab231b.png)
![image](https://user-images.githubusercontent.com/18248989/33480984-3674546e-d69b-11e7-9e57-66d7b6530abf.png)

 3. Clean the value of noRightBorderRadius
![image](https://user-images.githubusercontent.com/18248989/33480997-42ba00e8-d69b-11e7-9f59-b12709e9b992.png)

### Expected behavior:
The autoGenerated code should not have noRightBorderRadius="" redundant property

**Comment by shlomitc** [comment]
low priority and not relevant to this repo. closing
