### ISSUE TITLE
3.8 Tags Input

### ISSUE THREAD

**Issue by wuwa** [wix/wix-style-react#1222]
- [ ] Change input to have a NON-autocomplete version
- [ ] Add click outside behavior to convert entered text (any text, also partial) to tag
- [ ] In case of controlled list - click outside to convert text to tag only if from list

**Comment by lbelinsk** [comment]
user should be able to save the tag by clicking anywhere outside the field, alongside with what exists today (saving by clicking 'enter' or 'comma').

**Comment by vidmantas0010** [comment]
Clarification:
1. build a version where user can write any text as tag (no suggestion, no predefined list)
2. blur would work the same as enter (for autocomplete version would add first match from list, for non autocomplete add whatever user entered)

**Comment by argshook** [comment]
closing because #1292 & #1316 fixes this.

please reopen if they don't
