### ISSUE TITLE
12.1 Badge + 12.3 Counter Badge

### ISSUE THREAD

**Issue by wuwa** [wix/wix-style-react#1230]
- [ ] Separate rectangle vs ellipse options into 2 components - rectangle = badges, ellipse = counter [specs](https://zpl.io/a7GjPPq)
- [ ] Variations are only Solid / Outline / Transparent
- [ ] Include prefix / suffix icon option
- [ ] Fix Badge font sizes - only T5.1 for solid / T5 for Outlines/Transparent

**Comment by rokasmik** [comment]
@wuwa What is the "prefix / suffix" option?
For the counterbadge, should we always use T5?

**Comment by wuwa** [comment]
prefix/suffix can be seen here at the bottom, use only arrow system icon: https://zpl.io/Vq1d3Qm
for counter - yes only T5, appearance is only colors

**Comment by lbelinsk** [comment]
Done in wix-ui-backoffice
