### ISSUE TITLE
Page Header issues

### ISSUE THREAD

**Issue by lbelinsk** [wix/wix-style-react#1237]
##placeholder for all issues

**Comment by aarnoldaas** [comment]
## Page Header should have max-width prop for container that wraps Title, Breadcrumbs and Actions.
### Some verticals don't have responsive behavior (wrapping header to wix-container doesn't fit us 
for now)
### Title should align with content
![screen shot 2017-12-08 at 17 18 20](https://user-images.githubusercontent.com/9351975/33772464-6505a18c-dc3d-11e7-92c2-43ed1dffdd7e.png)

## I was unable to add Tabs component to Page to match design
Design:
![screen shot 2017-12-08 at 17 25 21](https://user-images.githubusercontent.com/9351975/33772289-cc5cc6d6-dc3c-11e7-843b-3cb6988b50c5.png)
### Transparent behavior on scroll.
### All tab items have spacing from the left (I added -margin to parent but it is hack)

**Comment by shlomitc** [comment]
@amiryonatan - is the above issue resolved?

**Comment by shlomitc** [comment]
Great. If other issues will be raised, let's open a new issue.
