### ISSUE TITLE
TextField warning

### ISSUE THREAD

**Issue by aarnoldaas** [wix/wix-style-react#1239]
### Summary:
TextField shoots warning when used with TimePicker, DatePicker and CustomComponent that controls wix-style-react component.

### Priority:
Minor

### Steps to reproduce:
          <TextField>
            <Label>{ timeLabel }</Label>
            <TimePicker onChange={ this.onStartTimeChange }
                        defaultValue={ value }
                        disableAmPm={ disableAmPm }/>
          </TextField>

### Expected behavior:
No warning.

### Relevant Components:
TextField, TimePicker, DatePicker

**Comment by lbelinsk** [comment]
Good point.
Instead of haveing different component for each Input (dropdown, autocomplete, ...) we should have one composite that should get the following children:

1. optional Label
2. Mandatory Input / Dropdown / TimeInput ....

@wuwa is there any Input type that should not come with the same padding?

**Comment by shlomitc** [comment]
Or maybe we should just create more composites for these use cases? @wuwa

**Comment by shlomitc** [comment]
after discussing with @wuwua, should probably add support to this composite and not create new one

**Comment by shlomitc** [comment]
A `TimePicker` composition is not documented yet in the storybook docs but can be achieved using the `FormField` component.
https://wix-wix-style-react.surge.sh/?selectedKind=Components&selectedStory=FormField&full=0&addons=0&stories=1&panelRight=0

Feel free to try it out and tell me if it works for you.
Thanks
