### ISSUE TITLE
Google Address Input should check not to setState when the component is unmounted

### ISSUE THREAD

**Issue by lbelinsk** [wix/wix-style-react#1240]
This component has async stuff.
Once you start the async method, the component might get unmounted, and once the async operation ends, the callback with the `setState`, we might end up doing setState on an unmounted component.

We should add a condition to the callback to check whether the component is still in the dom or not.

**Comment by lbelinsk** [comment]
@gonengar will it be possible to fix this on the fly while you are touching this component?

**Comment by shlomitc** [comment]
couldn't reproduce, closing until pops again
