### ISSUE TITLE
Implementing a form using Container component inside MessageBoxFunctionalLayout component, generates a UI that its content width exceeds the dialog's width

### ISSUE THREAD

**Issue by mennyWix** [wix/wix-style-react#1244]
### Summary:
Implementing a form using Container component inside MessageBoxFunctionalLayout component, generates a UI that its content width exceeds the width's dialog
![withminwidth](https://user-images.githubusercontent.com/28685657/33804157-c16b1a4a-dda7-11e7-8fd6-46fed696255d.png)
![withoutminwidth](https://user-images.githubusercontent.com/28685657/33804158-c3728792-dda7-11e7-849c-bbbbf81b6202.png)

### Priority:
- [ ] Blocker
- [X] Urgent
- [ ] Normal
- [ ] Minor

### Steps to reproduce:
 1. Render MessageBoxFunctionalLayout with a Container as its children
 2.
 3.

### Expected behavior:
Expected to have a container width the same as MessageBoxFunctionalLayout, but the Container width exceeds the MessageBoxFunctionalLayout - see attached images

### Relevant Components:
MessageBoxFunctionalLayout, Container

### Additional notes:
This problem was found while using these components in codeEmbed application.
Current workaround is to unset min-width inside container

**Comment by shlomitc** [comment]
@wuwa - what should be done in such case?
The `Grid` has a minimum width which is bigger than the `MessageBoxFunctionlLayout` size (600px)

**Comment by wuwa** [comment]
grid inside the box should have width 100%

**Comment by shlomitc** [comment]
The reason for that is that the `Container` component should not be used for the internal grid, but only for the entire page layout.

As `Card` usually contain forms, `<Card.Content/>` is responsible for the layout and padding.
Using it in this component doesn't make sense as it will add padding (and there is already padding in the `MessageBoxFunctionlLayout` component), so we need a similar component that knows how to the internal layout without padding.

We will soon handle all Grid issues and will focus on this one as well

**Comment by shlomitc** [comment]
BTW - removing the padding from `MessageBoxFunctionlLayout` is possible by passing the `noBodyPadding` flag.
