### ISSUE TITLE
Add CheckboxGroup composite

### ISSUE THREAD

**Issue by lbelinsk** [wix/wix-style-react#1250]
Similar to RadioGroup

**Comment by lbelinsk** [comment]
@shlomitc @argshook wdyt, do we need this or not?
We can use VBox :)

**Comment by shlomitc** [comment]
On the one hand - It's a nice composite that makes life easier.
On the other hand, we don't want to add a lot of composites if we don't have to, and this one doesn't have any additional value (comparing to RadioGroup which make sure only one item is selected).

If it's a repeated pattern, so maybe it will be nice to have it.

**Comment by argshook** [comment]
i guess we don't need `CheckboxGroup`. checkbox is like `ToggleSwitch` and we don't make groups for them

**Comment by shlomitc** [comment]
Looks like we don't need it. Can we close this issue?

**Comment by argshook** [comment]
yes, i think so. please reopen if you disagree
