### ISSUE TITLE
IconWithOptions z-index

### ISSUE THREAD

**Issue by ulmanwix** [wix/wix-style-react#1253]
### Summary:
![screen shot 2017-12-11 at 12 48 03](https://user-images.githubusercontent.com/31505846/33827847-7359d55a-de72-11e7-8448-dde7acf6cda0.png)

### Steps to reproduce:
When options of iconWithOptions are over another iconWithOptions

### Expected behavior:
the dropdown will be over the IconWithOptions icon
![screen shot 2017-12-11 at 12 57 13](https://user-images.githubusercontent.com/31505846/33827973-dc1b5ec4-de72-11e7-86a7-a144c8041595.png)

### Relevant Components:
IconWithOptions
### Additional notes:
I fixed this on my app by overriding the z-index on the container div to be auto (is currently 0)

**Comment by argshook** [comment]
hey there, thanks for reporting an issue :)

#1270 should fix this, it will reach you once 1.2.8 is out
