### ISSUE TITLE
Documentation for story() and AutoExample stopped working

### ISSUE THREAD

**Issue by boriskor** [wix/wix-style-react#1267]
### Summary:
Part of documentation of "Documenting Components" stoped working

### Priority:
- [x] Normal

### Steps to reproduce:
 1. Go to [Introduction -> Documenting components](https://wix.github.io/wix-style-react/?selectedKind=Introduction&selectedStory=Documenting%20components&full=0&down=0&left=1&panelRight=0)
 2. Click on `story()` tab or `AutoExample` tab

### Expected behavior:
Documentation for `story()`/`AutoExample` should be displayed

### Additional notes:
I think it's related to [this change](https://github.com/wix/wix-style-react/commit/90f738b304b8c0635b075a6139129bf4dcdd250b#diff-4a4257109df1c318bc7d2bf35551c443R7). The contents of these files are now:
``` javascript
module.exports = require('./dist/src/Story');
```
instead of the src of the components. `react-codegen` needs to be fed with non-transpiled src, so changing the imports to:
```javascript
import StorySource from '!raw-loader!wix-storybook-utils/dist/src/Story';
```
won't help either.

**Comment by argshook** [comment]
oh no. Thanks for reporting, i'll take a look

**Comment by argshook** [comment]
forgot to close this, it's fixed
