### ISSUE TITLE
Hybrid alert Close button is corrupted in Firefox

### ISSUE THREAD

**Issue by YuriyFedorov** [wix/wix-style-react#1278]
### Priority:
- [ ] Urgent

### Steps to reproduce:
 1. open that page in firefox and check https://wix.github.io/wix-style-react/?selectedKind=8.%20Notification%20Bars&selectedStory=8.1%20Standard&full=0&down=0&left=1&panelRight=0

![image](https://user-images.githubusercontent.com/21078547/34156230-f8a52c34-e4c4-11e7-8bb2-01136c3939fe.png)

**Comment by argshook** [comment]
hey, thanks for reporting!
Fixed in f59bec3560f210e189a792820f600843a445e68d and will reach you once 1.2.11 is released
