### ISSUE TITLE
PopoverMenuItem span.text has no ellipsing / support for long strings

### ISSUE THREAD

**Issue by alexk0ch** [wix/wix-style-react#1288]
### Priority:
- Urgent

### Steps to reproduce:
Attached screenshot, just pass in any long string into `<PopoverMenuItem text={HERE} />`

### Expected behavior:
Long text is ellipsed or, at least not breaking the list layout

### Relevant Components:
PopoverMenu, PopoverMenuItem

### Additional notes:
![screen shot 2017-12-21 at 2 37 42 am](https://user-images.githubusercontent.com/5727408/34265175-dbac5b06-e67d-11e7-8e1e-28b0c968c1e0.png)
![screen shot 2017-12-21 at 2 31 55 am](https://user-images.githubusercontent.com/5727408/34265176-dbc5b60a-e67d-11e7-8860-58dcc300c137.png)

**Comment by argshook** [comment]
closed by #1686
