### ISSUE TITLE
Add some indication that the initial value of some prop is the default prop.

### ISSUE THREAD

**Issue by lbelinsk** [wix/wix-style-react#1304]

**Comment by argshook** [comment]
please tell what am i missing, 'cause default value is displayed in API table

**Comment by shlomitc** [comment]
@lbelinsk 
Are you talking about the AutoExample selected radio button?

**Comment by shlomitc** [comment]
@lbelinsk - can you please explain the scenario?

**Comment by shlomitc** [comment]
not related to this repo and already displayed inside the storybook toggles. closing
