### ISSUE TITLE
"Usage without Haste" missing information

### ISSUE THREAD

**Issue by atoko** [wix/wix-style-react#1317]
### Summary:
When using the recommended webpack configuration, some of the CSS (namely shadows around dropdown boxes) was not being loaded.

### Priority:
- [ x ] Normal

### Steps to reproduce:
 1. Install new app with Create-React-App
 2. Install wix-style-react, sass-loader, node-sass
 3. Eject & setup webpack as described in "Usage without Haste" docs
 4. Modify App.js to include a \<Dropdown /> element
 5. Run with npm start, observe missing styles

### Expected behavior:
Components render as intended

### Relevant Components:
I am using safari, osx high sierra, node version v6.9.1, latest Create-React-App

### Additional notes:
I used an additional "&camelCase" option for the css-loader. This fixed the issue 
`... loaders: [ ..., 'css-loader?modules&importLoaders=1&camelCase&localIdentName=[name]__[local]___[hash:base64:5]', ... ]`

Images attached are with and without camelCase option
<img width="381" alt="screen shot 2018-01-03 at 12 15 29 am" src="https://user-images.githubusercontent.com/1724279/34509763-ae08a0f4-f01b-11e7-8440-049ddd5fa85d.png">
<img width="306" alt="screen shot 2018-01-03 at 12 18 19 am" src="https://user-images.githubusercontent.com/1724279/34509764-ae14ec06-f01b-11e7-9cc4-46429563d982.png">

## Todo

- [ ] - Verify it's not a "works on my box" issue.

- [ ] - Update documentation

**Comment by argshook** [comment]
Hello there, thanks for letting us know!

As i understand adding `camelCase` is the only thing you had to do? Is there anything else we missed to document?

also, we no longer use node 6 and are leaning on node 8.9.1

**Comment by atoko** [comment]
Hello!

Yes, that is correct. At first I thought I needed postcss but I reduced it
to just that one change.

**Comment by argshook** [comment]
closed by c4130c7c0e8433f541a0d9cd17c0d5d7aefa98d8
