### ISSUE TITLE
Page - Scrolling in the Header doesn't scroll in the content as expected.

### ISSUE THREAD

**Issue by amiryonatan** [wix/wix-style-react#1323]
### Summary:
Scrolling in the page when mouse is over the Header doesn't scroll the Page

### Priority:
- [ ] Blocker
- [ ] Urgent
- [x] Normal
- [ ] Minor

### Steps to reproduce:
 1. Scrolling when mouse is on the Header

### Expected behavior: 
Scroll will work

### Relevant Components: 
Page, PageHeader

**Comment by shlomitc** [comment]
@amiryonatan - is this still happening?

**Comment by amiryonatan** [comment]
Yes but maybe we can decide that it's by design

**Comment by shlomitc** [comment]
Your call. If you decide to keep it that way - please close

**Comment by amiryonatan** [comment]
Closed until users will complain about it

**Comment by argshook** [comment]
huh? users are complaining about it (at least in Vilnius)

**Comment by amiryonatan** [comment]
@wuwa is this a requirement ? 
In order to support this we're going to have to re-think the entire component design.

**Comment by wuwa** [comment]
i would say yes, it's definitely better if possible. i think the z-index is preventing this

**Comment by amiryonatan** [comment]
It's a bit more complicated then that :)
Ok we'll put this into consideration

**Comment by shlomitc** [comment]
So I say let’s close this issue for now

**Comment by aarnoldaas** [comment]
Any news?

**Comment by amiryonatan** [comment]
After long investigation we decided to put this bug as a known issue of the component.
Supporting this behaviour is currently not possible with the current component design, and to solve it would mean to refactor the entire component.
Right now, we do not have to capacity to work on it, so until @wuwa decides to prioritize this we will not be working on this bug.

@shlomitc @aarnoldaas
