### ISSUE TITLE
GoogleAddressInput container should have overflow hidden

### ISSUE THREAD

**Issue by Roeia1** [wix/wix-style-react#1328]
GoogleAddressInput container should have overflow hidden.
When one of the search results is long it's taking 2 rows, making the scroll appear.

### Priority:
- [ ] Blocker
- [X] Urgent
- [ ] Normal
- [ ] Minor

### Steps to reproduce:
 1. make a GoogleAddressInput with 400px width
 2.search something long, start scrolling up and down all the way.
 3.tada!

### Relevant Components:
DropDownLayout

**Comment by shlomitc** [comment]
is this still happening?

**Comment by Roeia1** [comment]
@shlomitc seems like it got fixed :)
