### ISSUE TITLE
StatsWidget - padding issues

### ISSUE THREAD

**Issue by wuwa** [wix/wix-style-react#1336]
A couple bugs:
- [ ] Grid in card is not centered 
![image](https://user-images.githubusercontent.com/6668874/34721889-391d907e-f54d-11e7-9d2b-570af5f9bacc.png)
- [ ] Title in top part of card is not vertically centered
![image](https://user-images.githubusercontent.com/6668874/34721914-580ce322-f54d-11e7-93bb-c29376897e14.png)

**Comment by shilomangam** [comment]
https://github.com/wix/wix-style-react/pull/1446
fixed
