### ISSUE TITLE
close dropdown when clicking header

### ISSUE THREAD

**Issue by zeevgg** [wix/wix-style-react#1342]
### Summary:
when using a drop down it feels weird that you need to click outside in order to close it without selecting anything new

### Priority:
Urgent

### Steps to reproduce:
 1. open drop down
 2. click in header
 3. it stays open

### Expected behavior:
drop down should close, just like I clicked on Escape

**Comment by argshook** [comment]
@milkyfruit please tell whether such behaviour is what we should be doing

**Comment by milkyfruit** [comment]
Makes perfect sense. Just please notice, that behaviour described above applies only for 4.1a/b Dropdown. If a dropdown has "Autocomplete" feature then different rules should apply.

See the full explanation [here](https://zpl.io/an17JjY)
