### ISSUE TITLE
Dropdown IE11 shows caret inside header

### ISSUE THREAD

**Issue by zeevgg** [wix/wix-style-react#1344]
### Summary:
Dropdown IE11 shows caret inside header
https://www.screencast.com/t/RIRAfLGL

### Priority:
Urgent

### Steps to reproduce:
 1. open drop down

### Expected behavior:
do not show caret

### Relevant Components:
DropDown

**Comment by zeevgg** [comment]
I think that it is impossible in IE11
https://social.msdn.microsoft.com/Forums/en-US/570c941f-5ade-4345-bd78-5fbeb18d4e29/hide-blinking-cursor-from-input-field?forum=iewebdevelopment

**Comment by shlomitc** [comment]
@zeevgg - So can we close it?

**Comment by zeevgg** [comment]
yes
