### ISSUE TITLE
PopoverMenuItem small request for auto-testing

### ISSUE THREAD

**Issue by alexk0ch** [wix/wix-style-react#1358]
### Summary:
We can add dataHook only to PopoverMenuItem container (li), clickable area contains button, inside which there is icon + text. 
If one of items in menu has way too longer text then the rest of items, selenium webdriver clicks right in the center of data-hooked item (which is container in our case). At the same time, text + icon takes less then 50% of container width, and selenium is unable to click it!

![screen-shot-2018-01-12-at-5 22 31-pm](https://user-images.githubusercontent.com/5727408/34882222-87ff7c52-f7be-11e7-94d3-daba8ae66aeb.png)

### Priority:
- [X] Normal

### Expected behavior:
Clicking on the LI (container) should trigger onClick callback, aka the whole PopoverMenuItem should be clickable, hover over PopoverMenuItem (not only it's contents), should trigger hover for icon + text inside of it.

### Additional notes:
This also will lead to better UX.

**Comment by OlgaDm** [comment]
Or we can move data-hooks to button element, which looks proper also.

**Comment by shlomitc** [comment]
It's a pretty old issue. anyway, a PR will be happily welcome
