### ISSUE TITLE
Input prefix in IE11 breaks into 2 lines

### ISSUE THREAD

**Issue by tzabarc** [wix/wix-style-react#1365]
### Priority:
- [ ] Blocker
- [ ] Urgent
- [x] Normal
- [ ] Minor

### Steps to reproduce:
 1.<Input prefix={<Input.Unit value={countryCode + ' |’}/>} >
 2.
 3.

### Relevant Components:
<Input>
### Additional notes:
[screencast video](https://www.screencast.com/t/QxnrmKVToP)

**Comment by shlomitc** [comment]
Thanks for reporting.
Do you think you can create a PR for that?

**Comment by tzabarc** [comment]
sure, will do when i'll get available. 
for the record - the fix is adding css rule  "white-space: nowrap;" for the inside prefix div

**Comment by shlomitc** [comment]
looks like an old bug. if still exists and please re-open
