### ISSUE TITLE
Selector component is broken with long title/subtitle

### ISSUE THREAD

**Issue by D0vydas** [wix/wix-style-react#1369]
### Summary:
Selector component is broken with long title/subtitle

### Priority:
- [ ] Blocker
- [ ] Urgent
- [x] Normal
- [ ] Minor

### Screenshots:
![screen shot 2018-01-17 at 13 34 58](https://user-images.githubusercontent.com/6649425/35041553-d0085122-fb8d-11e7-84f9-1f09da21d50a.png)
![screen shot 2018-01-17 at 13 35 34](https://user-images.githubusercontent.com/6649425/35041555-d0773484-fb8d-11e7-84a2-fede8c8c7c0d.png)

**Comment by shlomitc** [comment]
Hey, thanks for opening the issue.
Do you think you can make a small PR to fix it?

**Comment by aarnoldaas** [comment]
https://github.com/wix/wix-style-react/pull/1461
