### ISSUE TITLE
Simplify Notification Bars

### ISSUE THREAD

**Issue by milkyfruit** [wix/wix-style-react#1370]
Let's make [notification bars](https://wix.github.io/wix-style-react/?selectedKind=8.%20Notification%20Bars&selectedStory=8.1%20Standard&full=0&addons=0&stories=1&panelRight=0) more simple by removing "Size" prop.

The notification bar size depends only on a button - if it's used or not. Right now a developer must resize the bar manually by using "size" prop.

So, I updated [the design](zpl.io/VQoQBk9), that notification bar will be always with 12px paddings. This way the height can be flexible.

**Comment by argshook** [comment]
this is already partially implemented in #1356 
missing things are non hardcoded height and consistent padding
