### ISSUE TITLE
Review and Fix Old Issues

### ISSUE THREAD

**Issue by milkyfruit** [wix/wix-style-react#1376]
This spreadsheet has reported issues, some of them remain unfixed:
https://docs.google.com/spreadsheets/d/14bijZuhm_Fxp2aAmx7gRMYZ-muUmPBvRMEWfP5Twp0Q/edit#gid=942856749

We need to go all over them and make sure they're resolved.

The brief of issues:

**won't be fixed:**
3.8 Tags | Missing scrollbar's custom style

**Fixing:**
- [x] 2.2 Card | bottom padding must be 30px
- [ ] 3.1 Text Field | Prefix position breaks on IE browser
- [x] 3.1 Text Field | Allow to set max width to Error message's tooltip
- [x] 3.1 Text Field | Show required + info tooltip also when label is disabled
- [x] 7.1 Tooltip | Fix max-width to be correct size of tooltip (not content), Add default max-width: 204px
- [x] 3.8 Tags | tag color + hover color

**Will be fixed in a new version of the popover:**
7.1 Tooltip | tooltip not centered on element 
7.3 Popover Menu | popover menu not centered on element
7.3 Popover Menu | popover menu stays in place when scrolling

**Comment by shlomitc** [comment]
3.8 Tags | Missing scrollbar's custom style - *we don't want to use custom scrollabars*
2.2 Card | bottom padding must be 30px - *can be fixed*
3.1 Text Field | Prefix position breaks on IE browser - *can be fixed*
3.1 Text Field | Allow to set max width to Error message's tooltip - *best solution will be to pass in the entire tooltip props*
3.1 Text Field | Show required + info tooltip also when label is disabled - *can be fixed*
7.1 Tooltip | Fix max-width to be correct size of tooltip (not content), Add default max-width: 204px - *Will be fixed in a new version of the tooltip in wix-ui-backoffce*
7.1 Tooltip | tooltip not centered on element - *Will be fixed in a new version of the tooltip in wix-ui-backoffce*
7.3 Popover Menu | popover menu not centered on element - *Will be fixed in a new version of the popover in wix-ui-backoffce*
7.3 Popover Menu | popover menu stays in place when scrolling - *Will be fixed in a new version of the popover in wix-ui-backoffce*
3.8 Tags | tag color + hover color - *can be fixed*

**Comment by milkyfruit** [comment]
Few more issues from a [recent QA](https://docs.google.com/spreadsheets/d/1FCi9vBpR8apWxyHNqaOExAgCQy4BdhBea1lXif8QIkE/edit#gid=0):

### Functional Bugs / Missing Features
[**12.1 Badge:**](https://wix.github.io/wix-style-react/?selectedKind=12.%20Other&selectedStory=12.1%20Badge&full=0&addons=0&stories=1&panelRight=0) 
- [ ] Missing "badge group" type [(link to specs)](https://zpl.io/an6NYjJ)

[**3.6 Date Picker:**](https://wix.github.io/wix-style-react/?selectedKind=3.%20Inputs&selectedStory=3.6%20DatePicker&full=0&addons=0&stories=1&panelRight=0)
- [ ] Doesn't display an [error message](http://prntscr.com/hy1fc6)
- [ ] Should block access to [past dates](http://prntscr.com/hy1grs)
- [ ] Could not test it or does not work, [please check it.](http://prntscr.com/hy1jav)
- [ ] Missing [label option](http://prntscr.com/hygsb0)

[**1.5 Loader:**](https://wix.github.io/wix-style-react/?selectedKind=1.%20Foundation&selectedStory=1.5%20Loader&full=0&addons=0&stories=1&panelRight=0)
- [ ] Missing error state [(link to specs)](https://zpl.io/VOowyML)

[**3.4 Time Picker:**](https://wix.github.io/wix-style-react/?selectedKind=3.%20Inputs&selectedStory=3.4%20TimePicker&full=0&addons=0&stories=1&panelRight=0)

- [ ] Prevent [typing letters](http://prntscr.com/hyh1x3)
- [ ] Missing [24-hour format option](http://prntscr.com/hyh2c0)
- [ ] disableAmPm doesn't work or untested, [please check](https://prnt.sc/hyh6iq)
- [ ] AM / PM has to work the [same as hours and minutes](https://prnt.sc/hyh1x3)
- [ ] Missing [label option](https://prnt.sc/hyh1a6)
- [ ] Missing option with [seconds](http://prntscr.com/hyh7go)
- [ ] Missing option with [no "ticker"](http://prntscr.com/hyhma4)

[**4.4 ToggleSwitch:**](https://wix.github.io/wix-style-react/?selectedKind=4.%20Selection&selectedStory=4.4%20ToggleSwitch&full=0&addons=0&stories=1&panelRight=0)

- [ ] Missing [label option](https://zpl.io/bW6RPea)

[**4.2 Checkbox:**](https://wix.github.io/wix-style-react/?selectedKind=4.%20Selection&selectedStory=4.2%20Checkbox&full=0&addons=0&stories=1&panelRight=0)

- [ ] Missing error [tooltip on hover](http://prntscr.com/hyiuwu)

[**4.3 Radio Button / 4.5 Advanced Toggle:**](https://wix.github.io/wix-style-react/?selectedKind=4.%20Selection&selectedStory=4.2%20Checkbox&full=0&addons=0&stories=1&panelRight=0)

- [ ] By design type option is a [different component ](https://prnt.sc/hyzbrv)

[**11.2 Editable Selector:**](https://wix.github.io/wix-style-react/?selectedKind=11.%20Pickers%20and%20Selectors&selectedStory=11.2%20EditableSelector&full=0&addons=0&stories=1&panelRight=0)

- [ ] Please update "Add New" [feature behavior
](http://prntscr.com/hyyvhi)

_Check if fixed._

**Comment by lbelinsk** [comment]
The following issues are resolved:

3.1 Text Field | Allow to set max width to Error message's tooltip
3.1 Text Field | Show required + info tooltip also when label is disabled
7.1 Tooltip | Fix max-width to be correct size of tooltip (not content), Add default max-width

**Comment by hepiyellow** [comment]
@shlomitc are we maintaining this Issue?
If it appears in our private-wsr issues, then can we close this one.

**Comment by shlomitc** [comment]
Some bugs are still not solved but they are all in our wsr-issues backlog.

Closing, thanks
