### ISSUE TITLE
DataTable : showHeaderWhenEmpty should be true by default IMO

### ISSUE THREAD

**Issue by hepiyellow** [wix/wix-style-react#1379]
### Summary:
showHeaderWhenEmpty should be true by default IMO
### Priority:
- [ ] Blocker
- [ ] Urgent
- [x ] Normal
- [] Minor

### Additional notes:
Apart from the fact that when there is no header, it is confusing.
Unit-testing is difficult since when data.length is 0 (and showHeaderWheEmpty is false) then the DataTable.Driver methods start throwing errors since there is no `element`. Such as dataTableDriver.getRowsCount() throws an error.

In any way, the DataTable.Driver should be fixed to not throw arbitrary errors when data.length is 0.

**Comment by shlomitc** [comment]
Changing the default behavior might be a breaking change, and we will probably create a new version of the DataTable in the future, so I don't think it's worth fixing for now.
Do you think you can fix the DataTable driver?

**Comment by hepiyellow** [comment]
Yep. I’ll fix the driver.

**Comment by hepiyellow** [comment]
Duplicate of #1380
