### ISSUE TITLE
Update jquery version due to potential security vulnerability

### ISSUE THREAD

**Issue by shlomitc** [wix/wix-style-react#1389]
![image](https://user-images.githubusercontent.com/6093192/35292411-0d3d190c-0079-11e8-9741-f0ba9a3fbc29.png)

**Comment by ryh** [comment]
😞, why `jquery` is required in react based project.

**Comment by shlomitc** [comment]
@ryh It was used in several components when the library was created. I’ll be happy to remove it completely from the library if possible.
Would you like to make a PR for that? We’ll appreciate it greatly

**Comment by argshook** [comment]
@ryh at the moment jquery is still used in protractor testkits for selecting dom nodes and maybe some `find`s, don't remember exactly. It's not used in any components.

In general we don't need it at all and it should be easy to remove. it was added ages ago and nobody touched that part.

regarding security vulnerability, we're not vulnerable at all, cause 1) we don't use version with potential risk and 2) we use it only it testkits, not in user-facing code

**Comment by shilomangam** [comment]
jQuery Removed, waiting for merge.
https://github.com/wix/wix-style-react/pull/1447

**Comment by shlomitc** [comment]
merged in version 3.0.0
