### ISSUE TITLE
Breadcrumbs do not support extra long content

### ISSUE THREAD

**Issue by alexk0ch** [wix/wix-style-react#1391]
### Summary:
Hey guys, 

recently we've received a request to display video title in breadcrumbs, which can be up to 250 (!) characters long... And, unfortunately breadcrumbs do not support any kind of handling for this case - text breaks second line and the whole layout gets broken. Since we're not allowed to pass-in PropTypes.node as a breadcrumb label, we expect this to be handled somehow on wix-style-react side. 

### Priority:
- [X] Normal

### Steps to reproduce:
 1. Create Breadcumbs component with one of breadcrumb item having extra long text. 

### Expected behavior:
Handling of extra long strings, aka text ellipsing. Ideally - keep all the breadcrumbs take only one line, so if you have 3 breadcrumbs where 2 of them are short, the last one (which is long) will be ellipsed (... appended after text at max possible width taken).  

### Relevant Components:
Breadcrumbs. 

### Additional notes:
If it's way too hard to do, we can probably allow passing of PropTypes.node instead of PropTypes.string as a breadcrumb label. 

#### Thanks a lot!

![screen shot 2018-01-25 at 6 14 32 pm](https://user-images.githubusercontent.com/5727408/35399467-ee9f175e-01fc-11e8-998b-ca16badfebc7.png)

**Comment by argshook** [comment]
we probably should have `maxWidth` with `text-overflow: ellipsis` inside wix-style-react so you don't need to care about this but this needs UX decision, so summoning @milkyfruit 


but are you sure you can't pass node? it is allowed in proptypes https://github.com/wix/wix-style-react/blob/54c12ec91c8fe0efbf259f6efaf98363ebc0dd31/src/Breadcrumbs/Breadcrumbs.js#L28-L31

if it doesn't work, you can also simply trim title with js:

```js
const trim = length => string =>
  string.length > length
    ? string.substr(0, length) + '...'
    : string

trim(10)('hello world') // <- "hello worl..."
```

**Comment by milkyfruit** [comment]
By design the default maximum width of a single breadcrumb button is 204 pixels. The specs are [here.](zpl.io/V400Wjz)

**Comment by ipanasenko** [comment]
@argshook also, this is a chance to update propType for `value` to just be `node` ;)

**Comment by argshook** [comment]
thanks @milkyfruit i'll try to go over it today

**Comment by alexk0ch** [comment]
Thanks @argshook - if it will be up to 204 pixels per pill, It should be fine
