### ISSUE TITLE
No correct documentation for RadioGroup

### ISSUE THREAD

**Issue by rudnitskih** [wix/wix-style-react#1400]
### Summary:
Looks like an issue with documentation for `RadioGroup` component.

### Priority:
- [ ] Blocker
- [ ] Urgent
- [x] Normal
- [ ] Minor

### Steps to reproduce:
 1. Open the storybook for RadioGroup component - https://wix.github.io/wix-style-react/?selectedKind=4.%20Selection&selectedStory=4.3%20Radio%20Button%20Group&full=0&addons=0&stories=1&panelRight=0
 2. In examples showed that we need to use `RadioGroup.Button`, but actually we export  `RadioGroup.Radio` - https://github.com/wix/wix-style-react/blob/master/src/RadioGroup/RadioGroup.js#L95

### Expected behavior:
Documentation and exports should be equal. We can or update docs or change API. Both are acceptable to us.

**Comment by argshook** [comment]
hi, thanks for reporting! I fixed this already here 00f303b210bb0dda808f9ab85405c17ea3cf8d03 it will be live after next release (some time today)

the correct one is `RadioGroup.Radio`. For whatever reason this component had `displayName = 'RadioGroup.Button'` and so documentation showed that
