### ISSUE TITLE
Issue with long content in RadioGroup component 

### ISSUE THREAD

**Issue by rudnitskih** [wix/wix-style-react#1403]
### Summary:
We need to implement such component:
![image](https://user-images.githubusercontent.com/8848858/35564531-217f0e12-05c3-11e8-9c2a-fc94ebe59d2b.png)

According to docs we need to use `RadioGroup` component with `type="button"` and `display="horizontal"` properties. But we cannot add internal paddings. Also because the buttons have hardcoded width we cannot put long labels. It can create an issue for localizable pages. 

![image](https://user-images.githubusercontent.com/8848858/35564728-c67ade32-05c3-11e8-87ba-9f7eaf4af135.png)

### Priority:
- [ ] Blocker
- [ ] Urgent
- [x] Normal
- [ ] Minor

### Steps to reproduce:
 1. Use example from docs for `RadioGroup` component with `type="button"` and `display="horizontal"` properties.
 2. One of the options should have a long label.
 3. The text doesn't fit to button.

### Expected behavior:
All buttons should fit any long text.

### Additional notes:
Please check our code and give advise if we have mistake in usage -https://github.com/wix-private/wix-payments/blob/master/packages/wix-payments-onboarding/src/app/components/OnboardingForm/Adapters/RadioButtonGroupAdapter/RadioButtonGroupAdapter.tsx

**Comment by aarnoldaas** [comment]
Fixed by: https://github.com/wix/wix-style-react/pull/1457
