### ISSUE TITLE
Wrong color for divider in Card component

### ISSUE THREAD

**Issue by rudnitskih** [wix/wix-style-react#1404]
### Summary:
Our designer takes `Card` component from our design system and it has a divider with color #dfe5eb($D60). In `wix-style-react` the `Card` component has divider with color #f0f4f7($D70).

Could you please check and say where is a mistake.

### Priority:
- [ ] Blocker
- [ ] Urgent
- [ ] Normal
- [x] Minor

### Steps to reproduce:
 1. Open storybook with Card - https://wix.github.io/wix-style-react/?selectedKind=2.%20Layout&selectedStory=Card&full=0&addons=0&stories=1&panelRight=0
 2. Open Sketch with the same component
 3. Check dividers color

### Expected behavior:
Colors should be the same

**Comment by argshook** [comment]
thanks, it should indeed be `$D60`. fixed in https://github.com/wix/wix-style-react/commit/639c242cec2442fe60e993ba3995448b212dab68, closing :)
