### ISSUE TITLE
12.4 Full Text View

### ISSUE THREAD

**Issue by milkyfruit** [wix/wix-style-react#1405]
Every component, that has text content which overflows its container must have a tooltip on hover which displays the full text content.

Why not to make a separate component-function would do this job for all components? 

Initial index:
zpl.io/a7GjPPq

**Comment by shlomitc** [comment]
Agree.
1. we already have a text component with ellipsis behavior, so it should be a relatively easy task to replace texts with this component.
2. we need to add the tooltip behavior to this component.

**Comment by shlomitc** [comment]
The component will soon be implemented (WIP https://github.com/wix/wix-style-react/pull/2004) but refactoring existing components will be made separately.

anyway, closing it as no further action is needed here
