### ISSUE TITLE
Tabs Update

### ISSUE THREAD

**Issue by milkyfruit** [wix/wix-style-react#1406]
[6.3 Tabs Zeplin Specs](https://zpl.io/VQ0lyq4) were updated.

[The developed component ](https://wix.github.io/wix-style-react/?selectedKind=6.%20Navigation&selectedStory=6.3%20Tabs&full=0&addons=0&stories=1&panelRight=0)should be updated accordingly:
1. Tabs should not have "Side Content" option. This feature should be moved to [Page/Page Header component.](https://wix.github.io/wix-style-react/?selectedKind=2.%20Layout&selectedStory=2.5%20Page&full=0&addons=0&stories=1&panelRight=0)

2. [Restructured Indexing](http://zpl.io/bP6L5DV). 
- Replace the existing (composite) `type` property with new independent props:
   - item_width_type: fit_text (default) | fixed (uses width prop) | auto (maximise to fit container)
   - with_body_margins: boolean (add 30px horizontal margin for the container)
   - with_item_padding: boolean (add 18px horizontal padding for each tab item)

Most people used the old 'compact' type, so the new defaults should be: 
   - item_width_type: fit_text
   - with_body_margins: fasle
   - with_item_padding: false

Now the `compact` type is the most used one. In addition, prop names now are more self explanatory (e.g. body paddings, tab paddings).

3. Updated "maximum width" specs. Need to make sure they're implemented correctly. 
"maximum width" was applied only for type='compactSide". With the new Tabs API, it would be applied when item_width_type=`fit_text`.
It is not relevant when we use `fixed_width` or `auto`.

When a tab text content exceeds its width, the full text should be displayed using [this component.](https://github.com/wix/wix-style-react/issues/1405)

**Comment by shlomitc** [comment]
2. I don't understand this point. What change is needed?
3. can you explain the wanted changes? What's not implemented correctly?

**Comment by shlomitc** [comment]
@milkyfruit - ping

**Comment by milkyfruit** [comment]
Sorry, for the late answer:

2. Renaming the tab types and changing the default type.
3. If a tab doesn't have "width" prop it must have "maximum-width" parameter, which behaviour description is [here.](https://zpl.io/VQ0lyq4)

**Comment by hepiyellow** [comment]
@shlomitc @wuwa 
What is the priority of this API change?

**Comment by shlomitc** [comment]
It's been waiting for 1 full year, so I don't think it's urgent :)

**Comment by milkyfruit** [comment]
@hepiyellow wow, this is old. It's not urgent, let me update on status:
1. Specs changed to this: zpl.io/bPPApm6
2. Obsolete, please look at the link above.
3. Haven't changed, everything in the specs above.

**Comment by shlomitc** [comment]
old, closing
