### ISSUE TITLE
Breadcrumbs ... overflow has wrong color if breadcrumbs dark theme used

### ISSUE THREAD

**Issue by alexk0ch** [wix/wix-style-react#1417]
### Summary:
Breadcrumb max size is set to 204px, which is according to design; If you're using dark theme (white text color, dark background) three dots (...) which appear when text overflows breadcrumb have dark blur color, instead of white - theme is not applied to them. 

### Priority:
- [X] Normal

### Expected behavior:
3 dots inherit color from current text color of breadcrumb.

### Relevant Components:
Breadcrumbs.
![screen shot 2018-01-31 at 3 49 11 pm](https://user-images.githubusercontent.com/5727408/35626594-da4362d2-069e-11e8-96ac-524c4b3d6cc5.png)

**Comment by argshook** [comment]
closed by #1430
