### ISSUE TITLE
<Text appearance=“H4”> adds unwanted margin

### ISSUE THREAD

**Issue by hepiyellow** [wix/wix-style-react#1426]
@wuwa 
This component renders to an <h5> element with _`-webkit-margin-before -webkit-margin-after`_

![screen shot 2018-02-03 at 21 13 55](https://user-images.githubusercontent.com/6338722/35779057-d7158c28-09cf-11e8-86ec-b5c74b0ed93a.png)

**Comment by argshook** [comment]
@hepiyellow FYI, known issue https://github.com/wix/wix-style-react/issues/1090
and a (not merged) solution was here https://github.com/wix/wix-style-react/pull/1092

**Comment by shlomitc** [comment]
Wait - why do we close it now?
Aren't we supposed to be able to merge in now that we do have semver and manual releases?
