### ISSUE TITLE
StatsWidget incorrect spacing from left and right

### ISSUE THREAD

**Issue by aarnoldaas** [wix/wix-style-react#1434]
Stats widget is Card without Container that causes Card.Content not getting "box-sizing: border-box"
and incorrect width of the content. 
Wrapping it into Container will make container max-width: 1254px
Current:
![screen shot 2018-02-07 at 10 30 32](https://user-images.githubusercontent.com/9351975/35907879-d443f596-0bf7-11e8-879d-687fbb981f06.png)

If I will wrap it to Container:
<img width="1664" alt="screen shot 2018-02-07 at 11 13 20" src="https://user-images.githubusercontent.com/9351975/35907920-f1d95e52-0bf7-11e8-95c4-f257b8593894.png">

Problem is that currently spacing from left and right are incorrect.

Can I do pull request with wrapping it to Container?

**Comment by aarnoldaas** [comment]
Never mind I will wrap it into Container on our side. 
Maybe it should be mentioned in documentation and examples should be fixed?

**Comment by shlomitc** [comment]
Can you please fix the example so it will be shown in the storybook and code snippet as well?

**Comment by shilomangam** [comment]
Fixed
https://github.com/wix/wix-style-react/pull/1446
