### ISSUE TITLE
Page component is broken on Internet Explorer

### ISSUE THREAD

**Issue by aarnoldaas** [wix/wix-style-react#1449]
### Summary:
Content get pushed to the right on internet explorer when max-width property is present on content. 
Removing this line solves the problem but reverts another:
https://github.com/wix/wix-style-react/commit/404619f8c66095d72dcb803e66ded230cc97cecf#diff-2ad241a98828e294c44e3ed632651ee8R103

Found this issue now in production: Events and New Blog on business - manager

<img width="1291" alt="screen shot 2018-02-12 at 09 44 12" src="https://user-images.githubusercontent.com/9351975/36087533-7ff087e2-0fdb-11e8-99dd-d7bbaf96a84e.png">

### Priority:
- [x] Blocker
- [ ] Urgent
- [ ] Normal
- [ ] Minor

### Steps to reproduce:
 1. Put max-width on content
 2. Open with internet explorer
 3.

### Expected behavior:
Content does not get pushed to the right
### Relevant Components:
Page

**Comment by amiryonatan** [comment]
@aarnoldaas Fixed.

**Comment by argshook** [comment]
reopen due to https://github.com/wix/wix-style-react/commit/1e33b5139b27c49ff2297214fa595c31a4624d2c

**Comment by aarnoldaas** [comment]
@shlomitc @argshook @amiryonatan ?
It breaks at least two verticals in business manager

**Comment by shlomitc** [comment]
The suggested fix caused UI to break on Chrome.
We're going to work on a solution that will support browsers better.

**Comment by aarnoldaas** [comment]
I will reopen jira and assign it to you.

**Comment by shlomitc** [comment]
Fixed in version 2.0.26
