### ISSUE TITLE
Uncaught TypeError when moving via tabs between dropdown fields 

### ISSUE THREAD

**Issue by xmityaz** [wix/wix-style-react#1450]
### Summary:
When moving via Tab between dropdown fields, previously opened Drop Downs are not closed. The error appears in console. And the dropdown value might change to [Object object]

### Priority:
Normal

### Steps to reproduce:
 1. Open wix-style-react storybook with [dropdowns page](https://wix.github.io/wix-style-react/?selectedKind=4.%20Selection&selectedStory=4.1%20Dropdown&full=0&addons=0&stories=1&panelRight=0)
 2. Click on the first dropdown (with label "left to right")
 3. Try to press tab several times. Watch in console and on dropdowns

### Expected behavior:
When new dropdown open - the previous closes. No errors in console. And dropdown value remains the same they was

### Relevant Components:
DropDown, InputWIthOptions (?)

**Comment by shlomitc** [comment]
So if I understand it correctly, the Dropdown should be closed when `tab` is pressed.

I'm not sure regarding discarding the highlighted value. @milkyfruit - what do you think the behavior should be?

**Comment by milkyfruit** [comment]
The common dropdown's behaviour would be to highlight the dropdown field, while leaving it closed. Using the keyboard a dropdown usually opens using "arrow down" or "spacebar" keys.
Once the dropdown is open, the tab is disabled until option is chosen using "arrow keys" and "spacebar" or "enter" to confirm.

**Comment by milkyfruit** [comment]
Another issue we have with this component while accessing with "tab" key:
Instead of 1 click, 2 tab clicks are required to move the focus to another dropdown. I assume, there's some hidden object between the dropdowns, that gets focused as well, but we dont' see it.

**Comment by shlomitc** [comment]
summary:
1. While dropdown is open, tab should be disabled.
2. tab shouldn't open the dropdown (only arrow down and spacebar keyboard controls).
2. When dropdown is closed, one tab press should move you to next element (and not two like today)

**Comment by argshook** [comment]
> 1. While dropdown is open, tab should be disabled.
are you absolutely surely about that?

**Comment by milkyfruit** [comment]
@argshook there are 2 schools of thoughts:
a. Tab click is blocked until a value from dropdown list is selected
b. Tab click moves the focus to a next component and closes closes the first one's list.

I cannot be sure the one is better than other, until we make a test.
