### ISSUE TITLE
Page title collapses leaves a big blank area

### ISSUE THREAD

**Issue by aryelu** [wix/wix-style-react#1467]
### Summary:
https://wix.github.io/wix-style-react/?selectedKind=2.%20Layout&selectedStory=2.5%20%2B%20Page%20Example&full=0&addons=0&stories=1&panelRight=0
https://files.slack.com/files-pri/T02T01M9Y-F99JEDJ8L/screenshot_2018-02-15_15.16.15.png
if you scroll a bit, after the title collapses there leaves a big blank area
### Priority:
- [ ] Blocker
- [ ] Urgent
- [x] Normal
- [ ] Minor

### Steps to reproduce:
 1.
 2.
 3.

**Comment by shlomitc** [comment]
I think it's by design since otherwise, the text content will just jump.

**Comment by argshook** [comment]
https://github.com/wix/wix-style-react/blob/11283607c7c59b4623fb5f7ea83d804afd3b0382/src/Page/Page.js#L10

adjusting this line (i tried 100) can make it a lot better, currently a huge gap is possible

**Comment by shlomitc** [comment]
I guess it depends on the content of the header. @amiryonatan - why was 24 decided as the right number? what happens if we take higher?

**Comment by amiryonatan** [comment]
24px is the height of the padding between the header and the content.
It seemed logical at the time that on scroll, when the content top reaches the actual Header, it triggers the minimize event.
Increasing the value will cause a behaviour where some of the content will be hidden under the full header, and only after more scrolling the header will minimize.
@wuwa, the behaviour today is, right when the header is mininized we get a large padding between the header and content:
![screen shot 2018-02-15 at 17 33 11](https://user-images.githubusercontent.com/8499532/36264798-663c0478-1276-11e8-8e56-f9aa20c0361e.png)

They are suggesting to increase the threshold for the minimize event, which will be:
Before minimize: 
![screen shot 2018-02-15 at 17 34 50](https://user-images.githubusercontent.com/8499532/36264874-9cfd4cec-1276-11e8-94e7-1cde427ba065.png)

After minimize:
![screen shot 2018-02-15 at 17 35 01](https://user-images.githubusercontent.com/8499532/36264893-a355bdc2-1276-11e8-9ef7-7f622acd4efd.png)

What do u think ?

**Comment by wuwa** [comment]
hi,
the 2nd option is not good. cannot hide content like that. another small thing (half-related) - 
the bg color of the 24px pasdding should be invoked only after minimize event (be transparent before).
i would like to try to animate the content as well when invoking the minimize event - meaning translating it up by the amount that was removed (72px in this case)

**Comment by amiryonatan** [comment]
Fixed:
https://github.com/wix/wix-style-react/pull/1494
