### ISSUE TITLE
Implement multiselect

### ISSUE THREAD

**Issue by bildja** [wix/wix-style-react#1478]
### Summary:
![image](https://user-images.githubusercontent.com/818546/36433554-701b14aa-1665-11e8-839c-e654fe02c9f4.png)
https://zpl.io/2vEy3Yb
Implement a wix style react component for multiselect

### Priority:
- [ ] Blocker
- [ ] Urgent
- [X] Normal
- [ ] Minor

**Comment by shlomitc** [comment]
Implemented [here](https://github.com/wix/wix-style-react/commit/b94e4bf1ef1fef071828e6a9fa75ab2533d8f74d). will be released soon
