### ISSUE TITLE
Allow individual importing of a Icons (without bundling all icons)

### ISSUE THREAD

**Issue by hepiyellow** [wix/wix-style-react#1484]
CurrentlyIn the [Icons storybook page](https://wix.github.io/wix-style-react/?selectedKind=1.%20Foundation&selectedStory=1.4%20Icons&full=0&addons=0&stories=1&panelRight=0) it is stated that you should import specific icons like this:
`import {Duplicate2} from 'wix-style-react/Icons';`

This makes all the Icons bundled in your.
NOTE: I verified this by building a new fullstack-ts project using the genrators (`haste-preset-yoshi`, and checking the app.bundle.js. It might be that tree-shaking is not configured, or it is not able to "shake it off".

Anyways, I've seen that in some projects icons are imported like this:
`import ArrowRightThin from 'wix-style-react/dist/src/Icons/dist/components/ArrowRightThin';`

In which case the bundle includes only the specified icon.

In case we want to encourage this kind of importing,
then I guess we should use `import-path` to create individual `js` files under the root folder, so they could be imported like this:
`import ArrowRightThin from 'wix-style-react/Icons/ArrowRightThin';`

**Comment by shlomitc** [comment]
you're right. tree-shaking is a problem in many places.
we hope that webpack4 is going to overcome it, so hopefully really soon we can get rid of all of our custom solutions.

So fixing it will be done soon and then all we will need to do is just export one index file correctly and change the documentation.

**Comment by yakirn** [comment]
@shlomitc still happening with yoshi@2.8.1 and webpack@4.1.1 any updates on when this will be solved?

**Comment by shlomitc** [comment]
@yakirn - it's not enough that you use it, `wix-style-react` needs to declare that it's compatible with tree shaking. @lbelinsk is working on it and will soon get it working

**Comment by shlomitc** [comment]
The new Icons can now be imported individually more nicely (still no tree shaking)
`import Favorite from 'wix-style-react/new-icons/Favorite';`

https://wix-wix-style-react.surge.sh/?selectedKind=1.%20Foundation&selectedStory=1.4%20Icons&full=0&addons=0&stories=1&panelRight=0

I'm closing the issue as tree shaking is an ongoing task and once done will be announced publically

**Comment by yakirn** [comment]
Thanks @shlomitc !
