### ISSUE TITLE
Error watching file for changes (when running `npm start`)

### ISSUE THREAD

**Issue by hepiyellow** [wix/wix-style-react#1486]
Getting this when running `npm start`:
```
2018-02-26 11:53 node[41927] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: Error watching file for changes: EMFILE
    at _errnoException (util.js:1024:11)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1351:9)
jest failed with status code "1"
```

**Comment by argshook** [comment]
could you please elaborate, what steps you took to reach this error?

**Comment by hepiyellow** [comment]
This is my local HEAD:
`c7918119 2018-02-22 | expand Tag component functionality (#1481) (HEAD -> master, origin/master, origin/HEAD, fix/data-table-add-prop-types-column) [Vladislav Zhuk]`

I did:
```
rm -rf node_modules
rm package-lock.json
npm i
npm run build
npm start
```

Everything seems to work, but there is this error in the console.

**Comment by hepiyellow** [comment]
Here is the full log for `npm start`:
[build-log.txt](https://github.com/wix/wix-style-react/files/1758821/build-log.txt)

**Comment by shlomitc** [comment]
still happening?

**Comment by hepiyellow** [comment]
yes

**Comment by argshook** [comment]
maybe try this https://github.com/facebook/react-native/issues/910#issuecomment-94181845

**Comment by shlomitc** [comment]
did it work for you?

**Comment by shlomitc** [comment]
closing, contact me if still happening
