### ISSUE TITLE
Some clarification for 3. party WIX app developers

### ISSUE THREAD

**Issue by xat** [wix/wix-style-react#1490]
Hi Guys,

I just stumbled across this UI library and think that it is really awesome!

Currently I'm in the progress of writing a 3. party WIX app and was wondering if I could use the components from this UI library in that app or if we are supposed to use the UI components mentioned in the docs ( https://dev.wix.com/docs/ui-lib/ui-controls/ ). For example, in this library there seems to be a DatePicker, while in the UI library mentioned in the docs they state that we are supposed to create our own DatePicker (based on some PSD files).

Also the components mentioned in the docs often have internal state, which makes development a bit hard, if you, for example, want to manage state in a central place. In general this library here seems todo stuff more in a "React way" compared to the one mentioned in the docs.

So to sum the question up: Are 3. party WIX developers, which are building their apps using React, supposed/allowed to use this UI library in their apps or are they supposed to stick with UI components mentioned in the docs ( https://dev.wix.com/docs/ui-lib/ui-controls/ )?

**Comment by shlomitc** [comment]
Hey there!
In general, you should use the suggested library in order to get the best look and feel of Wix in your settings panel. However, if some components are missing, feel free to use the components as you wish.
