### ISSUE TITLE
New Focus styles

### ISSUE THREAD

**Issue by hepiyellow** [wix/wix-style-react#1495]
Need to update these components with new Focus styles from the zeplin specs:
(Applies only to `normal` theme)

For example: (The shadow-box is the new thing)
![screen shot 2018-03-01 at 13 52 18](https://user-images.githubusercontent.com/6338722/36843504-d4b7eae8-1d57-11e8-99d6-8c9381e17183.png)
(Also border color changed from B20 to B10)

And for Error state & Focus: (A red shadow box)
![screen shot 2018-03-01 at 13 53 20](https://user-images.githubusercontent.com/6338722/36843542-f51efd1c-1d57-11e8-8c7e-f4ccd5dcc1c9.png)

- [x] Input
- [x] Text Area
- [x] Input Area
- [x] RichTextComposite
- [x] RichTextArea
- [x] FieldWithSelection
- [x] TimePicker
- [x] DatePicker
- [x] Range
- [x] Search
- [x] Dropdown
- [x] Autocomplete
- [x] InputWithOptions
- [x] Dropdown Composite
- [x] Radio Button Group
- [x] ToggleSwitch
- [x] Button
- [ ] EditableSelector
- [ ] ModalSelectorLayout
- [x] Tag

Domas (@milkyfruit) is UI owner

**Comment by shlomitc** [comment]
@hepiyellow - is this issue still relevant?
what are the required changes for `EditableSelector` and `ModalSelectorLayout`?

**Comment by milkyfruit** [comment]
I just checked both `EditableSelector seems` and `ModalSelectorLayout`.
They all use updated focus styles.

Although, `EditableSelectorLayout` list should be [selected with arrow keys](https://zpl.io/a7wkJkp), not with tabs, as described in [Wix a11y guides.](https://v9yfnh.axshare.com/#g=1&p=radio_buttons) WSR [radio group](https://wix-wix-style-react.surge.sh/?selectedKind=4.%20Selection&selectedStory=4.3%20Radio%20Button%20Group&full=0&addons=0&stories=1&panelRight=0) also doesn't work like wix guides and [Zeplin specs](https://zpl.io/blGmR5a).

Discussed it with @hepiyellow, probably it should be a separate task that would be related to all types of list items.

**Comment by shlomitc** [comment]
OK, so closing this issue and will open a separate accessibility feature request for the selection groups and specifically for the `RadioGroup` and `EditableSelector`
