### ISSUE TITLE
RadioButtonGroup

### ISSUE THREAD

**Issue by hepiyellow** [wix/wix-style-react#1497]
When `type=button` then `spacing` property has no effect.
From the storybook: (This is with spacing 40px)
![screen shot 2018-03-01 at 14 19 54](https://user-images.githubusercontent.com/6338722/36844489-a3939e68-1d5b-11e8-8205-a74cb689ad7e.png)

**Comment by argshook** [comment]
that `type="button"` is something for us to deprecate. It should be treated as separate `4.5a Advanced Toggle` component, which is defined in design system.

**Comment by shlomitc** [comment]
We will deprecate this component once the `Thumbnails` component will be created.

**Comment by hepiyellow** [comment]
Duplicate of #1545
