### ISSUE TITLE
Tags: Need to allow deleting tags with keyboard

### ISSUE THREAD

**Issue by hepiyellow** [wix/wix-style-react#1502]
Suggested solution by @milkyfruit is to enable cursor movement (left/right arrows) so that Tags can be deleted using the `backspace` key.
![tags](https://user-images.githubusercontent.com/6338722/36942814-b39782cc-1f84-11e8-9f1e-91f5c0ffef40.png)

**Comment by shlomitc** [comment]
Tags removal is possible when tabbing between them (using the x mark), so a11y wise we’re covered
