### ISSUE TITLE
DatePicker modifies global style for react-datepicker

### ISSUE THREAD

**Issue by astrauka** [wix/wix-style-react#1508]
### Summary:

DatePicker modifies [global style](https://github.com/wix/wix-style-react/blob/master/src/DatePicker/DatePicker.scss#L26) for [react-datepicker](https://github.com/Hacker0x01/react-datepicker).

### Priority:
- [ ] Blocker
- [ ] Urgent
- [x] Normal
- [ ] Minor

### Steps to reproduce:
 1. Add react-datepicker component with default styling
 2. Add DatePicker from wix style react
 3. Open react-datepicker component - it will have wix-style-react styles

### Expected behavior:

react-datepicker should not have wix-style-react styles.

### Additional notes:

Quick solution - put the global styles under DatePicker container class, react datepicker component [accepts](https://reactdatepicker.com/#example-6):

* `className`
* `calendarClassName`
* `popperClassName`
* `dayClassName`

**Comment by argshook** [comment]
this should no longer be a problem since `wix-style-react@3.0.0`.
Please reopen if im wrong
