### ISSUE TITLE
Need workaround for protractor Browser.pause() which is not working

### ISSUE THREAD

**Issue by hepiyellow** [wix/wix-style-react#1514]
Protractor `browser.pause()` is not working with node 8.
See https://github.com/angular/protractor/issues/4307

What is the workaround?
Use `setTimeout`?

**Comment by argshook** [comment]
one quickie is to `browser.sleep(5000)`

**Comment by hepiyellow** [comment]
Yep that should work.
- There is `jasmine.DEFAULT_TIMEOUT_INTERVAL`, which will show you that the test failed if it exceeds this timeout, but it doesn't matter for debugging.
- We might want to add an eslint rule that restrict `browser.sleep()`, right?

**Comment by argshook** [comment]
we can add though it's not critical imo
