### ISSUE TITLE
Adding appendToParent to Tooltip breaks tooltip testkit

### ISSUE THREAD

**Issue by naamagr** [wix/wix-style-react#1546]
### Summary:
When adding the 'appendToParent' property to wix-style-react Tooltip, the [toolTipTestkit].isShown() method returns false instead of true. 
(Without the 'appendToParent' property, this method behaves correctly).
 
### Priority:
 Normal

### Steps to reproduce:
Add appendToParent={true} to Tooltip
Simulate show trigger

### Expected behavior:
[toolTipTestkit].isShown()  = true

### Relevant Components:
[toolTipTestkit].isShown()  = false

**Comment by shlomitc** [comment]
This test passes
https://github.com/wix/wix-style-react/blob/master/src/Tooltip/Tooltip.spec.js#L330

It takes into consideration that some waiting is needed there (30ms). can you see if this is the reason?

**Comment by shlomitc** [comment]
@naamagr - poing

**Comment by shlomitc** [comment]
Closing due to no response. please re-open if still relevant
