### ISSUE TITLE
Page Header width is not synchronized with the scrollbar state correctly

### ISSUE THREAD

**Issue by Jefoss** [wix/wix-style-react#1557]
### Summary:
The page header width is not adjusted properly when the scrollbar appears/disappears from the page, and its not aligned with the content

### Steps to reproduce:
 Easiest way would probably be opening the dev tools from the bottom and dragging it manually until theres a scrollbar, and watch how the content moves but not the header.

Other way would be just have enough content on the page to have a scrollbar, and have a button or something that removes the content from the page to the point where you wont have a scrollbar, click on that button to see that the header and content are not synched

### Expected behavior:
The header width should be updated immediately to be synched with the content

### Relevant Components:
Page, Page.Header

**Comment by amiryonatan** [comment]
Fixed: https://github.com/wix/wix-style-react/pull/1564
