### ISSUE TITLE
Support like an appendToParent for <DropDown>

### ISSUE THREAD

**Issue by smokokoi** [wix/wix-style-react#1611]
We want to present the Dropdown options from a div that has overflow: auto. At the current stage, the options are being cut off by the overflow.

Here's how it would look when cut off.
![screen shot 2018-03-29 at 16 31 47](https://user-images.githubusercontent.com/29129957/38091631-c1a84394-336e-11e8-9e9c-805e1ae97ed0.png)

Attached the desired behavior (assume the containing div reaches "Close" button). 

![screen shot 2018-03-28 at 10 35 59](https://user-images.githubusercontent.com/29129957/38091395-1ccd376c-336e-11e8-8237-f1e9fa6c71f5.png)

### Priority:
- Urgent

**Comment by mykas** [comment]
fixed

**Comment by marik22312** [comment]
@mykas On what version is this fix available

**Comment by mykas** [comment]
6.56.0
