### ISSUE TITLE
datepicker position is off when opened inside modal on safari

### ISSUE THREAD

**Issue by liorur** [wix/wix-style-react#1612]
### Priority:
- [ ] Blocker
- [ ] Urgent
- [ ] Normal
- [X] Minor

### Steps to reproduce:
 1. place datepicker inside modal
 2. open on safari
@argshook

**Comment by liorur** [comment]
![screen shot 2018-03-29 at 15 45 14](https://user-images.githubusercontent.com/1437073/38091914-832ef15c-336f-11e8-8892-9c809d529f51.jpg)

**Comment by shlomitc** [comment]
Fixed in #1656. will be released in 3.1.4
