### ISSUE TITLE
12.1 Badge  Max-Width

### ISSUE THREAD

**Issue by milkyfruit** [wix/wix-style-react#1622]
[12.1 Badge ](https://wix.github.io/wix-style-react/?selectedKind=12.%20Other&selectedStory=12.1%20Badge&full=0&addons=0&stories=1&panelRight=0&addonPanel=kadirahq%2Fstorybook-addon-actions%2Factions-panel)is missing "maximum width" property.

When a maximum width is set the badge should display like this:
![image](https://user-images.githubusercontent.com/1684587/38257779-94a4f0fa-3769-11e8-99d1-e82c036d85a1.png)

In addition, the badge's total padding must be 12px including with 1px border:
![badge component qa](https://user-images.githubusercontent.com/1684587/38257954-fba8e13a-3769-11e8-9f72-a4cfa8cbdd83.png)

**Comment by shlomitc** [comment]
kind of an old issue but specs explains differently now.
it should be 100% (as it is right now), but have an ellipsis capability
https://zpl.io/VQ91QZA
![image](https://user-images.githubusercontent.com/6093192/54883504-cfbab680-4e6e-11e9-9b3c-acfc0af1ade1.png)

In same case, I would also like to fix the maximum height if possible.

**Comment by milkyfruit** [comment]
probably this was an issue for someone that badges exceed their parent container instead of showing ellipsis.

**Comment by argshook** [comment]
Another example from the channel

![Minumum Size](https://user-images.githubusercontent.com/4284659/55308004-ffb31c80-5461-11e9-91ac-4a7fa4580228.png)

@shlomitc this is getting a priority, fyi

**Comment by shlomitc** [comment]
it's currently in work here - https://github.com/wix/wix-style-react/pull/3374

**Comment by nitayneeman** [comment]
https://github.com/wix/wix-style-react/pull/3628 fixed this issue and will be available as part of WSR v6.35.0.

I'm closing it.
