### ISSUE TITLE
MultiSelect height is not correct

### ISSUE THREAD

**Issue by andriuss** [wix/wix-style-react#1630]
### Summary:
MultiSelectComposite heigh is 36px
https://wix.github.io/wix-style-react/?selectedKind=3.%20Inputs&selectedStory=3.8%20%2B%20MultiSelectComposite&full=0&addons=0&stories=1&panelRight=0

It should be 34px normal height as other input elements.
Example - https://wix.github.io/wix-style-react/?selectedKind=3.%20Inputs&selectedStory=3.1%20%2B%20Input&full=0&addons=0&stories=1&panelRight=0

### Priority:
- [ ] Minor

### Steps to reproduce:
 1. Check Storybook

### Expected behavior:
Height is consistent with input elements

### Relevant Components:
MultiSelect

**Comment by shlomitc** [comment]
Are you sure that MultiSelect is the problematic one? or maybe the Input should be 36px and not 34px.
@wuwa - can you please assist here?

**Comment by wuwa** [comment]
all should be 36px height (including the border). btw - i see multiselect as 38 right now.

**Comment by andriuss** [comment]
I am sure all the inputs should be the same height. You pick a correct height.

**Comment by argshook** [comment]
@shlomitc yes it's multiselect. it has `input` inside with `border: 0`.

that input has height 36px. multiselect has border which is 2px, and so we end up with 36 + 2 = 38

**Comment by wuwa** [comment]
why is the input with border 0? can't it be used as-is inside the multi?

**Comment by argshook** [comment]
nope. Multiselect is using `<Input/>` inside, and by default `<Input/>` has a border. if it weren't somehow set to 0, we would see blue border around multiselect and also blue border around input, so two borders.

im describing current implementation, not discussing how it should be done

**Comment by shlomitc** [comment]
Fixed in #1663 and will be released in 3.1.4

**Comment by shlomitc** [comment]
Fix failed in CI. reopening

**Comment by argshook** [comment]
fixed by #1683
