### ISSUE TITLE
Feature Request: new ButtonLink component

### ISSUE THREAD

**Issue by hepiyellow** [wix/wix-style-react#1636]
Like `<TextLink>`, I thought we should have a `ButtonLink`.
The current solution is having a `<Button>`  inside an `<a>` tag.
But that requires also overriding the UA default `<a>` styling, like `text-decoration: underline`.

**Comment by argshook** [comment]
disagree, wsr currently has those `layout` components but i think it should be invisible to consumer and only two components exposed: `Link` & `Button`. Both should handle `onClick` and `src`.

Given `src` components would render `a` with `href`.
given `onClick` components would render `button` with, well, `onClick`.
given both `src` and `onClick` components would render `a`

this is `Link` & `Button` versus `TextLink`, `TextLinkLayout`,  `Button` and `ButtonLayout`. people do use those `layout` components and we end up supporting twice as many components

**Comment by shlomitc** [comment]
ok, so let's do this in the `wix-ui` infrastructure.
Thanks

**Comment by shlomitc** [comment]
Wait - another important use case.
Sometimes, we want a different component, for example - `Link` from `react-router`.
Eventually, this `Link` component becomes an anchor, but you don't want to end up with two anchors.

How do you suggest handling that?

**Comment by argshook** [comment]
to avoid name conflict, you can `import {Link: RouteLink} from 'react-router-dom';`

to avoid double anchors we can use `this.props.children.type` inside our `Link` and in case of `a` render `span` or something

**Comment by shlomitc** [comment]
done in referred PR
