### ISSUE TITLE
ToggleSwitch stays in focus mode after clicking on it in Safari browsers

### ISSUE THREAD

**Issue by shlomitc** [wix/wix-style-react#1640]
### Summary:
ToggleSwitch stays in focus mode after clicking on it in Safari browsers

### Steps to reproduce:
* Click to turn the toggle on
* Click to turn the toggle off
* Move the mouse out of the component

### Expected behavior:
focus state is dismissed

### Actual behavior:
focus state is stays

### Relevant Components:
ToggleSwitch

**Comment by hepiyellow** [comment]
I could not reproduce with 3.1.1
but I am seeing an issue, that when focusing on the ToggleSwitch via keyboard (using tab), then it gets the hover color.

**Comment by lbelinsk** [comment]
are we talking about wsr Toggle?
We have the new one in release/4.0.0 branch, maybe it doesn't have this bug at all

**Comment by shlomitc** [comment]
Yes, looks to be resolved. I opened the issue after it sat for a while in my backlog. closing

**Comment by shlomitc** [comment]
@hepiyellow - are you able to toggle using keyboard keys? it doesn't work for me

**Comment by hepiyellow** [comment]
Nope. 
I told you. Also checkbox. 
RichTextAreaButton,
