### ISSUE TITLE
Card - Card Header without a divider gets wrong CSS

### ISSUE THREAD

**Issue by shlomitc** [wix/wix-style-react#1641]
![image](https://user-images.githubusercontent.com/6093192/37778642-21395afe-2df3-11e8-95b3-7f90488012db.png)

**Comment by cTux** [comment]
Should be:

![image](https://user-images.githubusercontent.com/873220/38545059-d56b19a0-3cb1-11e8-843c-8f85cbb21c42.png)

**Comment by shlomitc** [comment]
more or less, there is still a +- 1px on the right card that's missing
