### ISSUE TITLE
There is no MessageBoxFixedHeaderFooter.driver

### ISSUE THREAD

**Issue by dmfilipenko** [wix/wix-style-react#1689]
### Summary:
There is no MessageBoxFixedHeaderFooter.driver for tests

### Priority:
- [ ] Blocker
- [ ] Urgent
- [x] Normal
- [ ] Minor

### Expected behavior:
Should be MessageBoxFixedHeaderFooter.driver
### Relevant Components:
MessageBoxFixedHeaderFooter

**Comment by shlomitc** [comment]
Hey! Thanks for reporting. Do you think you can add a PR for this driver?

**Comment by dmfilipenko** [comment]
@shlomitc not in nearest feature

**Comment by shlomitc** [comment]
Giving it a second look, the `MessageBoxFixedHeaderFooter` component is not documented and not planned to be added as it's not defined in the design system.
It will be removed in the near future and you're suggested to use the `MessageBoxFunctionalLayout`
