### ISSUE TITLE
DatePicker position is changed when switching months

### ISSUE THREAD

**Issue by yakirn** [wix/wix-style-react#1695]
### Summary:
In some cases, when moving between months in the DatePicker component, the component's position on the page changes, this causes the user to "miss" the next click on the button.
This happens without any scrolling actions.

### Priority:
- [ ] Blocker
- [x] Urgent
- [ ] Normal
- [ ] Minor

### Steps to reproduce:
See this [video](https://drive.google.com/file/d/1xRs1IKwc9e3Srd_LRyAhvO8aiupw7Ke5/view?usp=sharing)

### Expected behavior:

- As long as there's no scrolling, the DatePicker popup should remain in the same position.
- The calculation of where to open should consider the largest and smallest possible sizes of the pop up.
- API should support opening direction as prop (like in Popover component)

### Relevant Components:
`DateInput`

**Comment by shlomitc** [comment]
Fixed in version `4.11.0`. Closing.
