### ISSUE TITLE
Remove shouldCloseOnOverlayClick from Modal component to simplify the API

### ISSUE THREAD

**Issue by alonbt** [wix/wix-style-react#1706]
https://github.com/wix/wix-style-react/blob/master/src/Modal/Modal.js#L122

Consider writing this line instead: 
```
 <ReactModal shouldCloseOnOverlayClick={typeof onRequestClose === 'Function'}
```

This will reduce the need for `shouldCloseOnOverlayClick` prop in `<Modal />`. I can't think of a specific need for it that might require it to be independent.

**Comment by shlomitc** [comment]
it's a nice suggestion, but a breaking change and the default behavior is not that critical, so I'm closing.
