### ISSUE TITLE
[Modal] scrollableContent property does not work well with MessageBoxFunctionalLayout

### ISSUE THREAD

**Issue by xmityaz** [wix/wix-style-react#1712]
### Summary:
There is no way (without hacks) to set a scrollable container inside a content of `MessageBoxFunctionalLayout`

### Priority:
- [x] Normal

### Steps to reproduce:
 1. Create a `Modal` with `MessageBoxFunctionalLayout` inside (similar to [demo example](https://wix.github.io/wix-style-react/?selectedKind=9.%20Modals&selectedStory=Modal&full=0&addons=0&stories=1&panelRight=0))
 2. set `scrollableContent={true}` and `maxHeight="500px"` to the `Modal`
 3. Add a lot of content to the `MessageBoxFunctionalLayout` component so the modal scroll appears 
4. The modal scroll looks this way:
![screen shot 2018-05-05 at 12 05 41 pm](https://user-images.githubusercontent.com/10046613/39661591-aceb508a-505c-11e8-9c8c-543aaf4b2071.png)

### Expected behavior:
Modal has fixed header (would be great to have the ability to set a fixed footer as well)
![screen shot 2018-05-05 at 12 07 31 pm](https://user-images.githubusercontent.com/10046613/39661601-ece0140a-505c-11e8-976d-d63e66faaabf.png)

### Relevant Components:
Modal, MessageBoxFunctionalLayout

**Comment by shlomitc** [comment]
A `maxHeight` prop was added to the `MessageBoxFunctionalLayout` component in this commit:
https://github.com/wix/wix-style-react/commit/8c133ce161e93236fa7b1364c3be8469950c04b4#diff-fb327c5ed05f909b640bb5b0e134b369

So you can now make the internal content scrollable. Try it out and if there are still issues, please re-open.
Thanks
