### ISSUE TITLE
<TextLink/> does not support disabled prop

### ISSUE THREAD

**Issue by Wo1v3r** [wix/wix-style-react#1729]
### Priority:
- [ ] Blocker
- [ ] Urgent
- [x] Normal
- [ ] Minor

### Steps to reproduce:
 1.  Pass disabled prop to <TextLink/>

### Expected behavior:
 1. Disable onClick and cursor:pointer
 2. Show disabled design

### Relevant Components:
<TextLink/>

**Comment by romabelka** [comment]
Can't reproduce this

**Comment by shlomitc** [comment]
Fixed here https://github.com/wix/wix-style-react/pull/1798
