### ISSUE TITLE
Remove width property from input

### ISSUE THREAD

**Issue by yakirn** [wix/wix-style-react#1734]
### Summary:
This property is not working, also changing the component's width should be done via it's container.

### Priority:
- [ ] Blocker
- [ ] Urgent
- [ ] Normal
- [x] Minor

### Relevant Components:
Input, TextField

**Comment by hepiyellow** [comment]
So what it means, is that we want to remove the `width` property from the <Input>.

**Comment by yakirn** [comment]
I'm fine with @hepiyellow 's suggestion. Either having a working `width` or have it removed is fine by me. The current state isn't though.
Cheers guys!

**Comment by shlomitc** [comment]
Let's remove it,  please change the title

**Comment by lbelinsk** [comment]
Done. Thanks @falinsky
