### ISSUE TITLE
Checkbox does not work

### ISSUE THREAD

**Issue by Lomse** [wix/wix-style-react#1739]
### Summary:
Checkbox turns unchecked immediately after checking it
### Priority:
- [x] Blocker
- [ ] Urgent
- [ ] Normal
- [ ] Minor

### Steps to reproduce:
 1.I imported the Checkbox component `import Checkbox from 'wix-style-react/Checkbox'`
 2. I added the component to my stateless component as shown below
```
import React from 'react'

import Checkbox from 'wix-style-react/Checkbox'

const Choice = props => {
	return (
		<div>
			<Checkbox
				id="car"
				checked={false}
				dataHook="storybook-checkbox"
				onChange={_ref2 => (_ref2.target.checked ? 'Checked' : 'Unchecked')}>
				Car
			</Checkbox>
            <hr className="divider-long" style={{ margin: '10px 0' }} />
			<Checkbox
				id="bike"
				checked={false}
				dataHook="storybook-checkbox"
				onChange={_ref2 => (_ref2.target.checked ? 'Checked' : 'Unchecked')}>
				Bike
			</Checkbox>
		</div>
	)
}

export default Choice
```
 3. I made a short screencast that i have uploaded here. Sorry, I had to zip it first since github does not support `.mov` files.
[screencast.zip](https://github.com/wix/wix-style-react/files/2009621/screencast.zip)

### Expected behavior:
Checkbox should stay checked after checking it or unchecked after unchecking it.

### Relevant Components:
Checkbox

**Comment by hepiyellow** [comment]
Checkbox is a controlled component (stateless). You should manage the state
yourself.

**Comment by Lomse** [comment]
Thanks @hepiyellow  for the quick response. 
I'm logging the `_ref2.target` from the `onChange` event and below is what I get in the console:  

`<input type="checkbox" id="car" value="on" style="display: none;">`
Clearly, it doesn't have a `checked` property.

Say i have something like this: 

```
import React, { Component } from 'react'

import Checkbox from 'wix-style-react/Checkbox'

class Choice extends Component {
	constructor(){
            super()
        }
       render(){
           return (
		<div>
			<Checkbox
				id="car"
				checked={false}
				dataHook="storybook-checkbox"
				onChange={_ref2 => (_ref2.target.checked ? 'Checked' : 'Unchecked')}>
				Car
			</Checkbox>
            <hr className="divider-long" style={{ margin: '10px 0' }} />
			<Checkbox
				id="bike"
				checked={false}
				dataHook="storybook-checkbox"
				onChange={_ref2 => (_ref2.target.checked ? 'Checked' : 'Unchecked')}>
				Bike
			</Checkbox>
		</div>
	)
       }
}

export default Choice
```
How can I achieve what you are suggesting? Thanks again.

**Comment by Lomse** [comment]
@hepiyellow  Not sure what I'm doing what i'm doing wrong.
Could you please share a working code? I would appreciate a lot. thanks

**Comment by hepiyellow** [comment]
I didn't run this, but this is the basic idea:
```js
import React, { Component } from 'react'

import Checkbox from 'wix-style-react/Checkbox'

class Choice extends Component {
  constructor(props) {
    super(props);

    this.state = {carChecked: false, bikeChecked: false}
  }
  render() {
    return (
      <div>
        <Checkbox
          id="car"
          checked={this.state.carChecked}
          onChange={e => this.setState({carChecked:e.target.checked})}>
          Car
			  </Checkbox>
        <hr className="divider-long" style={{ margin: '10px 0' }} />
        <Checkbox
          id="bike"
          checked={this.state.bikeChecked}
          onChange={e => this.setState({bikeChecked:e.target.checked})}>>
          Bike
			</Checkbox>
      </div>
    )
  }
}

export default Choice;
```

**Comment by hepiyellow** [comment]
Maybe this read will make it clearer:
 * https://gist.github.com/markerikson/d71cfc81687f11609d2559e8daee10cc
 * The React Docs one might not be so clear: https://reactjs.org/docs/uncontrolled-components.html

**Comment by hepiyellow** [comment]
The term "Controlled" and "Uncontrolled" are often confusing. I prefer : 
"Controlled" =>  "Stateless"
"Uncontrolled" =>"Stateful"

**Comment by Lomse** [comment]
This looks promising thanks @hepiyellow . What if the checkboxes are generated programmatically (you have no knowledge of the items until they are rendered)? Initializing and keeping track of the states would be tricky. Thoughts?

**Comment by hepiyellow** [comment]
Store a state array with matching indexes to the generated checkboxes.

You can also create an Uncontrolled version of the checkbox (with checked state),
And then use it to render a list of checkboxes.
In order to query the state of an Uncontrolled checkbox, you need to have a ref to it. See https://reactjs.org/docs/refs-and-the-dom.html <https://reactjs.org/docs/refs-and-the-dom.html>

**Comment by Lomse** [comment]
@hepiyellow Thanks for the help. Much appreciated!
