### ISSUE TITLE
TextField to accept Dropdown without warning

### ISSUE THREAD

**Issue by TomasRup** [wix/wix-style-react#1743]
### Summary:
I am getting warning:
```
Warning: Failed prop type: TextField should have children of the following types in this order: Label (OPTIONAL), ThemedInput (ONCE)
    in TextField (created by PaymentSchedule)
    in PaymentSchedule (created by Unknown)
    in div (created by Unknown)
    in div (created by Container)
    in div (created by Content)
    in Content (created by Container)
    in div (created by Card)
    in Card (created by Container)
    in Container (created by Unknown)
    in Unknown (created by Unknown)
    in div (created by Unknown)
    in div (created by Unknown)
    in div (created by Page)
    in div (created by Page)
    in div (created by Page)
```

which does not make sense in my use case:
```ts
  <TextField info="Add text here">
    <Label appearance={LABELS_APPEARANCE}>
      Payment schedule
    </Label>
    <Dropdown
      options={pricingOptions}
      selectedId={getPaymentOptionId(recurring)}
      placeholder="Payment schedule"
      />
  </TextField>
```
i.e. I am using a `Dropdown` instead of `Input` and it works just fine

### Priority:
- [ ] Blocker
- [ ] Urgent
- [ ] Normal
- [x] Minor

### Steps to reproduce:
Code added

### Expected behavior:
No warning

### Relevant Components:
`TextField` `Dropdown` `Input`

**Comment by hepiyellow** [comment]
TextField is not for dropdown (in UX semantics)

Anyways, we should have a generic <FieldLabel> component. 

Do you want to contribute?

**Comment by TomasRup** [comment]
hey, after our project deadline - yes. But that will be on ~July.

**Comment by shlomitc** [comment]
`TextField` component and all similar compositions are about to die soon, so we won't be fixing this issue in those components.
However, we exposed a new component called `FormField` which makes compositions easy without any prop validation
https://wix-wix-style-react.surge.sh/?selectedKind=Components&selectedStory=FormField&full=0&addons=0&stories=1&panelRight=0

Feel free to try it out and tell me if it works for you.
Thanks
