### ISSUE TITLE
Importing composites is ugly

### ISSUE THREAD

**Issue by TomasRup** [wix/wix-style-react#1744]
### Summary:
I have to do imports for composites like `import FieldWithSelectionComposite from 'wix-style-react/dist/src/Composite/FieldWithSelectionComposite/FieldWithSelectionComposite'`

### Priority:
- [ ] Blocker
- [ ] Urgent
- [ ] Normal
- [x] Minor

### Expected behavior:
`import FieldWithSelectionComposite from 'wix-style-react/FieldWithSelectionComposite'`

### Relevant Components:
`FieldWithSelectionComposite`, `Composite`

**Comment by shlomitc** [comment]
this composition is going to be deprecated soon, so not going to be fixed.
closing, thanks.
