### ISSUE TITLE
PopoverMenu throws error

### ISSUE THREAD

**Issue by david-pe** [wix/wix-style-react#1752]
### Summary:
When clicking on a menu item that unmounts the Tooltip parent we get an error in the console (below)

### Priority:
- [ ] Blocker
- [ ] Urgent
- [X] Normal
- [ ] Minor

### Steps to reproduce:
 1. Create a PopoverMenu that unmounts its parent on clicking an item
 2. Click on the menu item

**AR:
Uncaught TypeError: Cannot read property 'parentElement' of null
    at TooltipContainerStrategy.getContainer (TooltipContainerStrategy.js:54)
    at Tooltip._getContainer (Tooltip.js:208)
    at hideLazy (Tooltip.js:568)** 

### Expected behavior:
No errors in console

### Relevant Components:
<PopoverMenu />

**Comment by argshook** [comment]
hello! could you please share code example that reproduces the issue?

**Comment by david-pe** [comment]
@argshook here's pseudo code of what should reproduce this:

`<PopoverMenu
        appendToParent
      >
        <PopoverMenuItem
          onClick={() => goToSomeOtherPage()}
          icon={<Navigate />}
          text={t('gosomewhere')}
        />
      </PopoverMenu>
`

**Comment by shlomitc** [comment]
Fixed here
https://github.com/wix/wix-style-react/pull/2133
