### ISSUE TITLE
Is the demo page down?

### ISSUE THREAD

**Issue by Lomse** [wix/wix-style-react#1756]
### Summary:
I'm not able to access the demo. Below is what the console is showing 
<img width="1680" alt="screen shot 2018-05-23 at 11 53 05 am" src="https://user-images.githubusercontent.com/4754182/40422934-6f4689fc-5e80-11e8-995a-390d4ab80a02.png">

### Priority:
- [x] Blocker
- [ ] Urgent
- [ ] Normal
- [ ] Minor

### Steps to reproduce:
 1. Visit https://github.com/wix/wix-style-react
 2. Then click the demo link on the page

### Expected behavior:
I should be redirected to the demo page

**Comment by shlomitc** [comment]
it works on my machine. try to clear cache / open from incognito

**Comment by Lomse** [comment]
@shlomitc thanks for the quick response. I'm actually using incognito

**Comment by Lomse** [comment]
The issue is probably from my side as I changed internet connection and it is working. Sorry for the trouble
