### ISSUE TITLE
DropdownLayout - options highlighting behavior not according to spec

### ISSUE THREAD

**Issue by tzvikaf** [wix/wix-style-react#1761]
when no options are selected and the dropdown get opened, 
an arbitrary option get the highlight,

the highlight should appear (when dropdown open) on:
- first selected option
- if no option selected - on the first option

**Comment by lbelinsk** [comment]
This is an issue that occurs when using `<InputWithOptions/>` with `shouldCloseOnSelect=false` (multiSelection mode)

**Comment by shlomitc** [comment]
should be ok now
