### ISSUE TITLE
<MultiSelectCheckbox/> - improvements and features request

### ISSUE THREAD

**Issue by lbelinsk** [wix/wix-style-react#1763]
- [ ] Rename MultiSelectCheckbox to MultiSelect and find a different name to MultiSelect (maybe InputWithTagstags). Should be indexed according to the zeplin.

- [ ] Support Error state

- [ ] Select All feature - Add optional "All" checkbox item that can mark all of the options.
          - Add a boolean prop `showAll` which is false by default.
          - When visible, it will always be the first item (not fixed sticky)
          - Add `onSelectAll` callback and `isAllSelected` boolean prop.

**Comment by hepiyellow** [comment]
Old multiselect can be either Tags or TagsInput.

**Comment by shlomitc** [comment]
1. what do you mean by `showAll` in the input? meaning no ellipsis?
2. didn't get the "when visible..." part

**Comment by shlomitc** [comment]
won't be added any time soon - will reopen by demand
