### ISSUE TITLE
<MultiSelect> (Tags) - BUG - hover background flipped in a certain scenario

### ISSUE THREAD

**Issue by hepiyellow** [wix/wix-style-react#1786]
How to reproduce:

- Go to storybook https://wix-wix-style-react.surge.sh/?selectedKind=3.%20Inputs&selectedStory=3.8%20Tags&full=0&addons=0&stories=1&panelRight=0
- Click on the Tags input
- Start typing 'a' and select Alabama
- Click on the input area and keep the mouse hovering over the input
- press the "delete" key
- hover outside the input

hover is flipped

**Comment by mosheKerbel** [comment]
@hepiyellow could you check if it is still happening?
i failed to reproduce it.

**Comment by hepiyellow** [comment]
Can not reproduce now.
