### ISSUE TITLE
`<Search/>` - v4.1.0 - BUG!! stays collapsed when navigated by keyboard

### ISSUE THREAD

**Issue by hepiyellow** [wix/wix-style-react#1797]
### Priority:
- [ x ] Blocker
- [ ] Urgent
- [ ] Normal
- [ ] Minor

### Steps to reproduce:
BUG#1
 1. Go to https://wix-wix-style-react.surge.sh/?selectedKind=3.%20Inputs&selectedStory=3.9%20Search&full=0&addons=0&stories=1&panelRight=0
 2.Turn on `expandable`
 3.Click search box - nothing happens, no cursor. (this might be a playground BUG, @dotansimha please investigate.

BUG#2
 1. Refresh page.
 2. Enter some text
 3. toggle expandable.
 4. click on text input
 5. delete the text
 6. click outside the Search (it collapses)
 7. press tab (it gets focus. BTW: should it expand automatically when focused?)
 8. press space

### Expected behavior:

BUG2 - I was expecting the search to expand. It didn't, but I see options and the 'x' button.

Thoughts:
I just thought these might have something to do with the fact that the playground updates the component. I don't know it it actually unmounts the component and mounts it again. If it doesn't and it does an update (componentWillUpdate). Then it might be that we don't reset the state properly.
This means that this is not such a bad bug, since the use-case is rare. But I think this usa-case it somehow reasonable, and needs to be fixed.

**Comment by shlomitc** [comment]
won't be fixed any time soon - will reopen on request
