### ISSUE TITLE
`<FloatingHelper/>` - placement `bottom-end` failing only in jsdom tests

### ISSUE THREAD

**Issue by hepiyellow** [wix/wix-style-react#1812]
It happens also with other placement values which include the '-end' or '-start' suffix.

Caused by the createRange polyfill in wix-ui-core's Popover.
https://github.com/wix/wix-ui/blob/153c2a71fb19bc816f91256701a0bf8940f128e8/packages/wix-ui-core/src/components/Popover/Popover.tsx#L23

- [ ] Need to find a way to include this pollyfill only in specific test.
- [ ] Need to add test for placement 'bottom-end'
- [ ] Need to add to FloatingHelper's story, a note that a polly fill might be needed, and instructions on where to take if from. See the tooltip's testkit documentation for an example.

**Comment by shlomitc** [comment]
won't be fixed
