### ISSUE TITLE
<MultiSelect> invokes `onManuallyInput` callback twice

### ISSUE THREAD

**Issue by ChenRoth** [wix/wix-style-react#1841]
### Summary:

on typing input and pressing Enter, the prop passed to `onManuallyInput` is called twice

### Priority:
- [ ] Blocker
- [ ] Urgent
- [X] Normal
- [ ] Minor

### Steps to reproduce:
 1. pass a `console.log` to `onManuallyInput`
 2. see if message is printed twice in console

### Expected behavior:

prop should be called once

### Relevant Components:

MultiSelect

### Additional notes:

use the examples to see "NOW" printed twice in console:

https://wix-wix-style-react.surge.sh/?selectedKind=3.%20Inputs&selectedStory=3.8%20Tags&full=0&addons=0&stories=1&panelRight=0

**Comment by ChenRoth** [comment]
should I take this?

**Comment by shlomitc** [comment]
already in progress
https://github.com/wix/wix-style-react/pull/1831

**Comment by hepiyellow** [comment]
A solution within #1831 was merged.
