### ISSUE TITLE
<MultiSelect> with maxNumRows always shows a scrollbar

### ISSUE THREAD

**Issue by ChenRoth** [wix/wix-style-react#1842]
### Summary:

component currently always shows a scrollbar when passed `maxNumRows`, even when not needed

### Priority:
- [ ] Blocker
- [ ] Urgent
- [X] Normal
- [ ] Minor

### Steps to reproduce:
 1. specify any number of `maxNumRows`
 2. see how the scrollbar is always there

### Expected behavior:

show a scrollbar only when exceeding `maxNumRows`

### Relevant Components:

InputWithTags

### Additional notes:

https://wix-wix-style-react.surge.sh/?selectedKind=3.%20Inputs&selectedStory=3.8%20Tags&full=0&addons=0&stories=1&panelRight=0

`Limited num rows` example demonstrates the issue

**Comment by ChenRoth** [comment]
I can take this, I already know how to fix it

**Comment by shlomitc** [comment]
can you add a screenshot? I don't see it on my machine (mac, chrome)

**Comment by ChenRoth** [comment]
![screen shot 2018-06-18 at 18 22 41](https://user-images.githubusercontent.com/36155213/41545776-a4f7e132-7324-11e8-8a22-ba062ecf594a.png)
![screen shot 2018-06-18 at 18 23 29](https://user-images.githubusercontent.com/36155213/41545820-b9acebcc-7324-11e8-872f-d1d4375a3095.png)

**Comment by ChenRoth** [comment]
this is how i think it should be
![screen shot 2018-06-18 at 18 23 58](https://user-images.githubusercontent.com/36155213/41545844-caba7286-7324-11e8-9dcc-fe92df578319.png)
![screen shot 2018-06-18 at 18 24 17](https://user-images.githubusercontent.com/36155213/41545872-d439e5b2-7324-11e8-8b75-f53386d133ae.png)

**Comment by ChenRoth** [comment]
fixed in #1843
