### ISSUE TITLE
<MultiSelect> moving to the next line for input even when there's plenty of space

### ISSUE THREAD

**Issue by ChenRoth** [wix/wix-style-react#1845]
### Summary:

Currently, `<MultiSelect>` uses an <Input> with a minimum width, thereby pushing the input to the next row even when there's plenty of space left in the current row

I suggest parting with `<Input>` and instead use a contenteditable span which can be used as a flexible inline input and no tricks such as hidden divs

### Priority:
- [ ] Blocker
- [x] Urgent
- [ ] Normal
- [ ] Minor

### Steps to reproduce:
use the examples in storybook and see how the input is pushed down

![screen shot 2018-06-18 at 19 09 08](https://user-images.githubusercontent.com/36155213/41548339-5f4382b6-732b-11e8-96e2-02ae6d423a8b.png)

### Expected behavior:

Allow the user to type next to the last tag (until the input is too long and then it'd be natural to push the input down a row)

### Relevant Components:

InputWithTags

**Comment by ChenRoth** [comment]
should i take it?

**Comment by shlomitc** [comment]
It's an interesting idea, but take into consideration it might be a bit tricky regarding keyboard events, styling, typography, etc...
Anyway, I'll be happy to receive a PR for that.

Thanks!

**Comment by gilalroy** [comment]
This is currently an issue in Automations. @shlomitc Can you prioritize this? 
![2019-02-06_11-19-32](https://user-images.githubusercontent.com/3962248/52331576-368c2980-2a01-11e9-9d1b-c9822df30c87.png)

**Comment by shlomitc** [comment]
Fixed in this PR https://github.com/wix/wix-style-react/pull/3146
