### ISSUE TITLE
Broken storybook code examples

### ISSUE THREAD

**Issue by shlomitc** [wix/wix-style-react#1850]
###  displayName  (`<WixComponent/>`):
- [X] LinearProgressBar
- [ ] Label -- not automated
- [X] Add Item
- [ ] ButtonWithOptions -- not automated
- [X] TextLink
- [ ] PopoverMenu -- not automated
- [ ] Notification -- not automated
- [X] FloatingHelper
- [ ] FloatingHelper.Content -- complex, codeExample comes from minified wix-ui-backoffice
- [X] SectionHelper
- [X] ModalSelectorLayout
- [X] Tag
- [X] Table

### withFocusable:
- [ ] FieldWithSelection (`<WithFocusable(Checkbox)`) -- not automated
- [ ] Popover (`<WithFocusable(Button)>`) -- not automated

### Inheritance:
- [X] MultiSelectCheckbox (`<InputWithOptions`)

### icons:
- [X] Button with prefix/suffix 
(` prefixIcon={<function(e){return a.default.createElement(r.default,o({viewBox:"0 0 360 227.3"},e),a.default.createElement("g",null,a.default.createElement("path",{fill:"currentColor",d:"M358 44.7L313.7 1.6 183.4 135.8 45.3 1.6 2.3 46l178.4 171.4 4.9 4.8z"})))} />}`)

edit(arijus): i edited your comment with changes to track progress

**Comment by argshook** [comment]
@shlomitc fyi, i edited your original comment with updates
