### ISSUE TITLE
v5 breaking changes suggestions

### ISSUE THREAD

**Issue by shlomitc** [wix/wix-style-react#1856]
Please edit this comment with things to go into wix-style-react@5.0.0

branch [version_5-alpha.x](https://github.com/wix/wix-style-react/tree/version_5-alpha.x)

| # | scope | description | merged to v5 branch |
| --- | --- | --- | --- |
| 1 | `<Checkbox/>` | remove the `large` size prop and the `active` prop. https://github.com/wix/wix-style-react/pull/2089 | true |
| 2 | `<Icons/>` | remove old icons and replaces with `icons-new`. https://github.com/wix/wix-style-react/pull/2090 | true |
| 3 | `<Button/>` | remove the `withNewIcons` make it true by default. https://github.com/wix/wix-style-react/pull/2089 | true |
| 4 | `<DataTable/>` | remove the `newDesign` flag from the `<DataTable/>` component and apply it as default https://github.com/wix/wix-style-react/pull/2091 | true |
| 5 | `<Heading/>` | new typography | true |
| 6 | `<MultiSelect/>` | deprecated `maxHeight` | true |
| 7 | `<Row/>` & `<Col/>` | grid without `* { box-sizing: border-box; }` https://github.com/wix/wix-style-react/pull/2053 | true |
| 8 | `<SideBar/>` & `<LanguagePicker/>` | remove deprecated components https://github.com/wix/wix-style-react/pull/2063 partly done, removed only docs but not components themselves | true |
| 9 | `<Grid/>` | remove Card export from grid | true |

**Comment by Faradey27** [comment]
- remove old icons

**Comment by argshook** [comment]
guildweek is working on TimeInput, it should be ready for v5.
breaking changes are some API and name change - TimePicker -> TimeInput

**Comment by shlomitc** [comment]
@argshook - let's try not to make it a breaking change. It's just a new component. Currently, the name `TimePicker` isn't in use so we should be ok. If we want to call it `TimeInput` later, then that's acceptable as a breaking change.

**Comment by argshook** [comment]
if we're going to use TimeInput from wix-ui-core, it's gonna be a breaking change since we no longer use moment.js

**Comment by shlomitc** [comment]
We are going to use `TimePicker` from `wix-ui-core`, which is a new component because the one we have in WSR is called `TimeInput`.
when we add `TimePicker`, we can remove `TimeInput` from the docs and call it *deprecated* (but not remove it from the library yet).

In v5 - we will remove the old `TimeInput` component, rename `TimePicker` as `TimeInput` and have a migration guide for those who used `TimeInput`

**Comment by lbelinsk** [comment]
A lot of new stuff for one version :)
Maybe buttons can be left for next major as this is going to be the focus for the next marathon project.
Le'ts try to finish everything maybe (without the buttons) in 2 weeks time, then we can release an alpha

**Comment by shlomitc** [comment]
@lbelinsk - the Button is really small. just removing a flag. this means new icons are not used by default.

**Comment by lbelinsk** [comment]
Text has no breaking changes, only Heading.

**Comment by lbelinsk** [comment]
New branch was created - version_5-alpha.x
6. Heading new typography - Done and merged into the release branch

**Comment by Faradey27** [comment]
Working on 1,2,3,4,6,8,9

**Comment by Faradey27** [comment]
<MultiSelect/> | deprecated maxHeight - i see this in master

**Comment by Faradey27** [comment]
@shlomitc ok, thats was the question) should we just deprecate here or remove

**Comment by shlomitc** [comment]
remove

**Comment by shlomitc** [comment]
Done. Thank you all everyone. See you in v6
