### ISSUE TITLE
consider upgrading dateFns to 2.0.0

### ISSUE THREAD

**Issue by argshook** [wix/wix-style-react#1857]
current `DatePicker` uses `"date-fns": "^1.29.0"` library for date
formatting. however this version doesn't support enough format patterns,
for example long localized dates.

version `'2.0.0-alpha.10'` does support it that, as it follows [Unicode
technical standard #35](https://www.unicode.org/reports/tr35/tr35-dates.html#Date_Field_Symbol_Table)

since it's major version, there are some [breaking
changes](https://github.com/date-fns/date-fns/blob/master/CHANGELOG.md#changed)

those need to be addressed in [`DatePicker` component](https://github.com/wix/wix-style-react/tree/master/src/DatePicker)

**Comment by shlomitc** [comment]
duplicate and old
