### ISSUE TITLE
X button is skewed <MessageBox> in Safari 10.1.2

### ISSUE THREAD

**Issue by ChenRoth** [wix/wix-style-react#1861]
### Summary:
![screen shot 2018-06-20 at 15 00 07](https://user-images.githubusercontent.com/36155213/41657078-cccadb16-749a-11e8-8918-cf262c5181cf.png)

### Priority:
- [ ] Blocker
- [X] Urgent
- [ ] Normal
- [ ] Minor

### Steps to reproduce:
 1. open the examples https://wix-wix-style-react.surge.sh/?selectedKind=9.%20Modals&selectedStory=MessageBox&full=0&addons=0&stories=1&panelRight=0 on Safari 10.1.2

### Expected behavior:
![screen shot 2018-06-20 at 15 02 39](https://user-images.githubusercontent.com/36155213/41657129-02c39bb8-749b-11e8-92aa-2facaa8b41e5.png)

### Relevant Components:
HeaderLayout

### Additional notes:
This can be fixed by applying `margin: 0 auto` to the svg element
unfortunately, Icon component doesn't accept any styling props

**Comment by shlomitc** [comment]
The close button implementation in this component was changed in the latest version, can you please check if it still happens?

**Comment by shlomitc** [comment]
ping?

**Comment by ChenRoth** [comment]
i can't check the page in production right now, but WSR's storybook seems ok
