### ISSUE TITLE
span in RadioButton behaves differently in Safari 10.1.2

### ISSUE THREAD

**Issue by ChenRoth** [wix/wix-style-react#1863]
### Summary:

content in button is aligned to the left in Safari, instead of center

![screen shot 2018-06-20 at 17 42 30](https://user-images.githubusercontent.com/36155213/41665768-73f68c30-74b1-11e8-9ffb-8f9651010f8d.png)

### Priority:
- [ ] Blocker
- [ ] Urgent
- [X] Normal
- [ ] Minor

### Steps to reproduce:
 1. https://wix-wix-style-react.surge.sh/?selectedKind=4.%20Selection&selectedStory=4.3%20Radio%20Button%20Group&full=0&addons=0&stories=1&panelRight=0
 2. set to display: horizontal, type: button

### Expected behavior:

![screen shot 2018-06-20 at 17 42 26](https://user-images.githubusercontent.com/36155213/41665757-67483cea-74b1-11e8-86c5-4b9bf3ed16c9.png)

### Relevant Components:

RadioButton

### Additional notes:

applying `margin: 0 auto;` to the span inside `RadioButton` would resolve this.

**Comment by shlomitc** [comment]
These Radio Buttons are soon to be deprecated when the `AdvancedToggle` component will be introduced, so I don't think it worth improving it, but a small PR will be merged if introduced.

![image](https://user-images.githubusercontent.com/6093192/41672032-81ede850-74c1-11e8-95e6-6f81ba8aeb95.png)


Thanks!

**Comment by shlomitc** [comment]
we have the new [`<SegmentedToggle/>`](https://wix-wix-style-react.surge.sh/?selectedKind=4.%20Selection&selectedStory=4.5%20SegmentedToggle&full=0&addons=0&stories=1&panelRight=0) component implemented and the old button variation is about to get deprecated.

Please use the new component.
