### ISSUE TITLE
IconWithOptions

### ISSUE THREAD

**Issue by Shaniko** [wix/wix-style-react#1868]
### Summary:
When using dropDirectionUp + small icon => cant click an option, the dropdownLayout closes too fast

### Priority:
- [ ] Blocker
- [ ] Urgent
- [ ] Normal
- [ ] Minor

### Steps to reproduce:
 1. IconWithOptions
 2. please use dropDirectionUp, and choose a small icon
 3. try to click an option from the list 

### Expected behavior:
You can reach an option with a reasonable time

### Relevant Components:
IconWithOptions

**Comment by shlomitc** [comment]
In the near future, we plan on ditching this component.
It is very much opinionated and doesn't allow enough customization.

We are going with the approach of letting the consumer control the open/close logic with some useful components.

so here is a snippet showing how to combine a `Tooltip` with a `DropdownLayout`, giving you the control to configure the `hideDelay` and close immediately.

```jsx
import React from 'react';
import Tooltip from 'wix-style-react/Tooltip';
import DropdownLayout from 'wix-style-react/DropdownLayout';
import Download from 'wix-style-react/new-icons/Download';

class IconWithOptions extends React.Component {
  tooltipRef = null;

  _hideTooltipOnSelection = () => {
    this.tooltipRef.hide({ hideDelay: 0 });
  };

  render() {
    return (
      <Tooltip
        ref={r => (this.tooltipRef = r)}
        placement="bottom"
        alignment="center"
        padding={'9px 0 15px 0'}
        hideDelay={500}
        content={
          <DropdownLayout
            visible
            inContainer
            onSelect={this._hideTooltipOnSelection}
            options={[
              { id: 0, value: 'Option 1' },
              { id: 1, value: 'Option 2' },
            ]}
          />
        }
      >
        <Download>hover</Download>
      </Tooltip>
    );
  }
}

```
