### ISSUE TITLE
Tooltip total browser tab crash

### ISSUE THREAD

**Issue by argshook** [wix/wix-style-react#1883]
when there is no space in browser window to show whole tooltip, the tab crashes, cpu spikes, infinite loop somewhere

steps to reproduce:
1. open https://wix-wix-style-react.surge.sh/?selectedKind=7.%20Tooltips&selectedStory=7.1.%20Tooltip&full=0&addons=0&stories=1&panelRight=0
1. in text input, copy paste some long text
1. resize browser window to the size that text shouldn't fit

expected:
tooltip, even if doesn't fit entire screen, should be visible

actual:
tab crashes, cpu spikes hogging entire system

additional:
reproduction possible not necessarily with long text, it seems to consistently crash browser when a portion of tooltip should appear out of bounds. code can be as simple as:
```jsx
  <Tooltip content="hello some text">
    <div>Right Center</div>
  </Tooltip>;
```

this is pretty bad, a tooltip near the edge of screen could kill entire page, need to investigate

**Comment by shlomitc** [comment]
Is this a new issue caused by latest changes?

**Comment by argshook** [comment]
i don't know, just noticed it yesterday while working on Field (which has info icon with tooltip)

**Comment by shlomitc** [comment]
Please see if it was broken also in the previous WSR version (before tooltip changes)

**Comment by argshook** [comment]
@shlomitc yes, seems related. after reverting c0880aeea06a85e825d471bd5811f4c560b3608b i can no longer reproduce
@Faradey27 please take a look if you can, it was your change so you know best
