### ISSUE TITLE
Tooltip causes Edge to freeze

### ISSUE THREAD

**Issue by yakirn** [wix/wix-style-react#1888]
### Summary:
In Edge, Hovering over a tooltip causes the browser to script. A message "wix.com is not responding due to a long running script" is displayed to the user.
### Priority:
- [x] Blocker
- [ ] Urgent
- [ ] Normal
- [ ] Minor

### Steps to reproduce:
 1. Render a tooltip with some content, and a child
 2. Hover over the tooltip's child
 3. On Edge: App is stuck, a message is displayed about a long running script.

### Expected behavior:
Tooltip should be displayed on all browsers. App should respond well.

### Relevant Components:
Tooltip

### Additional notes:
Downgrading to v4.1.3 solves the issue
react and react-dom version: 15.6.2
I can provide a wix-private repo with the problem

**Comment by argshook** [comment]
most probably same as #1883

**Comment by shlomitc** [comment]
@argshook, please revert the relevant commit as a hot fix

**Comment by argshook** [comment]
@yakirn fyi, 4.3.1 was released with a fix

**Comment by yakirn** [comment]
Thanks @argshook ! is it a rollback, or should support react 16?

**Comment by argshook** [comment]
@yakirn unfortunately it's a rollback because not only edge is affected. A temporary one, i hope

**Comment by yakirn** [comment]
OK, thanks for the quick response!
