### ISSUE TITLE
<Dropdown /> should trigger an onChange event when invoking onSelect

### ISSUE THREAD

**Issue by ChenRoth** [wix/wix-style-react#1897]
### Summary:

I strongly recommend that when`onSelect` is invoked, it should bubble up an `onChange` event, similarly to standard input elements, and even WSR's own `<Input />`

this would maintain a consistent event behaviour among components and allow the developer to make use of the selection outside the component's boundaries.

### Priority:
- [ ] Blocker
- [X] Urgent
- [ ] Normal
- [ ] Minor

### Expected behavior:
`onSelect` would actually be `onChange`, and instead of just passing an `{id, value}` object, it should be an `Event`-esque object

### Relevant Components:
Dropdown

**Comment by shlomitc** [comment]
we decided to keep the separation of `onSelect` and `onChange`.
in the case of auto-completion, the `onChange` callback refers to the input change, while the `onSelect` refers to the item selection.
