### ISSUE TITLE
<Dropdown/> - items exist in DOM also when not displayed

### ISSUE THREAD

**Issue by katmai7** [wix/wix-style-react#1899]
### Summary:
Hi, I found out that you can not remove nodes for the dropdown component(and maybe somewhere else) when the dropdown is not opened. 
In my case, I have virtualized table with about 200 rows with a dropddown in each row that contains up to 700 items. The total amount of dom elements is about 140000.

### Priority:
Normal

There are 4 different examples:
Try to record performance and check style recalculation time
1. https://codesandbox.io/s/q9m12n7ymq - default
2. https://codesandbox.io/s/ymlrxv3q09 - visibility: hidden -- bad
3. https://codesandbox.io/s/8kvzkk7252 - display: none -- good
4. https://codesandbox.io/s/m41wmqwp1x - removed nodes -- awesome

### Expected behavior:
Remove  elements from DOM(or at least use `display: none` instead of `visibility: hidden`)

### Relevant Components:
Dropdown.

**Comment by lbelinsk** [comment]
very important issue. Thanks for reporting and for doing the performance comparison. We will add it to our backlog, and will try to get to it as fast as possible

**Comment by shlomitc** [comment]
Issue was fixed here by replacing visibility hidden with display none

https://github.com/wix/wix-style-react/pull/1996

Please try it out and re-open if you encounter an issue
