### ISSUE TITLE
<DropdownLayout/> - the divider element is not rendered

### ISSUE THREAD

**Issue by ChenRoth** [wix/wix-style-react#1931]
### Summary:

divider element is not rendered:

<img width="578" alt="screen shot 2018-07-03 at 15 49 58" src="https://user-images.githubusercontent.com/36155213/42220943-10ae90aa-7ed9-11e8-8099-d75e1ac84cbb.png">

the divider option is
```
{
 description: "",
 id: "___",
 value: "-"
}
```
also tried passing a string `'-'`

it worked before i upgraded to 4.6.x.

### Priority:
- [ ] Blocker
- [X] Urgent
- [ ] Normal
- [ ] Minor

### Steps to reproduce:
 1. I'm using `<MultiSelect>` and just passing options, where at least one is a divider

### Expected behavior:
Render a divider instead of the value `-`

### Relevant Components:
MultiSelect, DropdownLayout

**Comment by shlomitc** [comment]
@Faradey27 - is it related to the autocomplete fix? looks to me like it's related to this change: https://github.com/wix/wix-style-react/pull/1818

**Comment by ChenRoth** [comment]
any news? no change as of 4.9.0

**Comment by yardnsm** [comment]
@ChenRoth Should be fixed in #1992, can you please verify?

**Comment by shlomitc** [comment]
@yardnsm - we need to release a new version first, only then it can be used

**Comment by shlomitc** [comment]
Released, closing. please re-open if the issue recurs.
