### ISSUE TITLE
Fix Editable Selector's Margins

### ISSUE THREAD

**Issue by milkyfruit** [wix/wix-style-react#1937]
### Summary:
EditableSelector's margins are not by the guidelines.

- [ ] Reduce the distance between the input and the buttons to 18px:
![image](https://user-images.githubusercontent.com/1684587/42268314-d81565ec-7f83-11e8-90e6-bf017156d672.png)
![image](https://user-images.githubusercontent.com/1684587/42268331-e1564496-7f83-11e8-8900-a1c5366877f0.png)

- [ ] Add the 12px margin between the 'edit' and 'delete' buttons"
![image](https://user-images.githubusercontent.com/1684587/42268545-7a0a821a-7f84-11e8-9858-6ed86478d0aa.png)

Link to specs:
zpl.io/bPLejgk

### Priority:
- [ ] Blocker
- [ ] Urgent
- [x] Normal
- [ ] Minor

**Comment by Faradey27** [comment]
https://github.com/wix/wix-style-react/pull/1984

**Comment by argshook** [comment]
@Faradey27 can this be closed?
