### ISSUE TITLE
`FocusableHOC` loses `onBlur` handler if its rerendered

### ISSUE THREAD

**Issue by AtomicAlienZ** [wix/wix-style-react#1939]
### Summary:
`FocusableHOC` loses `onBlur` handler if its wrapped component is rerendered.

### Priority:
- [ ] Blocker
- [x] Urgent
- [ ] Normal
- [ ] Minor

### Steps to reproduce:
 1. Type something in field in a form.
 2. `Tab` to submit button (focus handler triggered)
 3. Space/Enter to submit form
 4. Intercept the submit event, and chang state so the button now shows loader (or whatever) instead of text
 5. Unfocus from the button via mouse or keyboard (blur handler is NOT triggered)
 7. Focus ring remains

If we focus to and unfocus from the button again, blur handler gets triggered again.

### Expected behavior:
It should not "lose" `onBlur` handler and remove `data-focus-visible` from the element

### Relevant Components:
`<Button />`

**Comment by shlomitc** [comment]
@AtomicAlienZ 
We recently fixed the `onBlur` event for focus states:
https://github.com/wix/wix-style-react/issues/1721

I also created a small snippet to demonstrate your issue and it seems to work.
https://codesandbox.io/s/r678rwqq

So I'm closing now, please re-open if still not solved
