### ISSUE TITLE
infiniteScroll in <DataTable> doesn't load more items

### ISSUE THREAD

**Issue by ChenRoth** [wix/wix-style-react#1942]
### Summary:

I'm trying to have an infinite scroll with all data initially passed to the component (meaning I have no need for the `loadMore` cb)

However, when I scroll down, all I see is the `loader` node:

![screen shot 2018-07-04 at 13 54 20](https://user-images.githubusercontent.com/36155213/42273423-cec17176-7f91-11e8-8af2-d1ee1439b663.png)

so only the first batch of items (20 by default) is shown.

### Priority:
- [ ] Blocker
- [X] Urgent
- [ ] Normal
- [ ] Minor

### Steps to reproduce:
 pass these props:
```
infiniteScroll
data={_.range(0, 200)}
columns={[
  {
    title: 'test',
    render: (__, index) => index
 }]}
```
### Expected behavior:

render more items when scrolling down

### Relevant Components:
DataTable

**Comment by shlomitc** [comment]
try passing the `hasMore` flag

**Comment by ChenRoth** [comment]
no change

**Comment by ChenRoth** [comment]
```
<DataTable
            data={_.range(0, 200)}
            infiniteScroll
            columns={[{
              title: 'test',
              render: (__, index) => index
            }]}>
</DataTable>
```
(`_` is lodash)
if it works, try putting it inside a ` <MessageBoxFunctionalLayout>`

**Comment by shlomitc** [comment]
well, it looks like you need to manually pass the data which is relevant.

The `infiniteScroll` doesn't do for you the actual data fetching or data slicing, so you'll have to do it yourself. here's  a naive implementation:

```
import DataTable from 'wix-style-react/DataTable';
import {MessageBoxFunctionalLayout} from 'wix-style-react/MessageBox';
import s from './App.scss';
import _ from 'lodash';

const numOfDisplayedItemsPerPage = 20;
const totalItemsLength = 200;
const data = _.range(0, totalItemsLength);

class App extends React.Component {
  constructor(props) {
    super(props);
    this.state = {hasMore: true, endIndex: numOfDisplayedItemsPerPage, data: data.slice(0, numOfDisplayedItemsPerPage)};
    this.loadMore = this.loadMore.bind(this);
  }

  loadMore() {
    if (this.state.endIndex < totalItemsLength) {
      setTimeout(() => {
        const newEndIndex = this.state.endIndex + numOfDisplayedItemsPerPage;
        this.setState({
          endIndex: newEndIndex,
          data: data.slice(0, newEndIndex)
        });
      }, 500);
    } else {
      this.setState({
        hasMore: false
      });
    }
  }

  render() {
    return (
      <div className={s.root}>
        <MessageBoxFunctionalLayout>
          <DataTable
            dataHook="story-data-table-infinite-scroll"
            data={this.state.data}
            infiniteScroll
            newDesign
            itemsPerPage={this.state.endIndex}
            columns={[{
              title: 'test',
              render: (__, index) => index
            }]}
            hasMore={this.state.hasMore}
            loadMore={this.loadMore}
          />
        </MessageBoxFunctionalLayout>
      </div>
    );
  }
}

export default App;
```

**Comment by ChenRoth** [comment]
I've tried handling the loading of items manually, but the problem is `loadMore` isn't invoked, so all this wouldn't help

**Comment by shlomitc** [comment]
1. `loadMore` is not called when inside a max-height and scroll container => sounds like a bug to solve, not a big issue.
2. for your use case, I wouldn't use the `infiniteScroll`at all, but rather want to use some optimized mechanism for the entire table data load. something like this: https://github.com/bvaughn/react-virtualized. that's a good suggestion although not implemented yet.

**Comment by yardnsm** [comment]
Try using `useWindow={false}` on `<DataTable/>`, it worked for me when using `< MessageBoxFunctionalLayout/>` with `maxHeight.

**Comment by yardnsm** [comment]
@ChenRoth Have you tried the suggestion?

**Comment by ChenRoth** [comment]
not yet, i'll let you know

**Comment by shlomitc** [comment]
@ChenRoth - pinging

**Comment by ChenRoth** [comment]
I'll try it this week

**Comment by ChenRoth** [comment]
`useWindow={false}` makes it work, but when the table is being re-rendered (by editing something in the table), the component scrolls to the wrong place.
I'll try to use `scrollElement` and see if it helps

**Comment by shlomitc** [comment]
Any re-render causes it? or only if you change the list of items.

If its the second case, then probably the right behavior will be to make the scroll jump back to 0, as the list is changed.
If it's just a random render, then it sounds like a bug. Can you provide a small code snippet the shows it?
https://codesandbox.io/s/mymk2zn1mp

**Comment by ChenRoth** [comment]
it's an in-place edit - the changes are only applied when the user saves and closes the modal
the list of items doesn't change, it's the items' content that changes.

i have a video demonstrating it that i could send you over slack

**Comment by shlomitc** [comment]
a code example will be extremely helpful, can you please create one?

**Comment by ChenRoth** [comment]
I could try to reproduce something minimal.
before that, I would ask: 
whenever the data changes, I slice a new array and use it for data.
while the order of items never changes, this might affect the DataTable.
is there a way for me to instruct DataTable to use a property other than `id` to track rows?

**Comment by ChenRoth** [comment]
i solved the problem by slicing the original array only once and then editing its sliced version.
