### ISSUE TITLE
<Page/> -  When scrolling content to minimize header, the content jumps

### ISSUE THREAD

**Issue by hepiyellow** [wix/wix-style-react#1951]
As you ca see in this animated GIF:

![profile-20180704t201534_2](https://user-images.githubusercontent.com/6338722/42289245-1ed91134-7fc7-11e8-9beb-17e7a83fc929.gif)

I understand that the idea was to avoid a big gap when the minimization happens,
but I think the gap is not so bad, and it is more important that the content would not jump.

Think about someone who is reading a sentence at the bottom of the screen, and scrolls to see the next sentence, then the content jumps and he gets dis-oriented and needs to find the line he was reading again.

Anyway, when some one is scrolling down, they don't care about what is happening at the top of the screen, they are focused on the bottom part of the screen.

Solution:
Well, this can be easily fixed. just need your confirmation @wuwa @milkyfruit .

**Comment by milkyfruit** [comment]
I agree the jump is an issue and it the transition should be smooth.
In addition, recently there was a similar request from desgin side – to simplify transition animation by changing breadcrumbs' position. You can see the preview here:
[breadcrumbs_on_scroll.mov.zip](https://github.com/wix/wix-style-react/files/2165445/breadcrumbs_on_scroll.mov.zip)

I think these issues can be merged and solved together.
I'll test new animation with more use-cases and will update you here.

**Comment by hepiyellow** [comment]
Your suggestion looks very nice. It has some re-work needed in order to implement (mainly related to the  Action buttons).

Anyway, I think we should discuss your new suggestion separately.
And first resolve the jumping issue. (which is an easy fix)

I understand from your answer that you are in favour of removing the jumping,
I will create a PR for it, so you can see it in action.

**Comment by milkyfruit** [comment]
Sure, if it's an easy fix, lets do it.
Meanwhile, the general transition that David suggested lets leave for other update.

**Comment by shlomitc** [comment]
Fixed here:
https://github.com/wix/wix-style-react/pull/2016
