### ISSUE TITLE
<ColorPicker /> history bar behaviour

### ISSUE THREAD

**Issue by milkyfruit** [wix/wix-style-react#1977]
### Summary:

![image](https://user-images.githubusercontent.com/1684587/42504543-d2ff3b80-8444-11e8-9a32-abc2cd4a622d.png)

The history bar should work like this:
1. Left column displays previously selected (clicked confirm) color.
2. If there was no previously selected color, then both columns show current choice.
3. Right column displays currently choosing color.
4. Left column is updated when currently chosen color is confirmed with "confirm" button click.

### Priority:
- [ ] Blocker
- [ ] Urgent
- [x] Normal
- [ ] Minor

### Link to Zeplin:
https://zpl.io/awqQmjM

**Comment by Faradey27** [comment]
https://github.com/wix/wix-style-react/pull/1990

**Comment by shlomitc** [comment]
Fixed and merged
