### ISSUE TITLE
<RadioGroup/> and <EditableSelector/>- make component accessible

### ISSUE THREAD

**Issue by shlomitc** [wix/wix-style-react#2029]
The above components should align to the A11y guidelines (work with keyboard navigation, support selection, etc...)
See this issue for more details: https://github.com/wix/wix-style-react/issues/1495#issuecomment-407044410

**Comment by shlomitc** [comment]
no current request, so closing for now

**Comment by OriMarron** [comment]
I would like to reopen this one.
Specifically for `<RadioButton />`. 
It is already possible to *set as active* with keyboard TAB. 
what is missing is *selecting* with SPACE / ENTER

**Comment by OriMarron** [comment]
@mosheKerbel how can we push this forward? <RadioGroup/>  is **completely unaccessible** without a mouse.

I am willing to help, but I'm not sure what the right direction will be

**Comment by mosheKerbel** [comment]
@OriMarron 
Next time please send us also a message on the channel, we are on it and could have answered you quicker than mentions in Github.
Anyways, I see that we have the UX design for accessibility in [Zepplin](https://app.zeplin.io/project/5c8f6f1f9f489505cac756dc/screen/5c9b502feb413e0ab95466be)

So if you would like to contribute this feature you are welcome to schedule a meeting with me and we can go over it.

**Comment by shlomitc** [comment]
Hey @OriMarron 
as Moshe said, feel free to contribute the a11y feature, we'll be happy to assist.
