### ISSUE TITLE
<DropdownLayout> - change divider's data-hook

### ISSUE THREAD

**Issue by yardnsm** [wix/wix-style-react#2034]
Its a good idea to change the divider's data-hook to use a different template so we can distinguish it from a "regular" option item.

This has been done in https://github.com/wix/wix-style-react/pull/2005, but reverted since it could be a possible breaking change.

cc: @shlomitc

**Comment by hepiyellow** [comment]
@yardnsm 
Why do you need this?
Can't you simply check if the item's value is `-`?

**Comment by yardnsm** [comment]
It can cause some clashing `data-hooks`s. Consider the following items:

```javascript
[
	{ id: 1, value: 'an item' },
	{ value: '-' },
	{ id: 2, value: 'another item' },
]
```

According to the current implementation, both the first item and the second (the divider) will get a `data-hook` with the value of `dropdown-item-1`.
