### ISSUE TITLE
NotificationBar link should open in new tab

### ISSUE THREAD

**Issue by TomasRup** [wix/wix-style-react#2039]
### Summary:
We use a notification https://wix-wix-style-react.surge.sh/?selectedKind=8.%20Notification%20Bars&selectedStory=8.4%20Warning&full=0&addons=0&stories=1&panelRight=0

with `link` property. We use it to have a `Learn More` to open wix support page. But it opens it in the same browser tab. We do need an option to open it up in another tab.

### Priority:
- [ ] Blocker
- [ ] Urgent
- [x] Normal
- [ ] Minor

### Steps to reproduce:
 1. Use `<Notification>`
 2. Use `<Notification.ActionButton link="www.wix.com"/>`
 3. The www.wix.com will open up in the same browser tab

### Expected behavior:
www.wix.com opens in another tab

### Relevant Components:
`<Notification/>`, `<Notification.ActionButton/>`

**Comment by shlomitc** [comment]
I guess you can add a prop to the `ActionButton` to receive the `target`, or you can just do it like this:

```html
<a link="http://www.wix.com" onclick="window.open(this.href); return false;">Learn more</a>
```

**Comment by shlomitc** [comment]
@TomasRup - did it work for you?

**Comment by shlomitc** [comment]
old issue, closing
