### ISSUE TITLE
6.3 Tabs storybook is broken

### ISSUE THREAD

**Issue by ChenRoth** [wix/wix-style-react#2050]
### Priority:
- [ ] Blocker
- [ ] Urgent
- [X] Normal
- [ ] Minor

### Steps to reproduce:
 1. https://wix-wix-style-react.surge.sh/?selectedKind=6.%20Navigation&selectedStory=6.3%20Tabs&full=0&addons=0&stories=1&panelRight=0

**Comment by shlomitc** [comment]
Fixed
