### ISSUE TITLE
Testkits imports protractor and enzyme together

### ISSUE THREAD

**Issue by shlomitc** [wix/wix-style-react#2056]
The exposed testkit files are using a common file `src/test-common.js` which imports many packages together. For example, both `enzyme` and `protractor` are being imported, even if not in use.

We should refactor testkits to not use this `src/test-common.js`, but it requires an internal change to all of the test files.

**Comment by nayish** [comment]
this causes it not to work with projects with puppeteer since they dont have protractor installed... and we get a module `Cannot find module 'protractor'` message

**Comment by shlomitc** [comment]
Merged and release in V4.16.0
https://github.com/wix/wix-style-react/blob/master/CHANGELOG.md#4160---2018-08-05
