### ISSUE TITLE
<Tooltip/> - onClickOutside triggers un-needed rendering

### ISSUE THREAD

**Issue by katmai7** [wix/wix-style-react#2069]
### Summary:
hide() is calling even if a tooltip is hidden which leads to component rendering,
because it calls setState

### Priority:
Normal

### Steps to reproduce:
 1. Add 2 tooltips(or component based on it)
 2. Set up breakpoint  https://github.com/wix/wix-style-react/blob/9c309cddb8d580bcd96fe688a173acb57992428e/src/Tooltip/Tooltip.js#L297
 3. Click somewhere on the page
 4. Check that hide() method is called even if the tooltip is hidden

### Expected behavior:
Do not call hide() if the tooltip is hidden

### Additional notes:
Check other components(like calendar, input with options, dropdown) which are using `onOutsideClick`

**Comment by shlomitc** [comment]
Can you please supply a simple code snippet that shows the issue?
you can you this playground:
https://codesandbox.io/s/mymk2zn1mp

**Comment by katmai7** [comment]
@shlomitc Hi, it's not a bug with tooltip `hide` callback, but more perf optimization for a  tooltip. 
For now, if you have a lot of tooltips on a page, every click on it will call `setState` inside `hide` method
https://github.com/wix/wix-style-react/blob/9c309cddb8d580bcd96fe688a173acb57992428e/src/Tooltip/Tooltip.js#L297
even if a tooltip is hidden.

**Comment by shlomitc** [comment]
how do you suggest fixing it?

**Comment by katmai7** [comment]
@shlomitc I think we can add simple if statement at the beginning of the `hide` like:
```
if(!this.state.visible) {
  return;
}
```

Or if it possible, subscribe to the 'click outside' when a tooltip is shown and unsubscribe when a tooltip is hidden.

**Comment by shlomitc** [comment]
checking the state in ‘onClickOutside’ hook sounds good to me

**Comment by hepiyellow** [comment]
How about if we do :  
```js
!this.state.hidden && this.setState({hidden: true}); 
```

**Comment by hepiyellow** [comment]
Looking into it a bit further, I realized that there is no re-render when clicking outside.
That is, because Tooptip extends WixComponent which extends PureComponent.
PureComponent have a built in optimization that re-renders only if state or props are changed,
and calling `hide()` when the Tooltip is not shown, it does not change the state. (`hidden` stays `true`)
