### ISSUE TITLE
<Page.Header /> text wrapping

### ISSUE THREAD

**Issue by milkyfruit** [wix/wix-style-react#2071]
### Summary:
Currently [<Page.Header />](https://wix-wix-style-react.surge.sh/?selectedKind=2.%20Layout&selectedStory=2.5%20%2B%20PageHeader&full=0&addons=0&stories=1&panelRight=0) doesn't have a solution how to deal with long texts.

Wanted solution:
- Title should be a single line text, shouldn't wrap it, but show ellipsis instead.
- Subtitle could wrap up to two lines, then show ellipsis.

Link to updated specs: https://zpl.io/2vYq1J5

### Priority:
- [ ] Blocker
- [ ] Urgent
- [x] Normal
- [ ] Minor

![image](https://user-images.githubusercontent.com/1684587/43942511-fa8e1c58-9c80-11e8-90a6-49a4d9482c93.png)

**Comment by shlomitc** [comment]
multi-line ellipsis is a complex feature which should be considered, but it's a relatively high effort.
is there a solution we can achieve with a single line instead?

**Comment by milkyfruit** [comment]
yes, we can have a single line subtitle for now, I'll update the specs then.

**Comment by shlomitc** [comment]
closing in favor of this issue
https://github.com/wix/wix-style-react/issues/2413
