### ISSUE TITLE
Input component with type Number does not enforce numeric input in FireFox

### ISSUE THREAD

**Issue by avivr** [wix/wix-style-react#2093]
### Summary:
Input component with type=number does not enforce numeric inputs in FireFox

### Priority:
- [ ] Blocker
- [ ] Urgent
- [X] Normal
- [ ] Minor

### Steps to reproduce:
 1. In FireFox, go to [Input on Storybook](https://wix-wix-style-react.surge.sh/?selectedKind=3.%20Inputs&selectedStory=3.1%20Text%20Field&full=0&addons=0&stories=1&panelRight=0)
 2. Select 'Number' in 'Type'
 3. Type letters

Result: You see letters in input field.

### Expected behavior:
Only numbers should be permitted.

### Relevant Components:
Input

**Comment by argshook** [comment]
thanks! this is actually a bug with our storybook tools and not input itself. It is known since forever here https://github.com/wix/wix-ui/issues/123

i'll try to find time and finally close that one. thanks for reminding :)

**Comment by avivr** [comment]
This is happening for us on live site. I just used storybook as an easy example to reproduce

**Comment by shlomitc** [comment]
Very strange.
I create a simple example with the native input and I see some unexpected behaviors:
https://codesandbox.io/s/1rz4z976ll

In Safari, `<input type="number"/>` will trigger `onChange` only if the character is a number. If you type a letter, it will just change the UI but will not trigger the `onChange`. WAT?!

Worth googling a little bit

**Comment by avivr** [comment]
Using onKeyPress instead of onChange seems to work - 
https://codesandbox.io/s/x3kokx73yq

**Comment by avivr** [comment]
same in ms edge / ie11.
IMHO WSR should wrap the behaviour with onKeyPress and handle it itself to avoid differences in browsers behaviours. WDYT?
