### ISSUE TITLE
Disable autocomplete for dropdown

### ISSUE THREAD

**Issue by katmai7** [wix/wix-style-react#2098]
### Summary:
Hi, I found out, that HTML autocomplete works for dropdowns/multiselects.

I think it can be bad for an user experience

![screen shot 2018-08-07 at 18 33 39](https://user-images.githubusercontent.com/3172108/43786399-2d9d4d74-9a71-11e8-872d-b505ecb2e2fd.png)

### Priority:
- Minor

### Expected behavior:
Do not show browser built-in autocomplete for dropdowns/multiselect

**Comment by shlomitc** [comment]
is it activated by default or only if you pass in explicitly `autocomplete=true`?

**Comment by hepiyellow** [comment]
I could not reproduce.
But I think we can set `autocomplete="off"` as the default for `MultiSelect`.
@shlomitc ?

**Comment by hepiyellow** [comment]
We shell set `defaultProps: { autocomplete: 'off' } ` for `<InputWithOptions>`

**Comment by magonicolas** [comment]
Having the same issue, how can I solve it on Wix? Don't know how to se by code (Or not) the autocomplete to off.
