### ISSUE TITLE
Tooltip content in <DataTable> header is misplaced

### ISSUE THREAD

**Issue by ChenRoth** [wix/wix-style-react#2104]
### Summary:
the tooltip content in a `<DataTable>` header is misplaced and there's no way to control its position (WSR code hard codes the `moveBy` parameters)

![screen shot 2018-08-08 at 18 05 20](https://user-images.githubusercontent.com/36155213/43845982-ebe8341e-9b35-11e8-93b7-1d6030abc5bc.png)

### Priority:
- [ ] Blocker
- [ ] Urgent
- [X] Normal
- [ ] Minor

### Steps to reproduce:
 1. it's just an ordinary `<DataTable>` within a `<Card>`

### Expected behavior:

the tooltip would be placed correctly above its icon, or at least it'd be allowed to control the position

### Relevant Components:
DataTable, Tooltip

**Comment by shlomitc** [comment]
fixed here
https://github.com/wix/wix-style-react/pull/2119

will be released in next minor version (4.18.0)
