### ISSUE TITLE
`<InputTime/>` component

### ISSUE THREAD

**Issue by argshook** [wix/wix-style-react#2107]
Currently we have `<TimePicker/>` component which works with moment.js
dependency. The plan is to ditch that dependency and use TimePicker from
`wix-ui-backoffice`.

TODO:
1. [ ] proxy `<TimePicker/>` from wix-ui-backoffice to wix-style-react \
    https://github.com/wix/wix-style-react/pull/1874 \
    https://github.com/wix/wix-ui-backoffice/tree/master/src/components/TimePicker
1. [ ] proxied component should be named `<InputTime/>`
1. [ ] apply `FocusableHOC` on proxied component
1. [ ] add documentation for `<InputTime/>`
1. [ ] hide documentation for `<TimePicker>` and mark it as deprecated

**Comment by EgoziE** [comment]
check if still relevant
What is `<TimeInput/>` vs `<TimePicker/>`

**Comment by shlomitc** [comment]
We plan to rework on all date and time components in the upcoming months, so we could consider using the TimePicker or recreate based on the requirements.

Anyway, I'm closing the issue to clean old stuff from the backlog
