### ISSUE TITLE
Storybook: better shape support component API props

### ISSUE THREAD

**Issue by astrauka** [wix/wix-style-react#2111]
### Summary:

When using `infoTootlipProps: PropTypes.shape(Tooltip.propTypes)`
https://github.com/wix/wix-style-react/blob/master/src/FormField/FormField.js#L49
the storybook API does not list the properties
<img width="1125" alt="screen shot 2018-08-10 at 10 20 59" src="https://user-images.githubusercontent.com/1308928/43944438-8f035afa-9c87-11e8-975a-34fe933d3a05.png">

### Priority:
- [ ] Blocker
- [ ] Urgent
- [x] Normal
- [ ] Minor

### Steps to reproduce:

Go to 
[form field](https://wix-wix-style-react.surge.sh/?selectedKind=Components&selectedStory=FormField&full=0&addons=0&stories=1&panelRight=0)
API tab

### Expected behavior:

See tooltip props listed

### Relevant Components:

FormField, ImageViewer

**Comment by argshook** [comment]
thanks, this is a known issue https://github.com/wix/wix-ui/issues/620
