### ISSUE TITLE
<Popover> - throws an error when removing itself

### ISSUE THREAD

**Issue by katmai7** [wix/wix-style-react#2113]
### Summary:
I get a JS error when the tooltip tries to "delete" itself.
```
TooltipContainerStrategy.js:38 Uncaught TypeError: Cannot read property 'parentElement' of null
    at TooltipContainerStrategy.getContainer (TooltipContainerStrategy.js:38)
    at Tooltip._getContainer (Tooltip.js:268)
    at hideLazy (Tooltip.js:341)
```

Example: 
https://codesandbox.io/s/q7nnp80099

### Priority:
Normal/Urgent

### Steps to reproduce:
 1. Go to the example
 2. Try to delete a row
 3. Check the console.

### Expected behavior:
No error.

### Additional notes:
The example uses react 16, but I've checked it for react 15 and got the same error.

**Comment by shlomitc** [comment]
Hey, thanks for reporting!
So your specific issue is happening as a combination of Popover trying to removing itself while hiding it, so there is an asynchronous behavior there.

The Popover `onClick` is called and hides the tooltip. Specifically, the `getContainer()` is failing
https://github.com/wix/wix-style-react/blob/master/src/PopoverMenu/PopoverMenu.js#L52

Internally, it will try to hide, but won't find it (as you remoed it).
https://github.com/wix/wix-style-react/blob/master/src/Tooltip/Tooltip.js#L326

I think the safest approach will be pass the `onClick` only after the tooltip is hidden (pass it to hide function as a callback).

do you think you can make a PR for that?

**Comment by katmai7** [comment]
@shlomitc looks like the issue can be closed.
