### ISSUE TITLE
RadioGroup nested radio buttons all selected

### ISSUE THREAD

**Issue by saarkuriel** [wix/wix-style-react#2125]
### Summary:
Using `RadioGroup` with a nested `RadioGroup` as a `RadioGroup.Radio` and selecting that option causes all its nested option to appear selected, even though the correct option value is selected

### Priority:
- [ ] Blocker
- [*] Urgent
- [ ] Normal
- [ ] Minor

### Steps to reproduce:
 1. Clone the repo
 2. Select 4th option

### Expected behavior:
Only the selected option from the nested option to appear selected.

### Relevant Components:
RadioGroup

### Additional notes:
Repo: https://github.com/wix-a/radio-btns

![image](https://user-images.githubusercontent.com/39697196/44029022-8f0ee7c4-9f04-11e8-86b2-d8790ea926bb.png)

**Comment by argshook** [comment]
Hey there, thanks for reporting!

also thanks for reproduction repo, really helpful.

`<RadioGroup>` was never meant to work with nested radios so no surprise there is something wrong in there.
I opened a PR [#2128](https://github.com/wix/wix-style-react/pull/2128) with a fix.

---

If inside `RadioGroup.Radio` you are going to render something more complex than just a simple
label, i would suggest to use `content` prop for that:

```js
<RadioGroup>
  <RadioGroup.Radio
    content={
      <RadioGroup>
        <RadioGroup.Radio>anything goes</RadioGroup.Radio>
      </RadioGroup>
    }
  />
</RadioGroup>
```

this way you will need to adjust styling on your own (for example add `margin-left`) but there wont
be any `onClick` handler.

`children` was meant to be only for simple things like text and maybe an icon. Thus, it has `onClick` which in the case of nested RadioGroups (or anything else clickable, really) would result in unexpected behaviour.

**Comment by saarkuriel** [comment]
@argshook Thanks a lot!
