### ISSUE TITLE
Add ability to pass Icon to Dropdown as label

### ISSUE THREAD

**Issue by adavidof** [wix/wix-style-react#2143]
![image](https://user-images.githubusercontent.com/10529679/44341141-bb08e100-a48f-11e8-8732-0cda93472d00.png)

I want to pass as dropdown label Icon, but in the dropdown list as text.
How I can do this?

### Relevant Components:
Dropdown

**Comment by lbelinsk** [comment]
Not sure I understand. Can you please elaborate?
You want to have an item which in the options container should appear as text, but the trigger (the element that triggers the visibility of the items) should be an icon?
Similar to ButtonWithOptions?
https://wix-wix-style-react.surge.sh/?selectedKind=4.%20Selection&selectedStory=4.1%20%2B%20ButtonWithOptions&full=0&addons=0&stories=1&panelRight=0

**Comment by adavidof** [comment]
@lbelinsk 
yes, but instead of button I want to see the dropdown
![image](https://user-images.githubusercontent.com/10529679/44342011-5c913200-a492-11e8-843f-c06980497203.png)

**Comment by lbelinsk** [comment]
We have a component IconWithOption, but it opens the dropdown on hover, not on click.

**Comment by adavidof** [comment]
@lbelinsk cool, probably it should support `showTrigger`

**Comment by shlomitc** [comment]
@adavidof - did `IconWithOptions` solve your problem?

**Comment by adavidof** [comment]
@shlomitc no
my component is more customizable

**Comment by shlomitc** [comment]
What is missing?

**Comment by shlomitc** [comment]
`DropdownBase` will fulfill your need:
https://wix-wix-style-react.surge.sh/?selectedKind=Components&selectedStory=DropdownBase&full=0&addons=0&stories=1&panelRight=0
