### ISSUE TITLE
Input adds . (dot) to the value

### ISSUE THREAD

**Issue by katmai7** [wix/wix-style-react#2145]
### Summary:
Input comonent adds '.'(dot) to the value if user input couple of space symbol after text.

![input-dot-bug](https://user-images.githubusercontent.com/3172108/44400314-63cc4480-a553-11e8-9fe5-2ffe12804996.gif)

### Priority:
Minor

### Steps to reproduce:
 1. Go https://wix-wix-style-react.surge.sh/?selectedKind=3.%20Inputs&selectedStory=3.1%20%2B%20Input&full=0&addons=0&stories=1&panelRight=0
 2. Enter any text in an input
 3. Start adding white space (minimum 2 spaces)
 4. Input adds '.' to the value

### Expected behavior:
Input should not add '.'

**Comment by shlomitc** [comment]
are you sure it's not related to your OS behavior?
https://www.tekrevue.com/tip/macos-sierra-add-period-double-space/

**Comment by katmai7** [comment]
@shlomitc Oh, yes it is related to my OS.
Sorry about it, i haven't knew about double spaces.
