### ISSUE TITLE
<SectionHelper /> Make "close" button optional

### ISSUE THREAD

**Issue by milkyfruit** [wix/wix-style-react#2147]
### Summary:

[`<SectionHelper />`](https://wix-wix-style-react.surge.sh/?selectedKind=8.%20Notification%20Bars&selectedStory=8.7%20SectionHelper&full=0&addons=0&stories=1&panelRight=0) is missing a prop that makes "close" button optional, something like `close=none`.

Specs are [here](https://goo.gl/KRvFR2).

This fix was requested by Restaurants team.

### Priority:
- [ ] Blocker
- [x] Urgent
- [ ] Normal
- [ ] Minor

**Comment by shlomitc** [comment]
This is already available by not passing the `onClose` callback function. The docs don't show it though...
I created a PR that adds it explicitly https://github.com/wix/wix-style-react/pull/2148

**Comment by shlomitc** [comment]
Merged and will be available on next release
