### ISSUE TITLE
Uncaught TypeError: (0 , _HeadingSt2.default) is not a function

### ISSUE THREAD

**Issue by rghorbani** [wix/wix-style-react#2152]
### Summary:
This problem occurred to me after the refactor done to Heading and Text [#2037](https://github.com/wix/wix-style-react/pull/2037).

Using
webpack -> 4.16.5
wix-style-react -> 4.18.0

### Priority:
- [x] Blocker
- [x] Urgent
- [ ] Normal
- [ ] Minor

### Steps to reproduce:
 1. Using any main component like Page and Input produces this problem.
 2. It is derived from base components like Heading, Text, Label

![image](https://user-images.githubusercontent.com/5933939/44597663-a7d67800-a7e5-11e8-8163-af238f2d953b.png)

### Expected behavior:
Compiled, not running
### Relevant Components:
Page
Input
Label
Heading
Text
### Additional notes:
@shlomitc

**Comment by shlomitc** [comment]
Hey. Thanks for reporting.
Starting from `wix-style-react@3`, `stylable` components were added to the library, `Text` and `Label` are such.
[stylable](https://stylable.io/) is a CSS preprocessor we use for advanced styled components.

We will update our installation guide to work with create-react-app or similar webpack based applications so it will be more clear. In the meanwhile please follow the suggested installation guide here:
https://stylable.io/docs/getting-started/install-configure

**Comment by rghorbani** [comment]
Hi,
Tnx @shlomitc , I used the installation guide but following error occured.
module @stylable/core not found (Maybe you should inform the development team since it's Wix product). After installing the dependency, I was stopped by following error and warnings that I could not get around.
Error:
Uncaught ReferenceError: require is not defined
(I think it's related to stylables inside require and conflicting with node's since they are running in the same enviroment).
Warning:
Loading a Stylable stylesheet via webpack loaders is not supported and may cause runtime errors.

**Comment by rghorbani** [comment]
@shlomitc 
Seems the problem was with [this](https://github.com/wix/stylable/tree/master/packages/webpack-plugin#compatibilities-with-existing-loading-mechanisms).
Fixed it with using this regex for css rules `/(?<!\.st)\.css$/`.

**Comment by shlomitc** [comment]
do you still get the first error for `@stylable/core` not found?

**Comment by rghorbani** [comment]
@shlomitc Yes, but it's a dependency install. I think it should be included in the modules dependencies.
But the main problem was with css-loader trying to compile `.st.css` files that was solved by the new regex.
If you guide me maybe I can make a pull request for updated installation guide?

**Comment by rghorbani** [comment]
Created a pull request #2156

**Comment by shlomitc** [comment]
closing as the required docs were added

**Comment by lelikg** [comment]
I'm getting this error on a webpack project (not yoshi), I installed stylableWebpackPlugin

**Comment by EgoziE** [comment]
Closing due to irrelevance
