### ISSUE TITLE
TimePicker - Wrong import path

### ISSUE THREAD

**Issue by LittleTal** [wix/wix-style-react#2153]
### Summary:

For TimePicker component, import path in the documentation is 
`import TimePicker from 'wix-style-react/TimePicker';`

In fact, I should have import:
`import TimePicker from 'wix-style-react/TimeInput';`

### Priority:
- [ ] Blocker
- [ ] Urgent
- [x] Normal
- [ ] Minor

**Comment by argshook** [comment]
Hello, thanks for filling the issue

this is a long standing mistake that we have which i think should finally be fixed in v5. in the meantime, i fixed documentation
