### ISSUE TITLE
<InputWithOptions> cannot focus input without showing the options

### ISSUE THREAD

**Issue by liorur** [wix/wix-style-react#2168]
### Priority:
- [ ] Blocker
- [ ] Urgent
- [ ] Normal
- [ x] Minor

### Steps to reproduce:
use inputWithOptions autoFocus prop or call focus() on ref 
focus triggers the display of the options list (which is arguably correct) but hideOptions() does not hide them so there is no way to focus without showing the options

**Comment by shlomitc** [comment]
What exactly are you trying to do? Focus on `inputWithOptions` and not show dropdown?

**Comment by liorur** [comment]
exactly, i have inputWithOptions inside a modal, id like to focus on the input when the modal opens, but not open the options before the user begins typing or clicks the arrow because it looks strange

**Comment by shlomitc** [comment]
@wuwa - wdyt?

**Comment by milkyfruit** [comment]
I agree this behaviour is not right.
Keyboard focus should focus first the `dropdown button` first.
When it's focused then `arrow down`, `spacebar` or `enter` should open the `dropdown list`.
The full description is [here](https://v9yfnh.axshare.com/#g=1&p=dropdown)

WSR guidelines show it correct way as well: https://zpl.io/a87Zo6V

**Comment by hepiyellow** [comment]
@wuwa @dkomanov 
Can you answer to the question: 
> what happens when focusing the component via mouse-click? (open the options or not)

**Comment by hepiyellow** [comment]
1. ok. click opens options. Simple focus by keyboard doesn't open options.
1. So no new `showOptionsOnFocus` prop. Anyways, consumers can implement is  themselves if they need it.

**Comment by hepiyellow** [comment]
@wuwa As @shlomitc mentioned in [this PR](https://github.com/wix/wix-style-react/pull/2280),
There is an issue with `MultiSelect mode="select"/>`.

So it seems we DO need the `showOptionsOnFocus` option after all.
It will default to `false`.
