### ISSUE TITLE
<InputWithOptions> using arrows to scroll through many options causes current element not be visible

### ISSUE THREAD

**Issue by liorur** [wix/wix-style-react#2169]
### Priority:
- [ ] Blocker
- [ ] Urgent
- [ ] Normal
- [x ] Minor

### Steps to reproduce:

 create InputWithOptions with a long list of options
scenario 1 - scroll down using down arrow - current element slowly drift outside the pane
scenario 2 - scroll using up arrow - last element is not marked as current

**Comment by shlomitc** [comment]
both scenarios sound legit to me, but I might be missing something.
can you explain what is the wanted behavior?

**Comment by liorur** [comment]
the behaviour i expect is for the current element (marked by bluish background) to always be in view when using up/down arrows to brows options

**Comment by shlomitc** [comment]
@wuwa - what do you think?

**Comment by wuwa** [comment]
long one has a bug. short (medium) works completely fine in my eyes.

**Comment by yardnsm** [comment]
The problematic line is:

https://github.com/wix/wix-style-react/blob/2a459fb574873dbc77ba02cf391cbf8c77de81e9/src/DropdownLayout/DropdownLayout.js#L124

We're missing a pixel... We need to change `35` to `36`, as this is the current height of a single option.

This could cause problems, though. There are options that has a height different than `36px`, so we need to rethink the strategy to calculating the `scrollTop` for the dropdown.

For now, maybe the change to `36` is good enough?

**Comment by yardnsm** [comment]
Resolved in https://github.com/wix/wix-style-react/pull/2327
