### ISSUE TITLE
Dropdown with icon

### ISSUE THREAD

**Issue by adavidof** [wix/wix-style-react#2171]
How I can implement icon to dropdown option?

![image ](https://user-images.githubusercontent.com/10529679/44805992-57d52800-abce-11e8-9cbd-358722df1308.png)
![image](https://user-images.githubusercontent.com/10529679/44806005-64598080-abce-11e8-963f-de1ce919509b.png)

**Comment by shlomitc** [comment]
For the first case, you can just pass any node in the dropdown item `value`.

For the second case, did you try the `prefix` prop of `Dropdown`?

**Comment by shlomitc** [comment]
ping

**Comment by adavidof** [comment]
@shlomitc will try

**Comment by adavidof** [comment]
@shlomitc will try in some time

**Comment by shlomitc** [comment]
ok, so I'm closing it for now - please reopen if it doesn't fit your needs.

thanks!
