### ISSUE TITLE
V6 Breaking Changes Suggestions

### ISSUE THREAD

**Issue by shlomitc** [wix/wix-style-react#2181]
Please edit this comment with things to go into wix-style-react@6.0.0

Branch name: [`version_6`](https://github.com/wix/wix-style-react/tree/version_6)

- [x] Build is green, ready to release

| # | scope | description | merged to v6 branch | in migration doc |
| --- | --- | --- | :---: | :--: |
| 1 | `<MessageBoxFixedHeaderFooter/>` | Remove component | 👍 #2734 | ✅ |
| 2 | `Typography` folder | Cleanup and remove old styles | 👍 #2747 | ✅ |
| 3 | `Card` | Remove deprecated headers (LinkHeader, ButtonHeader, CollapsedHeader) | 👍 #2735 | ✅ |
| 4 | Polyfills | Remove old polyfills and keep only the new `testkit/polyfills` folder | 👍 #2736 | ✅ |
| 5 | `Tag` | make `useOldMargins` default behavior to `true` and remove flag | 👍 #2737 | ✅ |
| 6 | `Text` | remove `bold` prop | 👍 #2738 | ✅ |
| 7 | `Table/TableToolbar` | remove the nested folder | 👍 #2739 | ✅ |
| 8 | `TextField`, `DropdownComposite`, `TextArea` | remove components | 👍 #2740 | ✅ |
| 9 | `InputWithOptions` testkit | remove pressing methods | 👍 #2741 | ✅ |
| 10 | `DataTable`, `Table` | remove `infoTooltip` props | 👍 #2742 | ✅ |
| ~~11~~ | ~~`Button`~~ | ~~remove deprecated component~~ | ~~no~~ |
| 12 | `MessageBoxMarketerialLayout` | make fixImagePosition true and remove prop | 👍 #2743 | ✅ |
| 13 | TPA | remove folder and relevant components | 👍 #2744 | ✅ |
| 14 | Backoffice | remove folder and relevant components (**Edit:** only `<Tooltip/>` and `<TextLink/>` were removed) | 👍 #2745 | ✅ |
|15 | Dropdown | Add separate Controlled / Uncontrolled modes (`upgrade` prop) | 👍  #2806 | ✅ |
| 16 | `<ButtonWithOptions/>`,` <IconWithOptions/>` | Remove components | 👍 #2746 | ✅ |
| 17 | `<DataTable/>` | Remove `newDesign` prop | 👍 #2764 | ✅ |
| 18 | `<Notification/>` | Remove old timeout behaviour (`upgrade` prop) | 👍  #2805 | ✅ |
| 19 | BaseComponents | Only keep `WixComponent` in `BaseComponents`, `TextLink` and the old `Button` should move to `src/Deprecated`. | 👍  #2811 | ✅ |

**Comment by hepiyellow** [comment]
- MultiSelectCheckbox - `onSelect` should receive the option object as first argument and not the id only.
- InputWithOptions - selectedId which is passed to DropdownLayout should be derived from the input value (so we can remove the selectedId prop which is exposed to consumers and not really useful)
- Remove DropdownComposite (and other composites, once new stories using FormField are released)

**Comment by shlomitc** [comment]
@hepiyellow:
1. If we want to do that, we should have it deprecated first with a feature flag. only after we have it we can suggest changing the API.
2. How exactly can it be derived from the input? input is a string while selectedId is an id. Selecting options from the list is done only by ids and not values. is this deprecated somehow already? I want to review it.

**Comment by hepiyellow** [comment]
@shlomitc 
1. We can also add a function `onOptionSelect` with the new api, and deprecate `onSelect` later.
2. I think you are right. Both @ChenRoth  [solution](https://github.com/wix/wix-style-react/pull/2242) and @Faradey27 [solution](https://github.com/wix/wix-style-react/pull/2270/files) to the "Select same option" assumed an id and value have one-to-one correspondence. While it is not necessarily so in the scope of the InputWithOptions component.
3. ok

**Comment by yardnsm** [comment]
### `<Button/>`

> remove deprecated component


As the new button uses UniDriver, we can't simply remove the old button (which used heavily in the library) and replace it with the new one, as we would need to update some components' drivers to become `async`. This would break consumers.

We need to consider wether to keep the old one in the lib while **not** exposing it, and in the meantime we'll try to solve this UniDriver issue.

**Comment by hepiyellow** [comment]
Can we also cleanup the DataTable `newDesign` prop?
( I mean remove it)
@shlomitc @yardnsm

**Comment by shlomitc** [comment]
@hepiyellow - yes we can

**Comment by hepiyellow** [comment]
@yardnsm @shlomitc 
I added number 18 `<Notification/>`

**Comment by yardnsm** [comment]
Resolved in https://github.com/wix/wix-style-react/pull/2833
