### ISSUE TITLE
<InputArea/> - Error icon size margins are incorrect

### ISSUE THREAD

**Issue by LittleTal** [wix/wix-style-react#2183]
### Summary:
Error icon size in the following components is 20px and should be changed to 18px:
`InputArea`, `RichTextArea`, `Tags`, `AutoComplete`, `Dropdown`

### Priority:
- [ ] Blocker
- [ ] Urgent
- [ x ] Normal
- [ ] Minor

### Steps to reproduce:
 1.
 2.
 3.

**Comment by shlomitc** [comment]
Fixed here
https://github.com/wix/wix-style-react/pull/2271
