### ISSUE TITLE
DatePicker does not allow user to type date

### ISSUE THREAD

**Issue by argshook** [wix/wix-style-react#2184]
### Summary:
`<DatePicker/>` on click open up a calendar preview and also focuses input element of DatePicker. In input there is a caret blinking, suggesting that users can type in the date. However, that is not possible as of `wix-style-react@5.0.0`

### Priority:
- [ ] Blocker
- [ ] Urgent
- [X] Normal
- [ ] Minor

### Steps to reproduce:
 1. open https://wix-wix-style-react.surge.sh/?selectedKind=3.%20Inputs&selectedStory=3.6%20DatePicker&full=0&addons=0&stories=1&panelRight=0
 2. click on datepicker in preview section
 3. try to type or paste text

### Expected behavior:
it is possible to provide date by typing or pasting date.
given value should be accepted as correct date.

### Actual behavior:
nothing happens, user is unable to type or paste

### Relevant Components:
`<DatePicker/>`

### Additional notes:
this limitation was done intentionally since wix-style-react version 3.0.0 (probably, maybe 4.0.0). However, some users are asking DatePicker to fully support keyboard

**Comment by shlomitc** [comment]
@milkyfruit - what do you think?

**Comment by milkyfruit** [comment]
I agree we need to fix this.
The current behaviour also causes invisible focus to "dropdown button" which disables arrow movement in a calendar.

Possible solution:
`CalendarInput` and `Calendar` should have separate `tab-index` focuses.

I will review the specs and update with a proposed solution.

**Comment by shlomitc** [comment]
low priority and high effort, won't be fixed
