### ISSUE TITLE
MultiSelectCheckbox's onSelect seems to be called twice

### ISSUE THREAD

**Issue by yaelz** [wix/wix-style-react#2187]
### Summary:

When creating this simple component, onSelect seems to be called twice for MultiSelectCheckbox's onSelect event:

```
<MultiSelectCheckbox
              onSelect={function(item) {
                console.log('WHATTT is this ', item);
                console.log('***********************');
              }}
              options={[
                {
                  id: 'Trending',
                  value: 'Trending',
                },
                {
                  id: 'New Features',
                  value: 'New Features',
                },
                {
                  id: 'Web Design & Wix Editor',
                  value: 'Web Design & Wix Editor',
                },
                {
                  id: 'Web Development & Wix Code',
                  value: 'Web Development & Wix Code',
                },
                {
                  id: 'Marketing & Business Tools',
                  value: 'Marketing & Business Tools',
                },
                {
                  id: 'Professional Services & Wix Products',
                  value: 'Professional Services & Wix Products',
                },
              ]}
            />
```

output when click on the first checkbox:

```
WHATTT is this  {id: "Trending", value: {…}}
***********************
WHATTT is this  Trending
***********************
```
### Priority:
- [ ] Blocker
- [X] Urgent
- [ ] Normal
- [ ] Minor

### Steps to reproduce:
 1. Create the component like above
 2. Check a checkbox :)

### Expected behavior:
Expected the "***********************" to be printed only once, because onSelect is supposed to be called once. It is printed twice - once from the "super".
### Relevant Components:
MultiSelectCheckbox
### Additional notes:
We believe it has to do with calling super._onSelect() on [this line](https://github.com/wix/wix-style-react/blob/master/src/MultiSelectCheckbox/MultiSelectCheckbox.js#L55)

**Comment by yaelz** [comment]
P.S
We do not only _believe_ it has to do with super._onSelect(), but when removing that line it works for us.
Don't want to touch the code because I'm not sure it's fully tested and am pretty sure that whoever put that line did it for some reason.

**Comment by shlomitc** [comment]
Actually `super._onSelect()` does have an effect on it.

This is the `MultiSelectCheckbox` implementation:
```
  _onSelect(option) {
    super._onSelect(option);
    if (this.isSelected(option)) {
      this.props.onDeselect && this.props.onDeselect(option.id);
    } else {
      this.props.onSelect && this.props.onSelect(option.id);
    }
  }
```

As you can see, it calls `this.props.onSelect(id)` on the last line.


If you take a look in `InputWithOptions`, internally it also calls to `onSelect` from props (last long line):

```
_onSelect(option, isSelectedOption) {
    this.showOptions();
    const {onSelect} = this.props;

    if (this.closeOnSelect()) {
      this.setState({showOptions: false});
    }

    if (isSelectedOption) {
      this.setState({showOptions: false});
    } else if (onSelect) {
      onSelect(this.props.highlight ? this.props.options.find(opt => opt.id === option.id) : option);
    }
  }
```

So actually it seems like `inputWithOptions` takes care of the selection and should either not be called, or it should be the only one calling it. I'd go for the first option in order not to break the outer API.

**Comment by shlomitc** [comment]
After discussing - here are the needed actions:

1. in MultiSelectChecbkox.js
    1. remove the super call
    2. add the option to the onSelect and onDeselect callbacks `(optionId, option)`
    3. in the PropTypes comments, explain that optionId and option are called
2. in MultiSelectChecbkox.spec.js
    1. add check that `onSelect` is called once and with the new options


Thanks a lot!

**Comment by shlomitc** [comment]
Fixed in [this PR](https://github.com/wix/wix-style-react/pull/2267)
