### ISSUE TITLE
<Text/> - ellipsis (popover element container) does not align item in the center

### ISSUE THREAD

**Issue by mykas** [wix/wix-style-react#2188]
### Summary:
When text is used together with ellipsis enabled - the wrapped text is not aligned in the center. 
![screen shot 2018-09-04 at 10 10 23](https://user-images.githubusercontent.com/8919190/45015554-c846d380-b02a-11e8-9a26-c1ca93efd797.png)

### Priority:
- [ ] Blocker
- [ ] Urgent
- [x] Normal
- [ ] Minor

### Steps to reproduce:
 1. Enable ellipsis on `<Text/>`
 2. Check text wrapping element.

### Expected behavior:
Text should provide aligned element.

### Actual behavior:
Text is moved to top of the wrapping div.

## Relevant Components:
`<Text/>`

**Comment by lbelinsk** [comment]
@mykas this should be resolved now.
