### ISSUE TITLE
InputWithOptions - when trying to select the selected item, nothing happens

### ISSUE THREAD

**Issue by koriguy** [wix/wix-style-react#2189]
### Summary:
InputWithOptions - when trying to select the selected item, nothing happens

### Priority:
- [ ] Blocker
- [ ] Urgent
- [X ] Normal
- [ ] Minor

### Steps to reproduce:
 1. Select an item from dropdown (e.g 'United States')
 2. open the dropdown again, start typing (e.g 'Uni')
 3. Select the item that was previously selected with the keyboard (e.g 'United States')
4. dropdown is closed but input doesn't show the selected item (it shows 'Uni')

It also happens if you don't type anything, just open with mouse and select the selected item with mouse

### Expected behavior:
should show selected item

### Relevant Components:
InputWithOptions

**Comment by shlomitc** [comment]
Hey, can you please supply a small code snippet?
you can use codesandbox to generate it: https://codesandbox.io/s/mymk2zn1mp

**Comment by koriguy** [comment]
@shlomitc I guess no need since the problem is visible in WSR surge demo:
https://wix-wix-style-react.surge.sh/ 
go to the InputWithOptions component
go to the Controlled input
select one of the options (let's say **Fourth option**)
in the text box, start typing ('For')
and choose **Fourth option** again

**Comment by shlomitc** [comment]
Ok, got it.
Will add it to the backlog.
If you can make a PR that would be great

**Comment by hepiyellow** [comment]
Resolved by #2265
