### ISSUE TITLE
Tooltip - handle long content

### ISSUE THREAD

**Issue by lbelinsk** [wix/wix-style-react#219]
When given a long content it breaks words in the middle

![screen shot 2017-01-25 at 5 02 49 pm](https://cloud.githubusercontent.com/assets/18248989/22295673/6963494e-e320-11e6-8ab1-21ef37094441.png)

**Comment by lbelinsk** [comment]
@mastertheblaster

**Comment by mastertheblaster** [comment]
@lbelinsk It should be already fixed in the latest build.

**Comment by lbelinsk** [comment]
Fixed indeed
