### ISSUE TITLE
SectionHelper is too wide

### ISSUE THREAD

**Issue by qblake** [wix/wix-style-react#2197]
### Summary:
SectionHelper does not fit in the parent container
Example can be found here: https://wix-wix-style-react.surge.sh/?selectedKind=8.%20Notification%20Bars&selectedStory=8.7%20SectionHelper&full=0&addons=0&stories=1&panelRight=0
![image](https://user-images.githubusercontent.com/4469761/45084343-24832380-b10f-11e8-9103-5c002686f0f5.png)

### Priority:
- [ ] Blocker
- [ ] Urgent
- [ ] Normal
- [ ] Minor

### Steps to reproduce:
 1. mm. Just open https://wix-wix-style-react.surge.sh/?selectedKind=8.%20Notification%20Bars&selectedStory=8.7%20SectionHelper&full=0&addons=0&stories=1&panelRight=0

### Expected behavior:
SectionHelper fit to the parent container.
I think addiing `box-sizing: border-box;` to SectionHelper's styles would be enough.

### Relevant Components:
SectionHelper

**Comment by shlomitc** [comment]
Thanks for reporting!
Looks like you're correct. in `wsr@5` we removed some side effect that caused all components to have `box-sizing: border-box`, so some components were missing it previously.

Do you think you can create a small PR fixing it? I'll be happy to merge.
