### ISSUE TITLE
make package lighter - try to remove jQuery, lodash and ReactDom from dependencies

### ISSUE THREAD

**Issue by yanivefraim** [wix/wix-style-react#22]

**Comment by 3LOK** [comment]
Not sure I understand - lodash is a dependency - the package cannot work without it.

**Comment by yanivefraim** [comment]
Yes, I meant to try to remove those from our code in order to make this package lighter

**Comment by nirhart** [comment]
I think that in some cases its better to import only the lodash method we use instead of re-writing it. for example https://www.npmjs.com/package/lodash.uniqueid

**Comment by 3LOK** [comment]
I thought webpack is smart enough to include only the functions we use, event without importing only the methods (wasn't that the result of your test @shahata ?)

**Comment by nirhart** [comment]
@3LOK In some cases lodash is not needed at all and can be replaced by a single row instead, you can see my pr https://github.com/wix/wix-style-react/pull/37. In the other cases I think that even if webpack is excluding all of the unused methods, its better to import only what you have too, it will force us to think twice before using lodash, and use it only if we have to.

**Comment by shahata** [comment]
agree about importing smaller packages forcing you to think twice. also plz note in pr you mostly don't need lodash map/reduce, you have them natively on arrays
