### ISSUE TITLE
<Page/> - make the page extend to full size

### ISSUE THREAD

**Issue by naamagr** [wix/wix-style-react#2212]
### Summary:
Tooltip content is trimmed when it overflows Page content. See the attached image.

### Comment:
setting `flex: 1` style to the `page-scrollable-content` data-hook  seems to solve this issue.

### Priority: Normal

![image](https://user-images.githubusercontent.com/29533829/45159149-b6ae2900-b1ee-11e8-9027-53d64c64b72e.png)

**Comment by yardnsm** [comment]
Reproduced, `flex: 1` solved the issue.

@shlomitc is there any reason why not to add `flex: 1` for the page's content by default?

If there is one, we can add a prop to `<Page/>` to do that (probably `expandPageContent`).

**Comment by shlomitc** [comment]
Mmm good question.
Please ask Amir Yonatan or Erez if they remember anything about it .

**Comment by shlomitc** [comment]
Anyway, sounds to me like it should be a default behavior

**Comment by yardnsm** [comment]
Resolved in https://github.com/wix/wix-style-react/pull/2342
