### ISSUE TITLE
<Tooltip/> - integrating <Calendar/> week days are overflowing and splitting into two lines

### ISSUE THREAD

**Issue by naamagr** [wix/wix-style-react#2213]
### Summary:
Calendar days `Mo` and `We` are overflowing their wrapper.
Since tooltip content has a style `word-wrap: break-word`,  rendering `Calendar` inside a `Tooltip` causes these words to break (see image below).

### Priority: Normal

![image](https://user-images.githubusercontent.com/29533829/45162586-ff69e000-b1f6-11e8-9bc8-0366968c5b5f.png)

**Comment by hepiyellow** [comment]
@wuwa @dkomanov 
Shouldn't there be a component with a dropdown date selection that can say "Today" instead of the date?

**Comment by shlomitc** [comment]
@hepiyellow - it’s called Tag component.
We want to allow custom popover with custom triggers, instead of creating new components for each popover

**Comment by milkyfruit** [comment]
@hepiyellow yes, Shlomi is right, we don't want to restrict where the calendar is opened from.
We want to allow any component opening it:
![screen shot 2018-09-18 at 10 57 48](https://user-images.githubusercontent.com/1684587/45672775-b177a500-bb31-11e8-8993-1823bcd991f6.png)

**Comment by Faradey27** [comment]
fixed
