### ISSUE TITLE
Render Rich Text 

### ISSUE THREAD

**Issue by zivl** [wix/wix-style-react#2241]
### Summary:
I want to be able to render rich-text just like I have the ability to create one with the `RichTextInput` Component.
e.g.
```javascript
const htmlString = '<p>Hello <a href="#">this is a link</a> and This is <b>bold text</b></p>';
.
.
.
<RichText>{htmlString}</RichText>
```

### Priority:
- [ ] Blocker
- [X] Urgent
- [ ] Normal
- [ ] Minor

**Comment by shlomitc** [comment]
As this is just a simple action, I’d suggest using React’s native ‘dangerouslySetInnerHTML’ function.

https://reactjs.org/docs/dom-elements.html#dangerouslysetinnerhtml

Looks to me straightforward unless I miss something

**Comment by shlomitc** [comment]
ping?

**Comment by zivl** [comment]
the thing with `dangerouslySetInnerHTML` is that its it dangerous :)
it allows the user to write `<script>` tag with malicious content.
I would like to have a safe component that is the *rendering* part of the `wix-style-react/RichTextArea` component.

**Comment by shlomitc** [comment]
Just to clarify - are you talking about the rendering of the malicious code **while editing** the `RichTextArea` component or the output of it when you want to display the output as part of your application?

or in other words - protect `RichTextArea` or create a new component?

**Comment by shlomitc** [comment]
just to summarize and close the issue - the idea was to create a component that renders the html safely, for example using DOMPurify.

I'll be happy to suggest our users using such a component, but I'm not sure it should sit in the wix-style-react. probably should be a simple open source library.

Thanks
