### ISSUE TITLE
TableActionCell rtl support

### ISSUE THREAD

**Issue by lbelinsk** [wix/wix-style-react#2244]
There was an issue with the rtl syntax in the TableActionCell stylesheet, so this pr was merged as a hot fix:
https://github.com/wix/wix-style-react/pull/2243

1. The class `.actionsContainer` is not being used anywhere, so maybe this code should get erased?
2. Why do we support only class rtl and not also dir .rtl (we do that in many places and is is a best practice)
3. Why we have the tr in this selector?

**Comment by rghorbani** [comment]
This code fix does not work either. I fixed it in #2224.
