### ISSUE TITLE
[circularProgressBarTestkitFactory] Error when creating driver when no progress bar rendered

### ISSUE THREAD

**Issue by ipanasenko** [wix/wix-style-react#2259]
I get this error:

`TypeError: Cannot read property 'querySelector' of undefined`

I will try to come up with minimum reproducible example, ping me if it's necessary.

Basically, all I do is `circularProgressBarTestkitFactory({ wrapper: this.component, dataHook: 'uploading-file-percentage' })`, when elemenet with `dataHook` is not rendered

**Comment by shlomitc** [comment]
a simple reproducible example will be helpful, thanks!

**Comment by nitayneeman** [comment]
The issue will be resolved as part of https://github.com/wix/wix-ui-backoffice/pull/264.
I'm closing this issue.
