### ISSUE TITLE
Datepicker issue

### ISSUE THREAD

**Issue by lbelinsk** [wix/wix-style-react#226]
When trying to skip to a future year the UI isn't nice

@nirhart 

![screen shot 2017-01-26 at 10 51 08 am](https://cloud.githubusercontent.com/assets/18248989/22325106/5d91deec-e3b5-11e6-87b2-a5713aa62f1f.png)

**Comment by lbelinsk** [comment]
@nirhart this is relevant for Guineapig

**Comment by nirhart** [comment]
Done
