### ISSUE TITLE
`<MultiSelect/>` - Tab is not working, can not focus out of the component.

### ISSUE THREAD

**Issue by hepiyellow** [wix/wix-style-react#2263]
### Priority:
- [ ] Blocker
- [ ] Urgent
- [x] Normal
- [ ] Minor

### Steps to reproduce:
 1. Got to https://wix-wix-style-react.surge.sh/?selectedKind=3.%20Inputs&selectedStory=3.8%20Tags&full=0&addons=0&stories=1&panelRight=0
 2. click any `<MultiSelect/>`
 3. Try to press Tab to go to the next component.

**Comment by shlomitc** [comment]
done
