### ISSUE TITLE
<SideMenu.NavigationLink /> Wrong size

### ISSUE THREAD

**Issue by milkyfruit** [wix/wix-style-react#2277]
### Summary:
Two issues regarding [`<SideMenu.NavigationLink />`](https://wix-wix-style-react.surge.sh/?selectedKind=6.%20Navigation&selectedStory=6.1%20%2B%20SideMenu&full=0&addons=0&stories=1&panelRight=0) size:
1. Block's height increases to 52px when it has a drill-in arrow. It should always stay `42px`.
2. Line-height changes from 14px to 24px on active state. It should always stay `18px`.

### Priority:
- [ ] Blocker
- [ ] Urgent
- [x] Normal
- [ ] Minor

Reported by Gal Elmalah:

> hey guys the SideMenu.NavigationLink component is getting larger on active state. from height 14px to 24px. I added a temp hack on our project but just letting you guys know.

### Link to Specs:
zpl.io/bPq4dWm

**Comment by shlomitc** [comment]
the component is going to be restructured soon, so it won't be fixed
