### ISSUE TITLE
CI - eyes test timed out

### ISSUE THREAD

**Issue by hepiyellow** [wix/wix-style-react#2287]
I see many times that tests get Timeout error.
I guess you also.
In mist cases I find missing `async/await`, fix it, and re-run the build.
But I think the tests are flakey also without having missing `async/await`.

Need to investigate what is causing protractor tests to get  timeout when running in CI.

Here are some build failure examples :
- [1](http://pullrequest-tc.dev.wixpress.com/viewLog.html?buildId=869592&buildTypeId=FedInfra_WixStyleReact&tab=buildLog)
- [2](http://tc.dev.wixpress.com/viewLog.html?buildId=69747520&buildTypeId=CommonComponent_WixStyleReact&tab=buildLog) - It doesn't have any missing `async/await`.
- [3](http://pullrequest-tc.dev.wixpress.com/viewLog.html?buildId=911753&buildTypeId=FedInfra_WixStyleReact&tab=buildLog)
- [4](http://pullrequest-tc.dev.wixpress.com/viewLog.html?buildId=879229&buildTypeId=FedInfra_WixUiBackoffice&tab=buildLog) - [`wix-ui-backoffice`]
- [5](http://pullrequest-tc.dev.wixpress.com/viewLog.html?buildId=919089&buildTypeId=FedInfra_WixStyleReact&tab=buildLog)
- [6](http://pullrequest-tc.dev.wixpress.com/viewLog.html?buildId=920102&buildTypeId=FedInfra_WixStyleReact&tab=buildLog)

Possible reasons:
- CI agent high CPU 
- Applitools `checkWindow` request does not get a response (maybe network is busy)

**Comment by hepiyellow** [comment]
@Faradey27 Do you know how to log into the CI' agent, and see logs.
Network logs, CPU, etc...

**Comment by mykas** [comment]
@hepiyellow I think we are coming back to the same issue here that we don't know what kind of protractor config is being run in CI. I suspect that chrome is not running in headless mode in CI and we only run 1 instance of it. So basically high cpu could cause chrome instance to freeze and so we get timeouts etc. Maybe if you could continue on figuring out protractor configuration in CI could help. And btw its not from our repo its something coming from yoshi thats beeing merged with our config.

**Comment by hepiyellow** [comment]
The main suspect is `eyes` which probably doesn't get an HTTP  response.

We can try in `eyes.it` to add error handling for the `eyes.close()` call. So we can see if that is really the issue.

**Comment by hepiyellow** [comment]
Replaces by #2599
