### ISSUE TITLE
At the autoComplete component, maybe add a small arrow for the dropDown

### ISSUE THREAD

**Issue by lbelinsk** [wix/wix-style-react#23]
![screen shot 2016-11-29 at 2 58 59 pm](https://cloud.githubusercontent.com/assets/18248989/20710730/68065d10-b644-11e6-8111-b9cfaffe1d5c.png)

**Comment by 3LOK** [comment]
The arrow is not a standard element in a 'auto complete text box'. 

See for example the 'search' bar on the top of this page, or google search bar, etc...

The component you're talking about is a DropDown list, which also will be implemented.
