### ISSUE TITLE
Input field missing a class on parent div

### ISSUE THREAD

**Issue by timgws** [wix/wix-style-react#2301]
### Relevant Components
&lt;Input>

wix-style-react v5.5.0 (tested on react 15 and 16)

### Current Behavior
Browser renders <Input> incorrectly

![screen shot 2018-10-08 at 3 52 42 am](https://user-images.githubusercontent.com/1050232/46584317-a4553280-caad-11e8-915e-d2c54142d53e.png)
![screen shot 2018-10-08 at 3 53 01 am](https://user-images.githubusercontent.com/1050232/46584337-ac14d700-caad-11e8-8303-a19dfbd588d1.png)

### Expected Behavior
The &lt;div> before the &lt;input> should have a class with the following style:

```
    display: -webkit-box;
    display: -ms-flexbox;
    display: flex;
    width: 100%;
```

### Steps to Reproduce
Create a new React app. Run:
```
yarn add wix-style-react
```

Add a new Component that looks something like this:

```
import React from 'react';

import Page from 'wix-style-react/Page';
import Button from 'wix-style-react/Button';
import EmptyState from 'wix-style-react/EmptyState';
import {Add} from 'wix-style-react/new-icons';

import FormField from "wix-style-react/FormField";
import Input from "wix-style-react/Input";

const App = () => (
    <div data-hook="story-page-empty-state" style={pageContainerStyles} className="pageContainerStyles">
        <Page theme={"default"}>
            <Page.Header
                title="Your Product"
                actionsBar={<Button withNewIcons prefixIcon={<Add/>}>New Item</Button>}
            />

            <Page.Content>
                <EmptyState
                    theme="page"
                    title="You don't have any items yet"
                    subtitle="Create your product item in an easy & fast way to display it on your website"
                >
                    <FormField label={"Email"}>
                        <Input placeholder={"lol"} theme={"normal"} size={"large"}/>
                    </FormField>
                </EmptyState>

            </Page.Content>
        </Page>
    </div>
);

export default App;
```

Notice that the input field does not have a class on the &lt;div> before the &lt;input>.

Note: I did try to build wix-style-react from source, but kept hitting a dependency on teamcity-surge-autorelease that I could not skip without editing the package.json's that included it as a dependency.

### Severity
- [ ] Critical
- [ ] Major
- [ ] Low

**Comment by timgws** [comment]
Hi @hepiyellow 

Thanks so much for your quick reply!

I tried copying & pasting the code into CodeSandbox and the input field appears fine.

I have created a copy of what I am running here:

https://github.com/timgws/wix-style-react-2301

If you clone that package, run `npm install`, and `npm run build`, you should see what I am seeing.

(I was aware of pageContainerStyles, removing it still shows the exact same behavior).

**Comment by hepiyellow** [comment]
Good news !

The class that is missing has a `-` in it. (`input-wrapper`).
But in the JS file it is referred to as `inputWrapper` (CamelCase).

For this to work, you need in your `webpack.config.json`, to add the `camelCase` option to the `css-loader` config.

If you take a look at this Wix-Style-React documentation page [Usage Without Yoshi](https://wix-wix-style-react.surge.sh/?selectedKind=Introduction&selectedStory=Usage%20Without%20Yoshi&full=0&addons=0&stories=1&panelRight=0).
You'll see that the css-loader config has a `camelCase` option.
```
loaders: [
          'style-loader',
          'css-loader?modules&importLoaders=1&camelCase&localIdentName=[name]__[local]___[hash:base64:5]',
          'sass-loader'
        ],
```

Enjoy (-:

**Comment by vonex-tim** [comment]
@hepiyellow ah! thanks! The additional `camelCase` was way too easy to miss.
