### ISSUE TITLE
<DropdownLayout/> - support IE11 

### ISSUE THREAD

**Issue by giladsegal** [wix/wix-style-react#2304]
# Bug Report

### Relevant Components
`<DropdownLayout>`

### Current Behavior
Passing JSX elements to `options` prop throws an error when `componentWillReceiveProps` is triggered

### Expected Behavior
No error is thrown

### Steps to Reproduce
I've created a sandbox project but sadly codesandbox doesn't work in IE11
Anyway, you can examine the example in chrome and reproduce it in some IE11 environment
https://codesandbox.io/s/k20wy29o7v

### Severity
- [X] Critical
- [ ] Major
- [ ] Low

I've done some research and I think I know the root cause:
* `componentWillReceiveProps` of `<DropdownLayout>` uses `deep-eql` library
* `deep-eql` uses `WeakMap` behind the scenes 
* IE11 doesn't support frozen elements as `WeakMap` keys as you can see [here](http://kangax.github.io/compat-table/es6/#test-WeakMap)
* JSX elements are frozen (react internal implementation) 
* JSX elements in `options` prop are sent to `deep-eql` library for props comparison
* JSX elements are being used as keys of `WeakMap` inside `deep-eql` --> an error is thrown

`<DropdownLayout>` is the only place in `wix-style-react` where `deep-eql` is used and if this method call is removed the code still works (it might even improve performance slightly as no objects are being tested for deep equality)

**Comment by shlomitc** [comment]
Fixed and merged
https://github.com/wix/wix-style-react/commit/626fa7303683f0742e5f44ecc717089849bc8bf5
