### ISSUE TITLE
CI build too long due to snapshot tests

### ISSUE THREAD

**Issue by hepiyellow** [wix/wix-style-react#2314]
# Ways to reduce the time
- Use Applitools render grid
- Reduce snapshot size (use `checkRegion` instead of `checkWindow`)
- Storybook page load time - is this an issue? Can we have the test pages rendered out-side of Storybook?
- Reduce redundant snapshots - eyes.it configuration `disableSnapshotAtBrowserGet`,etc...

## Current status
Waiting....
Waiting for core3 to finish integration with render grid. It seems like it would be the most significant optimization (no need to upload many big images). And it should be easy to integrate with WSR.

**Comment by shlomitc** [comment]
I would go with Applitools render grid, as the best solution for 80% of the problem.
I don't see a reason to keep it open, just get to it soon
