### ISSUE TITLE
ColorPicker- letter in RGB results in NaN in all the tabs

### ISSUE THREAD

**Issue by Roeia1** [wix/wix-style-react#2316]
# Bug Report

### Relevant Components
ColorPicker

### Current Behavior
When typing a letter inside the RGB input, it's showing NaN

### Expected Behavior
Better to just ignore when letters are being typed there imo

### Steps to Reproduce
in storybook open ColorPicker and type a letter in the RGB tab

### Severity
- [ ] Critical
- [ ] Major
- [X] Low

**Comment by shlomitc** [comment]
low priority, won't be fixed
