### ISSUE TITLE
deprecationLog

### ISSUE THREAD

**Issue by hepiyellow** [wix/wix-style-react#2323]
Looking at the code of deprecationLog:
https://github.com/wix/wix-style-react/blob/master/src/utils/deprecationLog.js
It checks :
```
   if (process.env.NODE_ENV !== 'production') {
```

If the purpose is that the production client won
t log these deprecation warnings, then I don't think it works, since the client does not have a `process.env.NODE_ENV`.

@Faradey27 How does this work? Is this pre-processed at build time?

**Comment by shlomitc** [comment]
https://webpack.js.org/plugins/environment-plugin/
