### ISSUE TITLE
Collapsable <Card /> jitter when inner height has changed since last render

### ISSUE THREAD

**Issue by david-pe** [wix/wix-style-react#2324]
# Bug Report

### Relevant Components
Collapsable \<Card /\>

### Current Behavior
When the card's content's height changes while the card is expanded the user will experience a jump from the previous stored height to the current height at next render 

### Expected Behavior
Nothing should happen at re-render

### Steps to Reproduce
see here - https://github.com/nkbt/react-collapse/issues/191

### Severity
- [ ] Critical
- [x] Major
- [ ] Low

**Comment by shlomitc** [comment]
Thanks.
Do you have a suggestion how to solve this?

**Comment by david-pe** [comment]
suggestion: add a callback to the wrapping component to force **recalc w/o render**. This will update the `from` height for next render.

**Comment by EgoziE** [comment]
We upgraded `react-collapse` to version 5.
This issue should be solved now, feel free to reopen if needed.
