### ISSUE TITLE
Dropdown with fixed footer has 2 scrollbars under certain conditions

### ISSUE THREAD

**Issue by Jefoss** [wix/wix-style-react#2331]
# Bug Report

### Relevant Components
Dropdown

### Current Behavior
When there are enough options / the options are big enough for a scrollbar to appear,
and theres a fixed footer with some height, there will be another scrollbar beside the existing one.

### Expected Behavior
there shouldn't be another scrollbar for the fixed footer

### Steps to Reproduce
a reproducible example: 
https://codesandbox.io/s/8z3v17y7k9

### Severity
- [ ] Critical
- [ ] Major
- [X] Low

**Comment by shlomitc** [comment]
![image](https://user-images.githubusercontent.com/6093192/50480931-88479a00-09e7-11e9-88d0-fa8258df96c4.png)

**Comment by shlomitc** [comment]
here's a reproducible example

```jsx
<Dropdown
  placeholder="Select dominant hand"
  options={[
    { id: 0, value: 'Left' },
    { id: 1, value: 'Right' },
    { id: 2, value: 'Ambidextrous' },
    { id: 3, value: 'asd' },
    { id: 4, value: 'vvv' },
    { id: 5, value: 'vvvaaa' },
    { id: 6, value: 'vsdasdsadvv' },
  ]}
  fixedFooter={
    <div style={{ padding: '12px' }}>
      <TextButton prefixIcon={<Add />}>Add new item</TextButton>
    </div>
  }
/>
```

Scroll on the fixed footer area and it will create the second scroll.

A quick fix is by applying `flex` to the container

**Comment by shlomitc** [comment]
done here https://github.com/wix/wix-style-react/pull/2969
