### ISSUE TITLE
Selector component title & subtitle are displayed in one line

### ISSUE THREAD

**Issue by D0vydas** [wix/wix-style-react#2337]
# Bug Report

### Relevant Components
`Selector`

### Current Behavior
<img width="592" alt="screen shot 2018-10-16 at 14 33 23" src="https://user-images.githubusercontent.com/6649425/47014096-e63b4400-d151-11e8-92aa-91a41aba2fdf.png">

### Expected Behavior
<img width="586" alt="screen shot 2018-10-16 at 14 45 04" src="https://user-images.githubusercontent.com/6649425/47014165-1da9f080-d152-11e8-8bb7-b7f9ca54c40b.png">

### Severity
- [x] Critical
- [ ] Major
- [ ] Low

**Comment by shlomitc** [comment]
fixed
https://github.com/wix/wix-style-react/pull/2336
