### ISSUE TITLE
Placeholders of RichTextArea and InputArea are not the same colors has other components

### ISSUE THREAD

**Issue by gilisho** [wix/wix-style-react#2341]
# Bug Report

### Relevant Components
RichTextArea and InputArea (these are the components that I know, there could be more).

### Current Behavior
Placeholders of RichTextArea and InputArea are not the same colors as other components of WSR.

### Expected Behavior
RichTextArea and InputArea's placeholder's color are changed to be the same as the others (example below).

### Steps to Reproduce
https://codesandbox.io/s/r51z2nr39p

### Severity
- [ ] Critical
- [ ] Major
- [ X ] Low

**Comment by shlomitc** [comment]
Thanks for reporting!
A pull request will be greatly appreciated.

**Comment by shlomitc** [comment]
All relevant input field are now using `D40` (#7a92a5) from the color palette. It seems ok, so please re-open if you encounter any issues.
