### ISSUE TITLE
<Modal/> -  not scrollable to to if content is too high

### ISSUE THREAD

**Issue by maxaon** [wix/wix-style-react#2344]
# Bug Report
If modal doesn't fit the window top part of modal is hidden and it's not possible to scroll to it. And in our product user cannot close modal and stays with our wizard forever.
### Relevant Components

Modal
### Current Behavior

If modal is too high and doesn't fit window user can scroll to bottom but not to the top of modal
### Expected Behavior

All modal content should be scrollable, visible and acceceble
### Steps to Reproduce
[https://codesandbox.io/s/xr6rq60oxo](https://codesandbox.io/s/xr6rq60oxo)

![www wix com_dashboard_9a70d363-f222-4512-a385-6032257d292f_store_products_product_59bdc5db-787c-2e4a-4bf9-70609769f62d](https://user-images.githubusercontent.com/3187207/47082212-8c9c4d80-d215-11e8-8dff-b58ff43178c7.png)

### Severity
- [ ] Critical
- [x] Major
- [ ] Low

**Comment by shlomitc** [comment]
Hey! thanks for reporting an issue.
As a quick fix (or maybe even a solid one) - you can use the `maxHeight` prop. It will also set the right scrollbar look and feel for the internal content.

We'll take a deeper look at it

**Comment by EgoziE** [comment]
to reproduce:
```
      <Modal isOpen={true}>
        <MessageBoxFunctionalLayout
          theme="blue"
          title="Modal With Close Button Example"
          confirmText="OK"
          cancelText="Cancel"
        >
          {"I Have a close button on the upper right corner but its impossible to press without deleting the github creature first using the console ".repeat(
            30
          )}
        </MessageBoxFunctionalLayout>
      </Modal>
```

**Comment by EgoziE** [comment]
Does not happen with new modal - closing
