### ISSUE TITLE
`<TableToolbar/>` - <ItemGroup position="start"> has no affect

### ISSUE THREAD

**Issue by hepiyellow** [wix/wix-style-react#2346]
the position prop has no affect.
- The ItemGroups are positioned with space-between - regardless of the position value
- The position value translates to `positionStart` class without using the Stylsheet (global class which does not exist)

**Comment by shlomitc** [comment]
So what should be fixed then?

**Comment by shlomitc** [comment]
as this has no major effect nor complains, I'm closing
