### ISSUE TITLE
<Input />  - support setSelectionRange 

### ISSUE THREAD

**Issue by kelyar** [wix/wix-style-react#2349]
# Bug Report

### Relevant Components

[Input /]

### Current Behavior

there is a way to select everything that is inside Input.

### Expected Behavior

in media manager g6 we have an input with file name. (111.jpg)
but we want to autoselect only part of filename without extension (111)

### Severity
- [ ] Critical
- [ ] Major
- [x] Low

One of possible solutions is to add optional parameters to select() API
If parameters exist, we'll run setSelectionRange instead.
https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/setSelectionRange

**Comment by shlomitc** [comment]
the input `ref` is available, so no additional action is needed
