### ISSUE TITLE
<ColorPicker/> - keyboard enter doesn't trigger the 'onConfirm' callback

### ISSUE THREAD

**Issue by miroshSa** [wix/wix-style-react#2353]
# Bug Report

### Relevant Components
ColorPicker

### Current Behavior
Event 'onConfirm' doesn't trigger. 

### Expected Behavior
Event 'onConfirm'  should be triggered.

### Steps to Reproduce
Put some value into the input in and click 'Enter'

### Severity
- [ ] Critical
- [ ] Major
- [ ] Low

**Comment by nitayneeman** [comment]
Fixed as part of this PR:
https://github.com/wix/wix-style-react/pull/2683
