### ISSUE TITLE
<TextLink /> - add size `tiny`

### ISSUE THREAD

**Issue by ipanasenko** [wix/wix-style-react#2364]
Hey, guys.

We have `tiny` size (12px) for `Text`, but we don't have it for `TextLink`. Do you think we should have it?

Thanks!

**Comment by shlomitc** [comment]
Hey.
So the short answer - we need to have a way to display a textual link with tiny size.

For the longer answer:

Currently, the `TextLink` component is a mixture of both the `Text` component and `TextButton` component. For example, its props (theme, suffix icons) are related to the button behavior, but it acts as a link but not as a button.

`Text` with link capability should have the `tiny` size.
`TextButton` currently have only small (18) and medium(24) sizes.

@milkyfruit - if we allow `TextButton` in the spec, we can get the `tiny` size also for links which is the requested change, are you ok with that?

**Comment by milkyfruit** [comment]
@ipanasenko @shlomitc 
Hi,
So, first of all, do we have a request for this feature or it's more being technically aligned?
I'm ok with introducing tiny size for a text link, the only concern is what prefix/suffix icon we'll use for it?
We're planning to introduce 'small' icon size which is 18x18, but it'll be still too large to fit with tiny text size, which has 15px line-height. Need to make some design tests first, I think.

**Comment by ipanasenko** [comment]
I'm only asking about new size because I have a 12px text with a link in it. It will look weird to have 12px text and bigger link

**Comment by shlomitc** [comment]
@ipanasenko - we're going to add link styling to the `<Text/>` component.
So all you need to do is `<Text size="tiny"><a>my tiny link</a></Text>`
https://github.com/wix/wix-style-react/pull/2384

**Comment by shlomitc** [comment]
Released in v5.8.0
