### ISSUE TITLE
Contribution question

### ISSUE THREAD

**Issue by ImmanuelSegol** [wix/wix-style-react#2385]
Hi,
I really want to contribute. 
Witch issue can I take?

**Comment by argshook** [comment]
Hello!

what a noble cause, I welcome you with open arms :)

we always have issues to work on and you can see them here on github. Just find one you are interested in and shoot a message there, so we'll know someone is on it.

there could be issues that are not relevant anymore or no longer in priority so don't hesitate to post questions, even if you have multiple. just tag me and i will try to help you from there.

cheers!
