### ISSUE TITLE
<DropdownLayout /> selected item loses focus after "enter" is pressed

### ISSUE THREAD

**Issue by milkyfruit** [wix/wix-style-react#2386]
# Accesibility Report

### Relevant Components
[`<DropdownLayout />` ](https://wix-wix-style-react.surge.sh/?selectedKind=11.%20Pickers%20and%20Selectors&selectedStory=11.1%20DropdownLayout&full=0&addons=0&stories=1&panelRight=0=)

### Current Behavior
On Key Press "Enter" the highlighted list item gets "selected" status, but loses the focus. If arrow key up or down is pressed the scroll starts from beginning or end of the list.

### Expected Behavior
Continue scrolling from the selected item after "enter" is pressed.

### Severity
Major

**Comment by yardnsm** [comment]
This is actually the desired behaviour of the `<DropdownLayout/>`, as the parent component that uses it is responsible of setting the `selectedId` for it. Try playing with `<Dropdown/>` component, it'll behave as expected.

**Comment by yardnsm** [comment]
Do we want this behaviour in `<DropdownLayout/>`? It *already* keeps the `selectedId` in its internal state, so it won't be a problem to implement it.

Currently, when an item is selected, the hover is explicitly reset:

https://github.com/wix/wix-style-react/blob/03654f0dd29e59b100d4c6dab5b2250d9a7c258d/src/DropdownLayout/DropdownLayout.js#L78-L98

The hover is set to the `selectedId` when the `<DropdownLayout/>` becomes visible:

https://github.com/wix/wix-style-react/blob/03654f0dd29e59b100d4c6dab5b2250d9a7c258d/src/DropdownLayout/DropdownLayout.js#L295-L302

All the components that uses `<DropdownLayout/>` (`<BadgeSelect/>`, `<InputWithOptions/>`, `<Dropdown/>`, `< MultiSelectCheckbox/>`) seems to work as expected. The question is if do we need to support it in `<DropdownLayout/>`.

**Comment by milkyfruit** [comment]
@yardnsm You're right, I tested [4.1 Dropdown](https://wix-wix-style-react.surge.sh/?selectedKind=4.%20Selection&selectedStory=4.1%20Dropdown&full=0&addons=0&stories=1&panelRight=0) snippet, it seems to work.
Though, there's one glitch – it requires pressing arrow down twice if the first option is selected. For other options it seems to works fine.

**Comment by yardnsm** [comment]
@milkyfruit this was actually fixed in https://github.com/wix/wix-style-react/pull/2405 :)

Can we close this issue?

**Comment by milkyfruit** [comment]
@yardnsm yes, lets close this issue then :)
