### ISSUE TITLE
<TextArea /> There is no "Disabled" prop

### ISSUE THREAD

**Issue by milkyfruit** [wix/wix-style-react#2394]
# Bug Report

### Relevant Components
[`<InputArea />`](https://wix-wix-style-react.surge.sh/?selectedKind=3.%20Inputs&selectedStory=3.2%20%2B%20InputArea&full=0&addons=0&stories=1&panelRight=0) doesn't have `disabled` prop, when adding it to native HTML component, it's not styled.

### Expected Behavior
When `disabled` prop is enabled, the component should follow[ these specs.](https://zpl.io/2vxO4Ya)

### Severity
**Critical**

The fix was requested by Wix Media team.

**EDIT:** Initially I reported this bug for`<TextArea />`, however I confused it with `<InputArea />`.

**Comment by ImmanuelSegol** [comment]
@milkyfruit @argshook  Can I take this?

**Comment by shlomitc** [comment]
@immanuelSegol sure thing. Please refer to the contribution guide https://github.com/wix/wix-style-react/blob/master/CONTRIBUTION.md
@milkyfruit - can you please export the spec in a way also external contributor can see it?

**Comment by milkyfruit** [comment]
@ImmanuelSegol Here's the disabled colors for `<InputArea />`:
![image](https://user-images.githubusercontent.com/1684587/47907616-43463200-de94-11e8-9367-7cdbbd56fed5.png)

**Comment by shlomitc** [comment]
fixed and available in latest release
