### ISSUE TITLE
<Button />  - add min-width to component

### ISSUE THREAD

**Issue by milkyfruit** [wix/wix-style-react#2412]
EDITED: Added min-width default values for each button size.

# Feature Request

### Description
[`<Button />`](https://wix-wix-style-react.surge.sh/?selectedKind=5.%20Buttons&selectedStory=5.1%20Standard&full=0&addons=0&stories=1&panelRight=0) component needs a `min-width` property.
It should have a default value, which varies based on button size:

`min-width` default values by button size:

Large – `102px`
Medium – `84px` 
Small – `72px`
Tiny – `60px`

The overrides are allowed.

### Severity
Critical / Major

Wix Restaurants requested for this prop in their product.

### Link to specs
https://zpl.io/aRq9ZKv

**Comment by shlomitc** [comment]
@milkyfruit - is this the requirement for the default behavior of a button? or have it as an optional way of controlling the min-width?

**Comment by milkyfruit** [comment]
@shlomitc `min-width` should always exist with some default value. Each button size has its own default value. It should be allowed to override it if needed.

Updated [the specs](https://zpl.io/aRq9ZKv) specifying default `min-width` default values:
![image](https://user-images.githubusercontent.com/1684587/48545726-44815100-e8cf-11e8-988c-4ca57055cf61.png)

**Comment by mykas** [comment]
Done
