### ISSUE TITLE
<Page.Header /> show ellipsis instead of wrapping

### ISSUE THREAD

**Issue by milkyfruit** [wix/wix-style-react#2413]
# Bug Report

### Relevant Components
[`<Page.Header />`](https://wix-wix-style-react.surge.sh/?selectedKind=2.%20Layout&selectedStory=2.5%20%2B%20PageHeader&full=0&addons=0&stories=1&panelRight=0) title and subtitle should show ellipsis instead of wrapping text on long values.

Now:
![image](https://user-images.githubusercontent.com/1684587/48010068-8e2aa880-e125-11e8-9d91-5c4cb03ff2ed.png)

Expected:
![image](https://user-images.githubusercontent.com/1684587/48010086-9551b680-e125-11e8-9ccf-2e68f14b1a07.png)

### Severity
Major

### Link to Specs
https://zpl.io/bAE7QB8 (Needs an update)

**Comment by shlomitc** [comment]
I think Erez worked on it a few months ago and it was too complicated...
@hepiyellow - Do you remember it?

**Comment by hepiyellow** [comment]
Well, 
- there was this PR #2174 which added the ellipsis.
- And this PR #2209 reverted it.
- In this PR #2207 (which was suppose to revert ellipsis, but 2209 was the final PR that did get merged), arijus writes: 

  > "adding ellipsis slightly changes the height of heading and text and thus break many e2e tests. Reverting until we fix it"

**Comment by shlomitc** [comment]
this PR should fix the height (actually alignment) https://github.com/wix/wix-ui/pull/867
we'll see if it's possible to be fixed after it gets merged

**Comment by hepiyellow** [comment]
@shlomitc 
https://github.com/wix/wix-ui/pull/867 was merged.

We can try to add ellipsis now.

**Comment by shlomitc** [comment]
done
