### ISSUE TITLE
BadgeSelect shouldn't be a controlled component 🍄

### ISSUE THREAD

**Issue by aryelu** [wix/wix-style-react#2432]
# Bug Report

### Relevant Components
BadgeSelect

### Current Behavior
Select an option from the dropdown will change the `selectId`

### Expected Behavior
When selecting only invoke `onSelect` and let `onSelect` determine the outcome

### Steps to Reproduce
https://codesandbox.io/s/7w49xklnnx

### Severity
Critical

**Comment by yardnsm** [comment]
The `<BadgeSelect/>` is actually *partially* controlled, like the `<Dropdown/>` component. It tries to be both controlled and uncontrolled in the same time.

You can see an example here: https://codesandbox.io/s/xr76q6r9lq

When you provide a new `selectedId`, it'll update it's internal state to match it. But, when the `selectedId` won't change, it update the internal state according to the user selection.

We can, maybe, set the component to be uncontrolled when you don't pass `selectedId`, but then we'll get a different behavior than the Dropdown's. 

@shlomitc

**Comment by aryelu** [comment]
to make it clear I'm looking to set the `selectedId` in the `onSelect` prop.
my use case is to make the user approve his selection before the state will change using a modal.

**Comment by aryelu** [comment]
Hi, I’ve tried the controlled badgeSelect (btw ty!!) and it has a weird issue, the selectId is controlled as I selected but the dropdown shows the one I’ve clicked (edited)
![image](https://user-images.githubusercontent.com/11705492/48371234-ff3d0380-e6c3-11e8-8c60-487218c81ced.png)

**Comment by shlomitc** [comment]
fixed in v15.4.0
