### ISSUE TITLE
<Button/> - x-small size with affixes has wrong margins

### ISSUE THREAD

**Issue by LittleTal** [wix/wix-style-react#2435]
In `<Button/>` component with suffix/prefix props- margin and padding are not aligned to guidelines. 
A fix is needed for all available height prop.

For example in `height: x-small`

Margin should be 0px instead of 10px.

Also, padding should be: 
**Prefix:**
    padding-right: 12px;
    padding-left: 6px;

**Suffix:**
    padding-right: 6px;
    padding-left: 12px;

Component should be aligned to [zeplin guidelines](https://zpl.io/aRq9ZKv):

![image](https://user-images.githubusercontent.com/23282301/48132245-96a4ef80-e29b-11e8-808d-fbc10cbcad19.png)

### Severity
Critical

**Comment by mykas** [comment]
Hi, thanks for your input! I am working at this moment on introducing all the buttons aligned to specifications. It is already done in our core repo so it stay on.

**Comment by shlomitc** [comment]
done
