### ISSUE TITLE
Small size tag with thumb has wrong padding left

### ISSUE THREAD

**Issue by naamagr** [wix/wix-style-react#2461]
# Bug Report

### Current Behavior
Small size tag with thumb has wrong padding left. See image below.
![image](https://user-images.githubusercontent.com/29533829/48415565-63a8a300-e756-11e8-88d0-01e96ba3422c.png)

### Steps to Reproduce 
render Tag component with size small and thumb.

### Severity
Major

**Comment by nitayneeman** [comment]
Hi,

I checked the visual design and it seems that the implementation is aligned with the specification (3px on the left, 6px in the middle and 12px on the right):
![screen shot 2018-12-26 at 9 27 34](https://user-images.githubusercontent.com/7141972/50436908-8a7afd00-08f0-11e9-813e-27622ef578df.png)
