### ISSUE TITLE
<Table/> clickable table row styles `cursor: pointer` on all children

### ISSUE THREAD

**Issue by Wo1v3r** [wix/wix-style-react#2463]
# Bug Report

### Relevant Components
Table

### Current Behavior
When having a clickable row, all children elements are styled with `cursor: pointer` for example:
- Have a clickable row
- Use TableActionCell

All popover menu items are "clickable" in an area that isn't actually clickable (right hand side of the popover item)

### Expected Behavior
Only the <td/> parts of the table should be clickable

### Severity
low

**Comment by nitayneeman** [comment]
In case of a **clickable** row, all parts of the row are supposed to be styled with `cursor: pointer` when hovering it. It means that the whole area of the row is considered as clickable regardless of its actual rendered content.

This is the behavior according to the design system spec (verified with @LittleTal).
In case you still think differently, please reopen and provide more information (what's the reason?).

Closing.
