### ISSUE TITLE
BadgeSelect below another BadgeSelect

### ISSUE THREAD

**Issue by assafganor** [wix/wix-style-react#2474]
# Bug Report

### Relevant Components
BadgeSelect

### Current Behavior
There is an issue with the z-index positioning when a BadgeSelect is clicked and opened over another BadgeSelect .
The bottom BadgeSelect is visible on top the first BadgeSelect dropdown.

![screen shot 2018-11-14 at 17 50 32](https://user-images.githubusercontent.com/9839921/48537559-9a97c980-e8ba-11e8-89b2-f59c1ee18e90.png)

### Expected Behavior
BadgeSelect dropdown will be completely visible over other components

### Steps to Reproduce
https://codesandbox.io/s/1o7qw8yy5j

### Severity
Major

**Comment by yardnsm** [comment]
Resolved in #2478, should be available in next release.
