### ISSUE TITLE
Add component ButtonWhite

### ISSUE THREAD

**Issue by vidmantas0010** [wix/wix-style-react#248]

**Comment by mastertheblaster** [comment]
https://wix.github.io/wix-style-react/?selectedKind=3.%20Buttons&selectedStory=3.1%20Standard&full=0&down=0&left=1&panelRight=0

perhaps emptybluesecondary will fit your needs ?

**Comment by vidmantas0010** [comment]
@mastertheblaster I'am on Guild Week and got a task to add 8 types of buttons
