### ISSUE TITLE
Reduce build time - Remove redundant e2e snapshots

### ISSUE THREAD

**Issue by hepiyellow** [wix/wix-style-react#2488]
We should go over all e2e tests, and remove redundant snapshots.
Usually redundant snapshots can be found with tests that don't use the autoExampleDriver,
they use `eyes` and `browser.get` in each test.
`eyes` takes by default 2 snapshots, one at `browser.get` and one at the end.
We are now able to configure eyes to NOT take a snapshot at `browser.get`.
```js
eyes.it('should run tests with eyes', async () => {
}, {enableSnapshotAtBrowserGet: false});
```

Here is a checklist of all e2e tests:

- [ ] AddItem.e2e.js
- [ ] AutoComplete.e2e.js
- [ ] Avatar.e2e.js
- [ ] BadgeSelect.e2e.js
- [ ] Breadcrumbs.e2e.js
- [ ] Button.e2e.js
- [ ] Button.e2e.js
- [ ] Calendar.e2e.js
- [ ] Card.e2e.js
- [ ] Checkbox.e2e.js
- [ ] DataTable.e2e.js
- [ ] DatePicker.e2e.js
- [ ] DrillView.e2e.js
- [ ] Dropdown.e2e.js
- [ ] EditableSelector.e2e.js
- [ ] EmptyState.e2e.js
- [ ] FieldWithSelectionComposite.e2e.js
- [ ] FilePicker.e2e.js
- [ ] FormField.e2e.js
- [ ] GenericModalLayout.e2e.js
- [ ] Heading.e2e.js
- [ ] Highlighter.e2e.js
- [ ] IconWithOptions.e2e.js
- [ ] Icons.e2e.js
- [ ] ImageViewer.e2e.js
- [ ] Input.e2e.js
- [ ] InputArea.e2e.js
- [ ] Layout.e2e.js
- [ ] Loader.e2e.js
- [ ] MessageBox.e2e.js
- [ ] ModalSelectorLayout.e2e.js
- [ ] MultiSelect.e2e.js
- [ ] MultiSelectCheckbox.e2e.js
- [ ] Page.e2e.js
- [ ] PageHeader.e2e.js
- [ ] PopoverMenu.e2e.js
- [ ] RadioGroup.e2e.js
- [ ] Range.e2e.js
- [ ] RichTextArea.e2e.js
- [ ] Search.e2e.js
- [ ] SectionHelper.e2e.js
- [ ] Slider.e2e.js
- [ ] StatsWidget.e2e.js
- [ ] Table.e2e.js
- [ ] TableActionCell.e2e.js
- [ ] Tabs.e2e.js
- [ ] Tag.e2e.js
- [ ] Text.e2e.js
- [ ] TextButton.e2e.js
- [ ] TextLink.e2e.js
- [ ] Tooltip.e2e.js
- [ ] Typography.e2e.js

List obtained by:
```
cd src
find . | grep e2e | awk '{n=split($0,a,"/"); print a[n]}' | sort
```

**Comment by shlomitc** [comment]
initial work was done here (A->C)
https://github.com/wix/wix-style-react/pull/2587

**Comment by shlomitc** [comment]
will not keep working on this issue, as we decided to migrate tests to `eyes-storybook`
