### ISSUE TITLE
Omit 3rd party dependency 

### ISSUE THREAD

**Issue by giladsegal** [wix/wix-style-react#2489]
# Bug Report

### Relevant Components
`<InputWithOptions />`

### Current Behavior
Input props are calculated using 3rd party library called `omit`
The omitted prop keys are taken from `DropdownLayout.propTypes`
Production code might strip `PropType` and anyway production code shouldn't rely on `PropTypes`
Also, this is the only usage of this 3rd party so I think we can remove it

### Expected Behavior
Props calculation doesn't rely over `PropTypes`

### Severity
Low

**Comment by shlomitc** [comment]
won't be fixed
