### ISSUE TITLE
Feature Request - Extract Table selection state outside and pass it via props

### ISSUE THREAD

**Issue by Jefoss** [wix/wix-style-react#2496]
### Relevant Components
Table

### Current Behavior
The selection state is handled internally, and there are some functions on the selectionContext object to manually change selection, and using that currently feels hacky

### Wanted Behavior
pass selection state via props, and let the user of the `Table` handle the selection, or at least give the user the option to do so

**Comment by hepiyellow** [comment]
You can re-render with different selectedIds and the table will update
accordingly.

**Comment by hepiyellow** [comment]
May i know the use-case?

**Comment by hepiyellow** [comment]
@Jefoss Can I close this issue?

**Comment by shlomitc** [comment]
@Jefoss - ping?
