### ISSUE TITLE
GenericModalLayout

### ISSUE THREAD

**Issue by adavidof** [wix/wix-style-react#2497]
### Relevant Components
GenericModalLayout

### Current Behavior
Bug with name in storybook

### Expected Behavior
Correct name: `GenericModalLayout`

### Steps to Reproduce
https://wix-wix-style-react.surge.sh/?selectedKind=Components&selectedStory=GenericModalLayout&full=0&addons=0&stories=1&panelRight=0
![image](https://user-images.githubusercontent.com/10529679/49011915-7375ad80-f180-11e8-8b75-fc128e609757.png)

### Severity
Low

**Comment by shlomitc** [comment]
Thanks. Can you please add a displayName to the component?

**Comment by adavidof** [comment]
@shlomitc 
already added
https://github.com/wix/wix-style-react/blob/master/src/GenericModalLayout/GenericModalLayout.js#L52

**Comment by shlomitc** [comment]
merged
