### ISSUE TITLE
Problems with AutoCompleteInput

### ISSUE THREAD

**Issue by lbelinsk** [wix/wix-style-react#25]
1.  The AutoComplet litterly doesn't auto complete... it suggests all the options without any dependency in the inserted text.

2.  If I wrap the autoComplete component with **div** which has css attribute off flex display, the width of the component just becomes real tiny, even if I specifically try to set the width manually.

**Comment by 3LOK** [comment]
1. Perhaps the name of the component is misleading. The name could be "SuggestedInput" or something like that.

2. Fixed.

**Comment by lbelinsk** [comment]
The second issue is not fixed. Here is an example:

<img width="840" alt="screen shot 2016-12-10 at 9 47 39 pm" src="https://cloud.githubusercontent.com/assets/18248989/21075746/57603e7c-bf22-11e6-86cd-3b7b8f0d25f4.png">

If the css className "simpleFlex" remains empty, then the width of the Input component will be 100%.

Now if we add changes to the css className:

.simple-flex {
  display: flex;
}

then a tiny Input component will be rendered..

<img width="1434" alt="screen shot 2016-12-10 at 9 49 20 pm" src="https://cloud.githubusercontent.com/assets/18248989/21075768/dc622176-bf22-11e6-9e46-ac1011585277.png">

**Comment by 3LOK** [comment]
Ah, issue was addressed to 'AutoCompleteInput', not 'Input'.

Fixed for Input as well.
