### ISSUE TITLE
`<MultiSelect/>` (Tags) - background is transparent

### ISSUE THREAD

**Issue by hepiyellow** [wix/wix-style-react#2502]
Did you notice that `MultiSelect` is transparent?
As opposed to all inputs `<Input/>` , `<InputArea/>` which are white.

See [this PR](https://wix-wix-style-react-pr-2356.surge.sh/?selectedKind=3.%20Inputs&selectedStory=3.8%20Tags&full=0&addons=0&stories=1&panelRight=0) which converts the MultiSelect story to AutoStory.
In the playground it is obvious now that it is transparent.

This is a bug right?
@shlomitc

**Comment by shlomitc** [comment]
@milkyfruit - wdyt?

**Comment by milkyfruit** [comment]
@shlomitc It's a bug. The background should be white as in `<input />`.

**Comment by shlomitc** [comment]
I’ll add it to our backlog

**Comment by shlomitc** [comment]
done
