### ISSUE TITLE
`<InputWithOptions/>` - make `valueParser` usage more clear

### ISSUE THREAD

**Issue by hepiyellow** [wix/wix-style-react#2503]
## The issue

It is not clear from the docs what `valueParser` does?
The [docs](https://wix-wix-style-react.surge.sh/?selectedKind=Components&selectedStory=Dropdown&full=0&addons=0&stories=1&panelRight=0) say:
>Function that receives an option, and should return the value to be displayed. By default returns option.value

Does that mean the value to be displayed in the Dropdown options? or the value to be displayed in the dropdown input box?

Personally, I always thought its the value displayed i the dropdown options.

But, it seems by implementation:
- `<InputWithOptions/>` does absolutely nothing with `valueParser`
- `<Dropdown/>` - Uses `valueParser` only to set it's internal `value` state and use the `value` state as the `<Input/>`'s value.

## what to do now?
- Document it well
- Remove `valueParser` from `<InputWithOptions/>`'s propTypes.

**Comment by shlomitc** [comment]
1. It's related to the selected option in an input box. The reason - when you have a complex item in the list (icon/checkbox for example), you need to parse its text from it to display in an input.

2. It's probably better to have it only on the components that actually use it (`Dropdown`, `MultiSelectCheckbox`, `MultiSelect`)

**Comment by shlomitc** [comment]
or another option - implement it inside the `InputWithOptions` and make all other related components to use it.

faster solution is the first one probably

**Comment by shlomitc** [comment]
This issue discusses some possible solutions for not using `valueParser` https://github.com/wix/wix-style-react/issues/2504

**Comment by shlomitc** [comment]
won't be fixed any time soon - will reopen on request
