### ISSUE TITLE
Classnames usage

### ISSUE THREAD

**Issue by mastertheblaster** [wix/wix-style-react#251]
Seems like if a project is including own `classnames` package, it's beeing bundled twice.
Cause we use `wix-style-react` as 

```js
import { Button } from 'wix-style-react';
```

Perhaps we should move to:

```js
import Button from 'wix-style-react/button';
```

**Comment by mastertheblaster** [comment]
@nirhart Have you experienced this issue ?

**Comment by nirhart** [comment]
You are right, we should import from a specific path and not from 'wix-style-react'
