### ISSUE TITLE
<Page.Header /> has pointer cursor on hover when minimized

### ISSUE THREAD

**Issue by Jefoss** [wix/wix-style-react#2512]
### Relevant Components
Page, Page.Header

### Current Behavior
when the page is minimized, the header is actually rendered as a breadcrumb with 1 item, and has a pointer cursor on hover, as if its clickable when its not necessarily clickable

### Expected Behavior
the minimized header should not have a pointer cursor on hover, at least not by default

### Steps to Reproduce
have a page with enough content to scroll, and hover over the minimized header after scrolling a bit

### Severity
Low

**Comment by shlomitc** [comment]
Can you please provide a reproducable example?
I tried it on my side with this example and it looks fine

```js
<div
  style={{
    height: '300px',
    display: 'flex',
    flexFlow: 'column',
  }}
>
  <Page>
    <Page.Header subtitle="Page subtitle" title="Page Title" />
    <Page.Content>
      <h1>asd</h1>
      <h1>asd</h1>
      <h1>asd</h1>
      <h1>asd</h1>
      <h1>asd</h1>
      <h1>asd</h1>
      <h1>asd</h1>
      <h1>asd</h1>
      <h1>asd</h1>
      <h1>asd</h1>
      <h1>asd</h1>
    </Page.Content>
  </Page>
</div>
```

**Comment by Jefoss** [comment]
Seems to be a css leak from another place, closed
