### ISSUE TITLE
<Accordion /> - Missing module

### ISSUE THREAD

**Issue by rghorbani** [wix/wix-style-react#2522]
Hi,
I wanted to ask do you have any plan to add an `Accordion`?

**Comment by argshook** [comment]
Hello!

we have [`<Collapse/>`](https://wix-wix-style-react.surge.sh/?selectedKind=Components&selectedStory=Collapse) with which you can build accordions, but we don't have premade `<Accordion/>`.

i think with Collapse it's trivial enough to create accordion without a
dedicated component. but maybe you have in mind some specific use case or logic that's worth abstracting?

**Comment by wuwa** [comment]
not at the moment, I don't know of any requests

**Comment by rghorbani** [comment]
@shlomitc, @wuwa Can I make such a request?

**Comment by shlomitc** [comment]
@rghorbani - the requests are coming usually from the design system of Wix, so it can go to our UX backlog, but I don't think it will be prioritized until we see actual use case in our products

**Comment by shlomitc** [comment]
This component will soon be added to the library, stay tuned
![image](https://user-images.githubusercontent.com/6093192/52227518-68de3f80-28b8-11e9-8ba4-d7db5def7bd1.png)

**Comment by shlomitc** [comment]
release in v6.12.0, go check it out!
https://wix-wix-style-react.surge.sh/?selectedKind=Components&selectedStory=Accordion&full=0&addons=0&stories=1&panelRight=0

**Comment by rghorbani** [comment]
@shlomitc Thanks
