### ISSUE TITLE
`<Avatar/>` - Minor Open Issues

### ISSUE THREAD

**Issue by hepiyellow** [wix/wix-style-react#2526]
this is a list of leftover minor (open) issues with the new `<Avatar/>` component.

### Focusable / Clickable

Should we make Avatar optionally focusable (and use FocusableHOC to make is a11y compatible)?

### Default Styling for custom Placeholder
- should we add border-radius 50%? I think yes
- should we add size (height,width : inherit)?
  not sure.

If we want to provide size as default.
if we do it by css, then the consumer can not override it.

- We may do it in JS, by checking if the icon has width, height, and if not, then we add them.
- Other solution is to have `icon` as a render prop that receives the size. e.g. `(size)=> React.ReactElement`

### Delete image

`wix-ui-core`: Remove TODO comments from avatar.tsx about deleting img.
Make sure its the proper thing to do.

### Tests
wix-ui-core: unskip tests which are disabled due to not working with jsdom (browser only).

Once jsdom is out, and tests are unskipped, we can remove the e2e test.

**Comment by shlomitc** [comment]
Sounds to me like possible feature requests and not actual requirements which are not yet met in the component.
Let's see if any issues arise and open separate issues for that
