### ISSUE TITLE
<Search /> doesn't handle element options

### ISSUE THREAD

**Issue by sthuck** [wix/wix-style-react#2532]
# Bug Report

### Relevant Components
`<Search>`

### Current Behavior
When passing elements to search `<Search options={{id: '1', value: <div>111</div>}}/>`, the component is broken. 
the component tries to run a regex over the element (which I guess has toString() of '[object Object]' or something.) 
https://github.com/wix/wix-style-react/blob/master/src/Search/Search.js#L51

### Expected Behavior
Fix the behavior, so that elements could be passed.
Either don't filter for controlled components, or or some other magic I can't think of 😄 

if not/at the meanwhile, fixing the documentation will be appreciated:
https://wix-wix-style-react.surge.sh/?selectedKind=3.%20Inputs&selectedStory=3.9%20Search&full=0&addons=0&stories=1&panelRight=0

### Steps to Reproduce
https://codesandbox.io/s/mo9q3wonrj

### Severity
Low

**Comment by shlomitc** [comment]
Fix was merged, will be released in next version (6.5.0)
