### ISSUE TITLE
`<PopoverMenu/>` - Remove `setTimeout(0)` when opening the popover

### ISSUE THREAD

**Issue by hepiyellow** [wix/wix-style-react#2537]
Reported by @iaroslavshvets 

He asked why do we have to o an async wait for PopoverMenu to be open after clicking it.

Looking at the PopoverMenu code , we render Tooltip with :
```js
<Tooltip
  ...
  showDelay={0}
  hideDelay={0}
.../>
```

In Tooltip's `show function, we set a timeout:
```js
const delay = this.props.showImmediately ? 0 : props.showDelay;
setTimeout(() => {
...
}, delay);
```

In real browser, this doesn't really make a difference.
But in tests, this forces the consumers to do an async wait.

### Solution
Change Tooltip, so that if delay is `0`, the we won't call `setTimeout` at all.

**Comment by hepiyellow** [comment]
@shlomitc What do you think?

**Comment by shlomitc** [comment]
won't be fixed
