### ISSUE TITLE
Unexpected datahook behaviour

### ISSUE THREAD

**Issue by yakirn** [wix/wix-style-react#2538]
# Bug Report

### Relevant Components
Any component that inherits from `WixComponent` (e.g Button)

### Current Behavior
given the following app (assume trivial implementation of state and `toggleFoo`):
```
<div>
        <div>
          <Button dataHook="action" onClick={this.toggleFoo}>
            <span>Action</span>
          </Button>
        </div>
        <div>
          {this.state.isFoo ? (
            <Button dataHook="foo">Foo</Button>
          ) : (
            <Button dataHook="bar">Bar</Button>
          )}
        </div>
</div>
```
first render:
```
<div>
...
  <div>
    <button data-hook="foo">Foo</button>
  </div>
</div>
```
second render (after `toggleFoo`):
```
<div>
...
  <div>
    <button data-hook="foo">Bar</button>
  </div>
</div>
```
data-hook was not updated on the button's html.

### Expected Behavior

data-hook should update on the button's html:

second render (after `toggleFoo`):
```
<div>
...
  <div>
    <button data-hook="bar">Bar</button>
  </div>
</div>
```

### Steps to Reproduce

https://codesandbox.io/s/ov91jxjjr6

### Severity
This is very confusing, especially in tests as code will work as expected (As long as you don't rely on data-hook for your implementation) but a test that will check that barButton is now visible by the presence of data hook will fail.

**Comment by yakirn** [comment]
As seen in the code sandbox, it is possible to overcome the issue by giving each component a different key prop. This will force react to remount the component, calling `componentWillMount` again which triggers setting the data-hook prop.

But the real problem is that setting data hook this way is bad practice and error prone.

As a temporary fix I think we should sync data-hook across all of the component's lifecycle methods. I can submit a PR for this.

A proper fix IMO will be to stop using component inheritance and render data-hook in each component manually or think of a more sophisticated solution.

**Comment by hepiyellow** [comment]
@yakirn 
If you decide to refactor all components,
please show in the PR first a comment with how you want each component to apply the dataHook (before you start a big refactor). 
So we are on the same line...

**Comment by hepiyellow** [comment]
Some components still don't support dataHook update.
Look at this [smoke test](https://github.com/wix/wix-style-react/blob/0a76689f6fca8a0402719136528ba6c066e90356/testkit/testkit-smoke.test.js#L245) (sanity), if we enable it we will see  which components don't support it.

These are components that use wix-ui-core components, that in turn use `createHOC` which is like WixComponent, and it doesn't implement `componentDidUpdate`.

**Comment by shlomitc** [comment]
So an additional (similar) fix is required here:
https://github.com/wix/wix-ui/blob/master/packages/wix-ui-core/src/createHOC/index.tsx

**Comment by yakirn** [comment]
@shlomitc @hepiyellow I'll submit a PR to wix-ui today. I noticed there are component that override `componentDidUpdate` like [Page](https://github.com/wix/wix-style-react/blob/master/src/Page/Page.js#L80-L85).
For those components to work as expected we need to:
```
componentDidUpdate() {
    super.componentDidUpdate();
    // Do not trigger height calculation if the component is minimized
    if (!this.state.minimized) {
      this._calculateComponentsHeights();
    }
  }
```
Right?

**Comment by hepiyellow** [comment]
@yakirn You mean PR to wix-style-react..?

**Comment by yakirn** [comment]
@hepiyellow I submited [this PR](https://github.com/wix/wix-ui/pull/1038) to wix-ui, but this is not enough. Another PR to WSR is needed in order for your tests to pass (Search for every `componentDidUpdate` and if the component inherits from WixComponent add `super.componentDidUpdate()`
