### ISSUE TITLE
`<Table/>` - Add support for expanded row details (New Styling)

### ISSUE THREAD

**Issue by hepiyellow** [wix/wix-style-react#2539]
@wuwa @milkyfruit @LittleTal 

## Features

- [ ] expand column
  - [ ] show button on hover
- [ ] `<RowDetailsContent/>` - New component for Consumers to use
- [ ] Custom bg color - white / blue
- [ ] Custom Less button priority (primary / secondary)

### Styling Changes

- [ ] Remove horizontal divider between row and rowDetails

## Dev questions

- Is DataTable in use ONLY through Table? 
  - Can we change styling, and behaviour (click to collapse row)

## UX Questions

- Ask UX if there is a case with Actions & Expand Row button
- Are you sure? Closing is done ONLY by "Less" button.
  -  click on "expand-column"?
  -  Keep Less button in original place?
- Is multiple row expanding allowed? Is there a single-expand-only mode? (expanding one row closes others)

### Less Button

Assuming that we supply a Footer, that renders the "Less" button (The consumer has no control over it).

In this example, how would the consumer align the "Go To Editor" buttons with content above it.
![screen shot 2018-12-05 at 14 58 39](https://user-images.githubusercontent.com/6338722/49514983-4c189200-f89e-11e8-91f9-84acca62f8b5.png)

- Missing footer constraints (left padding)

### Solution 1

Less button column

### Solution 2

Keep Less button in Row.

**Comment by hepiyellow** [comment]
## API suggestion

```js
<Table
  rowDetails: ({row, rowNumber})=> (
    <RowDetailsContnet 
      verticalDivider={true}
      >
      Hello {rowNumber}
      <RowDetailsFooter 
        lessButtonPriority='secondary'
        collapseRowDetails={collapseRowDetails}
      />
    </RowDetailsContnet>
  )
>

```

**Comment by hepiyellow** [comment]
@wuwa @milkyfruit @LittleTal Can you relate to the UX questions and the UX Issue ?

**Comment by milkyfruit** [comment]
@hepiyellow 
I got a request that dev center team needs this feature.
@noafin is in the team.

**Comment by hepiyellow** [comment]
@noafin Noa told me last tuesday that she can not work on it now, maybe in the future.

@shlomitc Do we have a budget for this?
@milkyfruit how urgent?

**Comment by shlomitc** [comment]
Currently not, they can keep working on it whenever they will have time.
If more teams will request this feature we will consider taking it

**Comment by gugu-lee** [comment]
my table props:
 
showHeaderWhenEmpty={true}
        allowMultiDetailsExpansion={true}
        newDesign={true}
        rowDetails={({ row, rowNumber }) => (
          <RowDetailsContnet verticalDivider={true}>
            Hello {rowNumber}
            <RowDetailsFooter lessButtonPriority="secondary">
              <Button priority="primary">Go toEditor</Button>
            </RowDetailsFooter>
          </RowDetailsContnet>
        )}

but not show the detail ,and when i click the row in table ,the react is error.

**Comment by shlomitc** [comment]
Introducing the `Accordion` component
https://wix-wix-style-react.surge.sh/?selectedKind=Components&selectedStory=Accordion&full=0&addons=0&stories=1&panelRight=0

Closing
