### ISSUE TITLE
Feature Request - <Text /> multiline ellipsis

### ISSUE THREAD

**Issue by assafganor** [wix/wix-style-react#2540]
multiline ellipsis text with tooltip.
Like the current Text with ellipsis, but multiline.
![screen shot 2018-12-05 at 17 23 40](https://user-images.githubusercontent.com/9839921/49523727-03b79f00-f8b3-11e8-862e-1ca1fe6bbd8b.png)

**Comment by hepiyellow** [comment]
@shlomitc I think this was also a requirement for the `<Page/>` subtitle.
Can we have it as a separate task?

**Comment by shlomitc** [comment]
will add to backlog

**Comment by shlomitc** [comment]
we decided not to have one in our library. if the decision will be changed in the future I'll reopen
