### ISSUE TITLE
<Table/> - Add support for column class

### ISSUE THREAD

**Issue by assafganor** [wix/wix-style-react#2547]
I need a responsive <Table />, different column width in different screen width.
I want to add class to each column in order to use media queries.
Maybe adding "colClass" to columns prop object.

**Comment by hepiyellow** [comment]
@wuwa Can you verify with @assafganor the exact use-case they need to solve, and let us know if it is something we should support in WSR or not?

@assafganor Can you share your UX spec for the responsive Table?

**Comment by assafganor** [comment]
UX spec:
https://zpl.io/aw1l6Dd
https://zpl.io/bz1L74z
https://zpl.io/aBNn77e

**Comment by wuwa** [comment]
i think your case can be closely achieved with setting column widths in percentage, no need for breakpoints -> 3-2-2-2-3 column span

**Comment by hepiyellow** [comment]
@assafganor Can we close this issue?

**Comment by assafganor** [comment]
@wuwa  I have one column (Status) in same width on all screens. But as you said percentage will be close enough.

@hepiyellow Can I use `calc()` in `width` property in each `column`?

**Comment by assafganor** [comment]
@hepiyellow  Thanks, `calc()` works in inline styles.
I don't use `hideHEader` so it should works.
