### ISSUE TITLE
TypeError: Object doesn't support property or method 'default'

### ISSUE THREAD

**Issue by gugu-lee** [wix/wix-style-react#2554]
# TypeError: Object doesn't support property or method 'default'

### 
I try to use the wix style,i use the Label,Text but ,the page is not view correctly,
the page view 

**TypeError: Object doesn't support property or method 'default'
exports.Label
D:/github/provider-reg/code/webapp/node_modules/wix-ui-core/dist/src/components/deprecated/Label/Label.js:25
  22 |     children = props.children,
  23 |     ellipsis = props.ellipsis,
  24 |     disabled = props.disabled;
> 25 | return React.createElement("label", tslib_1.__assign({}, Label_st_css_1.default('root', {
     | ^
  26 |   ellipsis: ellipsis,
  27 |   disabled: disabled
  28 | }, props), {**

my code is:

_import React ,{ Component } from 'react';
import Button from 'wix-style-react/Button';

import Text from 'wix-style-react/Text';
import Label from 'wix-style-react/Label';
class App extends Component {
	render() {
    return (
      <div className="shopping-list">
        <Label size="medium">Shopping List for {this.props.name}</Label>
        >
      </div>
    );
  }
    
};
export default App;_

###Critical

**Comment by hepiyellow** [comment]
1. Well, seeing this `Label_st_css_1.default` seems like you might not have the Stylable loader configured properly.
See [this documentation](https://github.com/wix/wix-style-react/blob/master/docs/usage-without-yoshi.md) page for help regarding that.

1. In any way, can you specify the wix-style-react version you are using?

1. And seeing that `D:/github/provider-reg/code/webapp/node_modules/wix-ui-core/dist/src/components/deprecated/Label/Label.js:25` , I assume you are working on Windows. We would be glad to hear your feedback on how wix-style-react is working on windows, we do have some concern about non-case-sensitive file systems.
1. Is this the first time you are trying to make wix-style-react work? or it worked before and now it is broken? (if so, what version were you using before?

**Comment by gugu-lee** [comment]
thank you very much ,
i first use wix, my version is 5.15.1.
i try to work by your advise.
thank you again.

**Comment by gugu-lee** [comment]
hi：
now i use "npx create-yoshi-app my-app" to create project .
but 
**npm ERR! code ETIMEDOUT
npm ERR! errno ETIMEDOUT
npm ERR! network request to http://npm.dev.wixpress.com/create-yoshi-app failed, reason: connect ETIMEDOUT 10.42.123.179:80
npm ERR! network This is a problem related to network connectivity.**

soso .

**Comment by hepiyellow** [comment]
`npx create-yoshi-app my-app` is currently not available for non Wix employees.

The [documentation page](https://github.com/wix/wix-style-react/blob/master/docs/usage-without-yoshi.md) I sent you is about working without Yoshi.

**Comment by gugu-lee** [comment]
thank you,
i use the yoshi templete for my project directly,
