### ISSUE TITLE
Improve Autocomplete docs (specific protractor testkit)

### ISSUE THREAD

**Issue by moshfeu** [wix/wix-style-react#2570]
Current docs just says: `Autocomplete testkit is identical to InputWithOptions test kit`.
In `InputWithOptions` [docs](https://wix-wix-style-react.surge.sh/?selectedKind=4.%20Selection&selectedStory=4.1%20%2B%20InputWithOptions&full=0&addons=0&stories=1&panelRight=0) there is no mention about protractor testkit.

Having saying this, actually, there is Independent [protractor testkit](https://github.com/wix/wix-style-react/blob/master/testkit/protractor.js#L93) for AutoComplete.

### Severity

Low

**Comment by shlomitc** [comment]
This was fixed lately and now displaying the `protractor` testkit docs.
https://wix-wix-style-react.surge.sh/?activeTab=Testkit&addons=0&full=0&panelRight=0&selectedKind=Components&selectedStory=AutoComplete&stories=1

However, it should ideally show also the regular driver definitions and not just point to the `InputWithOptions` docs.
@argshook - can you please check why the driver api is not shown correctly?
@mykas CC

**Comment by shlomitc** [comment]
done
