### ISSUE TITLE
TableActionCell is undefined

### ISSUE THREAD

**Issue by gugu-lee** [wix/wix-style-react#2575]
# TableActionCell is undefined

### Relevant Components

wix-style-react/Table
wix-style-react/TableActionCell

### Current Behavior

i use the wix-style-react/Table and all of its ok ,
but  the console output the error 

**react.js:3580 Warning: Failed prop type: The prop `primaryAction.onClick` is marked as required in `TableActionCell`, but its value is `undefined`.**

and the primary button is not display.

### Severity

Major

**Comment by hepiyellow** [comment]
As the warning says, the `primaryAction` prop must be an object with an `onClick` property.
