### ISSUE TITLE
Heart Icon is not displayed properly

### ISSUE THREAD

**Issue by ZilvinasMaciulis** [wix/wix-style-react#2576]
Heart icon in Foundation

Two upper points of inner shape are slightly off causing the right upper edge to appear thinner than the left one.

Icon should maintain 1px stroke

![image](https://user-images.githubusercontent.com/44393332/49925217-f016c480-fec0-11e8-9a3d-39bcc4793dbd.png)

**Comment by shlomitc** [comment]
@ZilvinasMaciulis - all our icons are SVGs.
we do some optimizations on them, but not such that should do any damage to their structure.

Are you sure the SVG is correct?
https://github.com/wix/wix-ui/blob/master/packages/wix-ui-icons-common/src/general/raw/Heart.svg

**Comment by ZilvinasMaciulis** [comment]
Yes, pretty sure :)

**Comment by alisey** [comment]
We use [wix/svg2react-icon](https://github.com/wix/svg2react-icon) to convert SVGs to React components. This tool uses [SVGO](https://github.com/svg/svgo) to optimize SVGs, and one of the options is path simplifications, which is enabled by default.

To disable it we need to add `{convertPathData: false}` here:
https://github.com/wix/svg2react-icon/blob/master/src/lib/svg-optimizer.js
