### ISSUE TITLE
`<Tooltip/>` - Does not support SFC as children

### ISSUE THREAD

**Issue by hepiyellow** [wix/wix-style-react#2582]
## Cause
This is because we try to take a `ref` of the child
https://github.com/wix/wix-style-react/blob/0a76689f6fca8a0402719136528ba6c066e90356/src/Tooltip/Tooltip.js#L333

## Solution
We could instead do :
```js
componentDidMount() {
    super.componentDidMount && super.componentDidMount();
    this._childeNode = ReactDOM.findDOMNode(this);
    this._setContentDataHook();
  }

  componentDidUpdate(prevProps) {
    this.childeNode = ReactDOM.findDOMNode(this);
    if (prevProps.dataHook !== this.props.dataHook) {
      this.contentHook = this._createContentHook();
      this._setContentDataHook();
    }
    this.renderTooltipIntoContainer();
  }

```

**Comment by mykas** [comment]
Fixed. https://wix-wix-style-react.surge.sh/?selectedKind=7.%20Tooltip&selectedStory=7.1%20Tooltip&full=0&addons=0&stories=1&panelRight=0
