### ISSUE TITLE
inputAreaTestkitFactory protractor testkit for InputArea

### ISSUE THREAD

**Issue by adavidof** [wix/wix-style-react#2583]
# Bug Report
no `enterText` method to enter text to input area in protractor testkit

### Relevant Components
`InputArea`
`wix-style-react/InputArea`

### Current Behavior
`inputAreaTestkitFactory({ dataHook: 'ssh-keys-form-key-field' }).enterText(name);`
`enterText` is not a function

### Expected Behavior
`inputAreaTestkitFactory({ dataHook: 'input-area-element' }).enterText('foo');`
`foo` entered to input area element with data-hook `input-area-element`

### Severity

Major

**Comment by shlomitc** [comment]
will be added in this PR soon (sendKeys)
https://github.com/wix/wix-style-react/pull/2557

**Comment by shlomitc** [comment]
done and released
