### ISSUE TITLE
<CloseButton /> icon is not vertically centered in FF

### ISSUE THREAD

**Issue by kelyar** [wix/wix-style-react#2605]
# Bug Report

### Relevant Components
MessageBoxFunctionalLayout

### Current Behavior
MessageBoxFunctionalLayout.Title contains CloseButton
since 5.16.0 X icon is not vertically centered in FF (v64, macos)
works fine in chrome

![X is misplaced](https://i.imgur.com/XnkZuXb.png)

### Severity
Major

**Comment by mykas** [comment]
Working on this right now.

**Comment by mykas** [comment]
Fixed
