### ISSUE TITLE
Warning: Accessing PropTypes via the main React package is deprecated

### ISSUE THREAD

**Issue by hepiyellow** [wix/wix-style-react#2607]
We are getting this warning a lot in the build log:
>Warning: Accessing PropTypes via the main React package is deprecated, and will be removed in  React v16.0. Use the latest available v15.* prop-types package from npm instead. For info on usage, compatibility, migration and more, see https://fb.me/prop-types-docs

I searched in WSR code for:
- React.PropTypes
- import.*PropType.*from.*react

And I couldn't find any relevant matches.

Anyone has an idea how to avoid those warning?

[Example Build log](https://tc.dev.wixpress.com/viewLog.html?buildId=75574866&buildTypeId=CommonComponent_WixStyleReact&tab=buildLog&_focus=2117#_state=784,1471)

**Comment by shlomitc** [comment]
@yardnsm - did you have any findings regarding this?

**Comment by shlomitc** [comment]
won't be fixed any time soon - will reopen on request
