### ISSUE TITLE
Automation Tests `data-hook` API

### ISSUE THREAD

**Issue by hepiyellow** [wix/wix-style-react#2610]
## Our internal `data-hook`-s are actually an external API that we should not change !

The Automation team looks at the resulting DOM of production sites, and decides which hooks to use.

In recent change we made, I removed the internal `tooltip-content` dataHook, and put it on another DOM element and even changed its name.
I seems that Automation tests used it to click on PopoverMenu items. (I guess they clicked on it's children).

It seems like they need to be using WSR drivers !

## Selenium

It might be that Automation team is using Selenium WebDriver directly (not through protractor).
So our protractor drivers won't be suitable.

## Solution

Maybe UniDriver can help ?
We could have a Selenium WebDriver version derived from the UniDriver.

**Comment by shlomitc** [comment]
data-hooks were never intended to be used directly, so I do not consider it as an external API.
We can have a short discussion with them, but frankly, I think it's ok that they have their own drivers which they maintain from time to time.
When unidriver will be widely used, maybe we can think of having another adapter.
Anyway, they might be even using JAVA and not Javascript, so I don't know if it will be of any help.

closing.

**Comment by hepiyellow** [comment]
They are using java.

**And they are also freely using any `data-hook` attribute, and considering it as "API" which is less likely to break then class names**

>I was talking to Sapi Chodorov from Restaurants QA. 

If we want our internal data hooks we should use a different attribute name, like `data-wsr-hook`, and instruct the Automation team, to avoid using it.
Refactoring our internal hooks to the new name may break many Automation tests.

I will talk to George Leviatov from QA guilde about this.

**Comment by argshook** [comment]
> They are using java.
> And they are also freely using any data-hook attribute, and considering it as "API" 

they can use anything and consider it as API, but that does not mean we should consider it as API.

what if one day someone uses our HTML hierarchy as API, will that mean we can no longer change it?

or what if we introduce `data-wsr-hook` and someone uses that as API?

i don't think it's a problem on our side
