### ISSUE TITLE
React16 - `<Modal/>` - `driver.isOpen()` doesn't really tell if modal is open

### ISSUE THREAD

**Issue by hepiyellow** [wix/wix-style-react#2612]
When calling Modal `driver.isOpen()` it checks for:
```js
!!document.body.querySelector('.ReactModal__Content')
```

After unmounting , with React 16 , the `isOpen()` can return false, while this is still true:
```js
!!document.body.querySelector('.portal')
```

This causes an issue with multiple tests, not cleaning correctly after each other.

**Comment by hepiyellow** [comment]
I saw that when `<Modal/>` is unmounted.
The `.ReactModal__Content` class dissappears immediately,
but the `.portal` class exists for the duration of the `closeTimeoutMS`.

**Comment by shlomitc** [comment]
so what is the suggested solution?
is this a blocker regarding migrating to React16? is there a workaround or a better solution?

**Comment by amitdahan** [comment]
Our issue was that our tests were not cleaning the modal properly from the dom before finishing.
We added a call to this function to our `afterEach` (*after* unmounting our component) and it seems to work now:

```
export async function cleanModalLeftovers() {
  if (document.querySelector('.portal')) {
    await eventually(() => {
      if (document.querySelector('.portal')) {
        throw new Error('Portal still exists!');
      }
    });
  }
}
```

**Comment by shlomitc** [comment]
so `isOpen` should the testkit implementation change to query for the `.portal` instead?

**Comment by hepiyellow** [comment]
## Solution

Instruct consumer to do cleanup (after unmounting) using `driver.exists()` instead of `driver.isOpen()`:
```
await eventually(() => expect(modalDriver.exists()).toBeFalsy()));
```

This works for React 15 and 16.
