### ISSUE TITLE
Cards with <Collapse/> component

### ISSUE THREAD

**Issue by LittleTal** [wix/wix-style-react#2614]
### Relevant Components
Cards with `<Collapse/>` 

### Current Behavior
When the card collapses the divider disappears before the end of the animation.
It also causes the content to move 1px up.

### Expected Behavior
Add fade out / reduce opacity animation to the divider, without removing it completely (divider should disappear only at the end of the animation)

**Comment by shlomitc** [comment]
@argshook - how difficult is this to fix?

**Comment by argshook** [comment]
> It also causes the content to move 1px up.
> Severity major

:unamused:

here's #2615 with fade-out for divider

**Comment by argshook** [comment]
fixed in #2615, will be available in version newer than 5.18.3
