### ISSUE TITLE
`<Modal/>` driver does not support multiple Modals

### ISSUE THREAD

**Issue by hepiyellow** [wix/wix-style-react#2623]
## Issue

When multiple Modals are rendered onto the page (not necessarily opened),
then the driver methods like `isScrollable`, `getChildBySelector`, `isThemeExist` always query the first Modal.

## Solution

Similar to what we did with Tooltip:
-  we need to put a uniq identifier (per Modal instance) on Modal root element and put a similar id on the portal.
- The only thing we can put on the portal element is a className.
- change driver's `getPortal` to get the id from element root, and look for the correct portal element.

**Comment by shlomitc** [comment]
won't be fixed any time soon - will reopen on request
