### ISSUE TITLE
[<Page />] null is not an object (evaluating 'this._getScrollContainer().scrollTop')

### ISSUE THREAD

**Issue by alexk0ch** [wix/wix-style-react#2633]
# Bug Report

### Relevant Components
Page

### Current Behavior
Attempts to access scrollContainer.scrollTop while scrollContainer is null.

### Expected Behavior
Should eat this error (do nothing if container is null) or do not call this method at all if not mounted. 

### Steps to Reproduce
https://my.trackjs.com/details/f1c2c930a5904a4ba593ec42b33ba768
Application name: Wix Video Dashboard

### Severity
Minor

**Comment by shlomitc** [comment]
hey. can you please supply a reproducible example?

**Comment by alexk0ch** [comment]
I don't think so, wasn't able to reproduce, we only have a bunch of errors like these. Maybe we can lower priority here to Minor.

**Comment by shlomitc** [comment]
Specific browser? OS?

**Comment by shlomitc** [comment]
ping?

**Comment by shlomitc** [comment]
Ok, please re-open if pops again
