### ISSUE TITLE
<BadgeSelect/> - allow to hide the marker (color) in options 

### ISSUE THREAD

**Issue by assafganor** [wix/wix-style-react#2635]
`<BadgeSelect/>`
Our great and creative UX designer asked for a BadgeSelect without the color next to the options.
The skin should be applied to the Badge, but the options shouldn't have the marker (color)

![screen shot 2018-12-20 at 11 58 23](https://user-images.githubusercontent.com/9839921/50283878-e8769300-045f-11e9-8d9a-0d165fce0bb4.png)

![screen shot 2018-12-20 at 14 04 15](https://user-images.githubusercontent.com/9839921/50283956-2e335b80-0460-11e9-9b45-843b578c5a52.png)

**Comment by shlomitc** [comment]
@wuwa - what do you think?

**Comment by wuwa** [comment]
ok, can add this option

**Comment by shlomitc** [comment]
@assafganor - a pullrequest will be happily accepted

**Comment by shlomitc** [comment]
As this is yet to be implemented nor we have specs for it, I can suggest using [`DropdownBase`](https://wix-wix-style-react.surge.sh/?selectedKind=Components&selectedStory=DropdownBase&full=0&addons=0&stories=1&panelRight=0).
Just compose the `Badge` with the correct a suffix icon and `DropdownBase` component to get the required behavior.
If you still wish to do a PR to get the same component, you're still very much welcome

```js
import DropdownBase from 'wix-style-react/DropdownBase';
import Badge from 'wix-style-react/Badge';
import ChevronDown from 'wix-style-react/new-icons/ChevronDown';

const MyCustomBadgeSelect = () => <DropdownBase
  data-hook="story-dropdown-base-uncontrolled-click"
  options={[
    { id: 'general', value: 'general' },
    { id: 'standard', value: 'standard' },
    { id: 'danger', value: 'danger' },
    { id: 'success', value: 'success' },
    { id: 'neutral', value: 'neutral' },
    { id: 'warning', value: 'warning' },
  ]}
>
  {({ toggle, selectedOption = {} }) => {
    return (
      <Badge
        skin={selectedOption.value}
        suffixIcon={<ChevronDown viewBox="6 6 12 12" />}
        onClick={toggle}
      >
        {selectedOption.value || 'Please choose'}
      </Badge>
    );
  }}
</DropdownBase>
```
