### ISSUE TITLE
Breakpoints for General Icons

### ISSUE THREAD

**Issue by ZilvinasMaciulis** [wix/wix-style-react#2639]
Hi All!

All this time we had one size of general icons to fit all, even the smallest elements in WSR and now it is time to introduce breakpoints.

From now on icons should come in two sizes: 24x24 and 18x18.
18x18 icons should have prefix "Small" and be automatically used in particular size elements:

Button: "small", "tiny".
IconButton: "small"
TextButton: "small"
Badge: "medium" , "small"
Inputs: "small"
 
18x18 svg icons: https://drive.google.com/open?id=10JTsFQ0Pgs1Wrq6i4OnHsmTsJjoEnWhb

**Comment by ZilvinasMaciulis** [comment]
The pack was updated with new icons. I'll add the full updated pack soon today.

**Comment by ZilvinasMaciulis** [comment]
@mosheKerbel 

Updated small icons

[18x18_19.04.23.zip](https://github.com/wix/wix-style-react/files/3107374/18x18_19.04.23.zip)

**Comment by ZilvinasMaciulis** [comment]
@mosheKerbel 

Updated the naming

[18x18_19.04.23.zip](https://github.com/wix/wix-style-react/files/3107441/18x18_19.04.23.zip)

**Comment by shlomitc** [comment]
@ZilvinasMaciulis - what do you mean by updating the naming?
if these icons already exist in the system - I don't want to rename them as this is a breaking change

**Comment by mosheKerbel** [comment]
@shlomitc it's ok
we talked about it, Zilvinas jsut added the prefix of "Small" to the new icons he sent me in the prior message.

**Comment by shlomitc** [comment]
done
