### ISSUE TITLE
Ruler icon

### ISSUE THREAD

**Issue by adavidof** [wix/wix-style-react#2644]
### Relevant Components
Icon `Ruler`
Here I found it:
http://electric-process.surge.sh/

But in wix-style-react v.5.19.0 it doesn't exist.
https://wix-wix-style-react.surge.sh/?selectedKind=1.%20Foundation&selectedStory=1.4%20Icons&full=0&addons=0&stories=1&panelRight=0

### Current Behavior
No `Ruler` icon now in wix-style-react

### Expected Behavior
I need it.

### Severity

Minor

**Comment by shlomitc** [comment]
@wuwa - do we have any alternatives to this icon?

**Comment by milkyfruit** [comment]
@ZilvinasMaciulis is in charge of refining all WSR icons.
@adavidof do you need specifically this icon: 
![image](https://user-images.githubusercontent.com/1684587/50590531-16160000-0e94-11e9-9a50-798fec4ec461.png)
(ruler with a pencil)
Or any icon that illustrates a ruler?
Could you share about your project to @ZilvinasMaciulis where this icon is supposed to be used?

**Comment by shlomitc** [comment]
@adavidof - so can we close this issue?

**Comment by milkyfruit** [comment]
If none product is using this icon, then it shouldn't be added.

**Comment by adavidof** [comment]
@shlomitc yes, thanks!
