### ISSUE TITLE
typography.h1 is broken

### ISSUE THREAD

**Issue by adavidof** [wix/wix-style-react#2646]
# Bug Report
### Relevant Components
`Text` or `Heading`

### Current Behavior
![image](https://user-images.githubusercontent.com/10529679/50350437-e12ab480-0547-11e9-8d46-8992cc773a5d.png)
![image](https://user-images.githubusercontent.com/10529679/50350463-edaf0d00-0547-11e9-960b-bf54bf6df5a9.png)

### Expected Behavior
![image](https://user-images.githubusercontent.com/10529679/50350221-11be1e80-0547-11e9-91d4-042079d83897.png)
![image](https://user-images.githubusercontent.com/10529679/50350164-e0dde980-0546-11e9-9997-1fe013653e2f.png)

### Steps to Reproduce
Update to wix-style-react 5.19.0 from 4 major version

### Severity

Major

**Comment by shlomitc** [comment]
This is not a bug, but a required UX change in the entire wix level.
Please refer to the migration guide / change log to see all text changes
