### ISSUE TITLE
component generator - 'component already exists' error even if the folder has only README file

### ISSUE THREAD

**Issue by dorduch** [wix/wix-style-react#2648]
# Bug Report

### Relevant Components
component generator 

### Current Behavior
if the folder exists with only README file inside, the generator will not create new component with that name 

### Expected Behavior
the generator should fill the folder with the component files. 

### Steps to Reproduce
create NewComponent folder
put empty 'README-SPEC.md' file inside
npm run generate
give it name: 'NewComponent'

### Severity
Low

**Comment by yardnsm** [comment]
This is a safety feature used in the component. If your `README-SPEC.md` file is not committed, when you'll run the generator you'll also get the following warning:

```
✖ Git working directory is dirty. Commit or stash your changes, or run the generator with the --force flag
```

You can use `git stash` to stash your changes, run the generator, then run `git stash pop` in order to apply your stashed changed (and then resolve the conflicts, if exist).

**Comment by dorduch** [comment]
The issue occurs even if the `README-SPEC.md` file is already committed. 
The main point here is that even though the folder exists, there are no component files inside, hence we CAN create the new component.

**Comment by hepiyellow** [comment]
I agree with for. 
If therr are no file name collision, then we can generate safely. 
It is a common usecase.

**Comment by yardnsm** [comment]
I think this is a very specific use-case and most users probably won't even reach it.

Also, it requires to generate the files map during _the first_ user prompt. What will happen when we'll add more prompts that will cause more files to be added to the file map? We can't tell for sure what files will be generated. That's the reason for the naive check (if the folder exists, we assume the component exists).

Excluding only the `README-SPEC.md` file seems redundant to me.

**Comment by shlomitc** [comment]
I say let's keep it simple, it's an edge case, so you can just put the file on the side until generating
