### ISSUE TITLE
What's the deal with `runInputWithOptionsTest`?

### ISSUE THREAD

**Issue by yardnsm** [wix/wix-style-react#2649]
# Bug Report

### Relevant Components

All the `<InputWithOptions/>` family:

* `<InputWithOptions/>`
* `<Dropdown/>`
* `<MultiSelect/>`
* `<AutoComplete/>`
* `<MultiSelectCheckbox/>`

### Current Behavior

The `<InputWithOptions/>` test file exports a function called `runInputWithOptionsTest`. When called with a driver, it'll run the `<InputWithOptions/>` test suit with that driver.

At first it makes sense; there are some components that `extends` from `InputWithOptions` and you'd like to re-use it's tests. But, these tests are running agains **the same `<InputWithOptions/>` component** (not the new component you'd want to test), but with a different driver.

This doesn't make any sense.

I assume the intention was to run the tests against a different component, so for example the `<AutoComplete/>` test file will call `runInputWithOptionsTest` with the `<AutoComplete/>`'s driver **and the `<AutoComplete/>` component**.

This also make no sense.

Each component (specified above in "Relevant Components") has different behaviour. We can't (and shouldn't) write a single test suit that will work for different components with different behaviour. I tried to also pass the `Component` to `runInputWithOptionsTest`, and surprise: it fails.

The `<InputWithOptions/>` component is already tested. I think we can remove the `runInputWithOptionsTest` thingy completely. 

Oh, and when you make a small change in `<InputWithOptions/>`, you can get a 6 failing tests and different component and you won't understand what's happening.

### Expected Behavior

Remove `runInputWithOptionsTest` ~~or at least make it work with different components~~.

### Severity

* _Low_

cc: @argshook @hepiyellow @mykas @shlomitc @nitayneeman

**Comment by argshook** [comment]
It's over engineered nonsense, last i saw it, i twiched too :)

**Comment by yardnsm** [comment]
Resolved in #2652
