### ISSUE TITLE
Private drivers pattern issues

### ISSUE THREAD

**Issue by hepiyellow** [wix/wix-style-react#2651]
## Issues with our current pattern

Our current pattern is to have a private driver, which spreads the public driver.

### Duplicate code

private drivers need to reimplement element selectors

### Easy to override

Private drivers can easily (by mistake) override public driver methods, so we are not testing the public methods.

### Nested Drivers

If a driver A has a nested driver B.
Then drive A's private driver must construct a private version of driver B, and "merge" it with the public driver that A exposes.

## Suggested `[PRIVATE_SYMBOL]` Solution

In this solution, we have only one driver (file) and all private methods are nested inside a symbol prop.

1. No duplicate element selectors
1. private and public methods are in different namespaces (no collision, no override)
1. No need for any special code for nested drivers

**Comment by hepiyellow** [comment]
After discussion with Shlomi and Yarden, we decided to :

### 1. One file
- Avoid using `driver.private`, and write the private driver in the same file as `driver.js` (So we can easily share common element selectors).
- The public driver would be the default export.
- The private driver would be a named export.

### 2. We are ok with one namespace

We might want to have a "merge" function (merge public and private drivers) which checks for name collisions.

### 3. Nested private drivers is NOT a valid use-case 

- The need for nested private drivers is only because of inheritance (components like MultiSelect which inherit from InputWithOptions). 
- We should avoid inheritance.
- Until we do this inheritance-cleanup, we can ... do something... ugly,...

**Comment by argshook** [comment]
> @argshook Does this affect the smoke-test?

not only smoke test but testkit documentation too, also contributor happines. The more magic we do, the more difficult it is to parse it both for script and for human.

im not really sure what is the big problem here. we should consider
testkits public API and treat them accordingly. they should be simple and
readable, easy for contributors to handle.

for any special internal cases that are meant only for maintainers (us)
we can have separate file, and play there. merging these two worlds into one by
symbol, or merge function or whatever is just asking for trouble imo.

is problem repetition? let's solve it case by case, like extract some
selectors if they're repetitive. but even then, why are selectors
repetitive? let's maintain a good list of utilities then (e.g. `byHook`
and friends)
