### ISSUE TITLE
`DropdownLayout: Invalid options provided` error

### ISSUE THREAD

**Issue by adavidof** [wix/wix-style-react#2656]
# Bug Report
`DropdownLayout: Invalid options provided`

Please let me use value as I need.

### Relevant Components
DropdownLayout

### Current Behavior
pass options:
```js
[{
  id: 'admin',
  value: 'admin'
}, {
  id: 'viewer',
  value: 'viewer'
}, {
  id: '',
  value: 'none'
}];
```

and get `DropdownLayout: Invalid options provided: ` error

### Expected Behavior
Don't get the error.

### Severity
Critical

**Comment by shlomitc** [comment]
what is the expected UI in such a case?

**Comment by adavidof** [comment]
@shlomitc 
sorry, `id` is empty, options example is fixed

**Comment by shlomitc** [comment]
`id` is mandatory in order to apply unique selections.
again - what is the expected UI?

**Comment by shlomitc** [comment]
just pass in some arbitrary value

**Comment by adavidof** [comment]
@shlomitc 
I pass this:
```js
[{
  id: 'admin',
  value: 'admin'
}, {
  id: 'viewer',
  value: 'viewer'
}, {
  id: '',
  value: 'none'
}];
```

**Comment by shlomitc** [comment]
so pass this:

```
[{
  id: 'admin',
  value: 'admin'
}, {
  id: 'viewer',
  value: 'viewer'
}, {
  id: 'some-id',
  value: 'none'
}];
```

**Comment by adavidof** [comment]
I know
why I should do this?

I need just empty value

**Comment by shlomitc** [comment]
because this is how the component works, you won't be able to render without it

**Comment by adavidof** [comment]
in WSR 4 version I don't need it
this changes broke my app

**Comment by shlomitc** [comment]
this was not validated and caused unexpected behavior when items were changed and keyboard navigation was activated. thus - it actually fixes a bug and not breaking your app

**Comment by adavidof** [comment]
ok, thanks!
