### ISSUE TITLE
Multiselect: click enter and submit form

### ISSUE THREAD

**Issue by davydof** [wix/wix-style-react#2657]
# Bug Report

### Relevant Components
Multiselect

### Current Behavior
After enter value to multiselect and push `Enter` button the form which wrap the multiselect component start to submit.

### Expected Behavior
At the first `Enter` button push add the value to tag.

### Severity

Major

**Comment by adavidof** [comment]
@shlomitc could you please prioritize this task?
I really need it

**Comment by shlomitc** [comment]
@adavidof - I'm sorry but I don't think it could be pushed in the near future. PRs are also welcome

**Comment by hepiyellow** [comment]
Isn't simply calling having `e.preventDefault()` when Enter is pressed on an option?

**Comment by shlomitc** [comment]
@adavidof - does other component behave correctly? For example when using the `Autocomplete` component and pressing Enter for selection from the list?

**Comment by adavidof** [comment]
@shlomitc @hepiyellow 
the problem is:
1. I fill the input and click `Enter` button
2. value is added
3. the remove tag button clicked and remove added tag

like after add the tag I have the focus on the remove tag button.

![image](https://user-images.githubusercontent.com/10529679/53256008-935d3480-36cf-11e9-847b-3d1cce53c56a.png)
![image](https://user-images.githubusercontent.com/10529679/53256134-d5867600-36cf-11e9-898c-1c9764b15202.png)

So we need to fix this part

**Comment by shlomitc** [comment]
I couldn't get the focus on the remove button in any of the following examples in the storybook:
https://wix-wix-style-react.surge.sh/?selectedKind=3.%20Inputs&selectedStory=3.8%20Tags&full=0&addons=0&stories=1&panelRight=0

maybe you have some custom behavior? or reproducible example?

**Comment by adavidof** [comment]
@shlomitc https://github.com/wix-private/media-platform-client/tree/fix/multiselect branch
![image](https://user-images.githubusercontent.com/10529679/53338086-73b25000-390b-11e9-9b45-7d793c2f99e7.png)

**Comment by gilmeir** [comment]
**Reproducing**
I've created a [codesandbox](https://codesandbox.io/s/5zj7wj50kn) with MultiSelect and Input components inside a form.
See the behaviour when clicking Enter inside the component after selection.

**Prevent default**
If "Prevent Default" is unchecked an Enter key press will refresh the page after submitting the form - this is default browser behaviour for forms. This is the behaviour @davydof ran into.

If the checkbox is checked, the form's onSubmit in the sandbox calls e.preventDefault() to disable that refresh.

**Next step**
According to this example it's up to the form to handle that, I believe this is how it should work.
Going to consult with Neil (UX a11y) about this case.

**Comment by gilmeir** [comment]
The decision was to not propagate the Enter up to the parent, which means hitting Enter inside a form will not trigger a submit.

It might break the functionality for edge cases with multiselect without a submit button - Enter will not submit.

@shlomitc do we consider this breaking?

**Comment by shlomitc** [comment]
Not considered breaking, it’s a fix

**Comment by gilmeir** [comment]
Please ignore the previous 2 PRs, I created a new one #3562 due to an applitools issue which required creating a new PR
