### ISSUE TITLE
`<DropdownLayout/>` - Bad API Decisions

### ISSUE THREAD

**Issue by hepiyellow** [wix/wix-style-react#2660]
## Why?

This Issue is about pointing out the problematic things in the DropdownLayout API.
Things that we carry on to all the components that use it (Dropdown, InputWithOptions,...)
So that we can one day fix the API, or if we write a new component hierarchy from zero, we won't make the same mistakes.

### `id` is not needed

We shouldn't force every option to have `id`, moreover, `id` should not really needed.

DropdownLayout does not do any filtering by itself, it doesn't need to store selected item id as an inner state, and keep the selected item when items change. That is the responsibility of the Consumer of `<DropdownLayout/>` to keep manage the selected item if it changes the items.

### onSelect argument should NOT have the `value`

The `option.value` is what gets rendered. It is NOT always a string, it can be a component.
We should NOT be passing the whole option (which includes the `value`) when we call `onSelect`.

This is confusing and leads to bugs like [this one](https://github.com/wix/wix-style-react/blob/11fad24f85074a520fe6b45b893828caefbf9632/src/MultiSelect/MultiSelect.js#L159) and [this one](https://github.com/wix/wix-style-react/blob/11fad24f85074a520fe6b45b893828caefbf9632/src/MultiSelect/MultiSelect.js#L90) where we treat the `value` as a string.

> This is one more reason to prefer an API where each option is something like this, where the rendered part is in the children.

### Suggested API

```js
<Option
   value="arizona" 
   payload={{code: ARZ}} 
   selected
  >
  <span>A r i z o n a</span>
</Option>
```
- rendered part is in children (naturally), and conforms to native `<select/>` API.
- `value` is a string identifier (and conforms to native `<select/>` API). It can be used as an auto-complete (typeahead) source.
- `payload` is an opaque value, that is of no concern to `<DropdownLayout/>` it is just passed back in `onSelect` when an option is selected.
- `selected` - Having `selected` on the option conforms to native `<select/>` API, which also makes it easy to have multiple options selected.

**Comment by shlomitc** [comment]
won't be fixed any time soon - will reopen on request
