### ISSUE TITLE
<MultiSelect/> - testkit page is  broken

### ISSUE THREAD

**Issue by shlomitc** [wix/wix-style-react#2685]
# Bug Report

### Relevant Components
`<MultiSelect/>`

### Current Behavior
The Testkit page is not loading and an error is displayed
![image](https://user-images.githubusercontent.com/6093192/50493034-a4692c80-0a23-11e9-91e9-2ab6b1775127.png)
https://wix-wix-style-react.surge.sh/?selectedKind=3.%20Inputs&selectedStory=3.8%20Tags&full=0&addons=0&stories=1&panelRight=0

### Expected Behavior
Well... :)

### Severity

Major

**Comment by argshook** [comment]
fixed in https://github.com/wix/wix-ui/pull/1050, it will roll here too once we release new storybook
