### ISSUE TITLE
<Text/> - anchor styling should be more specific

### ISSUE THREAD

**Issue by shlomitc** [wix/wix-style-react#2688]
# Bug Report

### Relevant Components

`<Text/>`

### Current Behavior

The following should apply link styles to the direct `a` child element (`> a`):

```js
<Text>
  <a>some link</a>
</Text>
```
![image](https://user-images.githubusercontent.com/6093192/50539911-f4b1cd00-0b90-11e9-8754-90e3a053ad15.png)

This works well, but the rule is too strong. For example, a link can also be used inside a button

```js
<Button upgrade as="a" href="https://www.wix.com" target="_blank">
    Button which is a link
</Button>
```
![image](https://user-images.githubusercontent.com/6093192/50539914-fc717180-0b90-11e9-98a8-ef36314454ac.png)

But when wrapped with `<Text/>`, styles are overridden:

```js
<Text>
  <Button upgrade as="a" href="https://www.wix.com" target="_blank">
    Button which is a link
  </Button>
</Text>
```
![image](https://user-images.githubusercontent.com/6093192/50539919-05624300-0b91-11e9-89ff-397f00d21888.png)

### Expected Behavior

The `<Text/>` component link styles should apply only to the direct child (` > a`)

### Steps to Reproduce
As described above

### Severity

Major

**Comment by argshook** [comment]
```js
<Text>
  <Button upgrade as="a" href="https://www.wix.com" target="_blank">
    Button which is a link
  </Button>
</Text>
```

is it a valid use case?

the `> a` would probably fix it, sure, but what if user does

```js
<Text>
  <Dropdown/>
</Text>
```

or something similar? it's possible something else will need to be more specific and we'll jump to fix it too.

maybe instead we should note in story or somewhere that `<Text/>` has styles that are meant for textual content only and beware if you pass something else

**Comment by argshook** [comment]
> It can happen if some container applying Text (I think that one of our modals is doing it).

hmmm, maybe we should look into that and try not to apply for containers where we now any children could go.

> Regarding the Dropdown example, what will be the issue in this case?

dropdown is just a silly example, similar could happen with any other component. and the question is if we should care about it or instruct what valid usages are

**Comment by boriskor** [comment]
@argshook , in the case of the
```jsx
<Text>
  <Button upgrade as="a" href="https://www.wix.com" target="_blank">
    Button which is a link
  </Button>
</Text>
```

the `> a` won't help either, because `<Button as="a" />` is being rendered as `<a>` tag.
In the meantime, we made the rule apply to the direct child anyway, but IMO we need to instruct users to use some custom link component explicitly and not rely on plain `<a>` tags, because of the aforementioned problem.

**Comment by shlomitc** [comment]
done
