### ISSUE TITLE
<Button/> - native props are missing from docs

### ISSUE THREAD

**Issue by shlomitc** [wix/wix-style-react#2709]
# Bug Report

### Relevant Components
`<Button/>`

### Current Behavior
`onClick` for example is one of the main native API props that the component takes, but it is not displayed in the API tab.

### Expected Behavior
1. important APIs should be defined, even if they are native.
2. mention that all native APIs are supported

### Steps to Reproduce
just go to the API tab of Button

### Severity
Major

**Comment by mykas** [comment]
What other important native APIs can we consider?

**Comment by shlomitc** [comment]
I think that this is the most important I can think abiytb

**Comment by mykas** [comment]
ok, because we have to take in consideration that button can be become anchor and we are kind of limited to only universal attributes or custom props.

**Comment by mykas** [comment]
https://github.com/wix/wix-style-react/pull/2718
