### ISSUE TITLE
`<InputWithOptions/>` - ContactItemBuilder not working when highlight enabled

### ISSUE THREAD

**Issue by hepiyellow** [wix/wix-style-react#2715]
When using a ContactItemBuilder to build options, and passing them to `<InputWithOptions/>`,
I see only empty options.

When I disabled the highlighter `highlight = false`, then it works properly.

See example usage here:
https://github.com/wix/wix-style-react/pull/2708

In Storybook, 3.8 Tags, "Sugges+Allow New Tags" example.

**Comment by shlomitc** [comment]
the highlighting functionality should not be applied in the case of non-textual values

**Comment by shlomitc** [comment]
low priority, won't be fixed
