### ISSUE TITLE
<MultiSelect/> - Issues Summary

### ISSUE THREAD

**Issue by hepiyellow** [wix/wix-style-react#2759]
## Tab
Tab does not Step out of component

## Blur
Blur should do Cancel (Programatic blur)

## Paste
 - Select-Mode :
   - Single value: should paste text without submit (TBD)
   - Multiple values: TBD ?

## Closing Options
These should NOT close options
- Click on Option 
- Esc

**Comment by LittleTal** [comment]
### Tab
Blur after Tab - in case input value is empty
bug- tab after writing an existing option from the list should add a tag with the selection - currently value is deleted

### Paste
Select+autocomplete-Mode :
Single value: submit value as is (tag appearance will indicate if the value is in the list or not)
Multiple values: same as single

### keyboard 
Select - Mode (when user can only select from a list ):
Keyboard keys should search the list according to first letter

**Comment by shlomitc** [comment]
won't be fixed
