### ISSUE TITLE
input with options - dont apply blur when option is clicked

### ISSUE THREAD

**Issue by Shaniko** [wix/wix-style-react#276]
inputWithOptions component supports a Blur event, as well as a Set event for selecting an option from the dropdown. 
When clicking an option from the dropdown, the Blur event is invoked in addition to the Set event.

**Comment by argshook** [comment]
@Varnius hey, perhaps #841 of yours fixes this as well?

**Comment by argshook** [comment]
@Shaniko closing, please reopen if you still encounter this issue.
