### ISSUE TITLE
[Tooltip]: Add support for children as a function

### ISSUE THREAD

**Issue by ipanasenko** [wix/wix-style-react#2775]
Allowing `Tooltip` to accept children as a function, and providing a couple props to it, will help us to control children's behavior easier.

Use case I had:
I have this text, which is displayed on hover. And this text should display tooltip on click. So, when tooltip is active, but mouse is moved away, tooltip stays but text becomes hidden:

![image](https://user-images.githubusercontent.com/576152/51251211-7a12eb00-19a1-11e9-998c-88c681541c40.png)

If I knew Tooltip state, it'd allow me to keep showing text until tooltip is closed

**Comment by yardnsm** [comment]
We recommend using the newer `<Popover/>` component, which has a better positioning mechanism and is fully controlled.

I'd imagine you could achieve something similar with it:

```jsx
{/* This is the wrapper component that displays the image in your example */}
<Wrapper
	onMouseLeave={() => this.setState({ popoverShown: false })}
>

	<Popover
		shown={this.state.popoverShown}
		animate
		placement="top"
	>
		<Popover.Element>
			<span
				onClick={() => this.setState({ popoverShown: true })}
			>
				This is the caption
			</span>
		<Popover.Element/>
		<Popover.Content>
			<div><b>Bridal Bouquet</b></div>
			<div>by Wix</div>
		<Popover.Content/>
	</Popover/>
</Wrapper>
```

Docs available at: https://wix-wix-style-react.surge.sh/?selectedKind=Components&selectedStory=Popover&full=0&addons=0&stories=1&panelRight=0

**Comment by ipanasenko** [comment]
Yeah, I can do exactly same thing with Tooltip component. I wanted to avoid controlling it

**Comment by yardnsm** [comment]
So yeah, it's probably better to have it controlled. Anyway, we're planning to deprecate the `<Tooltip/> component in favour for the new `<Popover/>`, so it's recommended to use it.

**Comment by ipanasenko** [comment]
Understood. Thanks!
