### ISSUE TITLE
`<AdvancedToggle/>` or `<RadioButton/>`

### ISSUE THREAD

**Issue by mykas** [wix/wix-style-react#2785]
The intent of this issue is to suggest a new component name. 

Currently, we have `Advanced Toggle` component suggested in UX book: https://zpl.io/a8pGGAJ .
<img width="203" alt="screenshot 2019-01-18 at 17 45 45" src="https://user-images.githubusercontent.com/8919190/51396989-eaa83c00-1b48-11e9-898a-6303f40a577f.png">

### The problem with the current name I think is:

* The component will support multiple toggle values instead of just two like it is on `ToggleSwitch` component.

* The semantic equivalence of this in html is just to use multiple `<input type="radio"/>`. Which suggests itself that this might be actually a `Radio group`.

* Developers might not search for the `Toggle` in storybook when thinking in mind about radio.

### What I suggest

To use `<RadioButton/>`. This name will suggest that it works like radio but looks like a button.

What do you think @shlomitc @wuwa @LittleTal @milkyfruit @argshook @hepiyellow  ?

**Comment by shlomitc** [comment]
We were suggested the name of “Segmented Toggle” with this spec
https://github.com/wix/wix-ui/blob/master/packages/wix-ui-core/src/components/segmented-toggle/README.md

**Comment by mykas** [comment]
Is this gonna be developed by core3 or us?

**Comment by mykas** [comment]
But I like the name of Segmented Toggle.

**Comment by shlomitc** [comment]
Us

**Comment by hepiyellow** [comment]
### Naming

 I like the name `SegmentedToggle` better than `AdvancedToggle`

### Snippet?

I don't like the name `SegmentedToggle`, I agree with Mykolas that this is a RadioGroup with a special design. 

We actually have this implemented in WSR `<RadioGroup type="button"/>`. The fact that UX sees this as s separate component, doesn't mean that we need to create such a component.
**It could be a snippet.**

### `<Option/>`

The SegmentedToggle spec is nice.
- It defines `IToggleableOption` and implements it with `<SimpleToggleOption/>`.
- I think that `IToggleableOption` is actually a generic `IOption` API.
-I think we should take a little time, and create a `<List/>` and `<ListItem/>` (Aka `<Option/>`) in `wix-ui-core`.

**Comment by argshook** [comment]
`<RadioGroup type="button"/>` is a long standing mistake, we should not
encourage people to use it, it should probably vanish in next major.

regarding the name, why not just `<Toggle/>`?

**Comment by wuwa** [comment]
I am for SegmentedToggle. It's a common name of the big libraries (iOS etc), and even though it's a radio button group should be named otherwise (same could be said for tabs).

**Comment by milkyfruit** [comment]
I agree that `<AdvancedToggle />`name could be improved.

@argshook `<Toggle />`name represents better `<ToggleSwitch />` component: https://zpl.io/bW6RPea

@hepiyellow The core mechanism used in `RadioGroup` and `AdvancedToggle` is the same – radio button selection. However other characteristics are different – RadioGroup's child can be anything from paragraph to an image and a text field, while AdvancedToggle can contain only a name and an icon inside:

Radio Group
![image](https://user-images.githubusercontent.com/1684587/51460847-43ecb700-1d65-11e9-8ab6-b8dcfe069a1f.png)
![image](https://user-images.githubusercontent.com/1684587/51460753-0a1bb080-1d65-11e9-83a4-e1303597f22e.png)

Advanced Toggle
![image](https://user-images.githubusercontent.com/1684587/51460793-2586bb80-1d65-11e9-9175-ddd0f4bd2dfb.png)
