### ISSUE TITLE
`<SortableList />` - list of features and improvements

### ISSUE THREAD

**Issue by Faradey27** [wix/wix-style-react#2793]
List of user requests for `<SortableList />`(WIP component)

- [x] `Animations`:
 some people want to have re-order animations, drop animations, etc.(@naamagr ),
we can take a look to [react-beautiful-dnd](https://github.com/atlassian/react-beautiful-dnd), [react-sortable-hoc](https://github.com/clauderic/react-sortable-hoc) and wix-animations(maybe it possible to allow users to apply animations that they want)
- [x] `BUG` in some cases `preview`(flying/goast) item has different sizes in comparation to common item state (ask @naamagr)
- [x] `shouldCancelSortStart` - callback that call just before drag start, with some meta-data inside of it(like in react-sortable-hoc), which allow users to prevent drag start in some cases(@naamagr )
- [x] `pressDelay` - number, that prevent drag start, after mousedown for some(user defined time)(@naamagr )
- [x] width bug(@shlomitc  comment)
- [x] hover bug(@shlomitc  comment)
- [ ] `setScrollableContainer` or smth like this, should allow user to set scrollable container(body, parent, smth else) (@naamagr )
- [ ] control by keys(accesability)
- [ ] migrate to latest version of `react-dnd`(@mushkab )
- [ ] `performance` - [article](https://medium.com/@alexandereardon/dragging-react-performance-forward-688b30d40a33)
- [ ] `DroppableArea` - allow to d&d item from list to some area (@mushkab )
- [ ] `sortable tree` apis(@mushkab )

**Comment by Faradey27** [comment]
@shlomitc

**Comment by shlomitc** [comment]
I would add a couple more:
1. the click/hover event is not dismissed when dragging an item.
For example, see the SortableItemsList as displayed [here](https://wix-private-wix-ui-adi.surge.sh/?selectedKind=Components%2FLists&selectedStory=SortableItemsList&full=0&addons=0&stories=1&panelRight=0)
I'm dragging Item 1, over Item 2. Item 2 replaces Item 1 and gets the hover style although it is not hovered
![image](https://user-images.githubusercontent.com/6093192/51680679-144ee080-1feb-11e9-9a76-5a6dbaaf3e26.png)

2. Width of preview item can not be 100%
It's just a simple list of items that spreads to 100%. in Preview, the item is popping from context so it doesn't get the defined size.
![image](https://user-images.githubusercontent.com/6093192/51680756-47916f80-1feb-11e9-8b77-24cbe072ad60.png)
Currently people are trying to overcome it by measuring the items container size
```
refCallback = element => {
  this.width = element && element.getBoundingClientRect().width;
};

<div {...style('root', {}, this.props)} ref={this.refCallback}>
  <WSRSortableList {...this.props} renderItem={this.renderItem} />
</div>
``

**Comment by frontned** [comment]
Hey, @shlomitc I have tried to fix the 1 point that you mentioned about the hover states, PR is here https://github.com/wix/wix-style-react/pull/4026

**Comment by shlomitc** [comment]
SortableList and D&D will go through a makeover, so, for now, I think we can close and rethink of the next steps.
thanks
