### ISSUE TITLE
App twitching when opening popover with a calendar

### ISSUE THREAD

**Issue by naamagr** [wix/wix-style-react#2799]
### Relevant Components
Popover + Calendar

### Current Behavior
In Tasks & Reminders app: 
Since I started to use popover to display the calendar component:
clicking on the button that opens the calendar in a popover, for one of the tasks in the list, twitches the list and scrolls up  or down rapidly. 
This does not occur when the content of the popover is just a div and not a calendar.
Note: It is not consistent, might need to try a few times to reproduce.

### Expected Behavior
Popover opens with the calendar, without twitching, above or below the button according to free space.

### Steps to Reproduce
Override statics with RC version 1.87.0 of tasks-client-web 
go to business manager -> Customer Management -> Tasks & Reminders
Try to set the date for one of the last tasks in the list
If not reproducing, try to scroll the page a bit and then retry

### Severity: Major

See attached video: https://youtu.be/Jvl2iLH7GR8?t=32

**Comment by hepiyellow** [comment]
It happens because the Calendar is focusing on the selected day. Before the Popper decides on a new placement.

**Comment by hepiyellow** [comment]
A workaround is to disable Calendar autoFocus.
And `autoFocus` was merged to version6 and version 5.
@naamagr follow Slack for notification on the next minor release.

For notification about a "Real" solution, follow this Issue:
https://github.com/wix/wix-style-react/issues/2825
