### ISSUE TITLE
<DropdownBase/> - allow passing <Popover/> and <DropdownLayout/> props

### ISSUE THREAD

**Issue by yardnsm** [wix/wix-style-react#2804]
# Bug Report

### Relevant Components

- `<DropdownBase/>`

### Current Behavior

`<DropdownBase/>` only accept a specific set of props. If you'd want, for example, change the `<Popover.Content/>`'s portal element (using the popover's `appendTo` prop), you're out of luck.

### Expected Behavior

`<DropdownBase/>` should have a way to accept more `<DropdownLayout/>` and `<Popover/>`.

### Severity

- _**Low**_

**Comment by shlomitc** [comment]
`appendTo` was added, so I think it's enough for this usecase
