### ISSUE TITLE
Page.Content does not fill all available height

### ISSUE THREAD

**Issue by argshook** [wix/wix-style-react#2810]
WixStores UX requires a <Page> component whose <Page.Content> should occupy all the available vertical space.

Currently the only way I found, was to attach CSS properties to the inner [data-class=page-scrollable-content] node, as in:

https://github.com/wix-private/ecom/blob/4bace2504c7718f24d2269dee857d802b6c90cf0/client/wixstores-dashboard/wixstores-dashboard-abandoned-carts/src/components/Main/Main.scss#L17

but it is unstable because it relies on private implementation.

Possible to add a public property? or maybe a way to specify Content's class?

Thank you!

# Bug Report

### Relevant Components
`<Page/>`, `<Page.Content/>`

### Current Behavior
`<Page.Content/>` does not fill all available height, there is no easy way to achieve that

### Expected Behavior
`<Page.Content/>` should either always fill all available height (as in, have `height: 100%`) or have ability to do so without any hacks

### Steps to Reproduce
https://github.com/wix-private/ecom/blob/4bace2504c7718f24d2269dee857d802b6c90cf0/client/wixstores-dashboard/wixstores-dashboard-abandoned-carts/src/components/Main/Main.scss#L17

### Severity
Major

originally reported by @zzgab

**Comment by hepiyellow** [comment]
We could add a prop like we have in `<Card/>` which is called `streachVertically`. 
It adds the `streachVertically` class, which is defined:

.stretch-vertically {
  height: 100%;
  flex-grow: 1;
}

**Comment by zzgab** [comment]
@hepiyellow Might not be sufficient, as we also need to apply height 100% to the nested div. 

Checking…

**Comment by argshook** [comment]
ideally, Page.Content should always fill all available height.

users who add `height: 100%` to their child may use that space, no other hacks needed.
users who don't add `height: 100%` are unaffected by the change

need to see if it's possible without any additional requirements from user

**Comment by hepiyellow** [comment]
WIP - see https://github.com/wix/wix-style-react/pull/2915

**Comment by hepiyellow** [comment]
Resolved by #2935
