### ISSUE TITLE
Code snippets with HOCs are not usable

### ISSUE THREAD

**Issue by boriskor** [wix/wix-style-react#2813]
# Bug Report

### Relevant Components
https://wix-wix-style-react.surge.sh/?selectedKind=3.%20Inputs&selectedStory=3.3%20Field%20With%20Selection&full=0&addons=0&stories=1&panelRight=0

### Current Behavior
In the code snippet above you can see `<WithFocusable(Checkbox)` which is a display name for `<Checkbox />` component because [it's wrapped with `withFocusable` HOC](https://github.com/wix/wix-style-react/blob/2d78e40ac86722bce8f91bdda0658a2814a8799d/src/Checkbox/Checkbox.js#L118). It's not a valid JSX and can't be copypasted as is.

### Expected Behavior
See `<Checkbox` instead of `<WithFocusable(Checkbox)` in the code snippet.

### Severity
Low

**Comment by argshook** [comment]
that wouldn't be an issue if storypage was automated. I think instead of fixing the issue we should refactor that story page to be automated

**Comment by shlomitc** [comment]
won't be fixed any time soon as we're migrating to sections - will reopen on request
