### ISSUE TITLE
`<Popover/>`  With Interactive Content

### ISSUE THREAD

**Issue by hepiyellow** [wix/wix-style-react#2825]
## What is Interactive 

We can consider a Popover's content as "Interactive" when the consumer can act on it (not just see it).
It could be :
1. *Interactive Content*: The content is still shown  when hovered (User can copy text for example)
2. *Interactive Elements*: The content may have clickable elements (by mouse), OR focusable elements (by KeyBoard)

## Case 2: Interactive Elements

In this case, the requested UX is:
- Click on Popover.Target opens the Content.
- *Closing Content* - Closing is done by: 
  - Any click outside of the content (Including the Target)
  - Pressing `Esc`
  - Consumer logic
- *Tab Behavior* - `Tab` could either... (TBD @milkyfruit @wuwa )
  - cycle through focusable elements
  - when Tab is pressed while the last focusable element is focused, it should focus on the next element in the page and close the Popover content. (Is this possible?)

## Popover in Storybook

The [Storybook page for Popover](https://wix-wix-style-react.surge.sh/?selectedKind=Components&selectedStory=Popover&full=0&addons=0&stories=1&panelRight=0), shows only an example of simple non-focusable content.

- [ ] We should either add built-in Interactive functionality OR add a best-practice example.

### Click Outside

Currently, consumer which need to implement the click outside logic, need to avoid using the Popover's `onClickOutside` prop, and implement an On ClickOutside behavior on the Content element that they specify.

- [ ] We can at least add an example for that.

**Comment by yardnsm** [comment]
### Interactivity with mouse events

- If consumers _want_ to have the popover content open when hovering from the Target to the Content, they should:
	- Apply the `onMouseEnter` and `onMouseLeave` on the `<Popover/>` component itself.
	- Use React 16, as the portal implementation works pretty well with these events (it should work out of the box). `onMouseLeave` won't be triggered when hovering from the Target to the Content. We use the `react-portal` library to be compatible with React 15, but it doesn't work as well in this case.
	- Add a `hideDelay` prop (`150ms` seems like a reasonable value). This also will work for React 15.
	- ~~Add `appendTo="parent"`. This will work on React 15.~~

- If consumers _do not_ want to have the popover content open when hovering from the Target to the Content, they should:
	- Apply the `onMouseEnter` / `onMouseLeave` in the `<Popover.Element/>` **first child**, so these events will be directed on that element and not on the entire Popover.

### Interactivity with click events

- After a discussion with @shlomitc, the should update the `onClickOutside` **to not trigger* when the content is clicked. I'm not sure if it should trigger when the Target is clicked.

**Comment by shlomitc** [comment]
@mykas solved the interactivity issue in this PR https://github.com/wix/wix-ui/pull/1160 so regarding clicking outside - it is not called anymore when clicking on the element.

So looks to me like interactivity is solved. @hepiyellow  anything else?
