### ISSUE TITLE
Dropdown component throws console error if I don't define dropdownOffsetLeft="0" as a property

### ISSUE THREAD

**Issue by alonbt** [wix/wix-style-react#283]
This is the console error:
Failed prop type: Invalid prop `dropdownOffsetLeft` of type `number` supplied to `InputWithOptions`, expected `string`.

when I add dropdownOffsetLeft="0" the error disappears. It seems like the problem is that the default value defined a number and not a string

**Comment by nirhart** [comment]
fixed
