### ISSUE TITLE
`<Badge>` Component needs an `ellipsis` prop

### ISSUE THREAD

**Issue by milkyfruit** [wix/wix-style-react#2830]
# Feature Request

### Relevant Components
[`<Badge></Badge>`
](https://wix-wix-style-react.surge.sh/?selectedKind=12.%20Other&selectedStory=12.1%20Badge&full=0&addons=0&stories=1&panelRight=0)
### Current Behavior
Component with long text wraps the text

### Expected Behavior
Adding `ellipsis="true` property would prevent from wraping, would show ellipsis instead.
On Hover a tooltip would appear displaying a full text.

### Severity
Major

### Request comes from
Wix Stores

### Specs
zpl.io/VQ91QZA (Spec update needed to demonstrate ellipsis property)

**Comment by milkyfruit** [comment]
Related developer – @Oripi from Wix Stores

**Comment by shlomitc** [comment]
duplication of this issue
https://github.com/wix/wix-style-react/issues/1622
