### ISSUE TITLE
<Input/> - incorrect state of color and mouser cursor in disabled state

### ISSUE THREAD

**Issue by YuriyFedorov** [wix/wix-style-react#2845]
# Bug Report

### Relevant Components

Input

### Current Behavior

when disabled, arrows are non-clickable but Blue and active on hover (cursor turns to "Hand" mode when hovered over)

### Expected Behavior

Arrows should be disabled as well

### Steps to Reproduce

* enable specs.wos.TasksAutomation
* go to Business manager
* Customer management >> Automation >> create automation >> pick any trigger >> select Action - Create a Task
* under that > turn off `Set a due date` 
* hover over arrows in TimePicker

### Severity

Critical / Major / Low
Low

**Comment by shlomitc** [comment]
Reproducible example
![image](https://user-images.githubusercontent.com/6093192/51928431-992c6680-23fe-11e9-9c16-ff3700571ec2.png)
