### ISSUE TITLE
Add a name attribute inside a FilePicker

### ISSUE THREAD

**Issue by maxvektor** [wix/wix-style-react#2847]
# Feature request

### Relevant Components
FilePicker

### Current Behavior
FilePicker doesn't have a name attribute on a file input. It prevents form from serializing it. 

### Expected Behavior
My suggestion is to add additional prop to pass a name down to an inner input.

### Severity
Low

**Comment by shlomitc** [comment]
This component is relatively old and not according to the style-guide, so if you wish to make change a PR will be welcome
