### ISSUE TITLE
<FormField/> - char counter changes the height when label is inline

### ISSUE THREAD

**Issue by nitayneeman** [wix/wix-style-react#2862]
Given a `FormField` with an inline label that gets an input child (which invokes `setCharactersLeft` on value change).

# The Issue
First of all, the character counter is shown only after typing a value. On top of that, when the counter appears, it changes the FormField's height surprisingly. This behavior doesn't happen when the label is placed on the top.

Here's an example:
![formfield](https://user-images.githubusercontent.com/7141972/52056221-512a5280-256a-11e9-9dba-618e56ff5da5.gif)

**Comment by argshook** [comment]
> First of all, the character counter is shown only after typing a value.

this depends on when consumer calls `setCharactersLeft`, it does not necesarily have to be only during `onChange`.

initially i suggested to simply have `charactersLeft` prop on `FormField` consumer would simply pass a number and wouldn't need to bother calling function. buuuut lost the debate

**Comment by shlomitc** [comment]
let's add a `charactersCounter` prop as another option to set it.
we can decide if to deprecate the render prop, or just leave it as it is.

**Comment by argshook** [comment]
What about `maxLength`, same as in html?

**Comment by shlomitc** [comment]
Whatever you think is better

**Comment by argshook** [comment]
closed by https://github.com/wix/wix-style-react/pull/4350
