### ISSUE TITLE
`<SectionHelper />` needs additional theme

### ISSUE THREAD

**Issue by milkyfruit** [wix/wix-style-react#2863]
#Feature Request

[Section Helper](https://wix-wix-style-react.surge.sh/?selectedKind=8.%20Notification%20Bars&selectedStory=8.7%20SectionHelper&full=0&addons=0&stories=1&panelRight=0
) needs additional theme – `preview`.
This theme is defined by design, but not implemented

![image](https://user-images.githubusercontent.com/1684587/52058340-e714ac00-256f-11e9-8ee0-1e99c1ea7df9.png)

##Link to Specs:
https://zpl.io/VYBBRdE

**Comment by milkyfruit** [comment]
Wix Promote team requested this feature. Related devs @ArturasCH

**Comment by argshook** [comment]
closed by https://github.com/wix/wix-style-react/issues/2863
