### ISSUE TITLE
`<Slider />` missing value highlighting

### ISSUE THREAD

**Issue by milkyfruit** [wix/wix-style-react#2864]
### Bug Report

[`<Slider />`](https://wix-wix-style-react.surge.sh/?selectedKind=4.%20Selection&selectedStory=4.7%20Slider&full=0&addons=0&stories=1&panelRight=0) is missing dark blue value highlighting.

This is how it looks now:
![image](https://user-images.githubusercontent.com/1684587/52058891-14ae2500-2571-11e9-887c-b27aa9de43d1.png)

By design:
![image](https://user-images.githubusercontent.com/1684587/52059029-6656af80-2571-11e9-91ed-cc1a7895ef26.png)

**Link to Specs:**
https://zpl.io/29plGlb

Request arrived from Wix Promote, dev to contact @ArturasCH

**Comment by mykas** [comment]
Fixed.
