### ISSUE TITLE
Stacked Inputs vs `<FieldWithSelection>`

### ISSUE THREAD

**Issue by milkyfruit** [wix/wix-style-react#2869]
# ✨ Feature Request

### 🔦 Scope

???

### 💁 Explanation

Products need a possibility to stack form field elements together:
![image](https://user-images.githubusercontent.com/1684587/52063707-cc483480-257b-11e9-91ed-47f86da8c546.png)

We have defined [`FieldWithSelection`](https://wix-wix-style-react.surge.sh/?selectedKind=3.%20Inputs&selectedStory=3.3%20Field%20With%20Selection&full=0&addons=0&stories=1&panelRight=0) which is limited to 3 options:
![image](https://user-images.githubusercontent.com/1684587/52064099-9192cc00-257c-11e9-829b-59e69f80906d.png)
![image](https://user-images.githubusercontent.com/1684587/52064115-95bee980-257c-11e9-988d-9a893afdad36.png)
![image](https://user-images.githubusercontent.com/1684587/52064122-98b9da00-257c-11e9-8411-4ca24a70107a.png)

Link to FieldWithSelection specs: https://zpl.io/a7jKmvV

### 🐾 Possible solution 
 
a. Support FieldWithSelection and restrict usage of custom field stacking. 
b. Omit FieldWithSelection and develop a more flexible solution, which would allow to stack any kind of fields together.
c. Prevent usage of field stacking by promoting designers to use fields separated by space:
![image](https://user-images.githubusercontent.com/1684587/52064603-a2900d00-257d-11e9-8b94-209bef94fed6.png)

### 👀 Severity

- Critical / Major / Low

I think this request will repeat in a future, so I tend to support options b. or c.
@wuwa @shlomitc what do you think?

**Comment by argshook** [comment]
option c requires minimal work, if none at all. perhaps we can go with that?

**Comment by shlomitc** [comment]
`B` is in our roadmap, will take a few weeks but we'll get there.
`C` is possible already, so I suggest using this until `B` is ready.
`A` is also possible, but requires some CSS enhancement.

I'll go for C at the moment

**Comment by hepiyellow** [comment]
Even when we’ll have a generic stacking component (B) working,
The storybook UX index story should include all valid composition snippets, and any new composition should go through UX team for confermation. 

We can add warning when inadequate components are composited.

**Comment by shlomitc** [comment]
option C was decided. option B will be removed from lib.
option A can be considered in the future.

closing
