### ISSUE TITLE
`<Popover/>` / `OnClickOutside` - WSR should provide a standard way to implement this

### ISSUE THREAD

**Issue by hepiyellow** [wix/wix-style-react#2882]
# ✨ Feature Request

### 🔦 Scope

Mostly `<Popover/>` custom behaviour use cases.

### 💁 Explanation

Sometimes the built in `click-out-side` behaviour is not suitable for consumer use-cases, and they implement their own.

### 🐾 Possible solution 1

`<Popover/>` (and the component composing it), should provide click-outside callbacks for `Target`, for `Content` (and both)

### 🐾 Possible solution 2

Suggest to use `react-onclickoutside`, which is what we use in Popover.

### 🐾 Possible solution 3

Suggest a snippet to users, like this article:
https://medium.com/@pitipatdop/little-neat-trick-to-capture-click-outside-react-component-5604830beb7f

### 👀 Severity

Low

**Comment by shlomitc** [comment]
won't be fixed any time soon - will reopen on request
