### ISSUE TITLE
<Page/> docs are a bit messed up

### ISSUE THREAD

**Issue by boriskor** [wix/wix-style-react#2884]
# 🐛 Bug Report

### 🏗 Relevant Components

`<Page/>`

### 😯 Current Behavior
https://wix-wix-style-react.surge.sh/?selectedKind=2.%20Layout&selectedStory=2.5%20Page&full=0&addons=0&stories=1&panelRight=0
Go to `API` tab

![image](https://user-images.githubusercontent.com/827844/52176652-51229080-27be-11e9-9a6f-7fc1eefff22b.png)

### 🤔 Expected Behavior

In the IDE the example looks OK because the whitespaces are preserved and the font is of fixed width:

![image](https://user-images.githubusercontent.com/827844/52176661-6e575f00-27be-11e9-9402-e7f5b5455503.png)

### 👀 Severity
Low

**Comment by hepiyellow** [comment]
Resolved
