### ISSUE TITLE
`<Page/>` +`<PageHeader/>` - Use renderProps instead of `cloneElement` (`minimized`, `hasBackgroundImage` unrecognized attributes )

### ISSUE THREAD

**Issue by hepiyellow** [wix/wix-style-react#2891]
# ✨ Feature Request

### 🔦 Scope

<PageHeader/>

### 💁 Explanation

For example, `<PageHeader/>`'s `actionsBar` prop is of ReactNode type.
We clone it:
```js
React.cloneElement(actionsBar, { minimized, hasBackgroundImage })
```
This cause an inconveniece in the simple use-case where `actionsBar` is a `<Button/>`.
Native `<button/>` does not support `minimized`, `hasBackgroundImage` attributes, so we get warnings from React.

Props list to change:
- [ ] PageHeader - actionsBar
- [x] PageHeader - breadcrumbs
- [x] Page - childrenObject.PageHeader
- [x] Page - childrenObject.PageTail
- [x] Page - childrenObject.PageFixedContent (no props added in clone, but we can add it to API)

### 🐾 Possible solution 

Use renderProp.

```js
typeof actionsBar === 'function'? actionsBar({ minimized, hasBackgroundImage }): actionsBar;
```

### 👀 Severity

-  Low

**Comment by mosheKerbel** [comment]
@wuwa Can we consider removing the ability for consumers to render different things in the `actionsBar` when in minimized mode?

**Comment by wuwa** [comment]
it can stay the same for both modes, consumer not supposed to add things (however not sure if this has been done out there...)

**Comment by mosheKerbel** [comment]
@wuwa We still haven't release `<Page upgrade/>`, so we can make breaking changes.
Meaning that only when Users will upgrade to the new page, they will have to remove any "minimized-actions-bar" logic.

Do you want to make this braking change?

> If you would like to have the actionsBar Buttons, smaller, we can do that in a generic way, without the consumer's having to do anything about it.

**Comment by mosheKerbel** [comment]
resolved
