### ISSUE TITLE
<DatePicker/> - allow to control disabled previous date

### ISSUE THREAD

**Issue by gilisho** [wix/wix-style-react#2900]
# ✨ Feature Request

### 🔦 Scope

This feature refers to the `DatePicker` component.

### 💁 Explanation

I have two date picker components: From and To. I want that days past the chosen date in From `DatePicker` will be excluded from the To `DatePicker`.
Didn’t find any option to do that, as there’s only exclusion of dates past the current date (today).

### 🐾 Possible solution 

I was thinking of having a new prop that is similar to `excludePastDates` - can be called exludePastCertainDate for example with a given `number` or `new Date(number)`.

### 👀 Severity

I would say this is Critical, as it interferes the experience in our statistics pages (and probably with other statistics section in Wix).
The use case is to present statistics according to certain dates that the user can specify.

- **Critical** / Major / Low

**Comment by shlomitc** [comment]
the feature already exists using the `filterDate` predicate that can be supplied to `<DatePicker/>`
you can refer to the docs
https://wix-wix-style-react.surge.sh/?selectedKind=3.%20Inputs&selectedStory=3.6%20DatePicker&full=0&addons=0&stories=1&panelRight=0

I will be really happy for a PR adding a simple example of usage to the storybook.
