### ISSUE TITLE
Input maxLength not working when type set to number.

### ISSUE THREAD

**Issue by tzelonm** [wix/wix-style-react#2909]
# 🐛 Bug Report

### 🏗 Relevant Components
[Input](https://wix-wix-style-react.surge.sh/?selectedKind=Components&selectedStory=Input)
...

### 😯 Current Behavior
Input with maxLength={3} & type="number"
max length not working.
...

### 🤔 Expected Behavior
maxLength should work.
...

### 👣 Steps to Reproduce
In storybook set the maxLength to 3 and type to number

### 👀 Severity
- Critical / Major / Low

**Comment by shlomitc** [comment]
The native `Input` component doesn't work this way. `maxLength` is supported only for textual representation.
For numeric input, it is suggested to use `max` or `min` instead`<input type="number" max="3">`.
However, the `min`/`max` props are missing in the current component.

Until developed (PRs are always welcome), I suggest using the `onChange` event.

```jsx
class MyNumberInput extends React.Component {
  constructor(props) {
    super(props);
    this.state = {value: ''};
    this.handleChange = this.handleChange.bind(this);
  }
  
  handleChange(e) {
    console.log(e.target.value);
    if(Number(e.target.value) < 4) {
      this.setState({value: e.target.value});
    }
  }

  render() {
    return (<Input type="number" value={this.state.value} onChange={this.handleChange}/>);
  }
}
```

@NitayRabi FYI

**Comment by tzelonm** [comment]
Thanks, I will create PR with the changes. Passing max/min props to the input.

**Comment by shlomitc** [comment]
`NumberInput` component is available in the library, including the min-max props, so I guess this can be resolved.
