### ISSUE TITLE
`<Loader />`, <LinearProgressBar/>`, `<CircularProgressBar/>`needs a new theme

### ISSUE THREAD

**Issue by milkyfruit** [wix/wix-style-react#2913]
# ✨ Feature Request

[A loader](https://wix-wix-style-react-pr-2728.surge.sh/?selectedKind=1.%20Foundation&selectedStory=1.5%20Loader&full=0&addons=0&stories=1&panelRight=0) needs greyscale color theme to work on color backgrounds.
The request comes from Wix Stores. Developer from the team @eddierl 

![image](https://user-images.githubusercontent.com/1684587/52346089-7b2abb80-2a27-11e9-978c-7931513836f6.png)

Needs design guideline update before implementing. @milkyfruit will prepare the specs soon.

### 🔦 Scope

Small

### 👀 Severity

- Urgent, but not critical

**Comment by shlomitc** [comment]
What do you think about disabling the button while the loader is displayed?
![image](https://user-images.githubusercontent.com/6093192/52360184-16318e80-2a44-11e9-998b-52295a942155.png)

**Comment by milkyfruit** [comment]
Tested the loader on various backgrounds, current solution works well enough.
No need to introduce new themes for now.

Full Research:
https://drive.google.com/drive/folders/1Hi2guOIB5-_HpbOobKXMCef_BQHOpF5m?usp=sharing

Prototype 1:
https://drive.google.com/open?id=1OHoFoCdkbH6W9omDyauGYCP8YZ_OkCRa
Prototype 2:
https://drive.google.com/open?id=1t07BqfckQlLjfI5d4ovjOWElZbK0i0BY
