### ISSUE TITLE
MessageBoxMarketerialLayout doesn't display image 

### ISSUE THREAD

**Issue by nofarcohav** [wix/wix-style-react#2921]
# 🐛 Bug Report

### 🏗 Relevant Components

      <MessageBoxMarketerialLayout
        title={<FormattedMessage id={`${t}.newTitle`} values={{name: app.name}}/>}
        content={<FormattedMessage id={`${t}.newDescription`} values={{name: app.name}}/>}
        confirmText={<FormattedMessage id={`${t}.newLink`}/>}
        image={<div className="provision-img-new">123</div>}
        theme="blue"
        primaryButtonLabel="Button"
        dataHook="announcement-standard"
        />

...

### 😯 Current Behavior

there is no image in the header, just a div with a img inside with no src

...

### 🤔 Expected Behavior

the image should appeare 
...

### 👣 Steps to Reproduce

use the code above 

  - **WSR version**: `5.15.1`
  - **Yoshi version**: `1.2.0

### 👀 Severity

Low

- Critical / Major / Low

**Comment by shlomitc** [comment]
the relevant component prop is called `imageUrl` and not `image`, meaning you should pass a url and not a node.
if a node is required, a PR will be highly appreciated

**Comment by nofarcohav** [comment]
> the relevant component prop is called `imageUrl` and not `image`, meaning you should pass a url and not a node.
> if a node is required, a PR will be highly appreciated

the Docs shows that the component has also an image prop
https://wix-wix-style-react.surge.sh/?selectedKind=9.%20Modals&selectedStory=9.4%20Announcement&full=0&addons=0&stories=1&panelRight=0

**Comment by shlomitc** [comment]
docs are confusing now, they show both `MessageBoxMarketerialLayout` and `MessageBoxFunctionalLayout`
[see here](https://user-images.githubusercontent.com/6093192/52412467-82b19980-2ae7-11e9-9d15-1bcea7aeea20.png)

however, I deep dived into the code and see the `imageComponent`, so this will work for you
```jsx
 <MessageBoxMarketerialLayout
    title={<FormattedMessage id={`${t}.newTitle`} values={{name: app.name}}/>}
    content={<FormattedMessage id={`${t}.newDescription`} values={{name: app.name}}/>}
    confirmText={<FormattedMessage id={`${t}.newLink`}/>}
    imageComponent={<div className="provision-img-new">123</div>}
    theme="blue"
    primaryButtonLabel="Button"
    dataHook="announcement-standard"
    />
```

**Comment by shlomitc** [comment]
closing
