### ISSUE TITLE
`<Dropdown/>` ignores value changes if ids didn't change

### ISSUE THREAD

**Issue by dovilel** [wix/wix-style-react#2922]
# 🐛 Bug Report

### 🏗 Relevant Components

`<Dropdown/>`

...

### 😯 Current Behavior

If Dropdown's options values (labels) change, but not ids or selectedId, the selected value in the input does not change.

![screen shot 2019-02-07 at 5 43 13 pm](https://user-images.githubusercontent.com/22763470/52423558-062bb480-2b01-11e9-9c42-91e924db1a25.png)

...

### 🤔 Expected Behavior

Expect value changes to also be taken into account.

![screen shot 2019-02-07 at 5 56 06 pm](https://user-images.githubusercontent.com/22763470/52423929-ad105080-2b01-11e9-936d-227e7ef5ba73.png)

...

### 👣 Steps to Reproduce

```
import React from 'react';
import Dropdown from 'wix-style-react/Dropdown';
import Button from 'wix-style-react/Button';

class ChangingLabelDropdown extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      changeOptionLabel: false
    };
  }

  options() {
    return [
      { id: 1, value: this.state.changeOptionLabel ? 'Should be changed!': 'Option 1' },
      { id: 2, value: 'Option 2' },
    ]
  }

  render() {
    return (
      <div style={{width: '200px'}}>
        <Dropdown
          options={this.options()}
          initialSelectedId={1}
        />
        <Button onClick={() => this.setState({changeOptionLabel: true})}>Change first option</Button>
      </div>
    );
  }
}

export default () => (<ChangingLabelDropdown />);
```

Only happens since Dropdown "upgrade".
Seems like Dropdown only checks for options length, whether ids changed or selectedId changed.

  - **WSR version**: `6.2.0`
  - **Yoshi version**: `3.28.0`

### 👀 Severity

- Major

**Comment by shlomitc** [comment]
can you please explain the use case of this?
changing options value during selection looks a bit confusing in my opinion

**Comment by dovilel** [comment]
@shlomitc 
Eg. if dropdown is used as a filter, while it's labels show the result count for each option.
If the result count changes due to user action, eg. moving the item from one filtered category to another, the dropdown's labels should also change.

In Events:
![screen shot 2019-02-08 at 1 33 17 pm](https://user-images.githubusercontent.com/22763470/52476174-87895280-2ba6-11e9-8d93-8d1d530a255b.png)

![screen shot 2019-02-08 at 1 34 02 pm](https://user-images.githubusercontent.com/22763470/52476178-8b1cd980-2ba6-11e9-8daf-9fdf4f509135.png)

**Comment by shlomitc** [comment]
@hepiyellow it might be related to this change
https://github.com/wix/wix-style-react/commit/5dcc2eaca38a70de69d54ec36145c5f57a2a197b#diff-acc3a01ef84560b7b72c24ff5650dbf0R45
From what I see, we are checking only if `id` was changed, which means that if the value is changed, the selected value isn't reflected.

what do you think should be done here?

**Comment by shlomitc** [comment]
For this unique case, I can suggest using the more controlled variation of `Dropdown` - `inputWithOptions`.
using it will allow you to control also the actual input value which is derived by your state.

```jsx
import React from 'react';
import InputWithOptions from 'wix-style-react/InputWithOptions';

export default class ControlledSelect extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      value: '',
      selectedId: -1,
      clicked: false,
    };
  }

  getOptions = () => {
    return [
      { id: '0', value: !this.state.clicked ? 'First option' : 'after click' },
      { id: '1', value: 'Second option' },
    ];
  };

  onSelect = option => {
    this.setState({
      value: option.value,
      selectedId: option.id,
    });
  };

  onCustomEventInTheSystem = () => {
    //first - effect on the state which the options inherit from
    this.setState(
      {
        clicked: true,
      },
      () => {
        //set the input value according to the new option value
        const options = this.getOptions();
        const selectedOption = options.find(
          option => option.id === this.state.selectedId,
        );

        this.setState({
          value: (selectedOption && selectedOption.value) || this.state.value,
        });
      },
    );
  };

  render() {
    return (
      <div>
        <button onClick={this.onCustomEventInTheSystem}>custom thing</button>
        <InputWithOptions
          readOnly
          options={this.getOptions()}
          selectedId={this.state.selectedId}
          value={this.state.value}
          onSelect={this.onSelect}
        />
      </div>
    );
  }
}
```

**Comment by dovilel** [comment]
Thanks, will do that
