### ISSUE TITLE
V7-V8 Breaking Changes Suggestions

### ISSUE THREAD

**Issue by shlomitc** [wix/wix-style-react#2924]
Please edit this comment with things to go into wix-style-react@7.0.0

Branch name: [`version_7`](TBD)
- [ ] Build is green, ready to release

## Version 7

| # | scope | description | merged to v7 branch | in migration doc |
| --- | --- | --- | :---: | :--: |
| 1 | `<RichTextAreaComposite/>` | remove component, see [PR](https://github.com/wix/wix-style-react/pull/2997) | | |
| 5 | `<RichTextArea/>` | deprecated component, use `<RichTextInputArea/>` instead ([#3354](https://github.com/wix/wix-style-react/pull/3354)) | | |
| 7 | Infra | React >= 16.3 only - remove polyfills and remove [REF_FORWARD flag](https://github.com/wix/wix-style-react/issues/2924#issuecomment-517162706) | | |
| 8 | Infra | update react 16 types #3448 | | |

## Version 8
| # | scope | description | merged to v7 branch | in migration doc |
| --- | --- | --- | :---: | :--: |
| 1 | `<RadioGroup/>` | remove the buttons variation. see [PR](https://github.com/wix/wix-style-react/pull/2874) | | |
| 2 | `<HBox/>` `<VBox/>` | remove components. suggest using `Box` instead | | |
| 3 | `<DatePicker/>` | deprecate `isOpen` prop in favor of `initialOpen` (#3289) | | |
| 4 | `<Input/>` | depreacte the `unit` prop. see [PR](https://github.com/wix/wix-style-react/pull/2887/files#diff-deaeb5c7e253bfa4f497fa8ace0b3607R54) |  |  |
| 5 | `<Input/>` | deprecate `error` and `errorMessage` in favor of `status` and `statusMessage` |  |  |
| 6 | `<Tooltip/>` | remove deprecated component - use new one | | |
| 7 | `<DatePicker/>` | deprecate `isOpen` prop in favor of `initialOpen` (#3289) | | |
| 8 | `<PopoverMenu/>` | deprecated component, use `<PopoverMenuBeta/>` instead (should change the name of the beta thing) | | |
| 6 | `<Page/>` | upgrade flag - remove old component ) | | |
| 7 | Docs | remove all `upgrade` references in the code | | |
| 8 | `<Popover/>` | remove polyfill import which is test only (#3972). it was added when Dropdown was migrated to use Popover in order not to make a testing braking change | | |

**Comment by mosheKerbel** [comment]
find all usages of [support_ref_forward](https://github.com/wix/wix-style-react/blob/master/src/utils/supportRefForward.js)
it exists because this is how we support both react15 and react16 - with this new version we don't to support react15 anymore, so should make it the only behaviour.

**Comment by shlomitc** [comment]
done
