### ISSUE TITLE
PopoverMenu - add ability to manage position of opened dropdown menu

### ISSUE THREAD

**Issue by brumeregan** [wix/wix-style-react#2936]
Please, add ability to customize position for open popover items.
For now it always centered, but it could be align easily to the right/left side.
Expected:
<img width="300" alt="screen shot 2019-02-07 at 3 28 31 pm" src="https://user-images.githubusercontent.com/6932807/52553160-59e11b00-2deb-11e9-820f-b64368a18376.png">
For only this:
<img width="123" alt="screen shot 2019-02-07 at 9 17 35 pm" src="https://user-images.githubusercontent.com/6932807/52553187-69f8fa80-2deb-11e9-833b-67c3ddc0b224.png">

**Comment by mosheKerbel** [comment]
this is fixed in the new popoverMenu
can be closed once PR is merged https://github.com/wix/wix-style-react/pull/3485

**Comment by mosheKerbel** [comment]
new popover is in, instruction can be found in storybook under Beta section.
@brumeregan please use it, it will solve your issue.
