### ISSUE TITLE
`<Icons/>` - Prevent icons from shrinking

### ISSUE THREAD

**Issue by hepiyellow** [wix/wix-style-react#2939]
# 🐛 Bug Report

### 🏗 Relevant Components

All icons

### 😯 Current Behavior

If an icon is in a flex container, and some other item has `flex-grow: 1`, then the icon can shrink.
...

### 🤔 Expected Behavior

dont let it shrink
...

### 👣 Steps to Reproduce

  - **WSR version**: 6.2
  - **Yoshi version**: 

### 👀 Severity

- Low

**Comment by shlomitc** [comment]
if it's in some container that is doing `flex`, I think you should wrap it with some other container that handles flex properties.
I would like to add any specific flex constraints to the icon by default

**Comment by argshook** [comment]
> If an icon is in a flex container, and some other item has `flex-grow: 1`, then the icon can shrink.

huh, why is that bad? you can set `size` on an icon and pin it.

**Comment by mykas** [comment]
I would rather set `flex-shrink:0`?

**Comment by shlomitc** [comment]
won't be fixed any time soon - will reopen on request
