### ISSUE TITLE
Badge docs code example shows uppercase prop used, but it's true by default

### ISSUE THREAD

**Issue by argshook** [wix/wix-style-react#2940]
# 🐛 Bug Report

### 🏗 Relevant Components

Badge
https://wix-wix-style-react.surge.sh/?selectedKind=12.%20Other&selectedStory=12.1%20Badge&full=0&addons=0&stories=1&panelRight=0

### 😯 Current Behavior

1. in playground code example it shows `uppercase` prop being used.
2. toggling uppercase prop from true to false, code example does not show uppercase prop

### 🤔 Expected Behavior

1. in playground code example it should not show `uppercase` being used,
   because defaultProp is `uppercase={true}`, code example should not
   include it
2. code example should show `uppercase={false}`, but it does not show
   uppercase prop at all

### 👣 Steps to Reproduce

https://wix-wix-style-react.surge.sh/?selectedKind=12.%20Other&selectedStory=12.1%20Badge&full=0&addons=0&stories=1&panelRight=0

1. click uppercase prop toggle
2. observe `uppercase={false}` is missing from code example

### 👀 Severity

- Low

**Comment by shlomitc** [comment]
fixed when migrated from `wix-ui-backoffice`
