### ISSUE TITLE
Button: large button with affixes displays very-very small icon

### ISSUE THREAD

**Issue by ipanasenko** [wix/wix-style-react#2941]
WSR 6.3.0, reproduced in playground: https://wix-wix-style-react.surge.sh/?selectedKind=5.%20Buttons&selectedStory=5.1%20Button&full=0&addons=0&stories=1&panelRight=0

![image](https://user-images.githubusercontent.com/576152/52629324-1f967d00-2ec2-11e9-9327-e4b191726e29.png)

**Comment by mykas** [comment]
Fixing. It seems that flex items are letting icon shrink when not enough space is left for the button. Only occurs when viewport changes or not enough space is left.

**Comment by argshook** [comment]
```diff
modified: packages/wix-ui-core/src/themes/backoffice/button/button.st.css
@@ -462,6 +462,11 @@
 
 /* Suffix and prefix */
 
+.button .prefix,
+.button .sufix {
+  flex-shrink: 0;
+}
+
 .button.tiny .suffix {
   margin: 0 -6px 0 3px;
   width: 18px;
```

@mykas i think something like this should be enough?

**Comment by mykas** [comment]
@argshook  yep
