### ISSUE TITLE
`<Button/>` - Long text should be with ellipsis

### ISSUE THREAD

**Issue by hepiyellow** [wix/wix-style-react#2942]
# 🐛 Bug Report

### 🏗 Relevant Components

`<Button/>`

### 😯 Current Behavior

![screen shot 2019-02-12 at 13 47 10](https://user-images.githubusercontent.com/6338722/52633434-0cd57580-2ecd-11e9-84e8-58921ce1f6f8.png)

### 🤔 Expected Behavior

Ellipsis

### 👣 Steps to Reproduce

Put long text in button in storybook

  - **WSR version**: `6.3.0`

### 👀 Severity

- Low

**Comment by mykas** [comment]
I would not mix users strange cases to implementation. How many users would actually enter such long texts to the button? I would agree though to add snippet example where <Text> component is used.

**Comment by argshook** [comment]
For this case user is able to:
```js
<Button>
  <Text ellipsis light>long text</Text>
</Button>
```

instead of trying to fix all possible cases internally, we should
encourage composition of existing solutions

**Comment by shlomitc** [comment]
@argshook - it's a good solution, but the ellipsis will not be applied unless `width` or `maxWidth` are applied directly on the text. So it seems there's an issue anyway which might need to be resolved there

won't work
```jsx
<Box width="100px">
  <Button>
    <Text ellipsis light>long text omg omg omg omg omg</Text>
  </Button>
</Box>
```

will work
```jsx
<Button>
  <Box width="100px">
    <Text ellipsis light>long text omg omg omg omg omg</Text>
  </Box>
</Button>
```
