### ISSUE TITLE
<MessageBoxFunctionalLayout/> support a loader inside the button

### ISSUE THREAD

**Issue by milkyfruit** [wix/wix-style-react#2947]
# ✨ Feature Request

### 🔦 Scope

Small

### 💁 Explanation

[`<MessageBoxFunctionalLayout/>`](https://wix-wix-style-react.surge.sh/?selectedKind=9.%20Modals&selectedStory=9.1%20Alert&full=0&addons=0&stories=1&panelRight=0) component should support a loader inside submit button. This feature is needed for Wix Stores.

### 🐾 Possible solution 

Button label properties `primaryButtonLabel` and `secondaryButtonLabel` should change their propType from `string` to `node`

### 👀 Severity

- Major

### Contact
@eddierl FED from Wix Stores.

**Comment by milkyfruit** [comment]
Related topic: https://github.com/wix/wix-style-react/issues/2913

**Comment by shlomitc** [comment]
this snippet will just work out of the box
```jsx
<MessageBoxFunctionalLayout
    title="Interuption Message"
    confirmText={<Loader size="tiny"/>}
    theme="blue"
  >
    This is a generic message. No harm done, but really needed to interrupt you.
  </MessageBoxFunctionalLayout>
```

passing the `Loader` component as a prop to `confirmText`
and the result will be:
![image](https://user-images.githubusercontent.com/6093192/52724922-e42aaa00-2fb8-11e9-92d3-0137076b5452.png)

**Comment by shlomitc** [comment]
@milkyfruit - is this approved? can we close?

**Comment by milkyfruit** [comment]
yes.
