### ISSUE TITLE
Number formatting feature for an input component is needed

### ISSUE THREAD

**Issue by milkyfruit** [wix/wix-style-react#2949]
# ✨ Feature Request

### 🔦 Scope

Large

### 💁 Explanation

Wix Stores needs a component that supports number formatting, something similar [like spreadsheet apps have.](https://support.office.com/en-us/article/available-number-formats-0afe8f52-97db-41f1-b972-4b46e9f1e8d2)

### 🐾 Possible solution 

WSR team discussed in the past that a text field with `type="number"` and the incrementer arrows should be separated as a standalone component.

![image](https://user-images.githubusercontent.com/1684587/52698970-57aec600-2f7d-11e9-9600-846fdcb7c649.png)

I suggest creating a new `<NumberInput />` component that allows entering only numeric values and supports the requested number formatting.

### 👀 Severity

- Major

### ☎️ Contact

@eddierl FED from Wix Stores.

### 🦀 Blockers

Design Guidelines are not defined.

@wuwa @shlomitc what do you think?

**Comment by eddierl** [comment]
Actually, we are looking for a `<PriceInput />`

**Comment by milkyfruit** [comment]
To make a component reusable, I think, it's worth thinking of number formatting not just for prices. It could be percentage and weight as well.

**Comment by shlomitc** [comment]
@eddierl - what do you mean by a price input? is this just a "mask" of formatting the value?

**Comment by shlomitc** [comment]
@eddierl ping?

**Comment by eddierl** [comment]
Sorry, missed this one
I don't think it's a mask, more like input validation (formatting, limits) and putting the currency in the correct location(left/right).

**Comment by shlomitc** [comment]
@eddierl - do you have any guidelines? examples?

**Comment by eddierl** [comment]
We have partial guidelines here https://zpl.io/2p47G5N
Maybe worth checking it with Store's UX team

**Comment by shlomitc** [comment]
@milkyfruit - can you check the requirements and see if something is missing in our specs?

**Comment by milkyfruit** [comment]
@shlomitc what @eddierl shared it's a good start.
It doesn't specify formatting with the large numbers, like 10 000.00, 10,000.00.
It is planned to do a full spec. For now the start of it is done: zpl.io/a8w5Lqg

**Comment by shlomitc** [comment]
So this requirement is open for a while now but didn't get any attention and will not be solved soon. we can re-open this for discussion when it becomes relevant again.
