### ISSUE TITLE
`<FloatingNotification/>` Issues

### ISSUE THREAD

**Issue by hepiyellow** [wix/wix-style-react#2953]
### Issues
* Text ellipsis
  * [x]   tooltip has no propper styling
  * [ ]  text left margin is too large when ellipsis is applied
* [ ]  Buttons ellipsis is not working
* [x]  Need to limit button's width (max-width: 25%)
* [x]  Docs: Fix `type` type
* [ ]  Icon should be with D10 fill color
* [ ]  Only 2 dots are showing when there is an ellipsis

**Comment by hepiyellow** [comment]
@LittleTal Can you review this new component, and add issues you find to the list above.

You can use the story in the "Tests" category. It has all the variations:

https://wix-wix-style-react-pr-2820.surge.sh/iframe.html?selectedKind=Tests%2F8.%20Notification%20Bars%2F8.2%20Floating%20Notification&selectedStory=1.%20All%20Variations&full=0&addons=0&stories=1&panelRight=0

RTL version:

https://wix-wix-style-react-pr-2820.surge.sh/iframe.html?selectedKind=Tests%2F8.%20Notification%20Bars%2F8.2%20Floating%20Notification&selectedStory=1.%20All%20Variations&full=0&addons=0&stories=1&panelRight=0&rtl=

**Comment by LittleTal** [comment]
Same comments as you mentioned above.
Approved:)

**Comment by shlomitc** [comment]
button ellispsis will be solved once the button will support ellipsis.
regarding other issues - minor and won't be fixed
