### ISSUE TITLE
<PopoverMenu/> - disabled menu item color

### ISSUE THREAD

**Issue by LittleTal** [wix/wix-style-react#2954]
# 🐛 Bug Report

### 🏗 Relevant Components
<PopoverMenu/>
(menu item)

...

### 😯 Current Behavior
Icon and text colors on disabled state are not aligned to disabled variable
![image](https://user-images.githubusercontent.com/23282301/52726864-af205680-2fbc-11e9-9817-039f97ea3423.png)

Currently,
**icon color is** 
color: graytext;

**Text color is**
color: #7a92a5;

...

### 🤔 Expected Behavior
Colors should be aligned to disabled variable

![image](https://user-images.githubusercontent.com/23282301/52727324-a67c5000-2fbd-11e9-8cc6-c8aaf618999d.png)

Expected colors:
**icon color ** 
color: D55 ;

**Text color is**
color: D55 ;

...

### 👀 Severity
Low

**Comment by mosheKerbel** [comment]
Fixed in the new popoverMenu
can be closed once this is merged - https://github.com/wix/wix-style-react/pull/3485
