### ISSUE TITLE
ImageViewer. Add ZoomIn button

### ISSUE THREAD

**Issue by OleksiiPro** [wix/wix-style-react#2955]
# ✨ Feature Request

### 🔦 Scope

ImageViewer component. Add ZoomIn button, or possibility to customize buttons.

### 💁 Explanation

template-cms project needs ZoomIn button in ImageViewer component. It will be used for open image in full size

### 🐾 Possible solution 

1. Add new button
2. Add possibility to customize list of buttons (node prop)

### 👀 Severity

- Major

**Comment by shlomitc** [comment]
Do you have a Zeplin spec for it?

**Comment by OleksiiPro** [comment]
beckyb@wix.com responsible for it. Could you contact with her?

**Comment by shlomitc** [comment]
same as here https://github.com/wix/wix-style-react/issues/2956
