### ISSUE TITLE
ImageViewer loading state

### ISSUE THREAD

**Issue by OleksiiPro** [wix/wix-style-react#2956]
# ✨ Feature Request

### 🔦 Scope

existing ImageViewer component

### 💁 Explanation

Use case of ImageViewer - is to upload images to the server. But there're no loading status in ImageViewer component. Expect to show loading status

### 🐾 Possible solution 

Show loading icon in same way as error one

### 👀 Severity

- Major

**Comment by shlomitc** [comment]
do you have a zeplin spec for it?

**Comment by OleksiiPro** [comment]
> do you have a zeplin spec for it?

**Comment by OleksiiPro** [comment]
[beckyb@wix.com](mailto:beckyb@wix.com) responsible for it. Could you contact with her?

**Comment by shlomitc** [comment]
please ask her to contact the Design system UX - @wuwa

**Comment by shlomitc** [comment]
I didn't get any request from UX for that, so I guess it's not relevant. closing. if still relevant, please reopen
