### ISSUE TITLE
`<Button/>` - should not have `transition all`

### ISSUE THREAD

**Issue by hepiyellow** [wix/wix-style-react#2958]
This make difficult to implement simple cases where visibility need to be changed from `hidden` to `visible` without anumation.

And probably other difficult cases.

We shouldn't use `transition all`.

In particular this interferes with `<Page/>` that need to render `<PageHeader/>` with visibility `hidden` (
in order to measure it, and the make it appear, set visiblity to `visible` without transition.

**Comment by mykas** [comment]
@hepiyellow I think this was already fixed, right?

**Comment by hepiyellow** [comment]
@mykas right
