### ISSUE TITLE
Tooltip on Icon doesn't work

### ISSUE THREAD

**Issue by ipanasenko** [wix/wix-style-react#2963]
When wrapping an icon in Tooltip, I get following in console: 

```
Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()
```

Tooltip isn't shown.

This is easily fixed by wrapping an icon in span tag, but can also be fixed using `forwardRef`

**Comment by shlomitc** [comment]
Related to this issue https://github.com/wix/wix-style-react/issues/2582
Will be fixed when tooltip implementation will be replaced by new popper mechanism

**Comment by mykas** [comment]
Fixed in the next generation Tooltip. https://wix-wix-style-react.surge.sh/?selectedKind=7.%20Tooltip&selectedStory=7.1%20Tooltip&full=0&addons=0&stories=1&panelRight=0
