### ISSUE TITLE
Page - Conditional inline rendering

### ISSUE THREAD

**Issue by varzager** [wix/wix-style-react#2971]
There is an issue i keep on facing:
u  enforce allowed children in some of the components.

**for example: `<Page>` can have only one of the `Page.Content`, `Page.Header` etc.**

but they don't support Conditional inline rendering - 
like this:`shouldHaveThis && <Page.FixedContent>`.
 so i get warnings 😞 and add redundant code to overcome that.

would be great if there would be a cross solution for this

thanks 🙏

**Comment by shlomitc** [comment]
@hepiyellow WDYT about it?

**Comment by hepiyellow** [comment]
I’m good with it. If a child is false we can ignore the validation. 

PR welcome.

**Comment by shlomitc** [comment]
done
