### ISSUE TITLE
`<Page/>` (Docs) - Page Layout Story Issues

### ISSUE THREAD

**Issue by hepiyellow** [wix/wix-style-react#2983]
### Page related

My additions: (erez)
- [ ] With Table
- [ ] With Tail (Tabs)
- [ ] With Stretch

#### Description
- Should we have a `2.0 App Layout` (which is similar to BM)
- Do we want to mention features: Scroll V&H, mini-header, sticky?

- [ ] remove comments imports
- [ ] Remove BM sentnce

**Comment by shlomitc** [comment]
will re-open when defined. for now, it is not actionable
