### ISSUE TITLE
Docs template - Issues / Decissions

### ISSUE THREAD

**Issue by hepiyellow** [wix/wix-style-react#2984]
#### General
- [ ] Max-width is 1161 instead of 966 according to the UX spec

#### Header
- [x] Doesn't look like the specs, need to implement it in storybook-utils (@NitayRabi)

#### Included component:
- [x] Row vertical padding should be smaller

#### Import Example (arijus)
- [x] Copy To Clipboard should be on bottom
- [x] Divider should be 100% width

#### Examples
- [ ] Section Title  with divider and top padding is not standardized (Need a component, section we can reuse)
- [ ] Code: 
  - [x] `Show Code` should be on the bottom
  - [x] Background should be grey and not checkered
  - [ ] Should be able to have NO checkered padding inside code example
- [x] Copy to clipboard should be visible without opening code.
- [ ] Need a clean way to limit CodeExample height (without adding it inside the example)

## Component Stories

- Playground should be last tab

## General Content Guidelines
- In Example variations try to show only what is changing
- Show a box per feature

## Prioritization

- Use Google Analytics (exxclude localhost, and PR)

**Comment by argshook** [comment]
most of the topics raised here are either already fixed or are in progress. me and Domas are in sync regarding design.

also, moved to private https://github.com/wix-private/wix-style-react-playground/issues/22
