### ISSUE TITLE
`<Box/>` - Add `spacing` prop : space between with value (`px, %, ...`)

### ISSUE THREAD

**Issue by hepiyellow** [wix/wix-style-react#2990]
# ✨ Feature Request

### 🔦 Scope

`<Box/>`

### 💁 Explanation

Allow having fixed spacing between items (children)

### 🐾 Possible solution 

```
<Box spacing="tiny"/>
```
- Will render the children with tiny (6px) spacing.
- The `spacing` prop is independent of the `direction` and the `align` props.
- Expect, when `align=space_between` OR `verticalAlign=space_between`, in which case it overrides the `align|alignVertical` prop.

### 👀 Severity

- Low (Medium) - we should reuse this in many components, internally.

**Comment by hepiyellow** [comment]
@nitayneeman @shlomitc

**Comment by EgoziE** [comment]
Moved to Jira - closing
