### ISSUE TITLE
`<TimePicker/>` - input has horizontal scroll

### ISSUE THREAD

**Issue by hepiyellow** [wix/wix-style-react#2992]
# 🐛 Bug Report

### 🏗 Relevant Components

`<TimePicker/>`

### 😯 Current Behavior

Has scroll

### 🤔 Expected Behavior

no scroll

### 👣 Steps to Reproduce

Click digits and drag to right 

### 👀 Severity

-  Low

**Comment by TalZa1810** [comment]
@shlomitc 
I was unable to recreate the issue on my end. 
No Gif or image so I'm not sure what he's referring.

Can I close this?

**Comment by shlomitc** [comment]
please close
