### ISSUE TITLE
<TimeInput /> - Implementation doesn't fit specs

### ISSUE THREAD

**Issue by NitayRabi** [wix/wix-style-react#2993]
# 🐛 Bug Report

### 🏗 Relevant Components

<TimeInput />

...

### 😯 Current Behavior
TimeInput has static width

...

### 🤔 Expected Behavior
TimeInput should fill parent - see specs - 
![image](https://user-images.githubusercontent.com/24541325/53017568-f729f800-3458-11e9-80d4-60ff8d02a25c.png)

<TimeInput />

### 👣 Steps to Reproduce

  - **WSR version**: 6.3.0
  - **Yoshi version**: `...`

### 👀 Severity

Low
- Critical / Major / Low

**Comment by shlomitc** [comment]
The component should be replaced with the `InputTime` that we have in `wix-ui-backoffice`.
When we have the new component, it's default behavior could definitely the expanded width

**Comment by EgoziE** [comment]
Add new prop upgrade
change to 100%
breaking change

**Comment by EgoziE** [comment]
According to UX, spec is outdated - closing
