### ISSUE TITLE
<Badge > - using component produces a Stylable error

### ISSUE THREAD

**Issue by NitayRabi** [wix/wix-style-react#3001]
# 🐛 Bug Report

### 🏗 Relevant Components
<Badge />
...

### 😯 Current Behavior
When using a Badge component in development a stylable error appears in console - 
![image](https://user-images.githubusercontent.com/24541325/53097434-1ba1d500-352a-11e9-8c0d-8f1c2ac219aa.png)

...

### 🤔 Expected Behavior

Using <Badge /> component shouldn't produce any errors.

...

### 👣 Steps to Reproduce

  - **WSR version**: `...`
  - **Yoshi version**: `...`

### 👀 Severity

- Low

**Comment by shlomitc** [comment]
it's not related directly to the component, but to the usage of stylable in some application.
