### ISSUE TITLE
Components inside "Included Components" table are linked incorrectly

### ISSUE THREAD

**Issue by nitayneeman** [wix/wix-style-react#3006]
# 🐛 Bug Report

### 😯 Current Behavior

For all index pages that contain "Included Components", the component links (besides the first) are incorrect. It seems that all of them are mapped to the first component which appears in the list.

For example:
![feb-21-2019 09-16-09](https://user-images.githubusercontent.com/7141972/53150747-eba21280-35b9-11e9-9ae0-eeee5de96b5f.gif)

In the example above, both are linked to `<FormField/>`.

### 🤔 Expected Behavior

Correct links.

**Comment by shlomitc** [comment]
@argshook - maybe related to incorrect `keys` when rendering multiple items?

**Comment by argshook** [comment]
i'll take a look. me and Boris saw a case when links were ok with a click, but not ok with <kbd>cmd</kbd> click, most likely related

**Comment by shlomitc** [comment]
@argshook, this issue still happening and becomes more common as we have more and more such pages
See for example (Page.Header, Card, EmptyState):
https://wix-wix-style-react.surge.sh/?selectedKind=2.%20Layout&selectedStory=2.1%20Page%20Layout&full=0&addons=0&stories=1&panelRight=0

can you please prioritize it?
