### ISSUE TITLE
`<PopoverMenu/>` - Should defaults:  `appendToParent=true`, `zIndex=1`

### ISSUE THREAD

**Issue by hepiyellow** [wix/wix-style-react#3016]
- `appendToParent=true`: I think we always want to have the tooltip content MOVE with the button.
If not, then it'll be appended to body, which is most likey NOT the scrollable container of the page. so when the real scroll container will be scrolled along with the PopoverMenu button, and and opened tooltip  content would stay in its place (becoming detached from it's button.

- `zIndex=1` - well tooltip content should allway go over it's serroundings.

**Comment by shlomitc** [comment]
won't be fixed any time soon - will reopen on request
