### ISSUE TITLE
[Build: Stories] (Feature-Request): Have component stories inside component's folder (`src/`)

### ISSUE THREAD

**Issue by hepiyellow** [wix/wix-style-react#3018]
### Motivation

- **DevExp Convenience**: Simply avoid the need to skip folders when developing a component's story and test stories. Test stories are very much related to the e2e tests we are writing, and it's annoying that they are "so far" away. 
- **StandAlone Components**: Potentially "prepare" for the day when we'll want each component to be a stand-alone package. So puttin everything it needs in one folder is a good start.

@shlomitc Do you support this?

#### Component Folders
Each component has (might have):
- **AutoDocs** story: (with `story.js` suffix e.g. Comp.story.js)
- **Test** story: Doesn't use AutoDocs, so no `story.js` suffix 

#### Storybook build (`stories/index.js`)
We do have a `stories/index.js` which imports all stories, so it acts as an [entry point ](https://github.com/wix/wix-style-react/blob/a470016f295e49e3d4b2ad44a9ad0602be656388/.storybook/config.js#L14) for the storybook build.

So the current structure is:
> For a component named `Comp`

```
src/Comp/Comp.js
src/Comp/Comp.e2e.js
stories/components/Comp/index.story.js
stories/components/Comp/ExampleStory1.js
stories/components/Comp/ExampleStory2.js
stories/components/Comp/CompTestStories.js
stories/components/Comp/TestStory1.js
```
> **Comp.e2e.js**: Runs protractor tests on `stories/components/Comp/index.story.js` and `stories/components/Comp/CompTestStories.js`

The `stories/index.js` would include:
```js
import 'stories/components/Comp/index.story.js';
import 'stories/components/Comp/CompTestStories.js';
```

### Suggested File Structure

So proposed file structure would be:
```
src/Comp/Comp.e2e.js
src/Comp/stories/Comp.story.js
src/Comp/stories/ExampleStory1.js
src/Comp/stories/ExampleStory2.js
src/Comp/stories/CompTestStories.js
```

In this case, `stories/index.js` would have:
```js
import '../src/Comp/stories/Comp.story.js';
import '../src/Comp/stories/CompTestStories.js';
```

### Publishing

Stories should be only part of the storybook build, and not published.

### Implementing this

I guess all that needs to be done is to exclude story file from being tarnspiled.
So just need to update [this `glob](https://github.com/wix/wix-style-react/blob/a470016f295e49e3d4b2ad44a9ad0602be656388/scripts/transpileSrc.js#L54)` to exclude `**/src/**/stories/*`

@yavorsky 
Is that so?

**Comment by argshook** [comment]
let's not overcomplicate things

what i'd like to do is make a simple requirement:
if folder is component, it must include `.story.js` file.

that's it

the concrete structure doesn't really matter, as long as it accommodates to the rule.

having transpiled story is also non issue imo.

not sure @yavorsky needs to do anything here.

**Comment by argshook** [comment]
since #3071 & #3079  are merged, component stories are now under `src/ComponentName/docs`

closing
