### ISSUE TITLE
Can't type characters inside input components in react 16.8.2 where languages are Korean/Japanese/Chinese

### ISSUE THREAD

**Issue by morsh** [wix/wix-style-react#3029]
I got the following bug on Jira:
https://jira.wixpress.com/browse/WOS2-1675
This bug is due to upgrade to React@16.8.2
It happens only when typing on a keyboard in a language like Chinese/Japanese/Korean (languages where you need multiple keyboard strokes to input one character)
This issue is reproducible only on wix-style-react input components, but does not happen in the same dom tree with simple input components.

P.s. reverting to react 16.4.2 solves this issue.

**Comment by shlomitc** [comment]
I see that v16.8.3 of React was just released and fixed a bug that caused inputs to behave indirectly in UMD builds
https://github.com/facebook/react/blob/master/CHANGELOG.md#1683-february-21-2019
Please check latest version and see it is reproduced

**Comment by shlomitc** [comment]
I supposed this was resolved. if not, please re-open
