### ISSUE TITLE
<Input/> UniDriver

### ISSUE THREAD

**Issue by mosheKerbel** [wix/wix-style-react#3035]
Input.uni.driver was developed as part of the input.spec.js migration to unidriver.
The following functions were not part of the test, hence they were not added to the input.uni.driver, but should be:

- [ ] startComposing
- [ ] endComposing
- [ ]  hasRightBorderRadius
- [ ]  hasLeftBorderRadius
 - [ ] isOfSize
 - [ ] getCustomAffix
- [ ]  getDataHook
- [ ]  getTooltipDataHook
- [ ]  getTooltipElement
- [ ]  clearText
- [ ]  mouseOut
- [ ]  mouseOver

**Comment by shlomitc** [comment]
I think this is ok that there's no 1-1 match for these drivers as they're not critical for behavior testing, so I'm closing this issue
