### ISSUE TITLE
<Input/> invaild props status

### ISSUE THREAD

**Issue by tuantq10** [wix/wix-style-react#3044]
### 🛠 Relevant Components
[`<input />`]

### 😌 Current Behavior
Set empty `status` at first render component! => console log alert expected one of ["error", "loading"].

### 😉 Expected Behavior
Allow input empty `status`

 * **WSR version**: `6.6.1`

###  👀 Severity
ASAP

**Comment by argshook** [comment]
Hello!

`status` property has a propType validation: `PropTypes.oneOf([Input.StatusError, Input.StatusLoading])`, which yields the error you define.

if you don't need `status`, then don't define `status` property at all

**Comment by tuantq10** [comment]
Dear @argshookm, Thank you for your reply

Yep! The purpose defined props `status` at first render that i need to validate after submit. If error => error or not!

**Comment by argshook** [comment]
hmm, i'm not sure i fully understand if there's an issue or not :)

could you provide a small code example of what you are trying to do and what behaviour you expect? 
you can use this playground (click `show code` on bottom right) https://wix-wix-style-react.surge.sh/?selectedKind=Introduction&selectedStory=Playground&full=0&addons=0&stories=1&panelRight=0 and just paste code here in comment

or this codesandbox (https://codesandbox.io/s/7w8m804o5j) if example is more complex

**Comment by tuantq10** [comment]
sorry for my short explaination!

My opinion that, after click submit form, i would like to validate data of `<Input />`. For ex: check null, email, bla.... So, if the data in that field not correct => I have to change state of `<Input/>` status from `Empty` => `Error`. But in the first time render `<Input/>`. The props `status` have to be set `empty string` => that is problem, when show `Inspect` => alert expected one of ["error", "loading"]. That this case, component still working but i just expected props `status` except `empty string`.

**Comment by argshook** [comment]
> The props `status` have to be set `empty string`

why does it have to be set to empty string? what kind of status is empty string?

what i think you wish for is to not have status at all. in that case, well, don't set `status` prop

i don't know your code, there are multiple ways to do that. if you're unable to remove `status` prop, then you can set it to `undefined`

`<Input status={undefined}/>`

this is a verbose way of not setting `status` prop

**Comment by tuantq10** [comment]
🤔 Could you please tell me how to resolve my problem? 

At the first time render component `<Input/>`:

<img width="454" alt="screen shot 2019-02-27 at 23 32 27" src="https://user-images.githubusercontent.com/46707519/53506258-30f99f00-3ae8-11e9-84a4-6f08e9598ee7.png">

And show this status when data error:

<img width="448" alt="screen shot 2019-02-27 at 23 33 01" src="https://user-images.githubusercontent.com/46707519/53506278-3e168e00-3ae8-11e9-97b3-9f875331f42c.png">

**Comment by argshook** [comment]
> Could you please tell me how to resolve my problem?

my man, i'm happy to help but it's hard to understand what exactly is
the problem without seeing any code.

from what i gather in this thread, it seems really trivial:

```js
class MyThing extends React.Component {
  constructor(props) {
    super(props);

    this.state = {
      status: undefined
    }
  }

  render() {
    return (
      <div>
        <Input status={this.state.status}/>

        <Button onClick={() => this.setState({ status: 'error' })}>Set Error</Button>
        <Button onClick={() => this.setState({ status: undefined })}>Remove Error</Button>
      </div>
    )
  }
}
```

is that really something you are trying to do?

---

> At the first time render component `<Input/>`

what is first time? where, how do you render?

> And show this status when data error:

what do you mean "when data error"? when is the "when"?  what is data error?

please show some code so that i can understand what you try to do and
what's happening. otherwise i can't really help, it's a guesswork.

**Comment by tuantq10** [comment]
> ```js
> class MyThing extends React.Component {
>   constructor(props) {
>     super(props);
> 
>     this.state = {
>       status: undefined
>     }
>   }
> 
>   render() {
>     return (
>       <div>
>         <Input status={this.state.status}/>
> 
>         <Button onClick={() => this.setState({ status: 'error' })}>Set Error</Button>
>         <Button onClick={() => this.setState({ status: undefined })}>Remove Error</Button>
>       </div>
>     )
>   }
> }
> ```
> 
> is that really something you are trying to do?

Thanks @argshook! you solve my problem. My mistake :(. I set props status `"undefined"` as text instead `undefined`.

**Comment by argshook** [comment]
there we go, im happy you got it solved :)
