### ISSUE TITLE
<NumberInput > should allow locale parsing methods

### ISSUE THREAD

**Issue by NitayRabi** [wix/wix-style-react#3057]
# ✨ Feature Request

### 🔦 Scope
Due to changes in numeric display in different locales <NumberInput> should support a `parse` prop to support locales.

...

### 💁 Explanation
Passing a parse function to <NumberInput>
for e.g - https://github.com/AndreasPizsa/parse-decimal-number
and usage e.g - https://github.com/vlad-ignatov/react-numeric-input/blob/79874ccbe2293873300953f32d91f2d70d32a871/src/NumericInput.jsx#L444
...

### 🐾 Possible solution 

...

### 👀 Severity

- Critical / Major / Low

**Comment by shlomitc** [comment]
won't be added any time soon - will reopen on request
