### ISSUE TITLE
Adding clickOutsideTriggers to Tooltip component  

### ISSUE THREAD

**Issue by adirou** [wix/wix-style-react#3063]
# ✨ Feature Request
Adding clickOutsideTriggers to Tooltip component  
### 🔦 Scope

It's about Tooltip component
...

### 💁 Explanation
we at workflows need that onClickOutside property will be invoked  when 'mousedown' , 'touchstart'  events fired. 

Therefor adding  the following property will be great 
clickOutsideTriggers which set the the trigger from the set [ 'click' , 'mousedown' ]
...

### 🐾 Possible solution 

...

### 👀 Severity

Major
- Critical / Major / Low

**Comment by argshook** [comment]
> we at workflows need that onClickOutside property will be invoked when 'mousedown' , 'touchstart' events fired.

what is that needed, what's the use case?

currently `onClickOutside` should be invoked for `mouseup` and `touchend` events. does that not work for you?

**Comment by adirou** [comment]
we use drag and drop components, and therefor when we drag (before the drop) it's not trigger the on clickoutside, which important for us inorder to close a card before the drop

**Comment by argshook** [comment]
discussed use case in private, turns out Tooltip doesn't play here at all, what resolved the issue was usage of https://github.com/Pomax/react-onclickoutside
