### ISSUE TITLE
Upgrade date-fns to ver. 2.0 (alpha)

### ISSUE THREAD

**Issue by NitayRabi** [wix/wix-style-react#3081]
# ✨ Feature Request

### 🔦 Scope

- Refactor (Some API changes)

### 💁 Explanation

- Upgrading `date-fns` will allow us to get rid of `moment` and reduce bundle size.
- Main change is format <-> parse functionality which is not fully supported in current version (parse only supports ISO format).
### 🐾 Possible solution 

- Install latest `date-fns` version
- Rename all imports from snake_case to camelCase 
- Review breaking changes on methods (e.g - [parse](https://date-fns.org/v2.0.0-alpha.27/docs/parse) )
- Validate no degradations

### 👀 Severity

- Critical / Major / Low

**Comment by argshook** [comment]
Fyi #1857

**Comment by argshook** [comment]
> Upgrading date-fns will allow us to get rid of moment and reduce bundle size.

Unfortunately that's not entirely true, cause iirc TimePicker still requires moment, it should also be updated if we want to get rid of moment.

**Comment by NitayRabi** [comment]
Duplicate of #1857

**Comment by NitayRabi** [comment]
> > Upgrading date-fns will allow us to get rid of moment and reduce bundle size.
> 
> Unfortunately that's not entirely true, cause iirc TimePicker still requires moment, it should also be updated if we want to get rid of moment.

The meaning is that date-fns@2.0.0 has the ability to replace moment, of course replacing moment's usage is a task (maybe in the same scope maybe in another separate task)

**Comment by argshook** [comment]
just fyi, the idea to remove moment.js is from long ago

related https://github.com/wix/wix-style-react/issues/926

**Comment by shlomitc** [comment]
We plan to rework on all date and time components in the upcoming months, including doing performance optimizations and internationalization.
I'm closing the issue to clean old stuff from the backlog.
