### ISSUE TITLE
`<Page.Sticky/>` - Has higher `zIndex` then the BM's User Popover

### ISSUE THREAD

**Issue by hepiyellow** [wix/wix-style-react#3083]
### The Issue

@varzager Can you also share a link to production (with feature-toggle or static override details on how to reproduce)

>The lovely Island with birds and a palm tree in the below image, is a `<Page/>` content with `position: sticky` and a very high `zIndex` (11000).

![image (2)](https://user-images.githubusercontent.com/6338722/54089828-e690e180-4375-11e9-8c15-2cf179959a75.png)

### Solution

Either we coordinate `zIndex`-s with BM.
OR
Is there a way to isolate Stacking context so that BM will always be on top of the Page's content?

**Comment by varzager** [comment]
why does the `z-index` of `<Page.Sticky />` have to be so high? BM header is `2000`. 
cant it just be lower?

**Comment by hepiyellow** [comment]
Because our tooltip has zIndex 10000

We need to re-arrange all zIndice in WSR

**Comment by hepiyellow** [comment]
@varzager FYI
