### ISSUE TITLE
Page Header enzyme Testkit doesnt work in upgraded page

### ISSUE THREAD

**Issue by varzager** [wix/wix-style-react#3088]
can't find `page.header` by dataHook using `pageHeaderTestkitFactory` with `<Page upgrade>`
(`import {pageHeaderTestkitFactory} from 'wix-style-react/dist/testkit/enzyme';`)

it resolves when i remove the `upgrade` from page.

it is related to the new page(`<Page upgrade>`).

i have `xit` tests waiting for this to be resolved 😢

**Comment by hepiyellow** [comment]
@varzager Can you share a link to your repo? To the test which is skipped.
(And instruction on how to build and reproduce)

**Comment by varzager** [comment]
https://github.com/wix-private/ecom/blob/bc31368cf3f0e6aac513a8d32102cb527a9a448b/client/wixstores-dashboard/wixstores-dashboard-abandoned-carts/src/components/Main/Main.spec.ts#L23

npm i && npm t

**Comment by nitayneeman** [comment]
@hepiyellow Maybe you'd have any clue...

For a reason, the children of `.titleColumn` aren't rendered properly. The HTML element that enzymeTestkitFactoryCreator sends to the driverFactory is:
```html
<div class="header">
  <div>
    <div class="breadcrumbsContainer absolute minimized" data-hook="page-header-breadcrumbs">
      <div class="medium onGrayBackground">
        <div class="itemContainer active">
          <button
            type="button"
            data-hook="breadcrumb-clickable"
            class="item button itemFullWidth active"
          >
            <span
              data-text1237134500-size="small"
              data-text1237134500-skin="standard"
              data-text1237134500-weight="normal"
              class="Text1237134500--root"
              data-hook="breadcrumbs-item"
              >__mock_translation__e146abandonedCarts.title</span
            >
          </button>
        </div>
      </div>
    </div>
  </div>
  <div class="titleContainer minimized">
    <div class="titleColumn">
<!-- WHERE ARE THE RENDERED ELEMENTS? -->
      <div></div>
      <div></div>
<!-- -------------------------------- -->
    </div>
  </div>
</div>
<div class="actionsBar minimized" data-hook="page-header-actionbar">
  <button
    type="button"
    class="button icon-greybackground"
    style="display: inline-block;"
    data-content-hook="tooltip-content--1"
    data-hook="popover-menu"
  >
    <div class="inner">
      <svg viewBox="0 0 24 24" fill="currentColor" width="24" height="24">
        <path
          d="M6,12.5 C6,11.6715729 6.66579723,11 7.5,11 C8.32842712,11 9,11.6657972 9,12.5 C9,13.3284271 8.33420277,14 7.5,14 C6.67157288,14 6,13.3342028 6,12.5 Z M11,12.5 C11,11.6715729 11.6657972,11 12.5,11 C13.3284271,11 14,11.6657972 14,12.5 C14,13.3284271 13.3342028,14 12.5,14 C11.6715729,14 11,13.3342028 11,12.5 Z M16,12.5 C16,11.6715729 16.6657972,11 17.5,11 C18.3284271,11 19,11.6657972 19,12.5 C19,13.3284271 18.3342028,14 17.5,14 C16.6715729,14 16,13.3342028 16,12.5 Z"
        ></path>
      </svg>
    </div>
  </button>
</div>
```


As we can see, it doesn't render the children of `.titleColumn` at all, and definitely there's no element with `page-header-title` dataHook.

This is the relevant part of the wrapper element which is passed to the driver:

```html
        <Page
          upgrade
          maxWidth={MaxPageWidth}
          minWidth={MinWidth}
          scrollableContentRef={pageRef => !this.state.pageRef && this.setState({pageRef})}>
          <Page.Header
            title={localeKeys.abandonedCarts.title()}
            subtitle={
              <>
                <span data-hook="header-subtitle">{localeKeys.abandonedCarts.subtitle()}</span>{' '}
                <a
                  href={localeKeys.abandonedCarts.learnMoreURL()}
                  data-hook="header-subtitle-link"
                  onClick={() => biLogger.acClickLearnMore({origin: abandonedCartsStore.getFlowType()})}>
                  {localeKeys.abandonedCarts.learnMoreLink()}
                </a>
              </>
            }
            actionsBar={<HeaderActionsBar />}
            dataHook="page-header"
          />
```

It's a bit weird, but if we move the `dataHook="page-header"` attribute to Page (instead of Page.Header), the test actually passes.

**Comment by hepiyellow** [comment]
Clue number 1, what i did, is that when PageHeader receives an upgrade=true, then all animations are disabled. 

Clue number 2, when PageHeader is minimized, than the title is not displayed.

**Comment by varzager** [comment]
Found a workaround - 
Apparently it's caused because there are 2 "duplicate" `page header`'s in `page upgrade`
https://github.com/wix-private/ecom/commit/ff6d6858eaa8eca7b7c8550528b504547962f78e

Possible solution:
`pageHeaderTestkitFactory` should select one of the headers

**Comment by hepiyellow** [comment]
Possible solutions:
1.  Remove data-hook from second minimized-header
2. Try and avoid having 2 PageHEaders in the first place.

@varzager 
I am investigating the 2nd option

**Comment by hepiyellow** [comment]
Actually, Let go with the 1st solution. And investigate later.
