### ISSUE TITLE
<Dropdown /> - click of footer trigger onSelect callback

### ISSUE THREAD

**Issue by BrooklynKing** [wix/wix-style-react#3089]
# 🐛 Bug Report

### 🏗 Relevant Components

`<Dropdown />`

### 😯 Current Behavior

Click on footer, created with `{id: 'footer'}` as option, triggers `onSelect` callback

### 🤔 Expected Behavior

Clicks on footer should be ignored

### 👣 Steps to Reproduce

Add footer via option `{id: 'footer'}`
https://codesandbox.io/s/6xj56kqxmw

### 👀 Severity

Major

**Comment by gilmeir** [comment]
@BrooklynKing 
Here's an example for a dropdown with a footer using fixedFooter https://codesandbox.io/s/ovl2n4zqx6, any chance this provides you with what you need?

I see an example with { id: 'footer' } in our docs, we're gonna remove that from the docs.

**Comment by BrooklynKing** [comment]
@gilmeir it will be enough for now, thx
