### ISSUE TITLE
Error when using with webpack hot loading

### ISSUE THREAD

**Issue by tomenden** [wix/wix-style-react#309]
The error thrown - `Can't make class default hot reloadable due to being read-only`

This is happening due to `export {default as X}`, as here - https://github.com/wix/wix-style-react/blob/master/src/index.js#L5. 

See similar issue -  https://github.com/gaearon/react-hot-loader/issues/158.

It seems like the issue can be resolved pretty easily, by simply exporting directly.
E.g - `export {default as X} from 'a'` -> `export x from a`

![screen shot 2017-02-26 at 1 02 56 pm](https://cloud.githubusercontent.com/assets/8851265/23339127/147e6216-fc24-11e6-9b4a-fd5a3cd51de1.png)

**Comment by lbelinsk** [comment]
@tomenden is this still relevant?
