### ISSUE TITLE
ImageViewer - picture fit is different Chrome vs Firefox

### ISSUE THREAD

**Issue by amitdahan** [wix/wix-style-react#3091]
# 🐛 Bug Report

### 🏗 Relevant Components
`<ImageViewer />`

### 😯 Current Behavior
Consider the following:
```
<MediaPicker
  dataHook="setup-business-logo-picker"
  width={132}
  height={132}
  value="https://static.wixstatic.com/media/7175d1_bc0f6b3c4f43485aa99f0bcceaaea740~mv2.png"
/>
```

#### Chrome:
"Locks" the `<img />` tag inside a 132x132 box, and the `<img />` tag has no `object-fit` definition, so the image gets stretched to fill the box as seen here:
![image](https://user-images.githubusercontent.com/9748762/54186589-6624ca80-44b4-11e9-9617-44af1c4504c8.png)

#### Firefox:
The `<img />` is contained in a 132x132 box, but is only constrained by height, so width grows to accomodate the image's aspect ratio, so the expected behavior of the image filling the box but without distortion as seen here:
![image](https://user-images.githubusercontent.com/9748762/54186694-a08e6780-44b4-11e9-8eb9-9e0b8c890677.png)

### 🤔 Expected Behavior
I believe Firefox shows the expected behavior.

### 👣 Steps to Reproduce
  - **WSR version**: `6.7.3`
  - **Yoshi version**: `4.alpha.6`

### 👀 Severity
Seems to be **Low**, but we had a bug opened for this.

### ✅ Proposed solution
I experimented with normalizing behavior across browsers and found that setting the following styles on the `<img />` tag achieves consistent behavior:
```
img {
  width: 100%; // previously only height: 100% was set
  object-fit: cover;
}
```

**Comment by amitdahan** [comment]
(Can push a PR for this if desirable)

**Comment by argshook** [comment]
> (Can push a PR for this if desirable)

yes please, that's always encouraged :)
