### ISSUE TITLE
RTL ToggleSwitch is backwards

### ISSUE THREAD

**Issue by dleshem** [wix/wix-style-react#310]
In LTR, ToggleSwitch is left when "off", and right when "on", i.e. the switch moves towards the "end" when activated.

The same logic means that in RTL is should be right when "off", and left when "on" - which is currently not the case.

**Comment by dleshem** [comment]
This looks unnatural in RTL, e.g. see this: https://i.imgur.com/WVs9k4r.png

**Comment by nirhart** [comment]
Fixed, just use some parent div with "rtl" class like you used to
