### ISSUE TITLE
TimePicker locale based defaults

### ISSUE THREAD

**Issue by yambtz** [wix/wix-style-react#3102]
# ✨ Feature Request

### 🔦 Scope

TimePicker component
...

### 💁 Explanation

the ampm/24h mode should have a default behavior based on locale. for some locale am/pm makes no sense, for others 24h.

...

the component should check the user locale and use an appropriate default. a prop should allow overriding this behaviour

**Comment by yambtz** [comment]
the reason we think it should be in the component is uniformity - if a site owner sees different time formats in different areas of the site it looks kind of amateur. one of the reasons we have WSR is for the uniform back office experience.

**Comment by shlomitc** [comment]
You’re correct when talking about the uniform look and feel, however the library doesn’t come with a localization solution, same as it doesn’t supply translations solutions.

As a company - I agree we should have best practices / common libraries / HOCs to unify those cases, but I don’t think it should be part of the open source components
