### ISSUE TITLE
Tooltip min-width is too big

### ISSUE THREAD

**Issue by alonbt** [wix/wix-style-react#311]
If I want to make short tooltips like 'Replace' or 'Delete' then the min-width of the tooltip is too big and the word will not align.

Here is how I used it:

`            <Tooltip
                     placement="top"
                     alignment="center"
                     content="Replace"
                     active={true}
                     showDelay={0}
                     hideDelay={0}>`

The inner class I saw in console is `._-node_modules-wix-style-react-dist-src-Tooltip-TooltipContent__tooltip__r1c1h` and it has a value of min-width: 72px; if it could be customizable or just changed to a much lower value that can be great.

**Comment by nirhart** [comment]
min-width removed
