### ISSUE TITLE
Missing GoogleAddressInput driver

### ISSUE THREAD

**Issue by yaelz** [wix/wix-style-react#3117]
# ✨ Feature Request

### 🔦 Scope

We'd like to have a testkit/driver for <GoogleAddressInput/> which is missing
...

### 💁 Explanation

When using <GoogleAddressInput/> we, as users, need to test it. For that purpose, a driver would be best so that not all users should mock the Google Client API etc.

### 🐾 Possible solution 

...

### 👀 Severity

Major

**Comment by shlomitc** [comment]
Hey, I'm closing the issue as we don't plan to work on it in the near future, but we will be happy for your contribution.
thanks
