### ISSUE TITLE
Close Button Icon is off the Center

### ISSUE THREAD

**Issue by ZilvinasMaciulis** [wix/wix-style-react#3120]
Bug Report

Bussines Manage>Customer Management>Contact List>New Contact

The icon in the Close Button of the modal is off the center. See the image.

Chrome

Priority: Low

![image](https://user-images.githubusercontent.com/44393332/54542028-b4016d00-49a3-11e9-8dcd-9acd798cb9f4.png)

**Comment by shlomitc** [comment]
This is not a wix-style-react component but rather an angular version of it, so I'm closing.
In general - it's always good to look in our storybook and search for the exact component. if it looks good there but not in the project, it's probably not our component.
