### ISSUE TITLE
`<Modal/>` - zIndex is too low

### ISSUE THREAD

**Issue by hepiyellow** [wix/wix-style-react#3123]
`Modal` zIndex is 11
While the BusinessManager's header zIndex is 2000.

The Modal's opacity-overlay should be displayed above the BM's header.

### Workaround
Consumers can pass a `zIndex` prop to fix this.

### Proper Solution
BM should export a ZIndex map, or an API for opening Modals.
See this [Jira ticket](https://jira.wixpress.com/browse/WOS2-1722)

**Comment by shlomitc** [comment]
won't be fixed any time soon - will reopen on request
