### ISSUE TITLE
<Thumbnail /> replace checkmark icon

### ISSUE THREAD

**Issue by milkyfruit** [wix/wix-style-react#3132]
Two requests to update **[thumbnail](https://wix-wix-style-react.surge.sh/?selectedKind=Components&selectedStory=Thumbnail&full=0&addons=0&stories=1&panelRight=0&activeTab=Description)** component from Shoutouts Composer team (@drasius) :

- [ ] Thumbnail checkmark icon is not by the specs.

Current icon:
![image](https://user-images.githubusercontent.com/1684587/54717049-f1125e80-4b5f-11e9-9c7e-f4496f040af0.png)
Expected icon:
![image](https://user-images.githubusercontent.com/1684587/54717059-f8396c80-4b5f-11e9-890e-3b060b8738d1.png)
Component [should use this svg](https://github.com/wix/wix-ui/blob/master/packages/wix-ui-icons-common/src/system/raw/CheckboxChecked.svg).

- [ ] Update thumbnail's border color to  B00, Alpha 24% when `backgroundImage` prop is enabled.
EDIT: agreed on B00, 24%.

Thumbnail specs:
https://zpl.io/aNKzWJD

**Comment by milkyfruit** [comment]
@drasius @LittleTal

Made a test with B00, 24% and B00, 30% border colors.
Both options look fine to me. You can check it here:
https://drive.google.com/open?id=1ws6SkJsfObcZA1ejhOnX594hd4LqdrYs

**Comment by drasius** [comment]
@milkyfruit I prefer to have it with 24%. 
I think it works well and it is improvement from what we have right now.

**Comment by LittleTal** [comment]
Talked with Roni, we both agree on 24%. 
Thanks @milkyfruit ,@drasius!

**Comment by milkyfruit** [comment]
Cool, let's initiate this then. @drasius could you ask if Wix Promote devs could make a PR? Or let's wait until @shlomitc assigns someone?

**Comment by shlomitc** [comment]
@drasius - please assign one of your devs, as this will assure the feature request is resolved fast. The team will available to review and assist for any technical issues on the way. Thanks.

**Comment by argshook** [comment]
@drasius hello, can you share status? is any promote dev willing to take this?
