### ISSUE TITLE
[Table/Testkit] - Duplicate docs

### ISSUE THREAD

**Issue by hepiyellow** [wix/wix-style-react#3139]
# Documentation Issue

### 🔦 Scope

Relevant Page URL: https://wix-wix-style-react.surge.sh/?selectedKind=10.%20Tables&selectedStory=10.1%20Table&full=0&addons=0&stories=1&panelRight=0&activeTab=Testkit

### 💁 Explanation
The top part is manuall (and out of date probably).
The Bottom part is automated
The Bottom part starts witjh:
Table Testkits
...

### Expected Docs 

Need to reconcile manual docs, and use only autyomated

### 👀 Severity

- [ ] Major
- [x ] Low

**Comment by shlomitc** [comment]
done
