### ISSUE TITLE
`<PopoverMenu/>` : should have root with `position: relative`

### ISSUE THREAD

**Issue by hepiyellow** [wix/wix-style-react#3142]
### The Issue
(Only after [this PR](https://github.com/wix/wix-style-react/pull/3140) is merged)
With the new `<Page/>`, if there is a PopoverMenu in the Header, and you:
- click on the PopoverMenu (to open it)
- Then scroll up so that the minimized header appears

The Popover content moves down, and detaches (visually) from the button).

![Screen Shot 2019-03-21 at 14 17 01](https://user-images.githubusercontent.com/6338722/54751583-0df07580-4be4-11e9-896f-c5c6982eb831.png)

### Analysis
This happens because the Tooltip content has `position: absolute`,
but it's positions ancestor is the PageHeaderContainer, which changes position when it becomes sticky.

### Solution
I think that PopoverMenu should always have a "root" div with `position: absolute`.
Even if the Tooltip is attached to an element ancestor (body or other), we still always want the absolute positioning to be relative to the PopoverMenu button.

**Comment by mosheKerbel** [comment]
no need to change things in the page component
this is fixed with the new popover menu - just need to play with the appendTo values - parent, scrollParent or window. Depends on the sticky situations.

can be closed once this PR is merged:
https://github.com/wix/wix-style-react/pull/3485

**Comment by mykas** [comment]
Fixed.
