### ISSUE TITLE
<IconButton />: svg child is not resized

### ISSUE THREAD

**Issue by ipanasenko** [wix/wix-style-react#3144]
Hi! I'm playing with yoshi4 and it's new feature of importing svg files as react components.

I'm rendering one inside an icon button, and it appears in original size. I think it should be resized to 18/24px, as all other icons from WSR

**Comment by shlomitc** [comment]
all of our icons are already sized correctly, I guess the assets you're using is incorrect

**Comment by ipanasenko** [comment]
I have no problem with icons from WSR. I'm talking about icons that are not available in WSR.

```ts
import { ReactComponent as Logo } from './custom-icon.svg';

<IconButton size="small">
  <Logo />
</IconButton>
```

In this example, Logo gets rendered in its original size

**Comment by shlomitc** [comment]
probably related to the fact that all WSR icons accept `size` prop which is an abstraction over `width` and `height`.
https://github.com/wix/wix-style-react/blob/master/src/IconButton/IconButton.js#L70
I'll accept a PR changing it to `width` and `height` and would prefer this for all icons usages of buttons.

thanks

**Comment by ipanasenko** [comment]
Should I also add support for `width` and `height` to all WSR icons? With `size` prop setting `width` and `height` to same value?

**Comment by ipanasenko** [comment]
We can not change WST icons API at all, but just pass `width` and `height` along `size` from buttons

**Comment by shlomitc** [comment]
AFAIK, they support width and height already

**Comment by ipanasenko** [comment]
PR: https://github.com/wix/wix-style-react/pull/3245

**Comment by shlomitc** [comment]
Merged PR. Will be released in the next version. Thanks!
