### ISSUE TITLE
Search doesn't really support showOptionsIfEmptyInput

### ISSUE THREAD

**Issue by morsh** [wix/wix-style-react#3148]
# 🐛 Bug Report

### 🏗 Relevant Components

<Search />

...

### 😯 Current Behavior

When setting `showOptionsIfEmptyInput` to true, options still don't open when input is empty

...

### 🤔 Expected Behavior

when focusing on search input, search input will show default options

...

### 👣 Steps to Reproduce

provide some basic options and click on the search input

  - **WSR version**: "wix-style-react": "^6.9.0"
  - **Yoshi version**: >4

### 👀 Severity

Major (we need to display 'recommended' and 'recent' when opening search on focus)

- Critical / Major / Low

**Comment by shlomitc** [comment]
merged PR, will be released soon
