### ISSUE TITLE
FloatingHelper Content testkit is not exposed

### ISSUE THREAD

**Issue by eyaleizenberg** [wix/wix-style-react#3158]
# 🐛 Bug Report
Missing testkit for FloatingHelper.Content

### 🏗 Relevant Components
FloatingHelper.Content

...

### 😯 Current Behavior
According to the docs, the testkit for the FloatingHelper.Content is accessed by `floatingHelper.ContentTestkitFactory`, however, that constant is not exposed.

...

### 🤔 Expected Behavior
Properly expose the FloatingHelper.Content testkit.

...

### 👣 Steps to Reproduce
The following code will fail:
import {floatingHelper.ContentTestkitFactory as enzymeFloatingHelper.ContentTestkitFactory} from 'wix-style-react/dist/testkit/enzyme';

  - **WSR version**: `6.10.2`
  - **Yoshi version**: `...`

### 👀 Severity

- Critical / Major / Low

**Comment by gilmeir** [comment]
Hey @eyaleizenberg,
Will floatingHelperDriverFactory.getHelperContentDriver() work for you? [see here](https://github.com/wix/wix-ui-backoffice/blob/master/src/components/FloatingHelper/FloatingHelper.driver.ts#L32).

**Comment by eyaleizenberg** [comment]
Hi @gilmeir 
I am not using this after all...

Thanks anyway
