### ISSUE TITLE
<Button/>/<TextButton> testkit `isButtonDisabled` doesn't work

### ISSUE THREAD

**Issue by NitayRabi** [wix/wix-style-react#3160]
# 🐛 Bug Report

### 🏗 Relevant Components

`<Button/>`
`<TextButton/>`

### 😯 Current Behavior

Using Testkit's `isButtonDisabled` returns `false` even when buttons are disabled 
for e.g using - 
```
await (await (await buttonDriver.element()).getProperty(
            'disabled'
          )).jsonValue()
```
works while `isButtonDisabled` doesn't

### 🤔 Expected Behavior

testKits method should work according to docs description

### 👣 Steps to Reproduce
Create a `<Button disabled>` component and use the testkit to see if it's disabled.

  - **WSR version**: `6.7.3`
  - **Yoshi version**: `3`

### 👀 Severity

- Critical / Major / Low

**Comment by shlomitc** [comment]
I generated a new `yoshi` project with the following code and it passed, so it might be related to your project's configuration

```jsx
import React from 'react';
import { mount } from 'enzyme';
import Button from 'wix-style-react/Button';
import { buttonTestkitFactory } from 'wix-style-react/dist/testkit/enzyme';

describe('App', () => {
  let wrapper;

  afterEach(() => wrapper.unmount());

  it('should pass', async () => {
    const dataHook = 'my-hook';
    wrapper = mount(
      <div>
        <Button disabled dataHook={dataHook}/>
      </div>,
    );

    const driver = buttonTestkitFactory({ wrapper, dataHook });
    expect(await driver.isButtonDisabled()).toBe(true);
  });
});
```

**Comment by shlomitc** [comment]
I've got a hunch it's related to the way stylable is used in your project.
on the one hand - webpack is bundling your app, so it gives some namespace and hash to the css.
on the other hand - your tests are running in node (`@stylable/node` behind the scenes), which uses a different configuration.

It's not confirmed, but I would research in this direction

**Comment by splintor** [comment]
For what it worth, I seem to also run into this problem in http://pullrequest-tc.dev.wixpress.com/viewLog.html?buildId=2467348&buildTypeId=wixos_Wixos

**Comment by ob1** [comment]
@NitayRabi @shlomitc should we expect any progress on this?

**Comment by shlomitc** [comment]
suggested solution - change this line https://github.com/wix/wix-style-react/blob/master/src/Button/Button.uni.driver.js#L21

Instead of checking for the disabled state using the `stylableUtil`, make sure the component adds a `data-disabled` or `aria-disabled` (for better a11y). This will ensure a cross-platform query selector support instead of relying on the stylable runtime utility.

We have this in our backlog but we'll be happy for a contribution of this fix
