### ISSUE TITLE
<EmptyState/> - Missing testkit features.

### ISSUE THREAD

**Issue by NitayRabi** [wix/wix-style-react#3163]
# ✨ Feature Request

### 🔦 Scope

Add `<EmptyState />` (existing component) testkit methods for e2e purposes (Puppeteer!)
### 💁 Explanation

Will allow access to `<EmptyState/>` features similar to existing React testkit

### 🐾 Possible solution 

Migrate TestKit to UniDriver
### 👀 Severity

- Critical / Major / Low

**Comment by mykas** [comment]
Fixed.
