### ISSUE TITLE
`<Page.Header />` - Missing testkit features

### ISSUE THREAD

**Issue by NitayRabi** [wix/wix-style-react#3173]
# ✨ Feature Request

### 🔦 Scope

Add `<Page.Header />` (existing component) testkit methods for e2e purposes (Puppeteer!)
### 💁 Explanation

Will allow access to `<Page.Header />` features similar to existing React testkit

### 🐾 Possible solution 

Migrate TestKit to UniDriver
### 👀 Severity

- Critical / Major / Low

**Comment by shlomitc** [comment]
will be considered as part of the unidriver effort, so no need for a separate issue
