### ISSUE TITLE
`<Notificaiton/>` - Should be displayed over a minimized Page header

### ISSUE THREAD

**Issue by hepiyellow** [wix/wix-style-react#3178]
https://wix-wix-style-react.surge.sh/?selectedKind=Tests%2FComponents%2FPage&selectedStory=11.%20With%20Notification&full=0&addons=0&stories=1&panelRight=0

![Screen Shot 2019-03-26 at 13 20 19](https://user-images.githubusercontent.com/6338722/54993185-f3464400-4fc9-11e9-94fe-ca975ce7d73f.png)

Need to make Notification have a higher zIndex than the Page minimized header

**Comment by shlomitc** [comment]
in the business manager - global notifications should push the content, so I'm closing it due to invalid use case
