### ISSUE TITLE
<Table /> - missing testkit features

### ISSUE THREAD

**Issue by NitayRabi** [wix/wix-style-react#3182]
# ✨ Feature Request

### 🔦 Scope

Add `<Table />` (existing component) testkit methods for e2e purposes (Puppeteer!)
### 💁 Explanation

Will allow access to `<Table />` features similar to existing React testkit (Puppeteer!) 

### 🐾 Possible solution 

Migrate TestKit to UniDriver
### 👀 Severity

- Critical / Major / Low

**Comment by shlomitc** [comment]
will be resolved as part of the unidriver migration for all components
