### ISSUE TITLE
<ToggleSwitch/> Small toggle knob is deformed

### ISSUE THREAD

**Issue by LittleTal** [wix/wix-style-react#3183]
# 🐛 Bug Report

### 🏗 Relevant Components
`<ToggleSwitch/>`

...

### 😯 Current Behavior
Small toggle knob is deformed (looks ellipsis instead of a circle), 
seems like margin and padding values are wrong:
![image](https://user-images.githubusercontent.com/23282301/54997340-27266700-4fd4-11e9-9dba-2a68ed008597.png)
![image](https://user-images.githubusercontent.com/23282301/54997352-30afcf00-4fd4-11e9-8e41-da2bbed0864b.png)

Also circle size is wrong:

![image](https://user-images.githubusercontent.com/23282301/54997606-c77c8b80-4fd4-11e9-8f7b-5594dc4fe7a3.png)

...

### 🤔 Expected Behavior
Toggle knob should look like:
![image](https://user-images.githubusercontent.com/23282301/54998282-6b1a6b80-4fd6-11e9-8143-952d55b0a8b4.png)

![image](https://user-images.githubusercontent.com/23282301/54998377-aa48bc80-4fd6-11e9-93e3-eb6af18334cf.png)
![image](https://user-images.githubusercontent.com/23282301/54998437-cea49900-4fd6-11e9-9d68-c3c6bd1c4007.png)

Link to Zeplin guidelines:
https://zpl.io/aR1n6yz

...

### 👣 Steps to Reproduce

  - **WSR version**: `...`
  - **Yoshi version**: `...`

### 👀 Severity
Low

- Critical / Major / Low

**Comment by gilmeir** [comment]
wix-ui-core: fix knob positioning (1px from edges)
https://github.com/wix/wix-ui/pull/1251

wix-ui-backoffice: fix knob sizes
https://github.com/wix/wix-ui-backoffice/pull/270
