### ISSUE TITLE
<TableActionCell/> & <Page/> - using of non-valid prop `onActionTrigger` for `TableActionCell`

### ISSUE THREAD

**Issue by sidoruk-sv** [wix/wix-style-react#3192]
# Documentation Issue

### 🔦 Scope

Relevant Page URL: 
* [[Page](https://wix-wix-style-react.surge.sh/?selectedKind=Components&selectedStory=Page&full=0&addons=0&stories=1&panelRight=0)] -> `Multiple Tables With Sticky Headers` (https://github.com/wix/wix-style-react/blob/master/src/Page/docs/ExampleStickyTableWithGap.js#L132)
* [[Table](https://wix-wix-style-react.surge.sh/?selectedKind=10.%20Tables&selectedStory=10.1%20Table&full=0&addons=0&stories=1&panelRight=0)] -> `Table with Action Cell (Primary and Secondary Actions)` (https://github.com/wix/wix-style-react/blob/master/src/Table/docs/ActionCellPrimarySecondaryExample.js#L83)

### 💁 Explanation

there is such code:
```
//...
                <TableActionCell
                  dataHook="action-cell-component-secondary"
                  primaryAction={{
                    text: 'Edit',
                    theme: 'fullblue',
                    onActionTrigger: () => primaryAction(rowData),
                  }}
//...
```

There is no such prop `onActionTrigger` (seems like was available on prevouis DataTable component), have to be `onClick`;

### 👀 Severity

- [ ] Major
- [x] Low

**Comment by shlomitc** [comment]
no longer exists in code, closing
