### ISSUE TITLE
Drivers Sanity - Validate that  Driver is created with the proper component's root element

### ISSUE THREAD

**Issue by hepiyellow** [wix/wix-style-react#3205]
### Consumer Error
Consumers may create a testkit and supply the wrong `element: Element`.
Meaning for example:
```js
buttonTestkitFactory({wrapper: myApp, dataHook: myBadHook});
```
In this case, a ButtonDriver is initialized with an `element` which is NOT the root element of a `Button` component. This could lead to unexpected results.

### Nested Drivers Error

In some drivers we create drivers of nested components, and we use the componsing (parent) component's root element as the root of the composed element.
This may have unexpected behaviour.

## Solution

Add a component-type-id on the root element fo each compoennt, e.g.
```js
export const Button = (props)=> {
  return (
    <button data-wsr-comp-name="Button">
       ...
    </button>
  )
}
```

And in the driver, throw proper, informational, error when any of the driver methods is invoked, and the root `element` is not of the correct component-type

**Comment by argshook** [comment]
> In this case, a ButtonDriver is initialized with an element which is NOT the root element of a Button component. This could lead to unexpected results.

when `wrapper` was first introduced, the whole idea was that it can be any element, not necessarily direct parent.

don't think this is an issue, users very often pass non direct parent to `wrapper`. Changing this would be a major breaking change.

It just goes to show how nested drivers is not a good idea, imo

**Comment by EgoziE** [comment]
Closing for lack of public interest
