### ISSUE TITLE
`<Page/>` - Missing Tests

### ISSUE THREAD

**Issue by hepiyellow** [wix/wix-style-react#3206]
#### Missing Tests

- [ ] When the window is resized - stretch vertically should update
- [ ] Horizontal scroll when the window is less than min-width
- [ ] zIndex: 
  - [ ] `should NOT see components with z-index when they go under a sticky item`
  - [ ] Modal should have higher zIndex than sticky
  - [ ] Modal should have higher zIndex than the minimized header

**Comment by shlomitc** [comment]
won't be fixed any time soon - will reopen on request
