### ISSUE TITLE
`<Page/>` (Optimization) - Avoid PageWrapper

### ISSUE THREAD

**Issue by hepiyellow** [wix/wix-style-react#3208]
See if we can eliminate `PageWrapper` outer div,
and unify it with the `page` div.

https://github.com/wix/wix-style-react/blob/6d340e6d1a7c21b92346ad4c8346812e3f1778d7/src/Page/Page.js#L441

**Comment by shlomitc** [comment]
Let's just pass a `height` prop and change the documentation pages accordingly

**Comment by shlomitc** [comment]
done
