### ISSUE TITLE
<Dropdown/> - support mobile native control

### ISSUE THREAD

**Issue by NitayRabi** [wix/wix-style-react#3216]
# ✨ Feature Request

### 🔦 Scope

When using WSR in Mobile view - dropdown should not use popover and use native dropdown behaviour - 

e.g - 
![image](https://user-images.githubusercontent.com/24541325/55314663-45c4ac00-5473-11e9-9758-cb4bfe4528bb.png)

### 💁 Explanation

<Dropdown> should check running context (mobile) and use control accordingly 
### 🐾 Possible solution 

...

### 👀 Severity

- Critical / Major / Low

**Comment by shlomitc** [comment]
Done
