### ISSUE TITLE
<Divider/> - new component

### ISSUE THREAD

**Issue by NitayRabi** [wix/wix-style-react#3217]
# ✨ Feature Request

### 🔦 Scope

Create new `<Divider/>` component similar to `<Card.Divider />` behaviour for layout arrangement
### 💁 Explanation

`<Divider>` would render a full-width (flexible) divider.
### 🐾 Possible solution 

Use `<Card.Divider>` as basis for implementation.

### 👀 Severity

- Critical / Major / Low

**Comment by milkyfruit** [comment]
Current specs: https://zpl.io/25rXp4n
This feature is needed for [the upcoming Wix Stores project.](https://trello.com/c/CdT8XSMd/46-stores-order-page-activity-page)

**Comment by nitayneeman** [comment]
Implemented.

PRs:
https://github.com/wix/wix-style-react/pull/4204
https://github.com/wix/wix-style-react/pull/4209
https://github.com/wix/wix-style-react/pull/4210
https://github.com/wix/wix-style-react/pull/4211
