### ISSUE TITLE
<Tabs> - support full width + x scroll

### ISSUE THREAD

**Issue by NitayRabi** [wix/wix-style-react#3218]
# ✨ Feature Request

### 🔦 Scope

`<Tabs>` component should support x-scroll for mobile behaviour. 

### 💁 Explanation

In mobile view - tabs might be longer then container, should support - 
- Full width of containing element
- X-scroll (Considering containing element might be the scrolled element)

### 🐾 Possible solution 

- add `fullWidth` prop
### 👀 Severity

- Critical / Major / Low

**Comment by shlomitc** [comment]
won't be developed soon, so I'm closing
