### ISSUE TITLE
<Pagination/> - New component

### ISSUE THREAD

**Issue by NitayRabi** [wix/wix-style-react#3221]
# ✨ Feature Request

### 🔦 Scope

- Create new `<Pagination/>` component (can be used in composition with table/page)
- @milkyfruit - Your opinion? see [Arena new design](zpl.io/a8pjJMx)
### 💁 Explanation

Should support page list (with ellipsis).
Should support following events- 
- Clicking on page number
- Clicking on back/next page
- Clicking on first/last page

### 👀 Severity

- Critical / Major / Low

**Comment by milkyfruit** [comment]
@NitayRabi there already was an effort to develop pagination component in the past:
https://github.com/wix/wix-style-react/pull/2281
Its design was followed by the needs of Wix Blog product: https://zpl.io/bAEr6v8
However, the proper guidelines aren't designed.

**Comment by milkyfruit** [comment]
Wix Arena's pagination can be live previewed here: https://www.wix.com/experts-arena/explore
It is build based on this: https://github.com/AdeleD/react-paginate

**Comment by shlomitc** [comment]
no requirement at the moment, closing
