### ISSUE TITLE
Tooltip in Modal is not shown

### ISSUE THREAD

**Issue by hepiyellow** [wix/wix-style-react#3226]
# 🐛 Bug Report

### 🏗 Relevant Components

Tooltip, Modal

### 😯 Current Behavior

When rendering `<Tooltip/>` in `<Modal/>`, it is not shown.
The reason is that the Tooltip has a lower zIndex than the Modal, and the Tooltip is rendered onto the body by default.

### 🤔 Expected Behavior

Should be visible.

#### Set attachTo 
Use `<Tooltip appendToParent/>`
OR
Use `appendTo` and give it the DOM element of the Modal.

#### Set zIndex

```
<Tooltip zIndex=5010/> // Modal is 5000
```

### Solution 1 (quick fix)

Add a default predicate, that will attach the Tooltip to the Modal.
https://github.com/wix/wix-style-react/blob/e438dcc51626c6e39dd1811aa529db2f24033fda/src/Tooltip/TooltipContainerStrategy.js#L3

### Solution 2 (Cool Infrastructure)

Add an AppendToProvider (React Context Provider), then provides the "base" DOM element that will be used as a default for the `appendTo` prop of both `<Tooltip/>` (legacy), `<Popover/>` (the new guy)

### 👀 Severity

- Major

**Comment by maxaon** [comment]
This affects Video Maker and this is critical for product. Can it be prioritized higher?

**Comment by shlomitc** [comment]
@hepiyellow - please assist solving this ASAP

**Comment by hepiyellow** [comment]
@shlomitc 
Sure I will assist. 
Just to remind you that there are **2 workarounds** for this (mentioned already in the above Issue description).
