### ISSUE TITLE
Update Checkbox teskit to use class hashes

### ISSUE THREAD

**Issue by Oripi** [wix/wix-style-react#3236]
# 🐛 Bug Report

### 🏗 Relevant Components

`Checkbox testkit`

### 😯 Current Behavior

Testkit is using the css classes instead of hashed classes, causing it fail in tests.
### 🤔 Expected Behavior

Use hashed classes just like in this issue:
https://github.com/wix/wix-style-react/pull/3161

### 👣 Steps to Reproduce

  - **WSR version**: `latest`
  - **Yoshi version**: `latest`
 - **Karma version**: `latest`

### 👀 Severity

- Major

**Comment by gilmeir** [comment]
#3286
