### ISSUE TITLE
<InputArea /> support multiple sizes

### ISSUE THREAD

**Issue by milkyfruit** [wix/wix-style-react#3238]
[`<InputArea />`](https://wix-wix-style-react.surge.sh/?selectedKind=Components&selectedStory=InputArea&full=0&addons=0&stories=1&panelRight=0&activeTab=Usage) supports only one size – `medium`.
By [the updated design specs](https://zpl.io/adplw5E), it now supports 3 sizes: `small`, `medium`, `large`.

Wix Stores need size `small` for [the upcoming project.](https://trello.com/c/CdT8XSMd/46-stores-order-page-activity-page)

**Urgency**
Major

**Comment by EgoziE** [comment]
small and medium is already implemented, if large is needed we'll open another issue
