### ISSUE TITLE
`<TextButton>` support size `tiny`

### ISSUE THREAD

**Issue by milkyfruit** [wix/wix-style-react#3239]
[`<TextButton />`](https://wix-wix-style-react.surge.sh/?activeTab=Description&addons=0&full=0&panelRight=0&selectedKind=5.%20Buttons&selectedStory=5.3%20TextButton&stories=1) supports two sizes: `medium` and `small`.
Wix Stores requests to support size `tiny` for [the upcoming project](https://trello.com/c/CdT8XSMd/46-stores-order-page-activity-page).

[Current specs](https://zpl.io/a7Oj8wW) are missing definitions for size:tiny.

- [ ] Update specs(@milkyfruit )
- [ ] Develop (unasigned)

**Urgency**
Major

**UPDATE: Design in Wix Stores changes, I put this request on hold.**

**Comment by shlomitc** [comment]
So I'm closing this one until relevant again

**Comment by dorduch** [comment]
Relevant again

**Comment by dorduch** [comment]
confused with `<IconButton/>`
Closing again

**Comment by LittleTal** [comment]
Currently relevant for the OS team: https://zpl.io/bo843GE

**Comment by TalZa1810** [comment]
Hi @LittleTal ,
Can you please add the definitions to the WSR spec?
https://app.zeplin.io/project/5c8f6f1f9f489505cac756dc/screen/5c90f5f9cf48890dd6bb7cc5

Thanks :)
