### ISSUE TITLE
<NumberInput/> - Add 'strict' mode

### ISSUE THREAD

**Issue by NitayRabi** [wix/wix-style-react#3241]
# ✨ Feature Request

### 🔦 Scope

Add `strict` mode similar to - [react-numeric-input](https://github.com/vlad-ignatov/react-numeric-input#strict-vs-loose-mode)

### 💁 Explanation

- `strict` mode true - user *can't* type beyond `min` `max` constraints
- `strict` mode false - user *can* type beyond `min` `max` constraints (HTML5 default behaviour)
### 🐾 Possible solution 

Implement checking within range if `strict` is on before invoking `onChange`
### 👀 Severity

- Critical / Major / Low

**Comment by shlomitc** [comment]
won't be fixed. closing
