### ISSUE TITLE
`<Page/>` - Page Header is pushed away when scrolled in Safari

### ISSUE THREAD

**Issue by neta-hemyan** [wix/wix-style-react#3243]
# 🐛 Bug Report

### 🏗 Relevant Components

`<Page.Sticky />`

### 😯 Current Behavior

The sticky header doesn't behave as it should on **Safari**

After scrolling for a while, the non-sticky content is shown above the header

...

### 🤔 Expected Behavior

The sticky header should remain on top of the viewport after the page was scrolled.

...

### 👣 Steps to Reproduce

The bug is observable on WSR storybook, using Safari.

https://wix-wix-style-react.surge.sh/?selectedKind=Components&selectedStory=Page&full=0&addons=0&stories=1&panelRight=0&activeTab=Usage

Use case is 

> Multiple Tables With Sticky Headers

### 👀 Severity

Critical (It's currently blocking Price Quotes)

**Comment by hepiyellow** [comment]
I found the cause.
See this simplified scenario.
In Safari the sticky header is pushed away when scrolled. In chrome it doesn't.

https://jsbin.com/fetoviwinu/1/edit?html,css,output

If you remove the `display: flex` from the wrapper, then the issue is resolved.

**Comment by hepiyellow** [comment]
@neta-hemyan 
Do you have your `<Page upgrade/>` under an experiment?
Can you send a link to the page?

**Comment by neta-hemyan** [comment]
It's not under experiment.

the `<Page />`:
https://github.com/wix-private/crm/blob/inv-2222/price-quotes/price-quotes-web/src/components/Root/QuoteSummariesPage/QuoteSummariesPage.tsx

the table using` <Page.Sticky />`: 
https://github.com/wix-private/crm/blob/inv-2222/price-quotes/price-quotes-web/src/components/Root/QuoteSummariesPage/QuoteSummariesTable/QuoteSummariesTable.tsx

related css:
https://github.com/wix-private/crm/blob/inv-2222/price-quotes/price-quotes-web/src/components/Root/QuoteSummariesPage/QuoteSummariesPage.scss

**Comment by neta-hemyan** [comment]
@hepiyellow I just figured out, the problem is not in `<Page.Sticky />`, it's in `<Page.Header />`. `<Page.Sticky />` scrolls just fine, it's the  `<Page.Header />` where `position: sticky` doesn't work. check out other Page Layout examples in the storybook.

**Comment by hepiyellow** [comment]
I know.
The internal PageHeaderContainer is pushed away out of view, when the scroll amount is equal to the hight of the SCrollable container.

**Comment by neta-hemyan** [comment]
How to reproduce with price-quotes-web:
1. clone `crm` for `price-quotes-web`
2. checkout branch `inv-2222`
3. override `price-quotes-web` for local development (server is `http://localhost:3200`)
4.  `npm-run`
5. the bug can be seen when scrolling the front page of Price Quotes

alternatively, in Safari, use Elgar to see the latest RC of `price-quotes-web`, the bug is visible on the fron page.

**Comment by shlomitc** [comment]
fixed
