### ISSUE TITLE
Bug with Input

### ISSUE THREAD

**Issue by lbelinsk** [wix/wix-style-react#325]
I want to update the InputArea (it can be Input also) only if my condition is true.
Since Input isn't fully controlled, although the condition is true and I don't enter to my update func, still the text is being typed.

`<InputArea` 
`  dataHook="notes"`
`  onChange={e => e.target.value.trim().length <= 100 ? this.update('notes', e) : null}`
`  />`

@nirhart

**Comment by lbelinsk** [comment]
@nirhart

**Comment by nirhart** [comment]
Wouldn't that will do the trick?
<Input onChange={e => e.target.value.trim().length <= 10 ? this.update('notes', e) : e.target.value = e.target.value.substr(0, e.target.value.length - 1)}/>

**Comment by lbelinsk** [comment]
This is not a bug, I just simply forgot to provide a value prop so ofCourse it will be uncontrolled.
my bad :)

@nirhart
