### ISSUE TITLE
<InputArea/> allow to disable parts of value

### ISSUE THREAD

**Issue by milkyfruit** [wix/wix-style-react#3256]
# ✨ Feature Request

### 🔦 Scope
I'm not sure

### 💁 Explanation
Wix Events have automated emailing service.
Part of the email message is autogenerated and cannot be changed by a user.
Currently product uses their own developed Angular text area:
![image](https://user-images.githubusercontent.com/1684587/55808231-5e286c80-5aec-11e9-987e-994ce591f0b7.png)

### 🐾 Possible solution 
I suggest extend existing [`<InputArea />` component](https://wix-wix-style-react.surge.sh/?selectedKind=Components&selectedStory=InputArea&full=0&addons=0&stories=1&panelRight=0) to support some kind of markup language.
For example:
![image](https://user-images.githubusercontent.com/1684587/55808689-3f76a580-5aed-11e9-90ca-675e4605af3b.png)

### 👀 Severity
- Major

### Curent Specs
zpl.io/adplw5E
zpl.io/2vxO4Ya

@aarnoldaas is a developer from Wix Events team.
@shlomitc what do you think?

**Comment by aarnoldaas** [comment]
What we have in Angular is very simple solution
Div with fake input styles, textarea without styles that is focused when non editable content is clicked.
<div style={inputBorder}>
  <textarea value={'Editable value'} style={noBorders} />
  <div onClick={focusTextArea}>
    <div>Not Editable values</div>
  </div>
</div>

I don't think this solution fits wix-style-react
Yes we need to send value to server without Non editable content.

**Comment by shlomitc** [comment]
I discussed this with @wuwa and we don't think it's a good solution for this use case. Following this, let's try to suggest a better design instead of implementing this feature. @milkyfruit can you please assist?

**Comment by milkyfruit** [comment]
@shlomitc yes, will contact Angelė to find alternative solutions.
Let's close this issue for now then.
