### ISSUE TITLE
`<Button/>` Testkit - isButtonDisabled() not working

### ISSUE THREAD

**Issue by hepiyellow** [wix/wix-style-react#3274]
`isButtonDisabled` does not work for both Button and TextButton 
(the hash of the wix-ui-core stylesheet class is different in browser and driver (jest+puppeteer) -

repo: https://github.com/wix-private/wix-code-client/tree/master/wix-code-site-monitoring-bm

test that shows it: https://github.com/wix-private/wix-code-client/blob/master/wix-code-site-monitoring-bm/test/e2e/liveLog.spec.js#L326

**Comment by hepiyellow** [comment]
This is an open issue with Yoshi (and Stylable).
See this issue:
https://github.com/wix/yoshi/issues/1189
@idan-at

**Comment by shlomitc** [comment]
duplicate of this https://github.com/wix/wix-style-react/issues/3160
