### ISSUE TITLE
Deprecation messages which I are not my concern and I can't do anything

### ISSUE THREAD

**Issue by zivl** [wix/wix-style-react#3283]
# 🐛 Bug Report

### 😯 Current Behavior

I see those deprecation messages and I’m not sure what’s my part here:
```
DEPRECATED wix-ui-core: Deprecated import path: 
import {avatarDriverFactory} from 'wix-ui-core/drivers/vanilla'. 
avatarDriverFactory is actually a UniDriver. Please import from 'wix-ui-core/drivers/unidriver'
```

I’m not the one that imports directly from `wix-ui-core/drivers/vanilla`
I do the imports as follows:
`import {avatarTestkitFactory} from 'wix-style-react/dist/testkit'`

  - **WSR version**: `^6.x.x`
  - **Yoshi version**: `^3.x.x`

### 👀 Severity

-  Low

**Comment by hepiyellow** [comment]
Should be fixed by :
https://github.com/wix/wix-ui/pull/1260
