### ISSUE TITLE
<Rich Text Area /> adding link to selected text does not work/adds link somewhere else

### ISSUE THREAD

**Issue by dovilel** [wix/wix-style-react#3291]
# 🐛 Bug Report

### 🏗 Relevant Components

Rich Text Area

...

### 😯 Current Behavior

Adding link to selected text does not work as expected. Sometimes it throws error, other times does nothing, yet other times adds link to text AFTER the selected text.

...

### 🤔 Expected Behavior

Adds link to selected text

...

### 👣 Steps to Reproduce

Reproduced on [WSR playground](https://wix-wix-style-react.surge.sh/?selectedKind=Components&selectedStory=Rich%20Text%20Area&full=0&addons=0&stories=1&panelRight=0)

1. Type some text into the rich text area
2. Select all of the text
3. Click to add link
4. Type in some link
5. Click button with check.
Result: Button seems to not work.

![Screen Shot 2019-04-24 at 10 57 16 AM](https://user-images.githubusercontent.com/22763470/56642714-bb8df300-6680-11e9-9d1e-fda24c38a97b.png)

1. Add some more text on that line
2. Select previously selected text
3. Try adding link to it
Result: Link gets added to text after the selected text

![Screen Shot 2019-04-24 at 10 57 41 AM](https://user-images.githubusercontent.com/22763470/56642743-cb0d3c00-6680-11e9-9c14-da624eb2a42a.png)
![Screen Shot 2019-04-24 at 10 57 45 AM](https://user-images.githubusercontent.com/22763470/56642747-cc3e6900-6680-11e9-9e45-5ec22ec4ba80.png)
![Screen Shot 2019-04-24 at 10 57 48 AM](https://user-images.githubusercontent.com/22763470/56642751-ce082c80-6680-11e9-9038-7aec84fa73eb.png)

  - **WSR version**: 6.15.0
  - **Yoshi version**: ?

### 👀 Severity

Low

**Comment by shlomitc** [comment]
Hey, we're moving away from `RichTextArea` component and created a new component `RichTextInputArea`.

The new component is lighter, faster, tested (with driver) and works great with React 16.
It already supports links addition but not editing/removing them yet.

@nitayneeman is working in the upcoming days on feature parity with the old component, meaning that clicking on the link will just remove it.
We would be more than happy for a contribution in this area - so if you can help and add the "edit" functionality, that would be awesome!

**Comment by nitayneeman** [comment]
Hey,

Since WSR v6.18.0 - `RichTextArea` component is deprecated. You should migrate to [`RichTextInputArea`](https://wix-wix-style-react.surge.sh/?selectedKind=Components&selectedStory=RichTextInputArea&full=0&addons=0&stories=1&panelRight=0) instead. 

Either way, the issue you described is fixed in `RichTextInputArea`.

So, I'm closing this issue - please feel free to reopen it if necessary.
