### ISSUE TITLE
<Tooltip  size="smal" /> has incorrect paddings

### ISSUE THREAD

**Issue by milkyfruit** [wix/wix-style-react#3297]
# 🐛 Bug Report

### 🏗 Relevant Components

[<Tooltip />
](https://wix-wix-style-react.surge.sh/?activeTab=Description&addons=0&full=0&panelRight=0&selectedKind=7.%20Tooltip&selectedStory=7.1%20Tooltip&stories=1)
### 😯 Current Behavior

`size="small"` has incorrect paddings.

### 🤔 Expected Behavior

Here are specs for correct paddings:
https://zpl.io/boDpzxW

<img width="280" alt="Screenshot at Apr 26 11-56-59" src="https://user-images.githubusercontent.com/1684587/56796073-7ac9e180-681a-11e9-9383-f4fc39f9218b.png">

### 👀 Severity
Low

@mykas

**Comment by mykas** [comment]
Fixed.
