### ISSUE TITLE
<Dropdown/> - Contact Item Builder is hidden in documentation

### ISSUE THREAD

**Issue by justtal** [wix/wix-style-react#3301]
# Documentation Issue

### 🔦 Scope

Relevant Page URL: https://wix-wix-style-react.surge.sh/?selectedKind=4.%20Selection&selectedStory=4.1%20Dropdown&full=0&addons=0&stories=1&panelRight=0
### 💁 Explanation

  I looked for contact style dropdown and didn't find it. Only after asking in slack.

...

### Expected Docs 

  Under Selection I would expect to see all the dropdown options and builders.

...

### 👀 Severity

- [x] Low

**Comment by EgoziE** [comment]
Moved issue to Jira
