### ISSUE TITLE
TestkitFactory - Assert Driver is created with the Component's root element

### ISSUE THREAD

**Issue by hepiyellow** [wix/wix-style-react#3321]
# ✨ Feature Request

### 🔦 Scope

All Test Drivers (Testkits)

### 💁 Explanation

- Each driver **Is supposed** to receives the component's root element.
- If the driver receives some other element, the results would be unpredictable. (Some methods might  work by coincidence, others might throw an error)
- It can be the `data-hook`, provided by the consumer, finds different element then what the consumer intended.
- It could be that the driver is composing other drivers and passing to them it's own root element, rather than the correct one. (I saw this happen)

### 🐾 Possible solution

- Add a component name/id, as a data attribute on the component's root element. (e.g. `<div data-comp-id="wsr_dropdown">`)
  - Alternatively, we can use the components name as the element's custom HTML tagName. (e.g. `<wsr-dropdown>`)
- In the Driver, check that the given `element` has the appropriate `comp-id`, and throw an informational error if not.

### 👀 Severity

- Low

**Comment by EgoziE** [comment]
Moved to Jira - closing
