### ISSUE TITLE
Table with infinite scroll does not render new page

### ISSUE THREAD

**Issue by shamit6** [wix/wix-style-react#3350]
# 🐛 Bug Report

### 🏗 Relevant Components

DataTable, InfiniteScroll

### 😯 Current Behavior

When scrolling the table until bottom, the loader is still display and we need scrolling it will hide and the new page will render.
...

### 🤔 Expected Behavior

The loader will hide and the new page will render automatically.
...

The problem is in line:
https://github.com/wix/wix-style-react/blob/363a7ad9e50018fdc2aa41a7c12ad029db99cf12/src/DataTable/DataTable.js#L47

**the condition looks redundant to me, 
`nextProps.data[index] === elem` never be true. because my items are mobx computed, and they never have the same ref.

if something is not clear please talk to me.**

### 👣 Steps to Reproduce

scroll the table in:
https://www.wix.com/dashboard/82f32453-f082-405f-a5b9-8e378f7915e0/store/tax/group/a21607ef-61c5-41da-800c-44764ea208c4

src:
https://github.com/wix-private/ecom/tree/master/client/wixstores-dashboard/wixstores-dashboard-tax/src/components/GroupPage/GroupProductsTable

  - **WSR version**: latest
  - **Yoshi version**: ^3.0.0

- Major

**Comment by nitayneeman** [comment]
@shamit6 Regarding reproducing the bug - should I use an experiment in order to see the "Store Tax" link? (I don't see it right now)

**Comment by shamit6** [comment]
ohh, yes

the updated link
https://www.wix.com/dashboard/82f32453-f082-405f-a5b9-8e378f7915e0/store/tax/group/73b5c6a7-3f64-4a42-bb5c-b81b01564b21

experiments: 
specs.stores.TaxPhase2
specs.stores.TaxPhase3  

i already opened PR:
https://github.com/wix/wix-style-react/pull/3457

**Comment by nitayneeman** [comment]
The PR was merged.
Please feel free to reopen if necessary.
