### ISSUE TITLE
DataTableDriver.exists() not working as expected

### ISSUE THREAD

**Issue by yaarams** [wix/wix-style-react#3361]
# 🐛 Bug Report

1. testkit.exists() always returns true due to this: https://github.com/wix/wix-style-react/blob/master/src/DataTable/DataTable.driver.js#L14
2. The testkit is eager. It expects the element to be rendered when constructing the testkit.

### 🏗 Relevant Components

...

### 😯 Current Behavior

...

### 🤔 Expected Behavior

...

### 👣 Steps to Reproduce

  - **WSR version**: `...`
  - **Yoshi version**: `...`

### 👀 Severity

- Critical / Major / Low

**Comment by mosheKerbel** [comment]
fixed and release.
https://github.com/wix/wix-style-react/pull/3367
