### ISSUE TITLE
<More /> Icon - horizontal alignment

### ISSUE THREAD

**Issue by amitdahan** [wix/wix-style-react#3370]
# 🐛 Bug Report

### 🏗 Relevant Components
`import More from 'wix-style-react/new-icons/More';`

### 😯 Current Behavior
It seems to lean to the right:
![image](https://user-images.githubusercontent.com/9748762/57318659-80b99f80-7103-11e9-9a4d-eca7a1e46af9.png)
(Pic taken from the latest docs, in the Icons page)

### 🤔 Expected Behavior
Dots should be aligned to the center.

### 👣 Steps to Reproduce
Use the `More` icon somehow. We use it indirectly by using `PopoverMenu`. Rendering the `More` icon is enough though.

  - **WSR version**: `6.17.3`
  - **Yoshi version**: `4.4.1`

### 👀 Severity
- Low

**Comment by shlomitc** [comment]
should be fixed now, closing

**Comment by amitdahan** [comment]
Thanks @shlomitc !
