### ISSUE TITLE
Tooltip position is wrong if it is used in overflowing (scrollable) div

### ISSUE THREAD

**Issue by D0vydas** [wix/wix-style-react#338]
That's how it looks with `appendToParent` (without using it, tooltip is not visible at all).

![2](https://cloud.githubusercontent.com/assets/6649425/23848879/cb45d56a-07e1-11e7-8563-bc860f3b1cdf.png)

**Comment by nirhart** [comment]
@D0vydas is it still relevant, I tried without appendToParent and it worked fine
