### ISSUE TITLE
NestableList - drag & drop tree with hierarchy

### ISSUE THREAD

**Issue by tzvikaf** [wix/wix-style-react#3390]
the component can display a tree and allow dragging item to become sub items of other items or unsubing them.

the component depends on react-dnd

NestableList has most of the functionality needed to work properly
but new features might be required like:

1. make component completely controlled, not changing the tree internally
2. not allow dragging of specific item,
3. allow dragging item but not subbing it

looks like making it controllable is the best approach

**Comment by shlomitc** [comment]
This won't be handled soon, so I prefer closing and please reopen if you need to implement it.
thanks
