### ISSUE TITLE
<DropdownLayout /> Enable default marking of option

### ISSUE THREAD

**Issue by morsh** [wix/wix-style-react#3401]
# ✨ Feature Request

### 🔦 Scope

<DropdownLayout />
I want to expose a new property that would enable controlled marking an options

...

### 💁 Explanation

This feature is required to enable <InputWithOptions /> to mark the first selectable option when supplying a new set of options.

Part of the problem is that today, when clicking on `Enter` without hovering on any option simply closes the dropdown dialog without selecting any option.

...

### 🐾 Possible solution 

Expose a `defaultHoveredId` that would be used whenever options are changed (instead of state)

...

### 👀 Severity

- Major

**Comment by argshook** [comment]
closed by https://github.com/wix/wix-style-react/pull/3409
