### ISSUE TITLE
<Modal/> - Overlay mouse up event closes modal

### ISSUE THREAD

**Issue by splintor** [wix/wix-style-react#3417]
# 🐛 Bug Report

### 🏗 Relevant Components

Modal

### 😯 Current Behavior

When the user do a mouse down event on the modal content, drag it to the overlay and release the mouse button over the overlay, the modal is closed.

### 🤔 Expected Behavior

The Modal should only close when both mouse down and mouse up occur on the overlay and not on the content.

### 👣 Steps to Reproduce

1. Have a modal that closes when clicking the overlay.
2. Mouse down on the modal content
3. Drag the mouse outside of the modal content.
4. Mouse up on the overlay.

The dialog will be closed.

See https://codesandbox.io/s/rz7wj7knp for a repro project.

Note that this was reported for `react-modal` in https://github.com/reactjs/react-modal/issues/633 and was fixed for version 3.4.1. See https://codesandbox.io/s/28n7w for the same project that uses `react-modal` version `3.4.1` where the problem does not occur. (The problem does occur if you switch to previous version `3.3.2`).

  - **WSR version**: `16.8.4`
  - **Yoshi version**: `^3.0.0`

### 👀 Severity

Low

**Comment by EgoziE** [comment]
@splintor `react-modal` was upgraded to `3.10.1` can you please check if we can close this issue?

**Comment by splintor** [comment]
No, the problem doesn't seem to be fixed...
1. Go to [Modal storybook](https://www.wix-style-react.com/?activeTab=Playground&path=%2Fstory%2Fcomponents-api-components--modal)
1. Select **Playground** tab
1. Click **Open Modal** button
1. Mouse down in the modal area and drag the mouse outside and mouse up on the external overlay.

The dialog should not close in that case, but it is closed.

**Comment by EgoziE** [comment]
Luckily, it's a problem with the Playground and not the component.
Closing.

**Comment by splintor** [comment]
Don't you want to fix the playground? 🤔

**Comment by EgoziE** [comment]
maybe eventually, we're trying to focus on components stability first.
As you can see we migrated all issues to Jira and prioritize them accordingly.
