### ISSUE TITLE
Add theme/skin detection to the button testkit

### ISSUE THREAD

**Issue by eyaleizenberg** [wix/wix-style-react#3421]
# ✨ Feature Request

### 🔦 Scope
The button testkit does not allow to check the theme/skin of the button leaving the component untested especially if you have logic on the button's theme (upgrade button if non-premium, etc).

...

### 💁 Explanation
It's pretty clear - I hope 😄 

...

### 🐾 Possible solution 
Add a `hasTheme` property to the testkit allowing to check all possible themes.

...

### 👀 Severity

Low

**Comment by mykas** [comment]
Hi, I am just wondering why is this even needed? Here in wix-syle-react we test our components style with visual tests instead of checking the classname applied.

**Comment by eyaleizenberg** [comment]
Thank you @TalZa1810 !
