### ISSUE TITLE
<Stepper/> - new component

### ISSUE THREAD

**Issue by shlomitc** [wix/wix-style-react#3427]
# ✨ Feature Request

### 🔦 Scope
`<Stepper/>`

### 💁 Explanation
This new component is required by several projects
https://zpl.io/29wEv5W
![image](https://user-images.githubusercontent.com/6093192/57926637-7726f900-78b4-11e9-9cd2-0662493e5fcc.png)

### 👀 Severity

- Major

**Comment by mosheKerbel** [comment]
@shlomitc can be closed?

**Comment by shlomitc** [comment]
Yes
