### ISSUE TITLE
all components should be exported?

### ISSUE THREAD

**Issue by argshook** [wix/wix-style-react#343]
Most of the components are exported in [index.js](https://github.com/wix/wix-style-react/blob/master/src/index.js) and it's possible to, e.g.: `import { Button } from 'wix-style-react'`.

However, not all components work this way. E.g. you can't `import { Card } from 'wix-style-react`, you have to `import { Card } from 'wix-style-react/src/Grid'`. This means you need to look up the correct path.

i would assume every component found in this lib should be accessible `from 'wix-style-react'`.

if it's true, need to go over all components and make sure they are exported properly.

but maybe there's a reason not all are exported?

**Comment by nirhart** [comment]
Actually, it is better to not use it like this and import Card from 'wix-style-react/dist/src/Card' for now, so it won't import all the library together with your component, once we will solve it, we will add all of the components to index as well

**Comment by argshook** [comment]
@nirhart but this means i need to know and follow file structure, it may change any time.

also, with treeshaking from webpack 2 (which i was told `yoshi` is now using) all library shouldn't appear in bundle, so i'm guessing it's better to `import from 'wix-style-react'`?

**Comment by nirhart** [comment]
there is tree shaking in webpack 2, but yoshi is not using webpack 2 yet

**Comment by nirhart** [comment]
once it will be there we will import everything from 'wix-style-react'
