### ISSUE TITLE
<DropdownLayout/> - option with long continuous text ends up being cropped

### ISSUE THREAD

**Issue by Jefoss** [wix/wix-style-react#3433]
# 🐛 Bug Report

### 🏗 Relevant Components

`DropdownLayout`

### 😯 Current Behavior

When some option has a long continuous text it is getting cropped like this -
![image](https://user-images.githubusercontent.com/19532384/57985143-56090880-7a6c-11e9-9107-cd1ac4296fe9.png)

### 🤔 Expected Behavior

Probably show ellipsis

### 👣 Steps to Reproduce

 just enter a long text as one of the options in the dropdown like in here - 
https://codesandbox.io/s/2zzrr

### 👀 Severity

Low

--------------------------------

Changing the options style from `flex` to `block` seems to work (with ellipsis already) so maybe that will be the easier approach

**Comment by shlomitc** [comment]
@Jefoss - is this coming out of a real use case? what happens when the word is split into two?
It might be an edge case which not worth fixing

**Comment by Jefoss** [comment]
@shlomitc - yeah under some languages its very possible to have long enough options on our app
when a word is split into two you it will break into another line, but still if one of the parts is long enough you will have the same issue..

if the options are not really using the `flex` style, the fix is just changing it to `block`

**Comment by shlomitc** [comment]
@wuwa - according to the "list item select" spec, we don't cover the case of one long word.
Currently - multiple words break a line. The specs say it should be configurable to show ellipsis (not implemented). however, one long word is a mix of both, so what would be the right solution?

![image](https://user-images.githubusercontent.com/6093192/57985601-e1859800-7a72-11e9-92dc-08308a3809d5.png)

**Comment by EgoziE** [comment]
Developed
