### ISSUE TITLE
<DatePicker/> - Exclude current and past dates

### ISSUE THREAD

**Issue by antanaswix** [wix/wix-style-react#3441]
# ✨ Exclude current and past dates

### 🔦 Scope

Exclude current and past dates for the date picker. 

...

### 💁 Explanation

We are adding a feature that will allow users to change the Valid until date for Purchases of Paid Plans app. We need users to select the date which is after the current date and prevent users from selecting past date and current date.

...

### 🐾 Possible solution 

...

### 👀 Severity

We couldn't release this feature.

- Critical

**Comment by shlomitc** [comment]
it is possible with the `filterDate` predicate. I think we should add it to our docs

**Comment by shlomitc** [comment]
did it work out for you?
