### ISSUE TITLE
<EditableSelector> - Tooltip behaviour broken

### ISSUE THREAD

**Issue by NitayRabi** [wix/wix-style-react#3442]
# 🐛 Bug Report

### 🏗 Relevant Components

`<EditableSelector>`
### 😯 Current Behavior

- When the tooltip and hovering on item buttons overflow the tooltip
![image](https://user-images.githubusercontent.com/24541325/58022755-ce2c0880-7b16-11e9-8785-d35e05694686.png)
![image](https://user-images.githubusercontent.com/24541325/58022781-e0a64200-7b16-11e9-874a-9bec01d6462f.png)
- When adding new rows (test page specific case) the tooltip stays in same position covering the button (basically un-closeable)
![image](https://user-images.githubusercontent.com/24541325/58022869-177c5800-7b17-11e9-8d64-30e32f9b05be.png)

### 🤔 Expected Behavior

Tooltip size should contain buttons for editableSelector

### 👣 Steps to Reproduce

- Navigate to  [TestPage](https://wix-wix-style-react.surge.sh/?selectedKind=Tests%2FComponents%2FEditableSelector&selectedStory=editableSelector&full=0&addons=0&stories=1&panelRight=0)
- Click on `Click Me`
- Hover on item
- Click on edit

  - **WSR version**: 6.19.0
  - **Yoshi version**: `...`

### 👀 Severity

- Critical / Major / Low

**Comment by shlomitc** [comment]
This component is old and not used very widely, so won't be fixed
