### ISSUE TITLE
<DropdownBase/> arrow placement is incorrect

### ISSUE THREAD

**Issue by vladik7244** [wix/wix-style-react#3460]
# 🐛 Bug Report

### 🏗 Relevant Components

Popover
DropdownBase

### 😯 Current Behavior

![image](https://user-images.githubusercontent.com/7922368/58240835-74b11d00-7d54-11e9-85df-706d243c82a5.png)

### 🤔 Expected Behavior

![image](https://user-images.githubusercontent.com/7922368/58240860-81ce0c00-7d54-11e9-9a04-6c96fb3627be.png)

The reason is unitless number in calc expression of `top` of the arrow
![image](https://user-images.githubusercontent.com/7922368/58240924-9f02da80-7d54-11e9-8dfd-fdb79d8223a2.png)

### 👣 Steps to Reproduce

I can't reproduce it in codepen because this expression is somehow gets compiled to `2px` there. Also same happens in the storybook. But not in our project https://github.com/wix-private/media-studio
![image](https://user-images.githubusercontent.com/7922368/58242753-0a9a7700-7d58-11e9-85e4-ebfbde9223e7.png)

  - **WSR version**: `6.21.0`
  - **Yoshi version**: `4.5.1`

### 👀 Severity

-  Major

**Comment by shlomitc** [comment]
PR got merged. closing
