### ISSUE TITLE
Export TS types as named string enums

### ISSUE THREAD

**Issue by kranux** [wix/wix-style-react#3465]
Hi, first of all thanks for start providing types. That's amazing!

# ✨ Feature Request

### 🔦 Scope

At the moment you are providing types as string literal unions, for example: 

```ts
export type BoxHorizontalAlignment =
  | 'left'
  | 'center'
  | 'right'
  | 'space-between'; 
```

### 💁 Explanation

Which is cool, but I still need to hardcode these strings in my project.

### 🐾 Possible solution

I suggest exporting types as named string enums in such way:

```ts
export enum BoxHorizontalAlignment {
  left = 'left',
  center = 'center',
  right = 'right',
  spaceBetween = 'space-between',
}
```

I can import it and use in my project:

```tsx
import {BoxHorizontalAlignment} from 'WSR/Box';

/*...*/

<Box align={BoxHorizontalAlignment.left}/>
```

Which helps me to avoid hardcoded strings;

### 👀 Severity

Low

**Comment by shlomitc** [comment]
thanks for the idea, but I think this means just creating additional objects, regardless of the added types (we write js). You're welcome to make PRs adding it, but we probably won't add it to all components.

thanks
