### ISSUE TITLE
`<Slider/>` - pushable handlers get stuck when positioned at the start and end.

### ISSUE THREAD

**Issue by mykas** [wix/wix-style-react#3468]
# 🐛 Bug Report

Pushable Handlers" example feels broken when controlled with a mouse. It gets stuck when knobs gets positioned at the start and end.

### 🏗 Relevant Components

`<Slider/>`

### 😯 Current Behavior

Sometimes while dragging a slider with multiple handlers - one of the knobs get stuck.

### 🤔 Expected Behavior

Should be smooth.

### 👣 Steps to Reproduce

Open storybook API docs for Slider and try play with `Pushable Handlers` example.

### 👀 Severity

- Major

**Comment by shlomitc** [comment]
can't reproduce and we didn't get more complains about it, so closing
