### ISSUE TITLE
<ColorInput/> - remove default placeholder value

### ISSUE THREAD

**Issue by shlomitc** [wix/wix-style-react#3471]
# 🐛 Bug Report

### 🏗 Relevant Components
`<ColorInput/>`

### 😯 Current Behavior
The component currently holds `placeholder: 'Please choose a color'` as a default value.

### 🤔 Expected Behavior
Components should not have any business related values not default values

### 👣 Steps to Reproduce
just render `<ColorInput value=""/>`

### 👀 Severity
Low

**Comment by mykas** [comment]
Fixed.
