### ISSUE TITLE
<Avatar /> - display image on top of the text (name initials) 

### ISSUE THREAD

**Issue by assafganor** [wix/wix-style-react#3478]
# ✨ Feature Request

### 🔦 Scope

I want to suggest displaying the image on top of the Icon Placeholder or Initials Placeholder.
In that way, if the image is blank/transparent there still be something visible.

### 💁 Explanation
Example:
https://www.wix.com/_api/account-info-server/profileimage
returns (if it is not google/facebook account): 
{
profileImage: "https://gravatar.com/avatar/9de5c647d815d89a0d808f939bc30ce1?d=blank"
}

It is a valid image url, but it is blank, so you see nothing.

![Screen Shot 2019-05-28 at 11 34 58](https://user-images.githubusercontent.com/9839921/58463581-cb479e00-813c-11e9-8b27-9ddc6f832345.png)

### 👀 Severity
 Low

**Comment by shlomitc** [comment]
probably more of a UX question rather than a technical one.
I'd say that in that case - the user picked a wrong image but didn't expect the initials to appear.
@milkyfruit what are your thoughts?

**Comment by milkyfruit** [comment]
@assafganor @shlomitc I'm not sure I fully understood the issue.

Right now `<Avatar />` offers 4 states:

Placeholder
![image](https://user-images.githubusercontent.com/1684587/58539446-0d85e380-8200-11e9-8a96-bea05a5b087e.png)

Custom Placeholder
![image](https://user-images.githubusercontent.com/1684587/58539653-766d5b80-8200-11e9-8c31-5e221196748a.png)

Initials
![image](https://user-images.githubusercontent.com/1684587/58539454-12e32e00-8200-11e9-84db-9e92da9aec4f.png)

Image
![image](https://user-images.githubusercontent.com/1684587/58539462-15de1e80-8200-11e9-9724-3dd38ae723de.png)

Every property with given value overrides lower ranked property. Ranking placeholder as the lowest and image as the highest in priority.

Doesn't it already solve the current issue?

**Comment by assafganor** [comment]
@milkyfruit 
Current behavior is that every property that overrides a lower ranked property does it by unmounting the lower one. I suggest that in case of image property, instead of unmounting the lower one you will position the image element on top of the lower one by absolute position and z-index. In that way, if the image URL is valid but the image is blank we still display the lower one.

@shlomitc 
In my case the user didn't pick an image at all, I guess that this is an automatic image that WIX provides. It is really a question if we want to fix users or websites mistakes.....

Currently, as a workaround, I created my own Avatar component based on yours Avatar:
https://github.com/wix-private/experts/blob/master/experts-common/src/components/ExpertsAvatar/ExpertsAvatar.js

**Comment by milkyfruit** [comment]
Thanks, @assafganor. It's clear now, I think it totally makes sense to overlay image on top. Otherwise it would need some mechanism to check if url is valid...

**Comment by shlomitc** [comment]
But then in cases of a `png` image that contains a transparent background on purpose, you might see some part of the initials...
I think that it's not the responsibility of the Avatar to take care of transparent images.

**Comment by shlomitc** [comment]
closing as this behavior will not be applied. thanks for raising it anyway
