### ISSUE TITLE
<RichTextInputArea /> links are not target=_blank anymore, bad interaction with Business Manager

### ISSUE THREAD

**Issue by dovilel** [wix/wix-style-react#3497]
# 🐛 Bug Report

### 🏗 Relevant Components

`<RichTextInputArea />`

### 😯 Current Behavior

If there is a link added to the text area, user clicking on it causes Business Manager to fire an internal navigation event (businessManager.onNavigation).
With the old deprecated component (RichTextArea), links had target=_blank on them, which are not considered by BM to be internal navigation.

The constructed value does have target=_blank in both components.

### 🤔 Expected Behavior

Expect links to have no effect in Business Manager and to be consistent between input area and output value.

### 👣 Steps to Reproduce

Not sure how to give example with BM, since I can't find new RichTextInputAreas there.
Easy way to see behavior that happens:
1. Install Events App.
2. Go to BM -> Events.
3. Click Add Event
4. Scroll to bottom for the old RichTextArea
5. Add a link.
6. Inspect it and remove target="_blank"
7. Click on the link - see popup appearing.

  - **WSR version**: 16.5
  - **Yoshi version**: `...`

### 👀 Severity

- Major

**Comment by argshook** [comment]
closed by #3602, release pending on #3611
