### ISSUE TITLE
make testkit driver framework agnostic

### ISSUE THREAD

**Issue by yanivefraim** [wix/wix-style-react#35]
Driver currently receives an Enzyme wrapper component - we should consider changing it to receive a regular native dom element and not make our users coupled to Enzyme

**Comment by 3LOK** [comment]
... or have a testkit to each framework the users might use - it depends if you can really make the framework agnostic...

**Comment by lbelinsk** [comment]
We support today enzyme, protractor and vanilla (ReactTestUtils).

closing this issue..
