### ISSUE TITLE
<Page/> - the scroll behaves incorrectly when NumberInput or Input with type="number" is used inside

### ISSUE THREAD

**Issue by mykas** [wix/wix-style-react#3518]
# 🐛 Bug Report

NumberInput is being scrolled when mouse wheels is used but mouse is not on NumberInput component.

### 🏗 Relevant Components

`<Page/>`
`<NumberInput/>`
`<Input type="number"/>`

### 😯 Current Behaviour

When user clicks and enters a number in NumberInput or Input with type="number" which is inside the Page component then scrolls the page with mouse wheel - values starts to change.

https://www.screencast.com/t/hISWiGSZ6C

### 🤔 Expected Behaviour

Values inside input should only change when mouse is hovering on top of NumberInput, but not when it is outside.

### 👣 Steps to Reproduce

Install Paid Plans app in wix.com -> press create new plan and try to enter a number inside the NumberInput -> then scroll down.

Or snippet for the playground: 

```jsx
<div style={{ height: '100vh' }}>
  <Page upgrade>
     <Page.Content>     
      <NumberInput/>
    </Page.Content>
 </Page>
</div>
```

### 👀 Severity

- Critical

**Comment by EgoziE** [comment]
fixed
