### ISSUE TITLE
<InputArea/> - error message tooltip is breaking

### ISSUE THREAD

**Issue by mosheKerbel** [wix/wix-style-react#3531]
<img width="135" alt="Screen Shot 2019-06-05 at 14 36 51" src="https://user-images.githubusercontent.com/7388217/58967268-8ebf1680-87bc-11e9-8c22-f09adc9d21c3.png">

Tooltip is appending to parent by default and it does not have enough space to show the content, as a result the tooltip is breaking.

Solution: change tooltip `appendTo` to `window`

**Comment by shlomitc** [comment]
@mykas - I think it’s related to your recent changes

**Comment by mykas** [comment]
Yes, I will update `<ErrorIndicator/>` to append to window by default.
