### ISSUE TITLE
<Popover/> mouseEnter test kit is returning: "requestAnimationFrame is not defined"

### ISSUE THREAD

**Issue by ErezPaperny** [wix/wix-style-react#3542]
# 🐛 Bug Report

### 🏗 Relevant Components
<Popover/> TestKit

### 😯 Current Behavior
mouseEnter() return requestAnimationFrame is not defined

### 🤔 Expected Behavior
To simulate mouseEnter event

### 👣 Steps to Reproduce
      const previewUpgradePopup = popoverTestkitFactory({wrapper: driver.component, dataHook: 'branding-popup'});
      console.log(previewUpgradePopup.exists()); // RETURN TRUE
      await previewUpgradePopup.mouseEnter();  // RETURN Error

  - **WSR version**: `6.25.1`
  - **Yoshi version**: `4.1.0`

### 👀 Severity

Major - Can't build automation ....

**Comment by shlomitc** [comment]
Please try applying the `requestAnimationFramePolyfill` and let me know if it works

```javascript
import { requestAnimationFramePolyfill } from 'wix-style-react/dist/testkit/polyfills';

beforeAll(() => {
  requestAnimationFramePolyfill.install();
});
```

**Comment by shlomitc** [comment]
@ErezPaperny ping?

**Comment by ErezPaperny** [comment]
Yup its resolve the issue thx for the help :-)
