### ISSUE TITLE
<InputWithOptions /> usage of deprecated react api

### ISSUE THREAD

**Issue by morsh** [wix/wix-style-react#3554]
# 🐛 Bug Report

### 🏗 Relevant Components

<InputWithOptions />
...

### 😯 Current Behavior

After adding React.StrictMode to discover issues with the code, the following warnings return from the code:

```
Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of InputWithOptions which is inside StrictMode. Instead, add a ref directly to the element you want to reference.

        in div (created by InputWithOptions)
        in InputWithOptions (created by SearchBox)
        in div (created by SearchBox)
        in SearchBox (created by I18n)
        in I18n (created by Translate(SearchBox))
        in Translate(SearchBox) (created by Context.Consumer)
        in Connect(Translate(SearchBox)) (created by SearchEverythingWidget)
        in StrictMode (created by SearchEverythingWidget)
        in I18nextProvider (created by SearchEverythingWidget)
        in Provider (created by SearchEverythingWidget)
        in SearchEverythingWidget
        in Unknown (created by I18n)
        in I18n (created by Translate(Component))
        in Translate(Component)
        in I18nextProvider
        in Provider (created by WrapperComponent)
        in WrapperComponent

    Learn more about using refs safely here:
    https://fb.me/react-strict-mode-find-node
```

As well as the usage of `componentWillReceiveProps`:

```
Warning: Unsafe lifecycle methods were found within a strict-mode tree:
        in StrictMode (created by SearchEverythingWidget)
        in I18nextProvider (created by SearchEverythingWidget)
        in Provider (created by SearchEverythingWidget)
        in SearchEverythingWidget
        in Unknown (created by I18n)
        in I18n (created by Translate(Component))
        in Translate(Component)
        in I18nextProvider
        in Provider (created by WrapperComponent)
        in WrapperComponent

    componentWillReceiveProps: Please update the following components to use static getDerivedStateFromProps instead: DropdownLayout, SearchBox

    Learn more about this warning here:
    https://fb.me/react-strict-mode-warnings
```

...

### 🤔 Expected Behavior

When applying React.Strict mode to the component, no errors should show up.
...

### 👣 Steps to Reproduce

In any test, surround: `<React.StrictMode><InputWithOptions /></React.StrictMode>`

  - **WSR version**: any
  - **Yoshi version**: any

### 👀 Severity

Low

**Comment by shlomitc** [comment]
Currently, the library is still supporting React15, meaning these APIs are considered OK.
`getDerivedStateFromProps` and similar new syntax can be used only with a polyfill.
You're welcome to suggest a fix to support both React 15 and 16 that doesn't throw the warnings

**Comment by morsh** [comment]
https://github.com/wix/wix-style-react/issues/3580

**Comment by mosheKerbel** [comment]
@shlomitc Yep still happenning after upgrade to React16
We have instances of `findDomNode` both in WSR and in wix-ui-core, which are not supported in reactStrictMode, thus produing the folllowing error:
![image](https://user-images.githubusercontent.com/7388217/65384014-9da6e600-dd25-11e9-8913-8ee334575741.png)

it is happening in other components as well, not only `inputWithOptions`

**Comment by EgoziE** [comment]
Moved to Jira - closing
