### ISSUE TITLE
<Tooltip /> - Function components cannot be given refs. Attempts to access this ref will fail

### ISSUE THREAD

**Issue by saarkuriel** [wix/wix-style-react#3572]
# 🐛 Bug Report

### 🏗 Relevant Components
`<Tooltip />`

### 😯 Current Behavior

The component is breaking in a certain part of my code after upgrading WSR from 6.16.2 to 6.27.0

The error appears in the console is: `Warning: Function components cannot be given refs. Attempts to access this ref will fail.  Did you mean to use React.forwardRef()?`

### 🤔 Expected Behavior

Tooltip should appear as in any other usage in my code.

### 👣 Steps to Reproduce

  - **WSR version**: `6.27.0`
  - **Yoshi version**: `4.9.0`

repo: https://github.com/wix-private/premium-purchase-plan
problematic code: https://github.com/wix-private/premium-purchase-plan/blob/master/src/pages/SubscriptionPage/SummaryRow/SummaryRow.tsx#L116

There are many usages of tooltip in this project but this is the only one failing after the upgrade.

### 👀 Severity

- Critical

**Comment by mykas** [comment]
Hey @saarkuriel , wsr version 6 includes old and new refactored Tooltip. You should be getting deprecation logs urging you to upgrade to new Tooltip by passing `upgrade` prop. The new tooltip does not have this issue anymore

**Comment by saarkuriel** [comment]
Hey mykas thanks for the quick reply!
passing `upgrade` did fixed the problem but now it has totally different styling and requires me to put some time in a thing that was already finished and in production. Is there another way I can get around this problem?

**Comment by mykas** [comment]
Do you need `light` theme tooltip for your case?

**Comment by saarkuriel** [comment]
Well yes but it didn't work (also didn't see it in the docs 🤔) 
also, look:
![Screen Shot 2019-06-16 at 12 07 11](https://user-images.githubusercontent.com/39697196/59561993-6098cc80-902f-11e9-9435-9658e6128a02.png)

**Comment by mykas** [comment]
This is default behaviour :) its ok. The default floating behaviour is `parent` which means that the content width will be based on its parent defined width. If you pass `appendTo="window"` - the content will be in a good shape.

**Comment by mykas** [comment]
Regarding the `light` theme it was deprecated on purposed. Currently our UX infra defined that all the tooltips must be with `dark` theme. I suggest talking with your UX getting informal review from UX infra regarding this :)

**Comment by saarkuriel** [comment]
I see. Thanks a lot for your help!!!

**Comment by mykas** [comment]
No probs.
