### ISSUE TITLE
Support React 15 & 16 without showing warnings

### ISSUE THREAD

**Issue by morsh** [wix/wix-style-react#3580]
# ✨ Feature Request
Support React 15 & 16 without showing warnings.
Currently, when adding [React.StrictMode](https://reactjs.org/docs/strict-mode.html) there are warnings that require removing some methods (like componentWillReceiveProps) for some of the components.

### 🔦 Scope
wix-style-react wide
Specifically affecting components: DropdownLayout, Tooltip.
...

### 💁 Explanation
Not really sure how to support both version - currently, not really sure why we still support react 15

...

### 🐾 Possible solution 

* Move to react 16

...

### 👀 Severity
Low

**Comment by shlomitc** [comment]
done - wsr@7 is now fully React16 compatible
