### ISSUE TITLE
<Table/> - add <Loader/> to a row or all content

### ISSUE THREAD

**Issue by bbenjjamiin** [wix/wix-style-react#3596]
# ✨ Feature Request

### 🔦 Scope

Ability to trigger a loading state on a row of a table or on the entire content of the table.

...

### 💁 Explanation

When user delete a row, perform a specific action, our server takes time to respond, we need a way to indicate that the action is in progress and prevent the user from interacting.
...

### 🐾 Possible solution 

1. loading state on a row
2. global loading state on the entire content of the table
...

### 👀 Severity

- Major

**Comment by shlomitc** [comment]
Hey, I think a good UX will be just replacing the table content with a `Loader`, which is a common use case. We might add a global loader to the page in the future.

**Comment by EgoziE** [comment]
We decided to close this issue.
