### ISSUE TITLE
fonts / colors

### ISSUE THREAD

**Issue by yanivefraim** [wix/wix-style-react#36]
What about font and colors? Should we add them separately?

**Comment by lbelinsk** [comment]
I would like to know what is the correct way to us it also...

**Comment by 3LOK** [comment]
What I currently am doing is importing wix-style-react/src/common.scss.

**Comment by lbelinsk** [comment]
After talking about it with @shahata , The desired usage will be to add a new component to the repo which will act like a label component.

For instance:
` <Label> Hello </Label>`

This will prevent the user to add his own css, or to import this common.scss file.

This component will receive some props which will make it a bit more flexible to select a font / color.

**Comment by 3LOK** [comment]
Sounds good for most cases - still believe people will probably need access to the scss (eg. they'll need an svg with a fill color of $D20).
