### ISSUE TITLE
[Popover]: add zIndex prop

### ISSUE THREAD

**Issue by ipanasenko** [wix/wix-style-react#3607]
# ✨ Feature Request

### 🔦 Scope

Popover component seems to be missing `zIndex` prop. Tooltip component has it, I think Popover should have it too.

### 💁 Explanation

We have `<Popover appendTo="viewport" />` in a Modal component, and Popover is opened behind modal, because Modal has higher zIndex (5000 vs 1000)

### 🐾 Possible solution 

Allow to set zIndex of Popover

### 👀 Severity

We have a bug 

- Critical

**Comment by mosheKerbel** [comment]
fixed [here](https://github.com/wix/wix-ui/pull/1363)
because `<Popover/>` is spreading it's props into `<CorePopover/>` and inherit it's props, no need for another change in WSR.
