### ISSUE TITLE
Unable to reset RichTextInputArea value

### ISSUE THREAD

**Issue by mozesoron** [wix/wix-style-react#3609]
# 🐛 Bug Report

### 🏗 Relevant Components

RichTextInputArea

...

### 😯 Current Behavior

I'm passing initial value in order to reset/control the component value but once the user type I can't re render the component with "reset / default value"

...

### 🤔 Expected Behavior

passing initial value or any value will take over the value that already exist. 
...

### 👣 Steps to Reproduce

create a component type text and click clear /  add clear functionality 

  - **WSR version**: `6.16.2`
  - **Yoshi version**: `4.1.0-alpha.7`

### 👀 Severity

@the moment users in dev center can't clear the field / reset the form that they just filled in properly. 

- Critical / **Major** / Low

**Comment by mosheKerbel** [comment]
@mozesoron fixed and published
there's an example in the examples section on how to `Set value / Rest value `
https://wix-wix-style-react.surge.sh/?selectedKind=Components&selectedStory=RichTextInputArea&full=0&addons=0&stories=1&panelRight=0

plz update your version and give us a feedback about it.

**Comment by mosheKerbel** [comment]
Resolved.
