### ISSUE TITLE
InputArea placeholder bug

### ISSUE THREAD

**Issue by lbelinsk** [wix/wix-style-react#362]
@nirhart 

If you do:

```<InputArea placeholder="bla"/>```

I can see the placeholder

But when I add autoFocus prop the placeholder disappears.

```<InputArea placeholder="bla" autoFocus/>```

**Comment by nirhart** [comment]
@lbelinsk I tried this in the storybook example and it worked for me, maybe its something else?
<InputArea placeholder="FDSFSDF" autoFocus/></div>

**Comment by lbelinsk** [comment]
wattt..

For me it didn't work for sure, I played with it to make sure this is the autoFocus fault.
I will try to recreate this case in a different place at the code.

**Comment by nirhart** [comment]
@lbelinsk ?

**Comment by lbelinsk** [comment]
@nirhart still didn't get to this :)
Will try to make time for it this week

**Comment by lbelinsk** [comment]
Working..
