### ISSUE TITLE
Issue when testing <DropdownBase  appendTo=‘window’/> component

### ISSUE THREAD

**Issue by Artuar** [wix/wix-style-react#3620]
# 🐛 Bug Report

### 🏗 Relevant Components

<DropdownBase/>

### 😯 Current Behavior

I use component <DropdownBase/> with appendTo=‘window’
but when I test it by DropdownBase Testkits
method selectOption(index) returns error:
Cannot find element with locator: [data-hook=dropdown-layout-options] > *:nth-child(3)
P.S. Options list has more than 3 items. It works correct without appendTo=‘window’

### 🤔 Expected Behavior

Component <DropdownBase/> has the same behaviour when appendTo=‘window’ and without it. Method selectOption from DropdownBaseTestkits has to select options by index.

### 👣 Steps to Reproduce

Add <DropdownBase  appendTo=‘window’/> component to your application and try to test it by DropdownBaseTestkits when using method selectOption(index) 

  - **WSR version**: `6.27.0`
  - **Yoshi version**: `4.9.0`

### 👀 Severity

- Major

**Comment by shlomitc** [comment]
How do you initialize the testkit?

**Comment by shlomitc** [comment]
looks like the driver is not handling portal elements
https://github.com/wix/wix-style-react/blob/master/src/DropdownBase/DropdownBase.uni.driver.js#L13
it is treating it as a direct child which is not the case when using `appendTo="window"`

**Comment by mykas** [comment]
Fixed
