### ISSUE TITLE
Tooltips don't break into lines 

### ISSUE THREAD

**Issue by anatfenn** [wix/wix-style-react#3625]
# 🐛 Bug Report

### 🏗 Relevant Components

media manager
...

### 😯 Current Behavior

very long tooltips appear when hovering image title

...

### 🤔 Expected Behavior

the tooltip should break (according to our SG) to lines and not exceed the size of the image it is triggered from
...

### 👣 Steps to Reproduce

  - **WSR version**: `...`
  - **Yoshi version**: `...`

### 👀 Severity

major

- Critical / Major / Low

**Comment by shlomitc** [comment]
Can you please ask your devs to create a reproducible example, something that we can simulate?

**Comment by shlomitc** [comment]
@anatfenn - can you please respond?

**Comment by ipanasenko** [comment]
@shlomitc try adding a Stock Image to editor, and while you are on Shutterstock tab in Media Manager, hover over image titles:
![image](https://user-images.githubusercontent.com/576152/60793822-1b207880-a171-11e9-9afa-60cb89c7ccc2.png)

**Comment by mykas** [comment]
Text component supports `maxWidth` and it breaks even long words to new line.
