### ISSUE TITLE
Design tweaks on Google Preview and Social Preview

### ISSUE THREAD

**Issue by koriguy** [wix/wix-style-react#3627]
# ✨ Feature Request

### 🔦 Scope

Design tweaks on Google Preview and Social Preview
1.in the Google preview, the SEO title should never be collapsed. Even if I put just a space in the SEO title field. 
The description is OK
This state (no title no description) should never show:
![image](https://user-images.githubusercontent.com/7893896/60073207-793c6d00-9728-11e9-99d1-ef6ad031feb1.png)

2. in the social preview, the OG title should never be collapsed. Same as above. 
The description is OK.
This state (no title no description) should never show
![image](https://user-images.githubusercontent.com/7893896/60073214-7fcae480-9728-11e9-9af9-77db80043395.png)

3. Image Viewer component was supposed to have border radius of 0px
![image](https://user-images.githubusercontent.com/7893896/60073243-93764b00-9728-11e9-86e9-2fb714c964c7.png)

4. URL should break after 1 line and show tooltip + elipses
![image](https://user-images.githubusercontent.com/7893896/60073260-9ec97680-9728-11e9-9848-dd1ff01c4c96.png)

5. Both previews : Tooltips should wrap after 240px
![image](https://user-images.githubusercontent.com/7893896/60073283-abe66580-9728-11e9-8788-9a4fb917c6a1.png)

### 👀 Severity
Low

**Comment by shlomitc** [comment]
There’s no access to the doc, can you please write the details here?

**Comment by koriguy** [comment]
sure. Done

**Comment by shlomitc** [comment]
@wuwa - do these issues look legit? especially 1. and 2. that is more of UX decisions and not technical ones

**Comment by wuwa** [comment]
yes, all ok

**Comment by shlomitc** [comment]
1 + 2 + 4 are low on priority, so it won't be fixed soon. you're welcome to make a PR.
3 - will be solved soon, have a separate issue here https://github.com/wix/wix-style-react/issues/4131
5 - looks to be working ok
