### ISSUE TITLE
Input testkit

### ISSUE THREAD

**Issue by lbelinsk** [wix/wix-style-react#363]
Need a "hasMessage" method. (like hasError: https://github.com/wix/wix-style-react/blob/master/src/Input/Input.driver.js#L32)

**Comment by nirhart** [comment]
That should do the trick:
https://github.com/wix/wix-style-react/blob/master/src/Input/Input.spec.js#L14

**Comment by lbelinsk** [comment]
I ment adding to the driver hasMessage methos,
https://github.com/wix/wix-style-react/blob/master/src/Input/Input.driver.js#L11
