### ISSUE TITLE
Preventing passive event inside Page component

### ISSUE THREAD

**Issue by rudnitskih** [wix/wix-style-react#3635]
# 🐛 Bug Report

### 🏗 Relevant Components

Page
https://wix-wix-style-react.surge.sh/?selectedKind=Components&selectedStory=Page&full=0&addons=0&stories=1&panelRight=0

### 😯 Current Behavior

Error in the console because some component does `preventDefault` for passive event
![image](https://user-images.githubusercontent.com/8848858/60151789-c5e67d80-97e6-11e9-945b-73a258cd01f3.png)

### 🤔 Expected Behavior

Passive events shouldn't be prevented.

### 👣 Steps to Reproduce

1. Open WSR storybook and open the dev tools:
https://wix-wix-style-react.surge.sh/?selectedKind=Components&selectedStory=Page&full=0&addons=0&stories=1&panelRight=0

2. Scroll the page
3. See errors

  - **WSR version**:  6.32.0
  - **Yoshi version**: 4.9.3

### 👀 Severity

- Low

**Comment by shlomitc** [comment]
Hey, thanks. is this a new issue that came up in the latest version or did it happen before?

**Comment by rudnitskih** [comment]
I don't know, we just started using Page component in our app

**Comment by etaybarzilay89** [comment]
Happens for me as well ✌️

**Comment by EgoziE** [comment]
Moved to Jira - closing

https://jira.wixpress.com/browse/DSM-1500
