### ISSUE TITLE
Allow the <TextLink> attributes flow pass through to <a>

### ISSUE THREAD

**Issue by lbelinsk** [wix/wix-style-react#364]

**Comment by lbelinsk** [comment]
I would like to get in the end:

<a href=....   rel="noopener noreferrer" target="_blank"/>

**Comment by lbelinsk** [comment]
![image](https://cloud.githubusercontent.com/assets/18248989/24216424/dd278d2c-0f44-11e7-8dfb-f80d25595f3d.png)

**Comment by nirhart** [comment]
Did you mean add the prop or add a test for it? cause I don't see that prop at all

**Comment by lbelinsk** [comment]
Sorry I mixed up 2 issues, updated the issue title.
