### ISSUE TITLE
Text component with popover

### ISSUE THREAD

**Issue by adimorwix** [wix/wix-style-react#3642]
# 🐛 Bug Report

### 🏗 Relevant Components

Text with ellipsis attribute

### 😯 Current Behavior
popover has max-width 100% and is not customizable.

### 🤔 Expected Behavior
option to customize.
...

### 👣 Steps to Reproduce

  - **WSR version**: `6.32`
  - **Yoshi version**: `...`
![image](https://user-images.githubusercontent.com/47712745/60188166-8431f300-9837-11e9-8925-95a346a9f87b.png)

### 👀 Severity
Major

- Critical / Major / Low

**Comment by shamit6** [comment]
I also have this problem. it happens when the text is a column in table. i can reproduce it easily if needed

**Comment by mykas** [comment]
fixed.
