### ISSUE TITLE
Checkbox Unidriver fails to return the error message when hovering it

### ISSUE THREAD

**Issue by TalZa1810** [wix/wix-style-react#3647]
# 🐛 Bug Report

### 🏗 Relevant Components
`<Checkbox/>`

### 😯 Current Behavior
`getErrorMessage()` of the [Checkbox UniDriver](https://github.com/wix/wix-style-react/blob/master/src/Checkbox/Checkbox.uni.driver.js#L54) returns Error.

### 🤔 Expected Behavior
This function should return the tooltip error message when hovering the checkbox (in case of an error).

### 👣 Steps to Reproduce
On the checkbox visual testing, we're trying to create an interactive test- display tooltip error message on checkbox hover. In order to display it, we're using the tooltip driver. After debugging, the `hoverAndGetContent` function fails to return the content [here](https://github.com/wix/wix-style-react/blob/master/src/Tooltip/Tooltip.uni.driver.js#L48). 

#### Note:
In order to get the `<Tooltip/>` content using class, there's also a need to update the `getTooltipContent` function as follows: 

``` 
import styles from './TooltipContent.scss';
.....
const getTooltipContent = async () =>
    await (await getContentRoot()).$(styles.tooltip);
```

  - **WSR version**: `3.34.1`
  - **Yoshi version**: `^4.1.1`

### 👀 Severity

- Critical / Major / Low

**Comment by TalZa1810** [comment]
Meanwhile, I  was commented out the test in [this PR](https://github.com/wix/wix-style-react/pull/3648).
FYI @shlomitc  @mosheKerbel

**Comment by shlomitc** [comment]
Thanks. Moreover, when we took a deeper look, it was `eventually` that used some testing variable (jasmine.timeout), which wasn't globally available when running in the storybook.

I think it's a relatively simple fix, please try to take it when you can
