### ISSUE TITLE
Collapse animation is laggy when margin is used

### ISSUE THREAD

**Issue by liorcode** [wix/wix-style-react#3651]
🐛 Bug Report
When wrapping a Box component with a marginTop by a Collapse component, the open animation is very laggy.

E.g, in the following code:
```
<Collapse open={isOpen}>
  <Box verticalAlign="middle" marginTop={3}>
    ... Some content with height
  </Box>
</Collapse>
```
The collapse would open in a very sluggish way.

For now, to workaround it, i've replaced the marginTop by a paddingTop which performs a lot better.

🏗 Relevant Components

`<Collapse />`

 👣 Steps to Reproduce

https://codesandbox.io/s/wix-style-react-8y9tw

  - **WSR version**: `3.31`
  - **Yoshi version**: `6.34`

### 👀 Severity

Low

**Comment by nitayneeman** [comment]
Code to reproduce:
```jsx
class MyComponent extends React.Component {
  constructor(props) {
    super(props);
    this.state = {isOpen: false};
  }
  render() {
    return (
      <>
            <Box>
                <ToggleSwitch
                  dataHook="online-bookings-switch"
                  checked={this.state.isOpen}
                  onChange={e => {
                    this.setState({isOpen:!this.state.isOpen})
                  }}
                />
            </Box>
            <Collapse open={this.state.isOpen}>
              <Box marginTop="30px">aaa</Box>
              <Box>bbb</Box>
              <Box>ccc</Box>
            </Collapse>
      </>
    );
  }
}
```

It turns out it's a known issue with the library we use (react-collapse) under the hood:
https://github.com/nkbt/react-collapse#behaviour-notes
https://github.com/nkbt/react-collapse/issues/101

We need to mention this constraint in our component docs, at least. Keeping this issue open until we do that.

CC: @mosheKerbel
