### ISSUE TITLE
Add more control over the Text's tooltip in case of ellipsis

### ISSUE THREAD

**Issue by Jefoss** [wix/wix-style-react#3664]
# ✨ Feature Request

### 🔦 Scope
Text component with ellipsis

### 💁 Explanation
currently the  developer has no control over the ellipsis tooltip - (the props are hardcoded - https://github.com/wix/wix-style-react/blob/master/src/Text/ProxyText.js#L7-L10) and in some cases i believe there are things you would want to customize like hide/show delays etc..

### 🐾 Possible solution 

the solution could be pretty straightforward, propagate the tooltip props from the Text component to the tooltip component instead of having it hard coded.

### 👀 Severity
Low

**Comment by mykas** [comment]
Feature developed.

**Comment by shlomitc** [comment]
@mykas - is this issue still relevant?

**Comment by mykas** [comment]
Hi, this feature is already developed and merged. Closing it.
