### ISSUE TITLE
Stepper - disable click

### ISSUE THREAD

**Issue by adimorwix** [wix/wix-style-react#3674]
#✨ Feature Request

### 🔦 Scope
Hi 
zilvinasm, Ben Benhorin and Moshe Kerbel

We need to disable all clicks in the Stepper.
...
### 💁 Explanation
The client should not move from step to step by click on a step. 
Yasmin Adam is our UX
...
### 👀 Severity
for us is critical, we cant use the Stepper without the change

**Comment by mosheKerbel** [comment]
i recommend u tag Yasmin here.
@ZilvinasMaciulis @wuwa @shlomitc 
Adi's spec says that the stepper should disable clicks and navigation would be from outside of the stepper (some buttons in the end of the form).

1. our design spec does not support such a use case.
2. as i see it users should have a consitent ux. In some screens they would be able to navigate through the stepper and in some cases not? 

your thoughts.

**Comment by wuwa** [comment]
clicking on disabled steps - not possible, that's the whole point of disabled.
clicking on blue steps (completed or numbered) is possible.

**Comment by mosheKerbel** [comment]
@wuwa i'm not sure it was clear enough
1. current behaviour - steps are clickable
2 Adi's request - steps will not be clicakble at all, the navigation between them will be only from buttons of the form where stepper sits in.

**Comment by wuwa** [comment]
yes, you were clear. the answer is no, if they don't allow clicks, use the disabled state.

**Comment by mosheKerbel** [comment]
thanks @wuwa 
@adimorwix i'm closing this.

**Comment by adimorwix** [comment]
Yasmin doesn't have a user in git. I can't tag her here.

**Comment by adimorwix** [comment]
OK you can close the issue we will support the clicks
Thanks!
