### ISSUE TITLE
InputWithOptions text caret moves to text start when pressing the up key

### ISSUE THREAD

**Issue by naamagr** [wix/wix-style-react#3681]
# 🐛 Bug Report

### 🏗 Relevant Components

InputWithOptions

### 😯 Current Behavior

When the user enters some text in the `InputWithOptions`, some options may appear in the drop-down dialog and the user can navigate between them by using the up and down keys. 
pressing the down key behaves as expected, but after pressing the up key, the text caret moves to text start, so the user cannot easily continue his search.

### 🤔 Expected Behavior

The caret stays where it was (like it does when pressing the down key )

### 👣 Steps to Reproduce

It can be reproduced easily in the storybook:
https://wix-wix-style-react.surge.sh/?selectedKind=Components&selectedStory=InputWithOptions&full=0&addons=0&stories=1&panelRight=0

1. Click on the search box 
2. Insert some text 
3. Move down and then up over the options with the up and down keys
4. The caret moves to text start

### 👀 Severity

Major
It affects search feature in business manager, and probably all users of InputWithOptions

**Comment by gilmeir** [comment]
Hitting the `ArrowUp` key on `Input` component brings the cursor to the beginning of the text.
`InputWithOptions` composes `Input`, so in this case we will event.preventDefault() on `ArrowUp` key.
