### ISSUE TITLE
Flappy tests: Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL

### ISSUE THREAD

**Issue by sidoruk-sv** [wix/wix-style-react#3685]
# 🐛 Bug Report

It is a bit annoying to re-run your PR and wait when the test goes right for PR to be approved.

### 😯 Current Behavior

```
Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
    at Timeout._onTimeout (/home/builduser/agent00/work/af87960f4adfd0b0/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:4281:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
------- Stdout: -------
[protractor]  [31mF [0mA Jasmine spec timed out. Resetting the WebDriver Control Flow.
[protractor] 
[protractor] 
```
### 🤔 Expected Behavior

No flappy tests

### 👣 Steps to Reproduce

Almost every PR is marked with :x:

### 👀 Severity

- Major

**Comment by shlomitc** [comment]
yes, it's a very annoying issue. We tried investigating it a while ago and it looks to be part of the `eyes.it`, probably network connectivity. it can't be reproduced locally as we don't run applitools locally, which makes it even more hard to understand.

in general - we're rewriting many of the protractor tests to the new `.visual` test pattern which is faster, more reliable and easy to create.

in the meanwhile, I just suggest ignoring it. build is still running correctly, so if that's the only reason the build failed - I'm ok with merging

**Comment by shlomitc** [comment]
we upgraded our applitools service to a private cloud causing much fewer timeouts.
closing
