### ISSUE TITLE
<AutoDocs/> - Testkit doc for UniDriver lacks code examples

### ISSUE THREAD

**Issue by mosheKerbel** [wix/wix-style-react#3693]
1. Currently only the API table is created
2. Two options:
  - Parse the uniDriver to create all examples like the old drivers.
  - Remove the examples from all existing testkit desc docs and create one place with generic examples for the different test platforms. In this case we would need to remove the examples creation from autoDocs.

**Comment by mosheKerbel** [comment]
@argshook

**Comment by shlomitc** [comment]
in general - I think that the repetition of the code example is not necessary. I would prefer having it only once in our docs, with all the caveats of testing (for example popover, tooltip, etc...)

I agree with improving the API table. maybe by adding better support for JSDoc? That way we can document parameters, returned value and more

**Comment by argshook** [comment]
done, closing
