### ISSUE TITLE
<Tooltip/> - Page "bump" form bottom in some cases

### ISSUE THREAD

**Issue by mosheKerbel** [wix/wix-style-react#3694]
In some cases the `<tooltip/>` root class is getting `diaply: inline-block`,  which causes the page inside bussiness manager to "bump" from bottom, like in the attached screenshot.

Workaround: user can override the display to "block" like this:
```
<Tooltip className = {myClass } ... />
.myClass { display: block }
```

Fix suggestion: realize if the fact that tooltip is set to `inline-block` is needed at all. 
If it is possible and pass all tests scenarios then change it to `display: block`

[See slack chat](https://wix.slack.com/archives/C39FTGUBZ/p1561466849401700)

![image](https://user-images.githubusercontent.com/7388217/60676805-7a883b00-9e88-11e9-8e56-207e3f7b0d6a.png)

**Comment by mykas** [comment]
Fixed.
