### ISSUE TITLE
Start using to CSS variables

### ISSUE THREAD

**Issue by gilmeir** [wix/wix-style-react#3704]
We can migrate our colors scheme as a use case.
We can move them all to one repo (as long as backoffice exists it should be in wix-ui-core), instead of the duplication between wix-style-react / wix-ui-backoffice / wix-ui-core.

Why use css variables?
* It's native!
  * This means it's supported in all css frameworks like sass / stylable.
  * We can share variables regardless of the framework being used.
* Easier to debug!
  * Chrome dev-tools shows inside the `Source` --> `Computed` tab the variables and their values.
  * When you debug a DOM element color, for example, you'll see it's variable name, like `var(--D10-30)`, and when you expand it you see the variable's value.
  * I recently tried css variables while [changing all components' disabled theme in WSR](https://github.com/wix/wix-style-react/issues/2368).
    @LittleTal experienced that on her manual test from the UX side, and indicated it makes the process better.

TBD @gilmeir add code examples and stuff

**Comment by shlomitc** [comment]
will be done once we solve scoping for IE11
