### ISSUE TITLE
`<Calendar>` testkit doesn't provide a way to check if a specific date is disabled

### ISSUE THREAD

**Issue by dorduch** [wix/wix-style-react#3710]
If we are using `clickOnDay` function it clicks the day whether it's disabled or not.

**Comment by mykas** [comment]
Can you clarify a bit more? You would like to test if past dates are disabled or not? is that right?

**Comment by dorduch** [comment]
I want to test if a given date is disabled

**Comment by mykas** [comment]
Ok, thanks
