### ISSUE TITLE
6.6 Stepper Focus Flicker 

### ISSUE THREAD

**Issue by ZilvinasMaciulis** [wix/wix-style-react#3721]
# 🐛 Bug Report

6.6 Stepper

### 😯 Current Behavior

Focus state appears on mouse click creating a flicker effect. 

### 🤔 Expected Behavior

Focus state should only appear on the keyboard focus

### 👣 Steps to Reproduce

Try clicking on steps, see the video attached
[Focus flicker.mov.zip](https://github.com/wix/wix-style-react/files/3372802/Focus.flicker.mov.zip)

**Comment by shlomitc** [comment]
looks like the issue is for not using `FocusableHOC` for the `StepCircle` component.
`FocusableHOC` makes sure the focus ring appears only when using the keyboard and not on mouse click

**Comment by mykas** [comment]
Fixed
