### ISSUE TITLE
<Input> with error inside <Page.Content> has shifted tooltip. 

### ISSUE THREAD

**Issue by rudnitskih** [wix/wix-style-react#3724]
# 🐛 Bug Report

### 🏗 Relevant Components

`<Page>`, `<Page.Content>`, `<Input>`, `<Tooltip>`

### 😯 Current Behavior

`<Input>` with error inside `<Page.Content>` has shifted tooltip. 

![image](https://user-images.githubusercontent.com/8848858/60891713-8a2bc900-a266-11e9-931a-c12ff0c9b837.png)

### 🤔 Expected Behavior

Tooltips should be shown correctly.

### 👣 Steps to Reproduce

https://codesandbox.io/s/formfield-in-page-d4kpn

 1. Create `<Page.Content>` with `<Input>` and error. You should have a scroll on the page to reproduce the issue.
 2. Scroll a little bit.
 3. Hover an error icon in the input.
 4. Tooltip is shifted on the amount of scroll. 

  - **WSR version**: 6.37.0
  - **Yoshi version**: 4

### 👀 Severity

Low

**Comment by mykas** [comment]
Hi, the bug is related to Input using old Tooltip with bad floating calculation. https://github.com/wix/wix-style-react/blob/master/src/Input/InputErrorSuffix.js#L14
