### ISSUE TITLE
Change row text in Table

### ISSUE THREAD

**Issue by shl3vi** [wix/wix-style-react#3730]
# ✨ Feature Request

### 🔦 Scope
should be able to change row text color in table
 
### 💁 Explanation

in the zeplin (https://app.zeplin.io/project/5c8f6f1f9f489505cac756dc/screen/5cb9dbccfe244b013fdc3c38) we have text color for row that is D20 (for sku column for example) and D10 (for Name column for example)
When creating a table, the row default text color is  #D20(#32536A) without option to change. (we need #D10(#162d3d))
 
### 🐾 Possible solution 

should have api for changing to D10

### 👀 Severity
 LOW

**Comment by shlomitc** [comment]
I'd say that default colors are ok, but since there are many options, I suggest composing `Text` component with its default styling.
for example:
```jsx
class TableExample extends React.Component {
  state = {
    data: [
      { firstName: 'Meghan', lastName: 'Bishop' },
      { firstName: 'Sara', lastName: 'Porter' },
      { firstName: 'Deborah', lastName: 'Rhodes' },
      { firstName: 'Walter', lastName: 'Jenning' },
    ],
  };

  render() {
    return (
      <Table
        data={this.state.data}
        columns={[
          { title: 'First', render: row => <Text size="small">row.firstName</Text> },
          { title: 'Last', render: row => <Text size="small" secondary>row.lastName</Text> },
        ]}
      >
        <Table.Content />
      </Table>
    );
  }
}
```

you can try it in the playground
https://wix-wix-style-react.surge.sh/?selectedKind=Introduction&selectedStory=Playground&full=0&addons=0&stories=1&panelRight=0
