### ISSUE TITLE
MessageBox components should have individual exports

### ISSUE THREAD

**Issue by argshook** [wix/wix-style-react#3732]
# ✨ Feature Request

### 🔦 Scope

the following components do not have root import paths:

* `MessageBoxMarketerialLayout`
* `MessageBoxFunctionalLayout`
* `HeaderLayout`
* `FooterLayout`

### 💁 Explanation

for example, this does not work:
`import MessageBoxFunctionalLayout from 'wix-style-react/MessageBoxFunctionalLayout';`

user must do
`import { MessageBoxFunctionalLayout } from 'wix-style-react/MessageBox';`

but this way user is importing all `MessageBox` family, not only `MessageBoxFunctionalLayout`.

moreover, import path is not consistent with majority of other components

### 🐾 Possible solution 

consider aforementioned components as root level (do not nest under `MessageBox`)

use same `import-path` as for other components

### 👀 Severity

- Low

**Comment by shlomitc** [comment]
any usage for the `HeaderLayout` and `FooterLayout`?

**Comment by EgoziE** [comment]
deprecated
