### ISSUE TITLE
<Text /> ellipsis doesn't work as expected with long words

### ISSUE THREAD

**Issue by MSiliunas** [wix/wix-style-react#3733]
# 🐛 Bug Report

### 🏗 Relevant Components

`<Text ellipsis />` – tooltip displays text not as expected

### 😯 Current Behavior

![image](https://user-images.githubusercontent.com/6944305/61029965-063c2300-a3c5-11e9-8287-043c161d177c.png)

We have a use-case where we show email address. If it doesn't fit, ellipsis needs to be added. While the ellipsis itself is added correctly, the email in tooltip is not fitted properly (see attached screenshot)

### 🤔 Expected Behavior

The text should be properly handled in the tooltip – whether it would be wrapped or displayed in one line

### 👣 Steps to Reproduce

- Add `<Text ellipsis>no-reply@automations.ascendbywix.com</Text>` into a div which would be narrower than the text
- Hover on the text

  - **WSR version**: `6.38.0`

### 👀 Severity

- Major

**Comment by shlomitc** [comment]
@milkyfruit - what should be the behavior for one long word?

**Comment by milkyfruit** [comment]
@MSiliunas @shlomitc 
I think we should improve 2 things:
- add `word-break: break-word` in a tooltip
- Encourage using `maxWidth` prop, which can widen the tooltip if a user needs to keep the word unbroken.

**Comment by shlomitc** [comment]
Should the word break be applied only for cases of one word?

**Comment by milkyfruit** [comment]
Word break should be applied for all cases.
If a tooltip has a single word value and the length of a word exceeds the tooltip's width it's equally bad as there are multiple words that exceed tooltip's `maxWidth`.

**Comment by MSiliunas** [comment]
if I add prop `maxWidth={''}` it works for my case:
![image](https://user-images.githubusercontent.com/6944305/61214570-e5e7cd80-a710-11e9-909b-89618f854607.png)

**Comment by mykas** [comment]
Fixed.

**Comment by mykas** [comment]
Opening again because the change I did for wrod-break is breaking other components. I will develop a new prop for allowing such long words.

**Comment by mykas** [comment]
Scoped the break word feature to only Tooltip component. Fixed.
