### ISSUE TITLE
<Input /> - onFocus is called twice on mount when autoFocus prop is used

### ISSUE THREAD

**Issue by ipanasenko** [wix/wix-style-react#3738]
To reproduce:
```ts
<Input value="blablabla" onFocus={console.log} />
```

**Comment by shlomitc** [comment]
Tried copying it to the [playground](https://wix-wix-style-react.surge.sh/?selectedKind=Introduction&selectedStory=Playground&full=0&addons=0&stories=1&panelRight=0) and focus in, but couldn't reproduce.
can you please check?

**Comment by ipanasenko** [comment]
Try `<Input onFocus={(event) => console.log('event', event)} autoFocus />`

**Comment by ipanasenko** [comment]
![image](https://user-images.githubusercontent.com/576152/61627443-76ca2600-ac88-11e9-886e-7dba7f4da1b2.png)

**Comment by EgoziE** [comment]
fixed
