### ISSUE TITLE
`<RichTextInputArea/>` - initialValue prop strips down empty html tags

### ISSUE THREAD

**Issue by mykas** [wix/wix-style-react#3768]
# 🐛 Bug Report

If initialValue contains empty html tags - it will be stripped down by draftjs convertoToHtml function which is being run on componentDidMount().

### 🏗 Relevant Components

`<RichTextInputArea/>`

### 😯 Current Behaviour

1. User enters some text with new lines:
![Screenshot 2019-07-17 at 10 01 14](https://user-images.githubusercontent.com/8919190/61355501-3e3bde00-a87d-11e9-9268-5e0fadf1a9e8.png)

2. User post this data to server when user presses `SAVE` button or any other.

3. User refreshes the page and new initialValue becomes the one which was entered in step 1.
![Screenshot 2019-07-17 at 10 04 31](https://user-images.githubusercontent.com/8919190/61355593-70e5d680-a87d-11e9-9746-36873a1955d3.png)

As seen in picture above the empty tags are being strip down.

Digging a little bit in code I have found out that `convertToHTML` that comes from `draftjs` strips down this by default.

### 🤔 Expected Behaviour

Should accept intialValue prop with empty tags.

### 👣 Steps to Reproduce

Sandbox to play with: https://codesandbox.io/s/wix-style-react-w0qp4?fontsize=14

### 👀 Severity

- Critica

**Comment by mykas** [comment]
@aarnoldaas

**Comment by shlomitc** [comment]
@nitayneeman - WDYT? was this behavior done by intention?

**Comment by aarnoldaas** [comment]
any news?

**Comment by nitayneeman** [comment]
> @nitayneeman - WDYT? was this behavior done by intention?

We encountered a similar issue when we tested the component in the Inbox Setting.

The problem is the `convertFromHTML` - which removes empty paragraphs while converting the HTML value to the Draft.js blocks. 

This behavior was done by Draft.js team on purpose, from the following reason:
> This was on purpose to keep pastes of long text from having a lot of extra spaces between paragraphs. The content coming in can be pretty messy sometimes and this is one of the things we try to do to clean it up.

Perhaps we should consider adopting this approach?

Anyway, there are a few open issues related to that:
https://github.com/facebook/draft-js/issues/1082
https://github.com/facebook/draft-js/issues/231
https://github.com/facebook/draft-js/issues/578

The only things I can think about are:
1. Reimplement the HTML deserializer by our own (or use an existing customizable library on top of `convertFromHTML`).
2. A bit hacky - but insert to the empty paragraphs a placeholder as content so these will not be removed, and after the blocks are built - go over them and remove these placeholders.

**Comment by aarnoldaas** [comment]
It's a blocker for our users. 
Maybe it should remove empty nodes on paste but shouldn't modify initialValue. It's very strange if user enter text with spaces between paragraphs but after refresh they disappear.

**Comment by aarnoldaas** [comment]
We currently use old component and we can't migrate because immediately starting to get complaints from our users.

**Comment by mykas** [comment]
Hey @nitayneeman , how about the second path: the hack. What if you add empty string inside the empty <p> tags?

**Comment by nitayneeman** [comment]
> Hey @nitayneeman , how about the second path: the hack. What if you add empty string inside the empty `<p>` tags?

I've already tried some variations, like: `<p> </p>`, `<p><br></p>`, `<p>&nbsp</p>` - but all were removed by `convertFromHTML`. That's why I was thinking about adding some actual content and after the blocks are built removing it - but it's definitely a hack.

**Comment by mykas** [comment]
I see. I will check how conertFromHTML is handling. Maybe there is a way.

**Comment by aarnoldaas** [comment]
Our users already saved text with spaces between paragraphs. We need to support empty tags too.

**Comment by nitayneeman** [comment]
> We currently use old component and we can't migrate because immediately starting to get complaints from our users.

I talked to @shlomitc.

There are two ways to promote this behavior support:

1. We'll prioritize and take it as part of our next iteration (which means two weeks approximately until we get to that)
2. Contribution from your side

Anyway we agree this is an issue which must be resolved.

**Comment by mosheKerbel** [comment]
@aarnoldaas FYI 
we are currently on it.

**Comment by mosheKerbel** [comment]
bug was fixed
issue will be closed once version is released.

**Comment by mosheKerbel** [comment]
@aarnoldaas fixed
plz check it out and give us a feedback on how it goes.
