### ISSUE TITLE
Component Generator - add simulation test to meta file

### ISSUE THREAD

**Issue by mosheKerbel** [wix/wix-style-react#3782]
Currently when a component is generated it adds a meta file that adds it to the registry.
Feature to add: 
Add a sim test with `nonReactStrictModeCompliant` flag for sanity tests, like in [Stepper](https://github.com/wix/wix-style-react/blob/38c07e42e543324a61b3268e18164b033ba9b015/src/Stepper/Stepper.meta.js)

**Comment by shlomitc** [comment]
feel free to add it
