### ISSUE TITLE
Documentation - reflect Upgrade flag breaking change meaning in storyboook

### ISSUE THREAD

**Issue by mosheKerbel** [wix/wix-style-react#3783]
Motivation - our consumers might not fully understand the meaning of 'Upgrade' flag.
Request -
We should add a link to a section saying the 'upgrade' is a breaking change etc'
1. Make sure this description exists in our docs, if not then adding it.
2. Go over components that support `upgrade` and edit the alert in their storybook.

**Comment by shlomitc** [comment]
We removed most of the `upgrade` flag props in WSR 8

Also - I think we should avoid this pattern in the future. It works, but confusing and might leave redundant code on the consumer side when upgrading versions.

Instead - we should aim to have some kind of a provider component for the library that will take care of "experiments/feature-toggles", same as applications do. This could also be useful for theming.
