### ISSUE TITLE
PopoverMenuDriver.getTriggerElement incorrect type declaration

### ISSUE THREAD

**Issue by splintor** [wix/wix-style-react#3790]
# 🐛 Bug Report

### 🏗 Relevant Components
`PopoverMenuDriver` (beta)

### 😯 Current Behavior
`PopoverMenuDriver.getTriggerElement` [is defined to have no parameters](https://github.com/wix/wix-style-react/blob/master/src/beta/PopoverMenu/PopoverMenu.uni.driver.d.ts#L5), but [it expects to get the dataHook trigger](https://github.com/wix/wix-style-react/blob/master/src/beta/PopoverMenu/PopoverMenu.uni.driver.js#L9) as parameter.

### 🤔 Expected Behavior
Have the `.d.ts` definition match the implementation...

### 👣 Steps to Reproduce
Try to write tests for `PopoverMenu` (Beta)

  - **WSR version**: `6.41.0`
  - **Yoshi version**: `3.31.1`

### 👀 Severity

- Low

**Comment by mykas** [comment]
Hi, thanks for reporting this! Before I go and fix this: what do you expect the output of this method? would you think it should be native DOM element or are you ok that this method returns the unidriver method list?

**Comment by mykas** [comment]
Also, are you missing any other method for your case?

**Comment by splintor** [comment]
Currently, I only need to be able to call `click()` on the returned object, so I guess returning a `UniDriver` is OK.
