### ISSUE TITLE
Disable enter button in Input

### ISSUE THREAD

**Issue by lbelinsk** [wix/wix-style-react#38]
I have a form which contains both RadioGroup and Input.

![screen shot 2016-12-05 at 5 37 18 pm](https://cloud.githubusercontent.com/assets/18248989/20891023/c2b02e04-bb11-11e6-92c8-669e571790f0.png)

If i select a certain radio button, and then focus on the Input field, then once I press "Enter" key the Radio button turns to be unselected..

**Comment by 3LOK** [comment]
I can't recreate - can you please post code example?

**Comment by lbelinsk** [comment]
Actually I don't think we should address this issue, since it has something to do with event default behaviour..

When I added <Button onClick={e => e.preventDefault}...> it solved it.

The described behaviour happens also with a simple html button, so there is no need to do anything special..
