### ISSUE TITLE
Input clearText not working with puppeteer

### ISSUE THREAD

**Issue by Roeia1** [wix/wix-style-react#3805]
# 🐛 Bug Report

### 🏗 Relevant Components

Input
...

### 😯 Current Behavior

`clearText` isn't working in Testkit from
`import { inputTestkitFactory } from 'wix-style-react/dist/testkit/puppeteer-testkit-bundle'`
text just stays as is.
...

### 🤔 Expected Behavior

clearing the text.

...

### 👀 Severity

Major.
It can be done with 3 clicks to mark all text, and clicking Backspace.
I'm worried it will be flaky...

**Comment by yairhaimo** [comment]
This is due to the fact that `clearText` uses `enterText` behind the scenes which doesnt clear the current value, just appends it.

https://github.com/wix/wix-style-react/blob/c9dccb55973082db4eff5edb8de371de33f68a47/src/Input/Input.uni.driver.js#L120

**Comment by mosheKerbel** [comment]
> This is due to the fact that `clearText` uses `enterText` behind the scenes which doesnt clear the current value, just appends it.
> 
> https://github.com/wix/wix-style-react/blob/c9dccb55973082db4eff5edb8de371de33f68a47/src/Input/Input.uni.driver.js#L120

This is not the case here
If you look carefully you can see that this code is using ReactBase, which only works for jsdom platform and not puppeteer.
https://github.com/wix/wix-style-react/blob/6a57af5bbae51406dacd700789d6e298ef7253f1/test/utils/unidriver/ReactBase.js#L11

Anyways, i just issued a PR Yesterday that fixes it but it is also dependent on another PR in uniDriver that i wait for the guys to approve first
https://github.com/wix/wix-style-react/pull/4184
https://github.com/wix-incubator/unidriver/pull/92

**Comment by shlomitc** [comment]
The issue is stale for a while now and the changes Moshe mentioned are merged.
Let's reopen if it's still an issue.

**Comment by matanlb** [comment]
Hey, Pretty sure that is still happening.
I'm running v7.57.0 and getting the same issue.

Interesting thing is that the text does not append. working with `enterText` directly, putting a new string overrides the existing one, but sending in an empty string does nothing.

**Comment by alexandraseri** [comment]
Hey this is still happens on `focus()` function in v8.39.0
