### ISSUE TITLE
There is no way to specify data-hook for PopoverMenu.MenuItem

### ISSUE THREAD

**Issue by splintor** [wix/wix-style-react#3821]
# 🐛 Bug Report

### 🏗 Relevant Components

`PopoverMenu` (beta)

### 😯 Current Behavior

`PopoverMenu` automatically sets the data-hooks of its child `MenuItem`s as `popover-menu-{id}` (https://github.com/wix/wix-style-react/blob/master/src/beta/PopoverMenu/PopoverMenu.js#L236)

### 👀 Severity

Major - this is currently breaking our automation tests - https://wix.slack.com/archives/CEV9B2VGD/p1563869779001000

**Comment by mykas** [comment]
Hi, thanks for reporting this. After discussion we will surely add `dataHook`to next release.

**Comment by splintor** [comment]
Sounds super logical.

**Comment by dmitriweissmann** [comment]
This is also a concern for QA automaton. We use a data hooks or other attributes to identify the element and if the element in it's place.
For example in case of popover-menu-{id} we have no way to know what it is unless we start interaction with the element. for example it's a menu with 3 entries, currently there is no way to tell what is what and if there are all required and only the required.

**Comment by mykas** [comment]
Make sense

**Comment by mykas** [comment]
fixed.
