### ISSUE TITLE
Input theme amaterial bugs

### ISSUE THREAD

**Issue by lbelinsk** [wix/wix-style-react#383]
1. If the Input has an initial value then the title and the value is on top of each other.

![image](https://cloud.githubusercontent.com/assets/18248989/24577311/0c3a9e7e-16d4-11e7-879c-b3b10bd81d81.png)

After I will focus on the Input field, the title will jump up and will remain there as expected.
The desired behaviour is that the title will remain on top automatically if there is an initial value.

2. https://jira.wixpress.com/browse/INF-369?jql=labels%20%3D%20loginNeedHelp

**Comment by lbelinsk** [comment]
The second bug is still open..
https://jira.wixpress.com/projects/INF/issues/INF-369?filter=myopenissues

**Comment by shlomitc** [comment]
It's not part of the design system, so I'm closing. let's re-open in `wix-ui` context when becomes relevant
