### ISSUE TITLE
checking component existence with puppeteer testkit is bug proned

### ISSUE THREAD

**Issue by Roeia1** [wix/wix-style-react#3830]
# 🐛 Bug Report

### 🏗 Relevant Components

every component using base uni driver in puppeteer testkit

### 😯 Current Behavior

currently, the way to check if a component exists in order to use it is:
```
const button = await buttonTestkitFactory({page, dataHook: 'fancy-button'});
await eventually(async () => expect(await button.exists()).toBeTruthy());
await button.click();
```

...

### 🤔 Expected Behavior

I'm aware that the `exists` function is necessary in case you want to make sure a component doesn't exist.
but, maybe a better approach to wait for existence and not checking it, is to encapsulate this eventually in a function like `await button.eventually.exists()`.

**Comment by EgoziE** [comment]
According to our documentation `exists` "Checks whether the component found with the given data hook"
I understand what you're saying, still we decided not to change current implementation or add this one.

Using testkits on **mounted** components will **never** require waiting for the component to exist, therefore this behavior you describe should be a user responsibility.
Closing this issue 😊
