### ISSUE TITLE
<PreviewWidget/> - create new component

### ISSUE THREAD

**Issue by shlomitc** [wix/wix-style-react#3833]
# ✨ Feature Request

### 🔦 Scope

`<PreviewWidget/>`

### 💁 Explanation

a request for a new component
https://zpl.io/2jMDQLr

![image](https://user-images.githubusercontent.com/6093192/61807515-5ba31600-ae42-11e9-9a7f-35b1986d2ad5.png)

**Comment by EgoziE** [comment]
Moved to Jira - https://jira.wixpress.com/browse/DSM-149
