### ISSUE TITLE
PopoverMenu shows a focus recatngle on first item in Firefox

### ISSUE THREAD

**Issue by splintor** [wix/wix-style-react#3840]
# 🐛 Bug Report

### 🏗 Relevant Components
PopoverMenu (beta)

### 😯 Current Behavior
When clicking a PopoverMenu button in Firefox, it shows the list of items, and the first item has a selcetion rectangle.

In the attached screenshot you also see selection blue background, but this only appears when I press the `Ctrl` button to take the screenshot. Before that, only the dashed selection border appears.
The border doesn't appear on Chrome, only on Firefox.

![image](https://user-images.githubusercontent.com/243549/61871179-ca3aaf00-aee8-11e9-9d20-159e43cf5afe.png)

...

### 🤔 Expected Behavior

Selection rectangle shouldn't initially be displayed, only when using the keyboard arrows.

### 👣 Steps to Reproduce

Open https://www.wix.com/account/sites in Firefox, and click the view menu.

  - **WSR version**: `6.41.0`
  - **Yoshi version**: `3.31.1`

### 👀 Severity
Low

**Comment by mykas** [comment]
Isn't this the firefox behaviour to display focused item? The PopoverMenu accessibility is done so that when you open the menu it will focus the first item automatically.

**Comment by splintor** [comment]
I see. It still looks strange. Would be great if there was a way to set accessibility without this ugly border.

**Comment by mykas** [comment]
its true. I have read that there is way to override it. https://developer.mozilla.org/en-US/docs/Web/CSS/:-moz-focusring
