### ISSUE TITLE
Using <Search> component issues a warning about updateControlledOnClear

### ISSUE THREAD

**Issue by splintor** [wix/wix-style-react#3844]
# 🐛 Bug Report

### 🏗 Relevant Components

`<Search>` (I think also `<InputWithOptions>`)

### 😯 Current Behavior

When using the component, a warning about `updateControlledOnClear` is issued:
```
<Input/> - Clearing the value in a controlled component through onChange() will be deprecated in next major version. Pass updateControlledOnClear prop and use the onClear() callback to apply the new behavior
```

Coming from https://github.com/wix/wix-style-react/blob/master/src/Input/Input.js#L84

### 🤔 Expected Behavior

If `<Search>` is using controlled `<Input>`, it should probably set `updateControlledOnClear` and handle it properly to avoid the warning.

  - **WSR version**: `6.41.0`
  - **Yoshi version**: `3.31.1`

### 👀 Severity

Low

**Comment by EgoziE** [comment]
fixed in wsr 7
