### ISSUE TITLE
Bug with Button colors

### ISSUE THREAD

**Issue by lbelinsk** [wix/wix-style-react#386]
https://jira.wixpress.com/projects/INF/issues/INF-367?filter=myopenissues

**Comment by Faradey27** [comment]
@lbelinsk can you pls duplication info from private jira here? currently i think only wix-users can see it

**Comment by lbelinsk** [comment]
Description
go to https://users.wix.com/account-recovery/
pick any item from a list
go to next page by clicking on [NEXT] button
click on [BACK] button to back to 'How can we help' page
Actual result: [NEXT] button changed it's color from navy blue to blue/green
Expected result: [NEXT] button shouldn't change color in this case


<img width="1680" alt="azurebutton" src="https://cloud.githubusercontent.com/assets/18248989/24837275/eda83870-1d38-11e7-9d13-db105f77c3ae.png">

**Comment by lbelinsk** [comment]
It happens on Safari

**Comment by Faradey27** [comment]
@lbelinsk awesome, thank you

**Comment by Noam3kCH** [comment]
this doesn't reproduce in safari Version 10.1.1 (12603.2.4)

**Comment by lbelinsk** [comment]
QA used safari Version 10.0.3 (12602.4.8),  macOS Sierra 10.12.3..

@nirhart do we want to support it?

**Comment by nirhart** [comment]
Its due to old version of safari, not going to be fixed
