### ISSUE TITLE
<Breadcrumbs/> - accessibility focus is wrong visually

### ISSUE THREAD

**Issue by wuwa** [wix/wix-style-react#3871]
🐛 Bug Report

### 🏗 Relevant Components

<Breadcrumbs>

...

### 😯 Current Behavior

currently focus is default of browser

...

### 🤔 Expected Behavior

Adjust the keyboard focus according to Zeplin:
https://zpl.io/2ZDM4xq
...

### 👀 Severity

- Low

**Comment by shlomitc** [comment]
Currently, the Breadcrumbs display `<Text/>` component, wrapped by custom tags (`a`, `span`, `button`), applying default clickable focus.

A possible solution will be using `ButtonNext` from `wix-ui-core` and it's as` property. this will give us an out of the box solution for focus state and then all that is required is just styling according to specs
