### ISSUE TITLE
Unable to use with create-react-app

### ISSUE THREAD

**Issue by RazLandau** [wix/wix-style-react#3874]
# 🐛 Bug Report

### 😯 Current Behavior

I followed [this](https://wix-wix-style-react.surge.sh/?selectedKind=Introduction&selectedStory=Getting%20started&full=0&addons=0&stories=1&panelRight=0) but got this:
```
TypeError: Focusable_st_css_1.default is not a function
FocusableHOC.render
node_modules/wix-ui-core/dist/src/hocs/Focusable/FocusableHOC.js:177
  174 |   ref: reference,
  175 |   focusableOnFocus: this.onFocus,
  176 |   focusableOnBlur: this.onBlur
> 177 | }, Focusable_st_css_1.default('root', {
      | ^  178 |   focus: this.state.focus,
  179 |   'focus-visible': this.state.focusVisible
  180 | }, this.props)));
```

Any idea why? :pray:

### 👣 Steps to Reproduce

[webpack.config](https://github.com/RazLandau/test-wix-ui/blob/master/config/webpack.config.js)
[package.json](https://github.com/RazLandau/test-wix-ui/blob/master/package.json)
[repo](https://github.com/RazLandau/test-wix-ui)

**Comment by shlomitc** [comment]
Can you try to install all stylable dependencies with ‘@1’ notation? I think that v2 of stylable has some API breaking changes

**Comment by RazLandau** [comment]
Damn that was fast! Thanks a ton 🙏🙏 
For future references, I would add that for this solution to work I also had to change in webpack.config.js this line :
`const {StylableWebpackPlugin} = require('@stylable/webpack-plugin');`
to this:
`const StylableWebpackPlugin = require('@stylable/webpack-plugin');`

**Comment by shlomitc** [comment]
It will be great if you can make a Pull Request with these changes. Thanks!

**Comment by RazLandau** [comment]
I celebrated prematurely :(
Now things looks messed up:
 
![image](https://user-images.githubusercontent.com/18150955/62396604-433aa600-b57c-11e9-89d0-2d34da6fc55c.png)

Do you prefer I open a new issue?
