### ISSUE TITLE
Cheatsheet - add "table of contents" navbar

### ISSUE THREAD

**Issue by mosheKerbel** [wix/wix-style-react#3885]
Add something in the idea of the attached image that will navigate into anchor links of the different families.

![image](https://user-images.githubusercontent.com/7388217/62425827-5ff2ed00-b6e6-11e9-9a24-f6fc8ed49ceb.png)

@TalZa1810

**Comment by shlomitc** [comment]
added to the main issue
https://github.com/wix/wix-style-react/issues/3997
