### ISSUE TITLE
UniDriver - update major version adapters

### ISSUE THREAD

**Issue by mosheKerbel** [wix/wix-style-react#3886]
Update adapters to latest major version
1. protractor - will release soon a major [version](https://github.com/wix-incubator/unidriver/pull/89) with protractor 6 while we use protractor 5.
2. puppeteer - check the status
3. jsdom - we are fine

**Comment by shlomitc** [comment]
jsdom comes from yoshi.
puppeteer we don't use in wix-style-react so I don't think we need to do anything.
regarding protractor - is there an issue with is currently?

**Comment by EgoziE** [comment]
protractor v5 is for node 8 only
I think we should invest the time to update

**Comment by EgoziE** [comment]
Moved to Jira - https://jira.wixpress.com/browse/DSM-934
Closing
