### ISSUE TITLE
<Notification.ActionButton> is broken with defualt onClick 

### ISSUE THREAD

**Issue by liorur** [wix/wix-style-react#3889]
# 🐛 Bug Report

### 🏗 Relevant Components

 <Notification.ActionButton>

...

### 😯 Current Behavior

if we pass
```
 <Notification.ActionButton
            target={'_blank'}
            link={someLinl}
            type="textLink">
            {someText}
 </Notification.ActionButton>
```
then the default on click prevents the link from working

### 🤔 Expected Behavior

the default onClick should return true, or be removed altogether so the link can work

...

### 👣 Steps to Reproduce

just render the component

  - **WSR version**: latest
  - **Yoshi version**: latest

### 👀 Severity

 Low

**Comment by shlomitc** [comment]
it's because of defaultProps `onClick: e => e.preventDefault()`. It should just be removed in my opinion.

As a workaround, just passing some `onClick` works
```jsx
  <Notification show>
    <Notification.TextLabel>This notification has</Notification.TextLabel>
    <Notification.ActionButton
      type="textLink"
      target="_blank"
      link="http://www.wix.com"
      onClick={() => null}
    >
      text link action
    </Notification.ActionButton>
    <Notification.CloseButton />
  </Notification>
```
