### ISSUE TITLE
removing dataHook from "regular" input broke existing projects

### ISSUE THREAD

**Issue by yanivefraim** [wix/wix-style-react#389]
https://github.com/wix/wix-style-react/commit/473f2a38e239fb90fb19e6fcac39860b4a325cf1#diff-deaeb5c7e253bfa4f497fa8ace0b3607L178

projects using dataHooks to select `Input` in their tests are now broken. Maybe solution is to have it only on Input (currently it is on `ThemedInput`)

**Comment by nirhart** [comment]
Each component should be import using one of the two:
1) import Component from 'wix-style-react/dist/src/Component
2) import {Component} from 'wix-style-react'

Please do not import Component like this:
import Component from 'wix-style-react/dist/src/Component/Component
