### ISSUE TITLE
Not possible to give a value for GoogleAddressInput

### ISSUE THREAD

**Issue by mastertheblaster** [wix/wix-style-react#39]
I would like to give a value for this component.

```js
<GoogleAddressInput
  value={this.state.address}
  onChange={address = this.setState({address}) />
```

**Comment by 3LOK** [comment]
Hi,

The component currently accepts values in one of two ways:

 - controlled: Using the 'value' prop - note, the value is string only, just like onChange returns.
 - uncontrolled: Using the 'defaultValue' prop.

Both are working.
