### ISSUE TITLE
<ModalPreviewLayout/> - improve docs with examples

### ISSUE THREAD

**Issue by nitayneeman** [wix/wix-style-react#3903]
Currently, the playground is disabled - we should fix it.

Also, we should add examples with descriptions for correct usage:

- Modal with title, actions and inner content
- Modal with title, actions and full-width content

**Comment by nitayneeman** [comment]
This branch has started to apply the changes above:
https://github.com/wix/wix-style-react/tree/ModalPreviewLayout/fix-playground

**Comment by nitayneeman** [comment]
As part of this effort, we should align the examples according to:

> 5. Spacings between the buttons should be 12px.
> 
> 6. Action area left to right:
> 
> * The secondary button is a Text Button, Small, Light, Underline: None, Affix: Prefix.
> * Primary action button is a Button, Small, Light, Secondary.
> * More action button is an Icon Only Button, Small, Light Secondary.

https://github.com/wix/wix-style-react/pull/3773#issuecomment-518612129

**Comment by nitayneeman** [comment]
@ZilvinasMaciulis I fixed the docs according to the instructions above and added some examples:
https://wix-wix-style-react-pr-3971.surge.sh/?activeTab=Description&addons=0&full=0&panelRight=0&selectedKind=WIP&selectedStory=ModalPreviewLayout&stories=1

Let me know if we still have docs issues.

**Comment by ZilvinasMaciulis** [comment]
Great!

1. Only there is a thing with image resizing in the second example. On screen resize, the image should scale maintaining its original proportions & not squish or stretch as it does now.

2. The title should be "Small, Normal"

3. Can't see the navigation arrows. We will have to add it as an example.


Also I will work on descriptions and examples.
