### ISSUE TITLE
Wrong selection styles for input in safari.

### ISSUE THREAD

**Issue by rudnitskih** [wix/wix-style-react#3910]
# 🐛 Bug Report

### 🏗 Relevant Components

`<Input />`

### 😯 Current Behavior
Wrong selection styles for input in safari.

Safari:
![image](https://user-images.githubusercontent.com/8848858/62696866-10603a00-b9e2-11e9-830d-5947d4b5298b.png)

Chrome:
![image](https://user-images.githubusercontent.com/8848858/62696894-240ba080-b9e2-11e9-829a-a6b79895c99f.png)

### 🤔 Expected Behavior

Correct selection styles

### 👣 Steps to Reproduce

Open Input storybook in Safari - https://wix-wix-style-react.surge.sh/?selectedKind=3.%20Inputs&selectedStory=3.1%20Text%20Input&full=0&addons=0&stories=1&panelRight=0

  - **WSR version**: latest
  - **Yoshi version**: not relevant

### 👀 Severity

Our designer wants to cry :) 

- Major

**Comment by EgoziE** [comment]
PR - https://github.com/wix/wix-style-react/pull/4177

**Comment by rudnitskih** [comment]
@EgoziE Thanks a lot!
