### ISSUE TITLE
`<PopoverMenu/>` - beta - when appendTo="window" clicking component jumps  up in the page

### ISSUE THREAD

**Issue by mykas** [wix/wix-style-react#3912]
#3391 🐛 Bug Report

### 🏗 Relevant Components

`<PopoverMenu/>` beta. 

### 😯 Current Behavior

![PopoverMenu_Beta_jump](https://user-images.githubusercontent.com/8919190/62701461-0263e680-b9ed-11e9-833f-bee32fbfb2fb.gif)

### 🤔 Expected Behavior

Page should not jump around like that.

### 👣 Steps to Reproduce

Go to `<PopoverMenu/>` beta docs and add `appendTo="window"` and click on the icon button.

### 👀 Severity

- Major

**Comment by shlomitc** [comment]
is this a storybook bug and live examples bug or real issue?

**Comment by mykas** [comment]
Not sure. But it shouldn't happen in storybook too. It does not happen with other types of component that uses appendTo="window"

**Comment by mykas** [comment]
Fixed
