### ISSUE TITLE
`textTestkitFactory` `getText` returns `innerHTML`

### ISSUE THREAD

**Issue by varzager** [wix/wix-style-react#3936]
I'm using `Text` and have inside `[some text] <a ...>[some other text]</a>`.
in the tests i want to use `textTestkitFactory(...).getText()`, but the result is wrong.

**expected**: `[some text] [some other text]` (`innerText`)
**actual**: `[some text] <a ...>[some other text]</a>` (`innerHTML`).

is this done on purpose, why not return `innerText`?

**Comment by mykas** [comment]
Well, honestly I think that the feature to support anchor links inside the Text came after this testkit method has been introduced. You could open PR for this, but I think that there are users who are depending on this kind of working so it is how it is now. You could add getInnerText() method though.
