### ISSUE TITLE
AppliTools 

### ISSUE THREAD

**Issue by mosheKerbel** [wix/wix-style-react#3945]
Job `test2` is responsible for running the visual tests, send the snapshots and get the feedback from AppliTools.
We currently have ~536 tests
I've seen PR's that run only 6 tests or 33 tests.
AppliTools claim that in these specific cases they don't even get the screenshots, implying that the problem is on our side.

this is a valid one that was triggered by a pull request and ran all 536 tests
https://eyes.applitools.com/app/test-results/00000251836648266240/?accountId=mE99eP8CUn9UTSXSv98L3OSaJ0NZmAcY6Wndx6WSHODdY110

this is a *bad* one that was triggered by another pull request and ran only 33 tests
https://eyes.applitools.com/app/test-results/00000251836616744872/?accountId=mE99eP8CUn9UTSXSv98L3OSaJ0NZmAcY6Wndx6WSHODdY110

Severity level: Critical

@shlomitc

**Comment by mosheKerbel** [comment]
Job `test2` is responsible for running the visual tests, send the snapshots and get the feedback from AppliTools.
We are currently have ~536 tests
I've seen PR's that run only 6 tests or 33 tests.
AppliTools claim that in these specific cases they don't even get the screenshots, implying that the problem is on our side.

this is a valid one that was triggered by a pull request and ran all 536 tests
https://eyes.applitools.com/app/test-results/00000251836648266240/?accountId=mE99eP8CUn9UTSXSv98L3OSaJ0NZmAcY6Wndx6WSHODdY110

this is a *bad* one that was triggered by another pull request and ran only 33 tests
https://eyes.applitools.com/app/test-results/00000251836616744872/?accountId=mE99eP8CUn9UTSXSv98L3OSaJ0NZmAcY6Wndx6WSHODdY110

Severity level: Critical

@shlomitc

**Comment by shlomitc** [comment]
is this still relevant?

**Comment by mosheKerbel** [comment]
I didn't run into it, but it doesn't mean that it's not happening anymore.
I guess we need to go over bunch of PRs and check them.

**Comment by shlomitc** [comment]
so I'm closing and let's re-open if it's still relevant. thanks
