### ISSUE TITLE
InputWithOptions options - Tooltip on ellipsis <Text> not shown

### ISSUE THREAD

**Issue by adimorwix** [wix/wix-style-react#3948]
# ✨ Feature Request
Hi,
We using InpuWithOptions component.
The tooltip of ellipsis not shown

![image](https://user-images.githubusercontent.com/47712745/63028780-1f4e5d00-beb8-11e9-9fc2-1d1397662e88.png)

for example:
<InputWithOptions
         options={[
           {
             id: ‘0’,
             value: (
               <Box width={‘30px’}>
                 <Text ellipsis>First option</Text>
               </Box>
             ),
             overrideStyle: true
           }
         ]}
       />

### 💁 Explanation
In option with Text ellipsis, we should open a tooltip with full text

WSR -zeplin:
![image](https://user-images.githubusercontent.com/47712745/63028716-09409c80-beb8-11e9-97cd-6bf2f4582b04.png)

### 👀 Severity

-Major

Thanks
Adi

**Comment by shlomitc** [comment]
there are two issues here.
1. it's a missing feature for the default item in the `DropdownLayout` component.
2. the `InputWithOptions` is blocking the hover event. even when composing list items such as `ContactItemBuilder`, it does not work. as you can see in its story - it does work
https://wix-wix-style-react.surge.sh/?selectedKind=WIP%2FBuilders&selectedStory=ContactItemBuilder&full=0&addons=0&stories=1&panelRight=0

![image](https://user-images.githubusercontent.com/6093192/63501465-5afaaf80-c4d4-11e9-80f0-552a27031ca2.png)

But when composed in `InputWithOptions` options prop it doesn't.


So I think the second issue should be resolved, and then the first will be by implementing `ListItemSelect` https://zpl.io/2yqAzeG

**Comment by EgoziE** [comment]
`ListItemSelect` is released, closing this issue.
