### ISSUE TITLE
Storybook - some links are broken

### ISSUE THREAD

**Issue by mosheKerbel** [wix/wix-style-react#3950]
![image](https://user-images.githubusercontent.com/7388217/63080114-edd1a200-bf48-11e9-99c5-9f17fdf5eb8e.png)

These 2 links are broken

**Comment by shlomitc** [comment]
We’re using the same readme file both for the repo and for the storybook, and when relative links are used, they will not be applied in the storybook.

I think it’s best that we’ll have a separate introduction file for the storybook documentation

**Comment by mosheKerbel** [comment]
> when relative links are used, they will not be applied in the storybook
would it be a bad idea to make the links static?

> I think it’s best that we’ll have a separate introduction file for the storybook documentation
other motivation behind it except for this broken links?

**Comment by shlomitc** [comment]
> would it be a bad idea to make the links static?
yes, because then you won't be able to make them branch-related as they only point master. worth checking if `storybook` has some kind of integration for it.

have a more fancy introduction to the documentation which is not just a simple markdown file. make it more colorful and inviting.

**Comment by shlomitc** [comment]
fixed
