### ISSUE TITLE
Storybook - nest ux stories

### ISSUE THREAD

**Issue by mosheKerbel** [wix/wix-style-react#3951]
**Desired behaviour:**
![image](https://user-images.githubusercontent.com/7388217/63081679-e7452980-bf4c-11e9-8ca0-d0d71fb3c166.png)

**After expand:**
![image](https://user-images.githubusercontent.com/7388217/63081720-02179e00-bf4d-11e9-96db-c8ff5ce0d3f5.png)

**Motivation:**
Developers would enter directly the components section and won't get lost in other similiar ux stories.

**UX** is of course just a temp name, i just wanted to demonstrate the structure.

Effected areas that need to take under consideration:
1. links - should not get broken
2. tests - should not get broken

@shlomitc  @argshook @gilmeir

**Comment by shlomitc** [comment]
makes sense to me. I would go with a name like `Style Guide` that suggests you'll see layout related or use-case related example.

**Comment by mykas** [comment]
Lets talk before we do this. This was already was suppose to be done previously and the components folder should be called `API` instead of `Components`.

**Comment by EgoziE** [comment]
There are big plans for improving Storybook, Jira tickets overflowing.
I'm closing this one :)
