### ISSUE TITLE
Resolve Stylable warning for missing native css functions

### ISSUE THREAD

**Issue by gilmeir** [wix/wix-style-react#3965]
We get that warning on our logs, 
but also our **clients** are getting that, below is an example.

Following a previous talk with @tomrav this should be fixed in Stylable v2.

References:
https://wix.slack.com/archives/CH32ANHNF/p1563108886001300
https://github.com/wix/stylable/issues/698

Warning:
```js
WARNING in Stylable: /Users/gilme/projects/Mobile-Settings-Tab/node_modules/wix-style-react/dist/src/Swatches/Swatches.st.css:27:26: cannot find native function or custom formatter called repeat

  25 | }
  26 | .root:size(small) {
> 27 |   grid-template-columns: repeat(auto-fill, 24px);
     |                          ^
  28 | }
  29 | .root:size(medium) {

WARNING in Stylable: /Users/gilme/projects/Mobile-Settings-Tab/node_modules/wix-style-react/dist/src/Swatches/Swatches.st.css:30:26: cannot find native function or custom formatter called repeat

  28 | }
  29 | .root:size(medium) {
> 30 |   grid-template-columns: repeat(auto-fill, 40px);
     |                          ^
  31 | }
```

**Comment by EgoziE** [comment]
Relevant only to wsr 6
@shlomitc can we close it as `won't fix`?

**Comment by shlomitc** [comment]
Hey. it's relevant also for WSR7, but migrating to stylable2 (now 3) will take some time and not yet prioritized.
So it might be fixed in the future, but I can't promise when

**Comment by EgoziE** [comment]
In wsr7 swatches style was switched to scss, so I'm switching this issue off.
