### ISSUE TITLE
Input prefix vertically misaligned on Safari

### ISSUE THREAD

**Issue by tqmukas** [wix/wix-style-react#397]
My guess it's because of this:
https://github.com/wix/wix-style-react/blob/master/src/Input/Input.scss#L65

![screen shot 2017-04-13 at 17 40 18](https://cloud.githubusercontent.com/assets/6513105/25010609/5290819c-2073-11e7-894c-b95c492b4d86.png)

**Comment by argshook** [comment]
@tqmukas please check if you still see this. I'm looking with safari 10.1.2 (12603.3.8) and it's okay for me
