### ISSUE TITLE
6.1 Sidebar - links to components don't work as expected

### ISSUE THREAD

**Issue by TalZa1810** [wix/wix-style-react#3980]
# Documentation Issue

### 🔦 Scope

Relevant Page URL: https://wix-wix-style-react.surge.sh/?selectedKind=6.%20Navigation&selectedStory=6.1%20Sidebar&full=0&addons=0&stories=1&panelRight=0

### 💁 Explanation
All links to components `<SidebarHeader/>`, `<SidebarDivider/>`, `<SidebarSectionTitle/>` and `<SidebarSectionItem/>` are redirected to WIP page even though there are documentation for them: 
https://wix-wix-style-react.surge.sh/?selectedKind=WIP&selectedStory=What%20is%20this%3F&full=0&addons=0&stories=1&panelRight=0

### 👀 Severity
- [ ] Major
- [x] Low

**Comment by TalZa1810** [comment]
FYI @nitayneeman

**Comment by shlomitc** [comment]
if it's a quick fix, do you mind changing it?
