### ISSUE TITLE
Multiselect: Caret "jumps" when used with `customSuffix`

### ISSUE THREAD

**Issue by b3llash** [wix/wix-style-react#3985]
# 🐛 Bug Report

### 🏗 Relevant Components
`Multiselect`

### 😯 Current Behavior
When used with `customSuffix`, input receives focus before the suffix disappears, which makes the caret to jump.
[Demo](https://i.gyazo.com/bb19639e00a3bad74891a369866b352b.gif)

### 🤔 Expected Behavior
Hide suffix before the input receives focus.

### 👀 Severity
Low

**Comment by EgoziE** [comment]
PR - https://github.com/wix/wix-style-react/pull/4384
