### ISSUE TITLE
Multiselect: layout breaks with long Tags

### ISSUE THREAD

**Issue by b3llash** [wix/wix-style-react#3986]
# 🐛 Bug Report

### 🏗 Relevant Components
`Multiselect`

### 😯 Current Behavior
Text overflows Tag (https://pasteboard.co/ItwJktP.png)

### 🤔 Expected Behavior
Limit the Tag width and show an ellipsis(?)

### 👀 Severity
Low

**Comment by nitayneeman** [comment]
Talked to @LittleTal.

In the case of `MultiSelect` the tags will have `maxWidth` according to the parent width (the input) with an ellipsis.

FYI @shlomitc

**Comment by EgoziE** [comment]
PR - https://github.com/wix/wix-style-react/pull/4180
