### ISSUE TITLE
Cheatsheet- tasks list

### ISSUE THREAD

**Issue by TalZa1810** [wix/wix-style-react#3997]
### 🔦 Scope

Relevant Page URL: 
https://wix-wix-style-react.surge.sh/?selectedKind=Introduction&selectedStory=Components%20Cheatsheet&full=0&addons=0&stories=1&panelRight=0

#### Missing features:
- [ ] 1. Adding `Internal Components` section for components that are not in the index (for example `<DropdownBase/>`).

2. Adding examples to Cheatsheet of : 
- [x] `Sidebar` 
- [x] `ModalPreviewLayout ` 
- [x] `GoogleAddressInput` 
- [x] The updated `StatisticsWidget`, 
- [x] `ToggleButton` (currently is not mapped as 5.6)
- [x] The _Indication_ & _Presence_ of `Avatar`.

- [x] 3. Adding the `Foundation` section: 
   **Important:** Typography ( `Text`, `Heading`) , Icons
   **Less important:** Color, Spacing, Shadows, etc...
Related PR:  https://github.com/wix/wix-style-react/pull/4038

- [ ] 4. Adding the `Cheatsheet` to the generator so that when we generate a new component with the generator, a placeholder of the component will be added automatically to the `Cheatsheet`.

- [x] 5. Improving the example of `Tags Input` to be **Tag Input**.

- [x] 6. Remove `Green modal` example.

Related PR: https://github.com/wix/wix-style-react/pull/4016

#### Nice To Have:

- [ ] 7. Adding a description below the Components to explain the main usage of the components.

- [ ] 8.  Adding a Collapse / Expand feature. 

- [ ] 9. Converting the **linkTo** to **hrefTo** in the to be able to open a link in a new tab (file- `storybookMapping.js`) and converting the `<ComponentStorybookName/>` and `<ComponentsNames/>` components to support this.

- [ ] 10. Adding Virtualization to the page rendering instead of rendering all families at once (to improve the page performance). 

- [ ] 11. Adding search and/or adding “table of contents” navbar 
![image](https://user-images.githubusercontent.com/7388217/62425827-5ff2ed00-b6e6-11e9-9a24-f6fc8ed49ceb.png)

- [ ] 12. Support anchors - be able to send a link to a specific section.
![image](https://user-images.githubusercontent.com/7388217/65052218-dc7a1c00-d972-11e9-8768-4c3dc705aabe.png)

#### Out of scope

12. Move all components to the "Components" section. Some of the components have just a story without component documentation and vice versa. For example, we have `5.1 Button` but we don’t have `<Button/>` documentation (it’s kinda mixed).

13. Thinking about how to import existing complicated examples instead of duplicating them (as we saw with the `Table` & `Page` examples).

**Comment by TalZa1810** [comment]
Hi @ayeletr and @shlomitc ,
Here's a summary of the tasks we discussed yesterday (in addition to the tasks added above):
1. `Buttons`, `Navigation`, `Notification` families- adding the links to the components
2. `<Tooltip/>`- instead of `Hover Me` text, should be changed to `Small / Medium Tooltip`. @ayeletr  please update regarding the Tooltip text itself. 
3. `<Popover/>`- delete the text "Popover on the right" and change the Poover text to be `"Custom Floating Content"`. Moreover, the `svg` image should be updated. @ayeletr , let me know which `svg` image should be displayed instead. 
4. `8.1 Notification` - Remove `Reset` button.
5. `8.2 Floating Notification` & `8.3 Section Helper`- update the text as described in the Zeplin.
6. Modal family `9.2 Content` - adding an example of a `<MessageBoxFunctionalLayout/>` with a form (the example of adding a new product). 
7.  Modal family `9.3 Marketing`- adding the Blue example of the `<MessageBoxMarketerialLayout/>`
8. `ColorPicker`- adding a link to the `Swatches` component.
9. `Page Layout`- removing the link to the `Layout` component.
10. Other Family `Badge`- change the examples display to be 2 columns instead of 2 rows.
11. Other Family `Tag`- adding a Tag with an `<Avatar/>`.
12. `<CardGalleryItem/>` - change the size of the example to be fixed and update the example to demonstrate a real use case.
13. Adding a placeholder for the [Omni Setup](https://github.com/wix/wix-style-react/issues/4003).
14. Features to consider adding in the future:
- Collapse / Expand
- Adding a description below the `Components` to explain the main usage of the components. 


Let me know if you have anything else to add or comment :)

**Comment by TalZa1810** [comment]
Cheatsheet fixes and additions PR: https://github.com/wix/wix-style-react/pull/5041

**Comment by EgoziE** [comment]
Closing this issue, if something is still missing please open in Jira.
