### ISSUE TITLE
Beta <PopoverMenu/> - deprecate old popover from the storybook

### ISSUE THREAD

**Issue by shlomitc** [wix/wix-style-react#4000]
# ✨ Feature Request
`<PopoverMenu/>`

### 🔦 Scope
old PopoverMenu should be moved from the storybook documentation into the deprecated section.

Also - the new popover should be available through the playground and not just in its page doc.

### 💁 Explanation
Components/PopoverMenu => Deprecated/PopoverMenu

Also, the test file should be moved
Tests/7. Tooltip/ 7.3 PopoverMenu => try to move to visual or just rename to Tests/Deprecated/PopoverMenu

regarding the playground, either create a new `Beta` scope or decide to merge it with the `Components` and create a `Deprecated` scope for old components

**Comment by mykas** [comment]
Fixed
