### ISSUE TITLE
<VerticalTabs/> - Create new component

### ISSUE THREAD

**Issue by mosheKerbel** [wix/wix-style-react#4002]
# ✨ Feature Request

### 🔦 Scope

`<VerticalTabs/>`

### 💁 Explanation

A request for a new component - [VerticalTabs](https://app.zeplin.io/project/5c8f6f1f9f489505cac756dc/screen/5d3030d7a4f29f5171bb9dce) | [IC. Vertical Tab Items](https://app.zeplin.io/project/5c8f6f1f9f489505cac756dc/screen/5d3060870184ff8e0db1b202)
![image](https://user-images.githubusercontent.com/7388217/63634884-2cf8a500-c665-11e9-9467-a3c0fabcba7d.png)

### 🐾 Possible solution 

Below is a code snippet for an interface for a suggested API, together with an example of how to use it.
Below the code snippet there is a suggested development workflow.
```
import React from 'react';
import PropTypes from 'prop-types';

const Prefix = ({children}) => {};
Prefix.PropTypes = {
  children: PropTypes.node, // <Icon/>
};

const Suffix = ({children}) => {};
Suffix.PropTypes = {
  children: PropTypes.node, // <PopoverMenu/>, <Icon/>, <IconButton/>
};

const Footer = ({children}) => {};
Footer.PropTypes = {
  children: PropTypes.node, // <TextButton/>
};

const Tab = (props) => {};
Tab.PropTypes = {
  disabled: PropTypes.bool,
  children: PropTypes.node, // <Tab.Suffix/>, <Tab.Text/>, <Tab.Prefix/>
};

const TabsGroup = props => {};
TabsGroup.PropTypes = {
  category: PropTypes.string,
  children: PropTypes.node, // <VerticalTabs.Tab/>
};

class VerticalTabs extends React.Component {
  static TabsGroup;
  static Tab;
  static Footer;

  static PropTypes = {
    size: PropTypes.string,
    activeTabId: PropTypes.number
    onChange: PropTypes.func,
    children: PropTypes.node, // <VerticalTabs.TabsGroup/>, <VerticalTabs.Footer/>
  }

  /*
  *  Create context to inject Size prop
  *  Render children
  *  Each child will consume the `size` prop and apply it on itself
  *  Each child will apply the WSR styles itself
  *  All logic - State management, mouse and keyboard interactions, aria-labels will be done at a different layer of base components (Render Props)
    ** TabsGroups
      *** Category
      *** Tab (clickable) - Render
        **** Prefix
        **** Text
        **** Suffix
   */
}

// ====================================================
// Usage
// ====================================================

<VerticalTabs size="small" activeTabId={2} onChange={id => {}}>
  <VerticalTabs.TabsGroup category="category1">
    <VerticalTabs.Tab id={0}>
      <VerticalTabs.TabPrefix>
        <Bullet />
      </VerticalTabs.TabPrefix>
      <VerticalTabs.TabText>Option 1</VerticalTabs.TabText>
      <VerticalTabs.TabSuffix>
        <IconButton onClick={console.log('simulate remove')}>
          <Remove />
        </IconButton>
      </VerticalTabs.TabSuffix>
    </VerticalTabs.Tab>
    <VerticalTabs.Tab id={1} disabled>
      <VerticalTabs.TabText>Some disabled tab</VerticalTabs.TabText>
    </VerticalTabs.Tab>
  </VerticalTabs.TabsGroup>
  <VerticalTabs.TabsGroup category="category2">
    <VerticalTabs.Tab id={2}>
      <VerticalTabs.TabText>Something complexed</VerticalTabs.TabText>
      <VerticalTabs.TabSuffix>
        <PopoverMenu
          triggerElement={
            <IconButton priority="secondary">
              <More />
            </IconButton>
          }
        >
          <PopoverMenu.MenuItem text="option 1" onClick={e => console.log(e)} />
          <PopoverMenu.MenuItem text="option 2" onClick={e => console.log(e)} />
          <PopoverMenu.MenuItem text="option 3" onClick={e => console.log(e)} />
        </PopoverMenu>
      </VerticalTabs.TabSuffix>
    </VerticalTabs.Tab>
  </VerticalTabs.TabsGroup>
  <VerticalTabs.Footer>
    <TextButton
      prefixIcon={<PlusSign />}
      onClick={console.log('simulate add item')}
    >
      Add New
    </TextButton>
  </VerticalTabs.Footer>
</VerticalTabs>;
```

**Suggested workflow:**
1. `<VerticalTabs/>` should be a visual component which render tabs on vertical orientation with WSR themes.
2. `<BaseTabs\>` should be a base layer component that supply states, mouse and keyboard interactions and aria props. (see [downshift](https://github.com/downshift-js/downshift)).
3. Because `<BaseTabs\`> does not render anything but it's children, it's natural location would be inside `wix-ui-core`, but in order to ease the development process i suggest creating it inside a `core` directory inside `VerticalTabs`, and later on we would extract it to `wix-ui-core`.
4. `<BaseTabs/>` can later on be used to refactor WSR `<Tabs/>` which is not accessible at all. Of course can be used also for other libraries while sitting inside `wix-ui-core`

**Other thoughts:**

`wix-ui-core` has `<Dropdown/>`
`wix-style-react` has `<DropdownBase/>` and `<DropdownLayout/>`
All of these looks similar to `<VerticalTabs/>` so shouldn't we be using them?

IMO no, why?
1. `Tab` keypress is behaving differently as expected - selecting, which does not make sense in our `<VerticalTabs`/> case
2. Mechanisms are different - `<Popover/>` is being used which enlarge bundle size, though it is not needed at all for the `<VerticalTabs/>`
3. Large refactor - Though there are similarities, there are also differences which requires refactor, e.g - the Tab keypress in point 1. The way these components are written - these kind of refactors are hard and risky and the benefit is not that big, so it does not worth it in my opinion.

**Comment by EgoziE** [comment]
Moved to Jira - https://jira.wixpress.com/browse/DSM-139
