### ISSUE TITLE
<OmniSetup> - new component

### ISSUE THREAD

**Issue by mosheKerbel** [wix/wix-style-react#4003]
# ✨ Feature Request

### 🔦 Scope
[12.8 Omni Setup](https://zpl.io/2GWDKRY)
![image](https://user-images.githubusercontent.com/7388217/63636282-0000be00-c676-11e9-9988-f548ee21c8b2.png)
...

### 💁 Explanation

Not sure yet wether it should become a reusable component inside WSR, or just an instance of composition. Examples for a reusable composite component: `<CalendarPanel/>`

### 🐾 Possible solution 

Composition of the following:
`<Card/>` `<VerticalTabs/>` `<SomeNode/>`

**Comment by EgoziE** [comment]
Moved to Jira - https://jira.wixpress.com/browse/DSM-139
