### ISSUE TITLE
<Dropdown/> - documentation page misleading, suffix icons are wrong, infinite scroll is broken

### ISSUE THREAD

**Issue by shlomitc** [wix/wix-style-react#4004]
# Documentation Issue

### 🔦 Scope
The revised Dropdown docs contain incorrect implementation

### 💁 Explanation
1. prefix and suffix icons - the implementation used is with the `Input.Unit`'s compound component. This works in the example but not relevant for real-life examples.
Also, the title of the example is mentioning Input which is incorrect

![image](https://user-images.githubusercontent.com/6093192/63637850-292b4980-c68a-11e9-9347-6ef684709634.png)

2. the infinite scroll example is very long, not clear enough and also not working as expected.
a. In real-life examples, an initial value is set, and only then more values are fetched.
b. the infinite scroll is broken and displays a lot of white space. It might be related to the implementation, but could also be a broken feature so worth checking this out

![image](https://user-images.githubusercontent.com/6093192/63637909-c0909c80-c68a-11e9-9f54-76a44074e2b5.png)

**Comment by mykas** [comment]
Dont understand whats the problem with suffix and prefix using compound? As far as I remember this was NitayR feature to support proper spacing with this compound component. Does this mean that this unit should be explained more?

**Comment by shlomitc** [comment]
Check the example - it points that you need to import the input component in order to consume this functionality

**Comment by mykas** [comment]
Yes, but that was the point as I remember. I don't agree on this, but this was sort of way that was done. If you pass just suffix without Input you will not get the official spacings.

**Comment by mykas** [comment]
So maybe this should be fixed in the Dropdown to use the compound components under the hood.

**Comment by shlomitc** [comment]
Right, Dropdown should declare on new prefix and suffix properties that points to the input prefix and suffix. Should be done in inputWithOptions

**Comment by EgoziE** [comment]
Most of it is done
Moved to Jira - closing
