### ISSUE TITLE
<Dropdown/> / <Autocomplete/> - add a buit-in auto-complete functionality

### ISSUE THREAD

**Issue by shlomitc** [wix/wix-style-react#4005]
# ✨ Feature Request

### 🔦 Scope
Selection family

### 💁 Explanation
Dropdown fits perfectly as a custom replacement for the native `select` element, but the **autocomplete** feature is not implemented.

The library exposes the `<Autocomplete/>` component, however as much promising it sounds, it's actually quite useless. In fact, all it does it just extending `<InputWithOptions/>` which makes it look like an input, but the consumer must implement the logic on its own.

The `<Search/>`component is actually providing already such behavior which is much better.

I suggest adding the functionality in a way it just works with zero configuration.
Since it's quite opinionated, allow a way to customize predicate for more complex usages or items that are not purely textual.

One possible option will be extending `<InputWithOptions/>` to achieve this functionality (and let all other extending components to enjoy this like MultiSelect, MultiSelectCheckbox, ...), or just find a solution for Dropdown/Autocomplete

**Comment by EgoziE** [comment]
Moved to Jira - closing
