### ISSUE TITLE
MessageBoxFunctionalLayout - duplication of the `Footnote` example

### ISSUE THREAD

**Issue by TalZa1810** [wix/wix-style-react#4009]
# Documentation Issue
A duplication of the `Footnote` example. 

### 🔦 Scope

Relevant Page URL: https://wix-wix-style-react.surge.sh/?selectedKind=Components&selectedStory=MessageBoxFunctionalLayout&full=0&addons=0&stories=1&panelRight=0

### 💁 Explanation

Should remove the duplication of the Footnote example:
https://github.com/wix/wix-style-react/blob/master/src/MessageBox/FunctionalLayout/docs/index.story.js#L78

### 👀 Severity

- [ ] Major
- [x] Low

**Comment by shlomitc** [comment]
please remove it.
thanks
