### ISSUE TITLE
Contribution guide - explain testing differences

### ISSUE THREAD

**Issue by mosheKerbel** [wix/wix-style-react#4012]
# Documentation Issue

### 🔦 Scope

Contribution guide -> Testing

### 💁 Explanation

We are testing our components using
- E2E with protractor
- Visual tests
- Unit tests

Guide is missing instructions for when to use each when writing a new component / adding features to an existing component.

Motivation: I got that input from a contributor that got lost in all of the test possibilities.

**Comment by shlomitc** [comment]
Isn't this guide enough? It might need some updating, but overall this should be the go-to guide.
https://github.com/wix/wix-style-react/blob/master/docs/contribution/TESTING.md

**Comment by mosheKerbel** [comment]
need to update this guide to say when to use each one

**Comment by shlomitc** [comment]
whenever you've got some time that would be great

**Comment by mosheKerbel** [comment]
will try to push it during the on call week, also added it to my own mini backlog.
