### ISSUE TITLE
[DropdownBase] - Documentation is outdated (UniDriver await) 

### ISSUE THREAD

**Issue by just-jeb** [wix/wix-style-react#4013]
# Documentation Issue

### 🔦 Scope

Relevant Page URL: 

https://wix-wix-style-react.surge.sh/?activeTab=Testkit&addons=0&full=0&panelRight=0&selectedKind=Components&selectedStory=DropdownBase&stories=1

### 💁 Explanation

TestKit APIs are missing return types and examples are outdated (showing the old way, not awaiting on results)

I'm pretty sure this is not the only page that has outdated examples that don't use UniDriver so probably it is worth to do a bulk update.

### 👀 Severity

- [x] Major
- [ ] Low

**Comment by shlomitc** [comment]
We actually don't have a return value at all. this is usually achieved in `jsdoc` comments, but I don't think it's implemented at the moment. @argshook - WDYT

**Comment by just-jeb** [comment]
Maybe we're talking about different things but here is a great example of docs with return values: https://wix-wix-style-react.surge.sh/?activeTab=Testkit&addons=0&full=0&panelRight=0&selectedKind=Components&selectedStory=Tooltip&stories=1

**Comment by shlomitc** [comment]
unfortunately, this example is completely manual
https://github.com/wix/wix-style-react/blob/master/src/Tooltip/TooltipNext/docs/README.TESTKIT.md

**Comment by just-jeb** [comment]
It's a pity. Well, updating the examples will imply the return type so it probably would be enough.

**Comment by argshook** [comment]
we have some return values coming from autodocs but it's not always easy to determine what is actually returned, so there are a lot of gaps.

either way, showing better unidriver use cases in testkit tab is a work in progress already
