### ISSUE TITLE
Floating Notification Component text does not get default font-family

### ISSUE THREAD

**Issue by yogevitz** [wix/wix-style-react#4018]
# 🐛 Bug Report

### 🏗 Relevant Components

Floating Notification

### 😯 Current Behavior

Floating Notification component texts do not get the default font-family as shown here:
https://wix-wix-style-react.surge.sh/?selectedKind=Tests%2F8.%20Notification%20Bars%2F8.2%20Floating%20Notification&selectedStory=1.%20All%20Variations&full=0&addons=0&stories=1&panelRight=0&activeTab=Description
I used a workaround by inserting a Text component into the Floating Notification's scope

### 🤔 Expected Behavior

Text with default font-family

### 👣 Steps to Reproduce

  - **WSR version**: `6.50.2`
  - **Yoshi version**: `3.31.2`

### 👀 Severity

- Low

**Comment by shlomitc** [comment]
can you create a reproducible example?
looks like styles are applied without any additions
![image](https://user-images.githubusercontent.com/6093192/63685878-2145e380-c809-11e9-87e4-ac5545e13308.png)

**Comment by yogevitz** [comment]
I have created a mock project and the font was okay - the issue is probably related to our page

**Comment by shlomitc** [comment]
ok, closing
