### ISSUE TITLE
No styling for Page component

### ISSUE THREAD

**Issue by RazLandau** [wix/wix-style-react#4020]
# 🐛 Bug Report

### 😯 Current Behavior

I followed [this](https://github.com/wix/wix-style-react/issues/3874) but got this:
![image](https://user-images.githubusercontent.com/18150955/63698135-e5ba1200-c826-11e9-97c8-7837377e04ec.png)

Any idea why? :pray:

### 👣 Steps to Reproduce

[webpack.config](https://github.com/RazLandau/test-wix-ui/blob/master/config/webpack.config.js)
[package.json](https://github.com/RazLandau/test-wix-ui/blob/master/package.json)
[repo](https://github.com/RazLandau/test-wix-ui)

**Comment by argshook** [comment]
Hey there!

sorry for late response. I checked out your repo and had to do this
change in `config/webpack.config.js`:

```diff
modified: config/webpack.config.js
@@ -42,7 +42,7 @@ const useTypeScript = fs.existsSync(paths.appTsConfig);
 const cssRegex = /\.css$/;
 const cssModuleRegex = /\.module\.css$/;
 const sassRegex = /\.(scss|sass)$/;
-const sassModuleRegex = /\.module\.(scss|sass)$/;
+const sassModuleRegex = /\.(scss|sass)$/;
```

create-react-app in its config has assumptions which are not true for
wix-style-react. In particular, create-react-app applies loaders for
specific file extensions which we don't use in wix-style-react.

in this case it's sass modules: we do not use `.module.scss`, we just
use `.scss`.

Please try and let us know if it works for you.

**Comment by mykas** [comment]
Closing.
