### ISSUE TITLE
9.4 Announcement - API description is partial 

### ISSUE THREAD

**Issue by TalZa1810** [wix/wix-style-react#4025]
# Documentation Issue

### 🔦 Scope
`<MessageBoxMarketerialLayout/>` API is partially documented. 

Relevant Page URL: https://wix-wix-style-react.surge.sh/?activeTab=API&addons=0&full=0&panelRight=0&selectedKind=9.%20Modals&selectedStory=9.4%20Announcement&stories=1

### 💁 Explanation
Some **propNames** are missing. For example: `imageComponent`.
We want to encourage our users to use SVGs, therefore we should add this to the documentation. 

### 👀 Severity

- [ ] Major
- [ ] Low

**Comment by EgoziE** [comment]
deprecated - closing
