### ISSUE TITLE
<Multiselect/> - tags should change color on hover

### ISSUE THREAD

**Issue by b3llash** [wix/wix-style-react#4041]
# 🐛 Bug Report

### 🏗 Relevant Components
`<Multiselect>` and `<Tag>`

### 😯 Current Behavior
When hovering tags in a Multiselect, their background color doesn't change.
Instead, the input itself gets into hover state, which is misleading.
https://i.gyazo.com/508b154e942ff4ca513e7fc28f1b312d.gif

### 🤔 Expected Behavior
Tags should respond to cursor (get into hover state, show tooltip or whatever behavior attached to them).
The input itself should get into hover state only when hovered (and not when the tags in it are hovered).

### 👀 Severity
Low

**Comment by shlomitc** [comment]
@milkyfruit what do you think?

**Comment by milkyfruit** [comment]
@b3llash @shlomitc tags themselves have hover styles: https://zpl.io/bzq6pJE
It definitely makes sense to show it when they're in the input too.

**Comment by shlomitc** [comment]
alright. added to our backlog

**Comment by argshook** [comment]
closed by https://github.com/wix/wix-style-react/pull/6114
