### ISSUE TITLE
Add prop to Tooltip for hyphens

### ISSUE THREAD

**Issue by brumeregan** [wix/wix-style-react#4042]
# ✨ Feature Request

### 🔦 Scope

Hi, I think it could be great if in Tooltip component we could manage if inner text will be with style `hyphens: auto` or not.
It could solve such design issues when we have long text, and need to limit maxWidth. But sometimes it could looks weird in the end 🥴
<img width="452" alt="Screen Shot 2019-09-02 at 4 55 51 PM" src="https://user-images.githubusercontent.com/6932807/64121172-bb2c0400-cda6-11e9-8702-8aef63fb6e2e.png">

### 👀 Severity

- Major

**Comment by brumeregan** [comment]
**Or** maybe you can find other solution for such behavior?) It would be great if in such cases Tooltip could decrease its width 😀

**Comment by shlomitc** [comment]
@milkyfruit - what do you think?

**Comment by milkyfruit** [comment]
@brumeregan @shlomitc I'm okey with adding `hyphens` prop.
I think, default value should be `hyphens="false"`, because often this property adds hyphens even when they aren't necessary.

**Comment by shlomitc** [comment]
@brumeregan - please contact @mykas regarding contributing this feature to the library

**Comment by EgoziE** [comment]
Closing due to lack of public interest.
If someone is willing  to contribute this in the future, we'll reopen it.
