### ISSUE TITLE
Icons - improving Icons documentation 

### ISSUE THREAD

**Issue by TalZa1810** [wix/wix-style-react#4056]
# Documentation Issue
Currently, all icons are being displayed as a bulk. 

### 🔦 Scope
Relevant Page URL: https://wix-wix-style-react.surge.sh/?selectedKind=1.%20Foundation&selectedStory=1.4%20Icons&full=0&addons=0&stories=1&panelRight=0

### 💁 Explanation
Improving `Icons` documentation to be displayed by category: `1.3 System Icons` & `1.4 General Use Icons` and according to groups ("Actions", "General", "Toggle" ....). 

**Note** that some of the icons are missing in the spec. Should be added to the Zeplin with the names of the icons. 

### 👀 Severity

- [ ] Major
- [x] Low

**Comment by shlomitc** [comment]
Will be fixed in this PR: https://github.com/wix/wix-style-react/pull/5327
