### ISSUE TITLE
<ColorPicker /> Add color tooltip is not centered

### ISSUE THREAD

**Issue by MSiliunas** [wix/wix-style-react#4057]
# 🐛 Bug Report

### 🏗 Relevant Components

`<ColorPicker />`

### 😯 Current Behavior

Add color tooltip not centered

![image](https://user-images.githubusercontent.com/6944305/64431664-921bb400-d0c3-11e9-9023-c29502a2def9.png)

### 🤔 Expected Behavior

The tooltip should be centered

### 👣 Steps to Reproduce

  - **WSR version**: latest

### 👀 Severity

- Low

**Comment by EgoziE** [comment]
PR - https://github.com/wix/wix-style-react/pull/4812
