### ISSUE TITLE
`<FormField/>` - smaller content is not centered

### ISSUE THREAD

**Issue by miroshSa** [wix/wix-style-react#4068]
# 🐛 Bug Report

### 🏗 Relevant Components

<ToggleSwitch>

### 😯 Current Behavior

The swither with the attribute `size="small"` is not aligned with text when it wrapped into `<FormField>`
![image](https://user-images.githubusercontent.com/11633395/64519934-c7134b00-d2fd-11e9-9d3f-4c06f0948783.png)

...

### 🤔 Expected Behavior

The swither with the attribute `size="small"` aligned with text when it wrapped into `<FormField>`

...

### 👣 Steps to Reproduce

```
<FormField
              infoContent={"some info"}
              label={"some label"}
              labelPlacement="right"
              stretchContent={false}
            >
              <ToggleSwitch
                size="small"
                checked={false}
              />
            </FormField>
```
...

  - **WSR version**: `6.54.2`
  - **Yoshi version**: `4.12.1`

### 👀 Severity

- Critical / Major / Low

**Comment by shlomitc** [comment]
@nitayneeman - I remember you handled such thing, can you assist?

**Comment by EgoziE** [comment]
Created a PR - https://github.com/wix/wix-style-react/pull/4151
