### ISSUE TITLE
Change small <FormField/> Info icon size 

### ISSUE THREAD

**Issue by LittleTal** [wix/wix-style-react#4083]
# ✨ Feature Request

### 🔦 Scope
`<FormField/>` 
Change info icon size for small label size prop

...

### 💁 Explanation

When changing `<FormField/>` label size to small, info icon should be 18px instead of 24px.

...

### 🐾 Possible solution 

...

### 👀 Severity

Low

**Comment by EgoziE** [comment]
`<FormField/>` label has 3 sizes: tiny, small, medium (default)
So 18px for small and 24px for meduim, what about tiny?

**Comment by LittleTal** [comment]
@EgoziE 
We should remove the tiny option and replace only the icon to 18px for small label size

**Comment by EgoziE** [comment]
Done

**Comment by EgoziE** [comment]
Will be published on version 7.3.0
