### ISSUE TITLE
MessageBoxFunctionalLayout - Add 'backgroundColor' property

### ISSUE THREAD

**Issue by liorcode** [wix/wix-style-react#4086]
# ✨ Feature Request

### 🔦 Scope

`<MessageBoxFunctionalLayout>` modal component

### 💁 Explanation

Add a "backgroundColor" property which would default to the current one (`white`)
e..g 
`<MessageBoxFunctionalLayout backgroundColor="D70"/>`

### 👀 Severity

Low

My current workaround is to render the element with `noBodyPadding` and then apply my own background, border-radius and padding, but that doesn't feel right.

**Comment by shlomitc** [comment]
@liorcode - why would you need to change the background color? can you share your Zeplin with the required UI?

**Comment by liorcode** [comment]
The premium-checkout components is in greyish background color, so we need the modal to also be the same color.
you can see their storybook here: https://wix-private-checkout-components.surge.sh (in "popup")
and our zeplin here: 
https://app.zeplin.io/project/5cab112ade731163f139f958/screen/5d6ccd92cdedf2a1ba70ebcf

**Comment by shlomitc** [comment]
@LittleTal / @milkyfruit  - are you familiar with this project?

**Comment by milkyfruit** [comment]
I know @wuwa is reviewing this project.
Regarding modal's background color – another product "Print Shop" requested for the same feature, in their case the footer remained white.
I suggested using noPadding prop together with a <Box/> component to achieve this result.

If we go with new background prop, I don't think that it should allow any color value, only predefined ones.

@wuwa what do you think?

**Comment by liorcode** [comment]
if you use `noBodyPadding`, you lose not only the padding (which we do want) but also the rounded corners, @milkyfruit

**Comment by LittleTal** [comment]
@liorcode it should be defined as a new prop according to content type, not just a background color selection. 
D70 will be used in case we have page content inside a modal, Similar example as @milkyfruit mentioned: https://zpl.io/bJ1vdXE
![image](https://user-images.githubusercontent.com/23282301/65154234-d0a25e80-da33-11e9-9f04-745c19ae445a.png)

**Comment by liorcode** [comment]
also good :)

**Comment by shlomitc** [comment]
Great.
@liorcode, please make a pullrequest with the required feature. I will make sure to assign a reviewer who can assist. contact me in private if it's your first contribution to the library

**Comment by EgoziE** [comment]
Component is deprecated - closing
