### ISSUE TITLE
`<MessageBoxFunctionalLayout/>` - migrate Buttons

### ISSUE THREAD

**Issue by mykas** [wix/wix-style-react#4094]
🐛 Bug Report

### 🏗 Relevant Components

`<Button/>`

### 😯 Current Behavior

The current Button is still used from Deprecated folder.

### 🤔 Expected Behavior

Should be new Button.

### 👀 Severity

- Low

**Comment by ipanasenko** [comment]
I wanted to create new issue, but I will just post it here. When cancel button is disabled, its font size is bigger. Confirm button is fine:
![image](https://user-images.githubusercontent.com/576152/68675931-9c45ad00-0561-11ea-8d9d-a523425de8d7.png)
![image](https://user-images.githubusercontent.com/576152/68675949-a49de800-0561-11ea-86c7-332c15857cbf.png)

Reproducible in Storybook: https://wix-style-react.now.sh/?selectedKind=Components&selectedStory=MessageBoxFunctionalLayout&full=0&addons=0&stories=1&panelRight=0&activeTab=Playground

**Comment by EgoziE** [comment]
Check also testkit

**Comment by TalZa1810** [comment]
Marik started to work on this in this PR:
https://github.com/wix/wix-style-react/pull/4647

**Comment by shlomitc** [comment]
@TalZa1810 but the PR is not yet merged, why did you close the issue?

**Comment by EgoziE** [comment]
Because its a duplicate
