### ISSUE TITLE
`<AutoComplete />` - add a feature to allow only values from options

### ISSUE THREAD

**Issue by mykas** [wix/wix-style-react#4095]
# ✨ Feature Request

### 🔦 Scope

`<AutoComplete/>` , `<InputWithOptions/>`  

### 💁 Explanation

When user enters some value in the input and leaves it by tabbing to next input in the form - the entered value is still there. There should be a feature to clear the value which is not valid by the available options.

![Value](https://user-images.githubusercontent.com/8919190/64849123-5d57b180-d61b-11e9-9d94-96b99410e797.gif)

### 👀 Severity

-  Low

**Comment by mykas** [comment]
@mastertheblaster

**Comment by shlomitc** [comment]
not in priority and will not be solved in the near future, closing
