### ISSUE TITLE
Notification bug with props show={false}

### ISSUE THREAD

**Issue by lbelinsk** [wix/wix-style-react#410]
I tried to render 
```<Notification show={false}.../>```

 and received the error:

![image](https://cloud.githubusercontent.com/assets/18248989/25242315/da35bf52-2601-11e7-8252-7076d17b9f06.png)

Nothing got rendered..

When I changed it to true it worked

**Comment by yardnsm** [comment]
I couldn't reproduce the issue. Rendering the notification with `show={false}` renders nothing (as expected) and throws nothing.
