### ISSUE TITLE
Docs - Layout & Grid to reference the Layout.md

### ISSUE THREAD

**Issue by mosheKerbel** [wix/wix-style-react#4101]
I find this [doc](https://github.com/wix/wix-style-react/blob/master/docs/usage/LAYOUTING.md) to be helpful
I think that consumers that are entering the `Grid` and `Layout` components docs in storybook could get more understanding of what they need if they go over this doc.

**Comment by shlomitc** [comment]
I'd like eventually to remove one of them. There shouldn't be two grid options.
When doing that, improving the docs and referencing to other places can be done.
Anyway, let's raise this concern again once we work on the components
