### ISSUE TITLE
Change disabled colors for <Input/> 

### ISSUE THREAD

**Issue by LittleTal** [wix/wix-style-react#4116]
# 🐛 Bug Report

### 🏗 Relevant Components
`<Input/>`

...

### 😯 Current Behavior
`<Input/>` background color in disabled is D10-05, and border is D10-30 

...

### 🤔 Expected Behavior
On disabled state, background color should be replaced with D80, and border color should be D10-20

...

### 👣 Steps to Reproduce

  - **WSR version**: `...`
  - **Yoshi version**: `...`

### 👀 Severity

Major

**Comment by EgoziE** [comment]
Hey Lital, 
Should all other input familiy components change accordingly?
<InputArea/>, <NumberInput/>, <ColorInput/>, etc..
We looked at Zeplin, and the colors seem not to be updated.

I fixed only the <Input/> at the moment:
https://github.com/wix/wix-style-react/pull/4118
Can you please review it?

Thanks

**Comment by LittleTal** [comment]
@EgoziE 
- Yes, all other input family should be updated accordingly.
- I will update zeplin (we haven't got a chance to do it yet)
- Fix looks good:)

**Comment by EgoziE** [comment]
Will be published on version 7.3.0
