### ISSUE TITLE
Notification testkit bug

### ISSUE THREAD

**Issue by lbelinsk** [wix/wix-style-react#412]
After using "clickOnCloseButton" I expect that 
```expect(driver.visible()).toBeFalsy()```
Will pass, but it doesn't (even if i use wixEventually)

https://github.com/wix/wix-style-react/blob/96bd8b9550436d2bc385986f778eef510baa0988/src/Notification/Notification.spec.js#L194

@nirhart

**Comment by lbelinsk** [comment]
I tried in a different project to use the notification testkit. I made sure the notification is visible but the testkit didn't work..

**Comment by shlomitc** [comment]
I tried both un-commenting the test and use the testkit and both works

With the testkit, it does work when polling using eventually (or using fake timers)
The reason it's async is the fade-out animation (350ms).

Is it still happening today?

```js
describe('App', () => {
  let wrapper;

  afterEach(() => wrapper.detach());

  it('should hide the notification bar', async () => {
    wrapper = mount(
      <ComponentWithNotification/>,
      {attachTo: document.createElement('div')}
    );

    const driver = notificationTestkitFactory({wrapper, dataHook: 'notification'});
    driver.clickOnCloseButton();
    await eventually(() => expect(driver.visible()).to.equal(false));
  });
});
```

**Comment by shlomitc** [comment]
@argshook - so is this one closed now?

**Comment by argshook** [comment]
Yes, we didnt see this issue anymore
