### ISSUE TITLE
<Checkbox/> - implement grouping and marker logic

### ISSUE THREAD

**Issue by shlomitc** [wix/wix-style-react#4126]
# ✨ Feature Request

### 🔦 Scope

`<Checkbox/>`

### 💁 Explanation

![image](https://user-images.githubusercontent.com/6093192/65048029-201d5780-d96c-11e9-843c-bacafa5026f3.png)

Need to add support for the marker logic (none, on hover, always).
It should also have a clickable area zone.
Consider if a new component is needed for the group (like RadioGroup)

**Comment by EgoziE** [comment]
PR - https://github.com/wix/wix-style-react/pull/4201
