### ISSUE TITLE
Cheetsheet - add anchors

### ISSUE THREAD

**Issue by mosheKerbel** [wix/wix-style-react#4127]
Feature request:

Add anchors to the cheetsheet so we will be able to send a link to a specific section
Something like this that will copy it to the clipboard or/and change it in the url
![image](https://user-images.githubusercontent.com/7388217/65052218-dc7a1c00-d972-11e9-8768-4c3dc705aabe.png)

**Comment by shlomitc** [comment]
added to the main issue
https://github.com/wix/wix-style-react/issues/3997
