### ISSUE TITLE
<FormField/> label color

### ISSUE THREAD

**Issue by LittleTal** [wix/wix-style-react#4155]
# 🐛 Bug Report

### 🏗 Relevant Components
`<FormField/>`

### 😯 Current Behavior
Currently `<FormField/>` label color is D10 
![image](https://user-images.githubusercontent.com/23282301/65490855-9105c780-deb6-11e9-9bc1-439451177a4a.png)

...

### 🤔 Expected Behavior
`<FormField/>` label color should be D20

![image](https://user-images.githubusercontent.com/23282301/65491169-3325af80-deb7-11e9-9fc2-245693716114.png)

https://zpl.io/a7W9wQR

...

### 👣 Steps to Reproduce

  - **WSR version**: `...`
  - **Yoshi version**: `...`

### 👀 Severity
Low

**Comment by nitayneeman** [comment]
The label of `<FormField/>` is actually the `<Text/>` component, which means it defines the color.

Do we want to change the default `skin` value ("standard") to be `D20` (otherwise we'll probably have to override the color in the `<FormField/>`)?
