### ISSUE TITLE
<Image/> - consolidate all <img> to a reusable component

### ISSUE THREAD

**Issue by gilmeir** [wix/wix-style-react#4165]
**Components creating `<img>` elements:**
* [`<Carousel/>`](https://github.com/wix/wix-style-react/blob/master/src/Carousel/Carousel.js#L152)
* [`<ImageViewer/>`](https://github.com/wix/wix-style-react/blob/master/src/ImageViewer/ImageViewer.js#L67)
* [`<EmptyState/>`](https://github.com/wix/wix-style-react/blob/master/src/EmptyState/EmptyState.js#L35)
* [`<MessageBoxMarketerialLayout/>`](https://github.com/wix/wix-style-react/blob/master/src/MessageBox/MarketerialLayout/MessageBoxMarketerialLayout.js#L51)
* [`<Proportion/>`](https://github.com/wix/wix-style-react/blob/master/src/Proportion/Proportion.js#L55)
* [`<Thumbnail/>`](https://github.com/wix/wix-style-react/blob/master/src/Thumbnail/Thumbnail.js#L108)

**Used props:**
* className
* dataHook
* src
* onLoad
* onError

**Comment by shlomitc** [comment]
not sure I understand, aren't these already props available for the native image component? why create a wrapper for it?

**Comment by gilmeir** [comment]
**UX**
The guidelines UX suggested for image rendering in `<ImageViewer/>` may be applied to other components that compose images.

Examples:
* Rendering a loader while image loads (to avoid flakiness of rendering an image that hasn't been fetched/painted yet).
* Rendering the previous image while loading the current image
For every features UX should decide whether it's mandatory or opt-in (feature-boolean-prop).

**Tests**
Providing a testkit for an image, that includes common methods, like simulating an image load event that wraps it in a nicer way.

**Performance**
Some more features around performance can be added in the future, like image-prefetching
(https://developer.mozilla.org/en-US/docs/Web/HTTP/Link_prefetching_FAQ)

I recently helped someone with the `<Carousel/>` component, which renders images, and receives an `images` array of image urls.
The user can't control the image besides just providing a url.
The specific issue was around not being able to control the height of the `<Carousel/>`,
so I thought if `images` would be an array of <img/> elements it could be more flexible, so why not wrapping it with our <Image/> that will give us more flexibility.

**Comment by gilmeir** [comment]
Just ran into this post I saw a few months ago by Addy Osmani about image lazy loading.
In future aspects we can consider adding a `lazy` prop to an `<Image/>`, it will make feds more aware of this optimization.
https://twitter.com/addyosmani/status/1114777583302799360

**Comment by simast** [comment]
Closing this issue as this was already implemented as `<Image/>` component.
