### ISSUE TITLE
<Swatches/> - Improve testkit

### ISSUE THREAD

**Issue by yevhen-kutishchev** [wix/wix-style-react#4169]
# ✨ Feature Request

### 🔦 Scope

`<Swatches />` component's testkit.

### 💁 Explanation

Could you please add `swatchClicked(index)`, `addButtonClicked()`, `swatchAdded()` (which will trigger onAdd callback) methods to testkit.

**Comment by shlomitc** [comment]
feel free to contribute the missing methods if you need them
thanks
