### ISSUE TITLE
`<PopoverMenu/>` - internal component DropdownLayout has max-height: 260px. Shadow is not extending further.

### ISSUE THREAD

**Issue by gerdasi** [wix/wix-style-react#4197]
# 🐛 Bug Report

### 🏗 Relevant Components

`<PopoverMenu />`

...

### 😯 Current Behavior

When popover has more elements than height of 260px its shadow disappears. 
![Screenshot 2019-10-03 at 14 23 56](https://user-images.githubusercontent.com/54804606/66123982-ef842180-e5eb-11e9-8235-256c8a788691.png)

...

### 🤔 Expected Behavior

All popover should be covered in shadow.

...

### 👣 Steps to Reproduce

  - **WSR version**: `6.58.0`
  - **Yoshi version**: `4.16.3`

### 👀 Severity

- Critical

**Comment by mykas** [comment]
Fixed.
