### ISSUE TITLE
need a small toggle switch

### ISSUE THREAD

**Issue by argshook** [wix/wix-style-react#42]
Hello,

i need to use a small version of toggle switch, though toggle in this project doesn't have a way to set  size or adjust styles.

**Comment by 3LOK** [comment]
Sounds good - does it exist in the UX guild style document?

**Comment by argshook** [comment]
the only reference i have is a project on zeplin [here](https://zpl.io/Z1fT2XN), it does have small toggle. not sure if you can see it, can invite you if you don't

**Comment by 3LOK** [comment]
I can't see it. Send me an invite, and at the same time i'll ask the ux guild if it's something that should be standard.

**Comment by argshook** [comment]
i clicked invite, you should be notified somewhere somehow

**Comment by 3LOK** [comment]
@mastertheblaster implemented it, merged today.
