### ISSUE TITLE
Avoid Modal header cropping

### ISSUE THREAD

**Issue by brumeregan** [wix/wix-style-react#4226]
# ✨ Feature Request

Add functionality to avoid cropping of Modal header when we have dynamic content.
Fullscreen prop on FunctionalLayout doesnt help because of this
![Screen Shot 2019-10-08 at 12 17 01 PM](https://user-images.githubusercontent.com/6932807/66383973-8ffc8c00-e9c6-11e9-9c7c-0e1613ed0d38.png)

What actually I'm trying to avoid is this
<img width="1494" alt="Screen Shot 2019-09-30 at 13 17 58" src="https://user-images.githubusercontent.com/6932807/66384037-ac98c400-e9c6-11e9-8086-48593ecd014d.png">

### 🐾 Possible solution 

Discussion was here -> https://wix.slack.com/archives/C39FTGUBZ/p1570522108331800
As possible solution was mentioned adding prop to FunctionalLayout for margin, so header will be always visible.. 🙄 

### 👀 Severity

This behavior is reproduced for all modals, maybe it should be **fixed as a bug** for all WSR modals :)

- Critical

**Comment by argshook** [comment]
thanks for filling this issue!

fix is in progress https://github.com/wix/wix-style-react/pull/4230
