### ISSUE TITLE
<Box/> puppeteer testkit

### ISSUE THREAD

**Issue by ArturasCH** [wix/wix-style-react#4234]
Adding for visibility - link to jira task for future tech-debt cleanup

### Relevant Components
`<Box/>` puppeteer testkit

...

### Current Behavior

```js
import { boxTestkitFactory } from 'wix-style-react/dist/testkit/puppeteer';
​
//in test
const boxDriver = await boxTestkitFactory({ dataHook, page });
​
​
/// causes error
TypeError: driverFactory is not a function
```
...

###  Expected Behavior

Box testkit works just like all others

###  Steps to Reproduce
create puppeteer Box testkit in e2e

  - **WSR version**: `7.6.0`
  - **Yoshi version**: `4.16.4`

###  Severity

-  Low

**Comment by shlomitc** [comment]
is this still happening in latest WSR version?

**Comment by shlomitc** [comment]
No response - closing. Please reopen if needed

**Comment by alexandraseri** [comment]
Hey @shlomitc This happens on `<RadioGroup/>` testkit for puppeteer as well, should I open a new bug or reopen and adjust this one?

**Comment by shlomitc** [comment]
@alexandraseri - better opening a new one

**Comment by alexandraseri** [comment]
Thanks, opened: #5811
