### ISSUE TITLE
[Safari] - Input field - placeholder text appears on top of input text in a specific scenario

### ISSUE THREAD

**Issue by alonbt** [wix/wix-style-react#424]
it happens when you clear the input text not via keypress.
How to reproduce:
1. type some text
2. clear the text from an external event (can be done via redux, or other state manager - the important thing is not to clear the input field by keypressing it)
3. Expected Result - placeholder text. Actual Result - input is not cleared. placeholder text is below it.

when hovering the component the issue is resolved. but it still requires a solution.
![screen shot 2017-04-26 at 16 25 37](https://cloud.githubusercontent.com/assets/846623/25436783/0bfe091e-2a9d-11e7-9d0f-c07da9d9ee98.png)

**Comment by lbelinsk** [comment]
@nirhart Account recovery qa also found a similar problem although you fixed something in the past:

Reproduced in Safari Version 10.0.3 (12602.4.8):

Just open https://users.wix.com/account-recovery/reset-account-information/free/
Proceed to next page in wizard by filling the mandatory fields and clicking next.
Set values in date fields
https://screencast.com/t/ORTk8C0V4QAe

**Comment by shlomitc** [comment]
won't be fixed.
will accept a PR if a change is proposed
