### ISSUE TITLE
`<Tooltip/>` - when tooltip is appended to window and browser screen gets very small it will shrink tooltip content to its minnimum

### ISSUE THREAD

**Issue by mykas** [wix/wix-style-react#4242]
### 🏗 Relevant Components

`<Tooltip/>` 

### 😯 Current Behavior

![image](https://user-images.githubusercontent.com/8919190/66477529-066dbc80-eaa1-11e9-96c6-130653680f78.png)

### 🤔 Expected Behavior

Should detect that the container has not enough space and freeze the width shrinking. 

- Critical

**Comment by rudnitskih** [comment]
Any ETA for this bug? We have a lot of tooltips in our apps and it is very annoying bug for us.

**Comment by rudnitskih** [comment]
I think fixing width is not correct solution, we should tooltip change placement for such edge cases. For example check this [story](https://get-domain.surge.sh/?path=/story/transfer-in-domain-selection--transferinstatus-islocked): 

![image](https://user-images.githubusercontent.com/8848858/68023297-78f04780-fcaf-11e9-8166-08415c51e83a.png)

If we will fix a width for tooltip what should happen? Container can have `overflow: hidden` and tooltip will be cut. I think we should detect such cases (when tooltip near the viewport and change placement from top to left/right). 

We already do similar behaviour for top/bottom viewport edges and I think `<Tooltip />` should respect also left/right.

**Comment by rudnitskih** [comment]
FYI @brumeregan

**Comment by rudnitskih** [comment]
Unfortunately, I cannot create a codesanbox example to show what I described because of this: https://github.com/wix/wix-style-react/issues/4439

**Comment by mykas** [comment]
Hi, I am able to reproduced this in storybook but only when screen is very small. I suspect that this but actually hides some bigger issues on your side. The tooltip content by default is appended to document.body and it bases its width based on available space in the whole document.body. For some reason the document.body of yours is showing weird width size when tooltips calculation library called popper.js tries to apply it on popover content. I will need to debug this on your storybook as it does not happen so oftern for our other users.

**Comment by mykas** [comment]
Regarding freezing the width. This does not mean that tooltips width will be frozen. It just means that it should tell the calculation mechanism that it should respect tooltips width when viewport changes and trie to position the tooltip to other side just like you mentioned: top to left or right. Right now it just shrinks the tooltip size to very minnimum value where one letter is shown in one line.

**Comment by mykas** [comment]
So I just checked your storybook and it seems that you have made it appended to `parent`. It is for some time we have Tooltip that is appended to `window`. Can you give your wix-style-react version?

**Comment by mykas** [comment]
The breaking of the words to letters is actually related to this:
<img width="229" alt="Screenshot 2019-11-01 at 20 20 50" src="https://user-images.githubusercontent.com/8919190/68046708-292c7300-fce5-11e9-9c21-ba6a915b70d6.png">


So as you can see the shrinking that makes it look like this. It is pretty hard though to debug this as I need to inject to popper.js libraries calculation and mechanism if you could provide me with your repo and a way to run the same storybook - I could make it faster for you to find this bug and solve it.

**Comment by mykas** [comment]
Here is our storybook reproducible example:
<img width="536" alt="Screenshot 2019-11-01 at 20 23 24" src="https://user-images.githubusercontent.com/8919190/68046832-845e6580-fce5-11e9-8070-6d651092deb4.png">

as you can see this happens only on VERY small viewports. Of course this could be related that the tooltip is standing in the middle of the screen and in your case its fixed on the right side.

**Comment by mykas** [comment]
Actually I just noticed that if you set `placement="auto"` to Tooltip it will start acting just the way you have described and it will not shrink the tooltip. I am considering adding this as default value to Tooltip so it would not happen.

**Comment by EgoziE** [comment]
Looks like an issue a good UX can solve.
If it's still relevant/critical please ask for help in the slack channel #wix-style-react and we'll help with specific cases.
