### ISSUE TITLE
[IE11] - input field has an X button that is not working properly

### ISSUE THREAD

**Issue by alonbt** [wix/wix-style-react#425]
Problem: clicking the native X button doesn't delete the content of the input (specifically tested on an input field that was connected to redux but might as well not work for other input field)

Requires (by product definition) either to:
1. display the native X button or a custom X button but make it work for IE11
2. Hide the X button by default for all browsers
3. Display an X button via a flag in the input API so each developer can decide wether to show it or not

**Comment by nirhart** [comment]
fixed
