### ISSUE TITLE
<Popover> inside <Text>

### ISSUE THREAD

**Issue by malcolmmadsheep** [wix/wix-style-react#4266]
# 🐛 Bug Report

![image](https://user-images.githubusercontent.com/12401969/66570641-aa756780-eb76-11e9-8531-e6c2766dd2b4.png)

### 🏗 Relevant Components

- `<Popover>`
- `<Text>`

### 😯 Current Behavior

For very long strings without spaces tooltip content is stretching beyond its bounds and render the whole word.
...

### 🤔 Expected Behavior

I think, it should be ellipsis for such a cases.

...

### 👣 Steps to Reproduce

I couldn't implement it in codebox, because WSR version in codebox is ^5.0.0 (I didn't get how to update version of WSR module), and bug is present in 7.3.0.

https://codesandbox.io/embed/wix-style-react-bpyji

  - **WSR version**: `7.3.0`
  - **Yoshi version**: `4.16.4`

### 👀 Severity

- Low

**Comment by mykas** [comment]
I can't reproduce this in storybook. It works fine. 
![Screenshot 2019-10-10 at 17 39 00](https://user-images.githubusercontent.com/8919190/66579066-e0b9e380-eb84-11e9-9e6a-23a965c8d542.png)

**Comment by mykas** [comment]
Please share your snippet code here. Even in your sandbox example it does not reproduce.
