### ISSUE TITLE
Virtualized <Table /> memoized row rendering

### ISSUE THREAD

**Issue by audriuss** [wix/wix-style-react#4267]
# ✨ Feature Request

### 🔦 Scope
`<Table />` with Virtualization

### 💁 Explanation
When one item of all input array is changed, all rows are remounted together with containing components, that have negative impact on performance and UX.
For example we have `<Avatar />` rendered as row cell, which indicates task assignee. If user change the assignee all rows are remounted together with other avatars which causes all avatars to flicker while loading images.

### 🐾 Possible solution
Since virtual `<Table />` is using  `react-window` under the hood, row memoization could be implemented: https://react-window.now.sh/#/examples/list/memoized-list-items

### 👀 Severity
- Major

Our project will use virtualized Tables quite much, so it's important to us have a good performance

**Comment by audriuss** [comment]
PR: https://github.com/wix/wix-style-react/pull/4358

**Comment by simast** [comment]
Fixed with #4462 and #4455
