### ISSUE TITLE
Table.EmptyState positioning issue

### ISSUE THREAD

**Issue by hitpopdimestop** [wix/wix-style-react#4306]
# 🐛 Bug Report

### 🏗 Relevant Components
Table.EmptyState

### 😯 Current Behavior
If we wrap the table inside the `<Box>` component the empty state is not rendered full width as expected. See video:
https://drive.google.com/open?id=1yDLN2Tjr6d24tfh1bBVhzGpE0hNIRRsj

### 🤔 Expected Behavior
Empty state should be rendered full width.

### 👣 Steps to Reproduce
Wrap a table that has an empty state with `<Box>`

### 👀 Severity
Major

**Comment by nitayneeman** [comment]
`<Box/>` is a flexbox container which means we need to stretch the child somehow.

Possible ways to achieve:
1. Add a `className` prop to `<Table/>` so we can make it be `flex-grow: 1`.
2. Make `<Box/>`'s direction to be vertical using `direction: vertical`, so it would stretch the content horizontally.

The second acts like a workaround, but maybe the first is the right solution in this case.

**Comment by EgoziE** [comment]
Decided not to fix - closing
