### ISSUE TITLE
`<Dropdown/>` - selectAt testkit method stopped working

### ISSUE THREAD

**Issue by henrykuzmick** [wix/wix-style-react#4334]
The e2e dropdown driver broke after a recent update, `selectAt` stopped working.
This is a link to our temporary fix for context:
https://github.com/wix-private/app-market/pull/13286/files

**Comment by mosheKerbel** [comment]
@mykas you want to take a look?
looks like there were some changes in this area - https://github.com/wix/wix-style-react/blob/ea9c98b5d6eb9f966bd1a44135a7abe40b2a7936/src/DropdownBase/DropdownBase.uni.driver.js#L37

**Comment by mykas** [comment]
Checking

**Comment by mykas** [comment]
@henrykuzmick any errors?

**Comment by mykas** [comment]
Can you point me to exact test that fails? I'd like to replicate this locally and see whats going on. By the way which testing framework is this?

**Comment by henrykuzmick** [comment]
Sure, 
this is the failing test: https://github.com/wix-private/app-market/blob/3044e543aed868b7277faa2920882728c348b391/membership/membership-tpa/test/e2e/bo-new-order.e2e.ts#L62

It's failing because `selectOption` fails to find some dataHook
https://github.com/wix-private/app-market/pull/13286/files#diff-465688d573d0d4b5c8eb5d5dae4d7a5cL249

**Comment by simast** [comment]
The issue here seems to be that you have a `<Dropdown/>` component and you are using `DropdownBase` testkit to test this component. Internally `<Dropdown/>` doesn't even use `DropdownBase` component - so it was an unexpected side effect that this did work previously.

Could you update your puppeteer tests to use `dropdownTestkitFactory`? Something like this:

```js
const dropdown = await dropdownTestkitFactory({ dataHook: 'plan-dropdown', page });
await dropdown.click(); // not sure if required, should be optional
await dropdown.selectOptionById(1); // this is not an index, but an option id
```

**Comment by henrykuzmick** [comment]
Hi, I've tried this and it works! Thanks!

However, I still think it's confusing as methods like `dropdown.driver.selectOptionById(id);` and `dropdown.dropdownLayoutDriver.clickAtOption(0);` give me this:

![image](https://user-images.githubusercontent.com/13556336/69051736-e5887780-0a0d-11ea-8601-1da25472136f.png)
