### ISSUE TITLE
`<Swatches/>` -  are corrupted in Microsoft Edge

### ISSUE THREAD

**Issue by vladik7244** [wix/wix-style-react#4355]
# 🐛 Bug Report

### 🏗 Relevant Components

Swatches

...

### 😯 Current Behavior

![image](https://user-images.githubusercontent.com/7922368/67210801-5c881b80-f422-11e9-86e8-0b2fb2dd7b3f.png)

...

### 🤔 Expected Behavior

![image](https://user-images.githubusercontent.com/7922368/67210857-77f32680-f422-11e9-8af0-bc8b9eb252c3.png)

...

### 👣 Steps to Reproduce

Open https://wix-style-react.now.sh/?selectedKind=Components&selectedStory=Swatches&full=0&addons=0&stories=1&panelRight=0 with Edge

  - **WSR version**: `7.9.0`
  - **Browser version**: `Edge 40`

### 👀 Severity

- Major

**Comment by mykas** [comment]
Checking

**Comment by mykas** [comment]
The issue does not happen in the newest microsoft edge version. Appears only in version 40. I don't have resources to test on version 40.
