### ISSUE TITLE
`<StatisticsWidget/> - testkit method clickStatistics(index) not working 

### ISSUE THREAD

**Issue by ArturasCH** [wix/wix-style-react#4367]
# Bug Report

###  Relevant Components
Puppeteer ```statisticsWidgetTestkitFactory```

...

###  Current Behavior

when attempting to use 
```await statisticsWidgetTestkit.statisticsWidgetTestkitFactory(index)```
statistics widget item is not being clicked

From a short debugging attempt 
https://github.com/wix/wix-style-react/blob/master/src/StatisticsWidget/StatisticsWidget.uni.driver.js#L12

returns ```{}``` - not clickable element
...

###  Expected Behavior

When using the driver - Statistics Widget item is clicked
...

### Steps to Reproduce

Use the driver in a test.
```js
import { statisticsWidgetTestkitFactory } from 'wix-style-react/dist/testkit/puppeteer';
test('stats', async () => {
const statisticsDriver = await statisticsWidgetTestkitFactory({
    dataHook,
    page,
  });

await statisticsDriver.clickStatistics(index);
});
```

  - **WSR version**: `broken - 7.9.0 (^7.0.0); working - 7.8.1`
  - **Yoshi version**: `4.17.1`

### Severity

-  Major

**Comment by mykas** [comment]
Checking

**Comment by kranux** [comment]
@mykas, Hello, any updates? :)

**Comment by kranux** [comment]
Also, I noticed that with latest version of WSR (^7.8.1) click on description is not working properly. 

Example:

![image](https://user-images.githubusercontent.com/1897702/67764682-29addb00-fa53-11e9-8136-a0396e7cc429.png)

First click on description is not working after page reload. Note that second click and click in other places inside statistics widget work just fine.

**Comment by kranux** [comment]
@simast
