### ISSUE TITLE
Tag Input

### ISSUE THREAD

**Issue by LittleTal** [wix/wix-style-react#4377]
# 🐛 Bug Report

### 🏗 Relevant Components
`3.12 <Tags/>`

...

### 😯 Current Behavior
No visual cue when hovering the "X" button of individual tags.
...

### 🤔 Expected Behavior
Remove click event from tag (should show pointer only while hovering close button)

...

### 👣 Steps to Reproduce

  - **WSR version**: `...`
  - **Yoshi version**: `...`

### 👀 Severity

Low

**Comment by EgoziE** [comment]
PR - https://github.com/wix/wix-style-react/pull/4382
