### ISSUE TITLE
Focusing on a selected `Thumbnail` hides selection shadow

### ISSUE THREAD

**Issue by naamagr** [wix/wix-style-react#4378]
# 🐛 Bug Report

### 🏗 Relevant Components

Thumbnail

### 😯 Current Behavior

When using `Thumbnail` with backgroundImage or children, the box-shadow that is set for a selected `Thumbanil` does not have the `inset` property. Therefore, when focusing on a selected thumbnail, the focus shadow hides the selected shadow (instead of surrounding it)

### 🤔 Expected Behavior

The focus shadow should surround the selected shadow. This is how it works for thumbnails without backgroundImage or children. 

### 👣 Steps to Reproduce

This behavior can be reproduced with the storybook. 
1. Go to `Thumbnail with background image` or `Thumbnail with custom children` section.
2. Select the thumbnail (by altering the code)
3. Focus on the thumbnail 

### 👀 Severity

 Major 

Thanks!

**Comment by shlomitc** [comment]
It happens even in the basic cases,
![image](https://user-images.githubusercontent.com/6093192/67382391-118f1500-f596-11e9-8919-b409c543f1e8.png)

Here's how the spec is defined
![image](https://user-images.githubusercontent.com/6093192/67382318-f6bca080-f595-11e9-92ab-a51e891078be.png)
https://zpl.io/beAXL7N

@naamagr - can you make a pull-request fixing it?
