### ISSUE TITLE
<Sidebar /> doesn't animate in and out on change of `isHidden` flag.

### ISSUE THREAD

**Issue by banuni** [wix/wix-style-react#4387]
# 🐛 Bug Report

### 🏗 Relevant Components
`<Sidebar />` 

### 😯 Current Behavior
`<Sidebar />` doesn't animate in and out on change of `isHidden` flag.

### 🤔 Expected Behavior
`<Sidebar />` should animate in and out.

### 👣 Steps to Reproduce
create a sidebar
change isHiddden after render (no re-mounting, use a button or something)

  - **WSR version**: `7.10.0`
  - **Yoshi version**: `^4`

### 👀 Severity
Blocker - Critical

**Comment by EgoziE** [comment]
PR - https://github.com/wix/wix-style-react/pull/4399
