### ISSUE TITLE
<MultiSelectCheckbox/> - Add text overflow

### ISSUE THREAD

**Issue by marik22312** [wix/wix-style-react#4418]
# ✨ Feature Request

### 🔦 Scope

MultiSelectCheckbox

...

### 💁 Explanation

The MultiSelectCheckbox component does support text-overflow, but it affects only the `input` with the selected options [see attached photo](https://paste.pics/59e3d5a5686df83807f14e1f59548fcb)

We suggest adding support to text-overflow for the popover element, [see attached photo](https://paste.pics/440b022f94be4f54b8aa1722c37383cd)

### 👀 Severity
Major

**Comment by shlomitc** [comment]
just pass the `textOverflow="ellipsis"` prop
