### ISSUE TITLE
<DatePicker/> - Page bounces when opening datepicker located on its bottom

### ISSUE THREAD

**Issue by TetianaStashchenko** [wix/wix-style-react#4424]
https://wix-style-react.now.sh/?activeTab=Usage&addons=0&full=0&panelRight=0&selectedKind=Components&selectedStory=DatePicker&stories=1 -  when DatePicker  is about two or less centimeters from the bottom of the page, then when you click on the input field it  is jumps in the middle of the page but the calendar does not open.
WSR - 7.11.0
yoshi - 4.17.1

**Comment by simast** [comment]
Here is an example of the issue:

![bug](https://user-images.githubusercontent.com/433527/67863628-efb10780-fb2c-11e9-972e-36d4ddaff12b.gif)

**Comment by mykas** [comment]
Fixed by migrating to Popover.
