### ISSUE TITLE
TableToolbar.Label automatically focus input

### ISSUE THREAD

**Issue by adirou** [wix/wix-style-react#4426]
# 🐛 Bug Report

### 🏗 Relevant Components

<TableToolbar.Label>

...

### 😯 Current Behavior

After clicking on elements inside it automatically focus the input inside, which in components like InputWithOptions may cause bugs like opening the dropdownLayout not on purpose, 
 

...

### 🤔 Expected Behavior

should not function like normal <label> , and focus input

...

### 👣 Steps to Reproduce

https://wix-style-react.now.sh/?selectedKind=Components%2FPage%20Examples&selectedStory=3.%20Stretched%20Table%20In%20Page&full=0&addons=0&stories=1&panelRight=0&activeTab=Description

  - **WSR version**: `...`
  - **Yoshi version**: `...`

### 👀 Severity

Major

**Comment by BnayaZil** [comment]
Also clicking on a label / dropdown arrow while the dropdown is open causes a blink in the dropdown (closing and quickly opening the dropdown).

![image](https://jira.wixpress.com/secure/attachment/218577/2019-12-02_20-20-08%20%281%29.gif)

**Comment by EgoziE** [comment]
Moved to Jira - closing
https://jira.wixpress.com/browse/DSM-1496
