### ISSUE TITLE
Does default "textAlign" value for tooltip should be "start"?

### ISSUE THREAD

**Issue by rudnitskih** [wix/wix-style-react#4436]
# ✨ Feature Request

### 🔦 Scope

I am from Premium Domains team and in all our mocks all tooltips have content alignment to the left. Developers sometimes forget to set `textAlign="start` in Tooltip and our designer is upset. If `textAlign="start` is default behaviour in our design system, maybe we should change it in WSR component. I understand this is breaking change, but WDYT?

Some examples with our designs:
- https://share.goabstract.com/f12458f1-1418-41a0-b6bd-4b842050b12e
- https://app.goabstract.com/projects/05528230-bb19-11e8-9f9f-c92dc976b27b/branches/master/collections/c51e88bc-42f4-4e7c-baa4-97a70d41eaae

### 👀 Severity
- Low

**Comment by mykas** [comment]
Yes, this was intentional and defined by Design Systems. @milkyfruit please comment on this on Monday

**Comment by milkyfruit** [comment]
@mykas by design default text alignment should be left (if LTR). I agree with @rudnitskih, I think we should change `textAlign="start` as a default value.

Zeplin specs don't indicate text alignment, however two line examples show it as left: https://zpl.io/boDpzxW
