### ISSUE TITLE
<Text /> component doesn't work in codesandbox 

### ISSUE THREAD

**Issue by rudnitskih** [wix/wix-style-react#4439]
# Documentation Issue

### 🔦 Scope

Codesandbox with WSR 7.12.0 doesn't work.

### 💁 Explanation

I want to create an issue with example in codesandbox and latest WSR, but I cannot.
https://codesandbox.io/s/wix-style-react-5eflj

Runtime error:
![image](https://user-images.githubusercontent.com/8848858/68022372-d0d97f00-fcac-11e9-89ea-bb3d8ebc97e1.png)

### 👀 Severity
- Major

**Comment by simast** [comment]
The example does not work as your `src/index.vm` file is linking to an old React version (`15.6.1`).

**Comment by rudnitskih** [comment]
@simast Thank you!
