### ISSUE TITLE
Improve codesandbox usage 

### ISSUE THREAD

**Issue by rudnitskih** [wix/wix-style-react#4440]
# Documentation Issue

### 🔦 Scope

Codesandbox environment

### 💁 Explanation
When I want to create a feature request to WSR, it is good to create a reproducible example in codesandbox. But there are couple issues with it:
- The link with template only located in one place in all project: 
https://github.com/wix/wix-style-react/search?q=codesandbox&unscoped_q=codesandbox
- Codesandbox template has not latest WSR version: https://codesandbox.io/s/jj196orvpv?module=%2Fsrc%2FApp%2Findex.js

### Expected Docs 
- Link to codesandbox template should be located in feature request template and maybe in storybook. Maybe we can replace [Playground](https://wix-style-react.now.sh/?selectedKind=Introduction&selectedStory=Playground&full=0&addons=0&stories=1&panelRight=0) story with codesandbox iframe.
- The template should include latest WSR version.

### 👀 Severity
- Low

**Comment by simast** [comment]
We should update this template and bump React version in `src/index.vm` - as currently the template cannot be used with some components that use React 16.x features. Related #4439

**Comment by EgoziE** [comment]
We decided to stick with our current Playground and improve it as much as we can.
If we ever decide to use an external sandbox we'll let you know 😃
That can be a great idea for a guild week 😉

**Comment by rudnitskih** [comment]
@EgoziE Current Playground is awesome, I agree to continue with it instead of the codesandbox. Thank you for the update!
