### ISSUE TITLE
<Input/> - Content is selected on focus

### ISSUE THREAD

**Issue by rudnitskih** [wix/wix-style-react#4467]
# 🐛 Bug Report

### 🏗 Relevant Components

`<Input />`

### 😯 Current Behavior

Content is fully selected when <Input /> gets focus on user click.

### 🤔 Expected Behavior

According to design spec https://app.zeplin.io/project/5c8f6f1f9f489505cac756dc/screen/5cfa62f81f693934debb9933 
Input shouldn't have this behaviour by default, but it can be controlled by some prop.  

Discussion:
https://wix.slack.com/archives/C39FTGUBZ/p1572952621070600

### 👣 Steps to Reproduce

Open `<Input />` storybook page and play with a component: http://wix.to/ucBTBOI

  - **WSR version**: `7.13.0`
  - **Yoshi version**: not relevant

### 👀 Severity

- Low

**Comment by EgoziE** [comment]
Apparently this is the desired behavior according to UX.
