### ISSUE TITLE
`<Popover/>` - onClickOutisde is fired when popover is closed

### ISSUE THREAD

**Issue by marik22312** [wix/wix-style-react#4468]
# 🐛 Bug Report

### 🏗 Relevant Components

`<Popover/>`

### 😯 Current Behavior

onClickOutisde callback is fired on every click outside of the popover, even when the popover is closed.

### 🤔 Expected Behavior

don't fire the onClickOutisde callback when the popover is closed

### 👣 Steps to Reproduce

just put a popover component, pass an onClickOutside callback and see the magic happen

  - **WSR version**: `6.49`
  - **Yoshi version**: `3`

### 👀 Severity
- Major - Did a workaround for now.

**Comment by EgoziE** [comment]
@marik22312 This was fixed with the new prop `disableClickOutsideWhenClosed` since wsr 7.21.0
