### ISSUE TITLE
<Radio/> - new component

### ISSUE THREAD

**Issue by mykas** [wix/wix-style-react#4471]
# ✨ Feature Request

### 🔦 Scope

<Radio/> component

### 💁 Explanation

More and more people are coming with request to have single atomic component called: `<Radio/>`.

Examples of usage:

![image](https://user-images.githubusercontent.com/8919190/68279444-1797f200-007c-11ea-89d4-b37586541585.png)

![image](https://user-images.githubusercontent.com/8919190/68279462-2383b400-007c-11ea-945a-f10b91ccbb9b.png)

Current implementation of `<RadioGroup/>`  is hard to implement with `select` state.

### 👀 Severity

- Critical

**Comment by EgoziE** [comment]
moved to jira - closing
