### ISSUE TITLE
<InputWithOptions/> - onFocus event is called twice

### ISSUE THREAD

**Issue by marik22312** [wix/wix-style-react#4472]
# 🐛 Bug Report

### 🏗 Relevant Components

`<InputWithOptions />`

### 😯 Current Behavior

When pressing the arrow button of the `<InputWithOptions />` component, the onFocus event is fired twice.
this only happens when clicking the arrow button. not the field itself

### 🤔 Expected Behavior

`onFocus` callback should be fired once

### 👣 Steps to Reproduce
1. Add the `<InputWithOptions />` component on your page
2. Add a `onFocus` callback function
3. Click the arrow button to open the dropdown
4. `onFocus` callback fired twice

https://codesandbox.io/s/wix-style-react-u8mq0?fontsize=14

  - **WSR version**: 6.49.0
  - **Yoshi version**: 3

### 👀 Severity

Low, in my opinion, this can be easily overridden with a debouncer.

**Comment by EgoziE** [comment]
Moved to Jira - closing
https://jira.wixpress.com/browse/DSM-1497
