### ISSUE TITLE
<FullTextView/> not working correctly for very long words

### ISSUE THREAD

**Issue by sidoruk-sv** [wix/wix-style-react#4473]
# 🐛 Bug Report

### Better solution

Deprecate `<FullTextView />` in favor of `<Text ellipsis={true} />`

### 🏗 Relevant Components

`<FullTextView />`

### 😯 Current Behavior

When some long word is passed to `<FullTextView /`> it shows that word as is (without ellipses and tooltip/popover with a full word in it).
![image](https://user-images.githubusercontent.com/439289/68292832-656d2400-0095-11ea-835d-a6dffd650ca3.png)
![image](https://user-images.githubusercontent.com/439289/68292839-6aca6e80-0095-11ea-9688-2aeaabf886e9.png)

### 🤔 Expected Behavior

When a very long word is passed as a child and didn't fit the space, `<FullTextView />` should add ellipses and show tooltip on hover with that full word.

![image](https://user-images.githubusercontent.com/439289/68292880-7b7ae480-0095-11ea-99d5-4898964c63c8.png)
![image](https://user-images.githubusercontent.com/439289/68292893-7fa70200-0095-11ea-8cb1-47c807b858c5.png)

### 👣 Steps to Reproduce

Just wrap some long word inside a block with the width less then that word can be fitted.

https://codesandbox.io/s/wix-style-react-8urto
Mention that sometimes (when you will resize the window of codesandbox.io) it is shown as ellipses (but no Tooltip with full-content is shown).

  - **WSR version**: `5.*-7.*`
  - **Yoshi version**: `4.17.2`

### 👀 Severity

- Major

___

Can't use `<FullTextView/>` so created **alternative component** in our project:
https://github.com/wix-private/my-domains/blob/master/src/app/components/%40shared/BetterFullTextView/BetterFullTextView.tsx

This can be found here:
https://my-domains.surge.sh/?path=/story/modals-configure-mailbox-records--provider-other
(Chose "GoDaddy", inspect the last row)

My problem is that upgraded `<Tooltip/>` component breaks the behavior of custom `<BetterFullTextView/>` and I need to find another solution, so fixing `<FullTextView/>` is an option.

**Comment by shlomitc** [comment]
`FullTextView ` is deprecated in v8
