### ISSUE TITLE
onClickOutside isn't working on Autocomplete component

### ISSUE THREAD

**Issue by Ausra** [wix/wix-style-react#4483]
# 🐛 Bug Report

### 🏗 Relevant Components

Autocomplete

...

### 😯 Current Behavior

onClickOutside function is never called.

...

### 🤔 Expected Behavior

onClickOutside function is called

...

- Critical / Major / Low

**Comment by EgoziE** [comment]
Created a PR - https://github.com/wix/wix-style-react/pull/4485
