### ISSUE TITLE
<Table/> - row select checkbox have small click area

### ISSUE THREAD

**Issue by dorduch** [wix/wix-style-react#4484]
the clickable area around the row checkbox is too small, and it's easy to mistakenly click the row instead of selecting it

**Comment by mykas** [comment]
@milkyfruit I guess we need to expand the area, right?

**Comment by milkyfruit** [comment]
yes, I think it could be expanded to whole area up until the first value item (in given example it's avatar):
![image](https://user-images.githubusercontent.com/1684587/68395084-bd7c5700-0177-11ea-9210-a0d96dc1996f.png)

@dorduch how urgent is this?

**Comment by dorduch** [comment]
we got some complaints about it

**Comment by dorduch** [comment]
@milkyfruit  do you mean expanding it to include the padding and margin? or just the available space? (in this case it's above and below the checkbox)

**Comment by milkyfruit** [comment]
@dorduch I menat this area:
![image](https://user-images.githubusercontent.com/1684587/69236949-44c8c200-0b9d-11ea-9724-2ecf7d88c697.png)

**Comment by shlomitc** [comment]
should be fixed by now, closing
