### ISSUE TITLE
<IncrementerInput/> new component

### ISSUE THREAD

**Issue by LittleTal** [wix/wix-style-react#4497]
# ✨ Feature Request

### 🔦 Scope
`<IncrementerInput/>` new component
...

### 💁 Explanation

`<IncrementerInput/>` is a new component with the following props:
Size, Button type, Additional info, Required info, Label position
Zeplin spec: https://zpl.io/2p48p4J
...

### 🐾 Possible solution 

...

### 👀 Severity

Low

**Comment by EgoziE** [comment]
Moved to Jira - https://jira.wixpress.com/browse/DSM-105
