### ISSUE TITLE
<DurationInput/> new component

### ISSUE THREAD

**Issue by LittleTal** [wix/wix-style-react#4498]
# ✨ Feature Request

### 🔦 Scope
` <DurationInput/>` new component

...

### 💁 Explanation

`<DurationInput/>` is a new component with the following props:
Size, Seconds, Incrementer, Additional info, Required, Label position
Zeplin spec: https://zpl.io/adpdlpe

...

### 🐾 Possible solution 

...

### 👀 Severity

Low

**Comment by EgoziE** [comment]
Moving to Jira - https://jira.wixpress.com/browse/DSM-139
