### ISSUE TITLE
<TimePicker/> 

### ISSUE THREAD

**Issue by LittleTal** [wix/wix-style-react#4518]
# 🐛 Bug Report

### 🏗 Relevant Components
`<TimePicker/>` 

### 😯 Current Behavior
`<TimePicker/>` component's items are not aligned 
![image](https://user-images.githubusercontent.com/23282301/68752935-cf914600-060c-11ea-9f24-798b890cac7a.png)

### 🤔 Expected Behavior
Both items (Input and format) should be aligned to the center
![image](https://user-images.githubusercontent.com/23282301/68753248-5ba36d80-060d-11ea-972e-51c978368dcc.png)

### 👣 Steps to Reproduce

  - **WSR version**: `...`
  - **Yoshi version**: `...`

### 👀 Severity

Low

**Comment by EgoziE** [comment]
PR - https://github.com/wix/wix-style-react/pull/4817
