### ISSUE TITLE
< SocialButton/> - icons are not centered inside their circles

### ISSUE THREAD

**Issue by EgoziE** [wix/wix-style-react#4520]
# 🐛 Bug Report

### 🏗 Relevant Components
`< SocialButton/>`

### 😯 Current Behavior
![image](https://user-images.githubusercontent.com/35173937/68762091-23f0f180-061e-11ea-9914-09c6ca8dc17f.png)

### 🤔 Expected Behavior
Icons should be aligned

### 👀 Severity
- Low

**Comment by mykas** [comment]
Fixed.
