### ISSUE TITLE
Input focus() bug with testkit

### ISSUE THREAD

**Issue by lbelinsk** [wix/wix-style-react#453]
I am using the onFocus prop for some Input component.

When I try to test it with inputTestkit.focus() the given onFocus function is not triggered.

https://github.com/wix/wix-style-react/blob/master/src/Input/Input.js#L119

the _onFocus should be called also..

**Comment by lbelinsk** [comment]
Not fixed yet. Actually there is a new bug now:

![image](https://user-images.githubusercontent.com/18248989/27370949-60e9a85c-5667-11e7-98a7-aa3f65ab9f8c.png)

Looking into it

**Comment by nirhart** [comment]
its already fixed, please update

**Comment by lbelinsk** [comment]
Adding the same solution to blur..
