### ISSUE TITLE
<RichTextArea/> - improve usage of char count

### ISSUE THREAD

**Issue by LittleTal** [wix/wix-style-react#4543]
# 🐛 Bug Report

### 🏗 Relevant Components
`<RichTextArea/>`
...

### 😯 Current Behavior
Char limit in `<RichTextArea/>` starts with 89 characters instead of 100
![image](https://user-images.githubusercontent.com/23282301/69005028-52bfde00-0924-11ea-87de-b5f93673e048.png)
...

### 🤔 Expected Behavior
![image](https://user-images.githubusercontent.com/23282301/69005056-eb565e00-0924-11ea-983f-b07fdc1f6374.png)

...

### 👣 Steps to Reproduce

  - **WSR version**: `...`
  - **Yoshi version**: `...`

### 👀 Severity

Low

**Comment by argshook** [comment]
Hello! `<RichTextArea/>` has been deprecated, instead `<RichTextInputArea/>` should be used.

anyhow, the part that shows characters left to type is a responsibility of `<FormField/>`

also anyhow, could you share where you see this behaviour? Is it our storybook or code from somewhere else?

**Comment by LittleTal** [comment]
I saw this behavior while creating a new story, and also in the playground when the code is:
```
<FormField label="Rich Text Area label">
  {({ setCharactersLeft }) => (
    <RichTextInputArea
      onChange={value => setCharactersLeft(100 - value.length)}
    />
  )}
</FormField>
```

**Comment by argshook** [comment]
ok i see now, i'll shed some light.

considering this code:

```
<FormField label="Rich Text Area label">
  {({ setCharactersLeft }) => (
      <RichTextInputArea
      onChange={value => setCharactersLeft(100 - value.length)}
    />
  )}
</FormField>
```

`FormField` doesn't care about what number to show, it shows what it's
told to. In this case it's told to `setCharactersLeft` to `100 - value.length`

`100 - value.length` is `89`, because `value` is not just `''` but `<p><br></p>`. There's some HTML even though it's not visible in the editor.

`<p><br></p>` is 11 chars long and so it's `100 - 11 = 89`

that's only the case with RichTextInputArea, the `Rich` part basically
means "has HTML", and that HTML is part of the `value`.

---

summoning @nitayneeman

perhaps we could update
[this](https://github.com/wix/wix-style-react/blob/fa77456789170ffec14b4ee74e04c3598586c0d4/src/RichTextInputArea/RichTextInputArea.js#L175)
to pass not only `value` but also plain text? Or directly value length?  wdyt?

something like this (didn't test, just idea):

```js
onChange(
  EditorUtilities.convertToHtml(newEditorState),
  { plainText: newEnewEditorState.getCurrentContent().getPlainText() }
);
```

**Comment by nitayneeman** [comment]
> ok i see now, i'll shed some light.
> 
> considering this code:
> 
> ```
> <FormField label="Rich Text Area label">
>   {({ setCharactersLeft }) => (
>       <RichTextInputArea
>       onChange={value => setCharactersLeft(100 - value.length)}
>     />
>   )}
> </FormField>
> ```
> 
> `FormField` doesn't care about what number to show, it shows what it's
> told to. In this case it's told to `setCharactersLeft` to `100 - value.length`
> 
> `100 - value.length` is `89`, because `value` is not just `''` but `<p><br></p>`. There's some HTML even though it's not visible in the editor.
> 
> `<p><br></p>` is 11 chars long and so it's `100 - 11 = 89`
> 
> that's only the case with RichTextInputArea, the `Rich` part basically
> means "has HTML", and that HTML is part of the `value`.
> 
> summoning @nitayneeman
> 
> perhaps we could update
> [this](https://github.com/wix/wix-style-react/blob/fa77456789170ffec14b4ee74e04c3598586c0d4/src/RichTextInputArea/RichTextInputArea.js#L175)
> to pass not only `value` but also plain text? Or directly value length? wdyt?
> 
> something like this (didn't test, just idea):
> 
> ```js
> onChange(
>   EditorUtilities.convertToHtml(newEditorState),
>   { plainText: newEnewEditorState.getCurrentContent().getPlainText() }
> );
> ```

I agree the problem is we treat the inserted text and the parsed value so far the same (without differentiating them).

Actually I when Lital showed me the issue I thought about a similar solution:
```jsx
<FormField label="Rich Text Area label">
  {({ setCharactersLeft }) => (
      <RichTextInputArea
      onChange={(value, parsedValue/richValue/output) => setCharactersLeft(100 - value.length)}
    />
  )}
</FormField>
```

So I guess the solution is just passing the original text in some way
