### ISSUE TITLE
💥 wix-style-react 8.0: breaking changes list

### ISSUE THREAD

**Issue by mykas** [wix/wix-style-react#4544]
This is an issue meant for gathering next major version breaking changes. 
Feel free to write in comments changes that you would like to introduce in next major version.

🌟 **How to make it easier for everybody to include your changes**

1. Open a pr with changes that you would like to introduce.
2. Close pr and copy the link in the comments section below.

**Comment by EgoziE** [comment]
please check all leftover issues from the previous aggregating issue:
https://github.com/wix/wix-style-react/issues/2924

**Comment by argshook** [comment]
In wix-style-react v8 we should finalize deprecation of proxied icons. For users it means

```diff
-import Icon from 'wix-style-react/new-icons/Icon';`
+import Icon from 'wix-ui-icons-common/Icon';`
```

in wsr v8 the `new-icons/Icon` import path should be removed entirely. For migration users can do `npx wix-ui-codemod wix-style-react/icons-common src/`

CC: @simast

**Comment by simast** [comment]
PR to remove new-icons proxy: https://github.com/wix/wix-style-react/pull/4671

**Comment by EgoziE** [comment]
I suggest removing the old `<Tooltip/>`
It has an upgrade prop for the last 2 majors.

**Comment by argshook** [comment]
> I suggest removing the old `<Tooltip/>`
> It has an upgrade prop for the last 2 majors.

On this note i'd say perhaps all of the `upgrade` things we have should
become the defaults. Searching through code i see `upgrade` used in:

1. `Tooltip`
1. `Button`
1. `Page`
1. `TableActionCell`

`PopoverMenu` could also move out of `beta`. This would have the benefit
of removing all the special configurations for `beta` (like `npm run update-components:beta`)

for future `beta` things we could rename it to `next` as have discussed
a while ago

**Comment by mykas** [comment]
### Dynamically loaded component migration

Popover: https://github.com/wix/wix-style-react/pull/4678
Tooltip: TBD

**Comment by shlomitc** [comment]
done
