### ISSUE TITLE
<MultiSelectCheckbox /> - `closeOnSelect` ignores clicks on the item body

### ISSUE THREAD

**Issue by BnayaZil** [wix/wix-style-react#4547]
# 🐛 Bug Report

### 🏗 Relevant Components

<MultiSelectCheckbox /> - `closeOnSelect` ignores clicks on the item body

### 😯 Current Behavior

- Click on the input opens a dropdown -> click on the item checkbox close the dropdown.
- Click on the input opens a dropdown -> click on the item title (body) just trigger a select event without closing the dropdown.

### 🤔 Expected Behavior

I would expect any click on the item will close the dropdown.

...

### 👣 Steps to Reproduce

goto: current behavior

Example of my implementation:
```
<MultiSelectCheckbox
  onSelect={option => onRoleFilterAdded(option, roleTypes)}
  onDeselect={option => onRoleFilterRemoved(option, roleTypes)}
  valueParser={option => option.inputTitle}
  options={filterOptions}
  selectedOptions={rolesSelectedOptions}
  fixedFooter={rolesFilterFixedFooter}
  disabled={Boolean(membersTable.query)}
  placeholder={t('teamDetails.actions.rolesFilter.placeholder')}
  data-hook="account-team-table-roles-filter"
  markedOption
  closeOnSelect
  roundInput
/>
```

### 👀 Severity

Most of the users prefer clicking on the item's body.

- Major

**Comment by BnayaZil** [comment]
![multiSelectCheckbox](https://user-images.githubusercontent.com/13505136/69008408-cd075700-0952-11ea-9b32-81db130ffdc5.gif)

**Comment by EgoziE** [comment]
fixed
