### ISSUE TITLE
<InputWithOptions/> - input value is marked when the drop down is opened

### ISSUE THREAD

**Issue by EgoziE** [wix/wix-style-react#4554]
# 🐛 Bug Report

### 🏗 Relevant Components
`<InputWithOptions/>`

### 😯 Current Behavior
 input value is marked when the drop down is opened

### 🤔 Expected Behavior
 input value should not be marked unless user mark it

### 👣 Steps to Reproduce
![image](https://user-images.githubusercontent.com/35173937/69009938-f8923d80-0962-11ea-8fcb-c4ea928ca029.png)

### 👀 Severity
Low

**Comment by EgoziE** [comment]
only in readonly state

**Comment by mykas** [comment]
Hey @EgoziE & @LittleTal  any reasoning on removing this? I just talked with @milkyfruit and it seems this kind of pattern  is all over the Dropdowns we have. Not just readonly. Or should this be changed only in readonly state?

**Comment by LittleTal** [comment]
@mykas `<MultiSelectCheckbox/>` is not an input and you can't type inside. Therefore there is no need to mark the text.

**Comment by mykas** [comment]
Not sure whats so different on MusltiSelectCheckbox.  @milkyfruit can you add something here? :) does it make sense to make only MultiSelectCheckbox not markable?

**Comment by milkyfruit** [comment]
All dropdown components using 'read-only' input must behave the same. As I know these components behave as discussed: `InputWithOptions `, `Dropdown`,`MultiSelectCheckbox` and `DropdownBase`.

If dropdown component has autocomplete feature, then it's a different matter:
Single select must mark it, while multiselect must show type cursor at the last option.
