### ISSUE TITLE
<Multiselect/> - text is deleted on unfocus

### ISSUE THREAD

**Issue by naamagr** [wix/wix-style-react#4573]
# 🐛 Bug Report

### 🏗 Relevant Components

`Multiselect`

### 😯 Current Behavior

When a user inserts some text and then unfocuses on the component (clicks somewhere else), the text is deleted.

### 🤔 Expected Behavior

the text should be accepted as if the user pressed enter.

### 👣 Steps to Reproduce

Insert some text in the Multiselect component, and click somewhere else on the scree.

### 👀 Severity

Critical - a blocker for teams project

**Comment by argshook** [comment]
This is a bug that was solved long ago but somehow it was removed ¯\_(ツ)_/¯

i can't find in git history how that happened, probably someone did some force pushes.

i'll bring the fix back

**Comment by argshook** [comment]
@naamagr i looked more into this and the bug you're describing is
actually a feature, the intended behaviour.

This component has went through **a lot** and ended up having such
behaviour. You can read about it here:

https://github.com/wix/wix-style-react/blob/master/src/MultiSelect/README.DESIGN-SPEC.md

also lots of insight here https://github.com/wix/wix-style-react/issues/2559

some info also here

https://github.com/wix/wix-style-react/blob/master/src/MultiSelect/README.MIGRATION.md

---

@naamagr the bug you're describing, was it always the case or did it
suddenly start behaving that way? Did you perhaps recently upgrade
wix-style-react version?

**Comment by naamagr** [comment]
I use this component in a new feature. in a new feature. 
I'm sorry I guess I should have listed it as a feature and not a bug.

**Comment by argshook** [comment]
> I'm sorry I guess I should have listed it as a feature and not a bug.

you mean as a missing feature? guess we can consider that, i just remember there were lots of talks about it and we ended up removing it.

@milkyfruit pretty please, chirp in

**Comment by naamagr** [comment]
Yes I mean as a missing feature.

**Comment by shlomitc** [comment]
I think it's ok at the moment to just use the "controlled" mode of the component and attach an `onBlur` event handler.
For example, in the ["Tag Input" example](https://wix-style-react.now.sh/?selectedKind=Components&selectedStory=Multiselect&full=0&addons=0&stories=1&panelRight=0)
`onBlur={() => !!this.state.inputValue && this.handleOnManuallyInput([this.state.inputValue])}`

We will take this into deeper looking on what's the best approach of implementing this feature in the future

**Comment by milkyfruit** [comment]
`<Input/>` doesn't have a cancel event. All values are accepted on key down.
`<MultiSelect/>` can acts as:
A. input (any value is allowed)
B. select (only predefined values are allowed)

For select with autocomplete the common pattern is to cancel on blur.
For input with autocomplete suggestions it depends.

@naamagr on what basis do you request this feature?

**Comment by orgar28** [comment]
Hey @shlomitc We use this component in the new Team Management product, and this is a true blocker for this high priority product.

**Comment by shlomitc** [comment]
@orgar28 - see my answer above https://github.com/wix/wix-style-react/issues/4573#issuecomment-557029343

**Comment by naamagr** [comment]
@shlomitc Unfortunately, it seems that the `onBlur` prop is called **after** the input is cleared

**Comment by shlomitc** [comment]
talked with @naamagr - looks like the right approach will be allowing the consumer to decide whether it should delete the input content when in "controlled" mode. She will work on a PR fix for that

**Comment by argshook** [comment]
thanks to @naamagr PR #4645, `Multiselect` component will have new boolean prop `clearOnBlur`.

It is `true` by default, maintaining current behaviour. For specific cases it will be possible to `<Multiselect clearOnBlur={false}/>` and opt-in to new behaviour
