### ISSUE TITLE
<Dropdown /> - add onOpen callback

### ISSUE THREAD

**Issue by NickVlasov** [wix/wix-style-react#4583]
# ✨ Feature Request

### 🔦 Scope

`<Dropdown />`

### 💁 Explanation

When dropdown list is open it should call provided `onOpen` callback.
`<Dropdown />` already has `onClose` callback, so I think that it should be `onOpen` cb too.
### 🐾 Possible solution 

I can contribute this feature in PR.

### 👀 Severity

Major

**Comment by NickVlasov** [comment]
By the way, `onClose` cb doesn't called now after list is closed.
I call fix this issue in same PR also.

**Comment by argshook** [comment]
PRs are always very welcome :)
