### ISSUE TITLE
Input isDisabled() in puppeteer doesn’t work

### ISSUE THREAD

**Issue by lelikg** [wix/wix-style-react#4584]
# 🐛 Bug Report

in puppeteer - `inputTestkit.getDisabled` and `inputTestkit.isDisabled` return false when `Input` is disabled...

### 🏗 Relevant Components

Input teskit puppeteer
...

### 😯 Current Behavior

...

### 🤔 Expected Behavior

...

### 👣 Steps to Reproduce

  - **WSR version**: `...`
  - **Yoshi version**: `...`

### 👀 Severity

- Critical / Major / Low

**Comment by EgoziE** [comment]
Please use Puppeteer uni-driver:
```
import { InputTestkit } from 'wix-style-react/dist/testkit/puppeteer';
```

Feel free to reopen if the issue persists.
