### ISSUE TITLE
<LinearProgressBar/> - tooltip is shown with empty content

### ISSUE THREAD

**Issue by zivl** [wix/wix-style-react#4597]
# 🐛 Bug Report

### 🏗 Relevant Components
`<LinearProgressBar   
      value={20} 
      error 
      showProgressIndication
/>`

### 😯 Current Behavior
When `LinearProgressBar` component has no error message, the tooltip is still showing with empty content.
![image](https://user-images.githubusercontent.com/4571570/69609671-b89e1b00-1032-11ea-86fc-2ad6297fc02a.png)

### 🤔 Expected Behavior
I would expect that if there is not error message then no need to trigger the tooltip on mouse hover at all

### 👣 Steps to Reproduce
see playground configuration above

### 👀 Severity
Major

**Comment by argshook** [comment]
closed in #4618
