### ISSUE TITLE
<RichTextInputArea /> - when inside form, style buttons reload whole page

### ISSUE THREAD

**Issue by audriuss** [wix/wix-style-react#4604]
# 🐛 Bug Report

### 🏗 Relevant Components
`<RichTextInputArea />`
### 😯 Current Behavior

if `<RichTextInputArea />` added inside `<form/>` styling buttons act as submit buttons so whole page reloads. 

### 🤔 Expected Behavior
When `<RichTextInputArea />` is inside `<form />` clicking style button should not reload the page.

### 👣 Steps to Reproduce

1) Open `<RichTextInputArea />` story page https://wix-style-react.now.sh/?selectedKind=Components&selectedStory=RichTextInputArea&full=0&addons=0&stories=1&panelRight=0
2) Edit one of the example with this code:
```
<form>
  <RichTextInputArea initialValue='test' />;
</form>
```

3) Click one of the styling buttons, for example `B` for bold
### 👀 Severity

- Major

### Possible solution
Add type="button" attribute in styling buttons

**Comment by shlomitc** [comment]
fixed https://github.com/wix/wix-style-react/pull/5320
