### ISSUE TITLE
<Text/> & <popover/> - It's popover should not inherit `line-height` and `font-size` by default

### ISSUE THREAD

**Issue by EgoziE** [wix/wix-style-react#4606]
# 🐛 Bug Report

### 🏗 Relevant Components
`<Text/>`

### 😯 Current Behavior
The text gets wrong height from it's container
The problem was discovered when using `small` size text inside `medium` size checkbox
An image to help
![image](https://user-images.githubusercontent.com/35173937/69726112-79ea8c80-1128-11ea-8730-4b490e4ecf32.png)

### 🤔 Expected Behavior
Text tooltip wrapper should reboot it's style (maybe `all: initial` to root)

### 👣 Steps to Reproduce
This code demonstrates the problem
```
<div style={{ width: '100px', lineHeight: '50px', fontSize: '50px' }}>
  <Text ellipsis>kfjdhskldksjaldkjlaskjfjhdsf</Text>
</div>
```
### 👀 Severity
Major

**Comment by EgoziE** [comment]
@mykas Do you think we should fix it for `<Text/>` specifically or globally in `<Popover/>`?

**Comment by shlomitc** [comment]
won't be fixed
