### ISSUE TITLE
Dropdown component ignore values lower than 192px of dropdownWidth prop

### ISSUE THREAD

**Issue by idancn** [wix/wix-style-react#4609]
# 🐛 Bug Report

### 🏗 Relevant Components

`<Dropdown/>`

### 😯 Current Behavior

passing any value lower than '192px' to dropdownWidth prop sets the width to 192px (it works as expected for higher values).

### 🤔 Expected Behavior

the dropdown width should get the value of dropdownWidth prop, even if it's lower than 192px

### 👣 Steps to Reproduce

pass any value lower than '192px' to `<Dropdown/>`
for example:

`<Dropdown dropdownWidth="50px" />`

  - **WSR version**: 6.58.0
  - **Yoshi version**: 3.31.2

### 👀 Severity

- Major

**Comment by EgoziE** [comment]
According to our design guidelines, this behavior is intentional - closing
