### ISSUE TITLE
ColorInput no colour chosen bug

### ISSUE THREAD

**Issue by gerdasi** [wix/wix-style-react#4611]
# 🐛 Bug Report

### 🏗 Relevant Components

<ColorInput />

### 😯 Current Behavior

I choose a colour in `<ColorInput />` then the colour changes. After I delete the colour code and press enter there is no colour value in input field but chosen colour is still the old one. After pressing enter again colour is set to transparent.

### 🤔 Expected Behavior

I choose a colour in `<ColorInput />` then the colour changes. After I delete the colour code and press enter the colour value in input and chosen swatch are transparent.

### 👣 Steps to Reproduce

  - **WSR version**: `7.19.0`
  - **Yoshi version**: `4.21.11`

### 👀 Severity

- Critical

**Comment by argshook** [comment]
closed by #4624
