### ISSUE TITLE
<SectionHelper/> - close button change position when there's no title

### ISSUE THREAD

**Issue by henrykuzmick** [wix/wix-style-react#4623]
Hi. When you clear the `title` from the `SectionHelper` component, the close button position gets weird https://wix-style-react.now.sh/?activeTab=Playground&addons=0&full=0&panelRight=0&selectedKind=Components&selectedStory=SectionHelper&stories=1

**Comment by EgoziE** [comment]
Should check with UX

**Comment by EgoziE** [comment]
moved to Jira - closing
