### ISSUE TITLE
<Breadcrumbs/> - Enable collapsing long list to a popover menu

### ISSUE THREAD

**Issue by splintor** [wix/wix-style-react#4629]
# ✨ Feature Request

### 🔦 Scope
Extending `<Breadcrumbs>` behavior for a long list of breadcrumbs

### 💁 Explanation
We are going to support nested folders in sites-list, and users have no limitation on the level of folders. We need to show the path of the current folder in breadcrumbs, so the list can be too wide to display.
Our UX wants us to collapse the list, so instead of showing all breadcrumbs, we will show the beginning and the end, and in the middle, we will show a `<PopoverMenu>` that will contain all the missing breadcrumbs.

Zeplin specs:
- https://zpl.io/2j7r43A
- https://zpl.io/bzj9WD8

### 👀 Severity
- Major (the Nested Folder feature is due to next month, and we need it for this)

**Comment by EgoziE** [comment]
Hey @splintor 
I talked with Shlomi about this, he prefers that this change will not be as part of the component.
Please try this code:
```
import React from 'react';
import Breadcrumbs from 'wix-style-react/Breadcrumbs';
import { Layout, Cell } from 'wix-style-react/Layout';

class StandardBreadcrumbs extends React.Component {
  render() {
    const pp = <PopoverMenu
  buttonTheme="icon-greybackground"
  placement="bottom"
  size="normal"
>
  <PopoverMenuItem
    dataHook="story-popover-menu-item"
    onClick={() => {}}
    text="..."
  />
</PopoverMenu>;

    const items = [
      { id: 1, value: 'first item' },
      { id: 2, value: pp },
      { id: 3, value: 'third item' },
    ];

    return (
      <Layout>
        <Cell>
          <Breadcrumbs size="large" items={items} />
        </Cell>
      </Layout>
    );
  }
}
export default StandardBreadcrumbs;
```

Here the menu is the middle breadcrumb (yes, there will always be 3 options, the 2nd one is the menu)
If you'll encounter any styling problems, we can consider small changes inside `<Breadcrumbs/>`

**Comment by splintor** [comment]
But I need this to be dynamic. I want the menu to replace existing items only when the component has no room to display all of the items.

Keep in mind that our usage of the component is very dynamic - we show a folder path, and we don't control the length or the names of the folder parts.

If you think that `<Breadcrumbs>` component is not suitable for this use and we should develop our own component, please let us know.

**Comment by shlomitc** [comment]
@splintor - the requirement for dynamic width was not approved. It requires the component to do width measurement on initial rendering which means it is not SSR friendly.
So anyway - it means you will need to know in advance what is the limit, based on the number of items.

Regarding the menu itself, I think it's ok to give control to the consumer to do these compositions, instead of bundling it inside the component.

```jsx
import React from 'react';
import Breadcrumbs from 'wix-style-react/Breadcrumbs';
import PopoverMenu from 'wix-style-react/Beta/PopoverMenu';

class BreadcrumbsWithPopoverMenu extends React.Component {
  render() {
    const items = [
      { id: 1, value: 'First Item' },
      {
        id: 2,
        value: (
          <PopoverMenu
            appendTo="window"
            triggerElement={<TextButton>...</TextButton>}
          >
            <PopoverMenu.MenuItem text="Second Item" />
            <PopoverMenu.MenuItem text="Third Item" />
          </PopoverMenu>
        ),
      },
      { id: 3, value: 'Fourth Item' },
    ];

    return (
      <div style={{ paddingBottom: '100px' }}>
        <Breadcrumbs items={items} activeId={3}/>
      </div>
    );
  }
}
```

**Comment by splintor** [comment]
OK, I'll start with that and see how it goes. Thanks!

**Comment by splintor** [comment]
BTW, what about https://github.com/wix/wix-style-react/issues/4630? Will it be implemented using measurement? Or is it **low priority** and is never going to happen?

**Comment by shlomitc** [comment]
#4630 looks pretty straightforward, just replacing the content of the `Breadcrumbs` with the `Text` component that supports `ellipsis` which uses pure CSS to display the "...".

It is on low priority :)

**Comment by splintor** [comment]
`<Breadcrums`> [is already using `<Text>` component](https://github.com/wix/wix-style-react/blob/master/src/Breadcrumbs/Breadcrumbs.js#L71), but it just doesn't pass `ellipsis` prop. As I wrote [here](https://github.com/wix/wix-style-react/issues/3087#issuecomment-560101673), I tried creating a PR to fix it, but it's not as trivial as I thought.

Please note that `ellipsis` doesn't just use purs CSS. It uses [`EllipsisHOC`](https://github.com/wix/wix-style-react/blob/master/src/common/EllipsisHOC/EllipsisHOC.js) which uses wix-ui-core's [`withEllipsedTooltip`](https://github.com/wix/wix-ui/blob/master/packages/wix-ui-core/src/hocs/EllipsedTooltip/withEllipsedTooltip.tsx) which [uses measurement](https://github.com/wix/wix-ui/blob/master/packages/wix-ui-core/src/hocs/EllipsedTooltip/withEllipsedTooltip.tsx#L81) to determine whether the tooltip should be displayed...

Is there any chance to raise the priority of https://github.com/wix/wix-style-react/issues/4630, as we will need it for our **Nested Folders** feature?

**Comment by splintor** [comment]
@shlomitc @EgoziE We are about to get back to develop nested folders and need this to be addressed. I see you raised the priority of https://github.com/wix/wix-style-react/issues/4630.

Any update on this?
