### ISSUE TITLE
`<MessageBoxFunctionalLayout />` - ButtonsHeight 'tiny' sets sizes of 'small'

### ISSUE THREAD

**Issue by marik22312** [wix/wix-style-react#4644]
# 🐛 Bug Report

### 🏗 Relevant Components
`<MessageBoxFunctionalLayout />`

...

### 😯 Current Behavior

When setting the `buttonsHeight` prop to tiny, the buttons get bigger than when setting the prop to small

### 👣 Steps to Reproduce

  - **WSR version**: `7.15`
  - **Yoshi version**: `3`

### 👀 Severity

- Critical

**Comment by avrahamr** [comment]
@shlomitc any news about it?

**Comment by EgoziE** [comment]
We discovered this requires more effort than it is prfioritized.
If it's a blocker for you we can raise its priority.

**Comment by avrahamr** [comment]
It's not a blocker, and understand your point, but if low priority means `won't fix` it's less ideal. The big buttons don't look very professional...

**Comment by marik22312** [comment]
IMO, I think we should at least update the docs / fix it to work properly with the old button component...

**Comment by shlomitc** [comment]
This quarter we are going to develop new modal layouts, thus planning to deprecate the existing ones.
We'll be happy to merge a PR fixing it in the meanwhile

**Comment by shlomitc** [comment]
fixed
