### ISSUE TITLE
<Sidebar/> - Title color is wrong

### ISSUE THREAD

**Issue by banuni** [wix/wix-style-react#4653]
# 🐛 Bug Report

### 🏗 Relevant Components

<SidebarSectionTitle />

### 😯 Current Behavior
![image](https://user-images.githubusercontent.com/5357377/70139938-4bc2fa80-169c-11ea-8db2-19ce23c14ffe.png)

SidebarSectionTitle is almost transperant

### 🤔 Expected Behavior
SidebarSectionTitle should look as before
![image](https://user-images.githubusercontent.com/5357377/70139960-58475300-169c-11ea-9ce6-f60e7ecc27ed.png)

### 👀 Severity
- Critical , BLOCKER

**Comment by shlomitc** [comment]
fixed
