### ISSUE TITLE
<ListItemSelect/> - Allow passing tooltip options delay

### ISSUE THREAD

**Issue by marik22312** [wix/wix-style-react#4655]
# ✨ Feature Request

### 🔦 Scope

Behavior change / extend functionallity

### 💁 Explanation

Currently, when passing the `ellipsis` prop to `<ListItemSelect/>`, there's a tooltip that's getting revealed on hover. this tooltip reveals too fast and may cause some bad UX (See attached video)

https://drive.google.com/open?id=18g83zcpZgqMp6wCN7k2IWO1pKTR_00nn

### 🐾 Possible solution
Added a small delay to the tooltip / allow us to pass the delay props to the tooltip

### 👀 Severity

- Medium

**Comment by EgoziE** [comment]
PR - https://github.com/wix/wix-style-react/pull/4816

**Comment by EgoziE** [comment]
added a delay of 300ms, no need for a prop :)
