### ISSUE TITLE
Tooltip text alignment 

### ISSUE THREAD

**Issue by lbelinsk** [wix/wix-style-react#466]
Reported bug by Account recovery qa:

Alignment of all tool tips is centered instead of a nice way to read it 

https://www.screencast.com/t/NEYFq8eUBV

@nirhart

**Comment by lbelinsk** [comment]
You can see it in story-book also:

![image](https://cloud.githubusercontent.com/assets/18248989/26186649/994a6484-3b9b-11e7-940d-ca45132397be.png)

**Comment by nirhart** [comment]
Tooltip have a textAlign property that by default it 'center', you can make it 'right'
