### ISSUE TITLE
`<SectionHelper/>` title is not affected by `fullWidth` prop

### ISSUE THREAD

**Issue by AtomicAlienZ** [wix/wix-style-react#4664]
# 🐛 Bug Report

### 🏗 Relevant Components

`<SectionHelper/>`

### 😯 Current Behavior

Title stays narrow when `fullWidth` prop is set to true

![image](https://user-images.githubusercontent.com/1439457/70246653-b8afc080-1780-11ea-96a6-5e5897fd1e59.png)

### 🤔 Expected Behavior

Title should take 100% of available space

![image](https://user-images.githubusercontent.com/1439457/70246702-c9603680-1780-11ea-8cd1-c83e0e908e4a.png)

### 👣 Steps to Reproduce

  - **WSR version**: `7.20.0`
  - **Yoshi version**: `^4.17.0`

### 👀 Severity

- Critical / Major / Low

**Comment by shlomitc** [comment]
@milkyfruit - AFAIK, it was intended to support only the running text and not the title, is that true?

**Comment by EgoziE** [comment]
SectionHelper
