### ISSUE TITLE
<InputWithOptions/> - Native Select component not reflecting selected option

### ISSUE THREAD

**Issue by saarkuriel** [wix/wix-style-react#4666]
# 🐛 Bug Report

### 🏗 Relevant Components

`<InputWithOptions />`, `<Dropdown />` and whoever is using native select.

### 😯 Current Behavior

First option seems to be always selected even though it's not really reflected in the component. Also, you cannot choose it until you choose another one.

### 🤔 Expected Behavior

Component should reflect the selected option correctly.

### 👣 Steps to Reproduce

  - **WSR version**: `...`
  - **Yoshi version**: `...`

You can view in this storybook after turning on `native` prop:
https://wix-style-react.now.sh/?activeTab=Playground&addons=0&full=0&panelRight=0&selectedKind=Components&selectedStory=Dropdown&stories=1
### 👀 Severity

- Major

**Comment by EgoziE** [comment]
Moved to Jira - closing
