### ISSUE TITLE
<ListItemSection /> texts don't land on the same baseline

### ISSUE THREAD

**Issue by milkyfruit** [wix/wix-style-react#4669]
@EgoziE 

# 🐛 Bug Report

### 🏗 Relevant Components
[`<ListItemSection /> `](https://wix-style-react.now.sh/?selectedKind=Components&selectedStory=ListItemSection&full=0&addons=0&stories=1&panelRight=0&activeTab=Description)

### 😯 Current Behavior

`type="title"` and `type="subheader"` with `suffix` prop, texts don't land on the same baseline, while in design docs they do. Tested on Chrome, Firefox and Safari browsers on mac, suffix text is 1px too high:
![image](https://user-images.githubusercontent.com/1684587/70253720-67a5c980-178c-11ea-8aea-287602f3c43f.png)

However, text containers follow [design specs](https://zpl.io/2EgZ86n) correctly and land where they should:
![image](https://user-images.githubusercontent.com/1684587/70253501-02ea6f00-178c-11ea-8850-a7053a8c235f.png)

### 🤔 Expected Behavior
Align to land both texts on the same baseline:
![image](https://user-images.githubusercontent.com/1684587/70253881-bfdccb80-178c-11ea-83d6-07bad0872692.png)

### 👀 Severity

- Minor

**Comment by EgoziE** [comment]
The problem is with `<TextButton/>`
For some reason `tiny` size is height 18px instead of 15px, and then the text is automatically centred.

```
<Box>
    <Text size="small">hello</Text>
    <TextButton size="tiny">hello</TextButton>
</Box>
```

![image](https://user-images.githubusercontent.com/35173937/70378543-23e8c680-192a-11ea-996a-3d7d0aa08e67.png)

**Comment by EgoziE** [comment]
Anyway I'll fix 'em both :P

**Comment by EgoziE** [comment]
Opened 2 PRs
wix-style-react - https://github.com/wix/wix-style-react/pull/4672
**Blocked by:**
ui-core - https://github.com/wix/wix-ui/pull/1647
