### ISSUE TITLE
<PopoverMenu/> - Text is wrapped in items on Edge and Windows when using appendTo="parent"

### ISSUE THREAD

**Issue by splintor** [wix/wix-style-react#4675]
# 🐛 Bug Report

### 🏗 Relevant Components

beta `<PopoverMenu>`

### 😯 Current Behavior

This happens only on Edge on Windows. When using `<PopoverMenu>` component, and setting its `appendTo` prop to `'parent'`, items that are longer than the default width of the dropdown are wrapped.

...

### 🤔 Expected Behavior
Items text should not be wrapped - as it behaves in all other browsers.

### 👣 Steps to Reproduce
1. Open [`PopoverMenu` StoryBook](https://wix-style-react.now.sh/?selectedKind=BETA&selectedStory=PopoverMenu&full=0&addons=0&stories=1&panelRight=0) in Edge on Windows
2. In the first example, replace the code with:
```
<PopoverMenu
  triggerElement={
    <IconButton priority="secondary">
      <Icons.More />
    </IconButton>
  }
  appendTo="parent"
>
  <PopoverMenu.MenuItem text="Get Feedback" prefixIcon={<Icons.Chat />}/>
  }/>
</PopoverMenu>;
```
3. Open the popover menu.

The "Get Feedback" text will be wrapped. (It will not be wrapped on Chrome, or even on Edge on Mac).

#### Notes:
1. It won't happen if you don't set `appendTo="parent"`.
1. Setting `ellipsis` prop seems to fix the problem.

### 👀 Severity
- Low

**Comment by EgoziE** [comment]
changed PopoverMenu.MenuItem to wrap overflowing text.
