### ISSUE TITLE
CardGalleryItem with Popover as settingsMenu

### ISSUE THREAD

**Issue by miroshSa** [wix/wix-style-react#4677]
# 🐛 Bug Report

### 🏗 CardGalleryItem

CardGalleryItem

### 😯 Current Behavior

When you set in prop `settingsMenu` <Popover appendTo="parent">... the content of Popover is cut because of property `overflow:hidden` in data-hook='hover-component'

...

### 🤔 Expected Behavior

The content of Popover is fully shown

### 👣 Steps to Reproduce

Put <Popover appendTo="parent"> as  settingsMenu prop for CardGalleryItem conponent

  - **WSR version**: `7.21.0`
  - **Yoshi version**: `4.22.3`

### 👀 Severity

- Major

**Comment by shlomitc** [comment]
can't reproduce, can you please share a code example?

**Comment by miroshSa** [comment]
https://github.com/wix-private/video-maker/blob/6137607ef7551045ab5aa53e537b35c858c23451/video-maker-home/src/components/GalleryItem/GalleryItem.tsx#L154

**Comment by EgoziE** [comment]
Hey @miroshSa 
Is it still relevant? if so, can you please create a reproducible example is our Storybook?

**Comment by miroshSa** [comment]
@EgoziE I think the issue can be closed
