### ISSUE TITLE
<ColorInput/> with <Swatches/> -  turn black on empty color selected (showClear prop)

### ISSUE THREAD

**Issue by daphnakaplan** [wix/wix-style-react#4684]
# Bug Report:
when using ColorInput with swatch as child node with "showClear" prop true  , if selecting the empty color, input turns black (value "#000000") instead of none/null

### Relevant Components:
ColorInput + Swatches

### 😯 Current Behavior

clicking "empty" in the swatch leads to color input turning black 

### 🤔 Expected Behavior

clicking "empty" in the swatch leads to color input turning none/null/''

### 👣 Steps to Reproduce
@EgoziE managed to reproduce :
our usecase is here:
[](https://github.com/wix-private/photography/blob/5b55788f8b9d35c195a75a2e56ff4db2cabf8c54/logo-builder/zoe-editor/packages/zoe-editor-view/src/components/editors/desktop/EditorColorInput.js
)
and can be seen here:
[](http://wix.to/GEBuBLU)

### 👀 Severity

we don't have a workaround and we are looking forward launching LogoBuilder 2.0 in the coming week.

**Comment by EgoziE** [comment]
To reproduce:
```
<ColorInput
  value="#FFFFFF"
  colorPickerChildren={({ changeColor }) => (
    <Swatches
    showClear
      onClick={changeColor}
    />
  )}
/>;
```

**Comment by EgoziE** [comment]
PR - https://github.com/wix/wix-style-react/pull/4815
