### ISSUE TITLE
MessageBoxFunctionalLayout missing features and confusing

### ISSUE THREAD

**Issue by shlomitc** [wix/wix-style-react#470]
1. The close button doesn't get a specific action, it inherits it from the cancel button. it doesn't make sense since the current callback for the cancel button is called `onCancel`, which is not closing.

2. width - doesn't look like something we should pass in. width should be either dynamic or fixed to 600 without being able to modify.

**Comment by nirhart** [comment]
1. fixed
2. its fixed to 600 unless you change it
