### ISSUE TITLE
[ModalSelectorLayout] - Minor issue in "dataSource" signature

### ISSUE THREAD

**Issue by rudnitskih** [wix/wix-style-react#4704]
# Documentation Issue

### 🔦 Scope

Relevant Page URL: https://wix-style-react.now.sh/?activeTab=API&addons=0&full=0&panelRight=0&selectedKind=Components&selectedStory=ModalSelectorLayout&stories=1

### 💁 Explanation

In docs described that `title` prop in item which returned by `dataSource` callback should be a string but I think it should be a Node. This mistake produces also wrong typing in `wsr-types`.

![image](https://user-images.githubusercontent.com/8848858/70819384-c8618180-1dde-11ea-9869-3814c43528e2.png)

### 👀 
- [X] Low

**Comment by shlomitc** [comment]
solved. closing

**Comment by rudnitskih** [comment]
@shlomitc thank you!
