### ISSUE TITLE
<Accordion> - Doesn't collapse when clicking on an item

### ISSUE THREAD

**Issue by b3llash** [wix/wix-style-react#4707]
# 🐛 Bug Report

### 🏗 Relevant Components
`<Accordion>`

### 😯 Current Behavior
When collapsed, clicking anywhere on the item makes it expand.
When expanded, the item itself is inactive and the user must click on the icon to collapse.
[GIF](https://i.gyazo.com/8f45bbbbbc255199360916236949172c.gif)

### 🤔 Expected Behavior
Clicking anywhere on the item should expand/collapse.

  - **WSR version**: `7.22.0`

### 👀 Severity
Major

@tzabarc @BnayaZil

**Comment by argshook** [comment]
Hello, @b3llash this is actually intended behaviour according to spec.

![2019-12-16-104436_screenshot](https://user-images.githubusercontent.com/4284659/70892039-10f08900-1ff1-11ea-94c2-dd0a61cb44dd.png)

but perhaps it's not a good behaviour and should be revisited. @LittleTal please advise

**Comment by LittleTal** [comment]
Updated Zeplin spec
Open item should have Shadow30
and there is a divider at the bottom of the item's content area 

![image](https://user-images.githubusercontent.com/23282301/71369662-2139d280-25b4-11ea-9e64-8a16957b29e2.png)
