### ISSUE TITLE
<ImageViewer/> - add item not displayed correctly

### ISSUE THREAD

**Issue by shlomitc** [wix/wix-style-react#4708]
# 🐛 Bug Report

### 🏗 Relevant Components

`<ImageViewer/>`

### 😯 Current Behavior

![image](https://user-images.githubusercontent.com/6093192/70868488-0e0e7d80-1f8a-11ea-8a06-17d8ff2218b7.png)

When an image is loaded, the `AddItem` appears half the size it's supposed to be. This is because the "Image container" is displayed alongside it at the same time

### 🤔 Expected Behavior
the Image container should not be visible alongside the `<AddItem/>` while an image is still loading.

1. Comment out these lines https://github.com/wix/wix-style-react/blob/master/src/ImageViewer/ImageViewer.js#L90-L95
2. Open dev-tools and disabled cache
3. Check any [example](http://localhost:6006/?selectedKind=Components&selectedStory=ImageViewer&full=0&addons=0&stories=1&panelRight=0) of `ImageViewer` with `imageUrl` prop

### Side note

Please make sure that when making changes, this transition between URLs still looks ok (without falling back to AddItem)

```js
class MyComponent extends React.Component {
  state = {url: "https://static.wixstatic.com/media/c78d05b79ede429fb77c9d8ec4443b93.jpg/v1/fit/w_375,h_375/c78d05b79ede429fb77c9d8ec4443b93.jpg"}

  componentDidMount() {
    setTimeout(() => this.setState({url: 'https://onlinepngtools.com/images/examples-onlinepngtools/palm-fronds-and-sky.png'}), 1000);
  }
  render() {
    return (
      <ImageViewer imageUrl={this.state.url}/>
    )
  }
}
```

  - **WSR version**: `7.22.0`

**Comment by EgoziE** [comment]
fixed
