### ISSUE TITLE
<InputArea/> - missing status prop

### ISSUE THREAD

**Issue by MayaHamo** [wix/wix-style-react#4710]
Currently `<InputArea/>` has only 2 status options:
1. regular
2. error

Unlike very similar component, `<Input/>` which has 4 status options:
1. regular
2. error
3. warning
4. loading

_Possible solution:_
Replace **error** (bool) and **errorMessage** InputArea props, in **status** (string) and **statusMessage** props, like in Input.

**Comment by EgoziE** [comment]
PR - https://github.com/wix/wix-style-react/pull/4736/

**Comment by shlomitc** [comment]
Merged, closing
