### ISSUE TITLE
<Accordion /> missing divider 

### ISSUE THREAD

**Issue by LittleTal** [wix/wix-style-react#4715]
# 🐛 Bug Report

### 🏗 Relevant Components
`<Accordion />`

...

### 😯 Current Behavior
After selecting an item title, there is no divider between the content and the next item title.
Instead, the divider appears only at the bottom of the open item's title

![image](https://user-images.githubusercontent.com/23282301/70976679-10212b00-20b5-11ea-9677-9f40c5306d44.png)

While hovering the second item the bg from the first item is merged with the hover of the next item : 

![image](https://user-images.githubusercontent.com/23282301/70976722-24652800-20b5-11ea-802d-2dbcee878ee0.png)

...

### 🤔 Expected Behavior
Divider should appear also at the end of the content area when item is open:

![image](https://user-images.githubusercontent.com/23282301/71076015-b04a8300-218d-11ea-9188-dac7bd5b62eb.png)

On hover 

![image](https://user-images.githubusercontent.com/23282301/71076084-ca846100-218d-11ea-96de-1b2c69610e0f.png)

...

### 👣 Steps to Reproduce

  - **WSR version**: `...`
  - **Yoshi version**: `...`

### 👀 Severity

Low

**Comment by milkyfruit** [comment]
other related issue: https://github.com/wix/wix-style-react/issues/4721
