### ISSUE TITLE
<Carousel/> controllers position prop and new skin

### ISSUE THREAD

**Issue by LittleTal** [wix/wix-style-react#4723]
# ✨ Feature Request

### 🔦 Scope

Existing `<Carousel/>` component 

...

### 💁 Explanation

1. Need to add a new prop for controller position, currently controllers are located to the sides of the content:
![image](https://user-images.githubusercontent.com/23282301/71078122-6e234080-2191-11ea-93ed-2fc46e25fd07.png)

should be added an overlay option: 
![image](https://user-images.githubusercontent.com/23282301/71078144-77aca880-2191-11ea-86d3-2408cf55a07e.png)

Constraints:
Margins for small buttons- 6px
Margins for medium buttons- 12px

![image](https://user-images.githubusercontent.com/23282301/71078321-d1ad6e00-2191-11ea-887b-0970d60b6bcd.png)

2. Need to add a new skin option- 'transparent' 

![image](https://user-images.githubusercontent.com/23282301/71080417-c4927e00-2195-11ea-9eb4-c93f16d3ce77.png)

[Updated Zeplin spec](https://zpl.io/2EBGeGe)

...

### 🐾 Possible solution 

...

### 👀 Severity

Low

**Comment by TalZa1810** [comment]
Maybe we should consider exporting the Arrow Buttons to a new component? Since we're implementing these also for the `<ModalPreviewLayout/>`  (with a transparent skin) -https://zpl.io/bAlmpze

WDYT? 
@LittleTal  @shlomitc

**Comment by shlomitc** [comment]
Having the transparent button skin is enough. I don’t see the need for some predefined reusable composition/logic

**Comment by EgoziE** [comment]
done
