### ISSUE TITLE
<Input/> - refactor is needed for the entire "Suffix" implementation

### ISSUE THREAD

**Issue by shlomitc** [wix/wix-style-react#4731]
# ✨ Refactor Request

### 🔦 Scope
`<Input/>`, `<InputArea/>` but also other Input/Selection family components.
As part of adding `warning` state to `InputArea`, it came out there is separate logic to `Input` and to `InputArea` that does the same.

### Explanation
[`InputSuffix.js`](https://github.com/wix/wix-style-react/blob/master/src/Input/InputSuffix.js) file in the Input folder contains a common status logic (`error`, `warning`, `loading`).
However, it also contains some other old states (`info`, `magnifyingGlass`, `unit`) that should be deprecated from `Input`.
It also contains suffixes that used by `Input` but shouldn't be exposed to the `InputArea` (`menuArrow`)

### 🐾 Possible solution
I suggest making the reusable suffixes (error, warning, loading) shared across the "Inputs".
When Dropdowns are using it, it would extend them with custom suffixes such as `menuArrow`.
And so on...

It's a refactor, but also adding the missing capabilities to the other input related components

**Comment by EgoziE** [comment]
Merge `<ErrorIndicator/>` and `<WarningIndicator/>` to -> `<StatusIndicator/>`
An action item from - https://github.com/wix/wix-style-react/pull/4736

**Comment by EgoziE** [comment]
done
