### ISSUE TITLE
Merge <ErrorIndicator/> and <WarningIndicator/> to -> <StatusIndicator/>

### ISSUE THREAD

**Issue by EgoziE** [wix/wix-style-react#4738]
`<ErrorIndicator/>` and `<WarningIndicator/>` to -> `<StatusIndicator/>`
An action item from - https://github.com/wix/wix-style-react/pull/4736

**Comment by shlomitc** [comment]
Very much related to this PR
https://github.com/wix/wix-style-react/issues/4731
Maybe we can merge them?
