### ISSUE TITLE
Support wix-style-react with puppeteer on Sled 

### ISSUE THREAD

**Issue by Maozsm** [wix/wix-style-react#4739]
# ✨ Feature Request

Request to better support Sled with WSR components. 

### 💁 Explanation

Currently, Sled(Puppeteer) isn't working well with WSR Components. 
Using `wix-style-react/dist/testkit/puppeteer`
**Running Sled on local machine** get `Jest encountered an unexpected token`.
**Running Sled remotely** get `Your tests depend on unsupported external modules.`

Using `wix-style-react/dist/testkit/puppeteer-testkit-bundle`
**Running Sled remotely** machine partially works for some testkit like inputTestkitFactory, but only send the first character to input field. For other testkit like "tabsTestkitFactory", not working at all. 
**Running Sled on local machine** get `ReferenceError: window is not defined`

### 👀 Severity

- High

**Comment by shlomitc** [comment]
Please follow the instructions in the slack channel
https://wix.slack.com/archives/CHKPRKSG7/p1580388563122400

**Comment by Maozsm** [comment]
I followed the instructions but still have the same problem with inputWithLabelTestkitFactory. 

> machine partially works for some testkit like inputTestkitFactory, but only sends the first character to the input field.

**Comment by shlomitc** [comment]
Please follow these instructions: https://wix-private.github.io/sled/docs/component-libraries-testkits.
Thanks
