### ISSUE TITLE
<AddItem/> - in theme 'image', tooltip is empty when its content is undefined

### ISSUE THREAD

**Issue by rotemzif** [wix/wix-style-react#4740]
# 🐛 Bug Report

### 🏗 Relevant Components

AddItem

### 😯 Current Behavior

this component with the theme "image" is showing the tooltip even if it sets to null.
 
### 🤔 Expected Behavior

Tooltip should not be shown if the 'tooltipContent' is set to null, as written in the API.

### 👣 Steps to Reproduce
 - **WSR version**: `latest`
  - **Yoshi version**: `latest`

### 👀 Severity

  Major

**Comment by EgoziE** [comment]
PR - https://github.com/wix/wix-style-react/pull/4822
