### ISSUE TITLE
Cheatsheet links are broken

### ISSUE THREAD

**Issue by TalZa1810** [wix/wix-style-react#4743]
# 🐛 Bug Report

After the storybook migration, the cheatsheet links got broken.
I think it's related to the change of the stories hierarchy: 
https://wix-style-react.now.sh/?path=/story/introduction-cheatsheet--components-cheatsheet

Related file:
https://github.com/wix/wix-style-react/blob/master/stories/symbolsComponentsMapping/storybookMapping.js

`linkTo` documentation:
https://github.com/storybookjs/storybook/tree/next/addons/links

### 😯 Current Behavior
Both links of UX Stories & Component Stories are broken

### 🤔 Expected Behavior
Working links :) 

### 👣 Steps to Reproduce

  - **WSR version**: `7.25.0`
### 👀 Severity
- Low

**Comment by EgoziE** [comment]
PR - https://github.com/wix/wix-style-react/pull/4745

**Comment by TalZa1810** [comment]
Fixed.
