### ISSUE TITLE
<listItemSelect/> - support indeterminate checkbox

### ISSUE THREAD

**Issue by adimorwix** [wix/wix-style-react#4758]
#✨ Feature Request
Add option to indeterminate checkBox in ListItemSelect 
checkBox already supports indeterminate.

### 🔦 Scope 

We rewrite exist component in contacts
We want to replace checkBox + label with ListItemSelect

![image](https://user-images.githubusercontent.com/47712745/71556343-25487300-2a40-11ea-9fc3-bd95dcfd2d81.png)
  
### 👀 Severity
- Major

**Comment by EgoziE** [comment]
Moved to Jira - closing
