### ISSUE TITLE
<Tooltip> testkit - add isTooltipDisabled method

### ISSUE THREAD

**Issue by splintor** [wix/wix-style-react#4765]
# ✨ Feature Request

### 🔦 Scope
Testkit for `<Tooltip>` component

### 💁 Explanation
`<Tooltip>` component has a `disabled` feature which enables hiding the tooltip when its `disabled` prop is truthy or when its children's `disabled` prop is truthy.

We need our tests to be able to detect if a `<Tooltip>` component is disabled.

I'd issue a PR, but this probably requires change to `wix-core-ui`, which I'm less familiar with.

### 🐾 Possible solution
We can find the `<Tooltip>` component in the components tree and query its `props`, but that's what testkit is for...

### 👀 Severity

- Major / Low

**Comment by EgoziE** [comment]
Moved to Jira - closing
https://jira.wixpress.com/browse/DSM-1494
