### ISSUE TITLE
`<InputSuffix/>` - change tooltip alignment to `left`

### ISSUE THREAD

**Issue by TalZa1810** [wix/wix-style-react#4770]
# 🐛 Bug Report

### 🏗 Relevant Components

Currently the text alignment of all tooltips which are rendered inside `<InputSuffix/>` are `center`.  For example here:
https://github.com/wix/wix-style-react/blob/master/src/Input/ThemedInputErrorSuffix.js#L34
We would like to change the alignment to `left`. 

### 😯 Current Behavior

The text alignment is `center`.

<img width="716" alt="tttt" src="https://user-images.githubusercontent.com/24567980/71586277-51d4bb80-2b22-11ea-953a-4f2c8cdc4624.png">

### 🤔 Expected Behavior

Text alignment should be `left`:
![image (5)](https://user-images.githubusercontent.com/24567980/71586314-7335a780-2b22-11ea-844d-66a34b1eb352.png)

### 👣 Steps to Reproduce

  - **WSR version**: `7.28.0`

### 👀 Severity

- Low

**Comment by shlomitc** [comment]
is this approved by UX?

**Comment by TalZa1810** [comment]
It is approved by UX and was already fixed with the `StatusIndicator` component (which was implemented within the `Input`). We can close this one.
