### ISSUE TITLE
MultiSelect won't receive error prop with value false when 'select' mode is enabled

### ISSUE THREAD

**Issue by bendetro** [wix/wix-style-react#4775]
# 🐛 Bug Report

### 🏗 Relevant Components

MultiSelect

### 😯 Current Behavior

MultiSelect won't receive error prop with value false when 'select' mode is enabled

### 🤔 Expected Behavior

MultiSelect will receive error prop with value false when 'select' mode is enabled AKA behave normally
...

### 👣 Steps to Reproduce

create a MultiSelect component with 'select' mode enabled and error={false}, an error will show in the console.

  - **WSR version**: `^7.26.0`
  - **Yoshi version**: `^4.16.4`

### 👀 Severity

 Low

**Comment by EgoziE** [comment]
PR - https://github.com/wix/wix-style-react/pull/4828
