### ISSUE TITLE
`<DatePicker/>` - Allow passing custom "placement" prop

### ISSUE THREAD

**Issue by marik22312** [wix/wix-style-react#4796]
# ✨ Feature Request

### 🔦 Scope

Adding additional functionality to the `<DatePicker/>` cmponent

### 💁 Explanation

Allow the `<DatePicker/>` component to pass a "placement" prop to its popover,
to allow opening the popover in any desired direction.

this feature was discussed with @mykas on slack, and as he explained the component is using Popper.js and not WSR popover, so this is a feature request and not a bug.

### 🐾 Possible solution 

refactor `DatePicker` to use WSR Popover

### 👀 Severity

- Major, as we are having a UX bug because sometimes the component is opening to the top, while there's plenty of space under the trigger element.

**Comment by mykas** [comment]
Migrated to Popover and now it exposes `popoverProps`.
