### ISSUE TITLE
Modal issues

### ISSUE THREAD

**Issue by mastertheblaster** [wix/wix-style-react#48]
Please correct me if I am wrong, but I see the following issues:

* Missing tests for layouts
* Missing layout for videos
* Missing animations
* Current layouts `Layout1` and `Layout2` can be satisfying for a project, but not for a lib.

**Comment by lbelinsk** [comment]
That sounds like a problem with the modal's layouts not with the modal itself, so i am renaming the issue's name.

The current status is that we have some tests, but the layouts are not well organised.
I agree that we don't have a lot of layouts, but I don't think that we should implement any additional layouts until some actual requirement will appear.

Breaking into actual tasks:

- [ ] Organise the layouts
![image](https://user-images.githubusercontent.com/18248989/30253442-c33c1f4c-968d-11e7-8467-1befa28b7caa.png)

- [ ] Make sure we have tests + testkits for the layouts. (e2e as well)

**Comment by shlomitc** [comment]
1. we use eyes tests for visual regression
2. no layout was designed for video, you can just display one in a modal until defined.
3. no animations are defined
4. they are not documented nor suggested to be used, so I guess we will drop them one day

thanks
