### ISSUE TITLE
`<SortableList/>` repositioning of dragged item in nested sortable lists

### ISSUE THREAD

**Issue by argshook** [wix/wix-style-react#4804]
# 🐛 Bug Report

### 🏗 Relevant Components

`<SortableList/>`

### 😯 Current Behavior

nested SortableLists can have scenario where dragged objects do not
maintain their position. After mindlessly dragging objects around they
can sometimes jump back to initial position or even duplicate.

### 🤔 Expected Behavior

dragged items should always retain correct position

### 👣 Steps to Reproduce

reproducable example in storybook

https://wix-style-react.now.sh/?path=/story/components-api-work-in-progress-sortablelist--multi-area-list-with-sortable-columns

1. drag `Drag object 1` from left column to right one
2. while dragging, move `Drag object 1` outside of right column
3. drop `Drag object 1`
4. start dragging right column
5. observe how `Drag object 1` re-appers back in first column

![pr-4620](https://user-images.githubusercontent.com/4284659/71870879-09b82900-3120-11ea-9a5e-0f1b2d8e2cbe.gif)

  - **WSR version**: `7.30.0`

### 👀 Severity

- Low

**Comment by argshook** [comment]
an attempt to fix this issue was done here https://github.com/wix/wix-style-react/pull/4620

however, said fix induces additional issue, namely in safari:

while replaying reproduction scenario, multiple drag object might appear as hovered

**Comment by EgoziE** [comment]
Moved to Jira - closing
