### ISSUE TITLE
AllInputs: Use `Layout` / `Container` instead of using inline styling

### ISSUE THREAD

**Issue by jonathanadler** [wix/wix-style-react#4868]
I recommend using `Layout` / `Container` instead of using inline styling:
https://github.com/wix/wix-style-react/blob/master/docs/usage/LAYOUTING.md

_Originally posted by @TalZa1810 in https://github.com/wix/wix-style-react/pull/4727_

**Comment by shlomitc** [comment]
I think this doesn't need an issue. it's internal to documentation so it can be changed at any point.
closing
