### ISSUE TITLE
`hasLoader` method from Input TestKit API should return a Boolean value

### ISSUE THREAD

**Issue by iamjager** [wix/wix-style-react#4869]
# 🐛 Bug Report

### 🏗 Relevant Components
`Input`, `InputWithOptions`, `Search`

### 😯 Current Behavior
`inputTestkitFactory({...}).hasLoader()` returns either `null` or `HTMLElement`.

### 🤔 Expected Behavior
`inputTestkitFactory({...}).hasLoader()` should return a relevant `Boolean` value depending on whether loader is present or not.

My guess is that the root of the problem is that `querySelector` result should be coerced to Boolean [here](https://github.com/wix/wix-style-react/blob/master/src/Input/Input.driver.js#L93).

### 👣 Steps to Reproduce

1. Create a component which uses any of the following: `Input`, `InputWithOptions`, `Search`.
2. Set input to loading state by passing `status="loading"` prop. 
3. Create an Enzyme test for your component.
4. `const inputDriver = inputTestkitFactory({ wrapper: /** your component **/, hook: /** your data-hook **/ }); 
...
expect(inputDriver.hasLoader()).toBe(true);`
5. Test fails.

  - **WSR version**: `6.58.0`
  - **Yoshi version**: `4.25.3`

### 👀 Severity
- Low

**Comment by shlomitc** [comment]
This has been changed in WSR v8. `hasLoader()` was dropped in favor of `hasStatus()` which returns a boolean value as expected. v6 is no longer maintained for new features or bug fixes, so I recommend upgrading to the latest version.

thanks
