### ISSUE TITLE
`keyDown` method from Input TestKit API doesn't work as expected

### ISSUE THREAD

**Issue by iamjager** [wix/wix-style-react#4871]
# 🐛 Bug Report

### 🏗 Relevant Components
`Input`, `InputWithOptions`, `Search`

### 😯 Current Behavior
`inputTestkitFactory({...}).keyDown('Enter')` doesn't trigger `onEnterPressed` prop function.

### 🤔 Expected Behavior
`inputTestkitFactory({...}).keyDown('Enter')` should trigger `onEnterPressed` prop function.

The issue seems to be that we check for `keyCode` property when handling `keyDown` event in `Input` [here](https://github.com/wix/wix-style-react/blob/master/src/Input/Input.js#L337). However, we do not have ability to pass `keyCode` param in `inputDriver` [here](https://github.com/wix/wix-style-react/blob/master/src/Input/Input.driver.js#L35), only `key` (e.g., 'Enter'). There are couple ways how we can fix it:

- create a separate method for pressing enter in `inputDriver` (e.g., `pressEnter`);
- add ability to pass `keyCode` param to `keyDown` method in `inputDriver`;
- generate `keyCode` based on `key` (e.g., `'Enter'` -> `13`) inside `keyDown` method in `inputDriver`;
- check for `key` instead of `keyCode` when handling `keyDown` in `Input` component.

### 👣 Steps to Reproduce

1. Create a component which uses any of the following: `Input`, `InputWithOptions`, `Search`.
2. Add `onEnterPressed` handler to the input.
3. Create an Enzyme test for your component.
`const inputDriver = inputTestkitFactory({ wrapper: /** your component **/, hook: /** your data-hook **/ }); ... await inputDriver.keyDown('Enter'); expect(onEnterPressedSpy).toBeCalled();`
4. Test fails.

  - **WSR version**: `6.58.0`
  - **Yoshi version**: `4.25.3`

### 👀 Severity
- Major

**Comment by EgoziE** [comment]
done
