### ISSUE TITLE
Generator- adding a new component to the cheatsheet & symbolToComponents mapping

### ISSUE THREAD

**Issue by TalZa1810** [wix/wix-style-react#4885]
# ✨ Feature Request

### 🔦 Scope
Generating a new component will add placeholders in the `Cheatsheet` files && `Symbol => Components` mapping. 

### 💁 Explanation
Currently, when generating a new component, we need to remember to add the new component manually to the `Cheatsheet` & `Symbol => Components` mapping. 

The current solution is using the [Cheatsheet contribution guidlines](https://github.com/wix/wix-style-react/blob/master/docs/contribution/CHEATSHEET_GUIDLINES.md) .

### 🐾 Possible solution 
Adding placeholders at the relevant files will help us and contributors when needed to add the new component to the Cheatsheet.

This way, we will make sure that the Cheatsheet is aligned with our components inventory. 

### 👀 Severity
-  Major

**Comment by TalZa1810** [comment]
![Cheatsheet generator](https://user-images.githubusercontent.com/24567980/72680036-d1203400-3abd-11ea-90c5-25b94b0ceac3.png)

Hey @shlomitc ,
I've tried to define the process of adding a component to the Cheatsheet by creating a flowchart of the process. It will help me to split it to subtasks to the generator. 
I would love to hear feedback about the process.



Thanks!

**Comment by shlomitc** [comment]
Hey, it's a cool idea, but I think it mixes two concerns.
1 - what should be in the cheatsheet (the right side - consult UX)
2 - how to add something to the cheatsheet (the left side - "symbols", "InputFamily", etc...)

If you want to document a process, I would focus on the first one ("what should be in...") and remove the second part ("how to add...") as it's already described in the contribution guide you wrote.

In general, I think the generator should be very very very simple. Don't try to solve all the conditions. Instead, every new component would go under "Not classified" family or something similar

**Comment by EgoziE** [comment]
Moved to Jira - closing
