### ISSUE TITLE
< FormField/> - Long Formfield breaks

### ISSUE THREAD

**Issue by bbenjjamiin** [wix/wix-style-react#4899]
#4699 🐛 Bug Report
When using a Formfield with a Toggle and adding a very long label to the Formfield, the entire text get pushed down below the Toggle

### 🏗 Relevant Components

Toggle Swith
FormField

### 😯 Current Behavior

When using a Formfield with a Toggle and adding a very long label to the Formfield, the entire text get pushed down below the Toggle

### 🤔 Expected Behavior

We expect the Formfield label to stay aligned with the Toggle Switch pin to top.

### 👣 Steps to Reproduce

```
import React from 'react';
import FormField from 'wix-style-react/FormField';
import ToggleSwitch from 'wix-style-react/ToggleSwitch';
class ControlledToggleSwitch extends React.Component {
  state = {
    checked: false,
  };
  render() {
    const { checked } = this.state;
    return (
      <Layout>
      <Cell span="3">
      <FormField
        id="formfieldToggleSwitchId"
        label="Super long label on my toggle that get below the component"
        labelPlacement="right"
        stretchContent={false}
      >
        <ToggleSwitch
          id="formfieldToggleSwitchId"
          checked={checked}
          onChange={e => this.setState({ checked: e.target.checked })}
        />
      </FormField>
    </Cell>
  </Layout>
    );
  }
}
```

### 👀 Severity

Major (breaks our design in many translation)

**Comment by EgoziE** [comment]
fixed
