### ISSUE TITLE
Linting warning when providing props style

### ISSUE THREAD

**Issue by lbelinsk** [wix/wix-style-react#49]
For someone who works with the new stack, when I want to change the button's color, it triggers a lint warning.

<img width="1005" alt="screen shot 2016-12-10 at 10 11 34 pm" src="https://cloud.githubusercontent.com/assets/18248989/21075865/a7561462-bf25-11e6-867b-db8dd8ebe152.png">

**Comment by 3LOK** [comment]
Fixed - 'style' in Button is deprecated and will be removed by Jan 1st. 'theme' should be used instead. Thanks!
