### ISSUE TITLE
<MediaOverlay/> - Middle button is pushed from the middle

### ISSUE THREAD

**Issue by mosheKerbel** [wix/wix-style-react#4907]
When other buttons are defined, the medium button is sometimes pushed and not stays in the middle.
It happens when we go beneath a height of the div.
From what i checked it was `132px` in case of a top button defenetion.

Code for reproduction in playground:
```
<div style={{height: "132px"}}> // remove this height and it will reproduce
<MediaOverlay
    skin="gradient"
    media="https://static.wixstatic.com/media/89ea07a19c3d415e99a8a8a3c0ab1de8.jpg/v1/fill/w_343,h_343,al_c,q_80,usm_0.66_1.00_0.01/89ea07a19c3d415e99a8a8a3c0ab1de8.jpg"
  >
    <MediaOverlay.Content placement="top-end" visible="always">
      <Text size="small" light>
        <Button>Test</Button>
      </Text>
    </MediaOverlay.Content>
    <MediaOverlay.Content placement="middle" visible="always">
      <Text size="small" light>
        <Button>Test</Button>
      </Text>
    </MediaOverlay.Content>
  </MediaOverlay>
</div>
```

@simast

**Comment by simast** [comment]
Just to clarify this issue further: the user added `<IconButton size="tiny">` to top-right and `<Button>` to the middle content. According to our Zeplin specs there are two cases for minimum height:

1. Components that use only one content area, min size can be set to no less than 84x84 px. 
2. For components that use both center and corner content areas, min size should be no less than 108x108px.

We have the first implemented right now but not the second. Code to reproduce in Playground:

```jsx
<MediaOverlay
  skin="gradient"
  media="https://static.wixstatic.com/media/89ea07a19c3d415e99a8a8a3c0ab1de8.jpg/v1/fill/w_343,h_343,al_c,q_80,usm_0.66_1.00_0.01/89ea07a19c3d415e99a8a8a3c0ab1de8.jpg"
>
  <MediaOverlay.Content placement="top-end" visible="hover">
    <IconButton priority="secondary" skin="inverted" size="tiny">
      <Icons.More />
    </IconButton>
  </MediaOverlay.Content>
  <MediaOverlay.Content placement="middle" visible="hover">
    <Button>Test</Button>
  </MediaOverlay.Content>
</MediaOverlay>
```

**Comment by shlomitc** [comment]
Was this issue raised from actual user report or just something you encountered?

**Comment by simast** [comment]
Raised by user report in #wix-style-react

**Comment by EgoziE** [comment]
Won't be fixed - closing
