### ISSUE TITLE
<Collapse/> - open content is rendered as collapsed

### ISSUE THREAD

**Issue by simast** [wix/wix-style-react#4918]
# 🐛 Bug Report

### 🏗 Relevant Components

`<Collapse/>`

### 😯 Current Behavior

`<Collapse open>` element is rendered as collapsed with height fixed to 0px. See reproduction example below.

### 🤔 Expected Behavior

`<Collapse open>` element should be rendered as expanded.

### 👣 Steps to Reproduce

This issue is visible in Business Manager Dashboard  - the way the cards in the dashboard are loaded is that they have a parent container that is initially set to `display: none` and then later updated to `display: block`. When our `<Collapse open>` component is rendered in a `display: none` container - it will incorrectly pick up a height of 0px (seems to be a bug in `react-collapse` lib). The height is then updated when React element tree is updated (unless there are PureComponents or lifecycle events preventing this). This causes issues in the Dashboard where `<Collapse open>` element is hidden.

This is a minimum code to reproduce this issue (create an empty Yoshi project to run):

```jsx
class Parent extends React.Component {
  // Using componentDidMount just to delay and mimic loading state
  componentDidMount() {
    this.setState({ show: true });
  }
  state = { show: false };
  render() {
    return (
      <div style={{ display: this.state.show ? 'block' : 'none' }}>
        <Child />
      </div>
    );
  }
}

// NOTE the PureComponent - this causes no updates, hence react-collapse
// is not picking changes to display none/block in the parent
class Child extends React.PureComponent {
  render() {
    return (
      <Collapse open>
        This is collapsed content that should be visible.
      </Collapse>
    );
  }
}

ReactDOM.render(<Parent />, document.getElementById('root'));
```

A potential fix would be to upgrade `react-collapse` lib from 4.x to 5.x - as the author suggested in multiple bug reports (https://github.com/nkbt/react-collapse/issues/242 and https://github.com/nkbt/react-collapse/issues/224).

  - **WSR version**: `7.37.1`
  - **Yoshi version**: `4.28.4`

### 👀 Severity

Major

**Comment by EgoziE** [comment]
`react-collapse` was upgraded to latest - closing
Will reopen if someone complains.
