### ISSUE TITLE
<Dropdown withArrow="true" /> arrow misplaced 

### ISSUE THREAD

**Issue by yevhen-kutishchev** [wix/wix-style-react#4919]
# 🐛 Bug Report

### 🏗 Relevant Components

<Dropdown withArrow="true" />

### 😯 Current Behavior

Arrow positioned badly

![image](https://user-images.githubusercontent.com/33424167/72998711-f89d3680-3e06-11ea-8b64-44828f02f9ed.png)

### 🤔 Expected Behavior

Arrow should be on it's place.

### 👣 Steps to Reproduce

Open story book and toggle on `withArrow` toggle.
https://wix-style-react.now.sh/?activeTab=Playground&path=%2Fstory%2Fcomponents-api-components--dropdown

### 👀 Severity

- Major

**Comment by shlomitc** [comment]
@yevhen-kutishchev - can you share the design you're trying to achieve?
@milkyfruit - do we wish to allow applying an arrow for the dropdown select component?

**Comment by yevhen-kutishchev** [comment]
@shlomitc here it is: zpl://screen?sid=5da6f3ff6d736af0e2a09724&pid=5b2b413ed34626cb0de097b1

**Comment by milkyfruit** [comment]
I don't think that this feature gives a value for a dropdown.
Will contact Ilanit to get her opinion and why she designed with it.
