### ISSUE TITLE
Update rc-slider to latest version

### ISSUE THREAD

**Issue by ipanasenko** [wix/wix-style-react#494]
Currently "rc-slider" is two major version behind, I think it should be updated to its latest version.

It will help to get rid of annoying warinings: "Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead."

**Comment by tqmukas** [comment]
https://github.com/react-component/slider/blob/5.3.4/src/Slider.jsx#L539-L573
