### ISSUE TITLE
Popover arrow is not looking good on FF/IE when dark background below the tooltip

### ISSUE THREAD

**Issue by alonbt** [wix/wix-style-react#4953]
# 🐛 Bug Report

### 🏗 Relevant Components

Popover

### 😯 Current Behavior

On FF and IE the arrow seems corrupt
![Screen Shot 2020-02-04 at 17 08 11](https://user-images.githubusercontent.com/846623/73756962-1e183180-4771-11ea-824e-27c3b7dacd8c.png)
![Screen Shot 2020-02-04 at 17 08 57](https://user-images.githubusercontent.com/846623/73756983-23757c00-4771-11ea-9017-d72aa7180431.png)

### 🤔 Expected Behavior

Expect the arrow to look nice and smooth without these black lines
...

### 👣 Steps to Reproduce

1. go to Popover page in WSR in Firefox or Internet Explorer
2. It happens when the background below the tooltip is not white, so change it with devtools to a strong color (red, black, etc) and see that the arrow is not looking well. This also happens when the background is white but in that scenario you can't see the issue

I've investigated it a bit and it occurs probably because of transform: rotateZ(...); - this causes the lines to render improperly

### 👀 Severity

Major

**Comment by EgoziE** [comment]
Maybe it's because a year passed, but I see it looks better now on latest FF.
So I'm closing it, if it becomes urgent someday please notify us in the channel.
