### ISSUE TITLE
<Search /> - Style issues for small expandable search

### ISSUE THREAD

**Issue by tomas-ki** [wix/wix-style-react#4973]
# 🐛 Bug Report

### 🏗 Relevant Components

Search

### 😯 Current Behavior

Small expandable search has 2 issues. 
1. Element is not round: 
![image](https://user-images.githubusercontent.com/22006186/74149390-52c43700-4c10-11ea-94c7-31c7522931f7.png)

2. Clear button is not aligned:
![image](https://user-images.githubusercontent.com/22006186/74149490-8606c600-4c10-11ea-93c9-b387ef2c2169.png)

### 🤔 Expected Behavior
Proper alignment and size

### 👣 Steps to Reproduce
  - **WSR version**: 7.41.0

### 👀 Severity
Major

**Comment by EgoziE** [comment]
I couldn't reproduce it..
But if it still happens after we merge PR https://github.com/wix/wix-style-react/pull/4995
Please contact us in the channel.
