### ISSUE TITLE
<Search /> - Expandable search always expanded when providing 'value'

### ISSUE THREAD

**Issue by tomas-ki** [wix/wix-style-react#4974]
# 🐛 Bug Report
Expandable search is always expanded when providing 'value' prop to component, even if it's null, empty string or undefined.

### 🏗 Relevant Components
Search

### 😯 Current Behavior
Search is initially expanded when providing a falsy value.
Also it's not collapsing if removing the value from outside the search component.

### 🤔 Expected Behavior
Search should be collapsed whenever the value is falsy.

### 👣 Steps to Reproduce
Provide an empty value to search on component mount.
Add value from outside scope and then remove it.

### 👀 Severity
Major

**Comment by EgoziE** [comment]
PR - https://github.com/wix/wix-style-react/pull/4995
