### ISSUE TITLE
<Slider/> - Global styles are overridden

### ISSUE THREAD

**Issue by simast** [wix/wix-style-react#4976]
# 🐛 Bug Report

### 🏗 Relevant Components

`<Slider/>`

### 😯 Current Behavior

Slider does not display correctly in some projects because the global class names are overridden by external styles:

![slider-bug](https://user-images.githubusercontent.com/433527/74221006-bf474080-4cb9-11ea-8411-3b7d1c0194b7.png)

The screenshot above was provided by @drasius

### 🤔 Expected Behavior

Slider is displayed correctly. Ideally we should try not to use global class names or somehow isolate them to wix-style-react scope only.

### 👣 Steps to Reproduce

I am not able to reproduce this myself in production. It seems to happen for some users only (maybe it matters how you navigate to an app in business manager).  Currently it is not clear where the class name `.rc-slider-handle` came from (it is a default style for slider handle from `rc-slider` lib, but it is not clear who imported it since we do not use/import default `rc-slider` styles in wix-style-react ourselves).

We can emulate this in our Storybook by temporarily adding the following stylesheet to `.storybook/preview-head.html` file:

```html
<link
  rel="stylesheet"
  href="https://cdn.jsdelivr.net/npm/rc-slider@8.7.1/assets/index.css"
/>
```

  - **WSR version**: `7.42.0`
  - **Yoshi version**: `4.32.0`

### 👀 Severity

- Major

**Comment by simast** [comment]
I did some experiments with `rc-slider` lib and it seems it supports an undocumented prop `prefixCls` that can be used to change the prefix for global styles. So this would be one way to fix this issue - to provide our own custom class name prefix so we do not conflict with other `rc-slider` users.

**Comment by TalZa1810** [comment]
I've talked to Drąsius and it seems like the issue is not a new one. It happened also with the old `Slider` style for some users from time to time (randomly).

**Comment by drasius** [comment]
@TalZa1810 @shlomitc @simast 
What is status for this one? Are you planning to fix?
This is what I see now. 
![image (10)](https://user-images.githubusercontent.com/46714829/76313116-033f5c80-62dd-11ea-9120-eda7d082ebfc.png)

**Comment by shlomitc** [comment]
@drasius - can you please ask one of your developers to help us reproduce this in your project?
Otherwise, it is really hard to understand what should be the right fix for it

**Comment by drasius** [comment]
@shlomitc Sorry I missed your reply. I have already talked to dev about this, they don't know how to reproduce. I have also talked to @simast from your team, and Simas said he knows where this problem comes from. Btw I still see this slider as a floating egg.
