### ISSUE TITLE
<Grid/> - StretchViewsVertically rows break in production

### ISSUE THREAD

**Issue by BnayaZil** [wix/wix-style-react#4982]
# 🐛 Bug Report

### 🏗 Relevant Components

Row, Col

### 😯 Current Behavior

The stretchViewsVertically row adds to his child cols the following roles: 
![image](https://user-images.githubusercontent.com/13505136/74237749-efeca180-4cdc-11ea-8a49-53faf9c5c356.png)

but in production, this role failed since we have no `col-` in our class because Yoshi generates short hashes for production.

In general, this kind of role is really bad.

### 🤔 Expected Behavior

To work

### 👣 Steps to Reproduce

Just render in production mode a row with stretchViewsVertically and cols.

### 👀 Severity

- Major

**Comment by EgoziE** [comment]
Can you provide a link to the place where it breaks? So we could investigate this better

**Comment by BnayaZil** [comment]
https://www.wix.com/account/account-settings
Experiment: `specs.wos.AccountSettingsReact`.

**Comment by EgoziE** [comment]
PR - https://github.com/wix/wix-style-react/pull/4992
