### ISSUE TITLE
<Avatar> indicationExists(test kit) return always true when showIndicationOnHover is set

### ISSUE THREAD

**Issue by adirou** [wix/wix-style-react#5039]
# 🐛 Bug Report
<Avatar> indicationExists(test kit) return always true when showIndicationOnHover is set but component not hovered.
### 🏗 Relevant Components
<Avatar>

...

### 😯 Current Behavior
<Avatar> indicationExists(test kit) return always true when showIndicationOnHover is set but component not hovered.

...

### 🤔 Expected Behavior
indicationExists should return false when showIndicationOnHover is set but component isn't not hovered

...

### 👣 Steps to Reproduce

  - **WSR version**: `latest`
  - **Yoshi version**: `3`

### 👀 Severity

- Critical / Major / Low
Low

**Comment by EgoziE** [comment]
PR - https://github.com/wix/wix-style-react/pull/5125
