### ISSUE TITLE
<Input /> types are missing inputRef

### ISSUE THREAD

**Issue by OriMarron** [wix/wix-style-react#5083]
# 🐛 Bug Report

`<Input />` types are missing inputRef

### 🏗 Relevant Components
`<Input />`

### 🤔 Expected Behavior
<Input /> accepts a prop name `inputRef` but it is not included in typings

### 👀 Severity

Low

**Comment by OriMarron** [comment]
related to #3583

**Comment by mosheKerbel** [comment]
> # 🐛 Bug Report
> `<Input />` types are missing inputRef
> 
> ### 🏗 Relevant Components
> `<Input />`
> 
> ### 🤔 Expected Behavior
> accepts a prop name `inputRef` but it is not included in typings
> 
> ### 👀 Severity
> Low

hey @OriMarron can you show the use case where you are using inputRef? what is it, why not simply use ref?

**Comment by OriMarron** [comment]
@mosheKerbel 
We *can* simply use ref as an alternative.
But if we do, we want to be able to access `refInstance.input`. 
But `input` is not currently exposed as a public member on the types, so adding it there would be good too.
