### ISSUE TITLE
Popover manually trigger updatePosition

### ISSUE THREAD

**Issue by MSiliunas** [wix/wix-style-react#5118]
# ✨ Feature Request

### 🔦 Scope

Update `<Popover />` API.

### 💁 Explanation

It would be convienient to be able to manually update popover's position. It's needed when content of the popover can change while it is open.
Currently if popover's content change it grows in height downwards not upwards (as it would be expected).

### 🐾 Possible solution 

Expose an API to call position update on Popover. In this case we could trigger position update because we know when the content will change.

### 👀 Severity

- Major

**Comment by EgoziE** [comment]
Sounds like something that should be resolved by UX (or at least come as a request from UX)
If it's still relevant (or urgent) you can start a discussion in slack #wix-style-ux
