### ISSUE TITLE
IE11 Unstable and inconsistent performance for GoogleAddressInput

### ISSUE THREAD

**Issue by alonbt** [wix/wix-style-react#514]
Scenario:

1. You type an address in IE11 in a regular pace (like normal fast typing)
2. Some of the letters will not be typed. for example: If you will type 'San Fransisco' the actual text will be 'Sn Fraisso'

**Comment by nirhart** [comment]
@3LOK do you know anything about it?

**Comment by 3LOK** [comment]
Hi - Sorry, was on vacation. We just tested one of our sites with IE11 (eg. [dixie](www.dixiedelivery.co.il)) and could not recreate issue.

Sounds like a problem with controlled environment being unoptimized.

**Comment by nirhart** [comment]
@alonbt ?
