### ISSUE TITLE
dataHook prop is missing in <HeaderLayout />

### ISSUE THREAD

**Issue by karolinawix** [wix/wix-style-react#5159]
# 🐛 Bug Report
Component: https://github.com/wix/wix-style-react/blob/master/src/MessageBox/FunctionalLayout/HeaderLayout.js

### 👀 Severity

Low

**Comment by EgoziE** [comment]
`<HeaderLayout/>` is an internal component that shouldn't be used.

If you need change in UI, please contact UX.
If you need change in Testkit, please specify what you're trying to test.

I encourage you to write in our channel before opening an issue or PR 😄
