### ISSUE TITLE
Ejected CRA - __webpack_public_path__ is not defined

### ISSUE THREAD

**Issue by opula** [wix/wix-style-react#5181]
# 🐛 Bug Report
I've created a new project using CRA and immediately ejected to use WSR.   The only thing that was added to the original package.json was styleable/core & styleable/webpack-plugin @ 1.4.0.  I also updated the webpack config to mimc the readme.  Right now, the app will not progress beyond this error "ReferenceError: __webpack_public_path__ is not defined"

### 😯 Current Behavior
This is the current output each time the development app is started:

<img width="928" alt="Screen Shot 2020-03-12 at 3 51 05 PM" src="https://user-images.githubusercontent.com/168711/76534105-56e6ad00-6479-11ea-97fa-12fc66702741.png">

### 👣 Steps to Reproduce
npx create-react-app app --template typescript
cd app && yarn run eject
yarn  add wix-style-react @stylable/core@^1.0.0 @stylable/webpack-plugin@^1.0.0

In App.tsx:
import Button from 'wix-style-react/Button'

Add button the render function of component

  - **WSR version**: 7.49.0
 - **@stylable/core*: 1.4.0
 - **@stylable/webpack-plugin*: 1.4.0

**Comment by mykas** [comment]
Hey, can you share your webpack config?

**Comment by opula** [comment]
Sure.  Here is a gist: https://gist.github.com/opula/44d2c7ba49ae80c8c5192cfaa9ade3a2.

I managed to get it working properly from a minimalistic webpack starter kit.  So I'm guessing there is a conflict or something.  I played with the posted webpack in a couple of ways but didn't manage to get past this point.

**Comment by mykas** [comment]
So this `webpack_public_path` is important parameter for dynamic chunks to be loaded. I though that CRA solved this somehow, but it seems that you might need to specify it in webpack just like explained here: https://webpack.js.org/guides/public-path/

**Comment by mykas** [comment]
Oh its already defined: https://gist.github.com/opula/44d2c7ba49ae80c8c5192cfaa9ade3a2#file-webpack-config-js-L180 🤔

**Comment by mykas** [comment]
oh, that seems related to this: https://github.com/webpack/webpack/issues/2776#issuecomment-233808146

**Comment by opula** [comment]
Hrm, I just tried their solution and its the same result.  It's strange that minimalistic webpack config would be fine.  I'll try to root out the difference between the two to see if I can pinpoint the problem.

**Comment by mykas** [comment]
ok, thanks. Please write here again if you see any solution to this :)

**Comment by tozaicevas** [comment]
Facing same issue with JS CRA-ejected project.

**Comment by tozaicevas** [comment]
@opula It worked with this config https://github.com/RazLandau/test-wix-ui/blob/master/config/webpack.config.js + adding those lines in node_modules/wix-style-react/dist/es/src/Carousel/Carousel.global.scss (as described in https://chunkbytes.com/2019/10/how-to-use-slick-to-create-a-carousel/ )
```
$slick-font-path: "~slick-carousel/slick/fonts/";
$slick-loader-path: "~slick-carousel/slick/";
```
However, some components are not rendered correctly (e.g. Calendar, Card)

**Comment by EgoziE** [comment]
@opula & @tozaicevas  Please try this guide I wrote (and leave comments if needed)
#5545

I just want to say this wasn't easy and there are some specific rules you have to follow.
I hope that in the future wix-style-react will work perfectly with CRA.
For now, this is the best I could do :)

**Comment by tozaicevas** [comment]
> @opula & @tozaicevas Please try this guide I wrote (and leave comments if needed)
> #5545
> 
> I just want to say this wasn't easy and there are some specific rules you have to follow.
> I hope that in the future wix-style-react will work perfectly with CRA.
> For now, this is the best I could do :)

Tried it, got it working, great job! :)
