### ISSUE TITLE
Avatar component: expose "src" in driver.

### ISSUE THREAD

**Issue by etaybarzilay89** [wix/wix-style-react#5188]
# ✨ Feature Request

### 🔦 Scope

Avatar component.
...

### 💁 Explanation

- Exposing src attribute in the driver.
- Fixing "isImageLoaded" which always returns false.
- Adding documentation for its testkit.

For many sorts of integration tests (such as changing an avatar, removing one, etc.) we need to be able to get the "src" attribute from the driver (same as we're getting textContent from input driver etc.)

Also, isImageLoaded always returns false unless you do an ugly hack like this one:
`Object.defineProperty((global as any).Image.prototype, 'src', {
    set(src) {
      if (src === TEST_IMG_URL) {
        setTimeout(() => this.onload());
      }
    },
  });
});`

which btw, makes all sorts of related bugs such as that contentType is always "placeholder" unless image is loaded then it becomes "img", etc.
...

### 🐾 Possible solution 

...

### 👀 Severity

In my opinion, it's like having an Input component (of any type) without exposing text (or the different src of the input).

So I guess it's a Major.

**Comment by shlomitc** [comment]
Thanks for raising the issue.
Feel free to contribute to the library the missing testkit methods, we'll be happy to review it.
