### ISSUE TITLE
checkboxTestkitFactory - getLabel

### ISSUE THREAD

**Issue by adimorwix** [wix/wix-style-react#5212]
# 🐛 Bug Report
checkboxTestkitFactory
getLabel() return the all tag
<div data-hook=\"column-name\" class=\"labelOptionContentContainer\"><span class=\"labelOptionName\">ghi</span></div>
and not the text.

### 🏗 Relevant Components
checkbox
..

### 😯 Current Behavior

getLabel() return the tag
...

### 🤔 Expected Behavior
getLabel() return the text

  - **WSR version**: `latest`
  - **Yoshi version**: `...`

### 👀 Severity
Critical - we have failed tests

Thanks
Adi

**Comment by EgoziE** [comment]
Checkbox can receive any react node as children so we decided the return value should be that node.

If you want something specific just add your own data-hook or use other functions of html node
