### ISSUE TITLE
`<FormField />` interface issue

### ISSUE THREAD

**Issue by BnayaZil** [wix/wix-style-react#5265]
# 🐛 Bug Report

### 🏗 Relevant Components
FormField

### 😯 Current Behavior
The prop `infoTooltipProps` expect `PopoverCommonProps` which miss a few options (`onShow` for example).

### 🤔 Expected Behavior
To have the full tooltip props interface.

### 👣 Steps to Reproduce
  - **WSR version**: `7.51.0`

### 👀 Severity
- Low

**Comment by mykas** [comment]
Hey, would you like to contribute it? We have now a common place where we pick only the most logical props to be exposed: https://github.com/wix/wix-style-react/blob/master/src/common.d.ts

`onShow` was missed and it seems that feature is only for Tooltip. It would make sense to split those to `PopvoerCommonProps` and `TooltipCommonProps`.

**Comment by BnayaZil** [comment]
Sorry, I currently have no time for contribution, barely manage to get my own job done.
