### ISSUE TITLE
TableActionCell upgrade enzyme driver is not working

### ISSUE THREAD

**Issue by shalevshalit** [wix/wix-style-react#5288]
# 🐛 Bug Report
when add upgrade TableActionCell the driver factory is not working anymore.
https://github.com/wix/wix-style-react/blob/master/src/TableActionCell/TableActionCell.driver.js#L13
component is there when you use pupperteer/protractor but not with enzyme

### 🏗 Relevant Components

TableActionCell

### 😯 Current Behavior

getting old PopoverMenu driver when use upgrade

### 🤔 Expected Behavior

Getting new PopoverMenu driver

### 👣 Steps to Reproduce

Create a component with TableActionCell and add upgrade prop:
```
<TableActionCell
      upgrade
      dataHook="actions-menu"
      secondaryActions={[{text: 'Action', onClick={console.log}}]}
      alwaysShowSecondaryActions={true}
    />
```
Add a driver
```

import { tableActionCellTestkitFactory } from 'wix-style-react/dist/testkit/enzyme';
...
tableActionCellTestkitFactory({
      wrapper,
      dataHook: 'actions-menu'
    });
```

try use 
```
this.tableActionCellTestkit.clickHiddenAction(0);
```
get Error:
```
TypeError: Cannot read property 'querySelector' of undefined
```

  - **WSR version**: `6.58.0`
  - **Yoshi version**: `4.52.2`

### 👀 Severity

- Major

**Comment by shlomitc** [comment]
@EgoziE can you take a look?
