### ISSUE TITLE
<Dropdown/> - fixedFooter unable to interact with options hide

### ISSUE THREAD

**Issue by mosheKerbel** [wix/wix-style-react#5293]
Legitimate scenario:
FixedFooter includes a button which opens something
You'd expect the dropdown to be closed (hide the options).
User do not have an API to interact with the dropdown to do that.
(he can use a ref on the dropdown and call the existing `hideOptions` but this is not recommended)

Suggestion:
Use render props for fixedFooter to inject a `hideOptions` function that the user will be able to call.

**Comment by EgoziE** [comment]
done
