### ISSUE TITLE
improve docs

### ISSUE THREAD

**Issue by yanivefraim** [wix/wix-style-react#533]
I think we should add to docs how should we import a component. It is not clear...

For example:
https://wix.github.io/wix-style-react/?selectedKind=3.%20Inputs&selectedStory=3.1%20Text%20Field&full=0&down=0&left=1&panelRight=0

**Comment by InYourDreamz** [comment]
Yeah I agree!

**Comment by argshook** [comment]
hello,

not only "how to import component" part is missing in documentation but also a lot more. we understand this and are already working to improve docs a lot.

im closing this issue.

feel free to reopen if you have general documentation issues or better yet, open new issue about specific component. thanks!
