### ISSUE TITLE
TimePicker - wrong component name, should be TimeInput

### ISSUE THREAD

**Issue by audriuss** [wix/wix-style-react#5330]
# Documentation Issue

### 🔦 Scope

Relevant Page URL: https://wix-style-react.now.sh/?path=/story/components-api-components--timepicker

### 💁 Explanation

Component name in the docs is `TimePicker`, but in reality `TimeInput`. So, import `import { TimePicker } from 'wix-style-react';` does not work. 

### Expected Docs 

Changed component name and relevant info

### 👀 Severity

- [X] Major
- [ ] Low

**Comment by shlomitc** [comment]
Do you mind making a small PR fixing it? This would be really helpful
