### ISSUE TITLE
Missing info about installing wsr@8

### ISSUE THREAD

**Issue by rudnitskih** [wix/wix-style-react#5335]
Everything is awesome in [MIGRATION.md](https://github.com/wix/wix-style-react/blob/master/MIGRATION.md) except for one important thing:

There is no mention to do `npm i wix-style-react@8` 😊
I just missed 5 mins, because I did all steps but forgot to install updated lib. 
I don't know the exact place where to mention that, so sorry I didn't create PR.

**Comment by EgoziE** [comment]
Added to migration guide under `Order of migration`
