### ISSUE TITLE
inputDriver.hasStatus('error') throws exception in case status is absent

### ISSUE THREAD

**Issue by rudnitskih** [wix/wix-style-react#5336]
During the migration to WSR@8 I found the issue:

`hasStatus` changed the behavior and in case I want to check if error is absent this method throw exception, not false value.  

![image](https://user-images.githubusercontent.com/8848858/79008162-76025880-7b65-11ea-95c4-bf257c78f2ab.png)

![image](https://user-images.githubusercontent.com/8848858/79007268-7863b300-7b63-11ea-970e-f0ce13dd5f0d.png)

**Comment by EgoziE** [comment]
https://github.com/wix/wix-style-react/pull/5339

**Comment by EgoziE** [comment]
Solved in 8.1.0.
Many thanks!

**Comment by rudnitskih** [comment]
@EgoziE Thank you for such a quick fix!
