### ISSUE TITLE
MultiSelect + listItemSelectBuilder - looks bad in Safari

### ISSUE THREAD

**Issue by zeevgg** [wix/wix-style-react#5340]
# 🐛 Bug Report

### 🏗 Relevant Components

MultiSelect with listItemSelectBuilder 

happens in wsr storybook too:
https://wix-style-react.now.sh/?path=/story/components-api-components--listitemselect
Advanced Example

### 😯 Current Behavior

![image](https://user-images.githubusercontent.com/27914368/79107008-48432c80-7d7c-11ea-915b-0bf9f4edfd15.png)

### 👣 Steps to Reproduce
open safari
  - **WSR version**: `7.55.0`

My project is locked on 7.55.0. I need the fix in ^7. please

### 👀 Severity

- Major

**Comment by EgoziE** [comment]
Could not reproduce on Safari Version 13.1 (15609.1.20.111.8)
Spoke to Zeev, it happens on Version 13.0.4 (14608.4.9.1.4)
@shlomitc Is it serious enough to fix?

**Comment by zeevgg** [comment]
?

**Comment by shlomitc** [comment]
I can't replicate a working v13.0.4 and generally speaking, we focus on Chrome. This might be changed in the future but currently, we can't reach these issues.
@zeevgg - if you can make this browser work on your machine, do you mind making a PR fixing it?

**Comment by zeevgg** [comment]
I will try to make find time for it
