### ISSUE TITLE
React portal of <FloatingHelper /> shifts content of the page up

### ISSUE THREAD

**Issue by olega-wix** [wix/wix-style-react#5344]
# 🐛 Bug Report

### 🏗 Relevant Components

`<FloatingHelper />`

### 😯 Current Behavior

React portal of <FloatingHelper /> has property `display: inline-block` and it shifts content of the page up. In Business Manager it looks like the header is broken.

### 🤔 Expected Behavior

React portal of <FloatingHelper /> does not shift content of the page up.

### 👣 Steps to Reproduce

The issue reproduces in business manager when user opens website dashboard.
Actually it reproduces not on every page, but the issue is present when user opens Store Products or Email Marketing pages.
FloatingHelper is used in New Releases icon in the header. It is displayed only for the first time and will not be displayed once user sees it.

  - **WSR version**: `~7.46.0`
  - **Yoshi version**: `^3.22.4`

### 👀 Severity

- Critical

**Comment by EgoziE** [comment]
Did you try to upgrade react to 7.55.0 which is the latest 7?

**Comment by shlomitc** [comment]
Just upgrade to the latest wix-style-react version and it should work. starting from v7.48.0 we did some change that actually solved this. please re-open if it didn't work
