### ISSUE TITLE
<Text/> - Bad alignment when using <InfoIcon/> component

### ISSUE THREAD

**Issue by rudnitskih** [wix/wix-style-react#5347]
# 🐛 Bug Report

### 🏗 Relevant Components

`<InfoIcon />`

### 😯 Current Behavior

We have a lot of places where we use `<Tooltip />` +  `<InfoCircle/>`. I wanted to simplify it by using the new `<InfoIcon />`. I did everything how mentioned in the [docs](https://wix-style-react.now.sh/?path=/story/components-api-components--infoicon), but the icon is not centered to text and we have the wrong space between text and icon. This is [PR](https://github.com/wix-private/domain-contact-form/pull/19/files)  with my changes and the screenshot how it looks in PR: 

![image](https://user-images.githubusercontent.com/8848858/79215885-f28e8300-7e54-11ea-8e5b-f0911ce5c6fe.png)

### 🤔 Expected Behavior

You can check current alignment and padding on this [page](https://wix-private-domain-contact-form-widget.surge.sh/?path=/story/contact-form-widget--create-empty), before using `<InfoIcon />`:

![image](https://user-images.githubusercontent.com/8848858/79215744-b9eea980-7e54-11ea-90d8-8bb12cba5d7f.png)

I could achieve the required alignment and spacing, but I need to keep some flex wrapper like `s.headerRow`, move `<InfoIcon />` out of the text and keep the additional margin between text and icon. Check this [PR](https://github.com/wix-private/domain-contact-form/pull/20/files) 

I want to eliminate these CSS hacks and use `<InfoIcon />` as mentioned in the docs.

### 👣 Steps to Reproduce

1. `git clone https://github.com/wix-private/domain-contact-form`
2. `git checkout InfoIcon`
3. `cd ./domain-contact-form-widget`
4. `npm i`
5. `npm run start`
6. Open `Create (Empty)` story

Or you can check a simplified example:

The codesandbox [link](https://codesandbox.io/s/jj196orvpv?module=%2Fsrc%2FApp%2Findex.js) contains WSR@5, so I reproduced this case in storybook playground:

```
class MyComponent extends React.Component {
  render() {
    return (
      <Card>
        <Card.Content>
          <Text>Example from docs<InfoIcon content="tooltip"/></Text>
          
          <div style={{display: 'flex', 'aligItems': 'center'}}>
            <Text>Desired behaviour</Text>
            
            <div style={{marginLeft: '2px'}}>
              <InfoIcon content="tooltip"/>
            </div>
          </div>
        </Card.Content>
      </Card>
    );
  }
}
```

  - **WSR version**: `8`
  - **Yoshi version**: not relevant

### 👀 Severity

- Low

**Comment by rudnitskih** [comment]
@EgoziE Hey, do you need the branches which I mentioned in the issue or I can clean them up?

https://github.com/wix-private/domain-contact-form/pull/19
https://github.com/wix-private/domain-contact-form/pull/20

**Comment by EgoziE** [comment]
It's ok you can remove them, we're cleaning up our issues too :)

**Comment by rudnitskih** [comment]
I meant do you need these branches in my repo to understand the issue or is it clear from the description?

**Comment by EgoziE** [comment]
I don't, thanks

**Comment by EgoziE** [comment]
Decided not to fix - closing
