### ISSUE TITLE
<AddItem /> add missing prop "tooltipContent" 

### ISSUE THREAD

**Issue by miroshSa** [wix/wix-style-react#5353]
# 🐛 Bug Report

### 🏗 Relevant Components

<AddItem />

...

### 😯 Current Behavior

prop "tooltipContent" is missing in version 8

...

### 🤔 Expected Behavior

prop "tooltipContent" should exist for this component
...

### 👣 Steps to Reproduce

  - **WSR version**: `8.1.0`
  - **Yoshi version**: `4.56.1`

### 👀 Severity

- Critical

**Comment by EgoziE** [comment]
PR - https://github.com/wix/wix-style-react/pull/5371
