### ISSUE TITLE
<DropdownBase/> - API is rendered twice for some reason. 

### ISSUE THREAD

**Issue by TalZa1810** [wix/wix-style-react#5366]
# Documentation Issue

### 🔦 Scope

Relevant Page URL:  https://wix-style-react.now.sh/?activeTab=API&path=%2Fstory%2Fcomponents-api-components--dropdownbase

### 💁 Explanation

The API is rendered twitch. When commenting the `{ title: 'API', sections: [api()] }`, it does not render this at all.
I tried to play a bit with the `index.story` file and the `propTypes` of the component but couldn't figure out what causes this. Need to investigate this further.

```
    tabs([
      tab({
        title: 'Description',
        sections: [...]
      }),

      ...[
       // { title: 'API', sections: [api()] },
        { title: 'Testkit', sections: [testkit()] },
        { title: 'Playground', sections: [playground()] },
      ].map(tab),
    ]),
```

### Expected Docs
API is rendered once. 

### 👀 Severity

- [ ] Major
- [x] Low

**Comment by EgoziE** [comment]
fixed
