### ISSUE TITLE
Problem with install wix-style-react on react app

### ISSUE THREAD

**Issue by lenoirdevinci** [wix/wix-style-react#5394]
Hello,

When I try to install the wix-style-react on react app, I have a webpack message error. I try to start with a empty react app and have the same issue.
TypeError: _Pagination_st_css__WEBPACK_IMPORTED_MODULE_15___default(...) is not a function
Module../node_modules/wix-style-react/dist/es/src/Pagination/Pagination.js
node_modules/wix-style-react/dist/es/src/Pagination/Pagination.js:29

Can you help me please ?

**Comment by lenoirdevinci** [comment]
{
  "name": "test-wix",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.5.0",
    "@testing-library/user-event": "^7.2.1",
    "node-sass": "^4.13.1",
    "react": "^16.8.3",
    "react-dom": "^16.8.3",
    "react-scripts": "3.4.1",
    "wix-style-react": "^8.3.0"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}

**Comment by EgoziE** [comment]
Are you using Yoshi?
If not, make sure you read our guidelines:
https://wix-style-react.now.sh/?path=/story/introduction-getting-started--usage-without-yoshi

**Comment by lenoirdevinci** [comment]
I am not using Yoshi and I follow the guideline into the webpack configuration. I have no idea where this issue come in from

**Comment by EgoziE** [comment]
I don't see `stylable @stylable/core @stylable/webpack-plugin` (version 1) in your devDependencies

**Comment by lenoirdevinci** [comment]
The same issue after :

{
  "name": "test-wix",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@stylable/core": "^3.4.3",
    "@stylable/webpack-plugin": "^3.4.3",
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.5.0",
    "@testing-library/user-event": "^7.2.1",
    "node-sass": "^4.13.1",
    "react": "^16.8.3",
    "react-dom": "^16.8.3",
    "react-scripts": "3.4.1",
    "wix-style-react": "^8.3.0"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}

**Comment by lenoirdevinci** [comment]
Finally I don't find any solution so I re install with Yoshi.

**Comment by EgoziE** [comment]
@lenoirdevinci Please try this guide I wrote (and leave comments if needed)
https://github.com/wix/wix-style-react/pull/5545

I just want to say this wasn't easy and there are some specific rules you have to follow.
I hope that in the future wix-style-react will work perfectly with CRA.
For now, this is the best I could do :)
