### ISSUE TITLE
<Multiselect/> – Input loses focus when deleting a tag

### ISSUE THREAD

**Issue by b3llash** [wix/wix-style-react#5396]
# 🐛 Bug Report

### 🏗 Relevant Components
`<Multiselect/>`

### 😯 Current Behavior
Input is in focus. When deleting a tag (by clicking on "x"), the tag is removed but the input loses focus.
[GIF](https://i.gyazo.com/8781cffd7059fb4c082a8480b201148b.gif)

In some cases, the dropdown re-opens, which creates an inconsistent state where the input is not in focus but its dropdown is open.
[GIF](https://i.gyazo.com/8df7f755bef41ae2d8d1beb80acc8db2.gif)

### 🤔 Expected Behavior
After a tag is removed, the input should be focused and ready for user input.

### 👣 Steps to Reproduce

  - **WSR version**: `8.2.0`
  - **Yoshi version**: `?` (@Hadar-Grossman ?)

### 👀 Severity
Low

**Comment by EgoziE** [comment]
Moved to Jira - closing
