### ISSUE TITLE
Input should look good without having it's parent supply a "ltr" or "rtl" className

### ISSUE THREAD

**Issue by ronami** [wix/wix-style-react#54]
Trying to use an Input (or almost any other component) without it's parent having a class of ltr/rtl will make it look disfigured.

We should have the correct class when rtl property is being used instead of the user having to state it twice with the class not having any default.

**Comment by 3LOK** [comment]
Just to clarify: the requirement is for the 'body' to contain either 'ltr' or 'rtl', not necessarily the parent.

**Comment by lbelinsk** [comment]
We are doing this better now, don't see the point of leaving this issue, it is too general.
Closing it, if there is any specific component that needs our attention, a new issue can be opened.
