### ISSUE TITLE
Bugs with Edge browser

### ISSUE THREAD

**Issue by lbelinsk** [wix/wix-style-react#541]
- [ ] Buttons are not clickable - 
Account recovery QA reported that 2 Buttons are not clickable in edge browser.

Both of them are implemented with ```<ButtonLayout>``` component with an inner anchor or router Link 

- [x] FilePicker reopens - 
1. Open on any page popup to upload files
2. Select any file, ok
=> popup closes and automatically opens again.
If user tries close popup without selection files - the same behavior: closes and immediately opens again

**Comment by nirhart** [comment]
Which buttons?

**Comment by lbelinsk** [comment]
https://users.wix.com/account-recovery/forgot-email

Try insert matching url + email, get to page where you see done button which isn't ckickable
Also, insert none matching email + url and you will go to a page with "try again" button

**Comment by nirhart** [comment]
The buttons are not related to the library, it works perfectly fine in the storybook
The filepicker fixed

**Comment by lbelinsk** [comment]
It can be also related to buttonLayout..?

**Comment by lbelinsk** [comment]
Just made sure that the button is not clickable in edge browser.
In order to reproduce:

https://users.wix.com/account-recovery/forgot-email

Insert "wix.com" and any email you like, get to the following page:

![image](https://user-images.githubusercontent.com/18248989/27879597-dfc5bc6a-61ca-11e7-9b4a-cf1934812a9e.png)

Try again button is not clickable!

This is a straight forward implementation. I perform basic usage of ButtonLayout! Nothing special here..

**Comment by lbelinsk** [comment]
A new problem is reported. see: https://jira.wixpress.com/browse/USERS-318

**Comment by shlomitc** [comment]
old issue, closing
