### ISSUE TITLE
user avatars are not laoding. GET Gravatar returns 404

### ISSUE THREAD

**Issue by illiaChe** [wix/wix-style-react#5414]
The best example is Team member user, which has not loaded avatars in tons of places.
For example
User:
iliteamowner@test.com - f3f0d5d0-1f3b-4f78-b635-5f6feee6f7bf with experiment

Steps to reproduce:
1. Navigate to https://www.wix.com/account/domains with experiment specs.premium.NewMyDomainsPage_PREM_3633 set to true
2. Click on "teammates" on assigned to site domain
3. See lits of users (teammates) with not loaded avatars.
4. See that in top right corner, where user account is, avatar is not loaded as well
5. In console it looks like:
_Request URL: https://gravatar.com/avatar/38a7df9de9a8a24a7745edb6fa75a56?d=404
Request Method: GET
Status Code: 404_

![Screen Shot 2020-04-27 at 11 54 41](https://user-images.githubusercontent.com/8238303/80354636-a9d8c000-887f-11ea-8aad-725a45c3aa68.png)

**Expected result:**
User's default avatars should load, like it is loading now for user igortestenko@gmail.com on firefox, **for example:**
<img width="1675" alt="Screen Shot 2020-04-27 at 12 10 18" src="https://user-images.githubusercontent.com/8238303/80354966-1ce23680-8880-11ea-9833-8c90587569f2.png">

**Comment by sidoruk-sv** [comment]
Related code:
https://github.com/wix-private/my-domains/blob/master/src/app/components/%40pages/Main/%40shared/AssignedToSiteDomains/SitePreviewHeader/TeammatesPopover/TeammatesPopover.tsx#L107

Related data from server:
![image](https://user-images.githubusercontent.com/439289/80355457-cf19fe00-8880-11ea-824b-d012cebf864d.png)

**Comment by shlomitc** [comment]
Are you sure you get 404 for these images?
This code works as expected, and shows the fallback placeholder
```jsx
<Avatar
  imgProps={{ src: 'https://gravatar.com/avatar/38a7df9de9a8a24a7745edb6fa75a56?d=404' }}
/>;
```

I think that in the case you're showing - the images returning from the Avatar service are transparent and not returning a 404.

**Comment by illiaChe** [comment]
Thats what I see in console, and I am not the only one who is not seeing them

![Screen Shot 2020-04-27 at 12 27 15](https://user-images.githubusercontent.com/8238303/80356749-9418ca00-8882-11ea-935a-7dadf36c126e.png)

![Screen Shot 2020-04-27 at 12 27 52](https://user-images.githubusercontent.com/8238303/80356737-8fecac80-8882-11ea-9a6d-55a9619c7af9.png)

**Comment by shlomitc** [comment]
exactly as I said.
See that the links below have `?d=blank` - this is Gravatar's API to decide to have a fallback blank image.
If you change the URLs to `?d=404`, you will get the expected behavior

**Comment by sidoruk-sv** [comment]
@shlomitc interesting, and there are 200 actually:
![image](https://user-images.githubusercontent.com/439289/80358117-9aa84100-8884-11ea-8e63-2b0d2af38be0.png)
