### ISSUE TITLE
<Tooltip/> - increases bundle size significantly

### ISSUE THREAD

**Issue by rudnitskih** [wix/wix-style-react#5434]
# ✨ Feature Request

### 🔦 Scope

`<Tooltip />`

### 💁 Explanation

Want just let you know: I have created the simplest possible app which has two components `<InfoCircle />` and `<Tooltip/>`. 

![image](https://user-images.githubusercontent.com/8848858/80958606-fd15ba00-8e0d-11ea-9fef-f20bae68bbc8.png)

And the final amount of not gzipped code is 140 Kb and I see so strange dependencies:

![image](https://user-images.githubusercontent.com/8848858/80958762-2fbfb280-8e0e-11ea-8d63-9a7c97c30d2e.png)

I have created a repo where you can reproduce it: https://github.com/wix-a/wsr-tooltip-size
Again I just created the issue to let you know. Thank you!

This was reproduced with `wsr@8.6.1`.

### 👀 Severity
- Low

**Comment by mykas** [comment]
Oh yes, we know. Read more about this here: https://github.com/wix/wix-style-react/issues/4847

**Comment by EgoziE** [comment]
Moved to Jira - closing
