### ISSUE TITLE
stylable not working with css-loader

### ISSUE THREAD

**Issue by bilalesi** [wix/wix-style-react#5435]
i created new project with CRA and the needed configuration to webpack.config.js
but there is one thing that confuse me;
first , when i add exclution of .st.css to the rules array 
`exclude: /\.st.css$/,`
the project work properly except the styling of some component not applied 

![1](https://user-images.githubusercontent.com/2632473/81047130-aab8b580-8e6e-11ea-9455-455de53eee28.PNG)
![2](https://user-images.githubusercontent.com/2632473/81047134-ae4c3c80-8e6e-11ea-80c7-7560f99870f1.PNG)

and when i remove the exclution the project not loading at all due to this errors , 
![3](https://user-images.githubusercontent.com/2632473/81047303-ff5c3080-8e6e-11ea-81fb-f7e6a2a87f31.PNG)

![4](https://user-images.githubusercontent.com/2632473/81047338-169b1e00-8e6f-11ea-84b7-7ee716c36dbc.PNG)

i think the stylable format (.st.css) not working with css-loader and it's necessary to run both
in the same project coz the wix-style-react need them
am i right?? and what the possible solution of this problem?????

**Comment by EgoziE** [comment]
I know you're frustrated, I'm trying to handle it myself.
Let me share with you what is planned for the next couple of months:
1. Migration to Stylable 3 (latest)
2. Removing scss completely
3. Full integration with the latest CRA + tests

Just be patient, we're working on it I can promise!

**Comment by bilalesi** [comment]
Thank you for the update
I am waiting for it

**Comment by ivanji** [comment]
This is one of the nicest ui frameworks I've seen but the lack of proper documentation about how to make it work with Webpack which is the default bundler for most react projects (CRA, NextJS, etc) means that a lot of us have issues adopting it. I really hope you guys at least update your documentation in the mean time. Thanks.

**Comment by EgoziE** [comment]
Take a look at this PR - https://github.com/wix/wix-style-react/pull/5528

Once it's merged (this week), the first (and hardest) step mentioned in my previous comment will be done!

**Comment by ivanji** [comment]
Thanks. Sounds promising - seems like progress (although I'm not sure how upgrading Stylable would make it easier to work with Webpack). I'm sure updates to this file here: docs/usage-without-yoshi.md would provide more clarity.

**Comment by ivanji** [comment]
@bilalesi would you be able to share your webpack config?

**Comment by EgoziE** [comment]
Yes, I have a task updating this section.
I'll get to it after the first step.

**Comment by ivanji** [comment]
@EgoziE and for anyone else looking for a solution, you might want to check out https://github.com/wix/stylable/issues/1212 - thanks to the Stylable guys we finally have a working solution. Not optimal just jet but at least works.

**Comment by EgoziE** [comment]
@ivanji I'm glad to hear you finally made it! 🥳 
Unfortunately due to our current struggle with this issue, we decided to postpone it to the first week of August when wsr9 is out officially with Stylable 3 🌵

**Comment by EgoziE** [comment]
Please read our new Usage with [Create Stylable App](https://github.com/wix/wix-style-react/blob/readme/docs/usage/usage-with-create-stylable-app.md) guide.

If the problem persists let us know.
