### ISSUE TITLE
When <Dropdown /> is inside <Popover />, it does not close on click outside

### ISSUE THREAD

**Issue by audriuss** [wix/wix-style-react#5453]
# 🐛 Bug Report

### 🏗 Relevant Components
<Dropdown />
<Popover />

### 😯 Current Behavior

When `<Dropdown />` is placed inside `<Popover />` it does not close when clicked outside, but inside popover content. 

### 🤔 Expected Behavior

Should close dropdown on all cases when clicked outside dropdown

### 👣 Steps to Reproduce

Copy -> paste this to a storybook:
```
<div
  style={{
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    width: '400px',
    height: '150px',
    background: 'rgba(240, 244, 247, 1)',
    overflow: 'scroll',
  }}
>
<Popover shown>
<Popover.Element>
<IconButton>
</IconButton>
</Popover.Element>
<Popover.Content>
<div style={{padding: '60px' }}>
<Dropdown
    popoverProps={{ appendTo: 'window' }}
    options={[
      { id: 0, value: 'Option 1' },
      { id: 1, value: 'Option 2' },
    ]}
    placeholder="Select an option"
  />

</div>
</Popover.Content>
</Popover>
</div>
```

1) Click on dropdown to open it
2) Try to close it  by clicking it outside, but inside popover

  - **WSR version**: `8.7.0`
  - **Yoshi version**: `4.1.0`

### 👀 Severity
-  Low

**Comment by EgoziE** [comment]
Thanks @audriuss for opening this issue.
PR - https://github.com/wix/wix-style-react/pull/5456

**Comment by audriuss** [comment]
Thanks for the fix!
