### ISSUE TITLE
Change Css property

### ISSUE THREAD

**Issue by lenoirdevinci** [wix/wix-style-react#5455]
Hello,
Into a dashboard build with wix-style-react, I want to have a scrollbar but when I inspect the source page I can see :
```
{
    overflow: hidden;
}
```
applicated to the body. I don't how to manage to change it. I have look into the **/dist/statics/app.css** but no success. Someone can help me please ?

**Comment by EgoziE** [comment]
Which component are you using?
Can you share this dashboard design?

**Comment by lenoirdevinci** [comment]
Hello,
I am using **sidebar** and **page** into the left content.
But I found the problem. I forgot an old code in a useeffect which alternated the body to the closing of the sidebar
```
useEffect(() => {
    setIsSidebarOpen(!isSidebarHidden)
        document.body.style.overflow = 'auto';
        if (isSidebarOpen) {
            document.body.style.overflow = 'hidden';
        }
  }, [isSidebarHidden]);
```
