### ISSUE TITLE
<FontUpgrade /> does not affect <Popover.Content /> (when appendTo="window")

### ISSUE THREAD

**Issue by yevhen-kutishchev** [wix/wix-style-react#5466]
# 🐛 Bug Report

<FontUpgrade /> does not affect <Popover.Content /> (when appendTo="window").
To workaround this problem in Photo Studio project I have created wrapper for Popover component which wraps Popover.Content into FontUpgrade:
https://github.com/wix-private/media-studio/pull/871/files#diff-9baf8ac04fbd2711416aae80720e2e8eR1
I believe WSR a better place for this sort of fix.

### 🏗 Relevant Components

Popover.Content, FontUpgrade

### 😯 Current Behavior

Wrapping root component into <FontUpgrade /> will not change font inside <Popover.Content />.

### 🤔 Expected Behavior

...it should change font.

### 👣 Steps to Reproduce

  - **WSR version**: `8.9.0`

### 👀 Severity

- Major

**Comment by EgoziE** [comment]
Needs to be changed in wix-ui-core

**Comment by EgoziE** [comment]
PR - https://github.com/wix/wix-style-react/pull/5479
