### ISSUE TITLE
<DatePicker> - Does not start from the locale first day of week / does not allow to set first day of week

### ISSUE THREAD

**Issue by alexandraseri** [wix/wix-style-react#5477]
# 🐛 Bug Report

### 🏗 Relevant Components

DatePicker

...

### 😯 Current Behavior

When setting 'locale' prop of DatePicker, when locale first day of the week is Sunday, the date picker still starts week from Monday.

...

### 🤔 Expected Behavior

I would have expected the first day of the week to be according to the locale. Or maybe allow setting the first day of the week by demand. 

...

### 👣 Steps to Reproduce
`moment().locale('en').localeData().firstDayOfWeek(); // Results in 0 === Sunday
`
`<DatePicker locale="en"/>`

  - **WSR version**: 8.9.0
  - **Yoshi version**: 4.74.0

### 👀 Severity
 Low

**Comment by alexandraseri** [comment]
I understand that maybe we don't want to use `moment().locale('en').localeData().firstDayOfWeek();` because we don't want to be dependent on moment. So maybe just api for changing first day of the week?

**Comment by milkyfruit** [comment]
@alexandraseri our date picker is based on this lib: https://react-day-picker.js.org/docs/localization/
It could be fixed by exposing `firstDayOfWeek` prop. Let me know if you would be willing to contribute.

**Comment by alexandraseri** [comment]
@milkyfruit  Sure thing, I'm opening a PR. Can you review?

**Comment by EgoziE** [comment]
Moved to Jira - closing
