### ISSUE TITLE
[PageHeader] - How can I change the size of the title

### ISSUE THREAD

**Issue by lenoirdevinci** [wix/wix-style-react#5490]
Hello,

I try to change the size of title of the PageHeader.
Can someone can explain me how to do it please ?

**Comment by EgoziE** [comment]
Hey Leonir,
wix-style-react follows an internal wix-style design, so most components have specific sizes, colors, fonts, etc.

Luckily in this case, PageHeader can receive a function, so you can render anything there.
for example:
```
<Page.Header
  title={() => <Heading appearance="H4">My custom header</Heading>}
/>
```
