### ISSUE TITLE
<DatePicker> - calendar abbreviations for days of the week are incorrect in Portuguese

### ISSUE THREAD

**Issue by wailanak** [wix/wix-style-react#5504]
# 🐛 Bug Report

### 🏗 Relevant Components

WSR Calendar

### 😯 Current Behavior

Portuguese calendar : abbreviations for the days of the week are two letters. This doesn't make sense in Portuguese. 

![image (8)](https://user-images.githubusercontent.com/60387827/83254004-a99d4e80-a1b6-11ea-9ded-cdd70f3307d5.png)

### 🤔 Expected Behavior

Portuguese needs to abbreviate days of the week with 3 letters. 
In the calendar should be "Seg, Ter, Qua, Qui, Sex, Sáb, Dom" 

The abbreviations appear correctly here: 
https://github.com/date-fns/date-fns/blob/master/src/locale/pt/_lib/localize/index.js

But this doesn't show up in live.

### 👀 Severity

- Major

@milkyfruit

**Comment by EgoziE** [comment]
Moved to Jira - closing
