### ISSUE TITLE
<BarChart /> label not vertically aligned

### ISSUE THREAD

**Issue by MSiliunas** [wix/wix-style-react#5511]
# 🐛 Bug Report

### 🏗 Relevant Components

`<BarChart />`
`<Heading />`

### 😯 Current Behavior

![image](https://user-images.githubusercontent.com/6944305/83518793-94d8f780-a4e3-11ea-8a20-408713b6e194.png)

### 🤔 Expected Behavior

I expect that the label would be centered vertically.

### 👣 Steps to Reproduce

I don't have exact steps to reproduce, only happens in production. I've found out that BarChart's style `margin: auto` lacks specificity as it gets overriden by Heading's margin (see attached screenshot).
You can see the issue in Wix Email Marketing statistics.

  - **WSR version**: `8.13.1`
  - **Yoshi version**: `4.84.0`

### 👀 Severity

- Critical

**Comment by MSiliunas** [comment]
@mykas is familiar with the problem, had a few words with him beforehand :)

**Comment by drasius** [comment]
@mykas @EgoziE @milkyfruit 
Hi, what is the status of this one? It looks really bad and we face it in production, can you please prioritize this bug?

**Comment by EgoziE** [comment]
@drasius Thanks for your concern, we prioritized it as "low" so there's no update currently.
Due to thunderbolt effort we have very limited capacity.
Would you like to contribute this fix?
