### ISSUE TITLE
<Table/> - showLastRowDivider prop is broken

### ISSUE THREAD

**Issue by yambtz** [wix/wix-style-react#5538]
# 🐛 Bug Report

### 🏗 Relevant Components

<Table />

...

### 😯 Current Behavior

showLastRowDivider prop has 3 issues I found:
- default is true, even though documentation says otherwise
- works exactly opposite to its name, last row divider is shown when false and hidden when true
- when divider is hidden (prop at true) a barely noticeable divider is added on top of the last row.

...

### 🤔 Expected Behavior

- doc should reflect actual
- should be shown when show=true
- no divider added to top of row when hidden

...

### 👣 Steps to Reproduce
with showLastRowDivider set to TRUE
![image](https://user-images.githubusercontent.com/39235253/84347433-308cf680-abbb-11ea-83ba-53791579698c.png)

with showLastRowDivider set to FALSE:
![image](https://user-images.githubusercontent.com/39235253/84347483-603bfe80-abbb-11ea-838b-7f7aeeb57ccd.png)

  - **WSR version**: `...`
	8.16.0
  - **Yoshi version**: `...`
	4.86.0

### 👀 Severity

- Critical / Major / Low

**Comment by EgoziE** [comment]
Moved to Jira - closing
