### ISSUE TITLE
Storybook documentation

### ISSUE THREAD

**Issue by lbelinsk** [wix/wix-style-react#554]
The storybook "getting started" page has the following link:

![image](https://user-images.githubusercontent.com/18248989/27356040-bf2ac132-5615-11e7-83d3-3b410a9813ec.png)

When i click it I get redirected to the current page.
I don't even know what to expect to get, so maybe this line should be erased?

@nirhart

**Comment by nirhart** [comment]
The storybook presenting the README.md file of github, and there its perfectly fine to have it
