### ISSUE TITLE
Bug in Japanese typing for Google Address Input

### ISSUE THREAD

**Issue by YuriyFedorov** [wix/wix-style-react#555]
Problem is that in Japanese, we type the address and need to press Space, and Enter in order to chose Kanji (Chinese Letter). 
Then, the moment you press enter, the typing cursor is out of the entry field and you need to click on it again to continue typing. And we can not complete the entire home address.

Debug:
1) Set keyboard to "Hiragana" (Japanese)
2) Type Below;
Kumamotoken> Space, Enter > Kumamotoshi> Space, Enter> Higashiku> Space, Enter> Enokimachi> Space, Enter> 23-26
You will be rejected to type "23-26"
If you need to show to the Developers, just feel free to contact me Takanori Kawaharada
I will come to Debug in Japanese.

Thanks!
Taka & Kazu

**Comment by Takawix** [comment]
Hi,
Any progress on this matter?
You can see Wix Event and there home address works properly.

**Comment by lbelinsk** [comment]
Hey, just want to make sure that this issue is still relevant?
What is the priority of this issue?
Where is this component being used?

**Comment by Takawix** [comment]
Hi Lior
It seems like there has been some change and it seems working. I will ask Kazu / Marketing Writer to review it as well. 
This is the JIRA. https://jira.wixpress.com/browse/WOS-2477

**Comment by kazu-wix** [comment]
@YuriyFedorov I still see the issue. Please don't close this yet. I attached the screen capture video to this JIRA. https://jira.wixpress.com/browse/WOS-2477
