### ISSUE TITLE
Clear button is not working in Search component

### ISSUE THREAD

**Issue by DanielEliraz** [wix/wix-style-react#5567]
# 🐛 Bug Report

### 🏗 Relevant Components

Search

...

### 😯 Current Behavior

Clicking on clear button isn't clearing the search value

...

### 🤔 Expected Behavior

Clicking on clear button should clear the search value

...

### 👣 Steps to Reproduce

Go to [Search docs](https://wix-style-react.now.sh/?path=/story/components-api-components--search) and click on clear button

  - **WSR version**: `8.20.0`
  - **Yoshi version**: `...`

### 👀 Severity

Major

**Comment by sivanharel** [comment]
This issue was fixed and will be part of the next version.
PR: https://github.com/wix/wix-style-react/pull/5576
