### ISSUE TITLE
<RichTextInputArea/> - new prop minHeight/height

### ISSUE THREAD

**Issue by medasiaudvytyte** [wix/wix-style-react#5580]
# ✨ Feature Request

### 🔦 Scope
richTextInputArea
...

### 💁 Explanation
It is allowed to set maxHeight to richTextInputArea but not minHeight. Some designs require richTextInputArea to be bigger than the default.

...

### 🐾 Possible solution 
...

### 👀 Severity
I suppose it is low

**Comment by milkyfruit** [comment]
Yup, this request is valid and also needed by [People team](https://wix.slack.com/archives/CR7P4A1UP/p1593161486001300).

**Comment by EgoziE** [comment]
Developed - https://github.com/wix/wix-style-react/pull/5869
