### ISSUE TITLE
Add scroll listener to Page component

### ISSUE THREAD

**Issue by hitpopdimestop** [wix/wix-style-react#5596]
# ✨ Feature Request

### 🔦 Scope
`<Page />`
...

### 💁 Explanation
Right now it is pretty hard to track scroll events on a Page component, you have to make pretty ugly workarounds. What would be nice to have is these optional properties on a Page component:

`onPageScroll: ({top, bottom, left, right, reachedTop, reachedBottom, reachedLeft, reachedRight}) => {...}, // event returns offsets for all of the sides of the viewport and booleans representing if some of the edges are reached`

`scrollDebounce: 200 // we are able to set the debounce for the scroll event in ms`

`bypassDebounceOnEndReach: true // if we would like to receive onPageScroll event immediately when the user scrolls to one of the edges of the page`
...

### 🐾 Possible solution 
Listening to the event in an app that uses WSR is possible by adding event listener to this element

`const scrollableContent = document.querySelector(
      '[data-hook="page-scrollable-content"]',
    );`

in WSR it is possible to add a ref to that element as well as an onScroll event listener
...

### 👀 Severity

-  Low

**Comment by lironch** [comment]
@hitpopdimestop 
Thank you for the submitting this Feature Request.
In case you manage to find some time to work on it, it will be great if you can reach out to one of our team members for some initial guidance with the api definitions and implementation guidelines.
We have an internal component that can save you most of the work in this use case so it will be a shame if you will write it from scratch.
