### ISSUE TITLE
Mobile Responsiveness

### ISSUE THREAD

**Issue by McZenith** [wix/wix-style-react#5601]
How does Wix-style-react handle mobile responsiveness? Especially for grid and layout. Or how do we render any element based in which screen requested it? I have found any documentation in that at the storybook.

**Comment by shlomitc** [comment]
Currently, all of our components should support a fluid design. you can refer to the mobile web guidelines on how we think it's best to use them: https://github.com/wix/wix-style-react/blob/master/docs/usage/MOBILE_WEB_GUIDELINES.md

**Comment by McZenith** [comment]
Thank you @shlomitc... Cool stuffs in there🎈🎈🎈🙇

@Wix.Engineering rocks🎈🎈😍

**Comment by McZenith** [comment]
It would be great to have this on the documentation website though... I'm closing this🎈🎈🎈

**Comment by shlomitc** [comment]
cc @EgoziE

**Comment by EgoziE** [comment]
Thanks. I created a task for this.

**Comment by McZenith** [comment]
thanks, @EgoziE, and Thanks to @Wix.Engineering for making the library opensource.
