### ISSUE TITLE
<TagList/> - API Suggestion

### ISSUE THREAD

**Issue by shlomitc** [wix/wix-style-react#5627]
# ✨ `<TagList/>` - API Suggestion
![image](https://user-images.githubusercontent.com/6093192/86100073-0a26f080-bac1-11ea-9c0b-0dcdba2af1d7.png)
https://zpl.io/V1KzwqB

I'll be happy to hear if you have any feedback

```jsx
import React from 'react';
import { TagList } from 'wix-style-react';
/**
 * TagList.Tag === <Tag size="small" removable onRemove={() => changeInternalState} ...restOfTheTagsPropsByTheUserListTheme/>
 * TagList.ShowMoreButton - click behavior is set internally
 */
export default () => {
  const [tagsToDisplay, setTagsToDisplay] = React.useState([
    <TagList.Tag theme="danger">Tag 1</TagList.Tag>,
    <TagList.Tag>Tag 2</TagList.Tag>,
    <TagList.Tag>Tag 3</TagList.Tag>,
    <TagList.Tag>Tag 4</TagList.Tag>,
  ]);
  return (
    <TagList size="small" max="6">
      {({ amountOfHiddenTags, areTagsHidden }) => (
        <>
          {tagsToDisplay}
          <TagList.ShowMoreButton
            tooltipProps={{ content: 'Show All Filters' }}
          >
            {areTagsHidden ? `+${amountOfHiddenTags} more` : 'Show Less'}
          </TagList.ShowMoreButton>
          <TagList.Action onClick={setTagsToDisplay([])}>
            Clear All
          </TagList.Action>
        </>
      )}
    </TagList>
  );
};
```

**Comment by lironch** [comment]
Edit: Looking at my own comments i think the main issue i have with this example is that i can't figure if this component will manage for me the amount of displayed `Tag` elements or just render whatever i pass in while trying to inform me about stuff that can help me make a decision. once i'll know the answer to that question i'll be able to provide better feedback and suggestions to your api.

Here are my comments for reference:
* The <TagList /> `max` prop is a bit confusing, i don't know if this is the max amount of `Tag` elements this list can have in general or the max amount it should show before showing the `ShowMoreButton`.
* More on that part, `ShowMoreButton` is always rendered, i think it is safe to say that it shouldn't for 100% of the cases, we need to decide if this is the user responsibility or of the component.
* From your implementation it seems that the component is aware to the amount of `Tag` elements that should end up on the screen, how will it be able to calculate it? will it check the "type" of each child before passing the calculated amount?
* `areTagsHidden` is redundant since the user can just check for `amountOfHiddenTags` > 0.
* I would consider declaring specific props for rendering elements that we want to control like the `ShowMoreButton` & `Action` (maybe even actions...).
* If you expect the user to pass in only the tags to display and not more then you have to notify him when the `ShowMoreButton` button is clicked.

**Comment by shlomitc** [comment]
Thanks for the feedback!

1. What about `maxVisibleTags`? Is that more explicit? The default value should be 3 anyway for a better user experience
2. it appears only if some tags are hidden, but I get your point that it's always rendered **in the same place**, so maybe rendering it as a child is not that great. I do think this should be a feature of the component
3. it will count the children, but I agree that this will require checking if the other types (action and clear) are not there. like the previous bullet - this can be set as a specific entry prop instead of abusing `children`
4. `areTagsHidden` might be redundant, but it can reduce some mistakes by the user, so why not?
5. right, same as 2 and 3.
6. yes, I think we can expose an `onClick` callback for it.

I'll provide another suggestion for the API soon.

**Comment by shlomitc** [comment]
@lironch - Added the revised proposal.
1. I change the compound components to props since we agreed this component structure is well defined and should only be configurable.
2. Both buttons will spread the props to the `Button` component, so their API will be similar.
3. `TagList.Tag` is still compound since it's easier to enrich the `Tag` component with the shared `TagList` props
4. I added `initiallyHiddenTags` and `onTagRemove`. I think adding these two will make the component much more useful

```jsx
import React from 'react';
import { TagList } from 'wix-style-react';
/**
 * TagList.Tag => apply <Tag size="small" removable onRemove={() => props.onTagRemove()} ...restOfTheTagsPropsByTheUserListTheme/>
 * initiallyHiddenTags - since the visible/hidden state is internal, we might want to allow this behavior. default is true
 * onTagRemove - indicates which tag is removed
 */
export default () => {
  const [tags, setTags] = React.useState([
    <TagList.Tag theme="danger">Tag 1</TagList.Tag>,
    <TagList.Tag>Tag 2</TagList.Tag>,
    <TagList.Tag>Tag 3</TagList.Tag>,
    <TagList.Tag>Tag 4</TagList.Tag>,
  ]);
  return (
    <TagList
      size="small"
      maxVisibleTags="6"
      initiallyHiddenTags
      onTagRemove={indexToRemove =>
        setTags(tags.filter((tag, idx) => idx !== indexToRemove))
      }
      tags={tags}
      actionButton={{
        onClick: () => setTags([]),
        label: 'Clear All',
      }}
      showMoreButton={({ amountOfHiddenTags, areTagsHidden }) => ({
        tooltipProps: { content: 'Show All Filters' },
        label: areTagsHidden ? `+${amountOfHiddenTags} More` : 'Show Less',
      })}
    />
  );
};
```

**Comment by dorduch** [comment]
doesn't `onTagRemove` will be handled from the tag itself?
also, `showMoreButton` prop is not very clear since it handles both `expand` and `collapse` actions (for example - the tooltip props only applies for the `expand` action)

**Comment by shlomitc** [comment]
1. `onTagRemove` - each tag component has `onRemove` callback, but instead of manually setting a callback to each, the `TagList` will be responsible to that. I think this will reduce some boilerplate code.
2. so what about `toggleMoreButton? regarding the tooltip, then that could also be conditional base on the `areTagsHidden` data

**Comment by dorduch** [comment]
1. I think this will add more confusion than boilerplate since `<TagList.Tag>` accepts all of `<Tag>` props
2. I agree

**Comment by shlomitc** [comment]
1. we can still make it work by composing the functions and not just overriding. Naiively it will do this:
```jsx
const EnhancedTag = ({onRemove, tagProps}) => <Tag onRemove={() => {parentProps.onRemove(); onRemove();}} ...{tagProps}/>
```
This will still make sure the the original props are called, but also have some assistance to reduce the boilerplate and mistakes

**Comment by shlomitc** [comment]
so here's the last revision
```jsx
import React from 'react';
import { TagList } from 'wix-style-react';
/**
 * TagList.Tag => apply <Tag size="small" removable onRemove={() => props.onTagRemove()} ...restOfTheTagsPropsByTheUserListTheme/>
 * initiallyHiddenTags - since the visible/hidden state is internal, we might want to allow this behavior. default is true
 * onTagRemove - indicates which tag is removed
 */
export default () => {
  const [tags, setTags] = React.useState([
    <TagList.Tag theme="danger">Tag 1</TagList.Tag>,
    <TagList.Tag>Tag 2</TagList.Tag>,
    <TagList.Tag>Tag 3</TagList.Tag>,
    <TagList.Tag>Tag 4</TagList.Tag>,
  ]);
  return (
    <TagList
      size="small"
      maxVisibleTags="6"
      initiallyHiddenTags
      onTagRemove={indexToRemove =>
        setTags(tags.filter((tag, idx) => idx !== indexToRemove))
      }
      tags={tags}
      actionButton={{
        onClick: () => setTags([]),
        label: 'Clear All',
      }}
      toggleMoreButton={({ amountOfHiddenTags, areTagsHidden }) => ({
        tooltipProps: { content: 'Show All Filters' },
        label: areTagsHidden ? `+${amountOfHiddenTags} More` : 'Show Less',
      })}
    />
  );
};
```

**Comment by dorduch** [comment]
I'm still not 100% sure about `onTagRemove` prop, but if it's fine with you it's fine with me :)

**Comment by shlomitc** [comment]
it can be added on a second or third stage, not necessary right now

**Comment by shlomitc** [comment]
Approved
