### ISSUE TITLE
Undefined property

### ISSUE THREAD

**Issue by lenoirdevinci** [wix/wix-style-react#5640]
Hello,
When I try to use WSR, I have an issue.
TypeError: Cannot read property 'placeholder' of undefined
Module../node_modules/wix-style-react/dist/es/src/Avatar/assets.js
node_modules/wix-style-react/dist/es/src/Avatar/assets.js:4

It is look like if it is related to webpack
__webpack_require__
/var/www/my-app/webpack/bootstrap:789
 ```
 786 | };
  787 | 
  788 | // Execute the module function
> 789 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  790 | 
  791 | // Flag the module as loaded
  792 | module.l = true;
```

initially, I just try the start example 
```
import { Button } from 'wix-style-react';

function App() {
  return (
    <div className="App">
      <header className="App-header">
        <img src={logo} className="App-logo" alt="logo" />
        <p>
          Edit <code>src/App.js</code> and save to reload.
        </p>
        <Button>
          Click me!
        </Button>
        
      </header>
    </div>
  );
}

```

**Comment by EgoziE** [comment]
Please read our new Usage with [Create Stylable App](https://github.com/wix/wix-style-react/blob/readme/docs/usage/usage-with-create-stylable-app.md) guide.

If the problem persists let us know.
