### ISSUE TITLE
Tooltip does not disappear by un hovering element if move cursor to tooltip

### ISSUE THREAD

**Issue by CrispusDH** [wix/wix-style-react#5646]
# 🐛 Bug Report

### 🏗 Relevant Components

`<Tooltip/>`

### 😯 Current Behavior

Tooltip does not disappear by un hovering element if move cursor to tooltip.

Hover specific element

![image](https://user-images.githubusercontent.com/12623263/86562022-a55d1180-bf6a-11ea-9e89-3d0d092e00cd.png)

Un hover element, move cursor to tooltip

![image](https://user-images.githubusercontent.com/12623263/86561954-79419080-bf6a-11ea-942b-896281cb8ec2.png)

### 🤔 Expected Behavior

Tooltip disappear when element is not hovering by mouse

### 👀 Severity

- Low

**Comment by EgoziE** [comment]
Moved to Jira - closing

**Comment by CrispusDH** [comment]
could you add Jira ticket, please

**Comment by EgoziE** [comment]
DSM-1481
