### ISSUE TITLE
[TimeTable] Add click doesn't invoke if tooltip visible

### ISSUE THREAD

**Issue by bordi** [wix/wix-style-react#5665]
# 🐛 Bug Report

### 🏗 Relevant Components

`TimeTable` https://www.wix.com/pages/wix-style-react/?activeTab=Playground&path=%2Fstory%2Fcomponents-api-components--timetable

...

### 😯 Current Behavior

Add item callback doesn't invoke when `tooltip` is visible.

...

### 🤔 Expected Behavior

onClick callback is fired even if Tooltip is visible
![image](https://user-images.githubusercontent.com/5034399/87135621-f5a5dd80-c2a2-11ea-847b-3ea34b5c0adb.png)

...

### 👣 Steps to Reproduce

https://www.wix.com/pages/wix-style-react/?activeTab=Playground&path=%2Fstory%2Fcomponents-api-components--timetable

1. Go to Playground of `TimeTable`
2. Hover on a column to get "+ Add" button visible
3. Hover "+ Add" button
4. Get tooltip visible
5. Click on "+ Add" button

  - **WSR version**: 8.28.3
  - **Yoshi version**: 4.114.0

### 👀 Severity

-  Major?

**Comment by EgoziE** [comment]
This bug is related to the component storybook playground page and not related to the component itself.
Therefore I set the severity to low, will be fixed if we get to it.

**Comment by EgoziE** [comment]
opened a relevant ticket in Jira, closing this issue.
