### ISSUE TITLE
<Text/> - Enable size small to tooltip on ellipsis

### ISSUE THREAD

**Issue by gerdasi** [wix/wix-style-react#5668]
# ✨ Feature Request

### 🔦 Scope

When using `<Text />` component with ellipsis (especially when text size is small) there is need to make tooltip smaller and without arrow. 

### 💁 Explanation

`<Text />` component should have such attributes as `size` and `showArrow` or something similar when tooltip is present. When size is small and there is no arrow the tooltip should look something like this:

![Screenshot 2020-07-10 at 14 39 57](https://user-images.githubusercontent.com/54804606/87150716-46c1cb80-c2bb-11ea-97e1-be64812340a1.png)

### 👀 Severity

- Critical

**Comment by Zivilekin** [comment]
This issue is resolved. Example how to set small tooltip:

`<Text ellipsis tooltipProps={{ size:'small' }}>Some text</Text>`
