### ISSUE TITLE
<Badge /> component has wrong styles in storybook

### ISSUE THREAD

**Issue by rudnitskih** [wix/wix-style-react#5683]
# 🐛 Bug Report

### 🏗 Relevant Components

`<Badge />`

### 😯 Current Behavior

The text inside badge has a different color in storybook and production.

#### Storybook behaviour:
![image](https://user-images.githubusercontent.com/8848858/87252333-d8c40280-c47a-11ea-9c69-3591b15f42d2.png)

#### Production behavior:
![image](https://user-images.githubusercontent.com/8848858/87252317-ab775480-c47a-11ea-8856-ef4fe7db192b.png)

### 🤔 Expected Behavior

Styles should be consistent for storybook and production builds

### 👣 Steps to Reproduce

- To see storybook styles open our [storybook](https://my-domains.surge.sh/?path=/story/pages-account-level--default) page
- To see a production impersonates a user with domains, e.g. [dmytror@wix.com](https://bo.wix.com/user-manager/goto-dashboard-as/a7bf8e10-12e8-48a5-b966-d68388dd56a1) and open [Domains](https://www.wix.com/account/domains) app 

  - **WSR version**: ^8.28.1
  - **Yoshi version**: ^4.117.0

### 👀 Severity
- Low

**Comment by EgoziE** [comment]
I don't see a problem currently, if there's still a problem, let's talk privately (or through #wix-style-react channel)

**Comment by rudnitskih** [comment]
Not relevant more I think. The problem was with styles ordering in dev mode in a storybook.
