### ISSUE TITLE
How to Setup Webpack loaders in Wix library ??

### ISSUE THREAD

**Issue by rajmaxi** [wix/wix-style-react#5691]
# 🐛 Bug Report

### 🏗 Relevant Components

...

### 😯 Current Behavior

...

### 🤔 Expected Behavior

...

### 👣 Steps to Reproduce

  - **WSR version**: `...`
  - **Yoshi version**: `...`

### 👀 Severity

- Critical / Major / Low

Hi ,

I am new to react js but My requirement is need to setup wix UI library in my project. How to setup the web pack in my project in order to work with wix library.  They have created the webpack.config.js file but i dont know how to config those. Whenever i run my project i received the below error and attached here..

![image](https://user-images.githubusercontent.com/41547672/87298748-5560ea80-c528-11ea-8dc4-78015dafbd70.png)

**Comment by EgoziE** [comment]
This is a known issue that we'll address at the beginning of August.

**Comment by rajmaxi** [comment]
Thanks for the valid response and could you address the step to follows.

**Comment by EgoziE** [comment]
Please read our new Usage with [Create Stylable App](https://github.com/wix/wix-style-react/blob/readme/docs/usage/usage-with-create-stylable-app.md) guide.
