### ISSUE TITLE
<ModalMobileLayout/> - Title takes 100% width even when close button appears

### ISSUE THREAD

**Issue by rostyslavP** [wix/wix-style-react#5701]
# 🐛 Bug Report

### 🏗 Relevant Components
<ModalMobileLayout / >

...

### 😯 Current Behavior
On small screen when i use it like this  ```<ModalMobileLayout
      fullscreen={true}
      title={<Text>{modeTitleMap[mode]}</Text>}
      dataHook={dataHook}
      content={}
/>```

getting wrong aligment of title and close button
<img width="1241" alt="Screenshot 2020-07-14 at 21 09 00" src="https://user-images.githubusercontent.com/41200168/87527133-59118000-c694-11ea-94a1-aec3fd6417d6.png">

...

### 🤔 Expected Behavior
The title should be aligned with close button.

...

### 👣 Steps to Reproduce

  - **WSR version**: `8.30.0`
  - **Yoshi version**: `4.119.0`

### 👀 Severity
Low

- Critical / Major / Low

**Comment by EgoziE** [comment]
To reproduce:

https://www.wix.com/pages/wix-style-react/?path=/story/introduction-playground--playground&snippet=1b66a302-c915-4b3d-be65-2553cecdedf7
```
<Box width="350px">
  <ModalMobileLayout
    title={
      <Text weight="bold">
        1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9{' '}
      </Text>
    }
    onCloseButtonClick={() => {}}
  />
</Box>
```

**Comment by EgoziE** [comment]
Moved to Jira - closing
