### ISSUE TITLE
<FloatingHelper/> -  offClick handler

### ISSUE THREAD

**Issue by mastertheblaster** [wix/wix-style-react#5706]
# ✨  offClick handler for the FloatingHelper

Would it be possible to expose `offClick` handler of the floating helper?

Currently we could do like:

```js
<ClickOutside>
  <FloatingHelper />
</ClickOutside>
```

But as `FloatingHelper` is using portal to render outside of the element, it doesn't work.

We can also use like:

```js
<FloatingHelper
  content={
     <ClickOutside>
       <FloatingHelper.Content />
     </ClickOutside>
  }
/>
```

However in this case the `FloatingHelper` itself is adding predefined padding, so even clicking on the helper itself the click outside invokes a callback.

Thanks

**Comment by EgoziE** [comment]
Decided not to develop currently - closing
