### ISSUE TITLE
<DatePicker/>, <Calendar/> - Hover style of Months/Years dropdown and moving between months is not by spec

### ISSUE THREAD

**Issue by alexandraseri** [wix/wix-style-react#5753]
# 🐛 Bug Report

### 🏗 Relevant Components

`<DatePicker/>`, `<Calenadr/>`

...

### 😯 Current Behavior

When clicking to open the months/years dropdown, the content appears in blue, while on hover turns to black.

![image](https://user-images.githubusercontent.com/52129638/88510463-b807bb00-cfeb-11ea-94d1-597351d731f2.png)

Also, when clicking on the arrows of moving between months - the style is rectangular

![image](https://user-images.githubusercontent.com/52129638/88510688-2fd5e580-cfec-11ea-8384-20ed5cb8c2af.png)

...

### 🤔 Expected Behavior

When clicking open the months/years dropdown, the content should appear black, turning blue on hover.

![image](https://user-images.githubusercontent.com/52129638/88510565-f56c4880-cfeb-11ea-87f5-9ffe80b4693a.png)

Also, when clicking on the arrows of moving between months - the style is round

![image](https://user-images.githubusercontent.com/52129638/88510726-42501f00-cfec-11ea-8dcc-c24965f099bd.png)

...

### 👣 Steps to Reproduce

WSR version where it was as expected: 8.30
WSR version with the faulty style: 8.31

### 👀 Severity

Low

**Comment by TalZa1810** [comment]
Seems related to [this PR](https://github.com/wix/wix-style-react/pull/5724)

**Comment by EgoziE** [comment]
Moved to Jira - closing
