### ISSUE TITLE
<Page/> - Component crush when Page.content has an element with margin-top

### ISSUE THREAD

**Issue by daphnakaplan** [wix/wix-style-react#5770]
#5075 🐛 Bug Report

### 🏗 Relevant Components
<Page> <Page.content>

### 😯 Current Behavior
Inner div with marginTop !== 0px leads to error of type : 
Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.

 <Page>
      <Page.Header title="Page Title" />
      <Page.Content>
        <div style={{ marginTop: '1px' }}>hello3</div>
      </Page.Content>
    </Page>

### 🤔 Expected Behavior

allow to add marginTop or at least on fail due to margins

### 👣 Steps to Reproduce

This use works  ===>>>
 <Page>
      <Page.Header title="Page Title" />
      <Page.Content>
        <div style={{ marginTop: '0px' }}>hello3</div>
      </Page.Content>
    </Page>
This one produces an error ===>>>
 <Page>
      <Page.Header title="Page Title" />
      <Page.Content>
        <div style={{ marginTop: '1px' }}>hello3</div>
      </Page.Content>
    </Page>

  - **WSR version**: ^8.27.1
  - **Yoshi version**: ^4.0.0

### 👀 Severity
Major

**Comment by EgoziE** [comment]
fixed in 9.20.0
