### ISSUE TITLE
StatisticsWidget - "children" is missing from typescript interface

### ISSUE THREAD

**Issue by liorcode** [wix/wix-style-react#5773]
# 🐛 Bug Report

### 🏗 Relevant Components

`<StatisticsWidget />`

### 😯 Current Behavior

It seems the [docs](https://www.wix.com/pages/wix-style-react/?activeTab=API&path=%2Fstory%2Fcomponents-api-components--statisticswidget) (and implementation) include a `children` attribute under the `items` prop
However, the [typescript interface](https://github.com/wix/wix-style-react/blob/master/src/StatisticsWidget/index.d.ts) does not include this prop.

### 🤔 Expected Behavior

Interface should include the `children` prop of `items`

  - **WSR version**: 8.34

### 👀 Severity

Low

**Comment by shlomitc** [comment]
thanks. mind making a PR?

**Comment by mosheKerbel** [comment]
@liorcode I think you got confused with something else
The api and also the component itself does not deal with children, but receives `items`
 where do you see `children` in the API?
![image](https://user-images.githubusercontent.com/7388217/88888138-70c93680-d246-11ea-9a16-a069227e52a7.png)

ts interface includes `items`
I'm closing this issue, please reopen it if missed something.

**Comment by liorcode** [comment]
I was talking about the `children` of the `items` prop. you can see it in the screenshot :)
