### ISSUE TITLE
<Table/> - rowDetails with allowMultiDetailsExpansion ignores allowMultiDetailsExpansion

### ISSUE THREAD

**Issue by zeevgg** [wix/wix-style-react#5795]
# 🐛 Bug Report

Table with rowDetails and allowMultiDetailsExpansion . it ignores allowMultiDetailsExpansion only one row is expended. you can see it in playground:
https://www.wix.com/pages/wix-style-react/?path=/story/introduction-playground--playground&snippet=0772a73b-70e6-439e-93e0-1e97ae6e3f72

### 🏗 Relevant Components

<Table>
### 😯 Current Behavior

expends only one row at a time

### 🤔 Expected Behavior

expends multiple  one rows at a time

### 👣 Steps to Reproduce

see playground:
https://www.wix.com/pages/wix-style-react/?path=/story/introduction-playground--playground&snippet=0772a73b-70e6-439e-93e0-1e97ae6e3f72

  - **WSR version**: ^8
  - **Yoshi version**: 4

### 👀 Severity

- Major

**Comment by EgoziE** [comment]
Moved to Jira - closing
