### ISSUE TITLE
<FilePicker> mainLabel isn't clickable

### ISSUE THREAD

**Issue by shaimizrahi** [wix/wix-style-react#5809]
# 🐛 Bug Report

### 🏗 Relevant Components

<FilePicker>

### 😯 Current Behavior

mainLabel of FilePicker isn't clickable

### 🤔 Expected Behavior

mainLabel should be clickable

### 👣 Steps to Reproduce

https://www.wix.com/pages/wix-style-react/?activeTab=Usage&path=%2Fstory%2Fcomponents-api-components--filepicke

  - **WSR version**: `^8.0.0`
  - **Yoshi version**: `^4.0.0`

### 👀 Severity

- Critical / Major / Low

**Comment by orgar28** [comment]
@bamai Any update? what's its status?

**Comment by bamai** [comment]
hey @orgar28 ,
This is still in progress.
Unfortunately I will not be able to complete it in the next few weeks, do you think you can complete it?
If so, here is a link to the PR for this bug:
https://github.com/wix/wix-style-react/pull/5820
thank you :)
