### ISSUE TITLE
<Search/> - Value not changing on blur

### ISSUE THREAD

**Issue by AtomicAlienZ** [wix/wix-style-react#5818]
# 🐛 Bug Report

### 🏗 Relevant Components

`<Search/>`

### 😯 Current Behavior

Situation: a pre-filled controlled search, which should revert to its original value when the user blurs from the field. Error occurs when the user clears the field and blurs. The result:
![image](https://user-images.githubusercontent.com/1439457/89793516-a0bde700-db2e-11ea-98e0-093f6dff1421.png)

If the original value is an empty string, the search becomes unresponsive: the user can't focus it anymore.

### 🤔 Expected Behavior

`<Search/>` should properly work when its value is changed on blur

### 👣 Steps to Reproduce
```typescript
type State = {override: null | string};

export class FiltersV2 extends React.Component<{}, State> {
  state: State = {
    override: null,
  };

  get value() {
    return this.state.override !== null ? this.state.override : 'Something Default';
  }

  onBlur = () =>
    this.setState({
      override: null,
    });

  onChange = (event: React.ChangeEvent<HTMLInputElement>) =>
    this.setState({
      override: event.target.value,
    });

  render() {
    return (
      <>
        {this.value}
        <br />
        <Search
          expandable={true}
          expandWidth={240}
          value={this.value}
          onBlur={this.onBlur}
          onChange={this.onChange}
          onClear={console.log}
        />
      </>
    );
  }
}
```
1. Focus on search
2. Type something
3. Delete everything
4. Blur from the field

  - **WSR version**: `8.41.1`
  - **Yoshi version**: `4.125.0`

### 👀 Severity

- Critical

**Comment by EgoziE** [comment]
To reproduce:
https://www.wix-style-react.com/?path=/story/introduction-playground--playground&snippet=0794c0a2-e88a-4809-8b0d-6f8ced8a5ae4

```
() => {
  const initialState = {
    value: 'Unfocus me',
  };

  const [state, setState] = React.useReducer(
    (currentState, newState) => ({ ...currentState, ...newState }),
    initialState,
  );

  return (
    <>
      {state.value}
      <br />
      <Search
        expandable={true}
        expandWidth={240}
        value={state.value}
        onBlur={event => setState({ value: null })}
        onChange={event => setState({ value: event.target.value })}
        onClear={console.log}
      />
    </>
  );
};
```
