### ISSUE TITLE
<SortableList/> - dragged item is shifted

### ISSUE THREAD

**Issue by dovilel** [wix/wix-style-react#5825]
# 🐛 Bug Report

### 🏗 Relevant Components

`<SortableList />`

...

### 😯 Current Behavior

Starting drag on sortable list item shifts the dragged item to right and down, so it's not under mouse.

![WSR8-drag-shift](https://user-images.githubusercontent.com/22763470/89904799-0aeb9000-dbf2-11ea-855f-d995f0a5a629.gif)

![WSR8-pricing-plans-drag](https://user-images.githubusercontent.com/22763470/89905243-99601180-dbf2-11ea-99ad-e909fe9df475.gif)

This behavior starts with WSR 8.0.0
Fine in latest WSR 7 version.
Happens both in Events and Pricing plans, on all SortableList usages. Could not reproduce in WSR playground.

...

### 🤔 Expected Behavior

Mouse to stay over drag handle

...

### 👣 Steps to Reproduce

1. Install Pricing Plans in Editor.
2. Go to Business Manager -> Pricing Plans
3. Add a new pricing plan.
4. Try dragging it.

  - **WSR version**:  8.0.0+
  - **Yoshi version**: 4.140.0

### 👀 Severity

- Major

**Comment by EgoziE** [comment]
fixed
