### ISSUE TITLE
<SortableList/> - drag does not work if overlapping another iframe (Chrome)

### ISSUE THREAD

**Issue by dovilel** [wix/wix-style-react#5826]
# 🐛 Bug Report

### 🏗 Relevant Components

`<SortableList />` in WSR 8.0.0+

...

### 😯 Current Behavior

Drag does not work if dragging in Business Manager opened in Editor modal when mouse is over certain TPA iframes (Events, Bookings, Hotels).
Only in **Chrome**

![WSR8-drag-in-dashboard-modal-stuck](https://user-images.githubusercontent.com/22763470/89905920-65392080-dbf3-11ea-801c-1a930f340c62.gif)
![WSR8-drag-stuck-in-dashboard-modal](https://user-images.githubusercontent.com/22763470/89905933-679b7a80-dbf3-11ea-8238-a9f766fc4a06.gif)

...

### 🤔 Expected Behavior

Drag to always work.
...

### 👣 Steps to Reproduce

1. On blank site, install Pricing Plans.
2. Install Bookings.
3. Go to Bookings page. (for clearer effect, reducing Bookings widget width to be half)
4. Open Business Manager in modal, eg from clicking Manage Services from Bookings widget.
5. Open Pricing Plans section in BM.
6. Add 2 plans.
7. Try dragging a plan over the same space where Bookings widget sits in Editor.

Result: drag seems to stop working when it hits the space occupied by Bookings iframe. Once mouse moves out of that iframe's bounds, drag is back to normal.

Some debugging:
1. Setting `pointer-events: none` on TPA's iframe fixes the issue.
2. A guess, but problem happens only if domain of TPA iframe (wixapps.net) does not match domain of BM (wix.com).
3. Supporting second point, problem disappears if you enable `Strict-Origin-Isolation` in `chrome://flags`
4. Reproducible in WSR playground (replace opened BM's iframe src with playground src).
5. Reproducible with various combinations of TPAs. Events/Bookings/Hotel in Editor with Events/Pricing plans in BM.
6. Starts with WSR 8.0.0

  - **WSR version**: `8.0.0+`
  - **Yoshi version**: `4.140.0`

### 👀 Severity

- Critical

**Comment by EgoziE** [comment]
Decided not to fix - closing
