### ISSUE TITLE
InputArea doesn't work correctly

### ISSUE THREAD

**Issue by ralphhovsepian** [wix/wix-style-react#5832]
# 🐛 Bug Report

### 🏗 Relevant Components

<InputArea/>

### 😯 Current Behavior

No errors. the input doesn't show. Only the border of it does.

**[https://imgur.com/NQgWuAA](url)**

### 🤔 Expected Behavior

It should show normally

### 👣 Steps to Reproduce

```
import React from "react";
import InputArea from "wix-style-react/InputArea";


export default class App extends React.Component {
  render() {
    return (
      <div>
        


        <InputArea
                      rows={3}
                      maxHeight="120px"
                      minHeight="50px"
                      resizable
                    />
      </div>
    );
  }
}

```

  - **WSR version**: `...`
  - **Yoshi version**: `...`

### 👀 Severity

- Low

**Comment by EgoziE** [comment]
Looks like css isn't loaded correctly.
Please read our new Usage with [Create Stylable App](https://github.com/wix/wix-style-react/blob/readme/docs/usage/usage-with-create-stylable-app.md) guide.

If you manage to recreate this problem in our storybook, let us know, thank you!
