### ISSUE TITLE
Add maxLength support to <VariableInput>

### ISSUE THREAD

**Issue by splintor** [wix/wix-style-react#5846]
# ✨ Feature Request

### 🔦 Scope
Support limiting the input length of a <VariableInput> component, similar to <InputArea>.

### 💁 Explanation
In [ping-automations-client](https://github.com/wix-private/wixos/tree/master/ping/ping-automations/ping-automations-client), we want to move from using `<Input>` and `<InputArea>` to use `<VariableInput>`. Currently, we use `maxLength` prop to limit our `<InputArea>` input length to `200`, and we would like to be able to do it with `<VariableInput>`.

### 🐾 Possible solution
https://stackoverflow.com/questions/46044251/how-to-limit-max-length-of-draft-js

Without it, we can just show an error to the user when she exceeds the length, but this is not the best UX.

### 👀 Severity

- Low

**Comment by shlomitc** [comment]
In the `onChange` callback we provide both options to you to decide from:
![image](https://user-images.githubusercontent.com/6093192/90371451-ab6d0480-e077-11ea-81be-ed0a0dc450ea.png)

That will allow you to decide if you wish to use the entire markup for limiting the length or only the textual content

**Comment by shlomitc** [comment]
oops, I looked in the `RichTextInputArea` instead of `VariableInput`.
So let's start over - what exactly do you want to limit - the raw text?

**Comment by splintor** [comment]
Yes, raw text. After all, this is what's saved in the database.

**Comment by EgoziE** [comment]
If it's critical, please discuss with our UX through slack #wix-style-ux
