### ISSUE TITLE
Allow <Layout /> to be inline

### ISSUE THREAD

**Issue by moshfeu** [wix/wix-style-react#5848]
# ✨ Feature Request

### 🔦 Scope

Expected layout

![Screen Shot 2020-08-17 at 12 04 50](https://user-images.githubusercontent.com/3723951/90378577-36eb9300-e082-11ea-8f30-0ed7fd1d7a45.png)

`<Layout />` component using `display: grid`. So anyway it takes 100% width. `align

```
justifyItems="center"
```

![Screen Shot 2020-08-17 at 12 06 28](https://user-images.githubusercontent.com/3723951/90378691-57b3e880-e082-11ea-80bc-d1d6acd5d4a1.png)

In regular grid, `justify-content: center;` would do the job but not in `<Layout />` because it divided to 12 with `span`s.

...

### 💁 Explanation

...

### 🐾 Possible solution 

The solution might be to add `inline` prop so it will set `display: inline-grid` instead of `display: grid`.

...

### 👀 Severity

- Low

A workaround is to wrap the `<Layout />` with a div with `display: inline-block`.

**Comment by shlomitc** [comment]
There are many layout options in the library, maybe `Layout` is not the right one here.
We also have `Box` which is a flexbox container.

**Comment by moshfeu** [comment]
It was just an example. Like in css, there are different ways to implement the same layout, even though, `display: inline-grid` exists 😄

**Comment by shlomitc** [comment]
We try suggesting the best solutions for layouts. everything can obviously be done with more options but we prefer narrowing down the options when possible and not adding more features if not necessary.

In this case, I truly believe that the `Box` component is a good candidate, but I need to see the entire context of this page to verify it

**Comment by moshfeu** [comment]
Makes sense.
I'll try to implement it using `Box`.
