### ISSUE TITLE
RichTextInputArea missing padding  prop

### ISSUE THREAD

**Issue by michalavraham** [wix/wix-style-react#5875]
# 🐛 Bug Report

### 🏗 Relevant Components

<RichTextInputArea />
...

### 😯 Current Behavior:
numbered list and the bulleted list is cut.

...

### 🤔 Expected Behavior
adding padding prop to be able to manage inner input padding when choosing a numbered list or bulleted list.
...

### 👣 Steps to Reproduce

```
 <RichTextInputArea
    dataHook={`invoices-notes`}
  />
```

```
* {
padding: 0px; \\ css file
}
```

### 👀 Severity
Critical

**Comment by EgoziE** [comment]
If really needed, discuss with our UX at slack #wix-style-ux
