### ISSUE TITLE
Badge text is not centered when using MadeFor

### ISSUE THREAD

**Issue by yogevitz** [wix/wix-style-react#5876]
# 🐛 Bug Report

### 🏗 Relevant Components

Badge

### 😯 Current Behavior

The text of the Badge is closer to the top of the component when using MadeFor font

### 🤔 Expected Behavior

Text should be centered (as with the old font)

### 👣 Steps to Reproduce

Can see on WSR storybook:
Open Badge component page > Toggle MadeFor ON

  - **WSR version**: `^9.1.0`
  - **Yoshi version**: `^4.119.0`

### 👀 Severity

- Low

**Comment by EgoziE** [comment]
I'm sorry but I can't find any problem with Madefor here.
I tried zoom in and out, the code says 5px padding no matter what.
I do think it's related to pixel rounding that works differently between browsers and versions...
If you can point in the code for something that is broken, please re-open this issue with more information.
![image](https://user-images.githubusercontent.com/35173937/91452207-00cec000-e887-11ea-9016-e27271295f2b.png)
