### ISSUE TITLE
<DropdownLayout> - RTL storybook example is not displayed in rtl direction

### ISSUE THREAD

**Issue by liorcode** [wix/wix-style-react#5879]
# 🐛 Bug Report

### 🏗 Relevant Components

`<DropdownLayout>`

### 😯 Current Behavior

In storybook, the `DropdownLayout` has an example of RTL:
https://www.wix.com/pages/wix-style-react/?path=/story/components-api-components--dropdownlayout
However, the options are not really displayed in RTL direction.
The only way to get it to display in RTL, is using the "globe" icon.

### 🤔 Expected Behavior

RTL options example should appear in RTL direction

### 👀 Severity

- Low

**Comment by sivanharel** [comment]
Work in progress, opened task in Jira:
https://jira.wixpress.com/browse/DSM-775
