### ISSUE TITLE
Expose colors

### ISSUE THREAD

**Issue by tyv** [wix/wix-style-react#588]
what do you think? I need palette for other project and don't want to copy paste and support all the time that, instead I think separate repo would be nice and we can maintain this list together, will you consider PR with using it as object from `node_modules` (if it is possible in sass, I don't have much experience with it)?

**Comment by tyv** [comment]
i've added simple package https://github.com/wix/style-variables on npm as `wix-style-variables`
what I can do is produce `scss` also from that, so you will import `@import '../node_modules/wix-style-variables/dist/index.scss'` or I can try to add `json` import support to current `scss`, which might take time, because I am totally unaware on current stack of this propject.

**Comment by lbelinsk** [comment]
Hey,
We are not sure we want to expose this file at all.
We are considering what to do exactly.

This file will be reorganised in any case.
One possible approach is to expose all colors via the `<Text>` component, but we still considering our solution.
Will update here in any case, and you are welcome to suggest other alternatives.
Thanks..

**Comment by joncys** [comment]
We need a well documented and a sane sollution to this, to use in all of the contexts. Colors as much as any other design language element (fonts, grid sizes, etc.) are considered to be a part of the reusable design stack by the developers, so I need to be able to use these predefined wix style colors even in weird contexts such as coloring svg fills. Thus, documenting and exposing them via css variables seems like a good start. Then build upon that with, say the `<Text>` element.

**Comment by argshook** [comment]
closing in favor of #1094
