### ISSUE TITLE
<InputArea/> does not have `required` property

### ISSUE THREAD

**Issue by tyv** [wix/wix-style-react#5886]
# 🐛 Bug Report

### 🏗 Relevant Components

`InputArea`

### 😯 Current Behavior

Component does not have `required` property.

### 🤔 Expected Behavior

Expect same as `Input` to have `required` property and behave accordingly. 

### 👀 Severity

Low (i can use regular `textarea`, I think)

**Comment by EgoziE** [comment]
@tyv Would you like to contribute this?

**Comment by tyv** [comment]
@EgoziE sure, review plz
