### ISSUE TITLE
Bug with Input placeholder in IE 11

### ISSUE THREAD

**Issue by lbelinsk** [wix/wix-style-react#589]
There is no placeholder Inputs in ie 11

![image](https://user-images.githubusercontent.com/18248989/27879076-23fbef1e-61c9-11e7-83bf-e7faa307dc7f.png)

In order to reproduce, go to https://users.wix.com/account-recovery/reset-account-information/free, continue with the wizard until you get to "Verify This Account" page.

**Comment by lbelinsk** [comment]
After searching a bit for a solution, here is a suggested polyfill:
https://github.com/jamesallardice/Placeholders.js

**Comment by Faradey27** [comment]
Do we really need this dependency, i think better to wait for IE11 deprecation)

**Comment by lbelinsk** [comment]
@Faradey27 This is in production, so i am not sure.. wdyt?

**Comment by shlomitc** [comment]
pretty old bug closing
