### ISSUE TITLE
Unidrivers - make sure drivers are not using static class names as selectors

### ISSUE THREAD

**Issue by shlomitc** [wix/wix-style-react#5893]
There are some drivers that are still querying selectors by using class names.
This isn't a good approach since bundled apps contain different hashing for class names.

You can see an effort that was done for most drivers here - https://github.com/wix/wix-style-react/pull/4773

Some drivers might still be broken because of using the static names:

![image](https://user-images.githubusercontent.com/6093192/91438878-bcd2bf80-e874-11ea-8fb8-0904b4ccf5c4.png)

![image](https://user-images.githubusercontent.com/6093192/91438815-a6c4ff00-e874-11ea-81e8-d6aa521e6125.png)

**Comment by EgoziE** [comment]
done
