### ISSUE TITLE
<StarsRatingBar /> - testkit getSelectedRating() in readOnly mode always returns 5

### ISSUE THREAD

**Issue by assafganor** [wix/wix-style-react#5899]
# 🐛 Bug Report

### 🏗 Relevant Components

StarsRatingBar

...

### 😯 Current Behavior

tests problem:
driver.getSelectedRating()  returns always 5

The reason is that the same data-hook="filled-star" is used for both empty and filled stars
...

### 🤔 Expected Behavior

returns the correct value in readOnly mode too

...

### 👣 Steps to Reproduce

You can add this test:
```
  it('should show correct value on readOnly mode', async () => {
    const ratingValue = 2;
    const { driver } = render(<StarsRatingBar value={ratingValue} readOnly />);

    expect(await driver.getSelectedRating()).toEqual(ratingValue);
  });
```
In:
https://github.com/wix/wix-style-react/blob/master/src/StarsRatingBar/test/StarsRatingBar.spec.js

  - **WSR version**: `^9.3.0`
  - **Yoshi version**: `^4.1.0`

### 👀 Severity

 Low

**Comment by sivanharel** [comment]
Resolved.
Link for the PR: [(https://github.com/wix/wix-style-react/pull/5905)]
