### ISSUE TITLE
<CounterBadge/> does not look properly with `box-sizing: border-box`

### ISSUE THREAD

**Issue by AtomicAlienZ** [wix/wix-style-react#5915]
# 🐛 Bug Report

### 🏗 Relevant Components

`<CounterBadge/>`

### 😯 Current Behavior

If the project uses `box-sizing: border-box` for everything, `<CounterBadge/>` looks weird with narrow content:
![image](https://user-images.githubusercontent.com/1439457/91877842-37417c00-ec87-11ea-8735-62abac2a7dd2.png)

### 🤔 Expected Behavior

`<CounterBadge/>` should have `min-width` which works with any surrounding box-sizing and look perfectly round with narrow content.

### 👣 Steps to Reproduce

  - **WSR version**: `9.5.0`
  - **Yoshi version**: `4.166.0`

**Comment by sivanharel** [comment]
Resolved: [link for the PR](https://github.com/wix/wix-style-react/pull/5920)
