### ISSUE TITLE
<ModalSelectorLayout> - Select/Deselect all does not trigger the "onSelect" callback

### ISSUE THREAD

**Issue by liorcode** [wix/wix-style-react#5919]
# 🐛 Bug Report

### 🏗 Relevant Components

<ModalSelectorLayout>

### 😯 Current Behavior

I have a `ModalSelectorLayout` component with an `onSelect` callback. I use it to maintain an external list of which items are currently selected.
The problem is, that if a user clicks "Select all" - it does not trigger the `onSelect` callback - so I can't know that the selection was changed.

### 🤔 Expected Behavior

"Select All" / "Deselect all" should trigger the `onSelect` callback for all the relevant items.
Alternatively - support an `onSelectAll` prop.

### 👀 Severity

- Medium

**Comment by EgoziE** [comment]
Component was deprecated - closing
