### ISSUE TITLE
tabsTestkitFactory/TabsTestkit throws error when trying to use clickTabAt in puppeteer

### ISSUE THREAD

**Issue by UrielParienti** [wix/wix-style-react#5943]
### 🏗 Relevant Components

<Tabs>(tabsTestkitFactory / TabsTestkit )

### 😯 Current Behavior

trying to click on a specific tab index
falling due to :
"Error: Supported only in React/DOM"

### 🤔 Expected Behavior

tab will be clickable by index

### 👣 Steps to Reproduce

```
import {
  TabsTestkit,
  tabsTestkitFactory,
} from 'wix-style-react/dist/testkit/puppeteer';
    const tabsDriver = await TabsTestkit({
      dataHook: 'contact-panel-tabs',
      page: this.sledPage,
    });

    await tabsDriver.clickTabAt(1);

```

  - **WSR version**: 9.0.0
  - **Yoshi version**: `4.73.0`

### 👀 Severity

Low

**Comment by EgoziE** [comment]
Moved to Jira - closing
