### ISSUE TITLE
Notification component position is not recalculated on window.resize

### ISSUE THREAD

**Issue by dht** [wix/wix-style-react#5950]
# 🐛 Bug Report

### 🏗 Relevant Components

Notification

### 😯 Current Behavior

When a Notification component has two lines it is positioned correctly but if the window is expanded to a greater width the position of the component is not recalculated. This could be an issue with the underlying wix-animations library.

### 🤔 Expected Behavior

The notification is repositioned in the correct top location.

### 👣 Steps to Reproduce

  - **WSR version**: `^9.2.0`
  - **Yoshi version**: `^4.0.0`

### 👀 Severity

Low

**Comment by TalZa1810** [comment]
link to a video recreating the issue: https://wix.slack.com/archives/C39FTGUBZ/p1599642026158800?thread_ts=1599395121.079400&cid=C39FTGUBZ

**Comment by EgoziE** [comment]
Moved to Jira - closing
