### ISSUE TITLE
[MessageModalLayout] Cannot render node as primaryButton children.

### ISSUE THREAD

**Issue by etaybarzilay89** [wix/wix-style-react#5955]
# 🐛 Bug Report

### 🏗 Relevant Components

1. CustomModalLayout
Maybe other modals as well (such as MessageModalLayout) - not sure.
...

### 😯 Current Behavior

If I pass primaryButtonProps={{children: <Loader size="tiny" />}} it doesn't work (i.e. the loader does not appear on the button).

btw, it works if I just pass the loader to primaryButtonText prop, but it's a mistake since in the documentation it describes as a string prop. (so either a documentation error or an implementation one).
...

### 🤔 Expected Behavior

Loader should render on the button.

...

### 👣 Steps to Reproduce

https://www.wix-style-react.com/?path=/story/introduction-playground--playground&snippet=7063aaf5-9bba-4753-b960-affd9f719154

### 👀 Severity

Not sure.

**Comment by EgoziE** [comment]
This is how you can achieve it:
https://www.wix-style-react.com/?path=/story/introduction-playground--playground&snippet=1e4be557-dbb1-4882-bd92-7c97a5355b5a

![image](https://user-images.githubusercontent.com/35173937/93016323-09cec980-f5c9-11ea-9e8c-32375a58ab16.png)

**Comment by EgoziE** [comment]
And I'll change text to node

**Comment by etaybarzilay89** [comment]
I know I can pass a node to this prop, but @lironch said It works by mistake and when it will get fixed, it will no longer work.

So are you saying this is just a  documentation mistake (and prop name mistake)?

**Comment by EgoziE** [comment]
Yes, but the prop won't be renamed in order not to break anyone.
I changed the type in the d.ts file
