### ISSUE TITLE
Inconsistent behaviour with status props in MultiSelectCheckbox

### ISSUE THREAD

**Issue by shlaskt** [wix/wix-style-react#5996]
# 🐛 Bug Report

### 🏗 Relevant Components

MultiSelectCheckbox

...

### 😯 Current Behavior

When using ` status="Input.StatusError"` getting only the icon without red border (Like in the component storybook).
But when using ` status={Input.StatusError}` getting the red border also.

 

...

### 🤔 Expected Behavior

It's Inconsistent.

...

### 👣 Steps to Reproduce

With red border: https://www.wix.com/pages/wix-style-react/?path=/story/introduction-playground--playground&snippet=f2d49d7a-425d-40b4-affd-896c0ba4f48e
Without: https://www.wix.com/pages/wix-style-react/?path=/story/introduction-playground--playground&snippet=ca4c5cfe-5497-4236-b6ca-eb5cd5745ca9

-  Low

**Comment by shlomitc** [comment]
I don't think what you're doing is a valid usage of it.
an error should be displayed either by `status={Input.StatusError}` or `status="error"`.

There might be a side effect when passing a string which isn't valid

**Comment by shlaskt** [comment]
Great, so please update your component playground, because I take the example from that: https://www.wix.com/pages/wix-style-react/?activeTab=Playground&path=%2Fstory%2Fcomponents-api-components--multiselectcheckbox
![image](https://user-images.githubusercontent.com/45847538/93470455-9c89a400-f8fa-11ea-960f-7d3938f9cb14.png)

**Comment by shlomitc** [comment]
Can you make a small PR fixing it? That would be a great help

**Comment by shlaskt** [comment]
Fixed
