### ISSUE TITLE
Ellipsis propTypes

### ISSUE THREAD

**Issue by TalZa1810** [wix/wix-style-react#6016]
# Documentation Issue

All components which use [EllipsisCommonProps](https://github.com/wix/wix-style-react/blob/master/src/common/PropTypes/EllipsisCommon.js) , the props are not renders to the API tab (`<Text/>`, `<Heading/>` ...). 

### 🔦 Scope

Relevant Page URL: 
https://www.wix-style-react.com/?path=/story/components-api-components--text
https://www.wix-style-react.com/?path=/story/components-api-components--heading

### 💁 Explanation

Should decide whether we want to override them manually of find another solution. When we spread all the `Ellipsis` props, we get some props we don't want to display in the API tab. 

### 👀 Severity
- [ ] Major
- [x] Medium
- [ ] Low

**Comment by EgoziE** [comment]
As a quick fix, just duplicate the proptypes.
The real problem is that we cannot "compute" values in AST traverse.
Autodocs generation is made by a third party library that is not really maintained :(
