### ISSUE TITLE
<InputWithOptions/> - onBlur is called when selecting an option from the list

### ISSUE THREAD

**Issue by shlomitc** [wix/wix-style-react#6051]
# 🐛 Bug Report

### 🏗 Relevant Components
`<InputWithOptions/>`

### 😯 Current Behavior
When selecting an option from the dropdown list **with the mouse**, the `onBlur` method is called.

This is quite bad since some logics expect the `onBlur` to be triggered to clear a list or undo some action but this could lead to incorrect results. My hunch is that it's related to the `onClickOutside` logic, but I didn't check it thoroughly.

### 🤔 Expected Behavior
Not to trigger `onBlur`.

### 👣 Steps to Reproduce

```jsx
<InputWithOptions
  placeholder="select the option with the mouse"
  onBlur={() => alert("called onBlur - this shouldn\'t happen")}
  options={[{ id: 0, value: 'First option' }]}
/>;
```
https://www.wix-style-react.com/?path=/story/introduction-playground--playground&snippet=156fa95f-e217-4aa5-815c-12a73ebcfb5d

### 👀 Severity

Major

**Comment by EgoziE** [comment]
Moved to Jira - closing
