### ISSUE TITLE
<VariableInput /> - Value is removed when adding emoji next to `/` 

### ISSUE THREAD

**Issue by tzachbon** [wix/wix-style-react#6069]
# 🐛 Bug Report

### 🏗 Relevant Components

[`VariableInput`](https://www.wix-style-react.com/?path=/story/components-api-components--variableinput)

### 😯 Current Behavior

When you add an emoji next to a `/` it removes the slash.
[Example](https://www.wix-style-react.com/?path=/story/introduction-playground--playground)

### 🤔 Expected Behavior

Not to remove it.

### 👣 Steps to Reproduce
[An example](https://www.wix-style-react.com/?path=/story/introduction-playground--playground)

Let's say you have the value `xxx/{{slug}}` and you add an emoji between the slash like this `xxx🤔/{{slug}}`

The onChange method will return this value: `xxx🤔 {{slug}}`

![GIF](https://lh3.googleusercontent.com/fife/ABSRlIouTWs0IUcWGYuDKpjywSIICQcNl5unyra7lG1JCnZY_KM5zEihIo9__urYDBQL9--qfsw1gjwZfwvRivIxl3E3iVkK3suV8LaBTox3MrNSYhRWYpuHj7BoKeS1C7XYi_zQi0Sdb1oFYFJHxESfgifzAzhxDbj4FiWnSOshlD4rTFXLdxC05KPmYocNoJDjXoe1TPc-YkrkBRFeYKGSYsvx7Hx42U0GQnInFSSkJ5dNlK2k0r6iX_fK5aBky37Ea5dqIRxvWUdKPFpPhqE5QXWWlHXLLN7ujXOeHZSsYXe7r_pOvBAOX6B2CmTReZ5Yp26Td6KWL_hwhIqty3Vue3NOWIoss3JhdBkX7MRNRl-HDRZ7gDcLThPGOLINMbcKnyuMYj0OqwUY-4t0PNlFcKBdewrWVrOBvnZRki6FXKNswYPaAqEJMt3dq1_0y2wbDx-w2ZX-thy69mMYPKR6eJf0bcsHSjGmSzSGMHTeODISph-brFF6UjWuimixTE0CODrjy077hsdVTzRAAOrXQu6SuLSV9QXHvXJlY2mwGuC5oHNeKKFBwFyUi77qGSK4L9WJ6TSocljAued_ZjqPFL26wzmYHpZGdMktIEDTR6Q70wtRO5UbU4cK-fUzoCb3QsbFv4J4-a2OHBlKITM1peeOXfD5FC87NEzF_FlInfC9KlD7Au-1HUzOuTkGAJLPhKI6mSCDandMiFXgeWHF_pZ7quce7hbPlA=w1920-h897-ft)

After checking the source code I think the issue is related to [this line](https://github.com/wix/wix-style-react/blob/c7805841acd4eb76852744ccd407bc6b6596babb/src/VariableInput/EditorUtilities.js#L63)

### 👀 Severity

- Major

**Comment by EgoziE** [comment]
Moved to Jira - closing
