### ISSUE TITLE
Support for NextJS serverless

### ISSUE THREAD

**Issue by sebastienlabine** [wix/wix-style-react#6090]
Hi,

Could it be possible to support Next.JS for serverless use (no server.js)? We can't use the library because the .st.css are being used in the dist/es/ files.

[https://github.com/vercel/next.js/blob/master/errors/css-npm.md](url)
****
![image](https://user-images.githubusercontent.com/8888846/95931907-6411a480-0d98-11eb-8eb1-17c332c29317.png)
https://github.com/vercel/next.js/blob/master/errors/css-npm.md

**Comment by EgoziE** [comment]
Moved to Jira - closing
