### ISSUE TITLE
Tab is not working properly with ColorInput

### ISSUE THREAD

**Issue by daliusd** [wix/wix-style-react#6152]
# 🐛 Bug Report

### 🏗 Relevant Components

ColorInput

### 😯 Current Behavior

Tab is not working properly with ColorInput. See screenshot:

![image](https://user-images.githubusercontent.com/1944737/97702082-15ae1680-1ab7-11eb-8732-fd23e434b543.png)

### 🤔 Expected Behavior

When tab is used it should close color picker.

### 👣 Steps to Reproduce

  - **WSR version**: `9.29.1`
  - **Yoshi version**: `4.230.0`

### 👀 Severity

- Major

**Comment by mastertheblaster** [comment]
Seems like adding extra condition inside `_keyDown` method solves the issue (at least in our usecase).

```ts
class ColorInputOnSteroids extends ColorInput {
  _keyDown = (e: KeyboardEvent) => {
    e.stopPropagation();
    e.key === 'Tab' && (this as any).confirm();
    e.key === 'Enter' && (this as any).confirm();
    e.key === 'Escape' && (this as any).cancel();
  };
}
```

**Comment by EgoziE** [comment]
Moved to Jira - closing
