### ISSUE TITLE
[DatePicker] Excluding past dates ignores filtered dates

### ISSUE THREAD

**Issue by koSiukaS** [wix/wix-style-react#6175]
# 🐛 Bug Report

### 🏗 Relevant Components

DatePicker

...

### 😯 Current Behavior

When `excludePastDates` and `filterDate` props are used, the `filterDate` prop gets ignored and dates previously filtered become available.

...

### 🤔 Expected Behavior

Past dates and filtered dates not being available.

...

### 👣 Steps to Reproduce

  - **WSR version**: `9.1.0`
  - **Yoshi version**: `4.1.0`

### 👀 Severity

- Low

**Comment by EgoziE** [comment]
Moved to Jira - closing
https://jira.wixpress.com/browse/DSM-1508
