### ISSUE TITLE
Any reason for VerticalTabs.TabItem id prop to be number and not string?

### ISSUE THREAD

**Issue by tzelonm** [wix/wix-style-react#6185]
# ✨ Feature Request / Question

### 🔦 Scope

Change[ VerticalTabs.TabItem id prop](https://github.com/wix/wix-style-react/blob/d28e641bbb9e785084c3c8d15cac392a06b285f8/src/VerticalTabsItem/VerticalTabsItem.js#L32) type to string instead of number.

VerticalTabs activeTabId will also need to be changed to string
https://github.com/wix/wix-style-react/blob/d28e641bbb9e785084c3c8d15cac392a06b285f8/src/VerticalTabs/VerticalTabs.js#L42
...

### 💁 Explanation
ids should be informative and not just a number. Also, HTML ids are strings.

**Comment by EgoziE** [comment]
I agree it can be changed to a `number | string`
Would you like to contribute a fix?

**Comment by tzelonm** [comment]
Sure, https://github.com/wix/wix-style-react/pull/6290.
