### ISSUE TITLE
Importing EditorX theme is not working as docs suggested

### ISSUE THREAD

**Issue by dht** [wix/wix-style-react#6197]
In the [docs](https://www.wix-style-react.com/?path=/story/themes-editorx--editorx-theme) this is the suggested way to import the `editorX` theme:
```
import { theme } from 'wix-style-react/themes/editorX';
```
However using this returns:
> Cannot find module 'wix-style-react/themes/editorX' or its corresponding type declarations.ts(2307)

The routing may not be implemented and only a direct import works:
```
import { theme } from 'wix-style-react/dist/src/Themes/editorX';
```

**Comment by shlomitc** [comment]
it looks like a typescript error. does it work if you override the types declaration?

**Comment by dht** [comment]
@shlomitc how? should we create a mock definition?

**Comment by shlomitc** [comment]
Did you try it with the latest working version of `wix-style-react` it might have been resolved already
