### ISSUE TITLE
<Badge/>- cutting special characters

### ISSUE THREAD

**Issue by Roeia1** [wix/wix-style-react#6202]
# 🐛 Bug Report

### 🏗 Relevant Components

`<Badge>`
...

### 😯 Current Behavior

currently when writing this special character Å in Norwegian inside a small-sized Badge,
the circle above the letter is being cut off.

...

### 🤔 Expected Behavior

seeing the entire character correctly.

...

### 👣 Steps to Reproduce

https://www.wix-style-react.com/?path=/story/introduction-playground--playground&snippet=3c0a8d13-3a66-4977-ad1a-e979ce2251dd

  - **WSR version**: latest
  - **Yoshi version**: latest

### 👀 Severity

Critical (it's a blocker for us)

**Comment by EgoziE** [comment]
Moved to Jira - closing
