### ISSUE TITLE
MultiSelect inner input

### ISSUE THREAD

**Issue by lbelinsk** [wix/wix-style-react#623]
Don't expand to a new row if not needed.
For example in Guineapig -> add experiment form -> add one value to some filter and it immediately starts a new line although there is enough space:

![image](https://user-images.githubusercontent.com/18248989/28251754-cd4a7100-6a8c-11e7-8e8a-511337eb4aa5.png)

@nirhart

**Comment by nirhart** [comment]
do you use the latest? it suppose to be fixed there

**Comment by lbelinsk** [comment]
I am using wix-style-react latest :/
