### ISSUE TITLE
Show <Tooltip /> for disabled state in PopoverMenu.Item

### ISSUE THREAD

**Issue by rudnitskih** [wix/wix-style-react#6297]
# ✨ Feature Request

### 🔦 Scope

Add support to show tooltip when `<PopoverMenu.Item />` hovering in disabled state

### 💁 Explanation

There is no way to achieve such behaviour:
![image (80)](https://user-images.githubusercontent.com/8848858/99914528-aa96df00-2d06-11eb-8deb-f721448862b2.png)

Discussions:
- https://wix.slack.com/archives/C39FTGUBZ/p1603445304413100
- https://wix.slack.com/archives/C39FTGUBZ/p1605806906389900

### 🐾 Possible solution 

Two solutions in mind:
- trigger onMouseEnter event also in disabled state in `<DropdownLayout />`
- allow to pass `tooltipProps` into `<PopoverMenu.Item />` (similuar to `infoTooltipProps` in `<FormField />`) 

### 👀 Severity

Important behaviour for Roles&Permissions features

- Major

**Comment by EgoziE** [comment]
done
