### ISSUE TITLE
[Checkbox] - broken link for label driver

### ISSUE THREAD

**Issue by alexkubica** [wix/wix-style-react#6322]
# Documentation Issue

### 🔦 Scope

Relevant Page URL: 
https://www.wix-style-react.com/?activeTab=Testkit&path=%2Fstory%2Fcomponents-api-components--checkbox

### 💁 Explanation

The link for `label driver` in the table `Checkbox TestKit API
` under tab `Testkit`, is broken.

### Expected Docs 

The correct link :)

### 👀 Severity

- [ ] Major
- [X] Low

**Comment by EgoziE** [comment]
Moved to Jira - closing
