### ISSUE TITLE
<Carousel/> - image is not centered vertically with dots={false}

### ISSUE THREAD

**Issue by davydof** [wix/wix-style-react#6341]
# 🐛 Bug Report

### 🏗 Relevant Components

Carousel

### 😯 Current Behavior

Arrows are not centered with `dots={false}`

### 🤔 Expected Behavior

Arrows are centered vertically with `dots={false}`

### 👣 Steps to Reproduce

https://www.wix-style-react.com/?path=/story/introduction-playground--playground&snippet=6ca893f6-11b9-4787-8d92-bb6a55e977d3

  - **WSR version**: `9.46.0`
  - **Yoshi version**: `4.253.0`

### 👀 Severity

- Minor

![image](https://user-images.githubusercontent.com/10529679/100734770-d9811500-33d8-11eb-8c74-cf3501a3ebc5.png)

**Comment by davydof** [comment]
https://www.wix-style-react.com/?path=/story/introduction-playground--playground&snippet=dcfb637f-57d9-45ac-af94-9e41c9a731e4

Reproduces

**Comment by EgoziE** [comment]
Moved to Jira - closing
