### ISSUE TITLE
<FormField/> - labelPlacement="left" style is broken with long text

### ISSUE THREAD

**Issue by davydof** [wix/wix-style-react#6356]
# 🐛 Bug Report

### 🏗 Relevant Components

FormField
https://www.wix-style-react.com/?path=/story/components-api-components--formfield

### 😯 Current Behavior

![image](https://user-images.githubusercontent.com/10529679/101126790-d9655d00-3604-11eb-9672-98771a37543e.png)

### 🤔 Expected Behavior

![image](https://user-images.githubusercontent.com/10529679/101126756-ce123180-3604-11eb-952e-c253fd96208e.png)

### 👣 Steps to Reproduce

```js
<div style={{ width: 200 }}>
  <FormField
    id="visual-indicators-setting-card-toggle-switch-id"
    label="Allow keyboard users to navigate through your site."
    labelPlacement="left"
    labelSize="small"
  >
    <ToggleSwitch
      id="visual-indicators-setting-card-toggle-switch-id"
      dataHook="visual-indicators-setting-card-toggle-switch"
      onChange={() => {}}
      checked={() => {}}
      disabled={false}
      size="medium"
    />
  </FormField>
</div>;
```

https://www.wix-style-react.com/?path=/story/introduction-playground--playground&snippet=a33d452f-9459-41bd-97f2-a1af5dd309b1

  - **WSR version**: `9.48.0`
  - **Yoshi version**: `4.253.0`

### 👀 Severity

Low

**Comment by daugerdas** [comment]
Label placement issue should be fixed (https://github.com/wix/wix-style-react/pull/6392)
