### ISSUE TITLE
Bug: InputWithOptions wrapped with Tooltip causes multiple tooltips

### ISSUE THREAD

**Issue by zivl** [wix/wix-style-react#6365]
# 🐛 Bug Report

### 🏗 Relevant Components
`<Tooltip>`, `<InputWithOptions>`, `<Search>`

### 😯 Current Behavior
Writing the following code results in tooltip not properly attached component
```javascript
<Tooltip content={'x'}>
  <InputWithOptions />
</Tooltip>
```
![image](https://user-images.githubusercontent.com/4571570/101474211-7f8dcb80-3953-11eb-99fa-84084a6455df.png)

  - **WSR version**: `^9.28.0`
  - **Yoshi version**: `^4.276.0`

### 👀 Severity
Major

**Comment by EgoziE** [comment]
Moved to Jira - closing
