### ISSUE TITLE
NumberInput steppers dont work when using onBlur

### ISSUE THREAD

**Issue by zeevgg** [wix/wix-style-react#6435]
# 🐛 Bug Report

### 🏗 Relevant Components
NumberInput

...

### 😯 Current Behavior

when using onBlur instead of onChange, steppers (arrows) dont work

### 🤔 Expected Behavior

increase /decrease value

### 👣 Steps to Reproduce
create numberInput with onBlur event

  - **WSR version**: `9.57.0`
  - **Yoshi version**: `...`

### 👀 Severity

-  Major

**Comment by EgoziE** [comment]
solved

**Comment by EgoziE** [comment]
I don't see a problem - talk to me in private if needed - closing
