### ISSUE TITLE
<RadioGroup /> puppeteer testkit - `check` not working

### ISSUE THREAD

**Issue by tomershk** [wix/wix-style-react#6444]
# 🐛 Bug Report

### 🏗 Relevant Components

`<RadioGroup>`
`<RadioButton>`

...

### 😯 Current Behavior

When trying to `check` a radio button, Using:
1. radioGroup.selectByIndex(index);
2. radioButton.check();

getting the following error:
`Node is either not visible or not an HTMLElement`

...

### 🤔 Expected Behavior

Should `check` the radio button

...

### 👣 Steps to Reproduce

Example code for component:
https://www.wix-style-react.com/?path=/story/introduction-playground--playground&snippet=9960759a-9622-427e-9b6e-a054f36bc607

Example code for test:
```
const radioGroup = await RadioGroupTestkit({
      dataHook: `title-suggestions`,
      page: _page,
    });
    const radio = await radioGroup.getRadioAtIndex(1);
    await radio.check();
```

  - **WSR version**: `9.57.0`
  - **Yoshi version**: `4.1.0`

### 👀 Severity

- Critical / *Major* / Low

**Comment by EgoziE** [comment]
Moved to Jira - closing
