### ISSUE TITLE
<AddItem /> tooltip on a disabled <AddItem /> doesn't disappear

### ISSUE THREAD

**Issue by morsh** [wix/wix-style-react#6445]
# 🐛 Bug Report

### 🏗 Relevant Components
`<AddItem />`
...

### 😯 Current Behavior
When `<AddItem />` is disabled, and with tooltip, like so:

```
<Tooltip {...}>
  <AddItem disabled={true} />
</Tooltip />
```
![image](https://user-images.githubusercontent.com/5322722/103174945-00632780-486f-11eb-9d33-80e2d1799f18.png)

...

### 🤔 Expected Behavior

Tooltip should be hidden on mouse leave

...

### 👣 Steps to Reproduce

  - **WSR version**: `1.2069.0`
  - **Yoshi version**: `^4`

### 👀 Severity

- Critical

**Comment by morsh** [comment]
@EgoziE - FYI, I think you solved this

**Comment by EgoziE** [comment]
Fixed - https://github.com/wix/wix-style-react/pull/6449
