### ISSUE TITLE
<RadioGroup> - label not getting full width of parent

### ISSUE THREAD

**Issue by tomershk** [wix/wix-style-react#6480]
# 🐛 Bug Report

### 🏗 Relevant Components

- `RadioGroup`

...

### 😯 Current Behavior

When adding a component as child of `RadioGroup.Radio` it doesn't get the parent full width

### 🤔 Expected Behavior

Should get parent full width

### 👣 Steps to Reproduce

Playground [link](https://www.wix-style-react.com/?path=/story/introduction-playground--playground&snippet=a25e708b-5f07-4733-a019-1fcbabb68cda)
  - **WSR version**: `9.57.0`
  - **Yoshi version**: `4.1.0`

### 👀 Severity

- Major

**Comment by EgoziE** [comment]
Moved to Jira - closing
