### ISSUE TITLE
Dropdown options are shown in Helvetica instead of Madefor

### ISSUE THREAD

**Issue by sasha-kashcheyev** [wix/wix-style-react#6525]
# 🐛 Bug Report

### 🏗 Relevant Components

* Dropdown
* DatePicker

And other components rendering some sort of popovers.

### 😯 Current Behavior

Popovers of Dropdowns, DatePickers are rendered in Helvetica if `appendTo` is set to `window`.

### 🤔 Expected Behavior

Popovers of Dropdowns, DatePickers are rendered in Madefor.

### 👣 Steps to Reproduce

It happens on AngularJS page that uses [ngReact](https://github.com/ngReact/ngReact) to include React components in it.

To see it live:
1. Enable `specs.bookings.Madefor` experiment.
1. Follow [this link](https://manage.wix.com/dashboard/7f9cc7ac-74b7-44dd-a811-7c8cab58fdd6/bookings/scheduler/owner/calendar?referralInfo=sidebar).
1. In the top right corner of the page, press "Add sessions" -> "Class sessions".

You will see that most controls in the opened modal are in Madefor, but if you open any dropdown, its options are displayed in Helvetica. 

  - **WSR version**: `9.60.1`
  - **Yoshi version**: `4.294.0`

### 👀 Severity

- Major

**Comment by EgoziE** [comment]
Moved to Jira - closing

**Comment by sasha-kashcheyev** [comment]
> Moved to Jira - closing
Great news :)
@EgoziE could you send me a link to the Jira ticket please?

**Comment by EgoziE** [comment]
https://jira.wixpress.com/browse/DSM-1469
