### ISSUE TITLE
`<Checkbox/>` hover state not working when checked

### ISSUE THREAD

**Issue by b3llash** [wix/wix-style-react#6530]
# 🐛 Bug Report

### 🏗 Relevant Components
`<Checkbox/>`

### 😯 Current Behavior
No visual feedback when the user hovers the checkbox when checked/intermediate

### 🤔 Expected Behavior
Background color should change to `B20`

### 👣 Steps to Reproduce
Hover a checked/intermediate checkbox

  - **WSR version**: `9.65.0`

### 👀 Severity
Low

cc @tzachbon

**Comment by EgoziE** [comment]
Moved to Jira - closing
