### ISSUE TITLE
When there’s a lot of data in <Table/>, selecting checkboxes is slow

### ISSUE THREAD

**Issue by zeevgg** [wix/wix-style-react#6545]
# 🐛 Bug Report

### 🏗 Relevant Components

<Table/>

...

### 😯 Current Behavior

When there’s a lot of data in `<Table/>`  selecting checkboxes is slow

...

### 🤔 Expected Behavior

not to be slow

...

### 👣 Steps to Reproduce

create a table with 2k lines
try to select checkboxes

I was able to recreate in playground (it takes some time to load):
https://www.wix-style-react.com/?path=/story/introduction-playground--playground&snippet=0e7bcea4-75a3-49ac-a4b2-949d8a208d19

  - **WSR version**: `9.65.0`
  - **Yoshi version**: `...`

### 👀 Severity

- Major

**Comment by EgoziE** [comment]
Moved to jira - closing
