### ISSUE TITLE
Popover items break to new line even when maxWidth is bigger than content

### ISSUE THREAD

**Issue by rudnitskih** [wix/wix-style-react#6603]
# 🐛 Bug Report

### 🏗 Relevant Components

`<PopoverMenu />`, `<PopoverMenu.MenuItem />`

### 😯 Current Behavior

Details: https://wix.slack.com/archives/C39FTGUBZ/p1607620745178400

### 🤔 Expected Behavior

PopoverMenu respects `maxWidth` and don't break items into multilines when `showArrow={false}`

### 👣 Steps to Reproduce

https://www.wix-style-react.com/?path=/story/introduction-playground--playground&snippet=a491f8c2-a6cf-49e3-a32f-aea85baa958d

  - **WSR version**: `9.69.0`
  - **Yoshi version**: `not relevant`

### 👀 Severity

- Low

**Comment by EgoziE** [comment]
We're removing all Github issues
moving to Jira
Next issue please open under the DSM project thanks

**Comment by EgoziE** [comment]
DSM-1492

**Comment by rudnitskih** [comment]
Ok, I suggest to mention it in the template:

![image](https://user-images.githubusercontent.com/8848858/105160547-0ae4aa00-5b19-11eb-8a0e-0aef911f17f3.png)
