### ISSUE TITLE
Suggest we use Falcon CI/Yarn workspaces & Yarn lock

### ISSUE THREAD

**Issue by wildcard** [wix/wix-style-react#6641]
- [ ] [Falcon CI Getting started (Internal)](https://github.com/wix-private/falcon-ci/blob/master/docs/getting_started.md) 

- [ ] [Lerna ❤️ yarn workspaces ](https://github.com/lerna/lerna/blob/main/commands/bootstrap/README.md#--use-workspaces)

- [ ] [yarn.lock](https://classic.yarnpkg.com/en/docs/yarn-lock/)

**Comment by wildcard** [comment]
see https://github.com/wix-private/falcon-ci/blob/master/docs/getting_started.md

**Comment by EgoziE** [comment]
@wildcard Please open a Jira ticket (DSM project)

**Comment by EgoziE** [comment]
I suggest you discuss this with our team through the slack channel first.
