### ISSUE TITLE
InputWithOptions onBlur bug

### ISSUE THREAD

**Issue by lbelinsk** [wix/wix-style-react#668]
onBlur is being called not only when loosing focus, but each time the mouse is being clicked, never mind where on the screen.

This prevents me from implementing some new feature in my app which is based on the fact that onblur should be called only when it is expected of it.

I took some time to investigate, and although I found it while using multiselect, It is happening in InputWithOptions.

When you click on the screen, onBlur will be called with undefined event, while when it is called when it should have been called, the event is not undefined.

@nirhart can this issue get hight priority? 
I will try to make some time to investigate more but I am not sure I will get to it.

In order to reproduce, go to storybook and pass onBlur with console log in the InputWithOptions.

Thanks!

**Comment by Varnius** [comment]
What is the exact expected behavior? Fire onBlur only when nested text input loses focus OR also including such cases when you open up the dropdown and either click outside or pick an option there? In the latter case the actual focused element atm is not text input but rather whole container div.
@lbelinsk

**Comment by lbelinsk** [comment]
Hmm I think that if you have `shouldCloseOnSelect` prop set to true than you should loose focus (call onBlur).

`shouldCloseOnSelect` = true only in multiSelect (can reproduce it in guineapig add experiment form).

It should call onBlur every time you are focused (the dropdownLayout options are open) and then the dropdownLayout get closed, either if it is by pressing `ESC`, clicking outside or pressing tab twice..

**Comment by lbelinsk** [comment]
@Varnius

**Comment by Varnius** [comment]
@lbelinsk Ok, I'm assigning this one to myself.

**Comment by lbelinsk** [comment]
@Varnius thanks!
