### ISSUE TITLE
tooltip broken for ModalPreviewLayout

### ISSUE THREAD

**Issue by ofiratt** [wix/wix-style-react#6779]
# 🐛 Bug Report

### 🏗 Relevant Components

There is an issue with ModalPreviewLayout

### 😯 Current Behavior

tooltip is unreadable and looks bad 
### 👣 Steps to Reproduce

https://www.wix-style-react.com/?path=/story/introduction-playground--playground&snippet=47cc4271-0da3-46a0-8c4b-912b794f40b6

  - **WSR version**: `9.82.0`
  - **Yoshi version**: `4.317.2`

### 👀 Severity
Major

**Comment by EgoziE** [comment]
Hey @ofiratt 
We no longer use GitHub for issues, please open a Jira ticket through this link - http://wix.to/i0DYB4w
