### ISSUE TITLE
enhance tooltip driver

### ISSUE THREAD

**Issue by lbelinsk** [wix/wix-style-react#688]
The getContent method in the driver is too simple. In some cases you can't get the whole text because we are looking for the first element in it.

For example:

```
const content = 
   <div>
       <div>first line</div>
       <div>second line</div>
   </div>;

<Tooltip content={content}/>
```

The getContent() will bring "first line" and there is no way to get the second line.

A possible fix will be to remove the while loop here, but I am not sure if this will harm existing projects.

https://github.com/wix/wix-style-react/blame/master/src/Tooltip/Tooltip.driver.js#L31

**Comment by lbelinsk** [comment]
@amiryonatan If you already created the testkit for it, please make sure that we support this

**Comment by liorzisman** [comment]
@lbelinsk from discussion with @amiryonatan it seems the current version of `getContent` returns the content correctly
