### ISSUE TITLE
FieldWithSelectionComposite layout bug?

### ISSUE THREAD

**Issue by InYourDreamz** [wix/wix-style-react#690]
I can't seem to get it to look like how it is in the storybook. Please refer to the screenshot.

![screen shot 2017-08-08 at 3 15 14 pm](https://user-images.githubusercontent.com/11990210/29060491-9a912700-7c4c-11e7-81a3-078c04da93c8.png)

Here's how it's supposed to look like

![screen shot 2017-08-08 at 3 20 10 pm](https://user-images.githubusercontent.com/11990210/29060607-1904b156-7c4d-11e7-87e8-a406b29945ad.png)

**Comment by lbelinsk** [comment]
Hey,
Did you try to use the "copy to clipboard"  feature?

![image](https://user-images.githubusercontent.com/18248989/29065874-3319e67c-7c36-11e7-9e7d-ffac67d97d07.png)


```
<FieldWithSelectionComposite info="">
  <Label appearance="T1.1">
    Field With Selection Label
  </Label>
  <Input
    errorMessage=""
    helpMessage=""
    maxLength={524288}
    size="normal"
    textOverflow="clip"
    theme="normal"
    width="initial"
  />
  <InputWithOptions
    closeOnSelect
    dropDirectionUp
    dropdownOffsetLeft="0"
    dropdownWidth={null}
    errorMessage=""
    helpMessage=""
    inputElement={<Input errorMessage="" helpMessage="" maxLength={524288} size="normal" textOverflow="clip" theme="normal" width="initial"/>}
    maxHeightPixels={260}
    maxLength={524288}
    onSelect={function (){}}
    options={[
      {
        id: 1,
        value: '1'
      },
      {
        id: 2,
        value: '2'
      }
    ]}
    selectedId={1}
    size="normal"
    tabIndex={1}
    textOverflow="clip"
    theme="normal"
    valueParser={function (){}}
    width="initial"
  />
</FieldWithSelectionComposite>
```

The story book displays the component with respect to the visible code. If you did try to copy paste this snippet then my guess is that you have some wrapping styles that causes the bad behaviour.

Let me know if you still can't get it to look like you expect..

**Comment by InYourDreamz** [comment]
Yeap, it's the same code. 

I'm using version 1.1.2880 btw

`import FieldWithSelectionComposite from "wix-style-react/Composite/FieldWithSelectionComposite/FieldWithSelectionComposite";`

**Comment by lbelinsk** [comment]
So in that case I would guess there is some wrapping class, with fixed width or something that causes that.

The best thing will be to isolate this component and to see how it behaves in a sterile location, just like you see in the code sniipet in the documented example. If there will still be a problem we can try and reproduce it together.

**Comment by InYourDreamz** [comment]
Isolating it doesn't seem to solve the issue. Anyways, gotta move on so we created our own one.
