### ISSUE TITLE
Allow to click on the calendar without closing it

### ISSUE THREAD

**Issue by lbelinsk** [wix/wix-style-react#703]
Hey, I have opened an issue at react-datepicker:
https://github.com/Hacker0x01/react-datepicker/issues/989

I suggested there to add a pr to solve the problem there.

@tomerla @iluxav @nirhart 

Once this will be solved there we are good to go with the original plan. I have a local example for cashier needs that is wip.

**Comment by tomerla** [comment]
tnx @lbelinsk !

**Comment by lbelinsk** [comment]
Pr is ready: https://github.com/Hacker0x01/react-datepicker/pull/992
Hope they will merge that soon

**Comment by lbelinsk** [comment]
Merged!
After updating the version we can pass ```shouldCloseOnSelect``` prop

**Comment by tomerla** [comment]
Amazing!
tnx for the update :)
