### ISSUE TITLE
Add suffix to Dropdown

### ISSUE THREAD

**Issue by lbelinsk** [wix/wix-style-react#753]
```
<Dropdown
              options={options}
              value={value}
              onSelect={obj => onChange(obj.value)}
              suffix={<Input.Unit value="%" }
              />
```

Will not look good:

![image](https://user-images.githubusercontent.com/18248989/29749730-9ceb05f4-8b3b-11e7-80aa-eb0f41f6fd01.png)

**Comment by nirhart** [comment]
Why would you want to add suffix to the dropdown itself? shouldn't it be on the value?

**Comment by lbelinsk** [comment]
I can add it each time to the value, but thought it will be better for this.
I have a list of numbers, and I would have to concat "%" to the value just for display it to the user. behind the scenes I don't need the "%" in the stored value, I thought this is what the suffix for..

![image](https://user-images.githubusercontent.com/18248989/29750150-51a1b982-8b43-11e7-82fe-bb4e3b9509d8.png)

Here is a good example when I used an input (not dropdown) with suffix to display the "%":

![image](https://user-images.githubusercontent.com/18248989/29750171-ca8862a6-8b43-11e7-9785-121f292d32f7.png)

I would expect the dropdown to allow the same funcunality..
