### ISSUE TITLE
popover menus duplication

### ISSUE THREAD

**Issue by lbelinsk** [wix/wix-style-react#812]
We have 2 almost identical components:
https://github.com/wix/wix-style-react/blob/master/src/PopoverMenu/PopoverMenu.js
https://github.com/wix/wix-style-react/blob/master/src/Backoffice/PopoverMenu/PopoverMenu.js

This is because there was some intention to migrate to a new tooltip.
End result, not sure when and if we will move to the new tooltip, but in any case we can't leave this duplication.

**Comment by nirhart** [comment]
done
