### ISSUE TITLE
Can't use messageBoxFunctionalLayoutTestkitFactory enzyme driver

### ISSUE THREAD

**Issue by danielagreen** [wix/wix-style-react#817]
### Summary:
When rendering a Modal and under it MessageBoxFunctionalLayout, cant reach the MessageBoxFunctionalLayout driver (unit test).
(Seems to be related with enzyme disability to render portal components:
https://github.com/airbnb/enzyme/issues/252)

### Priority:
- [x] Normal

### Steps to reproduce:
 1. render this component: 
`<Modal
        dataHook="coupon-modal"
        contentLabel="sdfsdfds"
        isOpen={this.props.isOpen}
        onRequestClose={close}
        scrollable={false}>
        <MessageBoxFunctionalLayout title="title" dataHook="coupon-modal-message-box" />
      </Modal>`

2. #### in the driver:
`import {modalTestkitFactory, messageBoxFunctionalLayoutTestkitFactory} from 'wix-style-react/dist/testkit/enzyme';`

`public get = {`

    modalTestkitFactory: () => modalTestkitFactory({wrapper: this.component, dataHook: 'coupon-modal'}),
    messageBoxFunctionalLayoutTestkitFactory: () => messageBoxFunctionalLayoutTestkitFactory({
      wrapper: this.component,
      dataHook: 'coupon-modal-message-box'
    })
  `};`

3. #### in the test:
`driver.get.modalTestkitFactory().isScrollable()` works!
`driver.get.messageBoxFunctionalLayoutTestkitFactory().getTitle()` doesnt work

## Result
when trying to use messageBoxFunctionalLayoutTestkitFactory testKit functions, nothing works

### Relevant Components:
Modal
MessageBoxFunctionalLayout

# Workaround:
#### in the driver:
dont use the messageBoxFunctionalLayout enzyme driver.
instead do: 

`import {messageBoxFunctionalLayoutTestkitFactory} from 'wix-style-react/dist/testkit';`

and use like this:

      ` messageBoxFunctionalLayoutTestkitFactory: () => messageBoxFunctionalLayoutTestkitFactory({
        wrapper: document.body,
        dataHook: 'coupon-modal-message-box'
      });`

**Comment by shlomitc** [comment]
This is an old issue and looks like the "workaround" as suggested here, is currently the actual solution.

We updated the `Modal`'s Testkit section with an explanation on how to test this scenario.
