### ISSUE TITLE
disabled breadcrumb should not display cursor hover

### ISSUE THREAD

**Issue by aryelu** [wix/wix-style-react#822]
### Priority:
- [ ] Blocker
- [ ] Urgent
- [x] Normal
- [ ] Minor

### Steps to reproduce:
 1. add breadcrumbs with disabled prop
### Expected behavior:
No cursor:hover

**Comment by lbelinsk** [comment]
I don't see the problem..
In storyBook i added disabled and there is no hover.
![image](https://user-images.githubusercontent.com/18248989/30419514-4eb7043e-993f-11e7-85e2-71148264abc7.png)

Maybe you are using custom Items? then it is up to you to take care of the classes..
