### ISSUE TITLE
Tooltip won't work on a disabled button

### ISSUE THREAD

**Issue by shahafan** [wix/wix-style-react#832]
### Summary:
When trying to add a tooltip to a disabled button it doesn't work.

    <Tooltip textAlign="left" placement="left" alignment="center" content="test" maxWidth="250px">
        <Button theme="fullblue" onClick={() => console.log('clicked')} disabled={true}>
            Text
       </Button>
    </Tooltip>

### Priority:
- [x] Normal

### Expected behavior:
tooltip should be displayed when hovering

### Relevant Components:
Tooltip , Button

**Comment by lbelinsk** [comment]
@amiryonatan could you please check that in the new planned Tooltip we don't have this issue. If so, you can close this one

**Comment by Faradey27** [comment]
@lbelinsk looks like the problem is related to Button and not to Tooltip

https://github.com/wix/wix-style-react/blob/master/src/ButtonLayout/ButtonLayout.scss#L823 - root of problem, i am working on fix

**Comment by Faradey27** [comment]
https://github.com/wix/wix-style-react/pull/1855
