### ISSUE TITLE
Problems with AutoCpmpleteInput. Urgent..

### ISSUE THREAD

**Issue by lbelinsk** [wix/wix-style-react#85]
- [ ] The AutoComplete Literally doesn't auto complete... it suggests all the options without any dependency in the inserted text.

- [ ] According to the API, AutoComplete receives onSet props. the current implementation is problematic since it can't be tested. when i try to trigger an 'change' event this obviously doesn't work. there is no such event as 'set' which can be triggered in the test.
This is blocking me since I can't write no test which uses this component..

- [ ] Need A testkit for this component

**Comment by 3LOK** [comment]
1. This is a CONTROLLED (!!!) component - meaning, all state & algorithms are external. It will suggest what you give in the  'suggestions' property. It's up to the using component to listen to the onChange property and change the 'suggestions' prop (for example, GoogleAddressInput).

2 + 3 - Seems like the same issue - testkit needed.

**Comment by shahata** [comment]
@yoava do you think we should have an option to pass a data source (for example array of strings) so that the component will perform the filtering internally and calculate the suggestions on its own? or is this a different component?

Regarding point #2 I think this is just a misunderstanding, onChange wasn't documented and I think Lior thought he can only use onSet to get the value which obviously doesn't help

**Comment by lbelinsk** [comment]
I have just created a PR with a fix to the story book controlled component example..

Regarding 1: I think that a user would prefer to pass dataSource and expect that the displayed suggestions will get updated with respect to it's search word.

You can see it here in Material-UI component library:
http://www.material-ui.com/#/components/auto-complete

Unless there is a specific usage which I am not aware of, I think that it is a bit annoying to use the AutoComplete like I am using it now in the story book example:

`render() {`
  `  const onSet = value => this.setState({value: value.text});`
 `   const predicate = element =>`
`      this.state.value ?`
  `    element.text.toLowerCase().indexOf(this.state.value.toLowerCase()) !== -1 :`
  `    true;`

 `   return (`
   `   <AutoCompleteInput {...this.props} suggestions={suggestions.filter(predicate)} 
      `     value={this.state.value} onChange={onChange} onSet={onSet}/>`
    `);`
 ` }`

This can be the default behaviour of an AutoComplete, and if some user would want to use a custom predicate, he can send it as an optional props..

**Comment by 3LOK** [comment]
Guys, this is not the way you write React. React uses dumb, controlled components for various reasons, mainly regarding the separation of 'logic' and 'views'. 

Please do not change the AutoComplete itself. We use it as a dumb component, using selectors to show specific suggestions based on different logics we have from data stored in the store.

If you want to have a "React-abomination" that will not be controlled, please do it in a different component.

**Comment by lbelinsk** [comment]
The AutoComplete component in the Material-UI library is a controlled component..

Since you are using different logics I understand that this kind of component won't be useful. I think we should decide if it is needed to create another component which will have this default behaviour of a simple autocomplete because some users might be looking for this kind of simplicity.

I still didn't completely understand why a component which has a default behaviour of displaying the matched subString isn't considered as a controlled component.. It won't control it's own value. It will receive a value + onChange props which will be controlled by some parent component.
For example, I am using the AutoComplete inside some Form component which controls what happens in the form on subsequent user input.
The AutoComplete is an input form element whose value is controlled by the form, which means that it is a controlled component.

Regarding 2: As Yoav was saying, A testkit will solve the problem. 
In the meantime it is possible to trigger onChagne and after that to trigger 'Enter key pressed' event in order to simulate onSet..

**Comment by lbelinsk** [comment]
In the following link they implement a AutoComplete which is similar to the one we have now..
 I looked into it and I understand Yoav's point. 

https://github.com/reactjs/react-autocomplete

Still, I think that the second option isn't an abomination (material-UI is using it).

**Comment by shahata** [comment]
@yoavaa I strongly disagree that it is an abomination, having an autocomplete component filter on it's own is no different than expecting drop down to open when you click it or expecting the cursor to blink in a text input when it is focused. Supporting this does not conflict with it being a controlled component, it is still a controlled component even if it filters on its own, what matters is that the source of truth of what value this component has comes from React.

I would much rather doing:
```jsx
<AutoComplete
  filter={AutoComplete.fuzzyFilter}
  dataSource={fruits}
  maxSearchResults={5}
/>
```

Instead of doing:
```jsx
<AutoComplete
  onUpdateInput={searchText => this.setState({searchText)}
  dataSource={fruits.filter(key => AutoComplete.fuzzyFilter(this.state.searchText, key)).slice(0, 5)}
/>
```

Note that both examples above are valid uses of material-ui and I think that it makes sense that we support both external filter and internal filter as they do.

**Comment by nirhart** [comment]
@shahata @lbelinsk I tend to agree with @3LOK about keeping logic and ui apart, drop down to open and cursor blinking is ui and a component should handle it by default IMO, however filtering is the component logic. I liked what reacjs did with https://github.com/reactjs/react-autocomplete where they provided the component along with utils.js where they added some filters, so the component is pretty simple:

```javascript
<Autocomplete
          value={this.state.value}
          inputProps={{name: "US state", id: "states-autocomplete"}}
          items={getStates()}
          getItemValue={(item) => item.name}
          shouldItemRender={matchStateToTerm}
          sortItems={sortStates}
          onChange={(event, value) => this.setState({ value })}
          onSelect={value => this.setState({ value })}
          renderItem={(item, isHighlighted) => (
            <div
              style={isHighlighted ? styles.highlightedItem : styles.item}
              key={item.abbr}
            >{item.name}</div>
          )}
/>
```
Material did something similar, however, they provided the filters inside the AutoComplete.js (caseInsensitive, caseSensitive, fuzzy...) and added a default exactly exactly like caseSensitiveFilter, so they actually duplicated it. 
I would go here on a separation to 2 files, a component and a utils file for it. I also don't think that we should provide a default filter, I would make this prop isRequired and in our example we can show how we add a simple filter from our utils

**Comment by shahata** [comment]
@nirhart @3LOK You got it the other way around, LOL. react-autocomplete does the exact same thing as material-ui, they just call the prop in which you pass the filter function `shouldItemRender` while material-ui call it `filter`. I'm now even more convinced that this is the way to go.

See the example above that Nir pasted, it passes a static list of all states in `items` and an additional prop `shouldItemRender` with a filter function which the component then calls to decide what items to present.

Regarding defaults I agree that the default filter function should be `() => true`.

**Comment by shahata** [comment]
If we all agree that we should add an optional `filter`/`shouldItemRender` prop which is `(searchText, item) => true` by default, then I think everyone will be happy.

**Comment by 3LOK** [comment]
I don't agree. Please do it as a separate component
(FilteredAutoComplete?).

I would like the basic AutoComplete to remain dumb and fully controlled.

**Comment by shahata** [comment]
No problem, we can do a separate component, but notice how all examples that were brought here allow to pass a filter function, I really don't see how that makes them less controlled.

**Comment by nirhart** [comment]
I don't see how I got it the other way around, of course both of them allow passing a filter function, this is still controlled, the filter function is coming from the wrapper, and we can provide them outside the component, I just think that any logic should be. a default of () => true seems fine.

I really don't want to build 2 components that are doing the same.

**Comment by shahata** [comment]
@nirhart you got it the other way around by agreeing with @3LOK which says passing a filter function means it is uncontrolled :P

**Comment by 3LOK** [comment]
But is uncontrolled!

React is about unidirectional flow. A callback that is called on a for loop
asking "should I show this?" is simply not unidirectional.

Let's just have two components and end this discussion please.

**Comment by shahata** [comment]
@3LOK think of it as passing a predicate and not a callback and it becomes unidirectional :P

**Comment by 3LOK** [comment]
But that's the exact issue - you don't pass predicates in React.

See here: [Thinking In React](https://facebook.github.io/react/docs/thinking-in-react.html) (sent to me by @nirhart).

The ProductTable is 'AutoCompleteInput' - its stateless and clear - only displays the props it has received.

The FilteredProductTable is the vertical usage of ProductTable (or your FilteredAutoComplete) - It is separate component, that only holds state - you want to create such a component, knock yourself out, but do it SEPERATLY! (if for nothing, then for the sake of encapsulation and separation of concern - which is good practice irregardless to React)

**Comment by 3LOK** [comment]
Another advantage in seperation to two components (one smart and one dumb), is that I can wrap the dumb in a different smart component, but I can also give the smart component a different dumb component (for example, if I have AutoCompleteInput2 that looks completely different, I can still use the same FilteredAutoComplete with it).

**Comment by shahata** [comment]
I don't have a problem with creating a separate component, my problem is with you calling it an abomination ;)

**Comment by 3LOK** [comment]
That's ok, I think Batata French Fries are abominations. It has good company.

**Comment by lbelinsk** [comment]
The new InputWithOptions + DropdownLayout solves this issue.. A testkit was also added for this components (even to AutoComplete component)
