### ISSUE TITLE
Add Header component

### ISSUE THREAD

**Issue by lbelinsk** [wix/wix-style-react#855]
This header is implemented in wix restaurants dashboard:
![image](https://user-images.githubusercontent.com/18248989/30804625-ca6069e4-a1f6-11e7-92d4-cfd27daf72b9.png)

Tasks:

- [ ] Get spec from Ben

- [ ] Migrate it to wix-style-react

**Comment by lbelinsk** [comment]
@shahata

**Comment by argshook** [comment]
i think it shouldn't be a "header" component but a component which knows how to keep content at correct position if and when user scrolls.

then we can wrap inside whatever content we want (breadcrumbs, buttons etc) and be done.
documentation would show proper examples of various wix approved "header" implementations using this component.

if we think of this as a header we might end up in props hell or nonsensical components (e.g. <Header.Breadcrumbs/>, <Header.ButtonsRight/> etc).

bootstrap called such things "affix" some time ago.

**Comment by shahata** [comment]
I think first step is to move what @giladartzi created into wix-style-react, then we can debate any needed changes if at all.

**Comment by lbelinsk** [comment]
@giladartzi any kind of estimation for this one?

**Comment by argshook** [comment]
fyi, @amiryonatan started to work on this at #1101

**Comment by lbelinsk** [comment]
duplicated. We have a basic Page component and Amir is continuing to work on this
