### ISSUE TITLE
inputWithOptions doesn't show selected option

### ISSUE THREAD

**Issue by Noam3kCH** [wix/wix-style-react#859]
### Summary:
when selecting an option the selection isn't shown

### Priority:
- [ ] Blocker
- [ ] Urgent
- [x] Normal
- [ ] Minor

### Steps to reproduce:
 1. https://wix.github.io/wix-style-react/?selectedKind=Core&selectedStory=InputWithOptions&full=0&down=0&left=1&panelRight=0
 2. click on the carret
 3. select an option

### Expected behavior:
should show the selected option in the input

### Relevant Components:
inputWithOptions

**Comment by lbelinsk** [comment]
@Noam3kCH This is not a bug, just a stupid documentation idea.
You probably tried the "unControlled" story, which doesn't demonstrate anything :)

Try the one at the bottom "Controlled".

Appreciate that you opened a ticket for it!
