### ISSUE TITLE
FieldWithSelection - propagate onFocus callback on Input

### ISSUE THREAD

**Issue by alex5il** [wix/wix-style-react#860]
Right now the callback `onFocus` on `<Input />` in `<FieldWithSelection/>` doesn't work since  `<FieldWithSelection/>`component overrides the prop to use his own of focus.

In order to fix this issue we need to do something similar as i did with the `onBlur` here :
https://github.com/wix/wix-style-react/pull/852#pullrequestreview-64852386

There is a bug with `onFocus` in `<Input/>` when you call `focus()` explicitly which calls the `onFocus` callback twice instead of once.

**Comment by shlomitc** [comment]
we decided to deprecate this component in favor of stacked inputs - see more here #2869

closing
