### ISSUE TITLE
Testkit driver for RadioGroup returns null when calling getSelectedValue with it's type set to button

### ISSUE THREAD

**Issue by joncys** [wix/wix-style-react#861]
### Summary:
Testkit driver for `RadioGroup` returns `null`, when calling `getSelectedValue` with type set to `button`.

### Priority:
- [ ] Blocker
- [ ] Urgent
- [ ] Normal
- [x] Minor

### Steps to reproduce:
 1.
```
<RadioGroup dataHook="tomato-potato-salmon" value={ true } type="button">
  <RadioGroup.Radio value={ true }>true</RadioGroup.Radio>
  <RadioGroup.Radio value={ false }>false</RadioGroup.Radio>
</RadioGroup>
```
 2.
```
// returns null
radioGroupTestkitFactory({ wrapper, dataHook: 'tomato-potato-salmon' }).getSelectedValue();
```
 3. sob 😢

### Expected behavior:
Returns `'true'` in the above case

### Relevant Components:
`RadioGroup`, `RadioGroup.Radio`

#### Thanks a lot!
No problemo!

**Comment by shlomitc** [comment]
type button is planned to be removed, so it will not be fixed. closing
