### ISSUE TITLE
Support predicate in testkits

### ISSUE THREAD

**Issue by lbelinsk** [wix/wix-style-react#877]
Add an optional predicate prop that should allow users to locate their component as they wish.

```
InputDriverTetkitFactory({wrapper, dataHook});
```

will support also customLocator (or better name):
```
InputDriverTetkitFactory({wrapper, customLocator: () => {//returns the element}});
```

or even without the wrapper..

@hesher

**Comment by shlomitc** [comment]
won't be added. PullRequest are always welcome
