### ISSUE TITLE
define correct way of targeting specific components

### ISSUE THREAD

**Issue by argshook** [wix/wix-style-react#883]
this is a continuation of discussion in #856 

currently the preferred way to target components is by using `data-hook`s. this yields a problem, however, when a specific, one of many, component needs to be targeted. options are:

- use unique, no whitespace `data-hook` (possible to do now, need to define convention)
- allow multiple "data hooks" within `data-hook` attribute e.g. `data-hook="item index=0"`
- do something else?

personally i think `data-hook` should be simple no whitespace strings with no additional expression or meaning. for lists of items, when each has `data-hook` of `item-1`, `item-2` etc.:

- target all with `[data-hook*="item"]`
- target specific with `[data-hook="item"]`

but perhaps this doesn't cover all cases.

@skyiea @lbelinsk

**Comment by lbelinsk** [comment]
From a user's point of view, I think that if he has:

production.js
```
<Input dataHook="my-input"/>
<Input dataHook="my-input"/>
```

test.spec.js:
```
inputTestkitFactory({dataHook: 'my-input', wrapper})[0].enterText('ble');
//Or even:
inputTestkitFactory({dataHook: 'my-input', wrapper}).at(0).enterText('ble');

```

I think it can be nice that our testkit infrastructure will return one element or array of elements.

I like it better then a complex data-hooks with seperators.

**Comment by argshook** [comment]
so after some time passed and nothing happened, im closing.

let's not complicate, data-hook must contain unique value and `*=` attribute selector can be used to get something like `my-input-1`, `my-input-2` etc.
