### ISSUE TITLE
Title prop in Input Amaterial theme

### ISSUE THREAD

**Issue by lbelinsk** [wix/wix-style-react#909]
### Summary:
Input Amaterial theme needs to handle cases when a long title prop is provided.

![image](https://user-images.githubusercontent.com/18248989/31277764-305bcc22-aaab-11e7-985a-e01d31d1966b.png)

Maybe some horizontal scroll?
The horizontal scroll should start before it will overlap with the error suffix icon.

### Priority:
- [ ] Blocker
- [x] Urgent
- [ ] Normal
- [ ] Minor

### Steps to reproduce:
 1. Render `<Input theme="amaterial" title="some very long title"/>`

### Expected behavior:
The title will not overflow to the right. Instead, we will have horizontal scroll.

### Relevant Components:
Input
### Additional notes:
Being used by account recovery: https://github.com/wix-private/account-recovery/issues/164

**Comment by argshook** [comment]
nooo not the scroll!

just use shorter translation. on top "your contact form email" with an asterisk (*) on the bottom further explanation, "type only if you have contact form". content people know how to shorten such places.

also in this screenshot i see plenty of space on left and right, input title is not clipped.

with scroll we'll create further problems (e.g. scrollbar? if visible, then affects UI (different crossbrowser). If not, how do i know i need to scroll? some gradient? if so, then animation for it? should we test scrolling title?)

let's not hide content unnecessarily

**Comment by lbelinsk** [comment]
I agree, but this issue is coming back every time. Ideally, This should be solved by content writers, but in actual life, a QA (or me) going over the app, and accidentally locate such problem. The content writers apparently don't care enough to take a look how their content looks in the app.

The most important thing is to make the component robust enough to handle the content writers mistakes. I am open to other UX suggestions, but don't think we should solve it only by saying "this is content writer issue".

Maybe Ben could help. Why can't I tag him? How can we add him as a contributor? :)

**Comment by shlomitc** [comment]
Amaterial theme is not part of the design system. If becomes relevant, can be solved in the `wix-ui` context. closing
