### ISSUE TITLE
TPA TextLink has flaky e2e test

### ISSUE THREAD

**Issue by argshook** [wix/wix-style-react#925]
build is failing from time to time, need to investigate what causes the timeout.
![screenshot 2017-10-10 17 43 03](https://user-images.githubusercontent.com/4284659/31392673-8da18248-ade2-11e7-9f25-8e80ae9ef590.png)

**Comment by lbelinsk** [comment]
Deprecated component. we have it's e2e tests commented out, and it only a matter of time before wix-ui tpa will have it's own new component
