### ISSUE TITLE
remove moment.js dependency

### ISSUE THREAD

**Issue by argshook** [wix/wix-style-react#926]
we use `react-datepicker` which has `moment` as dependency.

`moment` js is too heavy for our needs, tends to be problematic and occasionally breaks our builds.

**Comment by shlomitc** [comment]
So its partially done. moment is still in use in the `TimePicker` component

**Comment by shlomitc** [comment]
that's low on priority as a standalone.
@mykas - take this into consideration when analyzing bundle size, maybe create a new issue just for bundle size reducing

**Comment by mykas** [comment]
Sure
