### ISSUE TITLE
Remove margin from the last element of RadioGroup

### ISSUE THREAD

**Issue by joncys** [wix/wix-style-react#927]
## Thanks for reporting an issue :)
You betcha!

### Summary:
Oh boy, I guess, you can't really change this anymore, because most probably everyone just relies on the margin being there and subtracts `12px` from the desired spacing, but having this just makes me a very very _very_ sad panda. 

Also, the OCD rage is barely bearable.

### Priority:
- [ ] Blocker
- [ ] Urgent
- [ ] Normal
- [x] Minor

### Steps to reproduce:
<img width="828" alt="screen shot 2017-10-11 at 15 52 27" src="https://user-images.githubusercontent.com/373939/31441634-6892184a-ae9c-11e7-9f09-565368604b27.png">

### Expected behavior:
I am to control my margins as I control my own destiny.

### Relevant Components:
`RadioGroup`

**Comment by argshook** [comment]
could you please clarify? you wish for `radiogroup:last-child { margin-bottom: 0 }`?

**Comment by joncys** [comment]
@argshook Yes. Because, there's no top margin for the `RadioGroup`, it is somewhat strange, that there's bottom margin (that results from the last item having that bottom margin, but still).

**Comment by argshook** [comment]
closed by #1687
