### ISSUE TITLE
Support default props in storybook autoExamples

### ISSUE THREAD

**Issue by lbelinsk** [wix/wix-style-react#932]
Hide the default props from the code snippet example because the user won’t need to provide them and when he will copy to clipboard he will pass them.

The dynamic story value should be initialized with the default value in the prop
and only if the user will change it then the prop will be added to the code snippet.

Also we should support the ...defaultProps syntax:

```
Component.defaultProps = {
   onSelect: () => {},
   ...OtherComponentDefaultProps
}
```

**Comment by argshook** [comment]
> Hide the default props from the code snippet example because the user won’t need to provide them and when he will copy to clipboard he will pass them.

this part is relevant for #933 which i almost have pushed.

the much more interesting part is improving `<AutoDocs/>` so that it can understand and properly read spread operators.

**Comment by argshook** [comment]
im closing this because #945 & #958
