### ISSUE TITLE
Modify the object param for story() to get index of category and component

### ISSUE THREAD

**Issue by lbelinsk** [wix/wix-style-react#937]

**Comment by argshook** [comment]
@lbelinsk can you elaborate more on this? `story` supports `category` and `storyName`, should be enough i guess?

**Comment by lbelinsk** [comment]
I had a problem that I needed to supply storyName="3.8 Button" iirc.
If it is solved then you can close the issue

**Comment by argshook** [comment]
Story name is automated if you dont provide it, but in many cases it needs to be custom, thats why there is `storyName`
