### ISSUE TITLE
Look why storybook first loading started to take so much time

### ISSUE THREAD

**Issue by lbelinsk** [wix/wix-style-react#940]

**Comment by argshook** [comment]
short answer - bundle is too big (~6MB iirc), need to recheck what we include.

**Comment by argshook** [comment]
ok it's not 6MB, it's ~2.1 (still too much)

quick list of what we can do:

1. google api is loaded even if component in view does not need it (5 requests)
1. font load is blocking render, should be deferred (12 requests)
1. do not `import {component} from 'wix-style-react';` and do `import component from 'wix-style-react/component';` everywhere
