### ISSUE TITLE
Icons

### ISSUE THREAD

**Issue by milkyfruit** [wix/wix-style-react#961]
# Migrating internal icons in Wix-Style-React

The goal is to replace all internal imports from `src/Icons` with imports from `wix-ui-icons-common`.

This probably means release the next major version of `wix-style-react` as this is a breaking change

## Migrating an icon

* Find usages of `src/Icons` inside of `wix-style-react`, e.g.:

```shell
brew install sift
cd wix-style-react
sift --ext=js 'import.*Icons' src
```

* Open the local `wix-style-react` storybook and navigate to the component you want to update. Open https://wix.github.io/wix-style-react/ in another tab so that you have a reference for comparison.

* Pick an icon import you want to change, and find the appropriate icon replacement in [wix-ui-icons-common](https://github.com/wix/wix-ui/tree/master/packages/wix-ui-icons-common). The repo contains a storybook with all available icons, and you can also go to http://electric-process.surge.sh/ ([repo](https://github.com/wix-private/icons-wsr-to-wui)) to see the correspondence between old and new icons.

  If you have any design-related questions talk to Ben Benhorin ([wuwa](https://github.com/wuwa)) or Domas Markevičius ([milkyfruit](https://github.com/milkyfruit)).

* Replace the icon import in the component's JS file. Many of the new icons are smaller relative to their viewBox than the old ones, you will need to adjust the icon's width and height (and possibly other properties) in the component's CSS file to make it approximately the same size and position as the icon previously used.

* Create a PR without assigning reviewers. Some of the eyes tests will probably fail, don't approve them right away, wait until the PR is reviewed and ready to be merged, then approve right before merging.

### Checklist

* If the component comes in small/medium/large variant check that the icon scales correspondingly.

* Check the disabled, error, and hover state.

* Check the RTL mode. If the icon needs to change direction:
```css
:global(.rtl) .your-icon-classname {
  transform: scaleX(-1);
}
```

* Make sure that your changes didn't affect position and spacing of other elements in the component.

* Check that `npm run test` is green.

* After creating a PR make sure the CI tests are passing. They can fail due to eyes tests, make sure you're ok with the differences in rendering.

## PR Examples

* https://github.com/wix/wix-style-react/pull/1635
* https://github.com/wix/wix-style-react/pull/1616
* https://github.com/wix/wix-style-react/pull/1621

# Migration Guide for Consumers

(To be added to release notes once we are ready to remove `src/Icons`)

`wix-style-react` no longer exports icons from `wix-style-react/dist/src/Icons`. You will need to change imports to a new library [wix-ui-icons-common](https://github.com/wix/wix-ui/tree/master/packages/wix-ui-icons-common), e.g.:

```js
// Before
import ArrowLeft from 'wix-style-react/dist/src/Icons/ArrowLeft';

// After
import ChevronLeft from 'wix-ui-icons-common/ChevronLeft';
```

You can find a recommended replacement for each icon at http://electric-process.surge.sh/

Many of the new icons [are smaller](https://jsfiddle.net/xxf9hxwc/) relative to their viewBox, so you will probably need to adjust CSS.

Also, icons no longer automatically flip horizontally when the're inside of a container with `rtl` class. This is mostly relevant for `<` and `>` icons. If you want to flip them in RTL mode, you'll need to add something like this:

```css
:global(.rtl) .your-icon-classname {
  transform: scaleX(-1);
}
```

If you need an icon that is no longer available, you can copy it into your project from the previous version of `wix-style-react`.

# Zeplin Docs

**1. General Use Icons**
Icons that are used by everyone.

They appear in:
- [Buttons](https://zpl.io/a7G5B8j)
- [Popover Menu](https://zpl.io/Vq1KXEm)

[**The List with Aliases**
](https://zpl.io/a3XmRm8)
[Folder with new set of icons
](https://drive.google.com/open?id=0B3MbBTg6SmtrTnNwWW9MbjRjRk0)

**2. _System Icons**
Icons that are designed exclusively for core elements

They appear in elements like:
- Checkbox
- Toggle
- Dropdown
- and [more](https://zpl.io/bo0DleZ)

These icons should be hidden from public and be visible only for developers who develop core elements.

[**The list with _System Aliases**
](https://zpl.io/2GErWrY)
[Folder with the set of icons](https://drive.google.com/drive/folders/0B3MbBTg6SmtrTzFoWWFYX1czcTQ?usp=sharing)

**Comment by lbelinsk** [comment]
Shlomi's comment in the email:
 "These icons should be hidden from public and be visible only for developers who develop core elements." - so this means we should remove it in the storybook or maybe display it only during development time.

We need to think of how to migrate existing icons without breaking projects."

**Comment by shlomitc** [comment]
Done
