### ISSUE TITLE
Ignore divider option in DropdownLayour testkit

### ISSUE THREAD

**Issue by lbelinsk** [wix/wix-style-react#964]
All testkit methods for dropdownLayout should ignore divider option when getting an option by index.

For example, 

```
const options = [
      {id: 1, value: 'Option 1'},
      {id: 2, value: 'Option 2'},
      {id: 3, value: '-'},
      {id: 4, value: 'Option 4'},
      {id: 5, value: '-'},
      {id: 6, value: 'Option 5'},
      {id: 7, value: customValue}
```

Trying to get option by index a user can accidentally click on a divider

**Comment by argshook** [comment]
i don't know, what if i actually want to target the divider?

**Comment by lbelinsk** [comment]
hmm, doesn't sound like something someone will want.
99.999% will do try to go to element[1] and will assume it will give them the second element, but currently, it will give them the first divider (see languagePicker, it has divider between each option)

**Comment by lbelinsk** [comment]
@amiryonatan I personally think that the divider pi we have today is not really nice.
A divider is not an option with value = "-".

This is something that also needs to be taken into consideration in the suggested solution, alongside header and footer.

**Comment by shlomitc** [comment]
I'm closing it as this is a breaking change with very minimal value. we might consider ignoring it in future refactors.
