### ISSUE TITLE
Changelog - Proper release cycle of the library

### ISSUE THREAD

**Issue by lbelinsk** [wix/wix-style-react#971]

**Comment by argshook** [comment]
i started tracking changes since https://github.com/wix/wix-style-react/pull/1112

todo:
* [ ] "toolify" package.json version bump
* [ ] use git tags
* [ ] use github releases

**Comment by lbelinsk** [comment]
@argshook As the leader of the manual releases, If there is something we need from here than please open a relevant issue in wix-ui, and close it here, since we will not do anything here anyway for wsr.

Don't invest time in this, if there are some stuff you think we should add then just open an issue for them.

So imo let's close this one, and after you apply manual releases in wix-ui, just open an issue for further improvements (if you see any)

**Comment by argshook** [comment]
👌  makes sense
