### ISSUE TITLE
define theming approach

### ISSUE THREAD

**Issue by argshook** [wix/wix-style-react#985]
a better theming mechanism is needed as we will need to support:

1. TPAs
2. Back office
3. mobile
4. editor
5. complete customization

currently we maintain dedicated folders with themed components. this vastly increases code duplication.

to avoid it we need to rethink architecture.

my high-level approach would be something like this:

* keep flat component structure
* all components support "theme" prop
* theme prop accepts object of shape relevant to component (properties same as classnames)
* support setting global theme (e.g. wrap with `<Theme/>` and work with `context`
* support extending/overriding theme properties through `theme` prop

for most cases - configure theme once and use same component as usual (not `backoffice/button`, just `button`)

for multitheme cases - use `<Theme/>` "provider" on different root components

for special cases - extend theme by giving it style object, perhaps created by some helper

**Comment by lbelinsk** [comment]
closing it and breaking into smaller issues, as this high level phase is over
