### ISSUE TITLE
DatePicker - hover color and dropdown opening

### ISSUE THREAD

**Issue by lbelinsk** [wix/wix-style-react#987]
- [ ] Month and year dropdown should open on the selected item, not like this:
![image](https://user-images.githubusercontent.com/18248989/31590425-9fcac954-b218-11e7-9198-fd6d27c0c2e8.png)
Also dropdown item hover is not in the right color (I think)

**Comment by shlomitc** [comment]
I think it looks ok now. select showYearDropdown and showMonthDropdown:
https://wix-wix-style-react.surge.sh/?selectedKind=3.%20Inputs&selectedStory=3.6%20DatePicker&full=0&addons=0&stories=1&panelRight=0

**Comment by argshook** [comment]
nope, still not okay. the issue is with dropdown lacking ability to focus selected option. When selected year is 2017 i expect dropdown to open with that year focused but instead it opens with `scrollTop = 0`

although issue is not with dropdown itself, it's with dropdown

**Comment by shlomitc** [comment]
Fixed
