### ISSUE TITLE
Breadcrumbs - wrong style for the Active breadcrumb

### ISSUE THREAD

**Issue by tomerla** [wix/wix-style-react#991]
### Summary:
Wrong style is applied to the **Active** breadcrumb

### Steps to reproduce:
 1. Go to biz mgr
 2. Go to Settings - Accept Payments tab

### Expected behavior:
Active tab will have a `cursor: text`

### Actual behavior:
Active tab has a `cursor: pointer`

### Additional notes:
There are 2 issues
1. I think that when using the `onClick` a **Button** style is applied
2. Current style for the **Active** breadcrumb is `cursor: default` (instead of `cursor: text`)

**Comment by lbelinsk** [comment]
@tomerla take a look in guineapig - https://guineapig.wix.com/home/new
The active link is not clickable.
It is with cursor: default, so I will fix the cursor issue.

See the code implementation for guineapig breadcrumbs usage:
https://github.com/wix-private/guineapig2/blob/2068f6a002028f86ed5cd228ea137266b5c64831/src/components/AppBreadcrumbs/AppBreadcrumbs.js#L53

**Comment by lbelinsk** [comment]
I looked into the zeplin and turns out that according to the spec, the cursor should be **pointer** :/
https://app.zeplin.io/project/5864e02695b5754a69f56150/screen/587603ea2d3c002b07d40624

![image](https://user-images.githubusercontent.com/18248989/31638005-0093eba0-b2da-11e7-864b-cf5b60cc374f.png

@wuwa can you approve?

@tomerla if this is not what your UX defined, please mention him here so he could be in the loop.

**Comment by wuwa** [comment]
yes, you are right, item is not linking anywhere so cursor should be normal. will fix the zeplin (there is a comment about this there).

**Comment by tomerla** [comment]
@lbelinsk I implemented the breadcrumbs using an `onClick` handler and I think that this is causing the issue for me:
https://github.com/wix-private/cashier-merchant-settings/blob/master/src/ui/components/HeaderBar/HeaderBar.js#L23-L27

you can check it on production:
1. Go to biz mgr
2. Go to Settings - Accept Payments tab

**Comment by lbelinsk** [comment]
@wuwa cursor should be default or text?

@tomerla I don't see how the onClick can cause the problem. I tried it on storybook by adding onClick and stuff, all looks regular.

I looked in the code, with or without the onClick, this is how your items get's rendered:
https://github.com/wix/wix-style-react/blob/master/src/Breadcrumbs/Breadcrumbs.js#L78

It behaves as expected in guineapig + storybook, so I will take a look tomorrow in the business manager to see what exactly do you mean.

**Comment by wuwa** [comment]
cursor: default

**Comment by lbelinsk** [comment]
@wuwa 
looked at the breadcrumbs we have on wix-stores, they use cursor: text.
So if this is the final decision then We should contact their UX.

**Comment by lbelinsk** [comment]
@tomerla second issue is dealt with, as I sent you the relevant details.
About the cursor, we will double check it and I will update you according to our decision.

For now we are up to date with the current spec file, so i am closing the issue.
