### ISSUE TITLE
rethinking dropdowns

### ISSUE THREAD

**Issue by argshook** [wix/wix-style-react#993]
currently we have many "dropdown" like components: `<Dropdown/>`, `<InputWithOptions/>`, `<AutoComplete/>`, `<GoogleAddressInput/>`, `<Multiselect/>`.

if you squint a little, not much difference is with `<PopoverMenu/>`, `<ButtonWithOptions/>`, `<IconWithOptions/>` and even `<Tooltip/>`

what do they all have in common?

all of them have something visible at all times.
that "something", when interacted with, displays another box nearby.

my proposal is to have one general approach for such behaviour which is
extendable enough to allow any behaviour (i guess looking similar to good 'ol bootstrap):

```js
import Dropdown from 'wix-style-react/Dropdown';

const MyDropdown = () =>
  <Dropdown>
    <Dropdown.Toggle>
      <ToggleComponent/>
    </Dropdown.Toggle>

    <Dropdown.Content>
      <DropdownMenu/>
    </Dropdown.Content>
  </Dropdown>;

// or even like this
const MyDropdown2 = () =>
  <Dropdown
    toggle={ToggleComponent}
    content={DropdownMenu}
  />
```

where:
 * `<ToggleComponent/>` is any component that receives, say, `toggle` function. Call it anytime you need to show/hide `<Dropdown.Content/>`.
 * `<DropdownMenu/>` is also any component that receives something similar as `<ToggleComponent/>` and so control of `<Dropdown>` is possible

of course more than just `toggle` is required. however, with this approach it's only one place to add/remove more functionality, so it's easy to implement and maintain.

all `Dropdown` needs to take care of is to show/hide whatever component at appropriate times and in correct location. `popper` can be used here as we already use this dependency in tooltip.

this issues is to brainstorm, at the moment there is no code for any of this. i came up to this point when thinking how to simplify `InputWithOptions`.

**Comment by shlomitc** [comment]
I like the first approach. Very declarative.

**Comment by lbelinsk** [comment]
I also like the first one better.
Instead of `toggle` we need to think of it as `onToggled` because this is more the react way (dataFlow is top to bottom, we pass a callback to be called on toggle, not a function that opens the options).

Let's add to this family the `IconWithOptions` and `LanguagePicker` which are similar. The only difference is the "trigger" event which is onMouseEnter instead of onClick.

I am not 100% convinced that there is code duplication between `IconWithOptions`, `ButtonWithOptions` and `InputWithOptions`, therefore I am not sure if we should create one component for all of them.

Input has a lot of keyboard events code which is not relevant for the button and icon.

**Comment by argshook** [comment]
> Instead of toggle we need to think of it as onToggle 

i beg to differ.

the idea is to create mechanism which doesn't care whether it's `onClick` that opens dropdown or `onMouseOver`, or something else.

`ToggleComponent` would be something like:

```js
const ToggleComponent = ({ toggle, ...otherProps }) =>
  <button onClick={toggle} className={otherProps.className}>
    Open Dropdown
  </button>;
```

`toggle` is available because `ToggleComponent` is a child of `Dropdown.Toggle`, it adds `toggle` function as prop.

if in above case `toggle` was named `onToggle`, the part with `onClick={onToggle}` wouldn't really make sense. `onClick={toggle}` is enough. i want to invoke action, not react to action. imagine together with `toggle` we also have e.g. `open`, `close`, `expand`, `resize`, `move` etc.

---

some duplication i saw is about dropdown direction (up or down) and show/hide logic.

---

i tend to second variant actually, because it's half the lines (5 vs 10) and has practically no area for guessing, only one way to use.

Heck, it can even be simple function, no `React.createElement`:

`createDropdown({ toggle: ToggleComponent, content: ContentComponent });`.

**Comment by milkyfruit** [comment]
#1200

**Comment by lbelinsk** [comment]
@amiryonatan you should probably read this.
Don't keep this open if you don't need it anymore, we will talk about it all in the demo anyway

**Comment by argshook** [comment]
@amiryonatan is working on something very similar, closing
