### ISSUE TITLE
`ltr` css class should not be mandatory

### ISSUE THREAD

**Issue by argshook** [wix/wix-style-react#999]
currently we [have some code](https://github.com/wix/wix-style-react/search?l=SCSS&q=.ltr&type=&utf8=%E2%9C%93) that requires `.ltr` css class to be defined somewhere near root of document.

it is stated in documentation but people tend to miss it. it's also an additional requirement which we can avoid.

`.ltr` should be the default case and so no `.ltr` would be required at all.
`.rtl`, when used, would override what's necessary.

**Comment by boriskor** [comment]
@argshook, I think that using HTML's [dir attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/dir) instead of classes would more suitable, as it's more semantic. WDYT?

**Comment by argshook** [comment]
@boriskor i suppose so, yes. classes were probably used just as a quick way out without much thought

**Comment by lbelinsk** [comment]
@argshook can we close this?

**Comment by argshook** [comment]
@lbelinsk maybe not yet, we still have some code that makes `.ltr` mandatory. This should also not be forgotten in any of `wix-ui` modules.

**Comment by shlomitc** [comment]
I see that we have `ltr` in the CSS only in `SideBar` component which is more or less deprecated, so we can create a task to deprecate it.

it also appears in many `exampleStandard` stories, but these should be removed as we go.

Did I miss something? if not, let's close

**Comment by argshook** [comment]
closing in favor of https://github.com/wix/wix-style-react/issues/1732
